# Get daily average values for air pollution in France from 2016-2026 using openAQ API

In [4]:
import requests
import pandas as pd 
import time

### List possible parameters (e.g. PM10, PM2.5, NO2)

In [4]:
api_url = "https://api.openaq.org/v3/parameters"

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, headers=headers)
response = response.json()

response

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 46},
 'results': [{'id': 1,
   'name': 'pm10',
   'units': 'µg/m³',
   'displayName': 'PM10',
   'description': 'Particulate matter less than 10 micrometers in diameter mass concentration'},
  {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': 'PM2.5',
   'description': 'Particulate matter less than 2.5 micrometers in diameter mass concentration'},
  {'id': 3,
   'name': 'o3',
   'units': 'µg/m³',
   'displayName': 'O₃ mass',
   'description': 'Ozone mass concentration'},
  {'id': 4,
   'name': 'co',
   'units': 'µg/m³',
   'displayName': 'CO mass',
   'description': 'Carbon Monoxide mass concentration'},
  {'id': 5,
   'name': 'no2',
   'units': 'µg/m³',
   'displayName': 'NO₂ mass',
   'description': 'Nitrogen Dioxide mass concentration'},
  {'id': 6,
   'name': 'so2',
   'units': 'µg/m³',
   'displayName': 'SO₂ mass',
   'description': 'Sulfur Dioxide mass concentration'},
  {'id': 7,
   'name': 'no2',
   'units': 'ppm',
   'displayName': 'NO₂',
   'description': 'Nitrogen Dioxide concentration'},
  {'id': 8,
   'name': 'co',
   'units': 'ppm',
   'displayName': 'CO',
   'description': 'Carbon Monoxide concentration'},
  {'id': 9,
   'name': 'so2',
   'units': 'ppm',
   'displayName': 'SO₂',
   'description': 'Sulfur Dioxide concentration'},
  {'id': 10,
   'name': 'o3',
   'units': 'ppm',
   'displayName': 'O₃',
   'description': 'Ozone concentration'},
  {'id': 11,
   'name': 'bc',
   'units': 'µg/m³',
   'displayName': 'BC',
   'description': 'Black Carbon mass concentration'},
  {'id': 15,
   'name': 'no2',
   'units': 'ppb',
   'displayName': 'NO₂',
   'description': None},
  {'id': 19,
   'name': 'pm1',
   'units': 'µg/m³',
   'displayName': 'PM1',
   'description': 'Particulate matter less than 1 micrometer in diameter mass concentration'},
  {'id': 21,
   'name': 'co2',
   'units': 'ppm',
   'displayName': 'CO₂',
   'description': 'Carbon Dioxide concentration'},
  {'id': 22,
   'name': 'wind_direction',
   'units': 'deg',
   'displayName': 'Wind direction',
   'description': 'Direction that the wind originates from'},
  {'id': 23,
   'name': 'nox',
   'units': 'ppb',
   'displayName': 'NOX',
   'description': None},
  {'id': 24,
   'name': 'no',
   'units': 'ppb',
   'displayName': 'NO',
   'description': None},
  {'id': 27,
   'name': 'nox',
   'units': 'µg/m³',
   'displayName': 'NOx mass',
   'description': 'Nitrogen Oxides mass concentration'},
  {'id': 28,
   'name': 'ch4',
   'units': 'ppm',
   'displayName': 'CH₄',
   'description': 'Methane concentration'},
  {'id': 32,
   'name': 'o3',
   'units': 'ppb',
   'displayName': 'O₃',
   'description': None},
  {'id': 33,
   'name': 'ufp',
   'units': 'particles/cm³',
   'displayName': 'UFP count',
   'description': 'Ultrafine Particles count concentration'},
  {'id': 34,
   'name': 'wind_speed',
   'units': 'm/s',
   'displayName': 'Wind speed',
   'description': 'Average wind speed in meters per second'},
  {'id': 35,
   'name': 'no',
   'units': 'ppm',
   'displayName': 'NO',
   'description': 'Nitrogen Monoxide concentration'},
  {'id': 95,
   'name': 'pressure',
   'units': 'hpa',
   'displayName': 'Atmospheric pressure',
   'description': 'Atmospheric or barometric pressure'},
  {'id': 97,
   'name': 'pm25-old',
   'units': 'ugm3',
   'displayName': None,
   'description': None},
  {'id': 98,
   'name': 'relativehumidity',
   'units': '%',
   'displayName': 'RH',
   'description': None},
  {'id': 100,
   'name': 'temperature',
   'units': 'c',
   'displayName': 'Temperature (C)',
   'description': None},
  {'id': 101,
   'name': 'so2',
   'units': 'ppb',
   'displayName': 'SO₂',
   'description': None},
  {'id': 102,
   'name': 'co',
   'units': 'ppb',
   'displayName': 'CO',
   'description': None},
  {'id': 125,
   'name': 'um003',
   'units': 'particles/cm³',
   'displayName': 'PM0.3 count',
   'description': None},
  {'id': 126,
   'name': 'um010',
   'units': 'particles/cm³',
   'displayName': 'PM1 count',
   'description': 'PM1 count'},
  {'id': 128,
   'name': 'temperature',
   'units': 'f',
   'displayName': 'Temperature (F)',
   'description': None},
  {'id': 130,
   'name': 'um025',
   'units': 'particles/cm³',
   'displayName': 'PM2.5 count',
   'description': 'PM2.5 count'},
  {'id': 132,
   'name': 'pressure',
   'units': 'mb',
   'displayName': 'Pressure',
   'description': None},
  {'id': 134,
   'name': 'humidity',
   'units': '%',
   'displayName': 'H',
   'description': None},
  {'id': 135,
   'name': 'um100',
   'units': 'particles/cm³',
   'displayName': 'PM10 count',
   'description': 'PM10 count'},
  {'id': 19840,
   'name': 'nox',
   'units': 'ppm',
   'displayName': 'NOx',
   'description': 'Nitrogen Oxides concentration'},
  {'id': 19843,
   'name': 'no',
   'units': 'µg/m³',
   'displayName': 'NO mass',
   'description': 'Nitrogen Monoxide mass concentration'},
  {'id': 19844,
   'name': 'pm4',
   'units': 'µg/m³',
   'displayName': 'PM4.0',
   'description': 'Particulate matter less than 4 micrometers in diameter mass concentration'},
  {'id': 19860,
   'name': 'pm25',
   'units': 'ppm',
   'displayName': None,
   'description': None},
  {'id': 19861,
   'name': 'bc_375',
   'units': 'ng/m³',
   'displayName': 'BC 375nm',
   'description': 'Black Carbon mass concentration 375nm '},
  {'id': 19862,
   'name': 'bc_470',
   'units': 'ng/m³',
   'displayName': 'BC 470nm',
   'description': 'Black Carbon mass concentration 470nm '},
  {'id': 19863,
   'name': 'bc_528',
   'units': 'ng/m³',
   'displayName': 'BC 528nm',
   'description': 'Black Carbon mass concentration 528nm '},
  {'id': 19864,
   'name': 'bc_625',
   'units': 'ng/m³',
   'displayName': 'BC 625nm',
   'description': 'Black Carbon mass concentration 625nm '},
  {'id': 19865,
   'name': 'bc_880',
   'units': 'ng/m³',
   'displayName': 'BC 880nm',
   'description': 'Black Carbon mass concentration 880nm '},
  {'id': 19866,
   'name': 'bc_370',
   'units': 'ng/m³',
   'displayName': 'BC 370nm',
   'description': 'Black Carbon mass concentration 375nm '}]}

# PM10

### Get 200 stations located in France that measure PM10
Stations are sorted descending by the duration of their measurements

In [48]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "FR",   # only consider stations located in France
    "parameters_id": 1,   # PM10 
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm10 = df_sorted.head(200)

df_top_pm10

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
23,2704,Saint-Lô Eglise,SAINT-LÔ,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274740, 'name': 'no µg/m³', 'paramete...","{'latitude': 49.116390000092665, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-1.084722000069518, 49.116390000092665, -1.08...",None,2016-11-21 11:00:00+00:00,2026-03-04 11:00:00+00:00
25,2707,Evreux Centre,ÉVREUX,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275240, 'name': 'no µg/m³', 'paramete...","{'latitude': 49.02133999977332, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[1.1483189995666427, 49.02133999977332, 1.1483...",None,2016-11-21 11:00:00+00:00,2026-03-04 11:00:00+00:00
26,2708,Alençon Météo-France,CERISÉ,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275085, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.445553000017455, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[0.11083299979257102, 48.445553000017455, 0.11...",None,2016-11-21 11:00:00+00:00,2026-03-04 11:00:00+00:00
33,2720,Montpellier Prés d'Arènes,MONTPELLIER,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275188, 'name': 'no µg/m³', 'paramete...","{'latitude': 43.591500000324274, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[3.886809999908339, 43.591500000324274, 3.8868...",None,2016-11-21 11:00:00+00:00,2026-03-04 11:00:00+00:00
54,3479,Gonfreville l Orcher,GONFREVILLE-L'ORCHER,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 24890, 'name': 'co µg/m³', 'parameter'...","{'latitude': 49.50273000006004, 'longitude': 0...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[0.232485999671531, 49.50273000006004, 0.23248...",None,2016-11-21 11:00:00+00:00,2026-03-04 11:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,2677,Besancon Victor Hugo,NaN,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5584, 'name': 'pm10 µg/m³', 'parameter...","{'latitude': 47.23489773654806, 'longitude': 6...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.029474220704546, 47.23489773654806, 6.02947...",None,2016-11-21 12:00:00+00:00,2016-12-05 01:00:00+00:00
14,2687,Vienne Centre,NaN,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5602, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 45.5259808277432, 'longitude': 4....","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[4.875408575196197, 45.5259808277432, 4.875408...",None,2016-11-21 12:00:00+00:00,2016-12-05 01:00:00+00:00
2,2668,MOULINS,NaN,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5572, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 46.56186359841856, 'longitude': 3...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[3.3310878208078036, 46.56186359841856, 3.3310...",None,2016-11-21 12:00:00+00:00,2016-12-01 20:00:00+00:00
1,2666,COL_OEILLON,NaN,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5567, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 45.38956220590412, 'longitude': 4...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[4.615813424391337, 45.38956220590412, 4.61581...",None,2016-11-21 12:00:00+00:00,2016-11-29 01:00:00+00:00
102,3596,Metz- Pont Grilles,METZ,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 19781, 'name': 'co µg/m³', 'parameter'...","{'latitude': 49.12508000010211, 'longitude': 6...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.181219000343986, 49.12508000010211, 6.18121...",None,2016-11-21 13:00:00+00:00,2026-03-04 11:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [49]:
rows = []

for _, station in df_top_pm10.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM10 behalten
        if sensor["parameter"]["id"] == 1:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm10_sensors = pd.DataFrame(rows)

df_pm10_sensors

     station_id               station_name  sensor_id sensor_name
0          2704            Saint-Lô Eglise       5640  pm10 µg/m³
1          2707              Evreux Centre       9841  pm10 µg/m³
2          2708       Alençon Météo-France       7954  pm10 µg/m³
3          2720  Montpellier Prés d'Arènes       5671  pm10 µg/m³
4          3479       Gonfreville l Orcher      24888  pm10 µg/m³
..          ...                        ...        ...         ...
195        2677       Besancon Victor Hugo       5584  pm10 µg/m³
196        2687              Vienne Centre       5598  pm10 µg/m³
197        2668                    MOULINS       5573  pm10 µg/m³
198        2666                COL_OEILLON       5568  pm10 µg/m³
199        3596         Metz- Pont Grilles       7939  pm10 µg/m³

[200 rows x 4 columns]

In [51]:
sensor_ids = df_pm10_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

200

[5640,
 9841,
 7954,
 5671,
 24888,
 7897,
 7755,
 7791,
 7917,
 7926,
 7942,
 7952,
 7960,
 24323,
 8214,
 8268,
 8272,
 8388,
 8501,
 9762,
 9605,
 9644,
 9649,
 9813,
 9823,
 4445295,
 15305,
 9883,
 9901,
 5668,
 8420,
 7762,
 7777,
 7993,
 8116,
 8139,
 8478,
 8514,
 8529,
 8595,
 8600,
 9704,
 8071,
 7956,
 8593,
 7906,
 7979,
 8106,
 8119,
 8343,
 8517,
 8625,
 9254,
 1312024,
 1562198,
 8191,
 7715,
 7752,
 9541,
 23228,
 9700,
 9405,
 9531,
 9687,
 9691,
 9722,
 9717,
 24620,
 9728,
 15296,
 7729,
 7732,
 9756,
 7907,
 8431,
 8151,
 9737,
 8160,
 7947,
 9724,
 9710,
 5655,
 8063,
 7948,
 7989,
 9874,
 15413,
 5641,
 8416,
 7771,
 7766,
 9771,
 5659,
 5579,
 8535,
 5603,
 5588,
 5608,
 8558,
 5660,
 7701,
 7828,
 8572,
 11547734,
 7830,
 7831,
 7834,
 7832,
 7833,
 7837,
 7839,
 8189,
 7925,
 23952,
 7999,
 8002,
 8009,
 8013,
 8026,
 8031,
 8043,
 8068,
 8075,
 8081,
 8131,
 8134,
 8141,
 8159,
 8184,
 8256,
 8294,
 8301,
 8312,
 8322,
 8326,
 8331,
 8359,
 8366,
 8369,
 8403,
 8408,
 8453,
 8483,
 8496,
 8521,
 8528,
 8554,
 8584,
 8613,
 8630,
 8637,
 9538,
 9544,
 9547,
 9583,
 9590,
 9593,
 9597,
 9599,
 9608,
 9647,
 9669,
 9698,
 9709,
 12542094,
 9766,
 7840,
 8297,
 9614,
 8406,
 8352,
 9564,
 8525,
 8319,
 8378,
 9662,
 8435,
 8463,
 9796,
 8510,
 8371,
 8471,
 5653,
 8642,
 8093,
 8615,
 8457,
 5593,
 9852,
 8304,
 8618,
 8078,
 8487,
 8057,
 8108,
 5584,
 5598,
 5573,
 5568,
 7939]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 5640: Seite 1, 1000 Ergebnisse
Sensor 5640: Seite 2, 1000 Ergebnisse
Sensor 5640: Seite 3, 820 Ergebnisse
Sensor 9841: Seite 1, 1000 Ergebnisse
Sensor 9841: Seite 2, 1000 Ergebnisse
Sensor 9841: Seite 3, 836 Ergebnisse
Sensor 7954: Seite 1, 1000 Ergebnisse
Sensor 7954: Seite 2, 1000 Ergebnisse
Sensor 7954: Seite 3, 862 Ergebnisse
Sensor 5671: Seite 1, 1000 Ergebnisse
Sensor 5671: Seite 2, 1000 Ergebnisse
Sensor 5671: Seite 3, 841 Ergebnisse
Sensor 24888: Seite 1, 1000 Ergebnisse
Sensor 24888: Seite 2, 1000 Ergebnisse
Sensor 24888: Seite 3, 188 Ergebnisse
Sensor 7897: Seite 1, 1000 Ergebnisse
Sensor 7897: Seite 2, 1000 Ergebnisse
Sensor 7897: Seite 3, 772 Ergebnisse
Sensor 7755: Seite 1, 612 Ergebnisse
Sensor 7791: Seite 1, 1000 Ergebnisse
Sensor 7791: Seite 2, 1000 Ergebnisse
Sensor 7791: Seite 3, 635 Ergebnisse
Sensor 7917: Seite 1, 1000 Ergebnisse
Sensor 7917: Seite 2, 1000 Ergebnisse
Sensor 7917: Seite 3, 656 Ergebnisse
Sensor 7926: Seite 1, 1000 Ergebnisse
Sensor 7926: Seite 2, 1000 Ergebnisse
Sensor 7926: Seite 3, 921 Ergebnisse
Sensor 7942: Seite 1, 1000 Ergebnisse
Sensor 7942: Seite 2, 1000 Ergebnisse
Sensor 7942: Seite 3, 846 Ergebnisse
Sensor 7952: Seite 1, 1000 Ergebnisse
Sensor 7952: Seite 2, 1000 Ergebnisse
Sensor 7952: Seite 3, 774 Ergebnisse
Sensor 7960: Seite 1, 1000 Ergebnisse
Sensor 7960: Seite 2, 1000 Ergebnisse
Sensor 7960: Seite 3, 829 Ergebnisse
Sensor 24323: Seite 1, 1000 Ergebnisse
Sensor 24323: Seite 2, 1000 Ergebnisse
Sensor 24323: Seite 3, 593 Ergebnisse
Sensor 8214: Seite 1, 1000 Ergebnisse
Sensor 8214: Seite 2, 953 Ergebnisse
Sensor 8272: Seite 1, 1000 Ergebnisse
Sensor 8272: Seite 2, 1000 Ergebnisse
Sensor 8272: Seite 3, 895 Ergebnisse
Sensor 8388: Seite 1, 1000 Ergebnisse
Sensor 8388: Seite 2, 1000 Ergebnisse
Sensor 8388: Seite 3, 898 Ergebnisse
Sensor 8501: Seite 1, 1000 Ergebnisse
Sensor 8501: Seite 2, 1000 Ergebnisse
Sensor 8501: Seite 3, 778 Ergebnisse
Sensor 9762: Seite 1, 1000 Ergebnisse
Sensor 9762: Seite 2, 1000 Ergebnisse
Sensor 9762: Seite 3, 962 Ergebnisse
Sensor 9605: Seite 1, 1000 Ergebnisse
Sensor 9605: Seite 2, 1000 Ergebnisse
Sensor 9605: Seite 3, 947 Ergebnisse
Sensor 9644: Seite 1, 1000 Ergebnisse
Sensor 9644: Seite 2, 1000 Ergebnisse
Sensor 9644: Seite 3, 901 Ergebnisse
Sensor 9649: Seite 1, 1000 Ergebnisse
Sensor 9649: Seite 2, 1000 Ergebnisse
Sensor 9649: Seite 3, 940 Ergebnisse
Sensor 9813: Seite 1, 1000 Ergebnisse
Sensor 9813: Seite 2, 1000 Ergebnisse
Sensor 9813: Seite 3, 878 Ergebnisse
Sensor 9823: Seite 1, 1000 Ergebnisse
Sensor 9823: Seite 2, 1000 Ergebnisse
Sensor 9823: Seite 3, 819 Ergebnisse
Sensor 4445295: Seite 1, 826 Ergebnisse
Sensor 15305: Seite 1, 1000 Ergebnisse
Sensor 15305: Seite 2, 1000 Ergebnisse
Sensor 15305: Seite 3, 490 Ergebnisse
Sensor 9883: Seite 1, 1000 Ergebnisse
Sensor 9883: Seite 2, 1000 Ergebnisse
Sensor 9883: Seite 3, 985 Ergebnisse
Sensor 9901: Seite 1, 1000 Ergebnisse
Sensor 9901: Seite 2, 1000 Ergebnisse
Sensor 9901: Seite 3, 821 Ergebnisse
Sensor 5668: Seite 1, 1000 Ergebnisse
Sensor 5668: Seite 2, 1000 Ergebnisse
Sensor 5668: Seite 3, 682 Ergebnisse
Sensor 8420: Seite 1, 1000 Ergebnisse
Sensor 8420: Seite 2, 1000 Ergebnisse
Sensor 8420: Seite 3, 856 Ergebnisse
Sensor 7762: Seite 1, 1000 Ergebnisse
Sensor 7762: Seite 2, 1000 Ergebnisse
Sensor 7762: Seite 3, 304 Ergebnisse
Sensor 7777: Seite 1, 1000 Ergebnisse
Sensor 7777: Seite 2, 1000 Ergebnisse
Sensor 7777: Seite 3, 516 Ergebnisse
Sensor 7993: Seite 1, 1000 Ergebnisse
Sensor 7993: Seite 2, 1000 Ergebnisse
Sensor 7993: Seite 3, 543 Ergebnisse
Sensor 8116: Seite 1, 1000 Ergebnisse
Sensor 8116: Seite 2, 1000 Ergebnisse
Sensor 8116: Seite 3, 505 Ergebnisse
Sensor 8139: Seite 1, 1000 Ergebnisse
Sensor 8139: Seite 2, 1000 Ergebnisse
Sensor 8139: Seite 3, 669 Ergebnisse
Sensor 8478: Seite 1, 1000 Ergebnisse
Sensor 8478: Seite 2, 1000 Ergebnisse
Sensor 8478: Seite 3, 621 Ergebnisse
Sensor 8514: Seite 1, 1000 Ergebnisse
Sensor 8514: Seite 2, 1000 Ergebnisse
Sensor 8514: Seite 3, 613 Ergebnisse
Sensor 8529: Seite 1, 1000 Ergebnisse
Sensor 8529: Seite 2, 1000 Ergebnisse
Sensor 8529: Seite 3, 668 Ergebnisse
Sensor 8595: Seite 1, 1000 Ergebnisse
Sensor 8595: Seite 2, 1000 Ergebnisse
Sensor 8595: Seite 3, 613 Ergebnisse
Sensor 8600: Seite 1, 1000 Ergebnisse
Sensor 8600: Seite 2, 1000 Ergebnisse
Sensor 8600: Seite 3, 624 Ergebnisse
Sensor 9704: Seite 1, 1000 Ergebnisse
Sensor 9704: Seite 2, 1000 Ergebnisse
Sensor 9704: Seite 3, 432 Ergebnisse
Sensor 8071: Seite 1, 1000 Ergebnisse
Sensor 8071: Seite 2, 1000 Ergebnisse
Sensor 8071: Seite 3, 440 Ergebnisse
Sensor 7956: Seite 1, 1000 Ergebnisse
Sensor 7956: Seite 2, 1000 Ergebnisse
Sensor 7956: Seite 3, 207 Ergebnisse
Sensor 8593: Seite 1, 1000 Ergebnisse
Sensor 8593: Seite 2, 1000 Ergebnisse
Sensor 8593: Seite 3, 275 Ergebnisse
Sensor 7906: Seite 1, 1000 Ergebnisse
Sensor 7906: Seite 2, 1000 Ergebnisse
Sensor 7906: Seite 3, 209 Ergebnisse
Sensor 7979: Seite 1, 1000 Ergebnisse
Sensor 7979: Seite 2, 1000 Ergebnisse
Sensor 7979: Seite 3, 277 Ergebnisse
Sensor 8106: Seite 1, 1000 Ergebnisse
Sensor 8106: Seite 2, 1000 Ergebnisse
Sensor 8106: Seite 3, 219 Ergebnisse
Sensor 8119: Seite 1, 1000 Ergebnisse
Sensor 8119: Seite 2, 1000 Ergebnisse
Sensor 8119: Seite 3, 264 Ergebnisse
Sensor 8343: Seite 1, 1000 Ergebnisse
Sensor 8343: Seite 2, 1000 Ergebnisse
Sensor 8343: Seite 3, 263 Ergebnisse
Sensor 8517: Seite 1, 1000 Ergebnisse
Sensor 8517: Seite 2, 1000 Ergebnisse
Sensor 8517: Seite 3, 267 Ergebnisse
Sensor 8625: Seite 1, 1000 Ergebnisse
Sensor 8625: Seite 2, 1000 Ergebnisse
Sensor 8625: Seite 3, 289 Ergebnisse
Sensor 9254: Seite 1, 1000 Ergebnisse
Sensor 9254: Seite 2, 957 Ergebnisse
Sensor 1312024: Seite 1, 699 Ergebnisse
Sensor 1562198: Seite 1, 607 Ergebnisse
Sensor 8191: Seite 1, 1000 Ergebnisse
Sensor 8191: Seite 2, 977 Ergebnisse
Sensor 7715: Seite 1, 701 Ergebnisse
Sensor 7752: Seite 1, 1000 Ergebnisse
Sensor 7752: Seite 2, 906 Ergebnisse
Sensor 9541: Seite 1, 1000 Ergebnisse
Sensor 9541: Seite 2, 1000 Ergebnisse
Sensor 9541: Seite 3, 191 Ergebnisse
Sensor 23228: Seite 1, 1000 Ergebnisse
Sensor 23228: Seite 2, 514 Ergebnisse
Sensor 9700: Seite 1, 1000 Ergebnisse
Sensor 9700: Seite 2, 867 Ergebnisse
Sensor 9405: Seite 1, 1000 Ergebnisse
Sensor 9405: Seite 2, 1000 Ergebnisse
Sensor 9405: Seite 3, 102 Ergebnisse
Sensor 9531: Seite 1, 1000 Ergebnisse
Sensor 9531: Seite 2, 1000 Ergebnisse
Sensor 9531: Seite 3, 102 Ergebnisse
Sensor 9687: Seite 1, 1000 Ergebnisse
Sensor 9687: Seite 2, 1000 Ergebnisse
Sensor 9687: Seite 3, 128 Ergebnisse
Sensor 9691: Seite 1, 1000 Ergebnisse
Sensor 9691: Seite 2, 811 Ergebnisse
Sensor 9722: Seite 1, 1000 Ergebnisse
Sensor 9717: Seite 1, 1000 Ergebnisse
Sensor 9717: Seite 2, 1000 Ergebnisse
Sensor 9717: Seite 3, 102 Ergebnisse
Sensor 24620: Seite 1, 1000 Ergebnisse
Sensor 24620: Seite 2, 937 Ergebnisse
Sensor 9728: Seite 1, 1000 Ergebnisse
Sensor 9728: Seite 2, 1000 Ergebnisse
Sensor 9728: Seite 3, 12 Ergebnisse
Sensor 15296: Seite 1, 1000 Ergebnisse
Sensor 15296: Seite 2, 1000 Ergebnisse
Sensor 15296: Seite 3, 27 Ergebnisse
Sensor 7729: Seite 1, 542 Ergebnisse
Sensor 7732: Seite 1, 1000 Ergebnisse
Sensor 7732: Seite 2, 1000 Ergebnisse
Sensor 7732: Seite 3, 64 Ergebnisse
Sensor 9756: Seite 1, 1000 Ergebnisse
Sensor 9756: Seite 2, 1000 Ergebnisse
Sensor 9756: Seite 3, 286 Ergebnisse
Sensor 7907: Seite 1, 1000 Ergebnisse
Sensor 7907: Seite 2, 1000 Ergebnisse
Sensor 7907: Seite 3, 141 Ergebnisse
Sensor 8431: Seite 1, 1000 Ergebnisse
Sensor 8431: Seite 2, 1000 Ergebnisse
Sensor 8431: Seite 3, 162 Ergebnisse
Sensor 8151: Seite 1, 1000 Ergebnisse
Sensor 8151: Seite 2, 1000 Ergebnisse
Sensor 8151: Seite 3, 36 Ergebnisse
Sensor 9737: Seite 1, 1000 Ergebnisse
Sensor 9737: Seite 2, 924 Ergebnisse
Sensor 8160: Seite 1, 1000 Ergebnisse
Sensor 8160: Seite 2, 647 Ergebnisse
Sensor 7947: Seite 1, 1000 Ergebnisse
Sensor 7947: Seite 2, 788 Ergebnisse
Sensor 9724: Seite 1, 1000 Ergebnisse
Sensor 9724: Seite 2, 799 Ergebnisse
Sensor 9710: Seite 1, 1000 Ergebnisse
Sensor 9710: Seite 2, 742 Ergebnisse
Sensor 5655: Seite 1, 1000 Ergebnisse
Sensor 5655: Seite 2, 251 Ergebnisse
Sensor 8063: Seite 1, 1000 Ergebnisse
Sensor 8063: Seite 2, 373 Ergebnisse
Sensor 7948: Seite 1, 1000 Ergebnisse
Sensor 7948: Seite 2, 346 Ergebnisse
Sensor 7989: Seite 1, 1000 Ergebnisse
Sensor 7989: Seite 2, 92 Ergebnisse
Sensor 9874: Seite 1, 1000 Ergebnisse
Sensor 9874: Seite 2, 279 Ergebnisse
Sensor 15413: Seite 1, 678 Ergebnisse
Sensor 5641: Seite 1, 13 Ergebnisse
Sensor 8416: Seite 1, 573 Ergebnisse
Sensor 7771: Seite 1, 132 Ergebnisse
Sensor 7766: Seite 1, 78 Ergebnisse
Sensor 9771: Seite 1, 147 Ergebnisse
Sensor 5659: Seite 1, 13 Ergebnisse
Sensor 5579: Seite 1, 1000 Ergebnisse
Sensor 5579: Seite 2, 1000 Ergebnisse
Sensor 5579: Seite 3, 389 Ergebnisse
Sensor 8535: Seite 1, 1000 Ergebnisse
Sensor 8535: Seite 2, 1000 Ergebnisse
Sensor 8535: Seite 3, 995 Ergebnisse
Sensor 5603: Seite 1, 1000 Ergebnisse
Sensor 5603: Seite 2, 1000 Ergebnisse
Sensor 5603: Seite 3, 619 Ergebnisse
Sensor 5588: Seite 1, 1000 Ergebnisse
Sensor 5588: Seite 2, 1000 Ergebnisse
Sensor 5588: Seite 3, 679 Ergebnisse
Sensor 5608: Seite 1, 1000 Ergebnisse
Sensor 5608: Seite 2, 1000 Ergebnisse
Sensor 5608: Seite 3, 617 Ergebnisse
Sensor 8558: Seite 1, 1000 Ergebnisse
Sensor 8558: Seite 2, 1000 Ergebnisse
Sensor 8558: Seite 3, 799 Ergebnisse
Sensor 5660: Seite 1, 1000 Ergebnisse
Sensor 5660: Seite 2, 943 Ergebnisse
Sensor 7701: Seite 1, 1000 Ergebnisse
Sensor 7701: Seite 2, 1000 Ergebnisse
Sensor 7701: Seite 3, 464 Ergebnisse
Sensor 7828: Seite 1, 1000 Ergebnisse
Sensor 7828: Seite 2, 1000 Ergebnisse
Sensor 7828: Seite 3, 706 Ergebnisse
Sensor 8572: Seite 1, 1000 Ergebnisse
Sensor 8572: Seite 2, 1000 Ergebnisse
Sensor 8572: Seite 3, 553 Ergebnisse
Sensor 11547734: Seite 1, 401 Ergebnisse
Sensor 7830: Seite 1, 1000 Ergebnisse
Sensor 7830: Seite 2, 1000 Ergebnisse
Sensor 7830: Seite 3, 818 Ergebnisse
Sensor 7831: Seite 1, 1000 Ergebnisse
Sensor 7831: Seite 2, 1000 Ergebnisse
Sensor 7831: Seite 3, 834 Ergebnisse
Sensor 7834: Seite 1, 1000 Ergebnisse
Sensor 7834: Seite 2, 1000 Ergebnisse
Sensor 7834: Seite 3, 714 Ergebnisse
Sensor 7832: Seite 1, 1000 Ergebnisse
Sensor 7832: Seite 2, 1000 Ergebnisse
Sensor 7832: Seite 3, 800 Ergebnisse
Sensor 7833: Seite 1, 1000 Ergebnisse
Sensor 7833: Seite 2, 1000 Ergebnisse
Sensor 7833: Seite 3, 840 Ergebnisse
Sensor 7837: Seite 1, 1000 Ergebnisse
Sensor 7837: Seite 2, 629 Ergebnisse
Sensor 7839: Seite 1, 1000 Ergebnisse
Sensor 7839: Seite 2, 1000 Ergebnisse
Sensor 7839: Seite 3, 822 Ergebnisse
Sensor 8189: Seite 1, 1000 Ergebnisse
Sensor 8189: Seite 2, 1000 Ergebnisse
Sensor 8189: Seite 3, 633 Ergebnisse
Sensor 7925: Seite 1, 1000 Ergebnisse
Sensor 7925: Seite 2, 1000 Ergebnisse
Sensor 7925: Seite 3, 934 Ergebnisse
Sensor 23952: Seite 1, 1000 Ergebnisse
Sensor 23952: Seite 2, 1000 Ergebnisse
Sensor 23952: Seite 3, 169 Ergebnisse
Sensor 7999: Seite 1, 1000 Ergebnisse
Sensor 7999: Seite 2, 1000 Ergebnisse
Sensor 7999: Seite 3, 902 Ergebnisse
Sensor 8002: Seite 1, 1000 Ergebnisse
Sensor 8002: Seite 2, 1000 Ergebnisse
Sensor 8002: Seite 3, 704 Ergebnisse
Sensor 8009: Seite 1, 1000 Ergebnisse
Sensor 8009: Seite 2, 1000 Ergebnisse
Sensor 8009: Seite 3, 464 Ergebnisse
Sensor 8013: Seite 1, 1000 Ergebnisse
Sensor 8013: Seite 2, 1000 Ergebnisse
Sensor 8013: Seite 3, 685 Ergebnisse
Sensor 8026: Seite 1, 1000 Ergebnisse
Sensor 8026: Seite 2, 1000 Ergebnisse
Sensor 8026: Seite 3, 971 Ergebnisse
Sensor 8043: Seite 1, 1000 Ergebnisse
Sensor 8043: Seite 2, 1000 Ergebnisse
Sensor 8043: Seite 3, 869 Ergebnisse
Sensor 8068: Seite 1, 1000 Ergebnisse
Sensor 8068: Seite 2, 622 Ergebnisse
Sensor 8075: Seite 1, 1000 Ergebnisse
Sensor 8075: Seite 2, 1000 Ergebnisse
Sensor 8075: Seite 3, 563 Ergebnisse
Sensor 8081: Seite 1, 1000 Ergebnisse
Sensor 8081: Seite 2, 1000 Ergebnisse
Sensor 8081: Seite 3, 718 Ergebnisse
Sensor 8131: Seite 1, 1000 Ergebnisse
Sensor 8131: Seite 2, 462 Ergebnisse
Sensor 8134: Seite 1, 1000 Ergebnisse
Sensor 8134: Seite 2, 1000 Ergebnisse
Sensor 8134: Seite 3, 699 Ergebnisse
Sensor 8141: Seite 1, 1000 Ergebnisse
Sensor 8141: Seite 2, 1000 Ergebnisse
Sensor 8141: Seite 3, 361 Ergebnisse
Sensor 8159: Seite 1, 1000 Ergebnisse
Sensor 8159: Seite 2, 1000 Ergebnisse
Sensor 8159: Seite 3, 930 Ergebnisse
Sensor 8184: Seite 1, 1000 Ergebnisse
Sensor 8184: Seite 2, 1000 Ergebnisse
Sensor 8184: Seite 3, 185 Ergebnisse
Sensor 8256: Seite 1, 1000 Ergebnisse
Sensor 8256: Seite 2, 1000 Ergebnisse
Sensor 8256: Seite 3, 331 Ergebnisse
Sensor 8294: Seite 1, 1000 Ergebnisse
Sensor 8294: Seite 2, 1000 Ergebnisse
Sensor 8294: Seite 3, 569 Ergebnisse
Sensor 8301: Seite 1, 1000 Ergebnisse
Sensor 8312: Seite 1, 1000 Ergebnisse
Sensor 8312: Seite 2, 1000 Ergebnisse
Sensor 8312: Seite 3, 549 Ergebnisse
Sensor 8322: Seite 1, 1000 Ergebnisse
Sensor 8322: Seite 2, 1000 Ergebnisse
Sensor 8322: Seite 3, 962 Ergebnisse
Sensor 8326: Seite 1, 1000 Ergebnisse
Sensor 8326: Seite 2, 1000 Ergebnisse
Sensor 8326: Seite 3, 983 Ergebnisse
Sensor 8331: Seite 1, 1000 Ergebnisse
Sensor 8331: Seite 2, 1000 Ergebnisse
Sensor 8331: Seite 3, 572 Ergebnisse
Sensor 8359: Seite 1, 1000 Ergebnisse
Sensor 8359: Seite 2, 1000 Ergebnisse
Sensor 8359: Seite 3, 710 Ergebnisse
Sensor 8366: Seite 1, 1000 Ergebnisse
Sensor 8366: Seite 2, 1000 Ergebnisse
Sensor 8366: Seite 3, 822 Ergebnisse
Sensor 8369: Seite 1, 1000 Ergebnisse
Sensor 8369: Seite 2, 1000 Ergebnisse
Sensor 8369: Seite 3, 898 Ergebnisse
Sensor 8403: Seite 1, 1000 Ergebnisse
Sensor 8403: Seite 2, 1000 Ergebnisse
Sensor 8403: Seite 3, 665 Ergebnisse
Sensor 8408: Seite 1, 1000 Ergebnisse
Sensor 8408: Seite 2, 1000 Ergebnisse
Sensor 8408: Seite 3, 615 Ergebnisse
Sensor 8453: Seite 1, 1000 Ergebnisse
Sensor 8453: Seite 2, 1000 Ergebnisse
Sensor 8453: Seite 3, 922 Ergebnisse
Sensor 8483: Seite 1, 1000 Ergebnisse
Sensor 8483: Seite 2, 1000 Ergebnisse
Sensor 8483: Seite 3, 856 Ergebnisse
Sensor 8496: Seite 1, 955 Ergebnisse
Sensor 8521: Seite 1, 1000 Ergebnisse
Sensor 8521: Seite 2, 1000 Ergebnisse
Sensor 8521: Seite 3, 70 Ergebnisse
Sensor 8528: Seite 1, 1000 Ergebnisse
Sensor 8528: Seite 2, 1000 Ergebnisse
Sensor 8528: Seite 3, 939 Ergebnisse
Sensor 8554: Seite 1, 1000 Ergebnisse
Sensor 8554: Seite 2, 1000 Ergebnisse
Sensor 8554: Seite 3, 583 Ergebnisse
Sensor 8584: Seite 1, 1000 Ergebnisse
Sensor 8584: Seite 2, 1000 Ergebnisse
Sensor 8584: Seite 3, 498 Ergebnisse
Sensor 8613: Seite 1, 1000 Ergebnisse
Sensor 8613: Seite 2, 1000 Ergebnisse
Sensor 8613: Seite 3, 644 Ergebnisse
Sensor 8630: Seite 1, 1000 Ergebnisse
Sensor 8630: Seite 2, 1000 Ergebnisse
Sensor 8630: Seite 3, 1000 Ergebnisse
Sensor 8630: Seite 4, 8 Ergebnisse
Sensor 8637: Seite 1, 1000 Ergebnisse
Sensor 8637: Seite 2, 1000 Ergebnisse
Sensor 8637: Seite 3, 547 Ergebnisse
Sensor 9538: Seite 1, 1000 Ergebnisse
Sensor 9538: Seite 2, 1000 Ergebnisse
Sensor 9538: Seite 3, 970 Ergebnisse
Sensor 9544: Seite 1, 1000 Ergebnisse
Sensor 9544: Seite 2, 1000 Ergebnisse
Sensor 9544: Seite 3, 960 Ergebnisse
Sensor 9547: Seite 1, 1000 Ergebnisse
Sensor 9547: Seite 2, 1000 Ergebnisse
Sensor 9547: Seite 3, 960 Ergebnisse
Sensor 9583: Seite 1, 1000 Ergebnisse
Sensor 9583: Seite 2, 1000 Ergebnisse
Sensor 9583: Seite 3, 944 Ergebnisse
Sensor 9590: Seite 1, 1000 Ergebnisse
Sensor 9590: Seite 2, 1000 Ergebnisse
Sensor 9590: Seite 3, 976 Ergebnisse
Sensor 9593: Seite 1, 1000 Ergebnisse
Sensor 9593: Seite 2, 912 Ergebnisse
Sensor 9597: Seite 1, 1000 Ergebnisse
Sensor 9597: Seite 2, 1000 Ergebnisse
Sensor 9597: Seite 3, 972 Ergebnisse
Sensor 9599: Seite 1, 1000 Ergebnisse
Sensor 9599: Seite 2, 1000 Ergebnisse
Sensor 9599: Seite 3, 968 Ergebnisse
Sensor 9608: Seite 1, 886 Ergebnisse
Sensor 9647: Seite 1, 1000 Ergebnisse
Sensor 9647: Seite 2, 1000 Ergebnisse
Sensor 9647: Seite 3, 1000 Ergebnisse
Sensor 9647: Seite 4, 18 Ergebnisse
Sensor 9669: Seite 1, 1000 Ergebnisse
Sensor 9669: Seite 2, 1000 Ergebnisse
Sensor 9669: Seite 3, 1000 Ergebnisse
Sensor 9669: Seite 4, 19 Ergebnisse
Sensor 9698: Seite 1, 1000 Ergebnisse
Sensor 9698: Seite 2, 1000 Ergebnisse
Sensor 9698: Seite 3, 954 Ergebnisse
Sensor 9709: Seite 1, 1000 Ergebnisse
Sensor 9709: Seite 2, 1000 Ergebnisse
Sensor 9709: Seite 3, 816 Ergebnisse
Sensor 12542094: Seite 1, 344 Ergebnisse
Sensor 9766: Seite 1, 1000 Ergebnisse
Sensor 9766: Seite 2, 1000 Ergebnisse
Sensor 9766: Seite 3, 941 Ergebnisse
Sensor 7840: Seite 1, 1000 Ergebnisse
Sensor 7840: Seite 2, 1000 Ergebnisse
Sensor 7840: Seite 3, 846 Ergebnisse
Sensor 8297: Seite 1, 1000 Ergebnisse
Sensor 8297: Seite 2, 1000 Ergebnisse
Sensor 8297: Seite 3, 787 Ergebnisse
Sensor 9614: Seite 1, 1000 Ergebnisse
Sensor 9614: Seite 2, 1000 Ergebnisse
Sensor 9614: Seite 3, 1000 Ergebnisse
Sensor 9614: Seite 4, 4 Ergebnisse
Sensor 8406: Seite 1, 1000 Ergebnisse
Sensor 8406: Seite 2, 528 Ergebnisse
Sensor 8352: Seite 1, 1000 Ergebnisse
Sensor 8352: Seite 2, 1000 Ergebnisse
Sensor 8352: Seite 3, 434 Ergebnisse
Sensor 9564: Seite 1, 1000 Ergebnisse
Sensor 9564: Seite 2, 1000 Ergebnisse
Sensor 9564: Seite 3, 839 Ergebnisse
Sensor 8525: Seite 1, 1000 Ergebnisse
Sensor 8525: Seite 2, 1000 Ergebnisse
Sensor 8525: Seite 3, 256 Ergebnisse
Sensor 8319: Seite 1, 1000 Ergebnisse
Sensor 8319: Seite 2, 1000 Ergebnisse
Sensor 8319: Seite 3, 485 Ergebnisse
Sensor 8378: Seite 1, 1000 Ergebnisse
Sensor 8378: Seite 2, 1000 Ergebnisse
Sensor 8378: Seite 3, 455 Ergebnisse
Sensor 9662: Seite 1, 1000 Ergebnisse
Sensor 9662: Seite 2, 1000 Ergebnisse
Sensor 9662: Seite 3, 455 Ergebnisse
Sensor 8435: Seite 1, 1000 Ergebnisse
Sensor 8435: Seite 2, 902 Ergebnisse
Sensor 8463: Seite 1, 1000 Ergebnisse
Sensor 8463: Seite 2, 1000 Ergebnisse
Sensor 8463: Seite 3, 229 Ergebnisse
Sensor 9796: Seite 1, 1000 Ergebnisse
Sensor 9796: Seite 2, 1000 Ergebnisse
Sensor 9796: Seite 3, 61 Ergebnisse
Sensor 8510: Seite 1, 1000 Ergebnisse
Sensor 8510: Seite 2, 1000 Ergebnisse
Sensor 8510: Seite 3, 248 Ergebnisse
Sensor 8371: Seite 1, 1000 Ergebnisse
Sensor 8371: Seite 2, 1000 Ergebnisse
Sensor 8371: Seite 3, 56 Ergebnisse
Sensor 8471: Seite 1, 1000 Ergebnisse
Sensor 8471: Seite 2, 838 Ergebnisse
Sensor 5653: Seite 1, 1000 Ergebnisse
Sensor 5653: Seite 2, 290 Ergebnisse
Sensor 8642: Seite 1, 1000 Ergebnisse
Sensor 8642: Seite 2, 453 Ergebnisse
Sensor 8093: Seite 1, 1000 Ergebnisse
Sensor 8093: Seite 2, 480 Ergebnisse
Sensor 8615: Seite 1, 1000 Ergebnisse
Sensor 8615: Seite 2, 179 Ergebnisse
Sensor 8457: Seite 1, 432 Ergebnisse
Sensor 5593: Seite 1, 580 Ergebnisse
Sensor 9852: Seite 1, 642 Ergebnisse
Sensor 8304: Seite 1, 204 Ergebnisse
Sensor 8618: Seite 1, 267 Ergebnisse
Sensor 8078: Seite 1, 232 Ergebnisse
Sensor 8487: Seite 1, 231 Ergebnisse
Sensor 8057: Seite 1, 226 Ergebnisse
Sensor 8108: Seite 1, 75 Ergebnisse
Sensor 5584: Seite 1, 11 Ergebnisse
Sensor 5598: Seite 1, 9 Ergebnisse
Sensor 5573: Seite 1, 9 Ergebnisse
Sensor 5568: Seite 1, 4 Ergebnisse
Sensor 7939: Seite 1, 1000 Ergebnisse
Sensor 7939: Seite 2, 1000 Ergebnisse
Sensor 7939: Seite 3, 959 Ergebnisse
418917

[{'date': '2016-11-21', 'value': 7.775},
 {'date': '2016-11-22', 'value': 18.214285714285715},
 {'date': '2016-11-23', 'value': 21.97222222222222},
 {'date': '2016-11-25', 'value': 30.0},
 {'date': '2016-11-26', 'value': 37.20454545454545},
 {'date': '2016-11-27', 'value': 21.053571428571427},
 {'date': '2016-11-28', 'value': 16.25},
 {'date': '2016-11-29', 'value': 16.5},
 {'date': '2016-11-30', 'value': 50.46875},
 {'date': '2016-12-01', 'value': 29.916666666666668},
 {'date': '2016-12-03', 'value': 25.47222222222222},
 {'date': '2016-12-04', 'value': 31.865384615384617},
 {'date': '2016-12-05', 'value': 32.6},
 {'date': '2017-02-18', 'value': 28.579375000000002},
 {'date': '2017-02-19', 'value': 25.664166666666663},
 {'date': '2017-02-20', 'value': 7.357500000000002},
 {'date': '2017-02-21', 'value': 11.878749999999998},
 {'date': '2017-02-22', 'value': 11.93},
 {'date': '2017-02-23', 'value': 23.449130434782607},
 {'date': '2017-02-24', 'value': 27.82875},
 {'date': '2017-02-25', 'value': 17.535},
 {'date': '2017-02-26', 'value': 10.215},
 {'date': '2017-02-27', 'value': 4.804583333333334},
 {'date': '2017-02-28', 'value': 9.589583333333334},
 {'date': '2017-03-01', 'value': 15.420416666666666},
 {'date': '2017-03-02', 'value': 26.118333333333336},
 {'date': '2017-03-03', 'value': 18.87958333333333},
 {'date': '2017-03-04', 'value': 11.200416666666667},
 {'date': '2017-03-05', 'value': 14.312916666666666},
 {'date': '2017-03-06', 'value': 17.532857142857146},
 {'date': '2017-03-07', 'value': 13.294347826086954},
 {'date': '2017-03-08', 'value': 4.83375},
 {'date': '2017-03-09', 'value': 5.264166666666665},
 {'date': '2017-03-10', 'value': 10.016666666666664},
 {'date': '2017-03-12', 'value': 13.16277777777778},
 {'date': '2017-03-13', 'value': 13.477083333333328},
 {'date': '2017-03-14', 'value': 23.216666666666665},
 {'date': '2017-03-15', 'value': 17.985833333333332},
 {'date': '2017-03-16', 'value': 28.24875},
 {'date': '2017-03-17', 'value': 25.575833333333332},
 {'date': '2017-03-18', 'value': 15.472083333333332},
 {'date': '2017-03-19', 'value': 10.43125},
 {'date': '2017-03-20', 'value': 9.33875},
 {'date': '2017-03-21', 'value': 18.68875},
 {'date': '2017-03-22', 'value': 10.13125},
 {'date': '2017-03-23', 'value': 13.355416666666665},
 {'date': '2017-03-24', 'value': 24.18},
 {'date': '2017-03-27', 'value': 42.920434782608694},
 {'date': '2017-03-28', 'value': 24.07},
 {'date': '2017-03-29', 'value': 19.90421052631579},
 {'date': '2017-03-30', 'value': 22.77416666666667},
 {'date': '2017-03-31', 'value': 18.788749999999997},
 {'date': '2017-04-01', 'value': 18.592916666666664},
 {'date': '2017-04-02', 'value': 17.175416666666667},
 {'date': '2017-04-03', 'value': 23.66333333333333},
 {'date': '2017-04-04', 'value': 17.897083333333335},
 {'date': '2017-04-05', 'value': 25.079583333333332},
 {'date': '2017-04-06', 'value': 34.232916666666675},
 {'date': '2017-04-07', 'value': 38.055416666666666},
 {'date': '2017-04-08', 'value': 48.628750000000004},
 {'date': '2017-04-09', 'value': 27.870833333333334},
 {'date': '2017-04-10', 'value': 23.47333333333333},
 {'date': '2017-04-11', 'value': 18.95875},
 {'date': '2017-04-12', 'value': 39.100833333333334},
 {'date': '2017-04-13', 'value': 17.215416666666666},
 {'date': '2017-04-14', 'value': 19.83625},
 {'date': '2017-04-15', 'value': 11.29208333333333},
 {'date': '2017-04-16', 'value': 12.11208333333333},
 {'date': '2017-04-17', 'value': 12.718750000000002},
 {'date': '2017-04-18', 'value': 14.608999999999998},
 {'date': '2017-04-19', 'value': 15.091818181818185},
 {'date': '2017-04-20', 'value': 25.604583333333338},
 {'date': '2017-04-21', 'value': 30.668333333333333},
 {'date': '2017-04-22', 'value': 24.225416666666664},
 {'date': '2017-04-23', 'value': 20.14},
 {'date': '2017-04-24', 'value': 27.60181818181818},
 {'date': '2017-04-25', 'value': 13.376666666666665},
 {'date': '2017-04-26', 'value': 10.536363636363635},
 {'date': '2017-04-28', 'value': 7.2749999999999995},
 {'date': '2017-04-29', 'value': 14.732608695652177},
 {'date': '2017-05-02', 'value': 9.547142857142855},
 {'date': '2017-05-03', 'value': 14.217999999999998},
 {'date': '2017-05-04', 'value': 20.018333333333334},
 {'date': '2017-05-10', 'value': 32.964999999999996},
 {'date': '2017-05-11', 'value': 11.939565217391305},
 {'date': '2017-05-12', 'value': 7.762222222222222},
 {'date': '2017-05-14', 'value': 9.443684210526316},
 {'date': '2017-05-15', 'value': 9.669583333333334},
 {'date': '2017-05-16', 'value': 11.1975},
 {'date': '2017-05-17', 'value': 14.75},
 {'date': '2017-05-18', 'value': 7.700588235294117},
 {'date': '2017-05-24', 'value': 11.631818181818183},
 {'date': '2017-05-25', 'value': 14.518749999999999},
 {'date': '2017-05-26', 'value': 14.194999999999999},
 {'date': '2017-05-27', 'value': 11.640416666666667},
 {'date': '2017-05-28', 'value': 13.65625},
 {'date': '2017-05-29', 'value': 10.294583333333334},
 {'date': '2017-05-30', 'value': 9.780833333333335},
 {'date': '2017-05-31', 'value': 8.709999999999999},
 {'date': '2017-06-01', 'value': 13.300833333333335},
 {'date': '2017-06-02', 'value': 17.682083333333335},
 {'date': '2017-06-03', 'value': 9.082916666666668},
 {'date': '2017-06-04', 'value': 10.255416666666667},
 {'date': '2017-06-05', 'value': 7.989999999999999},
 {'date': '2017-06-06', 'value': 17.859166666666663},
 {'date': '2017-06-07', 'value': 17.22208333333333},
 {'date': '2017-06-08', 'value': 11.494583333333336},
 {'date': '2017-06-09', 'value': 14.849166666666667},
 {'date': '2017-06-10', 'value': 14.521249999999997},
 {'date': '2017-06-11', 'value': 11.817083333333334},
 {'date': '2017-06-12', 'value': 16.264583333333334},
 {'date': '2017-06-13', 'value': 15.329583333333337},
 {'date': '2017-06-14', 'value': 19.692916666666665},
 {'date': '2017-06-15', 'value': 19.609583333333337},
 {'date': '2017-06-16', 'value': 18.655},
 {'date': '2017-06-17', 'value': 13.202499999999999},
 {'date': '2017-06-18', 'value': 16.841250000000002},
 {'date': '2017-06-19', 'value': 20.944166666666668},
 {'date': '2017-06-20', 'value': 27.469166666666666},
 {'date': '2017-06-21', 'value': 28.97000000000001},
 {'date': '2017-06-22', 'value': 33.35},
 {'date': '2017-06-23', 'value': 11.948636363636364},
 {'date': '2017-06-24', 'value': 10.470416666666669},
 {'date': '2017-06-25', 'value': 6.43},
 {'date': '2017-06-26', 'value': 10.521666666666667},
 {'date': '2017-06-27', 'value': 16.073636363636364},
 {'date': '2017-06-28', 'value': 8.58470588235294},
 {'date': '2017-06-29', 'value': 7.817083333333335},
 {'date': '2017-06-30', 'value': 7.044166666666668},
 {'date': '2017-07-01', 'value': 14.414761904761903},
 {'date': '2017-07-02', 'value': 8.415454545454548},
 {'date': '2017-07-03', 'value': 8.337083333333334},
 {'date': '2017-07-04', 'value': 10.916666666666666},
 {'date': '2017-07-05', 'value': 19.78714285714286},
 {'date': '2017-07-06', 'value': 24.126250000000002},
 {'date': '2017-07-07', 'value': 18.00571428571428},
 {'date': '2017-07-08', 'value': 9.487916666666669},
 {'date': '2017-07-09', 'value': 13.65695652173913},
 {'date': '2017-07-10', 'value': 9.144583333333333},
 {'date': '2017-07-11', 'value': 10.49},
 {'date': '2017-07-12', 'value': 8.485},
 {'date': '2017-07-13', 'value': 20.867272727272727},
 {'date': '2017-07-15', 'value': 14.846923076923076},
 {'date': '2017-07-16', 'value': 8.638333333333332},
 {'date': '2017-07-17', 'value': 26.701000000000004},
 {'date': '2017-07-18', 'value': 25.302222222222227},
 {'date': '2017-09-21', 'value': 9.165},
 {'date': '2017-09-22', 'value': 6.926666666666666},
 {'date': '2017-09-23', 'value': 11.902272727272726},
 {'date': '2017-09-24', 'value': 15.602500000000001},
 {'date': '2017-09-25', 'value': 9.188823529411765},
 {'date': '2017-09-26', 'value': 20.89333333333333},
 {'date': '2017-09-27', 'value': 18.48318181818182},
 {'date': '2017-09-28', 'value': 8.071333333333335},
 {'date': '2017-09-29', 'value': 14.290555555555557},
 {'date': '2017-09-30', 'value': 15.649090909090908},
 {'date': '2017-10-01', 'value': 6.149047619047619},
 {'date': '2017-10-02', 'value': 18.74761904761905},
 {'date': '2017-10-03', 'value': 11.166818181818181},
 {'date': '2017-10-04', 'value': 16.96},
 {'date': '2017-10-05', 'value': 13.13894736842105},
 {'date': '2017-10-06', 'value': 13.757142857142856},
 {'date': '2017-10-07', 'value': 12.926666666666668},
 {'date': '2017-10-08', 'value': 10.011304347826085},
 {'date': '2017-10-09', 'value': 12.97818181818182},
 {'date': '2017-10-12', 'value': 0.0},
 {'date': '2017-10-13', 'value': 0.45199999999999996},
 {'date': '2017-10-16', 'value': 4.833333333333333},
 {'date': '2017-10-17', 'value': 26.757058823529416},
 {'date': '2017-10-18', 'value': 28.39058823529412},
 {'date': '2017-10-19', 'value': 19.060434782608695},
 {'date': '2017-10-20', 'value': 10.765},
 {'date': '2017-10-21', 'value': 14.708571428571426},
 {'date': '2017-10-22', 'value': 15.232272727272727},
 {'date': '2017-10-23', 'value': 7.496666666666665},
 {'date': '2017-10-24', 'value': 8.379999999999999},
 {'date': '2017-10-25', 'value': 19.03666666666666},
 {'date': '2017-10-26', 'value': 21.326190476190476},
 {'date': '2017-10-27', 'value': 18.765500000000003},
 {'date': '2017-10-28', 'value': 15.339999999999998},
 {'date': '2017-10-29', 'value': 12.72809523809524},
 {'date': '2017-10-30', 'value': 16.46526315789474},
 {'date': '2017-10-31', 'value': 25.215},
 {'date': '2017-11-01', 'value': 20.17695652173913},
 {'date': '2017-11-02', 'value': 33.997857142857136},
 {'date': '2017-11-03', 'value': 30.084444444444443},
 {'date': '2017-11-04', 'value': 15.904444444444444},
 {'date': '2017-11-05', 'value': 7.916500000000002},
 {'date': '2017-11-06', 'value': 12.762631578947367},
 {'date': '2017-11-07', 'value': 19.032999999999998},
 {'date': '2017-11-08', 'value': 8.05},
 {'date': '2017-11-09', 'value': 17.060666666666666},
 {'date': '2017-11-10', 'value': 15.503333333333337},
 {'date': '2017-11-11', 'value': 7.512352941176471},
 {'date': '2017-11-12', 'value': 6.230909090909091},
 {'date': '2017-11-13', 'value': 13.5625},
 {'date': '2017-11-14', 'value': 21.355999999999998},
 {'date': '2017-11-15', 'value': 24.956000000000003},
 {'date': '2017-11-16', 'value': 33.820454545454545},
 {'date': '2017-11-17', 'value': 29.962},
 {'date': '2017-11-18', 'value': 21.104736842105265},
 {'date': '2017-11-19', 'value': 16.25},
 {'date': '2017-11-20', 'value': 15.85388888888889},
 {'date': '2017-11-21', 'value': 17.785714285714285},
 {'date': '2017-11-22', 'value': 21.916875000000005},
 {'date': '2017-11-23', 'value': 15.836842105263159},
 {'date': '2017-11-24', 'value': 8.654117647058824},
 {'date': '2017-11-25', 'value': 10.279333333333335},
 {'date': '2017-11-26', 'value': 15.078181818181816},
 {'date': '2017-11-27', 'value': 8.480666666666666},
 {'date': '2017-11-28', 'value': 16.71294117647059},
 {'date': '2017-11-29', 'value': 14.995882352941178},
 {'date': '2017-11-30', 'value': 9.427692307692308},
 {'date': '2017-12-01', 'value': 10.436666666666666},
 {'date': '2017-12-02', 'value': 15.692727272727273},
 {'date': '2017-12-03', 'value': 13.592352941176472},
 {'date': '2017-12-04', 'value': 19.678000000000004},
 {'date': '2017-12-05', 'value': 18.182000000000002},
 {'date': '2017-12-06', 'value': 19.120999999999995},
 {'date': '2017-12-07', 'value': 16.21238095238095},
 {'date': '2017-12-08', 'value': 11.200000000000001},
 {'date': '2017-12-11', 'value': 10.581999999999999},
 {'date': '2017-12-12', 'value': 13.7905},
 {'date': '2017-12-13', 'value': 12.61047619047619},
 {'date': '2017-12-14', 'value': 11.408333333333331},
 {'date': '2017-12-15', 'value': 10.836666666666664},
 {'date': '2017-12-16', 'value': 16.186666666666664},
 {'date': '2017-12-17', 'value': 12.731818181818182},
 {'date': '2017-12-18', 'value': 15.388571428571428},
 {'date': '2017-12-20', 'value': 34.15411764705882},
 {'date': '2017-12-21', 'value': 9.022105263157895},
 {'date': '2017-12-22', 'value': 10.879473684210527},
 {'date': '2017-12-23', 'value': 14.834375000000003},
 {'date': '2017-12-24', 'value': 4.857058823529411},
 {'date': '2017-12-25', 'value': 8.477500000000001},
 {'date': '2017-12-26', 'value': 6.461500000000001},
 {'date': '2017-12-27', 'value': 8.492608695652176},
 {'date': '2017-12-28', 'value': 13.360454545454546},
 {'date': '2017-12-29', 'value': 14.653888888888892},
 {'date': '2017-12-30', 'value': 15.99866666666667},
 {'date': '2017-12-31', 'value': 10.198636363636364},
 {'date': '2018-01-05', 'value': 19.18695652173913},
 {'date': '2018-01-06', 'value': 23.0985},
 {'date': '2018-01-07', 'value': 20.51},
 {'date': '2018-01-08', 'value': 21.30409090909091},
 {'date': '2018-01-09', 'value': 24.290416666666662},
 {'date': '2018-01-10', 'value': 17.699166666666667},
 {'date': '2018-01-11', 'value': 19.5625},
 {'date': '2018-01-12', 'value': 25.5915},
 {'date': '2018-01-13', 'value': 21.7075},
 {'date': '2018-01-14', 'value': 33.88090909090909},
 {'date': '2018-01-15', 'value': 13.110869565217389},
 {'date': '2018-01-16', 'value': 15.240526315789474},
 {'date': '2018-01-17', 'value': 17.092916666666664},
 {'date': '2018-01-18', 'value': 12.0},
 {'date': '2018-01-19', 'value': 11.284210526315789},
 {'date': '2018-01-20', 'value': 10.256818181818183},
 {'date': '2018-01-21', 'value': 9.376086956521739},
 {'date': '2018-01-22', 'value': 8.148333333333333},
 {'date': '2018-01-23', 'value': 9.04181818181818},
 {'date': '2018-01-24', 'value': 4.391},
 {'date': '2018-01-25', 'value': 13.268},
 {'date': '2018-01-26', 'value': 12.33875},
 {'date': '2018-01-27', 'value': 17.093529411764706},
 {'date': '2018-01-28', 'value': 4.0125},
 {'date': '2018-01-29', 'value': 6.78608695652174},
 {'date': '2018-01-30', 'value': 6.001249999999999},
 {'date': '2018-01-31', 'value': 10.100434782608696},
 {'date': '2018-02-01', 'value': 12.361818181818181},
 {'date': '2018-02-02', 'value': 14.214000000000002},
 {'date': '2018-02-03', 'value': 11.338},
 {'date': '2018-02-05', 'value': 20.55777777777778},
 {'date': '2018-02-06', 'value': 23.031111111111116},
 {'date': '2018-02-07', 'value': 12.195},
 {'date': '2018-02-08', 'value': 22.324761904761903},
 {'date': '2018-02-09', 'value': 12.547142857142857},
 {'date': '2018-02-10', 'value': 12.693999999999999},
 {'date': '2018-02-11', 'value': 16.104666666666667},
 {'date': '2018-02-12', 'value': 13.338571428571427},
 {'date': '2018-02-13', 'value': 7.338571428571429},
 {'date': '2018-02-25', 'value': 19.753333333333334},
 {'date': '2018-02-26', 'value': 20.166666666666668},
 {'date': '2018-02-27', 'value': 17.865454545454547},
 {'date': '2018-02-28', 'value': 34.50454545454546},
 {'date': '2018-03-01', 'value': 38.88},
 {'date': '2018-03-02', 'value': 11.253000000000002},
 {'date': '2018-03-03', 'value': 9.591250000000002},
 {'date': '2018-03-04', 'value': 9.269090909090908},
 {'date': '2018-03-05', 'value': 10.092916666666667},
 {'date': '2018-03-06', 'value': 10.223888888888888},
 {'date': '2018-03-07', 'value': 8.639},
 {'date': '2018-03-08', 'value': 14.860869565217392},
 {'date': '2018-03-09', 'value': 13.972000000000003},
 {'date': '2018-03-10', 'value': 16.363333333333333},
 {'date': '2018-03-11', 'value': 11.67},
 {'date': '2018-03-12', 'value': 17.455000000000002},
 {'date': '2018-03-13', 'value': 19.692857142857143},
 {'date': '2018-03-14', 'value': 11.541818181818181},
 {'date': '2018-03-15', 'value': 9.597222222222223},
 {'date': '2018-03-16', 'value': 14.520000000000003},
 {'date': '2018-03-17', 'value': 23.819285714285716},
 {'date': '2018-03-18', 'value': 32.879444444444445},
 {'date': '2018-03-19', 'value': 31.88},
 {'date': '2018-03-20', 'value': 1.4585714285714286},
 {'date': '2018-03-22', 'value': 21.383999999999997},
 {'date': '2018-03-23', 'value': 15.17125},
 {'date': '2018-03-24', 'value': 16.390434782608697},
 {'date': '2018-03-25', 'value': 47.0},
 {'date': '2018-03-26', 'value': 89.02272727272727},
 {'date': '2018-03-27', 'value': 10.97769230769231},
 {'date': '2018-03-28', 'value': 9.692857142857141},
 {'date': '2018-03-29', 'value': 8.192173913043481},
 {'date': '2018-03-30', 'value': 7.352500000000001},
 {'date': '2018-03-31', 'value': 9.935789473684212},
 {'date': '2018-04-01', 'value': 12.38},
 {'date': '2018-04-02', 'value': 9.757391304347829},
 {'date': '2018-04-03', 'value': 10.13409090909091},
 {'date': '2018-04-04', 'value': 14.637083333333335},
 {'date': '2018-04-05', 'value': 13.842631578947367},
 {'date': '2018-04-06', 'value': 17.300454545454542},
 {'date': '2018-04-07', 'value': 23.49952380952381},
 {'date': '2018-04-08', 'value': 15.93695652173913},
 {'date': '2018-04-09', 'value': 22.44615384615384},
 {'date': '2018-04-10', 'value': 8.09086956521739},
 {'date': '2018-04-11', 'value': 14.054210526315789},
 {'date': '2018-04-12', 'value': 36.59090909090909},
 {'date': '2018-04-13', 'value': 48.72434782608696},
 {'date': '2018-04-14', 'value': 24.22833333333333},
 {'date': '2018-04-15', 'value': 14.07888888888889},
 {'date': '2018-04-16', 'value': 17.465555555555557},
 {'date': '2018-04-17', 'value': 16.454285714285714},
 {'date': '2018-04-18', 'value': 16.689999999999998},
 {'date': '2018-04-19', 'value': 30.543181818181814},
 {'date': '2018-04-20', 'value': 40.23958333333333},
 {'date': '2018-04-21', 'value': 33.521304347826074},
 {'date': '2018-04-22', 'value': 24.755},
 {'date': '2018-04-23', 'value': 13.11705882352941},
 {'date': '2018-04-24', 'value': 14.412916666666666},
 {'date': '2018-04-25', 'value': 15.066250000000004},
 {'date': '2018-04-26', 'value': 18.41545454545454},
 {'date': '2018-04-27', 'value': 17.017777777777773},
 {'date': '2018-04-28', 'value': 12.50090909090909},
 {'date': '2018-04-29', 'value': 14.819411764705881},
 {'date': '2018-04-30', 'value': 11.145416666666664},
 {'date': '2018-05-01', 'value': 11.200869565217394},
 {'date': '2018-05-02', 'value': 9.695},
 {'date': '2018-05-03', 'value': 16.028695652173916},
 {'date': '2018-05-04', 'value': 42.059999999999995},
 {'date': '2018-05-05', 'value': 31.841363636363635},
 {'date': '2018-05-06', 'value': 44.461249999999986},
 {'date': '2018-05-07', 'value': 48.708260869565216},
 {'date': '2018-05-08', 'value': 41.21190476190477},
 {'date': '2018-05-09', 'value': 16.92529411764706},
 {'date': '2018-05-10', 'value': 20.384666666666664},
 {'date': '2018-05-11', 'value': 18.315499999999997},
 {'date': '2018-05-12', 'value': 16.390500000000003},
 {'date': '2018-05-13', 'value': 7.377777777777776},
 {'date': '2018-05-14', 'value': 16.096363636363638},
 {'date': '2018-05-15', 'value': 18.342777777777776},
 {'date': '2018-05-16', 'value': 23.74157894736842},
 {'date': '2018-05-17', 'value': 31.28380952380953},
 {'date': '2018-05-18', 'value': 18.775},
 {'date': '2018-05-19', 'value': 20.727999999999998},
 {'date': '2018-05-20', 'value': 33.7925},
 {'date': '2018-05-21', 'value': 36.571875},
 {'date': '2018-05-22', 'value': 33.997},
 {'date': '2018-05-23', 'value': 36.40500000000001},
 {'date': '2018-05-24', 'value': 37.269999999999996},
 {'date': '2018-05-25', 'value': 38.417857142857144},
 {'date': '2018-05-26', 'value': 36.202000000000005},
 {'date': '2018-05-27', 'value': 10.899047619047622},
 {'date': '2018-05-28', 'value': 19.27227272727272},
 {'date': '2018-05-29', 'value': 36.48363636363636},
 {'date': '2018-05-30', 'value': 27.180000000000003},
 {'date': '2018-05-31', 'value': 12.839545454545457},
 {'date': '2018-06-01', 'value': 10.822500000000002},
 {'date': '2018-06-02', 'value': 12.950454545454544},
 {'date': '2018-06-03', 'value': 12.9785},
 {'date': '2018-06-04', 'value': 24.027058823529412},
 {'date': '2018-06-05', 'value': 18.370416666666664},
 {'date': '2018-06-06', 'value': 31.30666666666667},
 {'date': '2018-06-07', 'value': 38.50782608695652},
 {'date': '2018-06-08', 'value': 20.09208333333333},
 {'date': '2018-06-09', 'value': 35.998260869565215},
 {'date': '2018-06-10', 'value': 34.951249999999995},
 {'date': '2018-06-11', 'value': 35.371904761904766},
 {'date': '2018-06-12', 'value': 27.98058823529412},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [53]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_pm10_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_pm10_mean
0    2016-11-21         15.307473
1    2016-11-22         20.258524
2    2016-11-23         20.047326
3    2016-11-25         25.068165
4    2016-11-26         26.159235
...         ...               ...
3111 2026-02-24         11.971721
3112 2026-02-25         16.919271
3113 2026-02-26         18.521137
3114 2026-02-27         16.938815
3115 2026-02-28         12.745906

[3116 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
france_daily[["date", "france_pm10_mean"]].to_csv(
    "france_pm10_daily_2016_2026.csv",
    index=False
)

NameError: name 'france_daily' is not defined

# PM2.5

### Get 200 stations located in France that measure PM2.5
Stations are sorted descending by the duration of their measurements

In [7]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "FR",   # only consider stations located in France
    "parameters_id": 2,   # PM2.5
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm25 = df_sorted.head(200)

df_top_pm25

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
11,2707,Evreux Centre,ÉVREUX,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275240, 'name': 'no µg/m³', 'paramete...","{'latitude': 49.02133999977332, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[1.1483189995666427, 49.02133999977332, 1.1483...",None,2016-11-21 11:00:00+00:00,2026-03-04 18:00:00+00:00
12,2708,Alençon Météo-France,CERISÉ,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275085, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.445553000017455, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[0.11083299979257102, 48.445553000017455, 0.11...",None,2016-11-21 11:00:00+00:00,2026-03-04 18:00:00+00:00
15,2720,Montpellier Prés d'Arènes,MONTPELLIER,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275188, 'name': 'no µg/m³', 'paramete...","{'latitude': 43.591500000324274, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[3.886809999908339, 43.591500000324274, 3.8868...",None,2016-11-21 11:00:00+00:00,2026-03-04 18:00:00+00:00
26,3479,Gonfreville l Orcher,GONFREVILLE-L'ORCHER,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 24890, 'name': 'co µg/m³', 'parameter'...","{'latitude': 49.50273000006004, 'longitude': 0...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[0.232485999671531, 49.50273000006004, 0.23248...",None,2016-11-21 11:00:00+00:00,2026-03-04 18:00:00+00:00
51,3588,Nancy-Charles III,NANCY,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275297, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.688170000094495, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.1904309999021265, 48.688170000094495, 6.190...",None,2016-11-21 11:00:00+00:00,2026-03-04 18:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,4018,FR34061,Loir-et-Cher,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4293015, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.5945165359368, 'longitude': 1....","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[1.30173969506476, 47.5945165359368, 1.3017396...",None,2017-02-18 08:00:00+00:00,2024-01-29 17:00:00+00:00
179,4019,FR34038,Cher,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274903, 'name': 'no µg/m³', 'paramete...","{'latitude': 46.8148188300394, 'longitude': 2....","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[2.61008200746779, 46.8148188300394, 2.6100820...",None,2017-02-18 08:00:00+00:00,2024-01-29 17:00:00+00:00
191,4068,FR04173,Seine-et-Marne,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 9594, 'name': 'pm10 µg/m³', 'parameter...","{'latitude': 48.8055412818308, 'longitude': 3....","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[3.08444637639995, 48.8055412818308, 3.0844463...",None,2017-02-18 08:00:00+00:00,2024-01-29 17:00:00+00:00
169,4002,FR34014,NaN,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 9450, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 47.9173751802827, 'longitude': 1....","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[1.96625944333933, 47.9173751802827, 1.9662594...",None,2017-02-18 08:00:00+00:00,2022-12-31 00:00:00+00:00
168,4001,FR34057,NaN,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 180, 'name': 'EEA France'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 9448, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 46.9429682344805, 'longitude': 2....","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[2.00326104989222, 46.9429682344805, 2.0032610...",None,2017-02-18 08:00:00+00:00,2021-12-29 21:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [8]:
rows = []

for _, station in df_top_pm25.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM25 behalten
        if sensor["parameter"]["id"] == 2:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm25_sensors = pd.DataFrame(rows)

df_pm25_sensors

     station_id               station_name  sensor_id sensor_name
0          2707              Evreux Centre    2021027  pm25 µg/m³
1          2708       Alençon Météo-France    2021026  pm25 µg/m³
2          2720  Montpellier Prés d'Arènes       5672  pm25 µg/m³
3          3479       Gonfreville l Orcher   14126423  pm25 µg/m³
4          3588          Nancy-Charles III       7924  pm25 µg/m³
..          ...                        ...        ...         ...
195        4018                    FR34061    1298710  pm25 µg/m³
196        4019                    FR34038       9495  pm25 µg/m³
197        4068                    FR04173    4442231  pm25 µg/m³
198        4002                    FR34014       9451  pm25 µg/m³
199        4001                    FR34057       9447  pm25 µg/m³

[200 rows x 4 columns]

In [9]:
sensor_ids = df_pm25_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

200

[2021027,
 2021026,
 5672,
 14126423,
 7924,
 8561,
 7958,
 8018,
 8196,
 9775,
 4442230,
 8273,
 8386,
 9247,
 9604,
 9634,
 9648,
 9816,
 9824,
 4445296,
 6571044,
 4445294,
 2021228,
 7798262,
 1562199,
 7915,
 12910123,
 8140,
 8477,
 8513,
 8590,
 8601,
 9893,
 1562236,
 6571043,
 2021024,
 7905,
 8107,
 8626,
 9867,
 6571045,
 1562200,
 8190,
 5633,
 4442228,
 1313925,
 9706,
 9118,
 9147,
 1313926,
 9533,
 9689,
 9692,
 9712,
 1313927,
 9723,
 9727,
 2020965,
 24599,
 9755,
 8432,
 8152,
 8062,
 5580,
 5664,
 8534,
 5610,
 8559,
 7702,
 7708,
 11547735,
 7826,
 7827,
 7829,
 7835,
 7838,
 7480203,
 7922,
 23955,
 13053058,
 10182727,
 4442227,
 8032,
 24867,
 8067,
 26008,
 10182729,
 1314203,
 40613,
 40645,
 13356377,
 8313,
 8323,
 8330,
 8360,
 40625,
 8404,
 8409,
 8520,
 40635,
 8555,
 24881,
 26003,
 1582598,
 9548,
 9596,
 9588,
 9589,
 1562368,
 4661655,
 9646,
 9681,
 9702,
 9733,
 1562192,
 9663,
 1290016,
 8372,
 8616,
 8456,
 5597,
 9865,
 8056,
 15290412,
 8181,
 5078301,
 8044,
 8200,
 8213,
 8238,
 8048,
 7944,
 8210,
 9617,
 5614,
 8051,
 8143,
 4445297,
 10189266,
 8334,
 24880,
 8568,
 1562363,
 8224,
 7480202,
 24006,
 8246,
 8156,
 9479,
 8308,
 8473,
 7854,
 9014237,
 8037,
 7480201,
 9383,
 9477,
 40623,
 8171,
 7879,
 21748,
 10182731,
 9418,
 7480205,
 9392,
 9408,
 1290017,
 24874,
 7983,
 8121,
 24871,
 8178,
 8281,
 26014,
 2021486,
 9446,
 1298716,
 1298709,
 1298723,
 1298714,
 1298711,
 24628,
 7889,
 12951387,
 6571255,
 7704,
 7852,
 7884,
 8265,
 7480206,
 2021048,
 7480204,
 7703,
 8285,
 1298715,
 1298710,
 9495,
 4442231,
 9451,
 9447]

### Get daily, average values from each sensor/station for 2016-2026

In [11]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 2021027: Seite 1, 1000 Ergebnisse
Sensor 2021027: Seite 2, 229 Ergebnisse
Sensor 2021026: Seite 1, 1000 Ergebnisse
Sensor 2021026: Seite 2, 227 Ergebnisse
Sensor 5672: Seite 1, 1000 Ergebnisse
Sensor 5672: Seite 2, 1000 Ergebnisse
Sensor 5672: Seite 3, 801 Ergebnisse
Sensor 14126423: Seite 1, 169 Ergebnisse
Sensor 7924: Seite 1, 1000 Ergebnisse
Sensor 7924: Seite 2, 1000 Ergebnisse
Sensor 7924: Seite 3, 891 Ergebnisse
Sensor 8561: Seite 1, 1000 Ergebnisse
Sensor 8561: Seite 2, 1000 Ergebnisse
Sensor 8561: Seite 3, 733 Ergebnisse
Sensor 7958: Seite 1, 1000 Ergebnisse
Sensor 7958: Seite 2, 1000 Ergebnisse
Sensor 7958: Seite 3, 847 Ergebnisse
Sensor 8018: Seite 1, 1000 Ergebnisse
Sensor 8018: Seite 2, 1000 Ergebnisse
Sensor 8018: Seite 3, 932 Ergebnisse
Sensor 8196: Seite 1, 1000 Ergebnisse
Sensor 8196: Seite 2, 1000 Ergebnisse
Sensor 8196: Seite 3, 890 Ergebnisse
Sensor 9775: Seite 1, 1000 Ergebnisse
Sensor 9775: Seite 2, 1000 Ergebnisse
Sensor 9775: Seite 3, 680 Ergebnisse
Sensor 4442230: Seite 1, 10 Ergebnisse
Sensor 8273: Seite 1, 1000 Ergebnisse
Sensor 8273: Seite 2, 1000 Ergebnisse
Sensor 8273: Seite 3, 863 Ergebnisse
Sensor 8386: Seite 1, 1000 Ergebnisse
Sensor 8386: Seite 2, 1000 Ergebnisse
Sensor 8386: Seite 3, 875 Ergebnisse
Sensor 9247: Seite 1, 1000 Ergebnisse
Sensor 9247: Seite 2, 1000 Ergebnisse
Sensor 9247: Seite 3, 847 Ergebnisse
Sensor 9604: Seite 1, 1000 Ergebnisse
Sensor 9604: Seite 2, 1000 Ergebnisse
Sensor 9604: Seite 3, 936 Ergebnisse
Sensor 9634: Seite 1, 1000 Ergebnisse
Sensor 9634: Seite 2, 1000 Ergebnisse
Sensor 9634: Seite 3, 889 Ergebnisse
Sensor 9648: Seite 1, 1000 Ergebnisse
Sensor 9648: Seite 2, 1000 Ergebnisse
Sensor 9648: Seite 3, 929 Ergebnisse
Sensor 9816: Seite 1, 1000 Ergebnisse
Sensor 9816: Seite 2, 1000 Ergebnisse
Sensor 9816: Seite 3, 755 Ergebnisse
Sensor 9824: Seite 1, 1000 Ergebnisse
Sensor 9824: Seite 2, 1000 Ergebnisse
Sensor 9824: Seite 3, 802 Ergebnisse
Sensor 4445296: Seite 1, 826 Ergebnisse
Sensor 6571044: Seite 1, 931 Ergebnisse
Sensor 4445294: Seite 1, 1000 Ergebnisse
Sensor 4445294: Seite 2, 26 Ergebnisse
Sensor 2021228: Seite 1, 1000 Ergebnisse
Sensor 2021228: Seite 2, 186 Ergebnisse
Sensor 7798262: Seite 1, 649 Ergebnisse
Sensor 1562199: Seite 1, 1000 Ergebnisse
Sensor 1562199: Seite 2, 258 Ergebnisse
Sensor 7915: Seite 1, 1000 Ergebnisse
Sensor 7915: Seite 2, 1000 Ergebnisse
Sensor 7915: Seite 3, 452 Ergebnisse
Sensor 12910123: Seite 1, 220 Ergebnisse
Sensor 8140: Seite 1, 1000 Ergebnisse
Sensor 8140: Seite 2, 1000 Ergebnisse
Sensor 8140: Seite 3, 663 Ergebnisse
Sensor 8477: Seite 1, 1000 Ergebnisse
Sensor 8477: Seite 2, 1000 Ergebnisse
Sensor 8477: Seite 3, 601 Ergebnisse
Sensor 8513: Seite 1, 1000 Ergebnisse
Sensor 8513: Seite 2, 1000 Ergebnisse
Sensor 8513: Seite 3, 712 Ergebnisse
Sensor 8590: Seite 1, 1000 Ergebnisse
Sensor 8590: Seite 2, 1000 Ergebnisse
Sensor 8590: Seite 3, 561 Ergebnisse
Sensor 8601: Seite 1, 1000 Ergebnisse
Sensor 8601: Seite 2, 1000 Ergebnisse
Sensor 8601: Seite 3, 619 Ergebnisse
Sensor 9893: Seite 1, 1000 Ergebnisse
Sensor 9893: Seite 2, 1000 Ergebnisse
Sensor 9893: Seite 3, 616 Ergebnisse
Sensor 1562236: Seite 1, 1000 Ergebnisse
Sensor 1562236: Seite 2, 23 Ergebnisse
Sensor 6571043: Seite 1, 359 Ergebnisse
Sensor 2021024: Seite 1, 600 Ergebnisse
Sensor 7905: Seite 1, 1000 Ergebnisse
Sensor 7905: Seite 2, 1000 Ergebnisse
Sensor 7905: Seite 3, 131 Ergebnisse
Sensor 8107: Seite 1, 1000 Ergebnisse
Sensor 8107: Seite 2, 1000 Ergebnisse
Sensor 8107: Seite 3, 219 Ergebnisse
Sensor 8626: Seite 1, 1000 Ergebnisse
Sensor 8626: Seite 2, 1000 Ergebnisse
Sensor 8626: Seite 3, 269 Ergebnisse
Sensor 9867: Seite 1, 1000 Ergebnisse
Sensor 9867: Seite 2, 1000 Ergebnisse
Sensor 9867: Seite 3, 84 Ergebnisse
Sensor 6571045: Seite 1, 192 Ergebnisse
Sensor 1562200: Seite 1, 607 Ergebnisse
Sensor 8190: Seite 1, 1000 Ergebnisse
Sensor 8190: Seite 2, 972 Ergebnisse
Sensor 5633: Seite 1, 1000 Ergebnisse
Sensor 5633: Seite 2, 1000 Ergebnisse
Sensor 5633: Seite 3, 196 Ergebnisse
Sensor 4442228: Seite 1, 280 Ergebnisse
Sensor 1313925: Seite 1, 778 Ergebnisse
Sensor 9706: Seite 1, 1000 Ergebnisse
Sensor 9706: Seite 2, 1000 Ergebnisse
Sensor 9706: Seite 3, 125 Ergebnisse
Sensor 9118: Seite 1, 1000 Ergebnisse
Sensor 9118: Seite 2, 436 Ergebnisse
Sensor 9147: Seite 1, 1000 Ergebnisse
Sensor 9147: Seite 2, 697 Ergebnisse
Sensor 1313926: Seite 1, 776 Ergebnisse
Sensor 9533: Seite 1, 1000 Ergebnisse
Sensor 9533: Seite 2, 1000 Ergebnisse
Sensor 9533: Seite 3, 92 Ergebnisse
Sensor 9689: Seite 1, 1000 Ergebnisse
Sensor 9689: Seite 2, 1000 Ergebnisse
Sensor 9689: Seite 3, 128 Ergebnisse
Sensor 9692: Seite 1, 1000 Ergebnisse
Sensor 9692: Seite 2, 871 Ergebnisse
Sensor 9712: Seite 1, 1000 Ergebnisse
Sensor 9712: Seite 2, 1000 Ergebnisse
Sensor 9712: Seite 3, 193 Ergebnisse
Sensor 1313927: Seite 1, 814 Ergebnisse
Sensor 9723: Seite 1, 1000 Ergebnisse
Sensor 9723: Seite 2, 1000 Ergebnisse
Sensor 9723: Seite 3, 178 Ergebnisse
Sensor 9727: Seite 1, 1000 Ergebnisse
Sensor 9727: Seite 2, 1000 Ergebnisse
Sensor 9727: Seite 3, 34 Ergebnisse
Sensor 2020965: Seite 1, 131 Ergebnisse
Sensor 24599: Seite 1, 1000 Ergebnisse
Sensor 24599: Seite 2, 191 Ergebnisse
Sensor 9755: Seite 1, 1000 Ergebnisse
Sensor 9755: Seite 2, 1000 Ergebnisse
Sensor 9755: Seite 3, 249 Ergebnisse
Sensor 8432: Seite 1, 1000 Ergebnisse
Sensor 8432: Seite 2, 1000 Ergebnisse
Sensor 8432: Seite 3, 147 Ergebnisse
Sensor 8152: Seite 1, 1000 Ergebnisse
Sensor 8152: Seite 2, 1000 Ergebnisse
Sensor 8152: Seite 3, 19 Ergebnisse
Sensor 8062: Seite 1, 1000 Ergebnisse
Sensor 8062: Seite 2, 381 Ergebnisse
Sensor 5580: Seite 1, 9 Ergebnisse
Sensor 5664: Seite 1, 13 Ergebnisse
Sensor 8534: Seite 1, 1000 Ergebnisse
Sensor 8534: Seite 2, 1000 Ergebnisse
Sensor 8534: Seite 3, 962 Ergebnisse
Sensor 5610: Seite 1, 1000 Ergebnisse
Sensor 5610: Seite 2, 1000 Ergebnisse
Sensor 5610: Seite 3, 630 Ergebnisse
Sensor 8559: Seite 1, 1000 Ergebnisse
Sensor 8559: Seite 2, 1000 Ergebnisse
Sensor 8559: Seite 3, 800 Ergebnisse
Sensor 7702: Seite 1, 1000 Ergebnisse
Sensor 7702: Seite 2, 1000 Ergebnisse
Sensor 7702: Seite 3, 742 Ergebnisse
Sensor 7708: Seite 1, 1000 Ergebnisse
Sensor 7708: Seite 2, 1000 Ergebnisse
Sensor 7708: Seite 3, 479 Ergebnisse
Sensor 11547735: Seite 1, 412 Ergebnisse
Sensor 7826: Seite 1, 1000 Ergebnisse
Sensor 7826: Seite 2, 1000 Ergebnisse
Sensor 7826: Seite 3, 773 Ergebnisse
Sensor 7827: Seite 1, 1000 Ergebnisse
Sensor 7827: Seite 2, 1000 Ergebnisse
Sensor 7827: Seite 3, 822 Ergebnisse
Sensor 7829: Seite 1, 1000 Ergebnisse
Sensor 7829: Seite 2, 1000 Ergebnisse
Sensor 7829: Seite 3, 697 Ergebnisse
Sensor 7835: Seite 1, 1000 Ergebnisse
Sensor 7835: Seite 2, 1000 Ergebnisse
Sensor 7835: Seite 3, 797 Ergebnisse
Sensor 7838: Seite 1, 1000 Ergebnisse
Sensor 7838: Seite 2, 1000 Ergebnisse
Sensor 7838: Seite 3, 835 Ergebnisse
Sensor 7480203: Seite 1, 694 Ergebnisse
Sensor 7922: Seite 1, 1000 Ergebnisse
Sensor 7922: Seite 2, 1000 Ergebnisse
Sensor 7922: Seite 3, 904 Ergebnisse
Sensor 23955: Seite 1, 1000 Ergebnisse
Sensor 23955: Seite 2, 1000 Ergebnisse
Sensor 23955: Seite 3, 169 Ergebnisse
Sensor 13053058: Seite 1, 288 Ergebnisse
Sensor 10182727: Seite 1, 568 Ergebnisse
Sensor 4442227: Seite 1, 995 Ergebnisse
Sensor 8032: Seite 1, 1000 Ergebnisse
Sensor 8032: Seite 2, 1000 Ergebnisse
Sensor 8032: Seite 3, 972 Ergebnisse
Sensor 24867: Seite 1, 1000 Ergebnisse
Sensor 24867: Seite 2, 795 Ergebnisse
Sensor 8067: Seite 1, 1000 Ergebnisse
Sensor 8067: Seite 2, 1000 Ergebnisse
Sensor 8067: Seite 3, 456 Ergebnisse
Sensor 26008: Seite 1, 1000 Ergebnisse
Sensor 26008: Seite 2, 1000 Ergebnisse
Sensor 26008: Seite 3, 100 Ergebnisse
Sensor 10182729: Seite 1, 565 Ergebnisse
Sensor 1314203: Seite 1, 1000 Ergebnisse
Sensor 1314203: Seite 2, 392 Ergebnisse
Sensor 40613: Seite 1, 998 Ergebnisse
Sensor 40645: Seite 1, 1000 Ergebnisse
Sensor 40645: Seite 2, 759 Ergebnisse
Sensor 13356377: Seite 1, 236 Ergebnisse
Sensor 8313: Seite 1, 1000 Ergebnisse
Sensor 8313: Seite 2, 1000 Ergebnisse
Sensor 8313: Seite 3, 834 Ergebnisse
Sensor 8323: Seite 1, 1000 Ergebnisse
Sensor 8323: Seite 2, 1000 Ergebnisse
Sensor 8323: Seite 3, 932 Ergebnisse
Sensor 8330: Seite 1, 803 Ergebnisse
Sensor 8360: Seite 1, 1000 Ergebnisse
Sensor 8360: Seite 2, 1000 Ergebnisse
Sensor 8360: Seite 3, 1000 Ergebnisse
Sensor 8360: Seite 4, 1 Ergebnisse
Sensor 40625: Seite 1, 1000 Ergebnisse
Sensor 40625: Seite 2, 769 Ergebnisse
Sensor 8404: Seite 1, 1000 Ergebnisse
Sensor 8404: Seite 2, 1000 Ergebnisse
Sensor 8404: Seite 3, 992 Ergebnisse
Sensor 8409: Seite 1, 1000 Ergebnisse
Sensor 8409: Seite 2, 1000 Ergebnisse
Sensor 8409: Seite 3, 906 Ergebnisse
Sensor 8520: Seite 1, 1000 Ergebnisse
Sensor 8520: Seite 2, 1000 Ergebnisse
Sensor 8520: Seite 3, 852 Ergebnisse
Sensor 40635: Seite 1, 1000 Ergebnisse
Sensor 40635: Seite 2, 752 Ergebnisse
Sensor 8555: Seite 1, 1000 Ergebnisse
Sensor 8555: Seite 2, 1000 Ergebnisse
Sensor 8555: Seite 3, 849 Ergebnisse
Sensor 24881: Seite 1, 1000 Ergebnisse
Sensor 24881: Seite 2, 1000 Ergebnisse
Sensor 24881: Seite 3, 148 Ergebnisse
Sensor 26003: Seite 1, 1000 Ergebnisse
Sensor 26003: Seite 2, 1000 Ergebnisse
Sensor 26003: Seite 3, 216 Ergebnisse
Sensor 1582598: Seite 1, 1000 Ergebnisse
Sensor 1582598: Seite 2, 360 Ergebnisse
Sensor 9548: Seite 1, 1000 Ergebnisse
Sensor 9548: Seite 2, 1000 Ergebnisse
Sensor 9548: Seite 3, 963 Ergebnisse
Sensor 9596: Seite 1, 1000 Ergebnisse
Sensor 9596: Seite 2, 1000 Ergebnisse
Sensor 9596: Seite 3, 963 Ergebnisse
Sensor 9588: Seite 1, 1000 Ergebnisse
Sensor 9588: Seite 2, 1000 Ergebnisse
Sensor 9588: Seite 3, 934 Ergebnisse
Sensor 9589: Seite 1, 1000 Ergebnisse
Sensor 9589: Seite 2, 1000 Ergebnisse
Sensor 9589: Seite 3, 971 Ergebnisse
Sensor 1562368: Seite 1, 1000 Ergebnisse
Sensor 1562368: Seite 2, 398 Ergebnisse
Sensor 4661655: Seite 1, 1000 Ergebnisse
Sensor 4661655: Seite 2, 26 Ergebnisse
Sensor 9646: Seite 1, 1000 Ergebnisse
Sensor 9646: Seite 2, 1000 Ergebnisse
Sensor 9646: Seite 3, 1000 Ergebnisse
Sensor 9646: Seite 4, 13 Ergebnisse
Sensor 9681: Seite 1, 1000 Ergebnisse
Sensor 9681: Seite 2, 1000 Ergebnisse
Sensor 9681: Seite 3, 990 Ergebnisse
Sensor 9702: Seite 1, 1000 Ergebnisse
Sensor 9702: Seite 2, 1000 Ergebnisse
Sensor 9702: Seite 3, 809 Ergebnisse
Sensor 9733: Seite 1, 1000 Ergebnisse
Sensor 9733: Seite 2, 1000 Ergebnisse
Sensor 9733: Seite 3, 992 Ergebnisse
Sensor 1562192: Seite 1, 1000 Ergebnisse
Sensor 1562192: Seite 2, 423 Ergebnisse
Sensor 9663: Seite 1, 1000 Ergebnisse
Sensor 9663: Seite 2, 1000 Ergebnisse
Sensor 9663: Seite 3, 117 Ergebnisse
Sensor 1290016: Seite 1, 851 Ergebnisse
Sensor 8372: Seite 1, 1000 Ergebnisse
Sensor 8372: Seite 2, 727 Ergebnisse
Sensor 8616: Seite 1, 839 Ergebnisse
Sensor 8456: Seite 1, 1000 Ergebnisse
Sensor 8456: Seite 2, 64 Ergebnisse
Sensor 5597: Seite 1, 866 Ergebnisse
Sensor 9865: Seite 1, 642 Ergebnisse
Sensor 8056: Seite 1, 223 Ergebnisse
Sensor 15290412: Seite 1, 32 Ergebnisse
Sensor 8181: Seite 1, 1000 Ergebnisse
Sensor 8181: Seite 2, 1000 Ergebnisse
Sensor 8181: Seite 3, 720 Ergebnisse
Sensor 5078301: Seite 1, 977 Ergebnisse
Sensor 8044: Seite 1, 1000 Ergebnisse
Sensor 8044: Seite 2, 1000 Ergebnisse
Sensor 8044: Seite 3, 720 Ergebnisse
Sensor 8200: Seite 1, 1000 Ergebnisse
Sensor 8200: Seite 2, 1000 Ergebnisse
Sensor 8200: Seite 3, 228 Ergebnisse
Sensor 8213: Seite 1, 1000 Ergebnisse
Sensor 8213: Seite 2, 1000 Ergebnisse
Sensor 8213: Seite 3, 209 Ergebnisse
Sensor 8238: Seite 1, 1000 Ergebnisse
Sensor 8238: Seite 2, 1000 Ergebnisse
Sensor 8238: Seite 3, 622 Ergebnisse
Sensor 8048: Seite 1, 137 Ergebnisse
Sensor 7944: Seite 1, 1000 Ergebnisse
Sensor 7944: Seite 2, 1000 Ergebnisse
Sensor 7944: Seite 3, 491 Ergebnisse
Sensor 8210: Seite 1, 365 Ergebnisse
Sensor 9617: Seite 1, 705 Ergebnisse
Sensor 5614: Seite 1, 1000 Ergebnisse
Sensor 5614: Seite 2, 1000 Ergebnisse
Sensor 5614: Seite 3, 822 Ergebnisse
Sensor 8051: Seite 1, 1000 Ergebnisse
Sensor 8051: Seite 2, 1000 Ergebnisse
Sensor 8051: Seite 3, 966 Ergebnisse
Sensor 8143: Seite 1, 1000 Ergebnisse
Sensor 8143: Seite 2, 1000 Ergebnisse
Sensor 8143: Seite 3, 1000 Ergebnisse
Sensor 8143: Seite 4, 28 Ergebnisse
Sensor 4445297: Seite 1, 987 Ergebnisse
Sensor 10189266: Seite 1, 526 Ergebnisse
Sensor 8334: Seite 1, 1000 Ergebnisse
Sensor 8334: Seite 2, 1000 Ergebnisse
Sensor 8334: Seite 3, 1000 Ergebnisse
Sensor 8334: Seite 4, 28 Ergebnisse
Sensor 24880: Seite 1, 1000 Ergebnisse
Sensor 24880: Seite 2, 287 Ergebnisse
Sensor 8568: Seite 1, 1000 Ergebnisse
Sensor 8568: Seite 2, 1000 Ergebnisse
Sensor 8568: Seite 3, 302 Ergebnisse
Sensor 1562363: Seite 1, 691 Ergebnisse
Sensor 8224: Seite 1, 1000 Ergebnisse
Sensor 8224: Seite 2, 1000 Ergebnisse
Sensor 8224: Seite 3, 244 Ergebnisse
Sensor 7480202: Seite 1, 61 Ergebnisse
Sensor 24006: Seite 1, 1000 Ergebnisse
Sensor 24006: Seite 2, 853 Ergebnisse
Sensor 8246: Seite 1, 1000 Ergebnisse
Sensor 8246: Seite 2, 1000 Ergebnisse
Sensor 8246: Seite 3, 247 Ergebnisse
Sensor 8156: Seite 1, 1000 Ergebnisse
Sensor 8156: Seite 2, 932 Ergebnisse
Sensor 9479: Seite 1, 1000 Ergebnisse
Sensor 9479: Seite 2, 456 Ergebnisse
Sensor 8308: Seite 1, 938 Ergebnisse
Sensor 8473: Seite 1, 254 Ergebnisse
Sensor 7854: Seite 1, 100 Ergebnisse
Sensor 9014237: Seite 1, 604 Ergebnisse
Sensor 8037: Seite 1, 1000 Ergebnisse
Sensor 8037: Seite 2, 1000 Ergebnisse
Sensor 8037: Seite 3, 736 Ergebnisse
Sensor 7480201: Seite 1, 366 Ergebnisse
Sensor 9383: Seite 1, 1000 Ergebnisse
Sensor 9383: Seite 2, 1000 Ergebnisse
Sensor 9383: Seite 3, 624 Ergebnisse
Sensor 9477: Seite 1, 1000 Ergebnisse
Sensor 9477: Seite 2, 1000 Ergebnisse
Sensor 9477: Seite 3, 692 Ergebnisse
Sensor 40623: Seite 1, 1000 Ergebnisse
Sensor 40623: Seite 2, 601 Ergebnisse
Sensor 8171: Seite 1, 682 Ergebnisse
Sensor 7879: Seite 1, 1000 Ergebnisse
Sensor 7879: Seite 2, 739 Ergebnisse
Sensor 21748: Seite 1, 666 Ergebnisse
Sensor 10182731: Seite 1, 547 Ergebnisse
Sensor 9418: Seite 1, 1000 Ergebnisse
Sensor 9418: Seite 2, 1000 Ergebnisse
Sensor 9418: Seite 3, 663 Ergebnisse
Sensor 7480205: Seite 1, 655 Ergebnisse
Sensor 9392: Seite 1, 1000 Ergebnisse
Sensor 9392: Seite 2, 895 Ergebnisse
Sensor 9408: Seite 1, 1000 Ergebnisse
Sensor 9408: Seite 2, 1000 Ergebnisse
Sensor 9408: Seite 3, 143 Ergebnisse
Sensor 1290017: Seite 1, 1000 Ergebnisse
Sensor 1290017: Seite 2, 585 Ergebnisse
Sensor 24874: Seite 1, 1000 Ergebnisse
Sensor 24874: Seite 2, 1000 Ergebnisse
Sensor 24874: Seite 3, 441 Ergebnisse
Sensor 7983: Seite 1, 1000 Ergebnisse
Sensor 7983: Seite 2, 1000 Ergebnisse
Sensor 7983: Seite 3, 625 Ergebnisse
Sensor 8121: Seite 1, 1000 Ergebnisse
Sensor 8121: Seite 2, 1000 Ergebnisse
Sensor 8121: Seite 3, 171 Ergebnisse
Sensor 24871: Seite 1, 1000 Ergebnisse
Sensor 24871: Seite 2, 1000 Ergebnisse
Sensor 24871: Seite 3, 144 Ergebnisse
Sensor 8178: Seite 1, 1000 Ergebnisse
Sensor 8178: Seite 2, 1000 Ergebnisse
Sensor 8178: Seite 3, 905 Ergebnisse
Sensor 8281: Seite 1, 1000 Ergebnisse
Sensor 8281: Seite 2, 376 Ergebnisse
Sensor 26014: Seite 1, 1000 Ergebnisse
Sensor 26014: Seite 2, 1000 Ergebnisse
Sensor 26014: Seite 3, 232 Ergebnisse
Sensor 2021486: Seite 1, 1000 Ergebnisse
Sensor 2021486: Seite 2, 3 Ergebnisse
Sensor 9446: Seite 1, 1000 Ergebnisse
Sensor 9446: Seite 2, 1000 Ergebnisse
Sensor 9446: Seite 3, 824 Ergebnisse
Sensor 1298716: Seite 1, 1000 Ergebnisse
Sensor 1298716: Seite 2, 641 Ergebnisse
Sensor 1298709: Seite 1, 1000 Ergebnisse
Sensor 1298709: Seite 2, 645 Ergebnisse
Sensor 1298723: Seite 1, 1000 Ergebnisse
Sensor 1298723: Seite 2, 610 Ergebnisse
Sensor 1298714: Seite 1, 1000 Ergebnisse
Sensor 1298714: Seite 2, 653 Ergebnisse
Sensor 1298711: Seite 1, 1000 Ergebnisse
Sensor 1298711: Seite 2, 649 Ergebnisse
Sensor 24628: Seite 1, 1000 Ergebnisse
Sensor 24628: Seite 2, 1000 Ergebnisse
Sensor 24628: Seite 3, 498 Ergebnisse
Sensor 7889: Seite 1, 1000 Ergebnisse
Sensor 7889: Seite 2, 1000 Ergebnisse
Sensor 7889: Seite 3, 925 Ergebnisse
Sensor 12951387: Seite 1, 127 Ergebnisse
Sensor 6571255: Seite 1, 439 Ergebnisse
Sensor 7704: Seite 1, 1000 Ergebnisse
Sensor 7704: Seite 2, 1000 Ergebnisse
Sensor 7704: Seite 3, 36 Ergebnisse
Sensor 7852: Seite 1, 1000 Ergebnisse
Sensor 7852: Seite 2, 1000 Ergebnisse
Sensor 7852: Seite 3, 5 Ergebnisse
Sensor 7884: Seite 1, 1000 Ergebnisse
Sensor 7884: Seite 2, 1000 Ergebnisse
Sensor 7884: Seite 3, 75 Ergebnisse
Sensor 8265: Seite 1, 987 Ergebnisse
Sensor 7480206: Seite 1, 61 Ergebnisse
Sensor 2021048: Seite 1, 473 Ergebnisse
Sensor 7480204: Seite 1, 61 Ergebnisse
Sensor 7703: Seite 1, 1000 Ergebnisse
Sensor 7703: Seite 2, 695 Ergebnisse
Sensor 8285: Seite 1, 1000 Ergebnisse
Sensor 8285: Seite 2, 1000 Ergebnisse
Sensor 8285: Seite 3, 263 Ergebnisse
Sensor 1298715: Seite 1, 916 Ergebnisse
Sensor 1298710: Seite 1, 924 Ergebnisse
Sensor 9495: Seite 1, 1000 Ergebnisse
Sensor 9495: Seite 2, 1000 Ergebnisse
Sensor 9495: Seite 3, 83 Ergebnisse
Sensor 4442231: Seite 1, 299 Ergebnisse
Sensor 9451: Seite 1, 1000 Ergebnisse
Sensor 9451: Seite 2, 749 Ergebnisse
Sensor 9447: Seite 1, 1000 Ergebnisse
Sensor 9447: Seite 2, 526 Ergebnisse
353071

[{'date': '2022-08-11', 'value': 12.0},
 {'date': '2022-08-12', 'value': 8.679166666666665},
 {'date': '2022-08-13', 'value': 7.229166666666665},
 {'date': '2022-08-14', 'value': 6.942857142857143},
 {'date': '2022-08-15', 'value': 10.823809523809526},
 {'date': '2022-08-16', 'value': 11.758333333333335},
 {'date': '2022-08-17', 'value': 6.725000000000001},
 {'date': '2022-08-18', 'value': 8.083333333333334},
 {'date': '2022-08-19', 'value': 6.971428571428572},
 {'date': '2022-08-20', 'value': 7.550000000000001},
 {'date': '2022-08-21', 'value': 5.7749999999999995},
 {'date': '2022-08-22', 'value': 3.9166666666666674},
 {'date': '2022-08-23', 'value': 1.5333333333333332},
 {'date': '2022-08-24', 'value': 3.059090909090909},
 {'date': '2022-08-25', 'value': 3.4},
 {'date': '2022-08-26', 'value': 6.754545454545456},
 {'date': '2022-08-27', 'value': 5.470833333333334},
 {'date': '2022-08-28', 'value': 5.3374999999999995},
 {'date': '2022-08-29', 'value': 5.095833333333332},
 {'date': '2022-08-30', 'value': 6.9416666666666655},
 {'date': '2022-08-31', 'value': 6.991666666666667},
 {'date': '2022-09-01', 'value': 8.079166666666664},
 {'date': '2022-09-02', 'value': 7.187499999999999},
 {'date': '2022-09-03', 'value': 5.741666666666667},
 {'date': '2022-09-04', 'value': 5.383333333333334},
 {'date': '2022-09-05', 'value': 4.295833333333333},
 {'date': '2022-09-06', 'value': 5.05},
 {'date': '2022-09-07', 'value': 4.923809523809525},
 {'date': '2022-09-08', 'value': 3.975},
 {'date': '2022-09-09', 'value': 4.179166666666666},
 {'date': '2022-09-10', 'value': 3.7999999999999994},
 {'date': '2022-09-11', 'value': 3.620833333333333},
 {'date': '2022-09-12', 'value': 3.5624999999999996},
 {'date': '2022-09-13', 'value': 5.337500000000001},
 {'date': '2022-09-14', 'value': 5.691666666666666},
 {'date': '2022-09-15', 'value': 6.9958333333333345},
 {'date': '2022-09-16', 'value': 4.1090909090909085},
 {'date': '2022-09-17', 'value': 2.0708333333333333},
 {'date': '2022-09-18', 'value': 2.952173913043478},
 {'date': '2022-09-20', 'value': 5.061538461538462},
 {'date': '2022-09-21', 'value': 6.000000000000001},
 {'date': '2022-09-22', 'value': 5.629166666666667},
 {'date': '2022-09-23', 'value': 7.504166666666667},
 {'date': '2022-09-24', 'value': 6.5},
 {'date': '2022-09-25', 'value': 3.6772727272727277},
 {'date': '2022-09-26', 'value': 3.3124999999999996},
 {'date': '2022-09-27', 'value': 5.145833333333335},
 {'date': '2022-09-28', 'value': 3.670833333333334},
 {'date': '2022-09-29', 'value': 4.154166666666667},
 {'date': '2022-09-30', 'value': 5.449999999999999},
 {'date': '2022-10-01', 'value': 3.9714285714285715},
 {'date': '2022-10-02', 'value': 2.677272727272727},
 {'date': '2022-10-03', 'value': 5.329166666666667},
 {'date': '2022-10-04', 'value': 5.295833333333333},
 {'date': '2022-10-05', 'value': 4.0874999999999995},
 {'date': '2022-10-06', 'value': 7.037500000000001},
 {'date': '2022-10-07', 'value': 6.949999999999999},
 {'date': '2022-10-08', 'value': 5.46818181818182},
 {'date': '2022-10-09', 'value': 7.037499999999999},
 {'date': '2022-10-10', 'value': 9.491666666666665},
 {'date': '2022-10-11', 'value': 6.7375},
 {'date': '2022-10-12', 'value': 9.774999999999999},
 {'date': '2022-10-13', 'value': 6.291666666666665},
 {'date': '2022-10-14', 'value': 3.55},
 {'date': '2022-10-15', 'value': 1.8095238095238098},
 {'date': '2022-10-16', 'value': 3.245833333333333},
 {'date': '2022-10-17', 'value': 7.437500000000001},
 {'date': '2022-10-18', 'value': 8.725},
 {'date': '2022-10-19', 'value': 8.137500000000001},
 {'date': '2022-10-20', 'value': 5.754166666666666},
 {'date': '2022-10-21', 'value': 5.483333333333332},
 {'date': '2022-10-22', 'value': 4.791666666666668},
 {'date': '2022-10-23', 'value': 4.054166666666668},
 {'date': '2022-10-24', 'value': 4.6},
 {'date': '2022-10-25', 'value': 4.386363636363635},
 {'date': '2022-10-26', 'value': 4.083333333333333},
 {'date': '2022-10-27', 'value': 7.162500000000001},
 {'date': '2022-10-28', 'value': 9.899999999999999},
 {'date': '2022-11-02', 'value': 7.84},
 {'date': '2022-11-03', 'value': 4.6863636363636365},
 {'date': '2022-11-04', 'value': 5.666666666666665},
 {'date': '2022-11-05', 'value': 7.545833333333332},
 {'date': '2022-11-06', 'value': 4.075},
 {'date': '2022-11-07', 'value': 5.762499999999999},
 {'date': '2022-11-08', 'value': 4.516666666666667},
 {'date': '2022-11-09', 'value': 6.604166666666667},
 {'date': '2022-11-10', 'value': 7.336842105263158},
 {'date': '2022-11-11', 'value': 9.908333333333333},
 {'date': '2022-11-12', 'value': 17.091666666666665},
 {'date': '2022-11-13', 'value': 15.595833333333337},
 {'date': '2022-11-14', 'value': 8.024999999999999},
 {'date': '2022-11-15', 'value': 4.3125},
 {'date': '2022-11-16', 'value': 4.445454545454545},
 {'date': '2022-11-17', 'value': 2.5130434782608697},
 {'date': '2022-11-18', 'value': 4.45},
 {'date': '2022-11-19', 'value': 8.10416666666667},
 {'date': '2022-11-20', 'value': 6.9624999999999995},
 {'date': '2022-11-21', 'value': 6.550000000000001},
 {'date': '2022-11-22', 'value': 4.4},
 {'date': '2022-11-24', 'value': 6.439130434782609},
 {'date': '2022-11-25', 'value': 9.850000000000001},
 {'date': '2022-11-26', 'value': 10.7125},
 {'date': '2022-11-27', 'value': 6.479166666666667},
 {'date': '2022-11-28', 'value': 6.5083333333333355},
 {'date': '2022-11-29', 'value': 7.587499999999999},
 {'date': '2022-11-30', 'value': 11.021739130434783},
 {'date': '2022-12-01', 'value': 18.220833333333335},
 {'date': '2022-12-02', 'value': 20.490909090909092},
 {'date': '2022-12-03', 'value': 17.3875},
 {'date': '2022-12-04', 'value': 18.3},
 {'date': '2022-12-05', 'value': 30.616666666666664},
 {'date': '2022-12-06', 'value': 23.254166666666666},
 {'date': '2022-12-07', 'value': 16.791666666666668},
 {'date': '2022-12-08', 'value': 13.252173913043478},
 {'date': '2022-12-09', 'value': 14.504545454545452},
 {'date': '2022-12-10', 'value': 11.7875},
 {'date': '2022-12-11', 'value': 12.991666666666669},
 {'date': '2022-12-12', 'value': 21.8125},
 {'date': '2022-12-13', 'value': 19.374999999999996},
 {'date': '2022-12-14', 'value': 24.733333333333334},
 {'date': '2022-12-15', 'value': 23.641666666666655},
 {'date': '2022-12-16', 'value': 26.375},
 {'date': '2022-12-17', 'value': 29.183333333333334},
 {'date': '2022-12-18', 'value': 22.058333333333334},
 {'date': '2022-12-19', 'value': 5.283333333333332},
 {'date': '2022-12-20', 'value': 5.375},
 {'date': '2022-12-21', 'value': 3.829166666666666},
 {'date': '2022-12-22', 'value': 6.1625000000000005},
 {'date': '2022-12-23', 'value': 2.4},
 {'date': '2022-12-24', 'value': 7.682608695652173},
 {'date': '2022-12-25', 'value': 4.804166666666666},
 {'date': '2022-12-26', 'value': 4.383333333333333},
 {'date': '2022-12-27', 'value': 5.7625},
 {'date': '2022-12-28', 'value': 3.1416666666666657},
 {'date': '2022-12-29', 'value': 6.216666666666666},
 {'date': '2022-12-30', 'value': 2.6500000000000004},
 {'date': '2022-12-31', 'value': 5.124999999999999},
 {'date': '2023-01-01', 'value': 7.495833333333334},
 {'date': '2023-01-02', 'value': 5.0},
 {'date': '2023-01-03', 'value': 4.626086956521739},
 {'date': '2023-01-04', 'value': 1.511111111111111},
 {'date': '2023-01-05', 'value': 2.9},
 {'date': '2023-01-06', 'value': 1.8727272727272726},
 {'date': '2023-01-07', 'value': 4.65},
 {'date': '2023-01-08', 'value': 3.3785714285714286},
 {'date': '2023-01-09', 'value': 4.633333333333333},
 {'date': '2023-01-10', 'value': 4.749999999999999},
 {'date': '2023-01-11', 'value': 2.55},
 {'date': '2023-01-16', 'value': 8.725},
 {'date': '2023-01-17', 'value': 11.225},
 {'date': '2023-01-18', 'value': 9.108333333333333},
 {'date': '2023-01-19', 'value': 9.845833333333337},
 {'date': '2023-01-20', 'value': 11.113636363636362},
 {'date': '2023-01-21', 'value': 14.533333333333337},
 {'date': '2023-01-22', 'value': 25.8},
 {'date': '2023-01-23', 'value': 16.84782608695652},
 {'date': '2023-01-24', 'value': 22.91},
 {'date': '2023-01-25', 'value': 30.699999999999992},
 {'date': '2023-01-26', 'value': 16.433333333333334},
 {'date': '2023-01-27', 'value': 7.120833333333334},
 {'date': '2023-01-28', 'value': 13.024999999999999},
 {'date': '2023-01-29', 'value': 19.691666666666666},
 {'date': '2023-01-30', 'value': 9.613636363636365},
 {'date': '2023-01-31', 'value': 9.850000000000001},
 {'date': '2023-02-01', 'value': 8.987499999999999},
 {'date': '2023-02-02', 'value': 9.3},
 {'date': '2023-02-14', 'value': 43.05652173913043},
 {'date': '2023-02-15', 'value': 41.208333333333336},
 {'date': '2023-02-16', 'value': 38.5},
 {'date': '2023-03-19', 'value': 6.595652173913043},
 {'date': '2023-03-20', 'value': 8.25},
 {'date': '2023-03-21', 'value': 4.77391304347826},
 {'date': '2023-03-22', 'value': 3.6041666666666665},
 {'date': '2023-03-23', 'value': 1.5},
 {'date': '2023-03-24', 'value': 3.7869565217391297},
 {'date': '2023-03-25', 'value': 6.004166666666666},
 {'date': '2023-03-26', 'value': 3.0434782608695645},
 {'date': '2023-03-27', 'value': 4.029166666666667},
 {'date': '2023-03-28', 'value': 5.2250000000000005},
 {'date': '2023-03-29', 'value': 5.141666666666668},
 {'date': '2023-03-30', 'value': 5.724999999999999},
 {'date': '2023-03-31', 'value': 6.379166666666666},
 {'date': '2023-04-01', 'value': 3.979166666666666},
 {'date': '2023-04-02', 'value': 6.391666666666667},
 {'date': '2023-04-03', 'value': 9.358333333333333},
 {'date': '2023-04-04', 'value': 7.483333333333334},
 {'date': '2023-04-05', 'value': 12.620833333333332},
 {'date': '2023-04-06', 'value': 9.573913043478258},
 {'date': '2023-04-07', 'value': 6.395833333333333},
 {'date': '2023-04-08', 'value': 7.591666666666666},
 {'date': '2023-04-09', 'value': 11.516666666666666},
 {'date': '2023-04-10', 'value': 6.608333333333333},
 {'date': '2023-04-11', 'value': 5.6000000000000005},
 {'date': '2023-04-12', 'value': 2.470833333333333},
 {'date': '2023-04-13', 'value': 5.308333333333333},
 {'date': '2023-04-14', 'value': 3.441666666666667},
 {'date': '2023-04-15', 'value': 4.908333333333333},
 {'date': '2023-04-16', 'value': 10.387499999999998},
 {'date': '2023-04-17', 'value': 16.162499999999998},
 {'date': '2023-04-18', 'value': 28.75000000000001},
 {'date': '2023-04-19', 'value': 11.137500000000001},
 {'date': '2023-04-20', 'value': 9.958333333333334},
 {'date': '2023-04-21', 'value': 13.229166666666666},
 {'date': '2023-04-22', 'value': 12.350000000000001},
 {'date': '2023-04-23', 'value': 3.7363636363636363},
 {'date': '2023-04-24', 'value': 6.499999999999999},
 {'date': '2023-04-26', 'value': 7.225000000000001},
 {'date': '2023-04-27', 'value': 7.712499999999999},
 {'date': '2023-04-28', 'value': 2.3625},
 {'date': '2023-04-29', 'value': 12.041666666666666},
 {'date': '2023-04-30', 'value': 11.200000000000003},
 {'date': '2023-05-01', 'value': 10.429166666666665},
 {'date': '2023-05-02', 'value': 6.095833333333331},
 {'date': '2023-05-03', 'value': 9.354166666666668},
 {'date': '2023-05-04', 'value': 5.345833333333332},
 {'date': '2023-05-05', 'value': 3.0500000000000003},
 {'date': '2023-05-06', 'value': 4.645833333333333},
 {'date': '2023-05-07', 'value': 5.1},
 {'date': '2023-05-08', 'value': 5.595833333333332},
 {'date': '2023-05-09', 'value': 2.379166666666667},
 {'date': '2023-05-10', 'value': 4.3625},
 {'date': '2023-05-11', 'value': 4.479166666666667},
 {'date': '2023-05-12', 'value': 4.970833333333334},
 {'date': '2023-05-13', 'value': 20.291666666666664},
 {'date': '2023-05-14', 'value': 16.529166666666665},
 {'date': '2023-05-15', 'value': 13.058333333333335},
 {'date': '2023-05-16', 'value': 4.1625000000000005},
 {'date': '2023-05-17', 'value': 5.583333333333333},
 {'date': '2023-05-18', 'value': 7.783333333333331},
 {'date': '2023-05-19', 'value': 9.887499999999998},
 {'date': '2023-05-20', 'value': 9.545833333333334},
 {'date': '2023-05-21', 'value': 9.941666666666665},
 {'date': '2023-05-22', 'value': 10.933333333333335},
 {'date': '2023-05-23', 'value': 9.85},
 {'date': '2023-05-24', 'value': 6.345833333333334},
 {'date': '2023-05-25', 'value': 10.845833333333333},
 {'date': '2023-05-26', 'value': 13.34166666666667},
 {'date': '2023-05-27', 'value': 10.6375},
 {'date': '2023-05-28', 'value': 11.816666666666665},
 {'date': '2023-05-29', 'value': 11.008333333333333},
 {'date': '2023-05-30', 'value': 9.525},
 {'date': '2023-05-31', 'value': 9.629166666666666},
 {'date': '2023-06-01', 'value': 14.85},
 {'date': '2023-06-02', 'value': 11.220833333333331},
 {'date': '2023-06-03', 'value': 11.441666666666668},
 {'date': '2023-06-04', 'value': 4.179166666666668},
 {'date': '2023-06-05', 'value': 7.387499999999998},
 {'date': '2023-06-06', 'value': 11.262500000000001},
 {'date': '2023-06-07', 'value': 13.58333333333333},
 {'date': '2023-06-08', 'value': 13.804166666666665},
 {'date': '2023-06-09', 'value': 13.966666666666667},
 {'date': '2023-06-10', 'value': 8.895833333333334},
 {'date': '2023-06-11', 'value': 11.241666666666665},
 {'date': '2023-06-12', 'value': 7.808333333333333},
 {'date': '2023-06-13', 'value': 9.420833333333333},
 {'date': '2023-06-14', 'value': 13.245833333333335},
 {'date': '2023-06-15', 'value': 12.241666666666665},
 {'date': '2023-06-16', 'value': 11.558333333333335},
 {'date': '2023-06-17', 'value': 10.737499999999999},
 {'date': '2023-06-18', 'value': 5.291666666666666},
 {'date': '2023-06-19', 'value': 8.433333333333335},
 {'date': '2023-06-20', 'value': 7.947826086956522},
 {'date': '2023-06-21', 'value': 4.3625},
 {'date': '2023-06-22', 'value': 4.470833333333333},
 {'date': '2023-06-23', 'value': 4.654166666666666},
 {'date': '2023-06-24', 'value': 4.849999999999999},
 {'date': '2023-06-25', 'value': 6.0625},
 {'date': '2023-06-26', 'value': 5.104166666666666},
 {'date': '2023-06-27', 'value': 5.291666666666667},
 {'date': '2023-06-28', 'value': 12.366666666666667},
 {'date': '2023-06-29', 'value': 15.116666666666667},
 {'date': '2023-06-30', 'value': 5.095833333333333},
 {'date': '2023-07-01', 'value': 8.520833333333334},
 {'date': '2023-07-02', 'value': 16.179166666666664},
 {'date': '2023-07-03', 'value': 7.1791666666666645},
 {'date': '2023-07-04', 'value': 5.095833333333332},
 {'date': '2023-07-05', 'value': 4.6625},
 {'date': '2023-07-06', 'value': 4.095833333333333},
 {'date': '2023-07-07', 'value': 6.633333333333333},
 {'date': '2023-07-08', 'value': 5.633333333333334},
 {'date': '2023-07-09', 'value': 7.766666666666667},
 {'date': '2023-07-10', 'value': 4.2749999999999995},
 {'date': '2023-07-11', 'value': 4.045833333333333},
 {'date': '2023-07-12', 'value': 3.554166666666667},
 {'date': '2023-07-13', 'value': 5.2875},
 {'date': '2023-07-14', 'value': 10.509090909090911},
 {'date': '2023-07-16', 'value': 2.2},
 {'date': '2023-07-17', 'value': 3.5166666666666675},
 {'date': '2023-07-18', 'value': 4.55},
 {'date': '2023-07-19', 'value': 4.208333333333334},
 {'date': '2023-07-20', 'value': 3.795833333333334},
 {'date': '2023-07-21', 'value': 4.650000000000001},
 {'date': '2023-07-22', 'value': 5.7749999999999995},
 {'date': '2023-07-23', 'value': 3.966666666666667},
 {'date': '2023-07-24', 'value': 2.316666666666667},
 {'date': '2023-07-25', 'value': 2.7791666666666663},
 {'date': '2023-07-26', 'value': 3.054166666666666},
 {'date': '2023-07-27', 'value': 2.5727272727272728},
 {'date': '2023-07-28', 'value': 1.508333333333333},
 {'date': '2023-07-29', 'value': 2.2583333333333337},
 {'date': '2023-07-30', 'value': 4.104166666666667},
 {'date': '2023-07-31', 'value': 3.9250000000000007},
 {'date': '2023-08-01', 'value': 3.5791666666666653},
 {'date': '2023-08-02', 'value': 1.9125000000000003},
 {'date': '2023-08-03', 'value': 2.145454545454546},
 {'date': '2023-08-04', 'value': 5.387499999999999},
 {'date': '2023-08-05', 'value': 3.586363636363636},
 {'date': '2023-08-06', 'value': 2.4208333333333334},
 {'date': '2023-08-07', 'value': 3.2090909090909094},
 {'date': '2023-08-08', 'value': 3.220833333333333},
 {'date': '2023-08-09', 'value': 3.329166666666666},
 {'date': '2023-08-10', 'value': 4.695833333333334},
 {'date': '2023-08-11', 'value': 4.429166666666667},
 {'date': '2023-08-12', 'value': 2.8874999999999997},
 {'date': '2023-08-13', 'value': 4.800000000000002},
 {'date': '2023-08-14', 'value': 3.8624999999999994},
 {'date': '2023-08-15', 'value': 3.095833333333333},
 {'date': '2023-08-16', 'value': 2.8470588235294123},
 {'date': '2023-08-17', 'value': 6.804166666666666},
 {'date': '2023-08-18', 'value': 12.235000000000003},
 {'date': '2023-08-19', 'value': 4.594444444444445},
 {'date': '2023-08-20', 'value': 3.686363636363636},
 {'date': '2023-08-21', 'value': 3.1849999999999996},
 {'date': '2023-08-22', 'value': 3.713636363636364},
 {'date': '2023-08-23', 'value': 4.118181818181818},
 {'date': '2023-08-24', 'value': 6.968181818181819},
 {'date': '2023-08-25', 'value': 11.49090909090909},
 {'date': '2023-08-27', 'value': 3.1},
 {'date': '2023-08-28', 'value': 2.4625},
 {'date': '2023-08-29', 'value': 3.0},
 {'date': '2023-08-30', 'value': 3.975},
 {'date': '2023-08-31', 'value': 3.6833333333333336},
 {'date': '2023-09-01', 'value': 1.9958333333333336},
 {'date': '2023-09-02', 'value': 2.4916666666666663},
 {'date': '2023-09-03', 'value': 4.008333333333334},
 {'date': '2023-09-04', 'value': 4.2875},
 {'date': '2023-09-05', 'value': 6.934782608695652},
 {'date': '2023-09-06', 'value': 10.3625},
 {'date': '2023-09-07', 'value': 7.037499999999999},
 {'date': '2023-09-08', 'value': 9.566666666666668},
 {'date': '2023-09-09', 'value': 10.336363636363636},
 {'date': '2023-09-10', 'value': 10.500000000000002},
 {'date': '2023-09-11', 'value': 11.08333333333333},
 {'date': '2023-09-12', 'value': 6.691666666666669},
 {'date': '2023-09-13', 'value': 3.670833333333334},
 {'date': '2023-09-14', 'value': 4.75},
 {'date': '2023-09-15', 'value': 5.3},
 {'date': '2023-09-16', 'value': 6.129166666666666},
 {'date': '2023-09-17', 'value': 6.529166666666666},
 {'date': '2023-09-18', 'value': 3.7624999999999997},
 {'date': '2023-09-19', 'value': 4.805},
 {'date': '2023-09-20', 'value': 3.7624999999999993},
 {'date': '2023-09-21', 'value': 2.2791666666666672},
 {'date': '2023-09-22', 'value': 1.9041666666666668},
 {'date': '2023-09-23', 'value': 3.504166666666666},
 {'date': '2023-09-24', 'value': 4.625},
 {'date': '2023-09-25', 'value': 4.2},
 {'date': '2023-09-26', 'value': 4.3},
 {'date': '2023-09-27', 'value': 6.168181818181819},
 {'date': '2023-09-28', 'value': 6.773913043478259},
 {'date': '2023-09-29', 'value': 5.25},
 {'date': '2023-09-30', 'value': 7.391666666666666},
 {'date': '2023-10-01', 'value': 8.836363636363636},
 {'date': '2023-10-02', 'value': 12.72272727272727},
 {'date': '2023-10-03', 'value': 5.054166666666667},
 {'date': '2023-10-04', 'value': 4.818181818181818},
 {'date': '2023-10-05', 'value': 5.35},
 {'date': '2023-10-06', 'value': 5.729166666666667},
 {'date': '2023-10-07', 'value': 5.336363636363637},
 {'date': '2023-10-08', 'value': 8.28181818181818},
 {'date': '2023-10-09', 'value': 8.595833333333331},
 {'date': '2023-10-10', 'value': 8.32272727272727},
 {'date': '2023-10-11', 'value': 9.355},
 {'date': '2023-10-12', 'value': 8.254166666666666},
 {'date': '2023-10-13', 'value': 15.85},
 {'date': '2023-10-14', 'value': 3.5454545454545463},
 {'date': '2023-10-15', 'value': 2.7863636363636366},
 {'date': '2023-10-16', 'value': 4.04090909090909},
 {'date': '2023-10-17', 'value': 5.450000000000001},
 {'date': '2023-10-18', 'value': 4.995454545454546},
 {'date': '2023-10-19', 'value': 4.691666666666667},
 {'date': '2023-10-20', 'value': 2.6227272727272726},
 {'date': '2023-10-21', 'value': 3.0291666666666655},
 {'date': '2023-10-22', 'value': 4.109090909090909},
 {'date': '2023-10-23', 'value': 6.290909090909091},
 {'date': '2023-10-24', 'value': 4.215000000000002},
 {'date': '2023-10-25', 'value': 2.375},
 {'date': '2023-10-26', 'value': 6.054166666666667},
 {'date': '2023-10-27', 'value': 4.2250000000000005},
 {'date': '2023-10-28', 'value': 3.0708333333333333},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [12]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_pm25_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_pm25_mean
0    2016-11-21          7.577060
1    2016-11-22         11.716680
2    2016-11-23         13.452645
3    2016-11-25         21.110799
4    2016-11-26         20.839287
...         ...               ...
3117 2026-02-24          6.403230
3118 2026-02-25          8.447074
3119 2026-02-26         11.604657
3120 2026-02-27         10.344162
3121 2026-02-28          7.094505

[3122 rows x 2 columns]

### Convert dataframe to csv

In [15]:
france_daily[["date", "france_pm25_mean"]].to_csv(
    "france_pm10_daily_2016_2026.csv",
    index=False
)

# NO2

In [18]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "FR",   # only consider stations located in France
    "parameters_id": 5,   # NO2
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_no2 = df_sorted.head(200)

df_top_no2

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
29,2707,Evreux Centre,ÉVREUX,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275240, 'name': 'no µg/m³', 'paramete...","{'latitude': 49.02133999977332, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[1.1483189995666427, 49.02133999977332, 1.1483...",None,2016-11-21 11:00:00+00:00,2026-03-04 19:00:00+00:00
35,2720,Montpellier Prés d'Arènes,MONTPELLIER,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275188, 'name': 'no µg/m³', 'paramete...","{'latitude': 43.591500000324274, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[3.886809999908339, 43.591500000324274, 3.8868...",None,2016-11-21 11:00:00+00:00,2026-03-04 19:00:00+00:00
53,3479,Gonfreville l Orcher,GONFREVILLE-L'ORCHER,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 24890, 'name': 'co µg/m³', 'parameter'...","{'latitude': 49.50273000006004, 'longitude': 0...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[0.232485999671531, 49.50273000006004, 0.23248...",None,2016-11-21 11:00:00+00:00,2026-03-04 19:00:00+00:00
57,3491,Atton,ATTON,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275482, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.88638699976619, 'longitude': 6...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.0936109998895915, 48.88638699976619, 6.0936...",None,2016-11-21 11:00:00+00:00,2026-03-04 19:00:00+00:00
119,3609,Thionville-Centre,THIONVILLE,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275111, 'name': 'no µg/m³', 'paramete...","{'latitude': 49.35833700015846, 'longitude': 6...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.156942000146252, 49.35833700015846, 6.15694...",None,2016-11-21 11:00:00+00:00,2026-03-04 19:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,3799,SAINT EXUPERY,PUSIGNAN,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274417, 'name': 'no µg/m³', 'paramete...","{'latitude': 45.75329999969274, 'longitude': 5...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[5.072199999985248, 45.75329999969274, 5.07219...",None,2016-11-21 12:00:00+00:00,2026-03-04 18:00:00+00:00
275,3805,LOVERCHY,ANNECY,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275075, 'name': 'no µg/m³', 'paramete...","{'latitude': 45.89527999992216, 'longitude': 6...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.118333000326252, 45.89527999992216, 6.11833...",None,2016-11-21 12:00:00+00:00,2026-03-04 18:00:00+00:00
289,3824,Albertville,ALBERTVILLE,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275066, 'name': 'no µg/m³', 'paramete...","{'latitude': 45.67500000012494, 'longitude': 6...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.389722000443968, 45.67500000012494, 6.38972...",None,2016-11-21 12:00:00+00:00,2026-03-04 18:00:00+00:00
369,4093,Quai des Celestins,PARIS 4E ARRONDISSEMENT,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274737, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.852779999795274, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[2.3605559999190917, 48.852779999795274, 2.360...",None,2016-11-21 12:00:00+00:00,2026-03-04 13:00:00+00:00
237,3757,NOVEL,ANNECY,Europe/Paris,"{'id': 22, 'code': 'FR', 'name': 'France'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275345, 'name': 'no µg/m³', 'paramete...","{'latitude': 45.91694300011561, 'longitude': 6...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[6.135556000416689, 45.91694300011561, 6.13555...",None,2016-11-21 12:00:00+00:00,2025-12-19 09:00:00+00:00

In [19]:
rows = []

for _, station in df_top_no2.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur NO2 behalten
        if sensor["parameter"]["id"] == 5:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_no2_sensors = pd.DataFrame(rows)

df_no2_sensors

     station_id               station_name  sensor_id sensor_name
0          2707              Evreux Centre       9837   no2 µg/m³
1          2720  Montpellier Prés d'Arènes       5673   no2 µg/m³
2          3479       Gonfreville l Orcher      24889   no2 µg/m³
3          3491                      Atton       7754   no2 µg/m³
4          3609          Thionville-Centre       7965   no2 µg/m³
..          ...                        ...        ...         ...
195        3799              SAINT EXUPERY       8532   no2 µg/m³
196        3805                   LOVERCHY       8552   no2 µg/m³
197        3824                Albertville       8632   no2 µg/m³
198        4093         Quai des Celestins       9671   no2 µg/m³
199        3757                      NOVEL       8399   no2 µg/m³

[200 rows x 4 columns]

In [20]:
sensor_ids = df_no2_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

200

[9837,
 5673,
 24889,
 7754,
 7965,
 8017,
 8163,
 8267,
 8270,
 8381,
 9758,
 9761,
 9859,
 9810,
 9821,
 15304,
 9885,
 5650,
 5669,
 7745,
 8425,
 8104,
 8422,
 8194,
 8216,
 8396,
 9763,
 7789,
 8097,
 8314,
 8499,
 8419,
 5651,
 7772,
 7761,
 1314202,
 7784,
 7998,
 8114,
 8137,
 8374,
 8480,
 8516,
 8533,
 8602,
 8599,
 9891,
 9730,
 9819,
 8082,
 8024,
 8591,
 7929,
 7977,
 7982,
 8105,
 8118,
 8153,
 8346,
 8519,
 8623,
 9870,
 9788,
 7769,
 8193,
 5645,
 20610,
 7753,
 9705,
 9829,
 9694,
 9803,
 15419,
 9846,
 9690,
 2960215,
 9804,
 9806,
 9812,
 9832,
 9836,
 9855,
 9757,
 8633,
 8429,
 8150,
 9780,
 8161,
 8198,
 8064,
 8574,
 7781,
 8629,
 7987,
 9873,
 8182,
 8262,
 9774,
 9112,
 8414,
 7765,
 9807,
 9770,
 5656,
 5649,
 5620,
 5606,
 5654,
 8427,
 8617,
 8465,
 8621,
 8333,
 8543,
 8647,
 7991,
 8609,
 8126,
 7995,
 1298731,
 8004,
 8008,
 8073,
 8254,
 8288,
 8296,
 8310,
 8320,
 8325,
 8357,
 8363,
 8367,
 8455,
 8494,
 8582,
 8611,
 8636,
 9529,
 9542,
 9643,
 9731,
 9716,
 9609,
 9629,
 9680,
 9625,
 9616,
 9637,
 9863,
 9652,
 9672,
 9693,
 9900,
 9747,
 9765,
 9768,
 9778,
 9779,
 9817,
 9827,
 9850,
 9853,
 9860,
 9897,
 5578,
 8537,
 5587,
 5605,
 5611,
 8556,
 8340,
 7806,
 7858,
 7920,
 8001,
 8012,
 8015,
 8033,
 8029,
 8041,
 8070,
 8079,
 8129,
 8132,
 8157,
 8168,
 8186,
 8260,
 8259,
 8339,
 8351,
 8400,
 8405,
 8484,
 8523,
 8532,
 8552,
 8632,
 9671,
 8399]

In [21]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 9837: Seite 1, 1000 Ergebnisse
Sensor 9837: Seite 2, 1000 Ergebnisse
Sensor 9837: Seite 3, 848 Ergebnisse
Sensor 5673: Seite 1, 1000 Ergebnisse
Sensor 5673: Seite 2, 1000 Ergebnisse
Sensor 5673: Seite 3, 912 Ergebnisse
Sensor 24889: Seite 1, 1000 Ergebnisse
Sensor 24889: Seite 2, 1000 Ergebnisse
Sensor 24889: Seite 3, 351 Ergebnisse
Sensor 7754: Seite 1, 1000 Ergebnisse
Sensor 7754: Seite 2, 1000 Ergebnisse
Sensor 7754: Seite 3, 762 Ergebnisse
Sensor 7965: Seite 1, 1000 Ergebnisse
Sensor 7965: Seite 2, 1000 Ergebnisse
Sensor 7965: Seite 3, 880 Ergebnisse
Sensor 8017: Seite 1, 1000 Ergebnisse
Sensor 8017: Seite 2, 1000 Ergebnisse
Sensor 8017: Seite 3, 1000 Ergebnisse
Sensor 8017: Seite 4, 3 Ergebnisse
Sensor 8163: Seite 1, 966 Ergebnisse
Sensor 8267: Seite 1, 1000 Ergebnisse
Sensor 8267: Seite 2, 1000 Ergebnisse
Sensor 8267: Seite 3, 878 Ergebnisse
Sensor 8270: Seite 1, 1000 Ergebnisse
Sensor 8270: Seite 2, 1000 Ergebnisse
Sensor 8270: Seite 3, 951 Ergebnisse
Sensor 8381: Seite 1, 1000 Ergebnisse
Sensor 8381: Seite 2, 1000 Ergebnisse
Sensor 8381: Seite 3, 1000 Ergebnisse
Sensor 8381: Seite 4, 56 Ergebnisse
Sensor 9758: Seite 1, 1000 Ergebnisse
Sensor 9758: Seite 2, 1000 Ergebnisse
Sensor 9758: Seite 3, 876 Ergebnisse
Sensor 9761: Seite 1, 1000 Ergebnisse
Sensor 9761: Seite 2, 1000 Ergebnisse
Sensor 9761: Seite 3, 877 Ergebnisse
Sensor 9859: Seite 1, 1000 Ergebnisse
Sensor 9859: Seite 2, 1000 Ergebnisse
Sensor 9859: Seite 3, 872 Ergebnisse
Sensor 9810: Seite 1, 1000 Ergebnisse
Sensor 9810: Seite 2, 1000 Ergebnisse
Sensor 9810: Seite 3, 870 Ergebnisse
Sensor 9821: Seite 1, 1000 Ergebnisse
Sensor 9821: Seite 2, 1000 Ergebnisse
Sensor 9821: Seite 3, 830 Ergebnisse
Sensor 15304: Seite 1, 1000 Ergebnisse
Sensor 15304: Seite 2, 1000 Ergebnisse
Sensor 15304: Seite 3, 605 Ergebnisse
Sensor 9885: Seite 1, 1000 Ergebnisse
Sensor 9885: Seite 2, 1000 Ergebnisse
Sensor 9885: Seite 3, 1000 Ergebnisse
Sensor 9885: Seite 4, 27 Ergebnisse
Sensor 5650: Seite 1, 1000 Ergebnisse
Sensor 5650: Seite 2, 1000 Ergebnisse
Sensor 5650: Seite 3, 870 Ergebnisse
Sensor 5669: Seite 1, 1000 Ergebnisse
Sensor 5669: Seite 2, 1000 Ergebnisse
Sensor 5669: Seite 3, 862 Ergebnisse
Sensor 7745: Seite 1, 1000 Ergebnisse
Sensor 7745: Seite 2, 1000 Ergebnisse
Sensor 7745: Seite 3, 838 Ergebnisse
Sensor 8425: Seite 1, 1000 Ergebnisse
Sensor 8425: Seite 2, 1000 Ergebnisse
Sensor 8425: Seite 3, 938 Ergebnisse
Sensor 8104: Seite 1, 1000 Ergebnisse
Sensor 8104: Seite 2, 1000 Ergebnisse
Sensor 8104: Seite 3, 848 Ergebnisse
Sensor 8422: Seite 1, 1000 Ergebnisse
Sensor 8422: Seite 2, 1000 Ergebnisse
Sensor 8422: Seite 3, 801 Ergebnisse
Sensor 8194: Seite 1, 1000 Ergebnisse
Sensor 8194: Seite 2, 1000 Ergebnisse
Sensor 8194: Seite 3, 869 Ergebnisse
Sensor 8216: Seite 1, 1000 Ergebnisse
Sensor 8216: Seite 2, 1000 Ergebnisse
Sensor 8216: Seite 3, 946 Ergebnisse
Sensor 8396: Seite 1, 1000 Ergebnisse
Sensor 8396: Seite 2, 1000 Ergebnisse
Sensor 8396: Seite 3, 874 Ergebnisse
Sensor 9763: Seite 1, 1000 Ergebnisse
Sensor 9763: Seite 2, 1000 Ergebnisse
Sensor 9763: Seite 3, 840 Ergebnisse
Sensor 7789: Seite 1, 1000 Ergebnisse
Sensor 7789: Seite 2, 1000 Ergebnisse
Sensor 7789: Seite 3, 646 Ergebnisse
Sensor 8097: Seite 1, 1000 Ergebnisse
Sensor 8097: Seite 2, 1000 Ergebnisse
Sensor 8097: Seite 3, 851 Ergebnisse
Sensor 8314: Seite 1, 1000 Ergebnisse
Sensor 8314: Seite 2, 1000 Ergebnisse
Sensor 8314: Seite 3, 848 Ergebnisse
Sensor 8499: Seite 1, 1000 Ergebnisse
Sensor 8499: Seite 2, 1000 Ergebnisse
Sensor 8499: Seite 3, 847 Ergebnisse
Sensor 8419: Seite 1, 752 Ergebnisse
Sensor 5651: Seite 1, 1000 Ergebnisse
Sensor 5651: Seite 2, 329 Ergebnisse
Sensor 7772: Seite 1, 1000 Ergebnisse
Sensor 7772: Seite 2, 176 Ergebnisse
Sensor 7761: Seite 1, 1000 Ergebnisse
Sensor 7761: Seite 2, 1000 Ergebnisse
Sensor 7761: Seite 3, 571 Ergebnisse
Sensor 1314202: Seite 1, 1000 Ergebnisse
Sensor 1314202: Seite 2, 350 Ergebnisse
Sensor 7784: Seite 1, 1000 Ergebnisse
Sensor 7784: Seite 2, 1000 Ergebnisse
Sensor 7784: Seite 3, 574 Ergebnisse
Sensor 7998: Seite 1, 1000 Ergebnisse
Sensor 7998: Seite 2, 1000 Ergebnisse
Sensor 7998: Seite 3, 735 Ergebnisse
Sensor 8114: Seite 1, 1000 Ergebnisse
Sensor 8114: Seite 2, 1000 Ergebnisse
Sensor 8114: Seite 3, 774 Ergebnisse
Sensor 8137: Seite 1, 1000 Ergebnisse
Sensor 8137: Seite 2, 1000 Ergebnisse
Sensor 8137: Seite 3, 758 Ergebnisse
Sensor 8374: Seite 1, 1000 Ergebnisse
Sensor 8374: Seite 2, 1000 Ergebnisse
Sensor 8374: Seite 3, 761 Ergebnisse
Sensor 8480: Seite 1, 1000 Ergebnisse
Sensor 8480: Seite 2, 1000 Ergebnisse
Sensor 8480: Seite 3, 768 Ergebnisse
Sensor 8516: Seite 1, 1000 Ergebnisse
Sensor 8516: Seite 2, 1000 Ergebnisse
Sensor 8516: Seite 3, 746 Ergebnisse
Sensor 8533: Seite 1, 1000 Ergebnisse
Sensor 8533: Seite 2, 1000 Ergebnisse
Sensor 8533: Seite 3, 768 Ergebnisse
Sensor 8602: Seite 1, 1000 Ergebnisse
Sensor 8602: Seite 2, 1000 Ergebnisse
Sensor 8602: Seite 3, 768 Ergebnisse
Sensor 8599: Seite 1, 1000 Ergebnisse
Sensor 8599: Seite 2, 1000 Ergebnisse
Sensor 8599: Seite 3, 769 Ergebnisse
Sensor 9891: Seite 1, 1000 Ergebnisse
Sensor 9891: Seite 2, 1000 Ergebnisse
Sensor 9891: Seite 3, 508 Ergebnisse
Sensor 9730: Seite 1, 1000 Ergebnisse
Sensor 9730: Seite 2, 1000 Ergebnisse
Sensor 9730: Seite 3, 278 Ergebnisse
Sensor 9819: Seite 1, 1000 Ergebnisse
Sensor 9819: Seite 2, 1000 Ergebnisse
Sensor 9819: Seite 3, 425 Ergebnisse
Sensor 8082: Seite 1, 1000 Ergebnisse
Sensor 8082: Seite 2, 1000 Ergebnisse
Sensor 8082: Seite 3, 365 Ergebnisse
Sensor 8024: Seite 1, 1000 Ergebnisse
Sensor 8024: Seite 2, 1000 Ergebnisse
Sensor 8024: Seite 3, 226 Ergebnisse
Sensor 8591: Seite 1, 1000 Ergebnisse
Sensor 8591: Seite 2, 1000 Ergebnisse
Sensor 8591: Seite 3, 297 Ergebnisse
Sensor 7929: Seite 1, 1000 Ergebnisse
Sensor 7929: Seite 2, 1000 Ergebnisse
Sensor 7929: Seite 3, 269 Ergebnisse
Sensor 7977: Seite 1, 1000 Ergebnisse
Sensor 7977: Seite 2, 1000 Ergebnisse
Sensor 7977: Seite 3, 111 Ergebnisse
Sensor 7982: Seite 1, 1000 Ergebnisse
Sensor 7982: Seite 2, 1000 Ergebnisse
Sensor 7982: Seite 3, 92 Ergebnisse
Sensor 8105: Seite 1, 1000 Ergebnisse
Sensor 8105: Seite 2, 1000 Ergebnisse
Sensor 8105: Seite 3, 239 Ergebnisse
Sensor 8118: Seite 1, 1000 Ergebnisse
Sensor 8118: Seite 2, 1000 Ergebnisse
Sensor 8118: Seite 3, 287 Ergebnisse
Sensor 8153: Seite 1, 1000 Ergebnisse
Sensor 8153: Seite 2, 1000 Ergebnisse
Sensor 8153: Seite 3, 92 Ergebnisse
Sensor 8346: Seite 1, 1000 Ergebnisse
Sensor 8346: Seite 2, 1000 Ergebnisse
Sensor 8346: Seite 3, 293 Ergebnisse
Sensor 8519: Seite 1, 1000 Ergebnisse
Sensor 8519: Seite 2, 1000 Ergebnisse
Sensor 8519: Seite 3, 211 Ergebnisse
Sensor 8623: Seite 1, 1000 Ergebnisse
Sensor 8623: Seite 2, 1000 Ergebnisse
Sensor 8623: Seite 3, 292 Ergebnisse
Sensor 9870: Seite 1, 1000 Ergebnisse
Sensor 9870: Seite 2, 1000 Ergebnisse
Sensor 9870: Seite 3, 114 Ergebnisse
Sensor 9788: Seite 1, 1000 Ergebnisse
Sensor 9788: Seite 2, 1000 Ergebnisse
Sensor 9788: Seite 3, 123 Ergebnisse
Sensor 7769: Seite 1, 1000 Ergebnisse
Sensor 7769: Seite 2, 923 Ergebnisse
Sensor 8193: Seite 1, 1000 Ergebnisse
Sensor 8193: Seite 2, 1000 Ergebnisse
Sensor 8193: Seite 3, 174 Ergebnisse
Sensor 5645: Seite 1, 1000 Ergebnisse
Sensor 5645: Seite 2, 1000 Ergebnisse
Sensor 5645: Seite 3, 243 Ergebnisse
Sensor 20610: Seite 1, 342 Ergebnisse
Sensor 7753: Seite 1, 1000 Ergebnisse
Sensor 7753: Seite 2, 942 Ergebnisse
Sensor 9705: Seite 1, 1000 Ergebnisse
Sensor 9705: Seite 2, 992 Ergebnisse
Sensor 9829: Seite 1, 1000 Ergebnisse
Sensor 9829: Seite 2, 1000 Ergebnisse
Sensor 9829: Seite 3, 123 Ergebnisse
Sensor 9694: Seite 1, 1000 Ergebnisse
Sensor 9694: Seite 2, 851 Ergebnisse
Sensor 9803: Seite 1, 1000 Ergebnisse
Sensor 9803: Seite 2, 1000 Ergebnisse
Sensor 9803: Seite 3, 121 Ergebnisse
Sensor 15419: Seite 1, 1000 Ergebnisse
Sensor 15419: Seite 2, 841 Ergebnisse
Sensor 9846: Seite 1, 1000 Ergebnisse
Sensor 9846: Seite 2, 1000 Ergebnisse
Sensor 9846: Seite 3, 118 Ergebnisse
Sensor 9690: Seite 1, 1000 Ergebnisse
Sensor 9690: Seite 2, 939 Ergebnisse
Sensor 2960215: Seite 1, 242 Ergebnisse
Sensor 9804: Seite 1, 1000 Ergebnisse
Sensor 9804: Seite 2, 1000 Ergebnisse
Sensor 9804: Seite 3, 146 Ergebnisse
Sensor 9806: Seite 1, 1000 Ergebnisse
Sensor 9806: Seite 2, 1000 Ergebnisse
Sensor 9806: Seite 3, 141 Ergebnisse
Sensor 9812: Seite 1, 1000 Ergebnisse
Sensor 9812: Seite 2, 1000 Ergebnisse
Sensor 9812: Seite 3, 156 Ergebnisse
Sensor 9832: Seite 1, 1000 Ergebnisse
Sensor 9832: Seite 2, 1000 Ergebnisse
Sensor 9832: Seite 3, 66 Ergebnisse
Sensor 9836: Seite 1, 1000 Ergebnisse
Sensor 9836: Seite 2, 1000 Ergebnisse
Sensor 9836: Seite 3, 159 Ergebnisse
Sensor 9855: Seite 1, 1000 Ergebnisse
Sensor 9855: Seite 2, 1000 Ergebnisse
Sensor 9855: Seite 3, 214 Ergebnisse
Sensor 9757: Seite 1, 907 Ergebnisse
Sensor 8633: Seite 1, 1000 Ergebnisse
Sensor 8633: Seite 2, 1000 Ergebnisse
Sensor 8633: Seite 3, 271 Ergebnisse
Sensor 8429: Seite 1, 1000 Ergebnisse
Sensor 8429: Seite 2, 1000 Ergebnisse
Sensor 8429: Seite 3, 171 Ergebnisse
Sensor 8150: Seite 1, 1000 Ergebnisse
Sensor 8150: Seite 2, 1000 Ergebnisse
Sensor 8150: Seite 3, 47 Ergebnisse
Sensor 9780: Seite 1, 1000 Ergebnisse
Sensor 9780: Seite 2, 856 Ergebnisse
Sensor 8161: Seite 1, 1000 Ergebnisse
Sensor 8161: Seite 2, 890 Ergebnisse
Sensor 8198: Seite 1, 1000 Ergebnisse
Sensor 8198: Seite 2, 788 Ergebnisse
Sensor 8064: Seite 1, 1000 Ergebnisse
Sensor 8064: Seite 2, 495 Ergebnisse
Sensor 8574: Seite 1, 1000 Ergebnisse
Sensor 8574: Seite 2, 494 Ergebnisse
Sensor 7781: Seite 1, 1000 Ergebnisse
Sensor 7781: Seite 2, 230 Ergebnisse
Sensor 8629: Seite 1, 1000 Ergebnisse
Sensor 8629: Seite 2, 327 Ergebnisse
Sensor 7987: Seite 1, 1000 Ergebnisse
Sensor 7987: Seite 2, 188 Ergebnisse
Sensor 9873: Seite 1, 1000 Ergebnisse
Sensor 9873: Seite 2, 294 Ergebnisse
Sensor 8182: Seite 1, 764 Ergebnisse
Sensor 8262: Seite 1, 1000 Ergebnisse
Sensor 8262: Seite 2, 15 Ergebnisse
Sensor 9774: Seite 1, 980 Ergebnisse
Sensor 9112: Seite 1, 965 Ergebnisse
Sensor 8414: Seite 1, 570 Ergebnisse
Sensor 7765: Seite 1, 78 Ergebnisse
Sensor 9807: Seite 1, 223 Ergebnisse
Sensor 9770: Seite 1, 147 Ergebnisse
Sensor 5656: Seite 1, 10 Ergebnisse
Sensor 5649: Seite 1, 13 Ergebnisse
Sensor 5620: Seite 1, 1000 Ergebnisse
Sensor 5620: Seite 2, 1000 Ergebnisse
Sensor 5620: Seite 3, 753 Ergebnisse
Sensor 5606: Seite 1, 1000 Ergebnisse
Sensor 5606: Seite 2, 1000 Ergebnisse
Sensor 5606: Seite 3, 560 Ergebnisse
Sensor 5654: Seite 1, 1000 Ergebnisse
Sensor 5654: Seite 2, 1000 Ergebnisse
Sensor 5654: Seite 3, 993 Ergebnisse
Sensor 8427: Seite 1, 1000 Ergebnisse
Sensor 8427: Seite 2, 1000 Ergebnisse
Sensor 8427: Seite 3, 853 Ergebnisse
Sensor 8617: Seite 1, 1000 Ergebnisse
Sensor 8617: Seite 2, 1000 Ergebnisse
Sensor 8617: Seite 3, 843 Ergebnisse
Sensor 8465: Seite 1, 1000 Ergebnisse
Sensor 8465: Seite 2, 1000 Ergebnisse
Sensor 8465: Seite 3, 812 Ergebnisse
Sensor 8621: Seite 1, 1000 Ergebnisse
Sensor 8621: Seite 2, 1000 Ergebnisse
Sensor 8621: Seite 3, 869 Ergebnisse
Sensor 8333: Seite 1, 1000 Ergebnisse
Sensor 8333: Seite 2, 1000 Ergebnisse
Sensor 8333: Seite 3, 881 Ergebnisse
Sensor 8543: Seite 1, 1000 Ergebnisse
Sensor 8543: Seite 2, 1000 Ergebnisse
Sensor 8543: Seite 3, 746 Ergebnisse
Sensor 8647: Seite 1, 1000 Ergebnisse
Sensor 8647: Seite 2, 1000 Ergebnisse
Sensor 8647: Seite 3, 830 Ergebnisse
Sensor 7991: Seite 1, 1000 Ergebnisse
Sensor 7991: Seite 2, 1000 Ergebnisse
Sensor 7991: Seite 3, 858 Ergebnisse
Sensor 8609: Seite 1, 1000 Ergebnisse
Sensor 8609: Seite 2, 1000 Ergebnisse
Sensor 8609: Seite 3, 825 Ergebnisse
Sensor 8126: Seite 1, 1000 Ergebnisse
Sensor 8126: Seite 2, 1000 Ergebnisse
Sensor 8126: Seite 3, 851 Ergebnisse
Sensor 7995: Seite 1, 844 Ergebnisse
Sensor 1298731: Seite 1, 1000 Ergebnisse
Sensor 1298731: Seite 2, 579 Ergebnisse
Sensor 8004: Seite 1, 1000 Ergebnisse
Sensor 8004: Seite 2, 1000 Ergebnisse
Sensor 8004: Seite 3, 665 Ergebnisse
Sensor 8008: Seite 1, 1000 Ergebnisse
Sensor 8008: Seite 2, 1000 Ergebnisse
Sensor 8008: Seite 3, 424 Ergebnisse
Sensor 8073: Seite 1, 1000 Ergebnisse
Sensor 8073: Seite 2, 1000 Ergebnisse
Sensor 8073: Seite 3, 980 Ergebnisse
Sensor 8254: Seite 1, 1000 Ergebnisse
Sensor 8254: Seite 2, 1000 Ergebnisse
Sensor 8254: Seite 3, 632 Ergebnisse
Sensor 8288: Seite 1, 1000 Ergebnisse
Sensor 8288: Seite 2, 973 Ergebnisse
Sensor 8296: Seite 1, 1000 Ergebnisse
Sensor 8296: Seite 2, 1000 Ergebnisse
Sensor 8296: Seite 3, 13 Ergebnisse
Sensor 8310: Seite 1, 1000 Ergebnisse
Sensor 8310: Seite 2, 1000 Ergebnisse
Sensor 8310: Seite 3, 865 Ergebnisse
Sensor 8320: Seite 1, 1000 Ergebnisse
Sensor 8320: Seite 2, 1000 Ergebnisse
Sensor 8320: Seite 3, 977 Ergebnisse
Sensor 8325: Seite 1, 1000 Ergebnisse
Sensor 8325: Seite 2, 1000 Ergebnisse
Sensor 8325: Seite 3, 1000 Ergebnisse
Sensor 8325: Seite 4, 33 Ergebnisse
Sensor 8357: Seite 1, 1000 Ergebnisse
Sensor 8357: Seite 2, 1000 Ergebnisse
Sensor 8357: Seite 3, 1000 Ergebnisse
Sensor 8357: Seite 4, 39 Ergebnisse
Sensor 8363: Seite 1, 1000 Ergebnisse
Sensor 8363: Seite 2, 1000 Ergebnisse
Sensor 8363: Seite 3, 992 Ergebnisse
Sensor 8367: Seite 1, 1000 Ergebnisse
Sensor 8367: Seite 2, 1000 Ergebnisse
Sensor 8367: Seite 3, 716 Ergebnisse
Sensor 8455: Seite 1, 1000 Ergebnisse
Sensor 8455: Seite 2, 1000 Ergebnisse
Sensor 8455: Seite 3, 941 Ergebnisse
Sensor 8494: Seite 1, 1000 Ergebnisse
Sensor 8494: Seite 2, 1000 Ergebnisse
Sensor 8494: Seite 3, 946 Ergebnisse
Sensor 8582: Seite 1, 1000 Ergebnisse
Sensor 8582: Seite 2, 1000 Ergebnisse
Sensor 8582: Seite 3, 575 Ergebnisse
Sensor 8611: Seite 1, 1000 Ergebnisse
Sensor 8611: Seite 2, 1000 Ergebnisse
Sensor 8611: Seite 3, 555 Ergebnisse
Sensor 9529: Seite 1, 811 Ergebnisse
Sensor 9542: Seite 1, 1000 Ergebnisse
Sensor 9542: Seite 2, 1000 Ergebnisse
Sensor 9542: Seite 3, 978 Ergebnisse
Sensor 9643: Seite 1, 1000 Ergebnisse
Sensor 9643: Seite 2, 1000 Ergebnisse
Sensor 9643: Seite 3, 1000 Ergebnisse
Sensor 9643: Seite 4, 25 Ergebnisse
Sensor 9731: Seite 1, 1000 Ergebnisse
Sensor 9731: Seite 2, 1000 Ergebnisse
Sensor 9731: Seite 3, 1000 Ergebnisse
Sensor 9731: Seite 4, 33 Ergebnisse
Sensor 9716: Seite 1, 1000 Ergebnisse
Sensor 9716: Seite 2, 1000 Ergebnisse
Sensor 9716: Seite 3, 996 Ergebnisse
Sensor 9609: Seite 1, 1000 Ergebnisse
Sensor 9609: Seite 2, 1000 Ergebnisse
Sensor 9609: Seite 3, 990 Ergebnisse
Sensor 9629: Seite 1, 1000 Ergebnisse
Sensor 9629: Seite 2, 1000 Ergebnisse
Sensor 9629: Seite 3, 45 Ergebnisse
Sensor 9680: Seite 1, 1000 Ergebnisse
Sensor 9680: Seite 2, 1000 Ergebnisse
Sensor 9680: Seite 3, 1000 Ergebnisse
Sensor 9680: Seite 4, 29 Ergebnisse
Sensor 9625: Seite 1, 1000 Ergebnisse
Sensor 9625: Seite 2, 1000 Ergebnisse
Sensor 9625: Seite 3, 394 Ergebnisse
Sensor 9616: Seite 1, 1000 Ergebnisse
Sensor 9616: Seite 2, 1000 Ergebnisse
Sensor 9616: Seite 3, 976 Ergebnisse
Sensor 9637: Seite 1, 1000 Ergebnisse
Sensor 9637: Seite 2, 1000 Ergebnisse
Sensor 9637: Seite 3, 1000 Ergebnisse
Sensor 9637: Seite 4, 7 Ergebnisse
Sensor 9863: Seite 1, 1000 Ergebnisse
Sensor 9863: Seite 2, 1000 Ergebnisse
Sensor 9863: Seite 3, 1000 Ergebnisse
Sensor 9863: Seite 4, 29 Ergebnisse
Sensor 9652: Seite 1, 1000 Ergebnisse
Sensor 9652: Seite 2, 1000 Ergebnisse
Sensor 9652: Seite 3, 1000 Ergebnisse
Sensor 9652: Seite 4, 29 Ergebnisse
Sensor 9672: Seite 1, 1000 Ergebnisse
Sensor 9672: Seite 2, 1000 Ergebnisse
Sensor 9672: Seite 3, 1000 Ergebnisse
Sensor 9672: Seite 4, 28 Ergebnisse
Sensor 9693: Seite 1, 1000 Ergebnisse
Sensor 9693: Seite 2, 1000 Ergebnisse
Sensor 9693: Seite 3, 923 Ergebnisse
Sensor 9900: Seite 1, 1000 Ergebnisse
Sensor 9900: Seite 2, 1000 Ergebnisse
Sensor 9900: Seite 3, 1000 Ergebnisse
Sensor 9900: Seite 4, 22 Ergebnisse
Sensor 9747: Seite 1, 1000 Ergebnisse
Sensor 9747: Seite 2, 1000 Ergebnisse
Sensor 9747: Seite 3, 1000 Ergebnisse
Sensor 9747: Seite 4, 19 Ergebnisse
Sensor 9765: Seite 1, 1000 Ergebnisse
Sensor 9765: Seite 2, 1000 Ergebnisse
Sensor 9765: Seite 3, 1000 Ergebnisse
Sensor 9765: Seite 4, 14 Ergebnisse
Sensor 9768: Seite 1, 1000 Ergebnisse
Sensor 9768: Seite 2, 1000 Ergebnisse
Sensor 9768: Seite 3, 1000 Ergebnisse
Sensor 9768: Seite 4, 20 Ergebnisse
Sensor 9778: Seite 1, 1000 Ergebnisse
Sensor 9778: Seite 2, 1000 Ergebnisse
Sensor 9778: Seite 3, 1000 Ergebnisse
Sensor 9778: Seite 4, 19 Ergebnisse
Sensor 9779: Seite 1, 1000 Ergebnisse
Sensor 9779: Seite 2, 1000 Ergebnisse
Sensor 9779: Seite 3, 1000 Ergebnisse
Sensor 9779: Seite 4, 1 Ergebnisse
Sensor 9817: Seite 1, 1000 Ergebnisse
Sensor 9817: Seite 2, 1000 Ergebnisse
Sensor 9817: Seite 3, 1000 Ergebnisse
Sensor 9817: Seite 4, 20 Ergebnisse
Sensor 9827: Seite 1, 1000 Ergebnisse
Sensor 9827: Seite 2, 1000 Ergebnisse
Sensor 9827: Seite 3, 1000 Ergebnisse
Sensor 9827: Seite 4, 29 Ergebnisse
Sensor 9850: Seite 1, 1000 Ergebnisse
Sensor 9850: Seite 2, 1000 Ergebnisse
Sensor 9850: Seite 3, 1000 Ergebnisse
Sensor 9850: Seite 4, 28 Ergebnisse
Sensor 9853: Seite 1, 1000 Ergebnisse
Sensor 9853: Seite 2, 1000 Ergebnisse
Sensor 9853: Seite 3, 1000 Ergebnisse
Sensor 9853: Seite 4, 32 Ergebnisse
Sensor 9860: Seite 1, 1000 Ergebnisse
Sensor 9860: Seite 2, 1000 Ergebnisse
Sensor 9860: Seite 3, 1000 Ergebnisse
Sensor 9860: Seite 4, 27 Ergebnisse
Sensor 9897: Seite 1, 1000 Ergebnisse
Sensor 9897: Seite 2, 1000 Ergebnisse
Sensor 9897: Seite 3, 1000 Ergebnisse
Sensor 9897: Seite 4, 19 Ergebnisse
Sensor 5578: Seite 1, 1000 Ergebnisse
Sensor 5578: Seite 2, 1000 Ergebnisse
Sensor 5578: Seite 3, 579 Ergebnisse
Sensor 8537: Seite 1, 1000 Ergebnisse
Sensor 8537: Seite 2, 1000 Ergebnisse
Sensor 8537: Seite 3, 1000 Ergebnisse
Sensor 8537: Seite 4, 10 Ergebnisse
Sensor 5587: Seite 1, 1000 Ergebnisse
Sensor 5587: Seite 2, 1000 Ergebnisse
Sensor 5587: Seite 3, 741 Ergebnisse
Sensor 5605: Seite 1, 1000 Ergebnisse
Sensor 5605: Seite 2, 1000 Ergebnisse
Sensor 5605: Seite 3, 972 Ergebnisse
Sensor 5611: Seite 1, 9 Ergebnisse
Sensor 8556: Seite 1, 1000 Ergebnisse
Sensor 8556: Seite 2, 1000 Ergebnisse
Sensor 8556: Seite 3, 1000 Ergebnisse
Sensor 8556: Seite 4, 43 Ergebnisse
Sensor 8340: Seite 1, 1000 Ergebnisse
Sensor 8340: Seite 2, 1000 Ergebnisse
Sensor 8340: Seite 3, 716 Ergebnisse
Sensor 7806: Seite 1, 634 Ergebnisse
Sensor 7858: Seite 1, 1000 Ergebnisse
Sensor 7858: Seite 2, 1000 Ergebnisse
Sensor 7858: Seite 3, 703 Ergebnisse
Sensor 7920: Seite 1, 1000 Ergebnisse
Sensor 7920: Seite 2, 1000 Ergebnisse
Sensor 7920: Seite 3, 1000 Ergebnisse
Sensor 7920: Seite 4, 36 Ergebnisse
Sensor 8001: Seite 1, 1000 Ergebnisse
Sensor 8001: Seite 2, 1000 Ergebnisse
Sensor 8001: Seite 3, 1000 Ergebnisse
Sensor 8001: Seite 4, 45 Ergebnisse
Sensor 8012: Seite 1, 1000 Ergebnisse
Sensor 8012: Seite 2, 1000 Ergebnisse
Sensor 8012: Seite 3, 990 Ergebnisse
Sensor 8015: Seite 1, 1000 Ergebnisse
Sensor 8015: Seite 2, 1000 Ergebnisse
Sensor 8015: Seite 3, 936 Ergebnisse
Sensor 8033: Seite 1, 1000 Ergebnisse
Sensor 8033: Seite 2, 453 Ergebnisse
Sensor 8029: Seite 1, 1000 Ergebnisse
Sensor 8029: Seite 2, 1000 Ergebnisse
Sensor 8029: Seite 3, 843 Ergebnisse
Sensor 8041: Seite 1, 1000 Ergebnisse
Sensor 8070: Seite 1, 1000 Ergebnisse
Sensor 8070: Seite 2, 1000 Ergebnisse
Sensor 8070: Seite 3, 278 Ergebnisse
Sensor 8079: Seite 1, 1000 Ergebnisse
Sensor 8079: Seite 2, 1000 Ergebnisse
Sensor 8079: Seite 3, 455 Ergebnisse
Sensor 8129: Seite 1, 1000 Ergebnisse
Sensor 8129: Seite 2, 850 Ergebnisse
Sensor 8132: Seite 1, 1000 Ergebnisse
Sensor 8132: Seite 2, 1000 Ergebnisse
Sensor 8132: Seite 3, 712 Ergebnisse
Sensor 8157: Seite 1, 1000 Ergebnisse
Sensor 8157: Seite 2, 1000 Ergebnisse
Sensor 8157: Seite 3, 694 Ergebnisse
Sensor 8168: Seite 1, 1000 Ergebnisse
Sensor 8168: Seite 2, 1000 Ergebnisse
Sensor 8186: Seite 1, 1000 Ergebnisse
Sensor 8186: Seite 2, 1000 Ergebnisse
Sensor 8186: Seite 3, 674 Ergebnisse
Sensor 8260: Seite 1, 1000 Ergebnisse
Sensor 8260: Seite 2, 1000 Ergebnisse
Sensor 8260: Seite 3, 551 Ergebnisse
Sensor 8259: Seite 1, 1000 Ergebnisse
Sensor 8259: Seite 2, 1000 Ergebnisse
Sensor 8259: Seite 3, 963 Ergebnisse
Sensor 8339: Seite 1, 1000 Ergebnisse

[{'date': '2016-11-21', 'value': 10.75},
 {'date': '2016-11-22', 'value': 55.25},
 {'date': '2016-11-23', 'value': 29.723333333333333},
 {'date': '2016-11-25', 'value': 30.785714285714285},
 {'date': '2016-11-26', 'value': 30.986666666666668},
 {'date': '2016-11-27', 'value': 20.568181818181817},
 {'date': '2016-11-28', 'value': 21.03125},
 {'date': '2016-11-29', 'value': 24.33},
 {'date': '2016-11-30', 'value': 51.333333333333336},
 {'date': '2016-12-01', 'value': 64.625},
 {'date': '2016-12-03', 'value': 41.75},
 {'date': '2016-12-04', 'value': 38.357142857142854},
 {'date': '2016-12-05', 'value': 42.64},
 {'date': '2017-02-18', 'value': 41.0325},
 {'date': '2017-02-19', 'value': 23.49},
 {'date': '2017-02-20', 'value': 12.135},
 {'date': '2017-02-21', 'value': 7.7245833333333325},
 {'date': '2017-02-22', 'value': 4.48},
 {'date': '2017-02-23', 'value': 6.299130434782607},
 {'date': '2017-02-24', 'value': 19.503333333333334},
 {'date': '2017-02-25', 'value': 25.27875},
 {'date': '2017-02-26', 'value': 8.167499999999999},
 {'date': '2017-02-27', 'value': 6.5112499999999995},
 {'date': '2017-02-28', 'value': 8.912916666666666},
 {'date': '2017-03-01', 'value': 11.677916666666668},
 {'date': '2017-03-02', 'value': 11.874166666666666},
 {'date': '2017-03-03', 'value': 21.16},
 {'date': '2017-03-04', 'value': 11.2325},
 {'date': '2017-03-05', 'value': 5.78},
 {'date': '2017-03-06', 'value': 16.022142857142857},
 {'date': '2017-03-07', 'value': 16.81695652173913},
 {'date': '2017-03-08', 'value': 9.799999999999999},
 {'date': '2017-03-09', 'value': 14.12791666666667},
 {'date': '2017-03-10', 'value': 27.913999999999998},
 {'date': '2017-03-12', 'value': 17.02777777777778},
 {'date': '2017-03-13', 'value': 16.45416666666667},
 {'date': '2017-03-14', 'value': 19.17791666666666},
 {'date': '2017-03-15', 'value': 27.22333333333333},
 {'date': '2017-03-16', 'value': 29.402083333333326},
 {'date': '2017-03-17', 'value': 14.092083333333333},
 {'date': '2017-03-18', 'value': 4.611249999999999},
 {'date': '2017-03-19', 'value': 4.84875},
 {'date': '2017-03-20', 'value': 8.64291666625},
 {'date': '2017-03-21', 'value': 18.911666666666665},
 {'date': '2017-03-22', 'value': 18.990416666666665},
 {'date': '2017-03-23', 'value': 30.54875},
 {'date': '2017-03-24', 'value': 19.73},
 {'date': '2017-03-27', 'value': 32.80086956521738},
 {'date': '2017-03-28', 'value': 23.037777777777777},
 {'date': '2017-03-29', 'value': 18.993684210526315},
 {'date': '2017-03-30', 'value': 26.120833333333334},
 {'date': '2017-03-31', 'value': 13.894166666666665},
 {'date': '2017-04-01', 'value': 10.580833333333334},
 {'date': '2017-04-02', 'value': 12.327083333333334},
 {'date': '2017-04-03', 'value': 23.98916666666666},
 {'date': '2017-04-04', 'value': 23.407500000000002},
 {'date': '2017-04-05', 'value': 14.624166666666666},
 {'date': '2017-04-06', 'value': 21.343333333333334},
 {'date': '2017-04-07', 'value': 25.28083333333333},
 {'date': '2017-04-08', 'value': 26.855833333333333},
 {'date': '2017-04-09', 'value': 28.31958333333333},
 {'date': '2017-04-10', 'value': 10.568333333333333},
 {'date': '2017-04-11', 'value': 16.8525},
 {'date': '2017-04-12', 'value': 14.003750000000004},
 {'date': '2017-04-13', 'value': 13.82166666666667},
 {'date': '2017-04-14', 'value': 14.45125},
 {'date': '2017-04-15', 'value': 9.930833333333334},
 {'date': '2017-04-16', 'value': 11.129166666666668},
 {'date': '2017-04-17', 'value': 8.822499999999998},
 {'date': '2017-04-18', 'value': 28.511000000000003},
 {'date': '2017-04-19', 'value': 20.49318181818182},
 {'date': '2017-04-20', 'value': 24.139166666666668},
 {'date': '2017-04-21', 'value': 22.61583333333333},
 {'date': '2017-04-22', 'value': 17.062916666666666},
 {'date': '2017-04-23', 'value': 17.655},
 {'date': '2017-04-24', 'value': 15.510909090909088},
 {'date': '2017-04-25', 'value': 13.15125},
 {'date': '2017-04-26', 'value': 19.45708333333333},
 {'date': '2017-04-27', 'value': 19.335833333333337},
 {'date': '2017-04-28', 'value': 16.020833333333332},
 {'date': '2017-04-29', 'value': 18.297826086956523},
 {'date': '2017-05-02', 'value': 15.693333333333333},
 {'date': '2017-05-03', 'value': 16.451428571428572},
 {'date': '2017-05-04', 'value': 11.94},
 {'date': '2017-05-10', 'value': 40.855000000000004},
 {'date': '2017-05-11', 'value': 20.772380952380953},
 {'date': '2017-05-12', 'value': 8.223636363636363},
 {'date': '2017-05-14', 'value': 5.915},
 {'date': '2017-05-15', 'value': 14.392083333333334},
 {'date': '2017-05-16', 'value': 14.896249999999997},
 {'date': '2017-05-17', 'value': 20.77769230769231},
 {'date': '2017-05-18', 'value': 12.173529411764704},
 {'date': '2017-05-24', 'value': 10.530454545454544},
 {'date': '2017-05-25', 'value': 9.353333333333332},
 {'date': '2017-05-26', 'value': 17.794166666666666},
 {'date': '2017-05-27', 'value': 11.940000000000003},
 {'date': '2017-05-28', 'value': 7.298333333333335},
 {'date': '2017-05-29', 'value': 10.513333333333334},
 {'date': '2017-05-30', 'value': 5.8045833333333325},
 {'date': '2017-05-31', 'value': 10.616250000000003},
 {'date': '2017-06-01', 'value': 15.769999999999996},
 {'date': '2017-06-02', 'value': 18.78875},
 {'date': '2017-06-03', 'value': 10.731249999999998},
 {'date': '2017-06-04', 'value': 7.929583333333333},
 {'date': '2017-06-05', 'value': 6.233750000000001},
 {'date': '2017-06-06', 'value': 4.344166666666667},
 {'date': '2017-06-07', 'value': 4.91125},
 {'date': '2017-06-08', 'value': 7.593333333333333},
 {'date': '2017-06-09', 'value': 5.479166666666667},
 {'date': '2017-06-10', 'value': 8.839166666666667},
 {'date': '2017-06-11', 'value': 8.258750000000001},
 {'date': '2017-06-12', 'value': 4.5995833333333325},
 {'date': '2017-06-13', 'value': 11.326666666666668},
 {'date': '2017-06-14', 'value': 12.73083333333333},
 {'date': '2017-06-15', 'value': 7.835416666666667},
 {'date': '2017-06-16', 'value': 3.7883333333333327},
 {'date': '2017-06-17', 'value': 7.075},
 {'date': '2017-06-18', 'value': 5.843749999999999},
 {'date': '2017-06-19', 'value': 13.410833333333334},
 {'date': '2017-06-20', 'value': 17.04583333333333},
 {'date': '2017-06-21', 'value': 16.338333333333335},
 {'date': '2017-06-22', 'value': 21.915},
 {'date': '2017-06-23', 'value': 4.683181818181819},
 {'date': '2017-06-24', 'value': 8.433333333333332},
 {'date': '2017-06-25', 'value': 2.7363636363636368},
 {'date': '2017-06-26', 'value': 5.394782608695652},
 {'date': '2017-06-27', 'value': 13.993636363636368},
 {'date': '2017-06-28', 'value': 3.3870588235294115},
 {'date': '2017-06-29', 'value': 4.976666666666667},
 {'date': '2017-06-30', 'value': 6.470416666666666},
 {'date': '2017-07-01', 'value': 5.81095238095238},
 {'date': '2017-07-02', 'value': 1.5568181818181814},
 {'date': '2017-07-03', 'value': 5.72},
 {'date': '2017-07-04', 'value': 7.385000000000001},
 {'date': '2017-07-05', 'value': 20.32},
 {'date': '2017-07-06', 'value': 11.757916666666667},
 {'date': '2017-07-07', 'value': 7.240476190476191},
 {'date': '2017-07-08', 'value': 6.074166666666667},
 {'date': '2017-07-09', 'value': 7.068695652173914},
 {'date': '2017-07-10', 'value': 6.5687500000000005},
 {'date': '2017-07-11', 'value': 7.932142857142859},
 {'date': '2017-07-12', 'value': 5.904},
 {'date': '2017-07-13', 'value': 12.602},
 {'date': '2017-07-15', 'value': 2.5146153846153845},
 {'date': '2017-07-16', 'value': 3.8120833333333324},
 {'date': '2017-07-17', 'value': 7.116},
 {'date': '2017-07-18', 'value': 13.89},
 {'date': '2017-09-21', 'value': 12.89},
 {'date': '2017-09-22', 'value': 10.594444444444445},
 {'date': '2017-09-23', 'value': 22.80454545454545},
 {'date': '2017-09-24', 'value': 19.588421052631578},
 {'date': '2017-09-25', 'value': 21.42631578947369},
 {'date': '2017-09-26', 'value': 15.179473684210524},
 {'date': '2017-09-27', 'value': 18.356818181818184},
 {'date': '2017-09-28', 'value': 12.029285714285715},
 {'date': '2017-09-29', 'value': 12.371111111111109},
 {'date': '2017-09-30', 'value': 7.121363636363636},
 {'date': '2017-10-01', 'value': 3.533636363636364},
 {'date': '2017-10-02', 'value': 5.981428571428572},
 {'date': '2017-10-03', 'value': 13.083181818181817},
 {'date': '2017-10-04', 'value': 11.615789473684211},
 {'date': '2017-10-05', 'value': 14.072500000000002},
 {'date': '2017-10-06', 'value': 17.372380952380954},
 {'date': '2017-10-07', 'value': 12.71263157894737},
 {'date': '2017-10-08', 'value': 14.218260869565217},
 {'date': '2017-10-09', 'value': 11.643157894736845},
 {'date': '2017-10-10', 'value': 11.211499999999997},
 {'date': '2017-10-11', 'value': 9.11857142857143},
 {'date': '2017-10-12', 'value': 9.738888888888889},
 {'date': '2017-10-13', 'value': 11.569},
 {'date': '2017-10-14', 'value': 21.858947368421052},
 {'date': '2017-10-15', 'value': 17.641428571428573},
 {'date': '2017-10-16', 'value': 9.760625000000001},
 {'date': '2017-10-17', 'value': 22.6665},
 {'date': '2017-10-18', 'value': 16.481875},
 {'date': '2017-10-19', 'value': 13.773478260869563},
 {'date': '2017-10-20', 'value': 1.855},
 {'date': '2017-10-21', 'value': 4.787619047619048},
 {'date': '2017-10-22', 'value': 4.286818181818182},
 {'date': '2017-10-23', 'value': 9.61},
 {'date': '2017-10-24', 'value': 8.453809523809522},
 {'date': '2017-10-25', 'value': 14.410500000000003},
 {'date': '2017-10-26', 'value': 20.430952380952384},
 {'date': '2017-10-27', 'value': 19.994},
 {'date': '2017-10-28', 'value': 11.979473684210529},
 {'date': '2017-10-29', 'value': 7.788181818181818},
 {'date': '2017-10-30', 'value': 25.92315789473684},
 {'date': '2017-10-31', 'value': 30.279999999999998},
 {'date': '2017-11-01', 'value': 26.32260869565218},
 {'date': '2017-11-02', 'value': 23.882352941176475},
 {'date': '2017-11-03', 'value': 24.46750000000001},
 {'date': '2017-11-04', 'value': 10.609444444444447},
 {'date': '2017-11-05', 'value': 6.456999999999999},
 {'date': '2017-11-06', 'value': 24.148333333333326},
 {'date': '2017-11-07', 'value': 30.961666666666662},
 {'date': '2017-11-08', 'value': 24.714999999999996},
 {'date': '2017-11-09', 'value': 16.015},
 {'date': '2017-11-10', 'value': 12.02526315789474},
 {'date': '2017-11-11', 'value': 5.4025},
 {'date': '2017-11-12', 'value': 4.514736842105263},
 {'date': '2017-11-13', 'value': 15.153888888888888},
 {'date': '2017-11-14', 'value': 20.444},
 {'date': '2017-11-15', 'value': 33.36842105263158},
 {'date': '2017-11-16', 'value': 31.838181818181816},
 {'date': '2017-11-17', 'value': 28.493809523809528},
 {'date': '2017-11-18', 'value': 14.655789473684209},
 {'date': '2017-11-19', 'value': 5.37},
 {'date': '2017-11-20', 'value': 20.266111111111112},
 {'date': '2017-11-21', 'value': 17.05714285714286},
 {'date': '2017-11-22', 'value': 9.231666666666666},
 {'date': '2017-11-23', 'value': 10.786111111111111},
 {'date': '2017-11-24', 'value': 19.52823529411765},
 {'date': '2017-11-25', 'value': 21.641111111111105},
 {'date': '2017-11-26', 'value': 11.792272727272728},
 {'date': '2017-11-27', 'value': 10.405625000000002},
 {'date': '2017-11-28', 'value': 34.584705882352935},
 {'date': '2017-11-29', 'value': 24.26470588235294},
 {'date': '2017-11-30', 'value': 23.41818181818182},
 {'date': '2017-12-01', 'value': 21.970588235294116},
 {'date': '2017-12-02', 'value': 27.20681818181818},
 {'date': '2017-12-03', 'value': 29.63352941176471},
 {'date': '2017-12-04', 'value': 31.25789473684211},
 {'date': '2017-12-05', 'value': 26.851764705882356},
 {'date': '2017-12-06', 'value': 23.343684210526316},
 {'date': '2017-12-07', 'value': 9.554285714285712},
 {'date': '2017-12-08', 'value': 12.090833333333334},
 {'date': '2017-12-11', 'value': 11.473333333333334},
 {'date': '2017-12-12', 'value': 28.507500000000004},
 {'date': '2017-12-13', 'value': 10.027368421052632},
 {'date': '2017-12-14', 'value': 9.677894736842106},
 {'date': '2017-12-15', 'value': 13.188095238095238},
 {'date': '2017-12-16', 'value': 17.616818181818182},
 {'date': '2017-12-17', 'value': 19.74818181818182},
 {'date': '2017-12-18', 'value': 25.16095238095238},
 {'date': '2017-12-20', 'value': 26.06},
 {'date': '2017-12-21', 'value': 15.265789473684208},
 {'date': '2017-12-22', 'value': 17.91095238095238},
 {'date': '2017-12-23', 'value': 11.199411764705882},
 {'date': '2017-12-24', 'value': 9.115294117647059},
 {'date': '2017-12-25', 'value': 4.95578947368421},
 {'date': '2017-12-26', 'value': 7.515555555555555},
 {'date': '2017-12-27', 'value': 6.813478260869566},
 {'date': '2017-12-28', 'value': 23.249565217391304},
 {'date': '2017-12-29', 'value': 11.251666666666667},
 {'date': '2017-12-30', 'value': 4.025294117647058},
 {'date': '2017-12-31', 'value': 2.9633333333333334},
 {'date': '2018-01-05', 'value': 13.793478260869565},
 {'date': '2018-01-06', 'value': 27.240476190476183},
 {'date': '2018-01-07', 'value': 14.019166666666663},
 {'date': '2018-01-08', 'value': 19.342608695652178},
 {'date': '2018-01-09', 'value': 20.288333333333334},
 {'date': '2018-01-10', 'value': 26.519166666666667},
 {'date': '2018-01-11', 'value': 30.12173913043478},
 {'date': '2018-01-12', 'value': 25.00421052631579},
 {'date': '2018-01-13', 'value': 33.518750000000004},
 {'date': '2018-01-14', 'value': 20.291363636363638},
 {'date': '2018-01-15', 'value': 8.930869565217392},
 {'date': '2018-01-16', 'value': 5.755909090909092},
 {'date': '2018-01-17', 'value': 6.9629166666666675},
 {'date': '2018-01-18', 'value': 5.0},
 {'date': '2018-01-19', 'value': 12.207368421052632},
 {'date': '2018-01-20', 'value': 8.383478260869566},
 {'date': '2018-01-21', 'value': 11.534347826086957},
 {'date': '2018-01-22', 'value': 8.82684210526316},
 {'date': '2018-01-23', 'value': 11.138181818181817},
 {'date': '2018-01-24', 'value': 5.457619047619046},
 {'date': '2018-01-25', 'value': 10.628},
 {'date': '2018-01-26', 'value': 22.961249999999996},
 {'date': '2018-01-27', 'value': 17.39470588235294},
 {'date': '2018-01-28', 'value': 7.1034999999999995},
 {'date': '2018-01-29', 'value': 9.304782608695652},
 {'date': '2018-01-30', 'value': 13.515},
 {'date': '2018-01-31', 'value': 8.034285714285714},
 {'date': '2018-02-01', 'value': 19.12},
 {'date': '2018-02-02', 'value': 23.755714285714287},
 {'date': '2018-02-03', 'value': 20.734705882352937},
 {'date': '2018-02-05', 'value': 30.565999999999995},
 {'date': '2018-02-06', 'value': 26.303333333333327},
 {'date': '2018-02-07', 'value': 26.046000000000003},
 {'date': '2018-02-08', 'value': 31.600476190476186},
 {'date': '2018-02-09', 'value': 14.640555555555554},
 {'date': '2018-02-10', 'value': 22.661052631578947},
 {'date': '2018-02-11', 'value': 4.765384615384615},
 {'date': '2018-02-12', 'value': 24.5},
 {'date': '2018-02-13', 'value': 10.874285714285715},
 {'date': '2018-02-25', 'value': 15.115},
 {'date': '2018-02-26', 'value': 15.915833333333333},
 {'date': '2018-02-27', 'value': 29.963},
 {'date': '2018-02-28', 'value': 25.430000000000003},
 {'date': '2018-03-01', 'value': 16.34},
 {'date': '2018-03-02', 'value': 24.176666666666662},
 {'date': '2018-03-03', 'value': 24.658571428571427},
 {'date': '2018-03-04', 'value': 10.91235294117647},
 {'date': '2018-03-05', 'value': 17.692083333333336},
 {'date': '2018-03-06', 'value': 17.7025},
 {'date': '2018-03-07', 'value': 11.207619047619046},
 {'date': '2018-03-08', 'value': 11.367826086956521},
 {'date': '2018-03-09', 'value': 19.8135},
 {'date': '2018-03-10', 'value': 18.252142857142854},
 {'date': '2018-03-11', 'value': 8.175263157894738},
 {'date': '2018-03-12', 'value': 6.309},
 {'date': '2018-03-13', 'value': 13.385625000000001},
 {'date': '2018-03-14', 'value': 20.424999999999997},
 {'date': '2018-03-15', 'value': 10.627777777777778},
 {'date': '2018-03-16', 'value': 22.057391304347824},
 {'date': '2018-03-17', 'value': 27.176499999999997},
 {'date': '2018-03-18', 'value': 13.807500000000001},
 {'date': '2018-03-19', 'value': 11.48},
 {'date': '2018-03-20', 'value': 24.413125},
 {'date': '2018-03-21', 'value': 27.656666666666666},
 {'date': '2018-03-23', 'value': 13.15076923076923},
 {'date': '2018-03-24', 'value': 15.16304347826087},
 {'date': '2018-03-25', 'value': 18.188260869565216},
 {'date': '2018-03-26', 'value': 17.92733333333333},
 {'date': '2018-03-27', 'value': 14.89285714285714},
 {'date': '2018-03-28', 'value': 12.838333333333333},
 {'date': '2018-03-29', 'value': 9.237},
 {'date': '2018-03-30', 'value': 17.05},
 {'date': '2018-03-31', 'value': 8.885333333333335},
 {'date': '2018-04-01', 'value': 6.838333333333334},
 {'date': '2018-04-02', 'value': 7.742608695652173},
 {'date': '2018-04-03', 'value': 7.8877272727272745},
 {'date': '2018-04-04', 'value': 8.42625},
 {'date': '2018-04-05', 'value': 9.916842105263159},
 {'date': '2018-04-06', 'value': 30.126190476190477},
 {'date': '2018-04-07', 'value': 20.052499999999995},
 {'date': '2018-04-08', 'value': 10.973333333333334},
 {'date': '2018-04-09', 'value': 21.301904761904765},
 {'date': '2018-04-10', 'value': 15.733913043478264},
 {'date': '2018-04-11', 'value': 28.9375},
 {'date': '2018-04-12', 'value': 24.307826086956528},
 {'date': '2018-04-13', 'value': 16.633913043478262},
 {'date': '2018-04-14', 'value': 20.96999999999999},
 {'date': '2018-04-15', 'value': 6.098888888888888},
 {'date': '2018-04-16', 'value': 17.847894736842104},
 {'date': '2018-04-17', 'value': 14.853809523809524},
 {'date': '2018-04-18', 'value': 19.705},
 {'date': '2018-04-19', 'value': 21.544545454545453},
 {'date': '2018-04-20', 'value': 17.769999999999996},
 {'date': '2018-04-21', 'value': 18.707391304347826},
 {'date': '2018-04-22', 'value': 10.18909090909091},
 {'date': '2018-04-23', 'value': 6.9788235294117635},
 {'date': '2018-04-24', 'value': 10.46608695652174},
 {'date': '2018-04-25', 'value': 6.051666666666667},
 {'date': '2018-04-26', 'value': 8.543809523809525},
 {'date': '2018-04-27', 'value': 16.44833333333333},
 {'date': '2018-04-28', 'value': 4.774545454545455},
 {'date': '2018-04-29', 'value': 9.717058823529412},
 {'date': '2018-04-30', 'value': 7.2455},
 {'date': '2018-05-02', 'value': 3.9104761904761913},
 {'date': '2018-05-03', 'value': 14.619545454545452},
 {'date': '2018-05-04', 'value': 14.301250000000001},
 {'date': '2018-05-05', 'value': 16.47681818181818},
 {'date': '2018-05-06', 'value': 13.369565217391301},
 {'date': '2018-05-07', 'value': 15.078260869565218},
 {'date': '2018-05-08', 'value': 8.375238095238094},
 {'date': '2018-05-09', 'value': 6.60235294117647},
 {'date': '2018-05-10', 'value': 5.890666666666666},
 {'date': '2018-05-11', 'value': 11.0915},
 {'date': '2018-05-12', 'value': 7.783999999999999},
 {'date': '2018-05-13', 'value': 3.985833333333334},
 {'date': '2018-05-14', 'value': 9.540000000000001},
 {'date': '2018-05-15', 'value': 10.276842105263157},
 {'date': '2018-05-16', 'value': 11.052},
 {'date': '2018-05-17', 'value': 9.068095238095237},
 {'date': '2018-05-18', 'value': 5.890000000000001},
 {'date': '2018-05-19', 'value': 10.077333333333334},
 {'date': '2018-05-20', 'value': 8.899333333333335},
 {'date': '2018-05-21', 'value': 7.80764705882353},
 {'date': '2018-05-22', 'value': 11.208947368421052},
 {'date': '2018-05-23', 'value': 11.2},
 {'date': '2018-05-24', 'value': 9.919230769230769},
 {'date': '2018-05-25', 'value': 15.186666666666667},
 {'date': '2018-05-26', 'value': 9.64},
 {'date': '2018-05-27', 'value': 6.977619047619048},
 {'date': '2018-05-28', 'value': 12.587999999999997},
 {'date': '2018-05-29', 'value': 15.97},
 {'date': '2018-05-30', 'value': 6.943181818181819},
 {'date': '2018-05-31', 'value': 6.3031578947368425},
 {'date': '2018-06-01', 'value': 8.279523809523809},
 {'date': '2018-06-02', 'value': 7.260952380952382},
 {'date': '2018-06-03', 'value': 6.2445},
 {'date': '2018-06-04', 'value': 14.344117647058823},
 {'date': '2018-06-05', 'value': 13.597083333333332},
 {'date': '2018-06-06', 'value': 14.103636363636362},
 {'date': '2018-06-07', 'value': 9.142272727272728},
 {'date': '2018-06-08', 'value': 10.192083333333334},
 {'date': '2018-06-09', 'value': 9.83090909090909},
 {'date': '2018-06-10', 'value': 6.036666666666667},

In [22]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_no2_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_no2_mean
0    2016-11-21        27.590070
1    2016-11-22        47.886450
2    2016-11-23        31.895527
3    2016-11-25        34.386618
4    2016-11-26        31.450254
...         ...              ...
3096 2026-02-24        15.381488
3097 2026-02-25        20.623755
3098 2026-02-26        21.391887
3099 2026-02-27        17.012252
3100 2026-02-28        12.999873

[3101 rows x 2 columns]

In [23]:
france_daily[["date", "france_no2_mean"]].to_csv(
    "daily_avg_france_NO2.csv",
    index=False
)