# Get daily average values for air pollution in Spain from 2016-2026 using openAQ API

In [1]:
import requests
import pandas as pd 
import time

### List possible parameters (e.g. PM10, PM2.5, NO2)

In [ ]:
api_url = "https://api.openaq.org/v3/parameters"

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, headers=headers)
response = response.json()

response

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 46},
 'results': [{'id': 1,
   'name': 'pm10',
   'units': 'µg/m³',
   'displayName': 'PM10',
   'description': 'Particulate matter less than 10 micrometers in diameter mass concentration'},
  {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': 'PM2.5',
   'description': 'Particulate matter less than 2.5 micrometers in diameter mass concentration'},
  {'id': 3,
   'name': 'o3',
   'units': 'µg/m³',
   'displayName': 'O₃ mass',
   'description': 'Ozone mass concentration'},
  {'id': 4,
   'name': 'co',
   'units': 'µg/m³',
   'displayName': 'CO mass',
   'description': 'Carbon Monoxide mass concentration'},
  {'id': 5,
   'name': 'no2',
   'units': 'µg/m³',
   'displayName': 'NO₂ mass',
   'description': 'Nitrogen Dioxide mass concentration'},
  {'id': 6,
   'name': 'so2',
   'units': 'µg/m³',
   'displayName': 'SO₂ mass',
   'description': 'Sulfur Dioxide mass concentration'},
  {'id': 7,
   'name': 'no2',
   'units': 'ppm',
   'displayName': 'NO₂',
   'description': 'Nitrogen Dioxide concentration'},
  {'id': 8,
   'name': 'co',
   'units': 'ppm',
   'displayName': 'CO',
   'description': 'Carbon Monoxide concentration'},
  {'id': 9,
   'name': 'so2',
   'units': 'ppm',
   'displayName': 'SO₂',
   'description': 'Sulfur Dioxide concentration'},
  {'id': 10,
   'name': 'o3',
   'units': 'ppm',
   'displayName': 'O₃',
   'description': 'Ozone concentration'},
  {'id': 11,
   'name': 'bc',
   'units': 'µg/m³',
   'displayName': 'BC',
   'description': 'Black Carbon mass concentration'},
  {'id': 15,
   'name': 'no2',
   'units': 'ppb',
   'displayName': 'NO₂',
   'description': None},
  {'id': 19,
   'name': 'pm1',
   'units': 'µg/m³',
   'displayName': 'PM1',
   'description': 'Particulate matter less than 1 micrometer in diameter mass concentration'},
  {'id': 21,
   'name': 'co2',
   'units': 'ppm',
   'displayName': 'CO₂',
   'description': 'Carbon Dioxide concentration'},
  {'id': 22,
   'name': 'wind_direction',
   'units': 'deg',
   'displayName': 'Wind direction',
   'description': 'Direction that the wind originates from'},
  {'id': 23,
   'name': 'nox',
   'units': 'ppb',
   'displayName': 'NOX',
   'description': None},
  {'id': 24,
   'name': 'no',
   'units': 'ppb',
   'displayName': 'NO',
   'description': None},
  {'id': 27,
   'name': 'nox',
   'units': 'µg/m³',
   'displayName': 'NOx mass',
   'description': 'Nitrogen Oxides mass concentration'},
  {'id': 28,
   'name': 'ch4',
   'units': 'ppm',
   'displayName': 'CH₄',
   'description': 'Methane concentration'},
  {'id': 32,
   'name': 'o3',
   'units': 'ppb',
   'displayName': 'O₃',
   'description': None},
  {'id': 33,
   'name': 'ufp',
   'units': 'particles/cm³',
   'displayName': 'UFP count',
   'description': 'Ultrafine Particles count concentration'},
  {'id': 34,
   'name': 'wind_speed',
   'units': 'm/s',
   'displayName': 'Wind speed',
   'description': 'Average wind speed in meters per second'},
  {'id': 35,
   'name': 'no',
   'units': 'ppm',
   'displayName': 'NO',
   'description': 'Nitrogen Monoxide concentration'},
  {'id': 95,
   'name': 'pressure',
   'units': 'hpa',
   'displayName': 'Atmospheric pressure',
   'description': 'Atmospheric or barometric pressure'},
  {'id': 97,
   'name': 'pm25-old',
   'units': 'ugm3',
   'displayName': None,
   'description': None},
  {'id': 98,
   'name': 'relativehumidity',
   'units': '%',
   'displayName': 'RH',
   'description': None},
  {'id': 100,
   'name': 'temperature',
   'units': 'c',
   'displayName': 'Temperature (C)',
   'description': None},
  {'id': 101,
   'name': 'so2',
   'units': 'ppb',
   'displayName': 'SO₂',
   'description': None},
  {'id': 102,
   'name': 'co',
   'units': 'ppb',
   'displayName': 'CO',
   'description': None},
  {'id': 125,
   'name': 'um003',
   'units': 'particles/cm³',
   'displayName': 'PM0.3 count',
   'description': None},
  {'id': 126,
   'name': 'um010',
   'units': 'particles/cm³',
   'displayName': 'PM1 count',
   'description': 'PM1 count'},
  {'id': 128,
   'name': 'temperature',
   'units': 'f',
   'displayName': 'Temperature (F)',
   'description': None},
  {'id': 130,
   'name': 'um025',
   'units': 'particles/cm³',
   'displayName': 'PM2.5 count',
   'description': 'PM2.5 count'},
  {'id': 132,
   'name': 'pressure',
   'units': 'mb',
   'displayName': 'Pressure',
   'description': None},
  {'id': 134,
   'name': 'humidity',
   'units': '%',
   'displayName': 'H',
   'description': None},
  {'id': 135,
   'name': 'um100',
   'units': 'particles/cm³',
   'displayName': 'PM10 count',
   'description': 'PM10 count'},
  {'id': 19840,
   'name': 'nox',
   'units': 'ppm',
   'displayName': 'NOx',
   'description': 'Nitrogen Oxides concentration'},
  {'id': 19843,
   'name': 'no',
   'units': 'µg/m³',
   'displayName': 'NO mass',
   'description': 'Nitrogen Monoxide mass concentration'},
  {'id': 19844,
   'name': 'pm4',
   'units': 'µg/m³',
   'displayName': 'PM4.0',
   'description': 'Particulate matter less than 4 micrometers in diameter mass concentration'},
  {'id': 19860,
   'name': 'pm25',
   'units': 'ppm',
   'displayName': None,
   'description': None},
  {'id': 19861,
   'name': 'bc_375',
   'units': 'ng/m³',
   'displayName': 'BC 375nm',
   'description': 'Black Carbon mass concentration 375nm '},
  {'id': 19862,
   'name': 'bc_470',
   'units': 'ng/m³',
   'displayName': 'BC 470nm',
   'description': 'Black Carbon mass concentration 470nm '},
  {'id': 19863,
   'name': 'bc_528',
   'units': 'ng/m³',
   'displayName': 'BC 528nm',
   'description': 'Black Carbon mass concentration 528nm '},
  {'id': 19864,
   'name': 'bc_625',
   'units': 'ng/m³',
   'displayName': 'BC 625nm',
   'description': 'Black Carbon mass concentration 625nm '},
  {'id': 19865,
   'name': 'bc_880',
   'units': 'ng/m³',
   'displayName': 'BC 880nm',
   'description': 'Black Carbon mass concentration 880nm '},
  {'id': 19866,
   'name': 'bc_370',
   'units': 'ng/m³',
   'displayName': 'BC 370nm',
   'description': 'Black Carbon mass concentration 375nm '}]}

# PM10

### Get all stations located in Poland that measure PM10
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "ES",   # only consider stations located in spain
    "parameters_id": 1,   # PM10 
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm10 = df_sorted

df_top_pm10

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
30,3226,Santa Perpètua de Mogoda,Santa Perpètua de Mogoda,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272698, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.526722, 'longitude': 2.1838}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.1838, 41.526722, 2.1838, 41.526722]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
31,3229,Sant Adrià de Besòs,Sant Adrià de Besòs,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272900, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.425594, 'longitude': 2.2221997...","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.2221997000000004, 41.425594, 2.222199700000...",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
33,3231,Sant Andreu de la Barca,Sant Andreu de la Barca,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272723, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.4508, 'longitude': 1.9748996}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.9748996, 41.4508, 1.9748996, 41.4508]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
35,3233,Vilanova i la Geltrú,Vilanova i la Geltrú,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 7571, 'name': 'co µg/m³', 'parameter':...","{'latitude': 41.218987, 'longitude': 1.7211995...","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.7211995000000004, 41.218987, 1.721199500000...",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
36,3235,Sant Celoni,Sant Celoni,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272718, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.6891, 'longitude': 2.495701}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.495701, 41.6891, 2.495701, 41.6891]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,5509326,MONFRAGÜE,TORIL,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13918283, 'name': 'co µg/m³', 'paramet...","{'latitude': 39.84374700007474, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-5.943007999637519, 39.84374700007474, -5.943...",None,2025-08-18 21:00:00+00:00,2025-12-18 02:00:00+00:00
638,5509325,MERIDA,MÉRIDA,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13918285, 'name': 'co µg/m³', 'paramet...","{'latitude': 38.906222999823484, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-6.339232000355508, 38.906222999823484, -6.33...",None,2025-08-18 21:00:00+00:00,2025-08-25 05:00:00+00:00
641,6162079,SANT CELONI (CARLES DAMM),SANT CELONI,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14870118, 'name': 'no2 µg/m³', 'parame...","{'latitude': 41.68900000005529, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[2.495700000244586, 41.68900000005529, 2.49570...",None,2025-12-09 12:00:00+00:00,2026-02-09 15:00:00+00:00
642,6162118,Ponts,Ponts,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14870404, 'name': 'o3 µg/m³', 'paramet...","{'latitude': 41.906708, 'longitude': 1.1930013}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.1930013, 41.906708, 1.1930013, 41.906708]",None,2025-12-12 03:00:00+00:00,2026-03-05 03:00:00+00:00
643,6187808,Barcelona,Barcelona,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 15062013, 'name': 'co µg/m³', 'paramet...","{'latitude': 41.41591, 'longitude': 2.1870944}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.1870944, 41.41591, 2.1870944, 41.41591]",None,2026-01-03 03:00:00+00:00,2026-03-05 03:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [7]:
rows = []

for _, station in df_top_pm10.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM10 behalten
        if sensor["parameter"]["id"] == 1:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm10_sensors = pd.DataFrame(rows)

df_pm10_sensors

     station_id               station_name  sensor_id sensor_name
0          3226   Santa Perpètua de Mogoda      25071  pm10 µg/m³
1          3229        Sant Adrià de Besòs      25184  pm10 µg/m³
2          3231    Sant Andreu de la Barca    4272875  pm10 µg/m³
3          3233       Vilanova i la Geltrú    4272857  pm10 µg/m³
4          3235                Sant Celoni      25172  pm10 µg/m³
..          ...                        ...        ...         ...
639     5509326                  MONFRAGÜE   13918284  pm10 µg/m³
640     5509325                     MERIDA   13918281  pm10 µg/m³
641     6162079  SANT CELONI (CARLES DAMM)   14870120  pm10 µg/m³
642     6162118                      Ponts   15147154  pm10 µg/m³
643     6187808                  Barcelona   15061783  pm10 µg/m³

[644 rows x 4 columns]

In [8]:
sensor_ids = df_pm10_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

644

[25071,
 25184,
 4272875,
 4272857,
 25172,
 25203,
 4272666,
 4272694,
 25178,
 4276068,
 4277250,
 2683695,
 4272824,
 25204,
 2683697,
 2683689,
 4272880,
 25117,
 25048,
 4273065,
 2683692,
 4272761,
 4272977,
 4272773,
 4273031,
 5722,
 7773641,
 6206,
 7343,
 6212,
 7120204,
 8667,
 6987,
 2683696,
 7036,
 7044,
 7075,
 7085,
 24767,
 7104,
 4285579,
 7123,
 7155,
 7156,
 7161,
 7184,
 25118,
 11973974,
 7287,
 7291,
 7295,
 7329,
 7299,
 7320,
 7360,
 7339,
 7364,
 30293,
 2683694,
 8651,
 9143,
 9545,
 9553,
 9557,
 9563,
 25200,
 9570,
 9581,
 9586,
 9587,
 9612,
 9667,
 10235,
 10308,
 10373,
 10385,
 10398,
 30134,
 10443,
 10489,
 10498,
 10513,
 10537,
 10542,
 10579,
 29333,
 9552,
 7173,
 9571,
 2683691,
 2011617,
 2011614,
 2011615,
 2011618,
 2011613,
 9569,
 8668,
 2011616,
 9406,
 10627,
 10240,
 10359,
 10605,
 10642,
 4272917,
 7049,
 8674,
 9114,
 9751,
 9952,
 10419,
 10494,
 10630,
 6983,
 7095,
 25177,
 25101,
 25167,
 7254,
 7281,
 7283,
 2683693,
 7059,
 29282,
 30135,
 9623,
 10553,
 7169,
 6995,
 4273263,
 10377,
 10381,
 10422,
 10428,
 10468,
 12144657,
 10546,
 10558,
 10570,
 25034,
 10601,
 9580,
 10364,
 6199,
 7056,
 10667,
 10665,
 10666,
 10693,
 10689,
 10711,
 7242,
 9575,
 9591,
 9907,
 9911,
 9561,
 21672,
 10260,
 10288,
 10318,
 10330,
 24612,
 10252,
 7107,
 7165,
 7327,
 7378,
 10244,
 10272,
 10275,
 10350,
 10409,
 10415,
 10433,
 30079,
 30078,
 10612,
 10640,
 10651,
 7066,
 4273208,
 24423,
 10516,
 10345,
 9935,
 10028,
 10100,
 7080,
 23695,
 10066,
 9988,
 10036,
 23690,
 23702,
 23675,
 5712,
 5696,
 5701,
 23685,
 5705,
 29386,
 5723,
 23700,
 9922,
 23701,
 10678,
 238926,
 9558,
 10281,
 7347,
 9990,
 10203,
 10172,
 10014,
 10128,
 10199,
 9959,
 10044,
 10114,
 10084,
 10103,
 10085,
 9989,
 10158,
 23816,
 10191,
 9524,
 10127,
 10136,
 10155,
 9944,
 10107,
 10075,
 10190,
 10295,
 10304,
 10565,
 10624,
 7690,
 11055,
 9934,
 12186430,
 7622778,
 9979,
 10000,
 10049,
 7622776,
 10069,
 10090,
 10079,
 10124,
 11053,
 10146,
 10137,
 12216857,
 10184,
 10194,
 10108,
 9100,
 2011805,
 23804,
 12186133,
 9949,
 9957,
 10031,
 23765,
 9938,
 10087,
 10041,
 10221,
 9556,
 23802,
 21749,
 21616,
 23867,
 22628,
 22624,
 22621,
 23798,
 23824,
 23829,
 23858,
 23862,
 23881,
 23864,
 20701,
 22913,
 22943,
 23346,
 23349,
 23354,
 29227,
 20448,
 20454,
 20459,
 19777,
 19780,
 23894,
 23149,
 22839,
 23135,
 23155,
 23136,
 23130,
 23200,
 23166,
 23158,
 23162,
 23169,
 23179,
 23178,
 23187,
 23196,
 23391,
 23408,
 23402,
 23813,
 19778,
 19779,
 19776,
 23846,
 23890,
 23872,
 23877,
 23851,
 13115250,
 22417,
 20444,
 22444,
 22447,
 1289687,
 1289658,
 1289673,
 1289621,
 1289680,
 1289609,
 1289670,
 1289681,
 1289611,
 1289606,
 1289675,
 1289607,
 1289623,
 1289661,
 1289679,
 1289602,
 1289648,
 1289628,
 1289652,
 4273052,
 4272789,
 4272822,
 4475451,
 4273135,
 4287830,
 4927037,
 5078366,
 5078351,
 8613042,
 5079065,
 5078327,
 5078956,
 5078797,
 5078765,
 5079056,
 5078805,
 5078570,
 5078825,
 5078955,
 5078772,
 5078305,
 5078643,
 5078438,
 5078565,
 5079321,
 5079323,
 5079790,
 5079331,
 5079054,
 5078485,
 5078313,
 5079000,
 5078420,
 5078618,
 5078766,
 5078688,
 5078322,
 5078606,
 7264925,
 7775958,
 7775450,
 7774884,
 7773392,
 7773180,
 7774555,
 7774106,
 7774454,
 7775293,
 7773717,
 7773000,
 7773186,
 14029664,
 7772943,
 7774132,
 7772706,
 7774178,
 7775818,
 7775541,
 7774814,
 7775597,
 7775224,
 7774688,
 7775593,
 7773199,
 7775542,
 7775893,
 7773746,
 7775406,
 7774551,
 7774310,
 7775637,
 7773227,
 10793552,
 7773053,
 7775063,
 7775865,
 7773631,
 7775021,
 7773958,
 7775722,
 7774915,
 7775668,
 7775401,
 7775915,
 7774684,
 7773973,
 7774848,
 7775993,
 7773888,
 7773802,
 7773171,
 7774741,
 7775576,
 7774977,
 7774947,
 7775592,
 7774712,
 7773301,
 7772933,
 7774631,
 7774832,
 7774860,
 7774325,
 7774933,
 7774255,
 7775370,
 7774662,
 7773283,
 7774618,
 7774843,
 7773861,
 7773777,
 7774367,
 7774014,
 7773175,
 7773309,
 7776008,
 7773982,
 7775699,
 7773543,
 7774710,
 7773816,
 7774229,
 7906926,
 7773585,
 7774561,
 7773414,
 7780772,
 7775015,
 7773484,
 7773838,
 7773195,
 7775421,
 7773125,
 7774465,
 7774995,
 7774241,
 7773740,
 7774541,
 7773914,
 7775607,
 7773258,
 7773833,
 7775452,
 7772893,
 7773780,
 7774488,
 7774786,
 7774835,
 7894750,
 7774433,
 7775766,
 7773099,
 7774634,
 7773573,
 11857177,
 7774005,
 7772962,
 7773353,
 7773101,
 7772713,
 7775167,
 7773665,
 7775326,
 7773997,
 7774881,
 7774242,
 7773574,
 7773386,
 7773987,
 7773506,
 7774973,
 7774493,
 7773857,
 7776535,
 7776515,
 7776477,
 7776585,
 7776985,
 7776999,
 7776573,
 7776957,
 7776630,
 7777036,
 7777021,
 7777033,
 7776595,
 7776505,
 7776972,
 7776564,
 7776955,
 7776576,
 7776572,
 7776479,
 7776540,
 7777001,
 7776491,
 7776590,
 7776521,
 7776950,
 7777004,
 7777040,
 7776468,
 7777030,
 7773817,
 7776539,
 7776949,
 7773032,
 8613538,
 7787507,
 7798109,
 7794936,
 8613061,
 7799526,
 7870008,
 7948336,
 7981802,
 8622256,
 8622679,
 8613473,
 8622639,
 8613520,
 8613690,
 8622632,
 8622265,
 8613643,
 8613611,
 8622318,
 8622245,
 8622624,
 8613592,
 7795390,
 8622235,
 8622633,
 8622615,
 8622284,
 11857180,
 8622652,
 8613530,
 8613438,
 10793871,
 8613575,
 8622272,
 8622314,
 8613465,
 8622673,
 8613633,
 8613667,
 8613688,
 14030925,
 8623577,
 8613501,
 8613652,
 8622231,
 7795386,
 7795385,
 8613357,
 8623616,
 7795399,
 8624473,
 8613463,
 8625970,
 8624812,
 8613569,
 8622266,
 8613419,
 10455751,
 10455768,
 10455780,
 10455779,
 10455739,
 10455782,
 10455735,
 10456087,
 10455727,
 10455777,
 10455763,
 10455730,
 10455757,
 11038885,
 11633767,
 11857175,
 11857477,
 11884533,
 12131203,
 12514741,
 13100347,
 13921564,
 13918284,
 13918281,
 14870120,
 15147154,
 15061783]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 25071: Seite 1, 1000 Ergebnisse
Sensor 25071: Seite 2, 1000 Ergebnisse
Sensor 25071: Seite 3, 87 Ergebnisse
Sensor 25184: Seite 1, 1000 Ergebnisse
Sensor 25184: Seite 2, 1000 Ergebnisse
Sensor 25184: Seite 3, 75 Ergebnisse
Sensor 4272875: Seite 1, 772 Ergebnisse
Sensor 4272857: Seite 1, 978 Ergebnisse
Sensor 25172: Seite 1, 1000 Ergebnisse
Sensor 25172: Seite 2, 1000 Ergebnisse
Sensor 25172: Seite 3, 80 Ergebnisse
Sensor 25203: Seite 1, 1000 Ergebnisse
Sensor 25203: Seite 2, 1000 Ergebnisse
Sensor 25203: Seite 3, 91 Ergebnisse
Sensor 4272666: Seite 1, 1000 Ergebnisse
Sensor 4272666: Seite 2, 50 Ergebnisse
Sensor 4272694: Seite 1, 1000 Ergebnisse
Sensor 4272694: Seite 2, 54 Ergebnisse
Sensor 25178: Seite 1, 1000 Ergebnisse
Sensor 25178: Seite 2, 1000 Ergebnisse
Sensor 25178: Seite 3, 57 Ergebnisse
Sensor 4276068: Seite 1, 300 Ergebnisse
Sensor 4277250: Seite 1, 871 Ergebnisse
Sensor 2683695: Seite 1, 1000 Ergebnisse
Sensor 2683695: Seite 2, 51 Ergebnisse
Sensor 4272824: Seite 1, 995 Ergebnisse
Sensor 25204: Seite 1, 1000 Ergebnisse
Sensor 25204: Seite 2, 1000 Ergebnisse
Sensor 25204: Seite 3, 33 Ergebnisse
Sensor 2683697: Seite 1, 1000 Ergebnisse
Sensor 2683697: Seite 2, 51 Ergebnisse
Sensor 2683689: Seite 1, 1000 Ergebnisse
Sensor 2683689: Seite 2, 43 Ergebnisse
Sensor 4272880: Seite 1, 1000 Ergebnisse
Sensor 4272880: Seite 2, 44 Ergebnisse
Sensor 25117: Seite 1, 1000 Ergebnisse
Sensor 25117: Seite 2, 1000 Ergebnisse
Sensor 25117: Seite 3, 86 Ergebnisse
Sensor 25048: Seite 1, 1000 Ergebnisse
Sensor 25048: Seite 2, 1000 Ergebnisse
Sensor 25048: Seite 3, 91 Ergebnisse
Sensor 4273065: Seite 1, 1000 Ergebnisse
Sensor 4273065: Seite 2, 54 Ergebnisse
Sensor 2683692: Seite 1, 1000 Ergebnisse
Sensor 2683692: Seite 2, 38 Ergebnisse
Sensor 4272761: Seite 1, 942 Ergebnisse
Sensor 4272977: Seite 1, 1000 Ergebnisse
Sensor 4272977: Seite 2, 5 Ergebnisse
Sensor 4272773: Seite 1, 926 Ergebnisse
Sensor 4273031: Seite 1, 1000 Ergebnisse
Sensor 4273031: Seite 2, 18 Ergebnisse
Sensor 5722: Seite 1, 1000 Ergebnisse
Sensor 5722: Seite 2, 1000 Ergebnisse
Sensor 5722: Seite 3, 55 Ergebnisse
Sensor 7773641: Seite 1, 628 Ergebnisse
Sensor 6206: Seite 1, 878 Ergebnisse
Sensor 7343: Seite 1, 1000 Ergebnisse
Sensor 7343: Seite 2, 1000 Ergebnisse
Sensor 7343: Seite 3, 288 Ergebnisse
Sensor 6212: Seite 1, 937 Ergebnisse
Sensor 7120204: Seite 1, 787 Ergebnisse
Sensor 8667: Seite 1, 1000 Ergebnisse
Sensor 8667: Seite 2, 94 Ergebnisse
Sensor 6987: Seite 1, 1000 Ergebnisse
Sensor 6987: Seite 2, 1000 Ergebnisse
Sensor 6987: Seite 3, 912 Ergebnisse
Sensor 2683696: Seite 1, 971 Ergebnisse
Sensor 7036: Seite 1, 1000 Ergebnisse
Sensor 7036: Seite 2, 867 Ergebnisse
Sensor 7044: Seite 1, 1000 Ergebnisse
Sensor 7044: Seite 2, 1000 Ergebnisse
Sensor 7044: Seite 3, 370 Ergebnisse
Sensor 7075: Seite 1, 1000 Ergebnisse
Sensor 7075: Seite 2, 1000 Ergebnisse
Sensor 7075: Seite 3, 585 Ergebnisse
Sensor 7085: Seite 1, 867 Ergebnisse
Sensor 24767: Seite 1, 1000 Ergebnisse
Sensor 24767: Seite 2, 1000 Ergebnisse
Sensor 24767: Seite 3, 329 Ergebnisse
Sensor 7104: Seite 1, 1000 Ergebnisse
Sensor 7104: Seite 2, 1000 Ergebnisse
Sensor 7104: Seite 3, 374 Ergebnisse
Sensor 4285579: Seite 1, 1 Ergebnisse
Sensor 7123: Seite 1, 1000 Ergebnisse
Sensor 7123: Seite 2, 1000 Ergebnisse
Sensor 7123: Seite 3, 452 Ergebnisse
Sensor 7155: Seite 1, 1000 Ergebnisse
Sensor 7155: Seite 2, 1000 Ergebnisse
Sensor 7155: Seite 3, 152 Ergebnisse
Sensor 7156: Seite 1, 1000 Ergebnisse
Sensor 7156: Seite 2, 1000 Ergebnisse
Sensor 7156: Seite 3, 261 Ergebnisse
Sensor 7161: Seite 1, 1000 Ergebnisse
Sensor 7161: Seite 2, 1000 Ergebnisse
Sensor 7161: Seite 3, 499 Ergebnisse
Sensor 7184: Seite 1, 1000 Ergebnisse
Sensor 7184: Seite 2, 1000 Ergebnisse
Sensor 7184: Seite 3, 381 Ergebnisse
Sensor 25118: Seite 1, 1000 Ergebnisse
Sensor 25118: Seite 2, 1000 Ergebnisse
Sensor 25118: Seite 3, 334 Ergebnisse
Sensor 11973974: Seite 1, 399 Ergebnisse
Sensor 7287: Seite 1, 1000 Ergebnisse
Sensor 7287: Seite 2, 1000 Ergebnisse
Sensor 7287: Seite 3, 269 Ergebnisse
Sensor 7291: Seite 1, 1000 Ergebnisse
Sensor 7291: Seite 2, 1000 Ergebnisse
Sensor 7291: Seite 3, 282 Ergebnisse
Sensor 7295: Seite 1, 1000 Ergebnisse
Sensor 7295: Seite 2, 1000 Ergebnisse
Sensor 7295: Seite 3, 257 Ergebnisse
Sensor 7329: Seite 1, 1000 Ergebnisse
Sensor 7329: Seite 2, 1000 Ergebnisse
Sensor 7329: Seite 3, 884 Ergebnisse
Sensor 7299: Seite 1, 1000 Ergebnisse
Sensor 7299: Seite 2, 1000 Ergebnisse
Sensor 7299: Seite 3, 319 Ergebnisse
Sensor 7320: Seite 1, 1000 Ergebnisse
Sensor 7320: Seite 2, 1000 Ergebnisse
Sensor 7320: Seite 3, 353 Ergebnisse
Sensor 7360: Seite 1, 1000 Ergebnisse
Sensor 7360: Seite 2, 1000 Ergebnisse
Sensor 7360: Seite 3, 270 Ergebnisse
Sensor 7339: Seite 1, 1000 Ergebnisse
Sensor 7339: Seite 2, 1000 Ergebnisse
Sensor 7339: Seite 3, 292 Ergebnisse
Sensor 7364: Seite 1, 1000 Ergebnisse
Sensor 7364: Seite 2, 1000 Ergebnisse
Sensor 7364: Seite 3, 388 Ergebnisse
Sensor 30293: Seite 1, 1000 Ergebnisse
Sensor 30293: Seite 2, 1000 Ergebnisse
Sensor 30293: Seite 3, 212 Ergebnisse
Sensor 2683694: Seite 1, 977 Ergebnisse
Sensor 8651: Seite 1, 868 Ergebnisse
Sensor 9143: Seite 1, 919 Ergebnisse
Sensor 9545: Seite 1, 1000 Ergebnisse
Sensor 9545: Seite 2, 1000 Ergebnisse
Sensor 9545: Seite 3, 58 Ergebnisse
Sensor 9553: Seite 1, 1000 Ergebnisse
Sensor 9553: Seite 2, 1000 Ergebnisse
Sensor 9553: Seite 3, 436 Ergebnisse
Sensor 9557: Seite 1, 1000 Ergebnisse
Sensor 9557: Seite 2, 1000 Ergebnisse
Sensor 9557: Seite 3, 89 Ergebnisse
Sensor 9563: Seite 1, 1000 Ergebnisse
Sensor 9563: Seite 2, 1000 Ergebnisse
Sensor 9563: Seite 3, 570 Ergebnisse
Sensor 25200: Seite 1, 1000 Ergebnisse
Sensor 25200: Seite 2, 1000 Ergebnisse
Sensor 25200: Seite 3, 500 Ergebnisse
Sensor 9570: Seite 1, 1000 Ergebnisse
Sensor 9570: Seite 2, 1000 Ergebnisse
Sensor 9570: Seite 3, 49 Ergebnisse
Sensor 9581: Seite 1, 1000 Ergebnisse
Sensor 9581: Seite 2, 1000 Ergebnisse
Sensor 9581: Seite 3, 159 Ergebnisse
Sensor 9586: Seite 1, 1000 Ergebnisse
Sensor 9586: Seite 2, 1000 Ergebnisse
Sensor 9586: Seite 3, 256 Ergebnisse
Sensor 9587: Seite 1, 1000 Ergebnisse
Sensor 9587: Seite 2, 1000 Ergebnisse
Sensor 9587: Seite 3, 60 Ergebnisse
Sensor 9612: Seite 1, 1000 Ergebnisse
Sensor 9612: Seite 2, 1000 Ergebnisse
Sensor 9612: Seite 3, 115 Ergebnisse
Sensor 9667: Seite 1, 1000 Ergebnisse
Sensor 9667: Seite 2, 1000 Ergebnisse
Sensor 9667: Seite 3, 84 Ergebnisse
Sensor 10235: Seite 1, 1000 Ergebnisse
Sensor 10235: Seite 2, 1000 Ergebnisse
Sensor 10235: Seite 3, 509 Ergebnisse
Sensor 10308: Seite 1, 1000 Ergebnisse
Sensor 10308: Seite 2, 1000 Ergebnisse
Sensor 10308: Seite 3, 449 Ergebnisse
Sensor 10373: Seite 1, 1000 Ergebnisse
Sensor 10373: Seite 2, 1000 Ergebnisse
Sensor 10373: Seite 3, 529 Ergebnisse
Sensor 10385: Seite 1, 1000 Ergebnisse
Sensor 10385: Seite 2, 1000 Ergebnisse
Sensor 10385: Seite 3, 544 Ergebnisse
Sensor 10398: Seite 1, 1000 Ergebnisse
Sensor 10398: Seite 2, 1000 Ergebnisse
Sensor 10398: Seite 3, 439 Ergebnisse
Sensor 30134: Seite 1, 1000 Ergebnisse
Sensor 30134: Seite 2, 1000 Ergebnisse
Sensor 30134: Seite 3, 222 Ergebnisse
Sensor 10443: Seite 1, 1000 Ergebnisse
Sensor 10443: Seite 2, 1000 Ergebnisse
Sensor 10443: Seite 3, 447 Ergebnisse
Sensor 10489: Seite 1, 1000 Ergebnisse
Sensor 10489: Seite 2, 1000 Ergebnisse
Sensor 10489: Seite 3, 473 Ergebnisse
Sensor 10498: Seite 1, 1000 Ergebnisse
Sensor 10498: Seite 2, 1000 Ergebnisse
Sensor 10498: Seite 3, 239 Ergebnisse
Sensor 10513: Seite 1, 594 Ergebnisse
Sensor 10537: Seite 1, 1000 Ergebnisse
Sensor 10537: Seite 2, 1000 Ergebnisse
Sensor 10537: Seite 3, 180 Ergebnisse
Sensor 10542: Seite 1, 1000 Ergebnisse
Sensor 10542: Seite 2, 1000 Ergebnisse
Sensor 10542: Seite 3, 584 Ergebnisse
Sensor 10579: Seite 1, 921 Ergebnisse
Sensor 29333: Seite 1, 1000 Ergebnisse
Sensor 29333: Seite 2, 1000 Ergebnisse
Sensor 29333: Seite 3, 199 Ergebnisse
Sensor 9552: Seite 1, 1000 Ergebnisse
Sensor 9552: Seite 2, 1000 Ergebnisse
Sensor 9552: Seite 3, 176 Ergebnisse
Sensor 7173: Seite 1, 1000 Ergebnisse
Sensor 7173: Seite 2, 891 Ergebnisse
Sensor 9571: Seite 1, 1000 Ergebnisse
Sensor 9571: Seite 2, 1000 Ergebnisse
Sensor 9571: Seite 3, 109 Ergebnisse
Sensor 2683691: Seite 1, 379 Ergebnisse
Sensor 2011617: Seite 1, 952 Ergebnisse
Sensor 2011614: Seite 1, 994 Ergebnisse
Sensor 2011615: Seite 1, 972 Ergebnisse
Sensor 2011618: Seite 1, 911 Ergebnisse
Sensor 2011613: Seite 1, 999 Ergebnisse
Sensor 9569: Seite 1, 1000 Ergebnisse
Sensor 9569: Seite 2, 96 Ergebnisse
Sensor 8668: Seite 1, 686 Ergebnisse
Sensor 2011616: Seite 1, 693 Ergebnisse
Sensor 9406: Seite 1, 1000 Ergebnisse
Sensor 9406: Seite 2, 1000 Ergebnisse
Sensor 9406: Seite 3, 4 Ergebnisse
Sensor 10627: Seite 1, 1000 Ergebnisse
Sensor 10627: Seite 2, 989 Ergebnisse
Sensor 10240: Seite 1, 1000 Ergebnisse
Sensor 10240: Seite 2, 1000 Ergebnisse
Sensor 10240: Seite 3, 4 Ergebnisse
Sensor 10359: Seite 1, 1000 Ergebnisse
Sensor 10359: Seite 2, 956 Ergebnisse
Sensor 10605: Seite 1, 1000 Ergebnisse
Sensor 10605: Seite 2, 671 Ergebnisse
Sensor 10642: Seite 1, 1000 Ergebnisse
Sensor 10642: Seite 2, 962 Ergebnisse
Sensor 4272917: Seite 1, 487 Ergebnisse
Sensor 7049: Seite 1, 1000 Ergebnisse
Sensor 7049: Seite 2, 535 Ergebnisse
Sensor 8674: Seite 1, 1000 Ergebnisse
Sensor 8674: Seite 2, 540 Ergebnisse
Sensor 9114: Seite 1, 1000 Ergebnisse
Sensor 9114: Seite 2, 545 Ergebnisse
Sensor 9751: Seite 1, 1000 Ergebnisse
Sensor 9751: Seite 2, 715 Ergebnisse
Sensor 9952: Seite 1, 1000 Ergebnisse
Sensor 9952: Seite 2, 537 Ergebnisse
Sensor 10419: Seite 1, 1000 Ergebnisse
Sensor 10419: Seite 2, 567 Ergebnisse
Sensor 10494: Seite 1, 1000 Ergebnisse
Sensor 10494: Seite 2, 546 Ergebnisse
Sensor 10630: Seite 1, 1000 Ergebnisse
Sensor 10630: Seite 2, 530 Ergebnisse
Sensor 6983: Seite 1, 1000 Ergebnisse
Sensor 6983: Seite 2, 1000 Ergebnisse
Sensor 6983: Seite 3, 202 Ergebnisse
Sensor 7095: Seite 1, 1000 Ergebnisse
Sensor 7095: Seite 2, 1000 Ergebnisse
Sensor 7095: Seite 3, 99 Ergebnisse
Sensor 25177: Seite 1, 1000 Ergebnisse
Sensor 25177: Seite 2, 346 Ergebnisse
Sensor 25101: Seite 1, 1000 Ergebnisse
Sensor 25101: Seite 2, 487 Ergebnisse
Sensor 25167: Seite 1, 1000 Ergebnisse
Sensor 25167: Seite 2, 947 Ergebnisse
Sensor 7254: Seite 1, 1000 Ergebnisse
Sensor 7254: Seite 2, 1000 Ergebnisse
Sensor 7254: Seite 3, 188 Ergebnisse
Sensor 7281: Seite 1, 1000 Ergebnisse
Sensor 7281: Seite 2, 1000 Ergebnisse
Sensor 7281: Seite 3, 136 Ergebnisse
Sensor 7283: Seite 1, 1000 Ergebnisse
Sensor 7283: Seite 2, 1000 Ergebnisse
Sensor 7283: Seite 3, 202 Ergebnisse
Sensor 2683693: Seite 1, 28 Ergebnisse
Sensor 7059: Seite 1, 1000 Ergebnisse
Sensor 7059: Seite 2, 182 Ergebnisse
Sensor 29282: Seite 1, 850 Ergebnisse
Sensor 30135: Seite 1, 847 Ergebnisse
Sensor 9623: Seite 1, 941 Ergebnisse
Sensor 10553: Seite 1, 707 Ergebnisse
Sensor 7169: Seite 1, 588 Ergebnisse
Sensor 6995: Seite 1, 167 Ergebnisse
Sensor 4273263: Seite 1, 1000 Ergebnisse
Sensor 4273263: Seite 2, 24 Ergebnisse
Sensor 10377: Seite 1, 1000 Ergebnisse
Sensor 10377: Seite 2, 1000 Ergebnisse
Sensor 10377: Seite 3, 488 Ergebnisse
Sensor 10381: Seite 1, 1000 Ergebnisse
Sensor 10381: Seite 2, 1000 Ergebnisse
Sensor 10381: Seite 3, 486 Ergebnisse
Sensor 10422: Seite 1, 1000 Ergebnisse
Sensor 10422: Seite 2, 1000 Ergebnisse
Sensor 10422: Seite 3, 498 Ergebnisse
Sensor 10428: Seite 1, 1000 Ergebnisse
Sensor 10428: Seite 2, 1000 Ergebnisse
Sensor 10428: Seite 3, 505 Ergebnisse
Sensor 10468: Seite 1, 1000 Ergebnisse
Sensor 10468: Seite 2, 1000 Ergebnisse
Sensor 10468: Seite 3, 517 Ergebnisse
Sensor 12144657: Seite 1, 349 Ergebnisse
Sensor 10546: Seite 1, 1000 Ergebnisse
Sensor 10546: Seite 2, 1000 Ergebnisse
Sensor 10546: Seite 3, 495 Ergebnisse
Sensor 10558: Seite 1, 1000 Ergebnisse
Sensor 10558: Seite 2, 1000 Ergebnisse
Sensor 10558: Seite 3, 502 Ergebnisse
Sensor 10570: Seite 1, 1000 Ergebnisse
Sensor 10570: Seite 2, 1000 Ergebnisse
Sensor 25034: Seite 1, 1000 Ergebnisse
Sensor 25034: Seite 2, 1000 Ergebnisse
Sensor 25034: Seite 3, 248 Ergebnisse
Sensor 10601: Seite 1, 1000 Ergebnisse
Sensor 10601: Seite 2, 1000 Ergebnisse
Sensor 10601: Seite 3, 408 Ergebnisse
Sensor 9580: Seite 1, 1000 Ergebnisse
Sensor 9580: Seite 2, 1000 Ergebnisse
Sensor 9580: Seite 3, 672 Ergebnisse
Sensor 10364: Seite 1, 1000 Ergebnisse
Sensor 10364: Seite 2, 1000 Ergebnisse
Sensor 10364: Seite 3, 326 Ergebnisse
Sensor 6199: Seite 1, 1000 Ergebnisse
Sensor 6199: Seite 2, 445 Ergebnisse
Sensor 7056: Seite 1, 973 Ergebnisse
Sensor 10667: Seite 1, 1000 Ergebnisse
Sensor 10667: Seite 2, 675 Ergebnisse
Sensor 10665: Seite 1, 1000 Ergebnisse
Sensor 10665: Seite 2, 680 Ergebnisse
Sensor 10666: Seite 1, 1000 Ergebnisse
Sensor 10666: Seite 2, 195 Ergebnisse
Sensor 10689: Seite 1, 1000 Ergebnisse
Sensor 10689: Seite 2, 679 Ergebnisse
Sensor 10711: Seite 1, 1000 Ergebnisse
Sensor 10711: Seite 2, 616 Ergebnisse
Sensor 7242: Seite 1, 1000 Ergebnisse
Sensor 7242: Seite 2, 884 Ergebnisse
Sensor 9575: Seite 1, 1000 Ergebnisse
Sensor 9575: Seite 2, 443 Ergebnisse
Sensor 9591: Seite 1, 1000 Ergebnisse
Sensor 9591: Seite 2, 1000 Ergebnisse
Sensor 9591: Seite 3, 16 Ergebnisse
Sensor 9907: Seite 1, 1000 Ergebnisse
Sensor 9907: Seite 2, 1000 Ergebnisse
Sensor 9907: Seite 3, 18 Ergebnisse
Sensor 9911: Seite 1, 1000 Ergebnisse
Sensor 9911: Seite 2, 977 Ergebnisse
Sensor 9561: Seite 1, 460 Ergebnisse
Sensor 21672: Seite 1, 1000 Ergebnisse
Sensor 21672: Seite 2, 991 Ergebnisse
Sensor 10260: Seite 1, 1000 Ergebnisse
Sensor 10260: Seite 2, 1000 Ergebnisse
Sensor 10260: Seite 3, 524 Ergebnisse
Sensor 10288: Seite 1, 1000 Ergebnisse
Sensor 10288: Seite 2, 1000 Ergebnisse
Sensor 10288: Seite 3, 580 Ergebnisse
Sensor 10318: Seite 1, 1000 Ergebnisse
Sensor 10318: Seite 2, 1000 Ergebnisse
Sensor 10318: Seite 3, 415 Ergebnisse
Sensor 10330: Seite 1, 1000 Ergebnisse
Sensor 10330: Seite 2, 1000 Ergebnisse
Sensor 10330: Seite 3, 494 Ergebnisse
Sensor 24612: Seite 1, 1000 Ergebnisse
Sensor 24612: Seite 2, 1000 Ergebnisse
Sensor 24612: Seite 3, 213 Ergebnisse
Sensor 10252: Seite 1, 1000 Ergebnisse
Sensor 10252: Seite 2, 1000 Ergebnisse
Sensor 10252: Seite 3, 490 Ergebnisse
Sensor 7107: Seite 1, 1000 Ergebnisse
Sensor 7107: Seite 2, 1000 Ergebnisse
Sensor 7107: Seite 3, 163 Ergebnisse
Sensor 7165: Seite 1, 1000 Ergebnisse
Sensor 7165: Seite 2, 1000 Ergebnisse
Sensor 7165: Seite 3, 153 Ergebnisse
Sensor 7327: Seite 1, 1000 Ergebnisse
Sensor 7327: Seite 2, 1000 Ergebnisse
Sensor 7327: Seite 3, 159 Ergebnisse
Sensor 7378: Seite 1, 1000 Ergebnisse
Sensor 7378: Seite 2, 1000 Ergebnisse
Sensor 7378: Seite 3, 146 Ergebnisse
Sensor 10244: Seite 1, 1000 Ergebnisse
Sensor 10244: Seite 2, 1000 Ergebnisse
Sensor 10244: Seite 3, 155 Ergebnisse
Sensor 10272: Seite 1, 1000 Ergebnisse
Sensor 10272: Seite 2, 1000 Ergebnisse
Sensor 10272: Seite 3, 146 Ergebnisse
Sensor 10275: Seite 1, 1000 Ergebnisse
Sensor 10275: Seite 2, 1000 Ergebnisse
Sensor 10275: Seite 3, 149 Ergebnisse
Sensor 10350: Seite 1, 1000 Ergebnisse
Sensor 10350: Seite 2, 1000 Ergebnisse
Sensor 10350: Seite 3, 143 Ergebnisse
Sensor 10409: Seite 1, 1000 Ergebnisse
Sensor 10409: Seite 2, 1000 Ergebnisse
Sensor 10409: Seite 3, 164 Ergebnisse
Sensor 10415: Seite 1, 1000 Ergebnisse
Sensor 10415: Seite 2, 1000 Ergebnisse
Sensor 10415: Seite 3, 151 Ergebnisse
Sensor 10433: Seite 1, 1000 Ergebnisse
Sensor 10433: Seite 2, 1000 Ergebnisse
Sensor 10433: Seite 3, 140 Ergebnisse
Sensor 30079: Seite 1, 1000 Ergebnisse
Sensor 30079: Seite 2, 905 Ergebnisse
Sensor 30078: Seite 1, 1000 Ergebnisse
Sensor 30078: Seite 2, 908 Ergebnisse
Sensor 10612: Seite 1, 1000 Ergebnisse
Sensor 10612: Seite 2, 1000 Ergebnisse
Sensor 10612: Seite 3, 163 Ergebnisse
Sensor 10640: Seite 1, 1000 Ergebnisse
Sensor 10640: Seite 2, 1000 Ergebnisse
Sensor 10640: Seite 3, 159 Ergebnisse
Sensor 10651: Seite 1, 1000 Ergebnisse
Sensor 10651: Seite 2, 1000 Ergebnisse
Sensor 10651: Seite 3, 164 Ergebnisse
Sensor 7066: Seite 1, 80 Ergebnisse
Sensor 4273208: Seite 1, 1000 Ergebnisse
Sensor 4273208: Seite 2, 21 Ergebnisse
Sensor 24423: Seite 1, 1000 Ergebnisse
Sensor 24423: Seite 2, 919 Ergebnisse
Sensor 10516: Seite 1, 1000 Ergebnisse
Sensor 10516: Seite 2, 1000 Ergebnisse
Sensor 10516: Seite 3, 524 Ergebnisse
Sensor 10345: Seite 1, 1000 Ergebnisse
Sensor 10345: Seite 2, 1000 Ergebnisse
Sensor 10345: Seite 3, 560 Ergebnisse
Sensor 9935: Seite 1, 1000 Ergebnisse
Sensor 9935: Seite 2, 452 Ergebnisse
Sensor 10028: Seite 1, 1000 Ergebnisse
Sensor 10028: Seite 2, 388 Ergebnisse
Sensor 10100: Seite 1, 1000 Ergebnisse
Sensor 10100: Seite 2, 478 Ergebnisse
Sensor 7080: Seite 1, 1000 Ergebnisse
Sensor 7080: Seite 2, 1000 Ergebnisse
Sensor 7080: Seite 3, 231 Ergebnisse
Sensor 23695: Seite 1, 1000 Ergebnisse
Sensor 23695: Seite 2, 1000 Ergebnisse
Sensor 23695: Seite 3, 588 Ergebnisse
Sensor 10066: Seite 1, 1000 Ergebnisse
Sensor 10066: Seite 2, 218 Ergebnisse
Sensor 9988: Seite 1, 1000 Ergebnisse
Sensor 9988: Seite 2, 208 Ergebnisse
Sensor 10036: Seite 1, 1000 Ergebnisse
Sensor 10036: Seite 2, 224 Ergebnisse
Sensor 23690: Seite 1, 1000 Ergebnisse
Sensor 23690: Seite 2, 860 Ergebnisse
Sensor 23702: Seite 1, 1000 Ergebnisse
Sensor 23702: Seite 2, 891 Ergebnisse
Sensor 23675: Seite 1, 1000 Ergebnisse
Sensor 23675: Seite 2, 835 Ergebnisse
Sensor 5712: Seite 1, 1000 Ergebnisse
Sensor 5712: Seite 2, 889 Ergebnisse
Sensor 5696: Seite 1, 943 Ergebnisse
Sensor 5701: Seite 1, 1000 Ergebnisse
Sensor 5701: Seite 2, 1000 Ergebnisse
Sensor 5701: Seite 3, 154 Ergebnisse
Sensor 23685: Seite 1, 1000 Ergebnisse
Sensor 23685: Seite 2, 895 Ergebnisse
Sensor 5705: Seite 1, 1000 Ergebnisse
Sensor 5705: Seite 2, 1000 Ergebnisse
Sensor 5705: Seite 3, 82 Ergebnisse
Sensor 29386: Seite 1, 1000 Ergebnisse
Sensor 29386: Seite 2, 914 Ergebnisse
Sensor 5723: Seite 1, 1000 Ergebnisse
Sensor 5723: Seite 2, 1000 Ergebnisse
Sensor 5723: Seite 3, 125 Ergebnisse
Sensor 23700: Seite 1, 1000 Ergebnisse
Sensor 23700: Seite 2, 798 Ergebnisse
Sensor 9922: Seite 1, 1000 Ergebnisse
Sensor 9922: Seite 2, 226 Ergebnisse
Sensor 23701: Seite 1, 1000 Ergebnisse
Sensor 23701: Seite 2, 204 Ergebnisse
Sensor 10678: Seite 1, 1000 Ergebnisse
Sensor 10678: Seite 2, 661 Ergebnisse
Sensor 238926: Seite 1, 1000 Ergebnisse
Sensor 238926: Seite 2, 455 Ergebnisse
Sensor 9558: Seite 1, 1000 Ergebnisse
Sensor 9558: Seite 2, 1000 Ergebnisse
Sensor 9558: Seite 3, 114 Ergebnisse
Sensor 10281: Seite 1, 1000 Ergebnisse
Sensor 10281: Seite 2, 1000 Ergebnisse
Sensor 10281: Seite 3, 174 Ergebnisse
Sensor 7347: Seite 1, 1000 Ergebnisse
Sensor 7347: Seite 2, 534 Ergebnisse
Sensor 9990: Seite 1, 1000 Ergebnisse
Sensor 9990: Seite 2, 782 Ergebnisse
Sensor 10203: Seite 1, 662 Ergebnisse
Sensor 10172: Seite 1, 1000 Ergebnisse
Sensor 10172: Seite 2, 762 Ergebnisse
Sensor 10014: Seite 1, 1000 Ergebnisse
Sensor 10014: Seite 2, 1000 Ergebnisse
Sensor 10014: Seite 3, 303 Ergebnisse
Sensor 10128: Seite 1, 1000 Ergebnisse
Sensor 10128: Seite 2, 1000 Ergebnisse
Sensor 10128: Seite 3, 435 Ergebnisse
Sensor 10199: Seite 1, 1000 Ergebnisse
Sensor 10199: Seite 2, 1000 Ergebnisse
Sensor 10199: Seite 3, 181 Ergebnisse
Sensor 9959: Seite 1, 1000 Ergebnisse
Sensor 9959: Seite 2, 1000 Ergebnisse
Sensor 9959: Seite 3, 313 Ergebnisse
Sensor 10044: Seite 1, 1000 Ergebnisse
Sensor 10044: Seite 2, 769 Ergebnisse
Sensor 10114: Seite 1, 1000 Ergebnisse
Sensor 10114: Seite 2, 760 Ergebnisse
Sensor 10084: Seite 1, 1000 Ergebnisse
Sensor 10084: Seite 2, 1000 Ergebnisse
Sensor 10084: Seite 3, 359 Ergebnisse
Sensor 10103: Seite 1, 1000 Ergebnisse
Sensor 10103: Seite 2, 786 Ergebnisse
Sensor 10085: Seite 1, 1000 Ergebnisse
Sensor 10085: Seite 2, 734 Ergebnisse
Sensor 9989: Seite 1, 1000 Ergebnisse
Sensor 9989: Seite 2, 516 Ergebnisse
Sensor 10158: Seite 1, 1000 Ergebnisse
Sensor 10158: Seite 2, 754 Ergebnisse
Sensor 23816: Seite 1, 1000 Ergebnisse
Sensor 23816: Seite 2, 977 Ergebnisse
Sensor 10191: Seite 1, 1000 Ergebnisse
Sensor 10191: Seite 2, 609 Ergebnisse
Sensor 9524: Seite 1, 1000 Ergebnisse
Sensor 9524: Seite 2, 1000 Ergebnisse

[{'date': '2019-01-09', 'value': 20.818181818181817},
 {'date': '2019-01-10', 'value': 24.625},
 {'date': '2019-01-11', 'value': 25.875},
 {'date': '2019-01-29', 'value': 23.3},
 {'date': '2019-01-30', 'value': 15.590909090909092},
 {'date': '2019-01-31', 'value': 16.714285714285715},
 {'date': '2019-02-01', 'value': 16.428571428571427},
 {'date': '2019-02-02', 'value': 10.833333333333334},
 {'date': '2019-02-03', 'value': 11.0},
 {'date': '2019-02-04', 'value': 28.615384615384617},
 {'date': '2019-02-05', 'value': 38.833333333333336},
 {'date': '2019-02-11', 'value': 29.333333333333332},
 {'date': '2019-02-13', 'value': 42.0},
 {'date': '2019-02-14', 'value': 36.6},
 {'date': '2019-02-15', 'value': 31.5},
 {'date': '2019-02-16', 'value': 34.0},
 {'date': '2019-02-17', 'value': 21.875},
 {'date': '2019-02-18', 'value': 27.857142857142858},
 {'date': '2019-02-19', 'value': 30.083333333333332},
 {'date': '2019-02-20', 'value': 44.375},
 {'date': '2019-02-21', 'value': 36.833333333333336},
 {'date': '2019-02-22', 'value': 49.5625},
 {'date': '2019-02-23', 'value': 45.21052631578947},
 {'date': '2019-02-24', 'value': 31.333333333333332},
 {'date': '2019-02-25', 'value': 43.42857142857143},
 {'date': '2019-02-26', 'value': 45.1},
 {'date': '2019-02-27', 'value': 50.214285714285715},
 {'date': '2019-02-28', 'value': 46.46153846153846},
 {'date': '2019-03-01', 'value': 43.5},
 {'date': '2019-03-02', 'value': 37.75},
 {'date': '2019-03-03', 'value': 28.58823529411765},
 {'date': '2019-03-04', 'value': 37.13333333333333},
 {'date': '2019-03-05', 'value': 31.0},
 {'date': '2019-03-06', 'value': 43.666666666666664},
 {'date': '2019-03-07', 'value': 12.272727272727273},
 {'date': '2019-03-08', 'value': 25.0},
 {'date': '2019-03-09', 'value': 27.555555555555557},
 {'date': '2019-03-10', 'value': 30.545454545454547},
 {'date': '2019-03-11', 'value': 31.533333333333335},
 {'date': '2019-03-12', 'value': 31.869565217391305},
 {'date': '2019-03-13', 'value': 28.73913043478261},
 {'date': '2019-03-14', 'value': 27.0},
 {'date': '2019-03-15', 'value': 28.523809523809526},
 {'date': '2019-03-16', 'value': 33.285714285714285},
 {'date': '2019-03-17', 'value': 32.5},
 {'date': '2019-03-18', 'value': 23.363636363636363},
 {'date': '2019-03-19', 'value': 22.904761904761905},
 {'date': '2019-03-20', 'value': 23.095238095238095},
 {'date': '2019-03-21', 'value': 39.10526315789474},
 {'date': '2019-03-22', 'value': 35.111111111111114},
 {'date': '2019-03-23', 'value': 33.7},
 {'date': '2019-03-24', 'value': 31.3},
 {'date': '2019-03-25', 'value': 38.611111111111114},
 {'date': '2019-03-26', 'value': 32.43478260869565},
 {'date': '2019-03-27', 'value': 32.73913043478261},
 {'date': '2019-03-28', 'value': 31.40909090909091},
 {'date': '2019-03-29', 'value': 27.727272727272727},
 {'date': '2019-03-30', 'value': 19.35},
 {'date': '2019-03-31', 'value': 20.7},
 {'date': '2019-04-01', 'value': 30.227272727272727},
 {'date': '2019-04-02', 'value': 39.19047619047619},
 {'date': '2019-04-03', 'value': 17.05},
 {'date': '2019-04-04', 'value': 8.416666666666666},
 {'date': '2019-04-05', 'value': 14.5},
 {'date': '2019-04-06', 'value': 11.6},
 {'date': '2019-04-07', 'value': 11.545454545454545},
 {'date': '2019-04-08', 'value': 17.227272727272727},
 {'date': '2019-04-09', 'value': 11.15},
 {'date': '2019-04-10', 'value': 14.272727272727273},
 {'date': '2019-04-11', 'value': 17.19047619047619},
 {'date': '2019-04-12', 'value': 21.772727272727273},
 {'date': '2019-04-13', 'value': 29.0},
 {'date': '2019-04-14', 'value': 19.25},
 {'date': '2019-04-15', 'value': 21.90909090909091},
 {'date': '2019-04-16', 'value': 19.789473684210527},
 {'date': '2019-04-17', 'value': 21.636363636363637},
 {'date': '2019-04-18', 'value': 20.047619047619047},
 {'date': '2019-04-19', 'value': 24.333333333333332},
 {'date': '2019-04-20', 'value': 19.526315789473685},
 {'date': '2019-04-21', 'value': 22.636363636363637},
 {'date': '2019-04-22', 'value': 39.57142857142857},
 {'date': '2019-04-23', 'value': 24.36842105263158},
 {'date': '2019-04-24', 'value': 17.181818181818183},
 {'date': '2019-04-25', 'value': 18.238095238095237},
 {'date': '2019-04-26', 'value': 15.272727272727273},
 {'date': '2019-04-27', 'value': 16.31578947368421},
 {'date': '2019-04-28', 'value': 20.0},
 {'date': '2019-04-29', 'value': 27.076923076923077},
 {'date': '2019-04-30', 'value': 20.181818181818183},
 {'date': '2019-05-01', 'value': 19.238095238095237},
 {'date': '2019-05-02', 'value': 18.80952380952381},
 {'date': '2019-05-03', 'value': 16.272727272727273},
 {'date': '2019-05-04', 'value': 9.947368421052632},
 {'date': '2019-05-05', 'value': 12.956521739130435},
 {'date': '2019-05-06', 'value': 20.94736842105263},
 {'date': '2019-05-07', 'value': 24.944444444444443},
 {'date': '2019-05-08', 'value': 30.26086956521739},
 {'date': '2019-05-09', 'value': 18.565217391304348},
 {'date': '2019-05-10', 'value': 26.75},
 {'date': '2019-05-11', 'value': 21.047619047619047},
 {'date': '2019-05-12', 'value': 16.764705882352942},
 {'date': '2019-05-13', 'value': 19.0},
 {'date': '2019-05-14', 'value': 27.526315789473685},
 {'date': '2019-05-15', 'value': 28.785714285714285},
 {'date': '2019-05-16', 'value': 15.0},
 {'date': '2019-05-18', 'value': 13.083333333333334},
 {'date': '2019-05-19', 'value': 8.75},
 {'date': '2019-05-20', 'value': 13.894736842105264},
 {'date': '2019-05-25', 'value': 9.0},
 {'date': '2019-05-27', 'value': 19.833333333333332},
 {'date': '2019-06-01', 'value': 25.666666666666668},
 {'date': '2019-06-04', 'value': 23.0},
 {'date': '2019-06-08', 'value': 16.666666666666668},
 {'date': '2019-06-15', 'value': 32.0},
 {'date': '2019-06-21', 'value': 13.0},
 {'date': '2019-06-22', 'value': 17.0},
 {'date': '2019-06-29', 'value': 55.0},
 {'date': '2019-07-03', 'value': -999.0},
 {'date': '2019-07-04', 'value': -582.75},
 {'date': '2019-07-05', 'value': 0.0},
 {'date': '2019-07-06', 'value': 0.0},
 {'date': '2019-07-07', 'value': 0.0},
 {'date': '2019-07-08', 'value': 0.0},
 {'date': '2019-07-09', 'value': 0.0},
 {'date': '2019-07-10', 'value': 0.0},
 {'date': '2019-07-11', 'value': 1.5},
 {'date': '2019-07-12', 'value': 0.0},
 {'date': '2019-07-13', 'value': 13.176470588235293},
 {'date': '2019-07-14', 'value': 9.916666666666666},
 {'date': '2019-07-15', 'value': 7.375},
 {'date': '2019-07-16', 'value': 0.0},
 {'date': '2019-07-17', 'value': 0.0},
 {'date': '2019-07-18', 'value': 0.0},
 {'date': '2019-07-19', 'value': 0.0},
 {'date': '2019-07-20', 'value': 0.0},
 {'date': '2019-07-21', 'value': 0.0},
 {'date': '2019-07-22', 'value': 2.25},
 {'date': '2019-07-23', 'value': 0.0},
 {'date': '2019-07-24', 'value': 0.0},
 {'date': '2019-07-25', 'value': 10.75},
 {'date': '2019-07-26', 'value': 0.0},
 {'date': '2019-07-27', 'value': 0.0},
 {'date': '2019-07-28', 'value': 0.0},
 {'date': '2019-07-29', 'value': 6.25},
 {'date': '2019-07-30', 'value': 0.0},
 {'date': '2019-07-31', 'value': 0.0},
 {'date': '2019-08-01', 'value': 0.0},
 {'date': '2019-08-02', 'value': 0.0},
 {'date': '2019-08-03', 'value': 0.0},
 {'date': '2019-08-04', 'value': 0.0},
 {'date': '2019-08-05', 'value': 0.0},
 {'date': '2019-08-06', 'value': 6.375},
 {'date': '2019-08-07', 'value': 7.0},
 {'date': '2019-08-08', 'value': 0.0},
 {'date': '2019-08-09', 'value': 0.0},
 {'date': '2019-08-10', 'value': 0.0},
 {'date': '2019-08-11', 'value': 0.0},
 {'date': '2019-08-12', 'value': 0.0},
 {'date': '2019-08-13', 'value': 0.0},
 {'date': '2019-08-14', 'value': 0.0},
 {'date': '2019-08-15', 'value': 0.0},
 {'date': '2019-08-16', 'value': 0.0},
 {'date': '2019-08-17', 'value': 0.0},
 {'date': '2019-08-18', 'value': 0.0},
 {'date': '2019-08-19', 'value': 0.5416666666666666},
 {'date': '2019-08-20', 'value': 0.0},
 {'date': '2019-08-21', 'value': 0.0},
 {'date': '2019-08-22', 'value': 0.0},
 {'date': '2019-08-23', 'value': 4.041666666666667},
 {'date': '2019-08-24', 'value': 0.0},
 {'date': '2019-08-25', 'value': 0.0},
 {'date': '2019-08-26', 'value': 0.0},
 {'date': '2019-08-27', 'value': 0.0},
 {'date': '2019-08-28', 'value': 0.0},
 {'date': '2019-08-29', 'value': 0.0},
 {'date': '2019-08-30', 'value': 0.0},
 {'date': '2019-08-31', 'value': 0.0},
 {'date': '2019-09-01', 'value': 0.0},
 {'date': '2019-09-02', 'value': 0.0},
 {'date': '2019-09-03', 'value': 0.5833333333333334},
 {'date': '2019-09-04', 'value': 0.0},
 {'date': '2019-09-05', 'value': 0.0},
 {'date': '2019-09-06', 'value': 0.0},
 {'date': '2019-09-07', 'value': 0.0},
 {'date': '2019-09-08', 'value': 0.0},
 {'date': '2019-09-09', 'value': 0.0},
 {'date': '2019-09-10', 'value': 0.0},
 {'date': '2019-09-11', 'value': 0.0},
 {'date': '2019-09-12', 'value': 0.0},
 {'date': '2019-09-13', 'value': 0.0},
 {'date': '2019-09-14', 'value': 0.0},
 {'date': '2019-09-15', 'value': 13.652173913043478},
 {'date': '2019-09-16', 'value': 19.916666666666668},
 {'date': '2019-09-17', 'value': 15.916666666666666},
 {'date': '2019-09-18', 'value': 0.0},
 {'date': '2019-09-19', 'value': 0.0},
 {'date': '2019-09-20', 'value': 0.0},
 {'date': '2019-09-21', 'value': 0.0},
 {'date': '2019-09-22', 'value': 0.0},
 {'date': '2019-09-23', 'value': 0.0},
 {'date': '2019-09-24', 'value': 0.0},
 {'date': '2019-09-25', 'value': 0.0},
 {'date': '2019-09-26', 'value': 0.0},
 {'date': '2019-09-27', 'value': 0.0},
 {'date': '2019-09-28', 'value': 1.3043478260869565},
 {'date': '2019-09-29', 'value': 7.375},
 {'date': '2019-09-30', 'value': 9.666666666666666},
 {'date': '2019-10-01', 'value': 0.0},
 {'date': '2019-10-02', 'value': 1.0416666666666667},
 {'date': '2019-10-03', 'value': 0.0},
 {'date': '2019-10-04', 'value': 3.9166666666666665},
 {'date': '2019-10-05', 'value': 0.0},
 {'date': '2019-10-06', 'value': 0.0},
 {'date': '2019-10-07', 'value': 0.0},
 {'date': '2019-10-08', 'value': 2.125},
 {'date': '2019-10-09', 'value': 1.0833333333333333},
 {'date': '2019-10-10', 'value': 12.5},
 {'date': '2019-10-11', 'value': 0.0},
 {'date': '2019-10-12', 'value': 0.0},
 {'date': '2019-10-13', 'value': 0.0},
 {'date': '2019-10-14', 'value': 0.0},
 {'date': '2019-10-15', 'value': 0.0},
 {'date': '2019-10-16', 'value': 0.0},
 {'date': '2019-10-17', 'value': 0.0},
 {'date': '2019-10-18', 'value': 0.0},
 {'date': '2019-10-19', 'value': 0.0},
 {'date': '2019-10-20', 'value': 0.0},
 {'date': '2019-10-21', 'value': 0.0},
 {'date': '2019-10-22', 'value': 0.0},
 {'date': '2019-10-23', 'value': 0.0},
 {'date': '2019-10-24', 'value': 0.0},
 {'date': '2019-10-25', 'value': 0.0},
 {'date': '2019-10-26', 'value': 1.7727272727272727},
 {'date': '2019-10-27', 'value': 0.0},
 {'date': '2019-10-28', 'value': 0.8333333333333334},
 {'date': '2019-10-29', 'value': 1.0},
 {'date': '2019-10-30', 'value': 1.0833333333333333},
 {'date': '2019-10-31', 'value': 3.210526315789474},
 {'date': '2019-11-01', 'value': 5.541666666666667},
 {'date': '2019-11-02', 'value': 6.4},
 {'date': '2019-11-03', 'value': 0.9583333333333334},
 {'date': '2019-11-04', 'value': 0.2916666666666667},
 {'date': '2019-11-05', 'value': 1.0869565217391304},
 {'date': '2019-11-06', 'value': 0.0},
 {'date': '2019-11-07', 'value': 1.7083333333333333},
 {'date': '2019-11-08', 'value': 2.125},
 {'date': '2019-11-09', 'value': 0.0},
 {'date': '2019-11-10', 'value': 0.21739130434782608},
 {'date': '2019-11-11', 'value': 1.625},
 {'date': '2019-11-12', 'value': 1.75},
 {'date': '2019-11-13', 'value': 9.26086956521739},
 {'date': '2019-11-14', 'value': 2.1666666666666665},
 {'date': '2019-11-15', 'value': 0.0},
 {'date': '2019-11-16', 'value': 0.0},
 {'date': '2019-11-17', 'value': 0.0},
 {'date': '2019-11-18', 'value': 0.9583333333333334},
 {'date': '2019-11-19', 'value': 0.0},
 {'date': '2019-11-20', 'value': 0.0},
 {'date': '2019-11-21', 'value': 0.0},
 {'date': '2019-11-22', 'value': 1.0416666666666667},
 {'date': '2019-11-23', 'value': 0.25},
 {'date': '2019-11-24', 'value': 0.0},
 {'date': '2019-11-25', 'value': 0.0},
 {'date': '2019-11-26', 'value': 1.625},
 {'date': '2019-11-27', 'value': 0.0},
 {'date': '2019-11-28', 'value': 0.0},
 {'date': '2019-11-29', 'value': 0.0},
 {'date': '2019-11-30', 'value': 0.75},
 {'date': '2019-12-01', 'value': 0.0},
 {'date': '2019-12-02', 'value': 20.416666666666668},
 {'date': '2019-12-03', 'value': 20.25},
 {'date': '2019-12-04', 'value': 0.0},
 {'date': '2019-12-05', 'value': 0.0},
 {'date': '2019-12-06', 'value': 0.0},
 {'date': '2019-12-07', 'value': 0.4583333333333333},
 {'date': '2019-12-08', 'value': 0.0},
 {'date': '2019-12-09', 'value': 0.0},
 {'date': '2019-12-10', 'value': 0.0},
 {'date': '2019-12-11', 'value': 0.0},
 {'date': '2019-12-12', 'value': 0.0},
 {'date': '2019-12-13', 'value': 0.0},
 {'date': '2019-12-14', 'value': 0.2916666666666667},
 {'date': '2019-12-15', 'value': 0.0},
 {'date': '2019-12-16', 'value': 0.0},
 {'date': '2019-12-17', 'value': 0.0},
 {'date': '2019-12-18', 'value': 0.0},
 {'date': '2019-12-19', 'value': 0.0},
 {'date': '2019-12-20', 'value': 0.0},
 {'date': '2019-12-21', 'value': 0.2631578947368421},
 {'date': '2019-12-22', 'value': 0.0},
 {'date': '2019-12-23', 'value': 0.0},
 {'date': '2019-12-24', 'value': 7.333333333333333},
 {'date': '2019-12-25', 'value': 21.416666666666668},
 {'date': '2019-12-26', 'value': 19.333333333333332},
 {'date': '2019-12-27', 'value': 23.666666666666668},
 {'date': '2019-12-28', 'value': 30.181818181818183},
 {'date': '2019-12-29', 'value': 21.333333333333332},
 {'date': '2019-12-30', 'value': 21.625},
 {'date': '2019-12-31', 'value': 19.869565217391305},
 {'date': '2020-01-01', 'value': 20.956521739130434},
 {'date': '2020-01-02', 'value': 23.59090909090909},
 {'date': '2020-01-03', 'value': 17.956521739130434},
 {'date': '2020-01-04', 'value': 20.047619047619047},
 {'date': '2020-01-05', 'value': 16.714285714285715},
 {'date': '2020-01-07', 'value': 27.1},
 {'date': '2020-01-09', 'value': 27.136363636363637},
 {'date': '2020-01-10', 'value': 18.375},
 {'date': '2020-01-11', 'value': 21.782608695652176},
 {'date': '2020-01-12', 'value': 24.166666666666668},
 {'date': '2020-01-13', 'value': 36.666666666666664},
 {'date': '2020-01-14', 'value': 32.095238095238095},
 {'date': '2020-01-15', 'value': 36.625},
 {'date': '2020-01-16', 'value': 37.73913043478261},
 {'date': '2020-01-17', 'value': 26.041666666666668},
 {'date': '2020-01-18', 'value': 20.82608695652174},
 {'date': '2020-01-19', 'value': 11.75},
 {'date': '2020-01-20', 'value': 20.869565217391305},
 {'date': '2020-01-21', 'value': 7.904761904761905},
 {'date': '2020-01-22', 'value': 42.588235294117645},
 {'date': '2020-01-23', 'value': 42.47826086956522},
 {'date': '2020-01-24', 'value': 52.583333333333336},
 {'date': '2020-01-25', 'value': 62.68181818181818},
 {'date': '2020-01-26', 'value': 32.833333333333336},
 {'date': '2020-01-27', 'value': 16.434782608695652},
 {'date': '2020-01-28', 'value': 15.708333333333334},
 {'date': '2020-01-29', 'value': 30.40909090909091},
 {'date': '2020-01-30', 'value': 22.73913043478261},
 {'date': '2020-01-31', 'value': 37.19047619047619},
 {'date': '2020-02-01', 'value': 18.458333333333332},
 {'date': '2020-02-02', 'value': 17.91304347826087},
 {'date': '2020-02-03', 'value': 35.791666666666664},
 {'date': '2020-02-04', 'value': 43.17391304347826},
 {'date': '2020-02-05', 'value': 24.91304347826087},
 {'date': '2020-02-06', 'value': 30.363636363636363},
 {'date': '2020-02-07', 'value': 26.0},
 {'date': '2020-02-08', 'value': 26.772727272727273},
 {'date': '2020-02-09', 'value': 26.666666666666668},
 {'date': '2020-02-10', 'value': 23.166666666666668},
 {'date': '2020-02-11', 'value': 28.695652173913043},
 {'date': '2020-02-12', 'value': 19.26086956521739},
 {'date': '2020-02-13', 'value': 18.545454545454547},
 {'date': '2020-02-14', 'value': 35.75},
 {'date': '2020-02-15', 'value': 24.434782608695652},
 {'date': '2020-02-16', 'value': 19.541666666666668},
 {'date': '2020-02-17', 'value': 26.75},
 {'date': '2020-02-18', 'value': 18.25},
 {'date': '2020-02-19', 'value': 24.217391304347824},
 {'date': '2020-02-20', 'value': 30.916666666666668},
 {'date': '2020-02-21', 'value': 32.916666666666664},
 {'date': '2020-02-22', 'value': 30.90909090909091},
 {'date': '2020-02-23', 'value': 26.333333333333332},
 {'date': '2020-02-24', 'value': 36.91304347826087},
 {'date': '2020-02-25', 'value': 37.791666666666664},
 {'date': '2020-02-26', 'value': 35.91304347826087},
 {'date': '2020-02-27', 'value': 25.916666666666668},
 {'date': '2020-02-28', 'value': 29.26086956521739},
 {'date': '2020-02-29', 'value': 66.9090909090909},
 {'date': '2020-03-01', 'value': 30.608695652173914},
 {'date': '2020-03-02', 'value': 17.208333333333332},
 {'date': '2020-03-03', 'value': 9.708333333333334},
 {'date': '2020-03-04', 'value': 28.75},
 {'date': '2020-03-05', 'value': 25.142857142857142},
 {'date': '2020-03-06', 'value': 15.428571428571429},
 {'date': '2020-03-07', 'value': 15.173913043478262},
 {'date': '2020-03-08', 'value': 26.0},
 {'date': '2020-03-09', 'value': 21.47826086956522},
 {'date': '2020-03-10', 'value': 25.875},
 {'date': '2020-03-11', 'value': 34.25},
 {'date': '2020-03-12', 'value': 33.82608695652174},
 {'date': '2020-03-13', 'value': 26.166666666666668},
 {'date': '2020-03-14', 'value': 24.26086956521739},
 {'date': '2020-03-15', 'value': 17.083333333333332},
 {'date': '2020-03-16', 'value': 13.173913043478262},
 {'date': '2020-03-17', 'value': 19.166666666666668},
 {'date': '2020-03-18', 'value': 21.458333333333332},
 {'date': '2020-03-19', 'value': 21.1},
 {'date': '2020-03-20', 'value': 17.5},
 {'date': '2020-03-21', 'value': 17.954545454545453},
 {'date': '2020-03-22', 'value': 23.833333333333332},
 {'date': '2020-03-23', 'value': 19.692307692307693},
 {'date': '2020-03-24', 'value': 21.083333333333332},
 {'date': '2020-03-25', 'value': 15.166666666666666},
 {'date': '2020-03-26', 'value': 15.833333333333334},
 {'date': '2020-03-27', 'value': 18.181818181818183},
 {'date': '2020-03-28', 'value': 18.208333333333332},
 {'date': '2020-03-29', 'value': 20.5},
 {'date': '2020-03-30', 'value': 16.0},
 {'date': '2020-03-31', 'value': 11.0},
 {'date': '2020-04-02', 'value': 6.0},
 {'date': '2020-04-03', 'value': 8.0},
 {'date': '2020-04-04', 'value': 19.0},
 {'date': '2020-04-06', 'value': 8.0},
 {'date': '2020-04-11', 'value': 21.0},
 {'date': '2020-04-17', 'value': 30.0},
 {'date': '2020-05-02', 'value': 20.0},
 {'date': '2020-05-06', 'value': 23.0},
 {'date': '2020-05-09', 'value': 28.666666666666668},
 {'date': '2020-05-16', 'value': 44.5},
 {'date': '2020-05-20', 'value': 20.0},
 {'date': '2020-05-22', 'value': 29.0},
 {'date': '2020-05-23', 'value': 28.75},
 {'date': '2020-06-02', 'value': 11.0},
 {'date': '2020-06-03', 'value': 7.5},
 {'date': '2020-06-04', 'value': 16.0},
 {'date': '2020-06-13', 'value': 12.0},
 {'date': '2020-06-19', 'value': 11.0},
 {'date': '2020-06-20', 'value': 22.666666666666668},
 {'date': '2020-06-27', 'value': 14.5},
 {'date': '2020-07-03', 'value': 20.0},
 {'date': '2020-07-04', 'value': 16.11111111111111},
 {'date': '2020-07-05', 'value': 19.5},
 {'date': '2020-07-08', 'value': 21.857142857142858},
 {'date': '2020-07-09', 'value': 26.916666666666668},
 {'date': '2020-07-10', 'value': 29.3},
 {'date': '2020-07-13', 'value': 18.0},
 {'date': '2020-07-15', 'value': 33.0},
 {'date': '2020-07-16', 'value': 14.333333333333334},
 {'date': '2020-07-17', 'value': 22.636363636363637},
 {'date': '2020-07-18', 'value': 22.142857142857142},
 {'date': '2020-07-21', 'value': 17.0},
 {'date': '2020-07-22', 'value': 20.0},
 {'date': '2020-07-25', 'value': 24.88888888888889},
 {'date': '2020-07-27', 'value': 48.0},
 {'date': '2020-07-29', 'value': 20.0},
 {'date': '2020-08-01', 'value': 42.0},
 {'date': '2020-08-07', 'value': 20.0},
 {'date': '2020-08-08', 'value': 25.272727272727273},
 {'date': '2020-08-09', 'value': 25.0},
 {'date': '2020-08-10', 'value': 34.75},
 {'date': '2020-08-11', 'value': 20.0},
 {'date': '2020-08-12', 'value': 30.75},
 {'date': '2020-08-15', 'value': 30.333333333333332},
 {'date': '2020-08-22', 'value': 13.285714285714286},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

spain_daily = (
    df_results.groupby("date")
              .agg(spain_pm10_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

spain_daily

           date  france_pm10_mean
0    2016-11-17         26.645652
1    2016-11-18         27.517426
2    2016-11-19         19.119545
3    2016-11-20         12.899220
4    2016-11-21         11.026883
...         ...               ...
3146 2026-02-24         26.243243
3147 2026-02-25         28.770270
3148 2026-02-26         25.185714
3149 2026-02-27         24.941176
3150 2026-02-28         20.333333

[3151 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
spain_daily[["date", "spain_pm10_mean"]].to_csv(
    "daily_avg_spain_PM10.csv",
    index=False
)

# PM2.5

### Get 200 stations located in France that measure PM2.5
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "ES",   # only consider stations located in spain
    "parameters_id": 2,   # PM2.5
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm25 = df_sorted

df_top_pm25

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
20,3226,Santa Perpètua de Mogoda,Santa Perpètua de Mogoda,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272698, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.526722, 'longitude': 2.1838}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.1838, 41.526722, 2.1838, 41.526722]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
21,3229,Sant Adrià de Besòs,Sant Adrià de Besòs,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272900, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.425594, 'longitude': 2.2221997...","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.2221997000000004, 41.425594, 2.222199700000...",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
22,3231,Sant Andreu de la Barca,Sant Andreu de la Barca,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272723, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.4508, 'longitude': 1.9748996}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.9748996, 41.4508, 1.9748996, 41.4508]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
24,3233,Vilanova i la Geltrú,Vilanova i la Geltrú,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 7571, 'name': 'co µg/m³', 'parameter':...","{'latitude': 41.218987, 'longitude': 1.7211995...","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.7211995000000004, 41.218987, 1.721199500000...",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
25,3235,Sant Celoni,Sant Celoni,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272718, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.6891, 'longitude': 2.495701}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.495701, 41.6891, 2.495701, 41.6891]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,3344587,LA LIEBRE 2,ALCALÁ DE GUADAIRA,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11857479, 'name': 'no2 µg/m³', 'parame...","{'latitude': 37.35943999996658, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-5.869109999912776, 37.35943999996658, -5.869...",None,2024-12-29 06:00:00+00:00,2026-02-09 15:00:00+00:00
419,3385215,OBSERVATORIO TEMISAS,AGÜIMES,Atlantic/Canary,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12131121, 'name': 'no2 µg/m³', 'parame...","{'latitude': 27.89980000019183, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-15.507930000379709, 27.89980000019183, -15.5...",None,2025-01-26 13:00:00+00:00,2026-02-09 15:00:00+00:00
420,3751838,MANZANARES,MANZANARES,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12527197, 'name': 'o3 µg/m³', 'paramet...","{'latitude': 38.995700000065106, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-3.358800000211578, 38.995700000065106, -3.35...",None,2025-03-15 19:00:00+00:00,2026-02-09 15:00:00+00:00
421,6162118,Ponts,Ponts,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14870404, 'name': 'o3 µg/m³', 'paramet...","{'latitude': 41.906708, 'longitude': 1.1930013}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.1930013, 41.906708, 1.1930013, 41.906708]",None,2025-12-12 03:00:00+00:00,2026-03-05 03:00:00+00:00
422,6187808,Barcelona,Barcelona,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 15062013, 'name': 'co µg/m³', 'paramet...","{'latitude': 41.41591, 'longitude': 2.1870944}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.1870944, 41.41591, 2.1870944, 41.41591]",None,2026-01-03 03:00:00+00:00,2026-03-05 03:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [13]:
rows = []

for _, station in df_top_pm25.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM25 behalten
        if sensor["parameter"]["id"] == 2:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm25_sensors = pd.DataFrame(rows)

df_pm25_sensors

     station_id              station_name  sensor_id sensor_name
0          3226  Santa Perpètua de Mogoda   12260261  pm25 µg/m³
1          3229       Sant Adrià de Besòs   15147153  pm25 µg/m³
2          3231   Sant Andreu de la Barca    4272885  pm25 µg/m³
3          3233      Vilanova i la Geltrú    4272945  pm25 µg/m³
4          3235               Sant Celoni   12260259  pm25 µg/m³
..          ...                       ...        ...         ...
418     3344587               LA LIEBRE 2   11857478  pm25 µg/m³
419     3385215      OBSERVATORIO TEMISAS   12131201  pm25 µg/m³
420     3751838                MANZANARES   12522429  pm25 µg/m³
421     6162118                     Ponts   15147147  pm25 µg/m³
422     6187808                 Barcelona   15062011  pm25 µg/m³

[423 rows x 4 columns]

In [14]:
sensor_ids = df_pm25_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

423

[12260261,
 15147153,
 4272885,
 4272945,
 12260259,
 15147152,
 4272960,
 15147155,
 4273113,
 15147148,
 4272896,
 15147149,
 15147151,
 15147150,
 12260256,
 12260260,
 4272983,
 12260262,
 12260258,
 4272663,
 15147156,
 7200,
 7775540,
 11857172,
 14095263,
 7035,
 7042,
 7074,
 7084,
 24768,
 1562291,
 29853,
 30191,
 25155,
 11857174,
 9585,
 1562292,
 7363,
 22310,
 9145,
 9584,
 25173,
 9566,
 9568,
 9582,
 25169,
 23333,
 25174,
 10236,
 12175421,
 10386,
 1703184,
 1961307,
 10442,
 10488,
 7622781,
 11069,
 10578,
 11980592,
 7120203,
 9368,
 6999,
 7622779,
 7622780,
 238756,
 7622777,
 24155,
 25176,
 25100,
 25166,
 29205,
 7194,
 10230,
 4272965,
 10378,
 10382,
 10423,
 1591273,
 12144658,
 10557,
 10571,
 25033,
 6197,
 10669,
 10658,
 10659,
 10694,
 10696,
 10712,
 21673,
 10261,
 10287,
 10319,
 10331,
 24614,
 10340,
 10253,
 25161,
 7367,
 25162,
 10257,
 10349,
 10361,
 10404,
 25064,
 10432,
 24975,
 7065,
 24424,
 10517,
 10344,
 7622775,
 7079,
 23713,
 23336,
 23331,
 23326,
 23692,
 23703,
 23697,
 1284583,
 23704,
 2533348,
 23683,
 23699,
 1896073,
 23708,
 2533347,
 9921,
 10675,
 1308680,
 1308673,
 1308681,
 1308670,
 1562410,
 1308672,
 1562411,
 1308690,
 1308684,
 1308689,
 1308669,
 1308682,
 1308691,
 1562303,
 1562311,
 1308675,
 1308671,
 1308688,
 1308686,
 1308674,
 7745110,
 1562296,
 1308679,
 1308685,
 1308692,
 1308678,
 12186132,
 1308687,
 10222,
 9555,
 21760,
 20702,
 1285419,
 21957,
 22626,
 22620,
 23797,
 23825,
 23830,
 23866,
 20703,
 22942,
 23345,
 23348,
 23353,
 25163,
 20453,
 23790,
 23786,
 23895,
 23151,
 22838,
 22840,
 22841,
 22842,
 23140,
 23144,
 23148,
 23159,
 23163,
 23170,
 23181,
 23180,
 23188,
 23197,
 23390,
 23399,
 23394,
 23814,
 23782,
 21124,
 22864,
 23847,
 23891,
 23873,
 23878,
 23852,
 11858111,
 22443,
 2062627,
 1289674,
 2011804,
 1289635,
 1289691,
 1798841,
 1289688,
 1289632,
 1289664,
 1289604,
 4272946,
 4273106,
 4475457,
 5078787,
 5078520,
 8613309,
 5078330,
 5078365,
 5078799,
 5078857,
 5078947,
 5078571,
 5078798,
 5079067,
 5078557,
 5078721,
 5078924,
 5079324,
 5079791,
 5079332,
 5078923,
 7632364,
 5078718,
 5078563,
 5078468,
 7004813,
 5078513,
 7772796,
 7775828,
 7774158,
 7775829,
 7773879,
 7775821,
 7774077,
 7774795,
 7775744,
 7773849,
 7774356,
 7775525,
 7772958,
 7773266,
 7775097,
 7772960,
 7775502,
 7775258,
 7774524,
 7775152,
 7772815,
 7773419,
 7773598,
 7773921,
 7772897,
 7775706,
 10793554,
 7772777,
 7774265,
 7773916,
 7775487,
 7774307,
 7774957,
 7774007,
 7775176,
 7773127,
 7774273,
 7775619,
 7774784,
 7774852,
 7774248,
 7775504,
 7775175,
 7775835,
 7772861,
 7774182,
 7775954,
 7773719,
 7775579,
 7773619,
 7775802,
 7775908,
 7773162,
 7774170,
 7775277,
 7773050,
 7775372,
 13372346,
 7774543,
 7775868,
 7774940,
 7773033,
 7772866,
 7780774,
 13375006,
 7773882,
 7774518,
 7775869,
 7773462,
 7775951,
 7773915,
 7775861,
 7775694,
 7773425,
 7772921,
 7775753,
 7775787,
 7775060,
 11886154,
 7775070,
 7774672,
 7773344,
 7772818,
 11857179,
 7775466,
 7773533,
 7774893,
 7775434,
 11857166,
 7774361,
 7775858,
 7774805,
 7775199,
 7775929,
 7853666,
 7772880,
 7776969,
 7776998,
 7776970,
 11857168,
 7777012,
 7777025,
 7776571,
 7777031,
 7776942,
 7777034,
 7776988,
 7776965,
 7776997,
 7776534,
 7777013,
 7776602,
 7776941,
 13372347,
 11886174,
 7776989,
 7775130,
 7776963,
 7776608,
 7776954,
 8622637,
 8613581,
 7798108,
 7794931,
 8622233,
 8622305,
 8613680,
 8622616,
 8613587,
 8622642,
 8622308,
 8613493,
 8613455,
 8622698,
 8622260,
 8613472,
 8622261,
 8622627,
 11857178,
 8613558,
 8613668,
 10793872,
 8613457,
 8622326,
 8622660,
 8613535,
 8613537,
 8623573,
 8613358,
 8613625,
 7795387,
 8613398,
 7795388,
 7795393,
 8624472,
 8613559,
 8613390,
 8622267,
 11857167,
 12906875,
 10455761,
 10455767,
 10455769,
 10455736,
 10455726,
 10456089,
 10455754,
 10455728,
 10455778,
 10455781,
 12260257,
 11857170,
 11857478,
 12131201,
 12522429,
 15147147,
 15062011]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 12260261: Seite 1, 369 Ergebnisse
Sensor 15147153: Seite 1, 47 Ergebnisse
Sensor 4272885: Seite 1, 444 Ergebnisse
Sensor 4272945: Seite 1, 901 Ergebnisse
Sensor 12260259: Seite 1, 365 Ergebnisse
Sensor 15147152: Seite 1, 47 Ergebnisse
Sensor 4272960: Seite 1, 1000 Ergebnisse
Sensor 4272960: Seite 2, 54 Ergebnisse
Sensor 15147155: Seite 1, 47 Ergebnisse
Sensor 4273113: Seite 1, 905 Ergebnisse
Sensor 15147148: Seite 1, 47 Ergebnisse
Sensor 4272896: Seite 1, 995 Ergebnisse
Sensor 15147149: Seite 1, 47 Ergebnisse
Sensor 15147151: Seite 1, 46 Ergebnisse
Sensor 15147150: Seite 1, 46 Ergebnisse
Sensor 12260256: Seite 1, 364 Ergebnisse
Sensor 12260260: Seite 1, 369 Ergebnisse
Sensor 4272983: Seite 1, 1000 Ergebnisse
Sensor 4272983: Seite 2, 54 Ergebnisse
Sensor 12260262: Seite 1, 352 Ergebnisse
Sensor 12260258: Seite 1, 362 Ergebnisse
Sensor 4272663: Seite 1, 926 Ergebnisse
Sensor 15147156: Seite 1, 47 Ergebnisse
Sensor 7200: Seite 1, 1000 Ergebnisse
Sensor 7200: Seite 2, 1000 Ergebnisse
Sensor 7200: Seite 3, 60 Ergebnisse
Sensor 7775540: Seite 1, 628 Ergebnisse
Sensor 11857172: Seite 1, 405 Ergebnisse
Sensor 14095263: Seite 1, 135 Ergebnisse
Sensor 7035: Seite 1, 1000 Ergebnisse
Sensor 7035: Seite 2, 860 Ergebnisse
Sensor 7042: Seite 1, 1000 Ergebnisse
Sensor 7042: Seite 2, 1000 Ergebnisse
Sensor 7042: Seite 3, 372 Ergebnisse
Sensor 7074: Seite 1, 1000 Ergebnisse
Sensor 7074: Seite 2, 1000 Ergebnisse
Sensor 7074: Seite 3, 577 Ergebnisse
Sensor 7084: Seite 1, 864 Ergebnisse
Sensor 24768: Seite 1, 1000 Ergebnisse
Sensor 24768: Seite 2, 1000 Ergebnisse
Sensor 24768: Seite 3, 327 Ergebnisse
Sensor 1562291: Seite 1, 1000 Ergebnisse
Sensor 1562291: Seite 2, 222 Ergebnisse
Sensor 29853: Seite 1, 1000 Ergebnisse
Sensor 29853: Seite 2, 1000 Ergebnisse
Sensor 29853: Seite 3, 661 Ergebnisse
Sensor 30191: Seite 1, 1000 Ergebnisse
Sensor 30191: Seite 2, 765 Ergebnisse
Sensor 25155: Seite 1, 1000 Ergebnisse
Sensor 25155: Seite 2, 955 Ergebnisse
Sensor 11857174: Seite 1, 407 Ergebnisse
Sensor 9585: Seite 1, 1000 Ergebnisse
Sensor 9585: Seite 2, 1000 Ergebnisse
Sensor 9585: Seite 3, 231 Ergebnisse
Sensor 1562292: Seite 1, 1000 Ergebnisse
Sensor 1562292: Seite 2, 311 Ergebnisse
Sensor 7363: Seite 1, 1000 Ergebnisse
Sensor 7363: Seite 2, 1000 Ergebnisse
Sensor 7363: Seite 3, 381 Ergebnisse
Sensor 22310: Seite 1, 811 Ergebnisse
Sensor 9145: Seite 1, 916 Ergebnisse
Sensor 9584: Seite 1, 1000 Ergebnisse
Sensor 9584: Seite 2, 1000 Ergebnisse
Sensor 9584: Seite 3, 59 Ergebnisse
Sensor 25173: Seite 1, 1000 Ergebnisse
Sensor 25173: Seite 2, 872 Ergebnisse
Sensor 9566: Seite 1, 1000 Ergebnisse
Sensor 9566: Seite 2, 1000 Ergebnisse
Sensor 9566: Seite 3, 32 Ergebnisse
Sensor 9568: Seite 1, 1000 Ergebnisse
Sensor 9568: Seite 2, 1000 Ergebnisse
Sensor 9568: Seite 3, 51 Ergebnisse
Sensor 9582: Seite 1, 1000 Ergebnisse
Sensor 9582: Seite 2, 1000 Ergebnisse
Sensor 9582: Seite 3, 183 Ergebnisse
Sensor 25169: Seite 1, 1000 Ergebnisse
Sensor 25169: Seite 2, 1000 Ergebnisse
Sensor 25169: Seite 3, 456 Ergebnisse
Sensor 23333: Seite 1, 1000 Ergebnisse
Sensor 23333: Seite 2, 444 Ergebnisse
Sensor 25174: Seite 1, 1000 Ergebnisse
Sensor 25174: Seite 2, 1000 Ergebnisse
Sensor 25174: Seite 3, 525 Ergebnisse
Sensor 10236: Seite 1, 1000 Ergebnisse
Sensor 10236: Seite 2, 1000 Ergebnisse
Sensor 10236: Seite 3, 506 Ergebnisse
Sensor 12175421: Seite 1, 362 Ergebnisse
Sensor 10386: Seite 1, 1000 Ergebnisse
Sensor 10386: Seite 2, 1000 Ergebnisse
Sensor 10386: Seite 3, 540 Ergebnisse
Sensor 1703184: Seite 1, 1000 Ergebnisse
Sensor 1703184: Seite 2, 321 Ergebnisse
Sensor 1961307: Seite 1, 1000 Ergebnisse
Sensor 1961307: Seite 2, 244 Ergebnisse
Sensor 10442: Seite 1, 1000 Ergebnisse
Sensor 10442: Seite 2, 1000 Ergebnisse
Sensor 10442: Seite 3, 456 Ergebnisse
Sensor 10488: Seite 1, 1000 Ergebnisse
Sensor 10488: Seite 2, 1000 Ergebnisse
Sensor 10488: Seite 3, 466 Ergebnisse
Sensor 7622781: Seite 1, 715 Ergebnisse
Sensor 11069: Seite 1, 1000 Ergebnisse
Sensor 11069: Seite 2, 1000 Ergebnisse
Sensor 11069: Seite 3, 575 Ergebnisse
Sensor 10578: Seite 1, 915 Ergebnisse
Sensor 11980592: Seite 1, 367 Ergebnisse
Sensor 7120203: Seite 1, 787 Ergebnisse
Sensor 9368: Seite 1, 101 Ergebnisse
Sensor 6999: Seite 1, 161 Ergebnisse
Sensor 7622779: Seite 1, 233 Ergebnisse
Sensor 7622780: Seite 1, 233 Ergebnisse
Sensor 238756: Seite 1, 827 Ergebnisse
Sensor 7622777: Seite 1, 233 Ergebnisse
Sensor 24155: Seite 1, 1000 Ergebnisse
Sensor 24155: Seite 2, 577 Ergebnisse
Sensor 25176: Seite 1, 1000 Ergebnisse
Sensor 25176: Seite 2, 241 Ergebnisse
Sensor 25100: Seite 1, 1000 Ergebnisse
Sensor 25100: Seite 2, 235 Ergebnisse
Sensor 25166: Seite 1, 1000 Ergebnisse
Sensor 25166: Seite 2, 260 Ergebnisse
Sensor 29205: Seite 1, 1000 Ergebnisse
Sensor 29205: Seite 2, 864 Ergebnisse
Sensor 7194: Seite 1, 1000 Ergebnisse
Sensor 7194: Seite 2, 72 Ergebnisse
Sensor 10230: Seite 1, 1000 Ergebnisse
Sensor 10230: Seite 2, 90 Ergebnisse
Sensor 4272965: Seite 1, 1000 Ergebnisse
Sensor 4272965: Seite 2, 10 Ergebnisse
Sensor 10378: Seite 1, 1000 Ergebnisse
Sensor 10378: Seite 2, 1000 Ergebnisse
Sensor 10378: Seite 3, 329 Ergebnisse
Sensor 10382: Seite 1, 1000 Ergebnisse
Sensor 10382: Seite 2, 1000 Ergebnisse
Sensor 10382: Seite 3, 480 Ergebnisse
Sensor 10423: Seite 1, 1000 Ergebnisse
Sensor 10423: Seite 2, 1000 Ergebnisse
Sensor 10423: Seite 3, 494 Ergebnisse
Sensor 1591273: Seite 1, 1000 Ergebnisse
Sensor 1591273: Seite 2, 257 Ergebnisse
Sensor 12144658: Seite 1, 349 Ergebnisse
Sensor 10557: Seite 1, 1000 Ergebnisse
Sensor 10557: Seite 2, 1000 Ergebnisse
Sensor 10557: Seite 3, 489 Ergebnisse
Sensor 10571: Seite 1, 1000 Ergebnisse
Sensor 10571: Seite 2, 1000 Ergebnisse
Sensor 25033: Seite 1, 1000 Ergebnisse
Sensor 25033: Seite 2, 1000 Ergebnisse
Sensor 25033: Seite 3, 249 Ergebnisse
Sensor 6197: Seite 1, 1000 Ergebnisse
Sensor 6197: Seite 2, 459 Ergebnisse
Sensor 10669: Seite 1, 1000 Ergebnisse
Sensor 10669: Seite 2, 668 Ergebnisse
Sensor 10658: Seite 1, 1000 Ergebnisse
Sensor 10658: Seite 2, 643 Ergebnisse
Sensor 10659: Seite 1, 1000 Ergebnisse
Sensor 10659: Seite 2, 173 Ergebnisse
Sensor 10694: Seite 1, 1000 Ergebnisse
Sensor 10694: Seite 2, 661 Ergebnisse
Sensor 10696: Seite 1, 1000 Ergebnisse
Sensor 10696: Seite 2, 666 Ergebnisse
Sensor 10712: Seite 1, 1000 Ergebnisse
Sensor 10712: Seite 2, 658 Ergebnisse
Sensor 21673: Seite 1, 1000 Ergebnisse
Sensor 21673: Seite 2, 701 Ergebnisse
Sensor 10261: Seite 1, 1000 Ergebnisse
Sensor 10261: Seite 2, 1000 Ergebnisse
Sensor 10261: Seite 3, 508 Ergebnisse
Sensor 10287: Seite 1, 1000 Ergebnisse
Sensor 10287: Seite 2, 1000 Ergebnisse
Sensor 10287: Seite 3, 577 Ergebnisse
Sensor 10319: Seite 1, 1000 Ergebnisse
Sensor 10319: Seite 2, 1000 Ergebnisse
Sensor 10319: Seite 3, 406 Ergebnisse
Sensor 10331: Seite 1, 1000 Ergebnisse
Sensor 10331: Seite 2, 1000 Ergebnisse
Sensor 10331: Seite 3, 475 Ergebnisse
Sensor 24614: Seite 1, 1000 Ergebnisse
Sensor 24614: Seite 2, 1000 Ergebnisse
Sensor 24614: Seite 3, 212 Ergebnisse
Sensor 10340: Seite 1, 1000 Ergebnisse
Sensor 10340: Seite 2, 1000 Ergebnisse
Sensor 10340: Seite 3, 845 Ergebnisse
Sensor 10253: Seite 1, 1000 Ergebnisse
Sensor 10253: Seite 2, 1000 Ergebnisse
Sensor 10253: Seite 3, 489 Ergebnisse
Sensor 25161: Seite 1, 1000 Ergebnisse
Sensor 25161: Seite 2, 639 Ergebnisse
Sensor 7367: Seite 1, 1000 Ergebnisse
Sensor 7367: Seite 2, 1000 Ergebnisse
Sensor 7367: Seite 3, 145 Ergebnisse
Sensor 25162: Seite 1, 1000 Ergebnisse
Sensor 25162: Seite 2, 630 Ergebnisse
Sensor 10257: Seite 1, 1000 Ergebnisse
Sensor 10257: Seite 2, 1000 Ergebnisse
Sensor 10257: Seite 3, 141 Ergebnisse
Sensor 10349: Seite 1, 1000 Ergebnisse
Sensor 10349: Seite 2, 1000 Ergebnisse
Sensor 10349: Seite 3, 148 Ergebnisse
Sensor 10361: Seite 1, 1000 Ergebnisse
Sensor 10361: Seite 2, 1000 Ergebnisse
Sensor 10361: Seite 3, 138 Ergebnisse
Sensor 10404: Seite 1, 1000 Ergebnisse
Sensor 10404: Seite 2, 1000 Ergebnisse
Sensor 10404: Seite 3, 136 Ergebnisse
Sensor 25064: Seite 1, 1000 Ergebnisse
Sensor 25064: Seite 2, 632 Ergebnisse
Sensor 10432: Seite 1, 1000 Ergebnisse
Sensor 10432: Seite 2, 1000 Ergebnisse
Sensor 10432: Seite 3, 125 Ergebnisse
Sensor 24975: Seite 1, 1000 Ergebnisse
Sensor 24975: Seite 2, 641 Ergebnisse
Sensor 7065: Seite 1, 77 Ergebnisse
Sensor 24424: Seite 1, 1000 Ergebnisse
Sensor 24424: Seite 2, 920 Ergebnisse
Sensor 10517: Seite 1, 1000 Ergebnisse
Sensor 10517: Seite 2, 1000 Ergebnisse
Sensor 10517: Seite 3, 518 Ergebnisse
Sensor 10344: Seite 1, 1000 Ergebnisse
Sensor 10344: Seite 2, 1000 Ergebnisse
Sensor 10344: Seite 3, 560 Ergebnisse
Sensor 7622775: Seite 1, 31 Ergebnisse
Sensor 7079: Seite 1, 1000 Ergebnisse
Sensor 7079: Seite 2, 1000 Ergebnisse
Sensor 7079: Seite 3, 555 Ergebnisse
Sensor 23713: Seite 1, 1000 Ergebnisse
Sensor 23713: Seite 2, 1000 Ergebnisse
Sensor 23713: Seite 3, 589 Ergebnisse
Sensor 23336: Seite 1, 1000 Ergebnisse
Sensor 23336: Seite 2, 34 Ergebnisse
Sensor 23331: Seite 1, 1000 Ergebnisse
Sensor 23331: Seite 2, 28 Ergebnisse
Sensor 23326: Seite 1, 1000 Ergebnisse
Sensor 23326: Seite 2, 36 Ergebnisse
Sensor 23692: Seite 1, 1000 Ergebnisse
Sensor 23692: Seite 2, 900 Ergebnisse
Sensor 23703: Seite 1, 1000 Ergebnisse
Sensor 23703: Seite 2, 786 Ergebnisse
Sensor 23697: Seite 1, 1000 Ergebnisse
Sensor 23697: Seite 2, 890 Ergebnisse
Sensor 1284583: Seite 1, 916 Ergebnisse
Sensor 23704: Seite 1, 1000 Ergebnisse
Sensor 23704: Seite 2, 885 Ergebnisse
Sensor 2533348: Seite 1, 335 Ergebnisse
Sensor 23683: Seite 1, 1000 Ergebnisse
Sensor 23683: Seite 2, 900 Ergebnisse
Sensor 23699: Seite 1, 1000 Ergebnisse
Sensor 23699: Seite 2, 819 Ergebnisse
Sensor 1896073: Seite 1, 556 Ergebnisse
Sensor 23708: Seite 1, 1000 Ergebnisse
Sensor 23708: Seite 2, 226 Ergebnisse
Sensor 2533347: Seite 1, 341 Ergebnisse
Sensor 9921: Seite 1, 1000 Ergebnisse
Sensor 9921: Seite 2, 217 Ergebnisse
Sensor 10675: Seite 1, 1000 Ergebnisse
Sensor 10675: Seite 2, 655 Ergebnisse
Sensor 1308680: Seite 1, 1000 Ergebnisse
Sensor 1308680: Seite 2, 430 Ergebnisse
Sensor 1308673: Seite 1, 1000 Ergebnisse
Sensor 1308673: Seite 2, 464 Ergebnisse
Sensor 1308681: Seite 1, 1000 Ergebnisse
Sensor 1308681: Seite 2, 276 Ergebnisse
Sensor 1308670: Seite 1, 1000 Ergebnisse
Sensor 1308670: Seite 2, 435 Ergebnisse
Sensor 1562410: Seite 1, 1000 Ergebnisse
Sensor 1562410: Seite 2, 175 Ergebnisse
Sensor 1308672: Seite 1, 1000 Ergebnisse
Sensor 1308672: Seite 2, 324 Ergebnisse
Sensor 1562411: Seite 1, 1000 Ergebnisse
Sensor 1562411: Seite 2, 155 Ergebnisse
Sensor 1308690: Seite 1, 270 Ergebnisse
Sensor 1308684: Seite 1, 485 Ergebnisse
Sensor 1308689: Seite 1, 1000 Ergebnisse
Sensor 1308689: Seite 2, 451 Ergebnisse
Sensor 1308669: Seite 1, 1000 Ergebnisse
Sensor 1308669: Seite 2, 435 Ergebnisse
Sensor 1308682: Seite 1, 1000 Ergebnisse
Sensor 1308682: Seite 2, 396 Ergebnisse
Sensor 1308691: Seite 1, 1000 Ergebnisse
Sensor 1308691: Seite 2, 441 Ergebnisse
Sensor 1562303: Seite 1, 1000 Ergebnisse
Sensor 1562303: Seite 2, 291 Ergebnisse
Sensor 1562311: Seite 1, 1000 Ergebnisse
Sensor 1562311: Seite 2, 160 Ergebnisse
Sensor 1308675: Seite 1, 1000 Ergebnisse
Sensor 1308675: Seite 2, 351 Ergebnisse
Sensor 1308671: Seite 1, 1000 Ergebnisse
Sensor 1308671: Seite 2, 366 Ergebnisse
Sensor 1308688: Seite 1, 1000 Ergebnisse
Sensor 1308688: Seite 2, 432 Ergebnisse
Sensor 1308686: Seite 1, 1000 Ergebnisse
Sensor 1308686: Seite 2, 443 Ergebnisse
Sensor 1308674: Seite 1, 1000 Ergebnisse
Sensor 1308674: Seite 2, 416 Ergebnisse
Sensor 7745110: Seite 1, 724 Ergebnisse
Sensor 1562296: Seite 1, 1000 Ergebnisse
Sensor 1562296: Seite 2, 177 Ergebnisse
Sensor 1308679: Seite 1, 1000 Ergebnisse
Sensor 1308679: Seite 2, 447 Ergebnisse
Sensor 1308685: Seite 1, 1000 Ergebnisse
Sensor 1308685: Seite 2, 190 Ergebnisse
Sensor 1308692: Seite 1, 1000 Ergebnisse
Sensor 1308692: Seite 2, 321 Ergebnisse
Sensor 1308678: Seite 1, 1000 Ergebnisse
Sensor 1308678: Seite 2, 354 Ergebnisse
Sensor 12186132: Seite 1, 296 Ergebnisse
Sensor 1308687: Seite 1, 703 Ergebnisse
Sensor 10222: Seite 1, 1000 Ergebnisse
Sensor 10222: Seite 2, 1000 Ergebnisse
Sensor 10222: Seite 3, 408 Ergebnisse
Sensor 9555: Seite 1, 1000 Ergebnisse
Sensor 9555: Seite 2, 1000 Ergebnisse
Sensor 9555: Seite 3, 46 Ergebnisse
Sensor 21760: Seite 1, 470 Ergebnisse
Sensor 20702: Seite 1, 1000 Ergebnisse
Sensor 20702: Seite 2, 810 Ergebnisse
Sensor 1285419: Seite 1, 1000 Ergebnisse
Sensor 1285419: Seite 2, 414 Ergebnisse
Sensor 21957: Seite 1, 1000 Ergebnisse
Sensor 21957: Seite 2, 503 Ergebnisse
Sensor 22626: Seite 1, 1000 Ergebnisse
Sensor 22626: Seite 2, 953 Ergebnisse
Sensor 22620: Seite 1, 1000 Ergebnisse
Sensor 22620: Seite 2, 813 Ergebnisse
Sensor 23797: Seite 1, 1000 Ergebnisse
Sensor 23797: Seite 2, 1000 Ergebnisse
Sensor 23797: Seite 3, 7 Ergebnisse
Sensor 23825: Seite 1, 1000 Ergebnisse
Sensor 23825: Seite 2, 1000 Ergebnisse
Sensor 23825: Seite 3, 54 Ergebnisse
Sensor 23830: Seite 1, 1000 Ergebnisse
Sensor 23830: Seite 2, 1000 Ergebnisse
Sensor 23830: Seite 3, 7 Ergebnisse
Sensor 23866: Seite 1, 1000 Ergebnisse
Sensor 23866: Seite 2, 399 Ergebnisse
Sensor 20703: Seite 1, 1000 Ergebnisse
Sensor 20703: Seite 2, 777 Ergebnisse
Sensor 22942: Seite 1, 1000 Ergebnisse
Sensor 22942: Seite 2, 642 Ergebnisse
Sensor 23345: Seite 1, 1000 Ergebnisse
Sensor 23345: Seite 2, 1000 Ergebnisse
Sensor 23345: Seite 3, 119 Ergebnisse
Sensor 23348: Seite 1, 1000 Ergebnisse
Sensor 23348: Seite 2, 1000 Ergebnisse
Sensor 23348: Seite 3, 138 Ergebnisse
Sensor 23353: Seite 1, 1000 Ergebnisse
Sensor 23353: Seite 2, 1000 Ergebnisse
Sensor 23353: Seite 3, 105 Ergebnisse
Sensor 25163: Seite 1, 1000 Ergebnisse
Sensor 25163: Seite 2, 253 Ergebnisse
Sensor 20453: Seite 1, 5 Ergebnisse
Sensor 23790: Seite 1, 1000 Ergebnisse
Sensor 23790: Seite 2, 768 Ergebnisse
Sensor 23786: Seite 1, 1000 Ergebnisse
Sensor 23786: Seite 2, 772 Ergebnisse
Sensor 23895: Seite 1, 1000 Ergebnisse
Sensor 23895: Seite 2, 756 Ergebnisse
Sensor 23151: Seite 1, 1000 Ergebnisse
Sensor 23151: Seite 2, 724 Ergebnisse
Sensor 22838: Seite 1, 484 Ergebnisse
Sensor 22840: Seite 1, 316 Ergebnisse
Sensor 22841: Seite 1, 487 Ergebnisse
Sensor 22842: Seite 1, 316 Ergebnisse
Sensor 23140: Seite 1, 1000 Ergebnisse
Sensor 23140: Seite 2, 743 Ergebnisse
Sensor 23144: Seite 1, 1000 Ergebnisse
Sensor 23144: Seite 2, 774 Ergebnisse
Sensor 23148: Seite 1, 1000 Ergebnisse
Sensor 23148: Seite 2, 741 Ergebnisse
Sensor 23159: Seite 1, 1000 Ergebnisse
Sensor 23159: Seite 2, 769 Ergebnisse
Sensor 23163: Seite 1, 1000 Ergebnisse
Sensor 23163: Seite 2, 761 Ergebnisse
Sensor 23170: Seite 1, 1000 Ergebnisse
Sensor 23170: Seite 2, 773 Ergebnisse
Sensor 23181: Seite 1, 1000 Ergebnisse
Sensor 23181: Seite 2, 755 Ergebnisse
Sensor 23180: Seite 1, 1000 Ergebnisse
Sensor 23180: Seite 2, 715 Ergebnisse
Sensor 23188: Seite 1, 1000 Ergebnisse
Sensor 23188: Seite 2, 765 Ergebnisse
Sensor 23197: Seite 1, 1000 Ergebnisse
Sensor 23197: Seite 2, 755 Ergebnisse
Sensor 23390: Seite 1, 1000 Ergebnisse
Sensor 23390: Seite 2, 757 Ergebnisse
Sensor 23399: Seite 1, 1000 Ergebnisse
Sensor 23399: Seite 2, 520 Ergebnisse
Sensor 23394: Seite 1, 1000 Ergebnisse
Sensor 23394: Seite 2, 751 Ergebnisse
Sensor 23814: Seite 1, 1000 Ergebnisse
Sensor 23814: Seite 2, 770 Ergebnisse
Sensor 23782: Seite 1, 481 Ergebnisse
Sensor 21124: Seite 1, 302 Ergebnisse
Sensor 22864: Seite 1, 343 Ergebnisse
Sensor 23878: Seite 1, 1000 Ergebnisse
Sensor 23878: Seite 2, 565 Ergebnisse
Sensor 11858111: Seite 1, 374 Ergebnisse
Sensor 22443: Seite 1, 1000 Ergebnisse
Sensor 22443: Seite 2, 205 Ergebnisse
Sensor 2062627: Seite 1, 1000 Ergebnisse
Sensor 2062627: Seite 2, 76 Ergebnisse
Sensor 1289674: Seite 1, 1000 Ergebnisse
Sensor 1289674: Seite 2, 332 Ergebnisse
Sensor 2011804: Seite 1, 957 Ergebnisse
Sensor 1289635: Seite 1, 741 Ergebnisse
Sensor 1289691: Seite 1, 542 Ergebnisse
Sensor 1798841: Seite 1, 488 Ergebnisse
Sensor 1289688: Seite 1, 746 Ergebnisse
Sensor 1289632: Seite 1, 630 Ergebnisse
Sensor 1289664: Seite 1, 143 Ergebnisse
Sensor 1289604: Seite 1, 101 Ergebnisse
Sensor 4272946: Seite 1, 64 Ergebnisse
Sensor 4273106: Seite 1, 998 Ergebnisse
Sensor 4475457: Seite 1, 1000 Ergebnisse
Sensor 4475457: Seite 2, 21 Ergebnisse
Sensor 5078787: Seite 1, 236 Ergebnisse
Sensor 5078520: Seite 1, 977 Ergebnisse
Sensor 8613309: Seite 1, 180 Ergebnisse
Sensor 5078330: Seite 1, 994 Ergebnisse
Sensor 5078365: Seite 1, 994 Ergebnisse
Sensor 5078799: Seite 1, 849 Ergebnisse
Sensor 5078857: Seite 1, 971 Ergebnisse
Sensor 5078947: Seite 1, 979 Ergebnisse
Sensor 5078571: Seite 1, 974 Ergebnisse
Sensor 5078798: Seite 1, 264 Ergebnisse
Sensor 5079067: Seite 1, 257 Ergebnisse
Sensor 5078557: Seite 1, 262 Ergebnisse
Sensor 5078721: Seite 1, 262 Ergebnisse
Sensor 5078924: Seite 1, 258 Ergebnisse
Sensor 5079324: Seite 1, 1000 Ergebnisse
Sensor 5079324: Seite 2, 12 Ergebnisse
Sensor 5079791: Seite 1, 1000 Ergebnisse
Sensor 5079791: Seite 2, 8 Ergebnisse
Sensor 5079332: Seite 1, 1000 Ergebnisse
Sensor 5079332: Seite 2, 9 Ergebnisse
Sensor 5078923: Seite 1, 971 Ergebnisse
Sensor 7632364: Seite 1, 718 Ergebnisse
Sensor 5078718: Seite 1, 915 Ergebnisse
Sensor 5078563: Seite 1, 923 Ergebnisse
Sensor 5078468: Seite 1, 910 Ergebnisse
Sensor 7004813: Seite 1, 332 Ergebnisse
Sensor 5078513: Seite 1, 949 Ergebnisse
Sensor 7772796: Seite 1, 661 Ergebnisse
Sensor 7775828: Seite 1, 655 Ergebnisse
Sensor 7774158: Seite 1, 680 Ergebnisse
Sensor 7775829: Seite 1, 722 Ergebnisse
Sensor 7773879: Seite 1, 643 Ergebnisse
Sensor 7775821: Seite 1, 624 Ergebnisse
Sensor 7774077: Seite 1, 647 Ergebnisse
Sensor 7774795: Seite 1, 658 Ergebnisse
Sensor 7775744: Seite 1, 639 Ergebnisse
Sensor 7773849: Seite 1, 712 Ergebnisse
Sensor 7774356: Seite 1, 646 Ergebnisse
Sensor 7775525: Seite 1, 689 Ergebnisse
Sensor 7772958: Seite 1, 717 Ergebnisse
Sensor 7773266: Seite 1, 722 Ergebnisse
Sensor 7775097: Seite 1, 690 Ergebnisse
Sensor 7772960: Seite 1, 679 Ergebnisse
Sensor 7775502: Seite 1, 698 Ergebnisse
Sensor 7775258: Seite 1, 663 Ergebnisse
Sensor 7774524: Seite 1, 670 Ergebnisse
Sensor 7775152: Seite 1, 714 Ergebnisse
Sensor 7772815: Seite 1, 726 Ergebnisse
Sensor 7773419: Seite 1, 723 Ergebnisse
Sensor 7773598: Seite 1, 729 Ergebnisse
Sensor 7773921: Seite 1, 680 Ergebnisse
Sensor 7772897: Seite 1, 716 Ergebnisse
Sensor 7775706: Seite 1, 694 Ergebnisse
Sensor 10793554: Seite 1, 493 Ergebnisse
Sensor 7772777: Seite 1, 727 Ergebnisse
Sensor 7774265: Seite 1, 686 Ergebnisse
Sensor 7773916: Seite 1, 704 Ergebnisse
Sensor 7775487: Seite 1, 712 Ergebnisse
Sensor 7774307: Seite 1, 714 Ergebnisse
Sensor 7774957: Seite 1, 703 Ergebnisse
Sensor 7774007: Seite 1, 703 Ergebnisse
Sensor 7775176: Seite 1, 669 Ergebnisse
Sensor 7773127: Seite 1, 695 Ergebnisse
Sensor 7774273: Seite 1, 689 Ergebnisse
Sensor 7775619: Seite 1, 681 Ergebnisse
Sensor 7774784: Seite 1, 700 Ergebnisse
Sensor 7774852: Seite 1, 653 Ergebnisse
Sensor 7774248: Seite 1, 698 Ergebnisse
Sensor 7775504: Seite 1, 656 Ergebnisse
Sensor 7775175: Seite 1, 692 Ergebnisse
Sensor 7775835: Seite 1, 698 Ergebnisse
Sensor 7772861: Seite 1, 622 Ergebnisse
Sensor 7774182: Seite 1, 680 Ergebnisse
Sensor 7775954: Seite 1, 643 Ergebnisse
Sensor 7773719: Seite 1, 700 Ergebnisse
Sensor 7775579: Seite 1, 695 Ergebnisse
Sensor 7773619: Seite 1, 726 Ergebnisse
Sensor 7775802: Seite 1, 726 Ergebnisse
Sensor 7775908: Seite 1, 721 Ergebnisse
Sensor 7773162: Seite 1, 729 Ergebnisse
Sensor 7774170: Seite 1, 718 Ergebnisse
Sensor 7775277: Seite 1, 729 Ergebnisse
Sensor 7773050: Seite 1, 711 Ergebnisse
Sensor 7775372: Seite 1, 729 Ergebnisse
Sensor 13372346: Seite 1, 236 Ergebnisse
Sensor 7774543: Seite 1, 730 Ergebnisse
Sensor 7775868: Seite 1, 727 Ergebnisse
Sensor 7774940: Seite 1, 721 Ergebnisse
Sensor 7773033: Seite 1, 726 Ergebnisse
Sensor 7772866: Seite 1, 729 Ergebnisse
Sensor 7780774: Seite 1, 714 Ergebnisse
Sensor 13375006: Seite 1, 234 Ergebnisse
Sensor 7773882: Seite 1, 719 Ergebnisse
Sensor 7774518: Seite 1, 726 Ergebnisse
Sensor 7775869: Seite 1, 726 Ergebnisse
Sensor 7773462: Seite 1, 697 Ergebnisse

[{'date': '2025-02-21', 'value': 21.0},
 {'date': '2025-02-22', 'value': 34.0},
 {'date': '2025-02-23', 'value': 10.0},
 {'date': '2025-02-24', 'value': 19.0},
 {'date': '2025-02-25', 'value': 14.0},
 {'date': '2025-02-26', 'value': 6.0},
 {'date': '2025-02-27', 'value': 15.0},
 {'date': '2025-02-28', 'value': 17.0},
 {'date': '2025-03-01', 'value': 15.0},
 {'date': '2025-03-02', 'value': 6.0},
 {'date': '2025-03-03', 'value': 10.0},
 {'date': '2025-03-04', 'value': 10.0},
 {'date': '2025-03-05', 'value': 10.0},
 {'date': '2025-03-06', 'value': 7.0},
 {'date': '2025-03-07', 'value': 14.0},
 {'date': '2025-03-08', 'value': 3.0},
 {'date': '2025-03-09', 'value': 6.0},
 {'date': '2025-03-10', 'value': 14.0},
 {'date': '2025-03-11', 'value': 14.0},
 {'date': '2025-03-12', 'value': 14.0},
 {'date': '2025-03-13', 'value': 17.0},
 {'date': '2025-03-14', 'value': 4.0},
 {'date': '2025-03-15', 'value': 12.0},
 {'date': '2025-03-16', 'value': 12.0},
 {'date': '2025-03-17', 'value': 7.0},
 {'date': '2025-03-18', 'value': 20.0},
 {'date': '2025-03-19', 'value': 10.0},
 {'date': '2025-03-20', 'value': 14.0},
 {'date': '2025-03-21', 'value': 15.0},
 {'date': '2025-03-22', 'value': 22.0},
 {'date': '2025-03-23', 'value': 11.0},
 {'date': '2025-03-24', 'value': 15.0},
 {'date': '2025-03-25', 'value': 12.0},
 {'date': '2025-03-26', 'value': 15.0},
 {'date': '2025-03-27', 'value': 13.0},
 {'date': '2025-03-28', 'value': 11.0},
 {'date': '2025-03-29', 'value': 19.0},
 {'date': '2025-03-30', 'value': 10.0},
 {'date': '2025-03-31', 'value': 11.0},
 {'date': '2025-04-01', 'value': 15.0},
 {'date': '2025-04-02', 'value': 6.0},
 {'date': '2025-04-03', 'value': 6.0},
 {'date': '2025-04-04', 'value': 4.0},
 {'date': '2025-04-05', 'value': 7.0},
 {'date': '2025-04-06', 'value': 15.0},
 {'date': '2025-04-07', 'value': 11.0},
 {'date': '2025-04-08', 'value': 17.0},
 {'date': '2025-04-09', 'value': 22.0},
 {'date': '2025-04-10', 'value': 15.0},
 {'date': '2025-04-11', 'value': 18.0},
 {'date': '2025-04-12', 'value': 12.0},
 {'date': '2025-04-13', 'value': 16.0},
 {'date': '2025-04-14', 'value': 8.0},
 {'date': '2025-04-15', 'value': 8.0},
 {'date': '2025-04-16', 'value': 5.0},
 {'date': '2025-04-17', 'value': 7.0},
 {'date': '2025-04-18', 'value': 6.0},
 {'date': '2025-04-19', 'value': 13.0},
 {'date': '2025-04-20', 'value': 4.0},
 {'date': '2025-04-21', 'value': 4.0},
 {'date': '2025-04-22', 'value': 8.0},
 {'date': '2025-04-23', 'value': 8.0},
 {'date': '2025-04-24', 'value': 10.0},
 {'date': '2025-04-25', 'value': 11.0},
 {'date': '2025-04-26', 'value': 15.0},
 {'date': '2025-04-27', 'value': 6.0},
 {'date': '2025-04-28', 'value': 6.0},
 {'date': '2025-04-29', 'value': 10.0},
 {'date': '2025-04-30', 'value': 10.0},
 {'date': '2025-05-01', 'value': 10.0},
 {'date': '2025-05-02', 'value': 8.0},
 {'date': '2025-05-03', 'value': 9.0},
 {'date': '2025-05-04', 'value': 37.0},
 {'date': '2025-05-05', 'value': 6.0},
 {'date': '2025-05-06', 'value': 6.0},
 {'date': '2025-05-07', 'value': 8.0},
 {'date': '2025-05-08', 'value': 12.0},
 {'date': '2025-05-09', 'value': 10.0},
 {'date': '2025-05-10', 'value': 5.0},
 {'date': '2025-05-11', 'value': 3.0},
 {'date': '2025-05-12', 'value': 7.0},
 {'date': '2025-05-13', 'value': 11.0},
 {'date': '2025-05-14', 'value': 11.0},
 {'date': '2025-05-15', 'value': 11.0},
 {'date': '2025-05-16', 'value': 8.0},
 {'date': '2025-05-17', 'value': 15.0},
 {'date': '2025-05-18', 'value': 12.0},
 {'date': '2025-05-19', 'value': 10.0},
 {'date': '2025-05-20', 'value': 4.0},
 {'date': '2025-05-21', 'value': 10.0},
 {'date': '2025-05-22', 'value': 13.0},
 {'date': '2025-05-23', 'value': 11.0},
 {'date': '2025-05-24', 'value': 10.0},
 {'date': '2025-05-25', 'value': 16.0},
 {'date': '2025-05-26', 'value': 10.0},
 {'date': '2025-05-27', 'value': 8.0},
 {'date': '2025-05-28', 'value': 13.0},
 {'date': '2025-05-29', 'value': 12.0},
 {'date': '2025-05-30', 'value': 13.0},
 {'date': '2025-05-31', 'value': 10.0},
 {'date': '2025-06-01', 'value': 13.0},
 {'date': '2025-06-02', 'value': 9.0},
 {'date': '2025-06-03', 'value': 7.0},
 {'date': '2025-06-04', 'value': 16.0},
 {'date': '2025-06-05', 'value': 12.0},
 {'date': '2025-06-06', 'value': 19.0},
 {'date': '2025-06-07', 'value': 12.0},
 {'date': '2025-06-08', 'value': 16.0},
 {'date': '2025-06-09', 'value': 10.0},
 {'date': '2025-06-10', 'value': 16.0},
 {'date': '2025-06-11', 'value': 20.0},
 {'date': '2025-06-12', 'value': 21.0},
 {'date': '2025-06-13', 'value': 27.0},
 {'date': '2025-06-14', 'value': 29.0},
 {'date': '2025-06-15', 'value': 22.0},
 {'date': '2025-06-16', 'value': 16.0},
 {'date': '2025-06-17', 'value': 16.0},
 {'date': '2025-06-18', 'value': 14.0},
 {'date': '2025-06-19', 'value': 17.0},
 {'date': '2025-06-20', 'value': 16.0},
 {'date': '2025-06-21', 'value': 15.0},
 {'date': '2025-06-22', 'value': 13.0},
 {'date': '2025-06-23', 'value': 9.0},
 {'date': '2025-06-24', 'value': 47.0},
 {'date': '2025-06-25', 'value': 14.0},
 {'date': '2025-06-26', 'value': 15.0},
 {'date': '2025-06-27', 'value': 15.0},
 {'date': '2025-06-28', 'value': 16.0},
 {'date': '2025-06-29', 'value': 16.0},
 {'date': '2025-06-30', 'value': 12.0},
 {'date': '2025-07-01', 'value': 18.0},
 {'date': '2025-07-02', 'value': 10.0},
 {'date': '2025-07-03', 'value': 18.0},
 {'date': '2025-07-04', 'value': 16.0},
 {'date': '2025-07-05', 'value': 11.0},
 {'date': '2025-07-06', 'value': 15.0},
 {'date': '2025-07-07', 'value': 8.0},
 {'date': '2025-07-08', 'value': 9.0},
 {'date': '2025-07-09', 'value': 10.0},
 {'date': '2025-07-10', 'value': 14.0},
 {'date': '2025-07-11', 'value': 15.0},
 {'date': '2025-07-12', 'value': 11.0},
 {'date': '2025-07-13', 'value': 7.0},
 {'date': '2025-07-14', 'value': 6.0},
 {'date': '2025-07-15', 'value': 9.0},
 {'date': '2025-07-16', 'value': 16.0},
 {'date': '2025-07-17', 'value': 15.0},
 {'date': '2025-07-18', 'value': 14.0},
 {'date': '2025-07-19', 'value': 14.0},
 {'date': '2025-07-20', 'value': 11.0},
 {'date': '2025-07-21', 'value': 13.0},
 {'date': '2025-07-22', 'value': 8.0},
 {'date': '2025-07-23', 'value': 11.0},
 {'date': '2025-07-24', 'value': 4.0},
 {'date': '2025-07-25', 'value': 8.0},
 {'date': '2025-07-26', 'value': 9.0},
 {'date': '2025-07-27', 'value': 12.0},
 {'date': '2025-07-28', 'value': 15.0},
 {'date': '2025-07-29', 'value': 12.0},
 {'date': '2025-07-30', 'value': 12.0},
 {'date': '2025-07-31', 'value': 10.0},
 {'date': '2025-08-01', 'value': 12.0},
 {'date': '2025-08-02', 'value': 11.0},
 {'date': '2025-08-03', 'value': 8.0},
 {'date': '2025-08-04', 'value': 14.0},
 {'date': '2025-08-05', 'value': 9.0},
 {'date': '2025-08-06', 'value': 11.0},
 {'date': '2025-08-07', 'value': 10.0},
 {'date': '2025-08-08', 'value': 15.0},
 {'date': '2025-08-09', 'value': 19.0},
 {'date': '2025-08-10', 'value': 18.0},
 {'date': '2025-08-11', 'value': 24.0},
 {'date': '2025-08-12', 'value': 21.0},
 {'date': '2025-08-13', 'value': 25.0},
 {'date': '2025-08-14', 'value': 20.0},
 {'date': '2025-08-15', 'value': 17.0},
 {'date': '2025-08-16', 'value': 18.0},
 {'date': '2025-08-17', 'value': 18.0},
 {'date': '2025-08-18', 'value': 25.0},
 {'date': '2025-08-19', 'value': 19.0},
 {'date': '2025-08-20', 'value': 17.0},
 {'date': '2025-08-21', 'value': 16.0},
 {'date': '2025-08-22', 'value': 9.0},
 {'date': '2025-08-23', 'value': 12.0},
 {'date': '2025-08-24', 'value': 11.0},
 {'date': '2025-08-25', 'value': 15.0},
 {'date': '2025-08-26', 'value': 19.0},
 {'date': '2025-08-27', 'value': 16.0},
 {'date': '2025-08-28', 'value': 17.0},
 {'date': '2025-08-29', 'value': 9.0},
 {'date': '2025-08-30', 'value': 5.0},
 {'date': '2025-08-31', 'value': 8.0},
 {'date': '2025-09-01', 'value': 8.0},
 {'date': '2025-09-02', 'value': 5.0},
 {'date': '2025-09-03', 'value': 5.0},
 {'date': '2025-09-04', 'value': 12.0},
 {'date': '2025-09-05', 'value': 4.0},
 {'date': '2025-09-06', 'value': 5.0},
 {'date': '2025-09-07', 'value': 8.0},
 {'date': '2025-09-08', 'value': 14.0},
 {'date': '2025-09-09', 'value': 10.0},
 {'date': '2025-09-10', 'value': 7.0},
 {'date': '2025-09-11', 'value': 7.0},
 {'date': '2025-09-12', 'value': 12.0},
 {'date': '2025-09-13', 'value': 7.0},
 {'date': '2025-09-14', 'value': 3.0},
 {'date': '2025-09-15', 'value': 16.0},
 {'date': '2025-09-16', 'value': 9.0},
 {'date': '2025-09-17', 'value': 7.0},
 {'date': '2025-09-18', 'value': 14.0},
 {'date': '2025-09-19', 'value': 18.0},
 {'date': '2025-09-20', 'value': 9.0},
 {'date': '2025-09-21', 'value': 11.0},
 {'date': '2025-09-22', 'value': 5.0},
 {'date': '2025-09-23', 'value': 5.0},
 {'date': '2025-09-24', 'value': 3.0},
 {'date': '2025-09-25', 'value': 6.0},
 {'date': '2025-09-26', 'value': 7.0},
 {'date': '2025-09-27', 'value': 6.0},
 {'date': '2025-09-30', 'value': 13.0},
 {'date': '2025-10-01', 'value': 13.0},
 {'date': '2025-10-02', 'value': 13.0},
 {'date': '2025-10-03', 'value': 14.0},
 {'date': '2025-10-04', 'value': 15.0},
 {'date': '2025-10-05', 'value': 6.0},
 {'date': '2025-10-06', 'value': 4.0},
 {'date': '2025-10-07', 'value': 7.0},
 {'date': '2025-10-08', 'value': 12.0},
 {'date': '2025-10-09', 'value': 17.0},
 {'date': '2025-10-10', 'value': 10.0},
 {'date': '2025-10-11', 'value': 7.0},
 {'date': '2025-10-12', 'value': 7.0},
 {'date': '2025-10-13', 'value': 9.0},
 {'date': '2025-10-14', 'value': 19.0},
 {'date': '2025-10-15', 'value': 13.0},
 {'date': '2025-10-16', 'value': 16.0},
 {'date': '2025-10-17', 'value': 19.0},
 {'date': '2025-10-18', 'value': 12.0},
 {'date': '2025-10-19', 'value': 14.0},
 {'date': '2025-10-20', 'value': 8.0},
 {'date': '2025-10-21', 'value': 8.0},
 {'date': '2025-10-22', 'value': 7.0},
 {'date': '2025-10-23', 'value': 3.0},
 {'date': '2025-10-24', 'value': 7.0},
 {'date': '2025-10-25', 'value': 10.0},
 {'date': '2025-10-26', 'value': 4.0},
 {'date': '2025-10-27', 'value': 6.0},
 {'date': '2025-10-28', 'value': 7.0},
 {'date': '2025-10-29', 'value': 10.0},
 {'date': '2025-10-30', 'value': 12.0},
 {'date': '2025-10-31', 'value': 9.0},
 {'date': '2025-11-01', 'value': 11.0},
 {'date': '2025-11-02', 'value': 13.0},
 {'date': '2025-11-03', 'value': 8.0},
 {'date': '2025-11-04', 'value': 12.0},
 {'date': '2025-11-05', 'value': 9.0},
 {'date': '2025-11-06', 'value': 15.0},
 {'date': '2025-11-07', 'value': 6.0},
 {'date': '2025-11-08', 'value': 12.0},
 {'date': '2025-11-09', 'value': 20.0},
 {'date': '2025-11-10', 'value': 16.0},
 {'date': '2025-11-11', 'value': 17.0},
 {'date': '2025-11-12', 'value': 16.0},
 {'date': '2025-11-13', 'value': 19.0},
 {'date': '2025-11-14', 'value': 17.0},
 {'date': '2025-11-15', 'value': 26.0},
 {'date': '2025-11-16', 'value': 13.0},
 {'date': '2025-11-17', 'value': 7.0},
 {'date': '2025-11-18', 'value': 14.0},
 {'date': '2025-11-19', 'value': 16.0},
 {'date': '2025-11-20', 'value': 17.0},
 {'date': '2025-11-21', 'value': 8.0},
 {'date': '2025-11-22', 'value': 2.0},
 {'date': '2025-11-23', 'value': 28.0},
 {'date': '2025-11-24', 'value': 4.0},
 {'date': '2025-11-25', 'value': 4.0},
 {'date': '2025-11-26', 'value': 7.0},
 {'date': '2025-11-27', 'value': 21.0},
 {'date': '2025-11-28', 'value': 21.0},
 {'date': '2025-11-29', 'value': 37.0},
 {'date': '2025-11-30', 'value': 20.0},
 {'date': '2025-12-01', 'value': 31.0},
 {'date': '2025-12-02', 'value': 20.0},
 {'date': '2025-12-03', 'value': 13.0},
 {'date': '2025-12-04', 'value': 16.0},
 {'date': '2025-12-05', 'value': 18.0},
 {'date': '2025-12-06', 'value': 25.0},
 {'date': '2025-12-07', 'value': 23.0},
 {'date': '2025-12-08', 'value': 18.0},
 {'date': '2025-12-09', 'value': 18.0},
 {'date': '2025-12-10', 'value': 18.0},
 {'date': '2025-12-11', 'value': 16.0},
 {'date': '2025-12-12', 'value': 31.0},
 {'date': '2025-12-14', 'value': 19.0},
 {'date': '2025-12-15', 'value': 9.0},
 {'date': '2025-12-16', 'value': 20.0},
 {'date': '2025-12-17', 'value': 18.0},
 {'date': '2025-12-18', 'value': 20.0},
 {'date': '2025-12-19', 'value': 30.0},
 {'date': '2025-12-20', 'value': 35.0},
 {'date': '2025-12-21', 'value': 18.0},
 {'date': '2025-12-22', 'value': 4.0},
 {'date': '2025-12-23', 'value': 5.0},
 {'date': '2025-12-24', 'value': 9.0},
 {'date': '2025-12-25', 'value': 2.0},
 {'date': '2025-12-26', 'value': 3.0},
 {'date': '2025-12-27', 'value': 4.0},
 {'date': '2025-12-28', 'value': 5.0},
 {'date': '2025-12-29', 'value': 6.0},
 {'date': '2025-12-30', 'value': 18.0},
 {'date': '2025-12-31', 'value': 18.0},
 {'date': '2026-01-01', 'value': 23.0},
 {'date': '2026-01-02', 'value': 18.0},
 {'date': '2026-01-03', 'value': 30.0},
 {'date': '2026-01-04', 'value': 4.0},
 {'date': '2026-01-05', 'value': 12.0},
 {'date': '2026-01-06', 'value': 9.0},
 {'date': '2026-01-07', 'value': 6.0},
 {'date': '2026-01-08', 'value': 18.0},
 {'date': '2026-01-09', 'value': 3.0},
 {'date': '2026-01-10', 'value': 1.0},
 {'date': '2026-01-11', 'value': 17.0},
 {'date': '2026-01-12', 'value': 18.0},
 {'date': '2026-01-13', 'value': 21.0},
 {'date': '2026-01-14', 'value': 22.0},
 {'date': '2026-01-15', 'value': 28.0},
 {'date': '2026-01-16', 'value': 18.0},
 {'date': '2026-01-17', 'value': 9.0},
 {'date': '2026-01-18', 'value': 5.0},
 {'date': '2026-01-19', 'value': 5.0},
 {'date': '2026-01-20', 'value': 1.0},
 {'date': '2026-01-21', 'value': 13.0},
 {'date': '2026-01-22', 'value': 12.0},
 {'date': '2026-01-23', 'value': 11.0},
 {'date': '2026-01-24', 'value': 12.0},
 {'date': '2026-01-25', 'value': 20.0},
 {'date': '2026-01-26', 'value': 1.0},
 {'date': '2026-01-27', 'value': 12.0},
 {'date': '2026-01-28', 'value': 2.0},
 {'date': '2026-01-29', 'value': 4.0},
 {'date': '2026-01-30', 'value': 10.0},
 {'date': '2026-01-31', 'value': 7.0},
 {'date': '2026-02-01', 'value': 4.0},
 {'date': '2026-02-02', 'value': 17.0},
 {'date': '2026-02-03', 'value': 2.0},
 {'date': '2026-02-04', 'value': 13.0},
 {'date': '2026-02-05', 'value': 14.0},
 {'date': '2026-02-06', 'value': 2.0},
 {'date': '2026-02-07', 'value': 2.0},
 {'date': '2026-02-08', 'value': 11.0},
 {'date': '2026-02-09', 'value': 8.0},
 {'date': '2026-02-10', 'value': 11.0},
 {'date': '2026-02-11', 'value': 2.0},
 {'date': '2026-02-12', 'value': 4.0},
 {'date': '2026-02-14', 'value': 2.0},
 {'date': '2026-02-15', 'value': 1.0},
 {'date': '2026-02-16', 'value': 13.0},
 {'date': '2026-02-17', 'value': 3.0},
 {'date': '2026-02-18', 'value': 14.0},
 {'date': '2026-02-19', 'value': 4.0},
 {'date': '2026-02-20', 'value': 4.0},
 {'date': '2026-02-21', 'value': 19.0},
 {'date': '2026-02-22', 'value': 19.0},
 {'date': '2026-02-23', 'value': 22.0},
 {'date': '2026-02-24', 'value': 29.0},
 {'date': '2026-02-25', 'value': 19.0},
 {'date': '2026-02-26', 'value': 23.0},
 {'date': '2026-02-27', 'value': 30.0},
 {'date': '2026-02-28', 'value': 28.0},
 {'date': '2026-01-13', 'value': 27.0},
 {'date': '2026-01-14', 'value': 30.0},
 {'date': '2026-01-15', 'value': 40.0},
 {'date': '2026-01-16', 'value': 19.0},
 {'date': '2026-01-17', 'value': 6.0},
 {'date': '2026-01-18', 'value': 2.0},
 {'date': '2026-01-19', 'value': 6.0},
 {'date': '2026-01-20', 'value': 1.0},
 {'date': '2026-01-21', 'value': 13.0},
 {'date': '2026-01-22', 'value': 11.0},
 {'date': '2026-01-23', 'value': 9.0},
 {'date': '2026-01-24', 'value': 13.0},
 {'date': '2026-01-25', 'value': 4.0},
 {'date': '2026-01-26', 'value': 1.0},
 {'date': '2026-01-27', 'value': 8.0},
 {'date': '2026-01-28', 'value': 1.0},
 {'date': '2026-01-29', 'value': 3.0},
 {'date': '2026-01-30', 'value': 5.0},
 {'date': '2026-01-31', 'value': 7.0},
 {'date': '2026-02-01', 'value': 2.0},
 {'date': '2026-02-02', 'value': 13.0},
 {'date': '2026-02-03', 'value': 2.0},
 {'date': '2026-02-04', 'value': 16.0},
 {'date': '2026-02-05', 'value': 5.0},
 {'date': '2026-02-06', 'value': 2.0},
 {'date': '2026-02-07', 'value': 1.0},
 {'date': '2026-02-08', 'value': 11.0},
 {'date': '2026-02-09', 'value': 9.0},
 {'date': '2026-02-10', 'value': 6.0},
 {'date': '2026-02-11', 'value': 3.0},
 {'date': '2026-02-12', 'value': 4.0},
 {'date': '2026-02-13', 'value': 5.0},
 {'date': '2026-02-14', 'value': 1.0},
 {'date': '2026-02-15', 'value': 1.0},
 {'date': '2026-02-16', 'value': 2.0},
 {'date': '2026-02-17', 'value': 1.0},
 {'date': '2026-02-18', 'value': 12.0},
 {'date': '2026-02-19', 'value': 3.0},
 {'date': '2026-02-20', 'value': 2.0},
 {'date': '2026-02-21', 'value': 13.0},
 {'date': '2026-02-22', 'value': 8.0},
 {'date': '2026-02-23', 'value': 17.0},
 {'date': '2026-02-24', 'value': 39.0},
 {'date': '2026-02-25', 'value': 20.0},
 {'date': '2026-02-26', 'value': 31.0},
 {'date': '2026-02-27', 'value': 30.0},
 {'date': '2026-02-28', 'value': 13.0},
 {'date': '2023-03-30', 'value': 10.0},
 {'date': '2023-03-31', 'value': 27.0},
 {'date': '2023-04-01', 'value': 21.0},
 {'date': '2023-04-02', 'value': 2.0},
 {'date': '2023-04-03', 'value': 4.0},
 {'date': '2023-04-04', 'value': 10.0},
 {'date': '2023-04-05', 'value': 9.0},
 {'date': '2023-04-06', 'value': 14.0},
 {'date': '2023-04-07', 'value': 8.0},
 {'date': '2023-04-08', 'value': 9.0},
 {'date': '2023-04-09', 'value': 7.0},
 {'date': '2023-04-10', 'value': 10.0},
 {'date': '2023-04-11', 'value': 12.0},
 {'date': '2023-04-12', 'value': 15.0},
 {'date': '2023-04-13', 'value': 6.5},
 {'date': '2023-04-15', 'value': 11.0},
 {'date': '2023-04-16', 'value': 9.0},
 {'date': '2023-04-17', 'value': 6.0},
 {'date': '2023-04-19', 'value': 10.0},
 {'date': '2023-04-20', 'value': 8.0},
 {'date': '2023-04-23', 'value': 20.0},
 {'date': '2023-04-24', 'value': 7.0},
 {'date': '2023-04-26', 'value': 14.0},
 {'date': '2023-04-27', 'value': 7.0},
 {'date': '2023-04-28', 'value': 11.0},
 {'date': '2023-04-29', 'value': 7.0},
 {'date': '2023-04-30', 'value': 7.0},
 {'date': '2023-05-01', 'value': 11.0},
 {'date': '2023-05-02', 'value': 9.0},
 {'date': '2023-05-03', 'value': 8.0},
 {'date': '2023-05-04', 'value': 10.0},
 {'date': '2023-05-05', 'value': 10.0},
 {'date': '2023-05-06', 'value': 15.0},
 {'date': '2023-05-07', 'value': 10.0},
 {'date': '2023-05-08', 'value': 7.0},
 {'date': '2023-05-09', 'value': 11.0},
 {'date': '2023-05-10', 'value': 10.0},
 {'date': '2023-05-11', 'value': 7.0},
 {'date': '2023-05-12', 'value': 4.0},
 {'date': '2023-05-13', 'value': 8.0},
 {'date': '2023-05-14', 'value': 8.0},
 {'date': '2023-05-15', 'value': 7.0},
 {'date': '2023-05-16', 'value': 22.0},
 {'date': '2023-05-17', 'value': 16.0},
 {'date': '2023-05-18', 'value': 8.0},
 {'date': '2023-05-19', 'value': 10.0},
 {'date': '2023-05-20', 'value': 5.0},
 {'date': '2023-05-21', 'value': 10.0},
 {'date': '2023-05-22', 'value': 14.0},
 {'date': '2023-05-24', 'value': 23.0},
 {'date': '2023-05-25', 'value': 14.0},
 {'date': '2023-05-26', 'value': 13.0},
 {'date': '2023-05-27', 'value': 18.0},
 {'date': '2023-05-28', 'value': 17.0},
 {'date': '2023-05-29', 'value': 10.0},
 {'date': '2023-05-30', 'value': 17.0},
 {'date': '2023-05-31', 'value': 15.0},
 {'date': '2023-06-01', 'value': 13.0},
 {'date': '2023-06-02', 'value': 20.0},
 {'date': '2023-06-03', 'value': 18.0},
 {'date': '2023-06-04', 'value': 18.0},
 {'date': '2023-06-05', 'value': 12.0},
 {'date': '2023-06-06', 'value': 9.0},
 {'date': '2023-06-07', 'value': 8.0},
 {'date': '2023-06-08', 'value': 8.0},
 {'date': '2023-06-22', 'value': 23.0},
 {'date': '2023-06-23', 'value': 14.0},
 {'date': '2023-06-24', 'value': 19.0},
 {'date': '2023-06-25', 'value': 9.0},
 {'date': '2023-06-26', 'value': 10.0},
 {'date': '2023-06-27', 'value': 12.0},
 {'date': '2023-06-28', 'value': 11.0},
 {'date': '2023-06-29', 'value': 20.0},
 {'date': '2023-06-30', 'value': 8.0},
 {'date': '2023-07-01', 'value': 10.0},
 {'date': '2023-07-02', 'value': 9.0},
 {'date': '2023-07-03', 'value': 8.0},
 {'date': '2023-07-04', 'value': 13.0},
 {'date': '2023-07-05', 'value': 16.0},
 {'date': '2023-07-06', 'value': 10.0},
 {'date': '2023-07-07', 'value': 17.0},
 {'date': '2023-07-08', 'value': 18.0},
 {'date': '2023-07-09', 'value': 16.0},
 {'date': '2023-07-10', 'value': 29.0},
 {'date': '2023-07-11', 'value': 38.0},
 {'date': '2023-07-12', 'value': 79.0},
 {'date': '2023-07-13', 'value': 18.0},
 {'date': '2023-07-14', 'value': 14.0},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

spain_daily = (
    df_results.groupby("date")
              .agg(spain_pm25_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

spain_daily

           date  france_pm25_mean
0    2016-11-21          5.460331
1    2016-11-22          6.112696
2    2016-11-23          6.210247
3    2016-11-24         13.384615
4    2016-11-25          7.013935
...         ...               ...
3117 2026-02-24         19.000000
3118 2026-02-25         20.866667
3119 2026-02-26         21.310345
3120 2026-02-27         22.777778
3121 2026-02-28         16.982759

[3122 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
spain_daily[["date", "spain_pm25_mean"]].to_csv(
    "daily_avg_spain_PM25.csv",
    index=False
)

# NO2

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "ES",   # only consider stations located in spain
    "parameters_id": 5,   # NO2
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_no2 = df_sorted.head(300)

df_top_no2

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
38,3221,Constantí,Constantí,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272730, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.15493, 'longitude': 1.2177014}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.2177014, 41.15493, 1.2177014, 41.15493]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
43,3226,Santa Perpètua de Mogoda,Santa Perpètua de Mogoda,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272698, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.526722, 'longitude': 2.1838}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.1838, 41.526722, 2.1838, 41.526722]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
44,3227,Santa Pau,Santa Pau,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272712, 'name': 'no µg/m³', 'paramete...","{'latitude': 42.14328, 'longitude': 2.5102024}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.5102024, 42.14328, 2.5102024, 42.14328]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
45,3229,Sant Adrià de Besòs,Sant Adrià de Besòs,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272900, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.425594, 'longitude': 2.2221997...","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[2.2221997000000004, 41.425594, 2.222199700000...",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
47,3231,Sant Andreu de la Barca,Sant Andreu de la Barca,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 16, 'name': 'Catalonia Medi Ambient I S...",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4272723, 'name': 'no µg/m³', 'paramete...","{'latitude': 41.4508, 'longitude': 1.9748996}","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[1.9748996, 41.4508, 1.9748996, 41.4508]",None,2016-11-17 23:00:00+00:00,2026-03-05 03:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,3382,BAILÉN,BAILÉN,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 7428, 'name': 'co µg/m³', 'parameter':...","{'latitude': 38.09292999978484, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-3.783919999977688, 38.09292999978484, -3.783...",None,2017-01-29 18:00:00+00:00,2026-02-09 15:00:00+00:00
171,3383,ALGECIRAS EPS,ALGECIRAS,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 7429, 'name': 'co µg/m³', 'parameter':...","{'latitude': 36.13623000002991, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-5.453430000208752, 36.13623000002991, -5.453...",None,2017-01-29 18:00:00+00:00,2026-02-09 15:00:00+00:00
172,3384,EL EJIDO,EJIDO (EL),Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 7430, 'name': 'co µg/m³', 'parameter':...","{'latitude': 36.76971999972862, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-2.8109699996840787, 36.76971999972862, -2.81...",None,2017-01-29 18:00:00+00:00,2026-02-09 15:00:00+00:00
174,3386,MOTRIL,MOTRIL,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 7432, 'name': 'co µg/m³', 'parameter':...","{'latitude': 36.74312000005969, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-3.517300000294817, 36.74312000005969, -3.517...",None,2017-01-29 18:00:00+00:00,2026-02-09 15:00:00+00:00
175,3387,POZO DULCE,HUELVA,Europe/Madrid,"{'id': 67, 'code': 'ES', 'name': 'Spain'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 7433, 'name': 'co µg/m³', 'parameter':...","{'latitude': 37.25335999969387, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-6.935140000179095, 37.25335999969387, -6.935...",None,2017-01-29 18:00:00+00:00,2026-02-09 15:00:00+00:00

In [20]:
rows = []

for _, station in df_top_no2.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur NO2 behalten
        if sensor["parameter"]["id"] == 5:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_no2_sensors = pd.DataFrame(rows)

df_no2_sensors

     station_id              station_name  sensor_id sensor_name
0          3221                 Constantí       6977   no2 µg/m³
1          3226  Santa Perpètua de Mogoda       6991   no2 µg/m³
2          3227                 Santa Pau    4273060   no2 µg/m³
3          3229       Sant Adrià de Besòs       6994   no2 µg/m³
4          3231   Sant Andreu de la Barca       6996   no2 µg/m³
..          ...                       ...        ...         ...
295        3382                    BAILÉN      10181   no2 µg/m³
296        3383             ALGECIRAS EPS      10061   no2 µg/m³
297        3384                  EL EJIDO      10080   no2 µg/m³
298        3386                    MOTRIL      10195   no2 µg/m³
299        3387                POZO DULCE      10123   no2 µg/m³

[300 rows x 4 columns]

In [21]:
sensor_ids = df_no2_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

300

[6977,
 6991,
 4273060,
 6994,
 6996,
 7011,
 7003,
 7005,
 7008,
 7016,
 7022,
 7111,
 7126,
 7127,
 7174,
 7220,
 7226,
 7228,
 7232,
 7236,
 7266,
 7270,
 7271,
 7277,
 7280,
 7301,
 7304,
 7310,
 7313,
 25171,
 7336,
 7354,
 7359,
 7108,
 7210,
 7198,
 6202,
 7134,
 7341,
 7039,
 6341,
 6986,
 6989,
 7010,
 7711741,
 7038,
 7047,
 7052,
 7077,
 7087,
 7093,
 7102,
 7109,
 7117,
 7120,
 7121,
 7153,
 7137,
 7159,
 7179,
 7182,
 7202,
 7205,
 7213,
 7248,
 7258,
 7289,
 7290,
 7293,
 7297,
 7303,
 7318,
 7381,
 7337,
 7366,
 7372,
 7373,
 8653,
 9144,
 9638,
 9624,
 9654,
 9635,
 9674,
 9744,
 9714,
 9719,
 9684,
 9619,
 9676,
 10233,
 10267,
 10306,
 10324,
 10371,
 10383,
 10396,
 10425,
 22297,
 10445,
 10482,
 10491,
 10500,
 10511,
 10539,
 10544,
 10581,
 10646,
 6204,
 7025,
 7178,
 9640,
 7171,
 9750,
 9370,
 6211,
 9372,
 9375,
 9366,
 1316153,
 7214,
 7002,
 10263,
 10628,
 10238,
 10360,
 10607,
 10644,
 7217,
 7050,
 7197,
 8672,
 9111,
 9522,
 9602,
 9930,
 10466,
 10599,
 10293,
 10417,
 10496,
 10519,
 10632,
 6984,
 7097,
 9906,
 25102,
 7211,
 7255,
 29202,
 7284,
 6975,
 7100,
 7192,
 10369,
 10228,
 10283,
 10454,
 9620,
 7028,
 10555,
 7168,
 6997,
 7221,
 7186,
 6982,
 7181,
 10277,
 10299,
 10311,
 10339,
 10375,
 10380,
 10421,
 10430,
 10469,
 10508,
 10530,
 10535,
 10547,
 10550,
 10559,
 10568,
 10592,
 10602,
 10653,
 9573,
 10365,
 6213,
 7058,
 10674,
 10692,
 10697,
 10672,
 10683,
 10700,
 9546,
 9551,
 9574,
 9592,
 9607,
 9914,
 9910,
 9565,
 30300,
 7138,
 7141,
 7145,
 7230,
 9931,
 10259,
 10290,
 10317,
 10328,
 10335,
 10342,
 10357,
 10393,
 10410,
 10439,
 10585,
 10250,
 7101,
 7167,
 7325,
 7369,
 7380,
 10242,
 10255,
 10270,
 10273,
 10352,
 10363,
 10402,
 10407,
 10413,
 10435,
 10475,
 10533,
 10614,
 10638,
 10649,
 7068,
 7180,
 6974,
 8701,
 10224,
 10246,
 10321,
 10514,
 10523,
 10575,
 5557,
 5562,
 10347,
 10463,
 10313,
 10400,
 7082,
 5702,
 5715,
 5550,
 5551,
 23696,
 6786,
 6889,
 10619,
 23688,
 5690,
 5693,
 5703,
 5697,
 5698,
 5724,
 5709,
 29372,
 5717,
 5721,
 9919,
 5692,
 5706,
 10680,
 7262,
 7014,
 6188,
 9695,
 10389,
 10280,
 7345,
 7099,
 7285,
 10027,
 10033,
 9946,
 10211,
 10181,
 10061,
 10080,
 10195,
 10123]

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 6977: Seite 1, 1000 Ergebnisse
Sensor 6977: Seite 2, 1000 Ergebnisse
Sensor 6977: Seite 3, 358 Ergebnisse
Sensor 6991: Seite 1, 1000 Ergebnisse
Sensor 6991: Seite 2, 1000 Ergebnisse
Sensor 6991: Seite 3, 346 Ergebnisse
Sensor 4273060: Seite 1, 1000 Ergebnisse
Sensor 4273060: Seite 2, 20 Ergebnisse
Sensor 6994: Seite 1, 1000 Ergebnisse
Sensor 6994: Seite 2, 1000 Ergebnisse
Sensor 6994: Seite 3, 355 Ergebnisse
Sensor 6996: Seite 1, 1000 Ergebnisse
Sensor 6996: Seite 2, 1000 Ergebnisse
Sensor 6996: Seite 3, 346 Ergebnisse
Sensor 7011: Seite 1, 1000 Ergebnisse
Sensor 7011: Seite 2, 1000 Ergebnisse
Sensor 7011: Seite 3, 357 Ergebnisse
Sensor 7003: Seite 1, 1000 Ergebnisse
Sensor 7003: Seite 2, 1000 Ergebnisse
Sensor 7003: Seite 3, 344 Ergebnisse
Sensor 7005: Seite 1, 1000 Ergebnisse
Sensor 7005: Seite 2, 1000 Ergebnisse
Sensor 7005: Seite 3, 347 Ergebnisse
Sensor 7008: Seite 1, 1000 Ergebnisse
Sensor 7008: Seite 2, 1000 Ergebnisse
Sensor 7008: Seite 3, 342 Ergebnisse
Sensor 7016: Seite 1, 1000 Ergebnisse
Sensor 7016: Seite 2, 1000 Ergebnisse
Sensor 7016: Seite 3, 356 Ergebnisse
Sensor 7022: Seite 1, 1000 Ergebnisse
Sensor 7022: Seite 2, 1000 Ergebnisse
Sensor 7022: Seite 3, 356 Ergebnisse
Sensor 7111: Seite 1, 1000 Ergebnisse
Sensor 7111: Seite 2, 1000 Ergebnisse
Sensor 7111: Seite 3, 347 Ergebnisse
Sensor 7126: Seite 1, 1000 Ergebnisse
Sensor 7126: Seite 2, 1000 Ergebnisse
Sensor 7126: Seite 3, 331 Ergebnisse
Sensor 7127: Seite 1, 1000 Ergebnisse
Sensor 7127: Seite 2, 1000 Ergebnisse
Sensor 7127: Seite 3, 236 Ergebnisse
Sensor 7174: Seite 1, 1000 Ergebnisse
Sensor 7174: Seite 2, 1000 Ergebnisse
Sensor 7174: Seite 3, 221 Ergebnisse
Sensor 7220: Seite 1, 1000 Ergebnisse
Sensor 7220: Seite 2, 1000 Ergebnisse
Sensor 7220: Seite 3, 365 Ergebnisse
Sensor 7226: Seite 1, 1000 Ergebnisse
Sensor 7226: Seite 2, 1000 Ergebnisse
Sensor 7226: Seite 3, 348 Ergebnisse
Sensor 7228: Seite 1, 1000 Ergebnisse
Sensor 7228: Seite 2, 1000 Ergebnisse
Sensor 7228: Seite 3, 357 Ergebnisse
Sensor 7232: Seite 1, 1000 Ergebnisse
Sensor 7232: Seite 2, 1000 Ergebnisse
Sensor 7232: Seite 3, 334 Ergebnisse
Sensor 7236: Seite 1, 1000 Ergebnisse
Sensor 7236: Seite 2, 1000 Ergebnisse
Sensor 7236: Seite 3, 341 Ergebnisse
Sensor 7266: Seite 1, 1000 Ergebnisse
Sensor 7266: Seite 2, 1000 Ergebnisse
Sensor 7266: Seite 3, 344 Ergebnisse
Sensor 7270: Seite 1, 1000 Ergebnisse
Sensor 7270: Seite 2, 1000 Ergebnisse
Sensor 7270: Seite 3, 340 Ergebnisse
Sensor 7271: Seite 1, 1000 Ergebnisse
Sensor 7271: Seite 2, 1000 Ergebnisse
Sensor 7271: Seite 3, 342 Ergebnisse
Sensor 7277: Seite 1, 1000 Ergebnisse
Sensor 7277: Seite 2, 1000 Ergebnisse
Sensor 7277: Seite 3, 362 Ergebnisse
Sensor 7280: Seite 1, 1000 Ergebnisse
Sensor 7280: Seite 2, 1000 Ergebnisse
Sensor 7280: Seite 3, 353 Ergebnisse
Sensor 7301: Seite 1, 1000 Ergebnisse
Sensor 7301: Seite 2, 1000 Ergebnisse
Sensor 7301: Seite 3, 358 Ergebnisse
Sensor 7304: Seite 1, 1000 Ergebnisse
Sensor 7304: Seite 2, 1000 Ergebnisse
Sensor 7304: Seite 3, 341 Ergebnisse
Sensor 7310: Seite 1, 1000 Ergebnisse
Sensor 7310: Seite 2, 1000 Ergebnisse
Sensor 7310: Seite 3, 332 Ergebnisse
Sensor 7313: Seite 1, 1000 Ergebnisse
Sensor 7313: Seite 2, 1000 Ergebnisse
Sensor 7313: Seite 3, 332 Ergebnisse
Sensor 25171: Seite 1, 1000 Ergebnisse
Sensor 25171: Seite 2, 746 Ergebnisse
Sensor 7336: Seite 1, 1000 Ergebnisse
Sensor 7336: Seite 2, 1000 Ergebnisse
Sensor 7336: Seite 3, 330 Ergebnisse
Sensor 7354: Seite 1, 1000 Ergebnisse
Sensor 7354: Seite 2, 1000 Ergebnisse
Sensor 7354: Seite 3, 347 Ergebnisse
Sensor 7359: Seite 1, 1000 Ergebnisse
Sensor 7359: Seite 2, 1000 Ergebnisse
Sensor 7359: Seite 3, 348 Ergebnisse
Sensor 7108: Seite 1, 1000 Ergebnisse
Sensor 7108: Seite 2, 1000 Ergebnisse
Sensor 7108: Seite 3, 107 Ergebnisse
Sensor 7210: Seite 1, 1000 Ergebnisse
Sensor 7210: Seite 2, 957 Ergebnisse
Sensor 7198: Seite 1, 1000 Ergebnisse
Sensor 7198: Seite 2, 1000 Ergebnisse
Sensor 7198: Seite 3, 829 Ergebnisse
Sensor 6202: Seite 1, 870 Ergebnisse
Sensor 7134: Seite 1, 1000 Ergebnisse
Sensor 7134: Seite 2, 1000 Ergebnisse
Sensor 7134: Seite 3, 305 Ergebnisse
Sensor 7341: Seite 1, 1000 Ergebnisse
Sensor 7341: Seite 2, 1000 Ergebnisse
Sensor 7341: Seite 3, 347 Ergebnisse
Sensor 7039: Seite 1, 1000 Ergebnisse
Sensor 7039: Seite 2, 1000 Ergebnisse
Sensor 7039: Seite 3, 315 Ergebnisse
Sensor 6341: Seite 1, 1000 Ergebnisse
Sensor 6341: Seite 2, 1000 Ergebnisse
Sensor 6341: Seite 3, 316 Ergebnisse
Sensor 6986: Seite 1, 1000 Ergebnisse
Sensor 6986: Seite 2, 1000 Ergebnisse
Sensor 6986: Seite 3, 355 Ergebnisse
Sensor 6989: Seite 1, 1000 Ergebnisse
Sensor 6989: Seite 2, 1000 Ergebnisse
Sensor 6989: Seite 3, 884 Ergebnisse
Sensor 7010: Seite 1, 1000 Ergebnisse
Sensor 7010: Seite 2, 1000 Ergebnisse
Sensor 7010: Seite 3, 916 Ergebnisse
Sensor 7711741: Seite 1, 741 Ergebnisse
Sensor 7038: Seite 1, 1000 Ergebnisse
Sensor 7038: Seite 2, 925 Ergebnisse
Sensor 7047: Seite 1, 1000 Ergebnisse
Sensor 7047: Seite 2, 1000 Ergebnisse
Sensor 7047: Seite 3, 356 Ergebnisse
Sensor 7052: Seite 1, 1000 Ergebnisse
Sensor 7052: Seite 2, 1000 Ergebnisse
Sensor 7052: Seite 3, 812 Ergebnisse
Sensor 7077: Seite 1, 1000 Ergebnisse
Sensor 7077: Seite 2, 1000 Ergebnisse
Sensor 7077: Seite 3, 584 Ergebnisse
Sensor 7087: Seite 1, 868 Ergebnisse
Sensor 7093: Seite 1, 1000 Ergebnisse
Sensor 7093: Seite 2, 1000 Ergebnisse
Sensor 7093: Seite 3, 539 Ergebnisse
Sensor 7102: Seite 1, 1000 Ergebnisse
Sensor 7102: Seite 2, 1000 Ergebnisse
Sensor 7102: Seite 3, 375 Ergebnisse
Sensor 7109: Seite 1, 1000 Ergebnisse
Sensor 7109: Seite 2, 1000 Ergebnisse
Sensor 7109: Seite 3, 325 Ergebnisse
Sensor 7117: Seite 1, 1000 Ergebnisse
Sensor 7117: Seite 2, 1000 Ergebnisse
Sensor 7117: Seite 3, 584 Ergebnisse
Sensor 7120: Seite 1, 1000 Ergebnisse
Sensor 7120: Seite 2, 1000 Ergebnisse
Sensor 7120: Seite 3, 328 Ergebnisse
Sensor 7121: Seite 1, 1000 Ergebnisse
Sensor 7121: Seite 2, 1000 Ergebnisse
Sensor 7121: Seite 3, 467 Ergebnisse
Sensor 7153: Seite 1, 1000 Ergebnisse
Sensor 7153: Seite 2, 1000 Ergebnisse
Sensor 7153: Seite 3, 298 Ergebnisse
Sensor 7137: Seite 1, 1000 Ergebnisse
Sensor 7137: Seite 2, 1000 Ergebnisse
Sensor 7137: Seite 3, 323 Ergebnisse
Sensor 7159: Seite 1, 1000 Ergebnisse
Sensor 7159: Seite 2, 1000 Ergebnisse
Sensor 7159: Seite 3, 645 Ergebnisse
Sensor 7179: Seite 1, 1000 Ergebnisse
Sensor 7179: Seite 2, 1000 Ergebnisse
Sensor 7179: Seite 3, 307 Ergebnisse
Sensor 7182: Seite 1, 1000 Ergebnisse
Sensor 7182: Seite 2, 1000 Ergebnisse
Sensor 7182: Seite 3, 376 Ergebnisse
Sensor 7202: Seite 1, 1000 Ergebnisse
Sensor 7202: Seite 2, 1000 Ergebnisse
Sensor 7202: Seite 3, 809 Ergebnisse
Sensor 7205: Seite 1, 1000 Ergebnisse
Sensor 7205: Seite 2, 1000 Ergebnisse
Sensor 7205: Seite 3, 578 Ergebnisse
Sensor 7213: Seite 1, 1000 Ergebnisse
Sensor 7213: Seite 2, 1000 Ergebnisse
Sensor 7213: Seite 3, 870 Ergebnisse
Sensor 7248: Seite 1, 1000 Ergebnisse
Sensor 7248: Seite 2, 1000 Ergebnisse
Sensor 7248: Seite 3, 802 Ergebnisse
Sensor 7258: Seite 1, 1000 Ergebnisse
Sensor 7258: Seite 2, 1000 Ergebnisse
Sensor 7258: Seite 3, 10 Ergebnisse
Sensor 7289: Seite 1, 1000 Ergebnisse
Sensor 7289: Seite 2, 1000 Ergebnisse
Sensor 7289: Seite 3, 346 Ergebnisse
Sensor 7290: Seite 1, 1000 Ergebnisse
Sensor 7290: Seite 2, 1000 Ergebnisse
Sensor 7290: Seite 3, 363 Ergebnisse
Sensor 7293: Seite 1, 1000 Ergebnisse
Sensor 7293: Seite 2, 1000 Ergebnisse
Sensor 7293: Seite 3, 326 Ergebnisse
Sensor 7297: Seite 1, 1000 Ergebnisse
Sensor 7297: Seite 2, 1000 Ergebnisse
Sensor 7297: Seite 3, 882 Ergebnisse
Sensor 7303: Seite 1, 1000 Ergebnisse
Sensor 7303: Seite 2, 1000 Ergebnisse
Sensor 7303: Seite 3, 343 Ergebnisse
Sensor 7318: Seite 1, 1000 Ergebnisse
Sensor 7318: Seite 2, 1000 Ergebnisse
Sensor 7318: Seite 3, 336 Ergebnisse
Sensor 7381: Seite 1, 1000 Ergebnisse
Sensor 7381: Seite 2, 1000 Ergebnisse
Sensor 7381: Seite 3, 779 Ergebnisse
Sensor 7337: Seite 1, 1000 Ergebnisse
Sensor 7337: Seite 2, 1000 Ergebnisse
Sensor 7337: Seite 3, 371 Ergebnisse
Sensor 7366: Seite 1, 1000 Ergebnisse
Sensor 7366: Seite 2, 1000 Ergebnisse
Sensor 7366: Seite 3, 427 Ergebnisse
Sensor 7372: Seite 1, 1000 Ergebnisse
Sensor 7372: Seite 2, 1000 Ergebnisse
Sensor 7372: Seite 3, 483 Ergebnisse
Sensor 7373: Seite 1, 1000 Ergebnisse
Sensor 7373: Seite 2, 1000 Ergebnisse
Sensor 7373: Seite 3, 321 Ergebnisse
Sensor 8653: Seite 1, 869 Ergebnisse
Sensor 9144: Seite 1, 935 Ergebnisse
Sensor 9638: Seite 1, 1000 Ergebnisse
Sensor 9638: Seite 2, 1000 Ergebnisse
Sensor 9638: Seite 3, 723 Ergebnisse
Sensor 9624: Seite 1, 1000 Ergebnisse
Sensor 9624: Seite 2, 1000 Ergebnisse
Sensor 9624: Seite 3, 744 Ergebnisse
Sensor 9654: Seite 1, 1000 Ergebnisse
Sensor 9654: Seite 2, 1000 Ergebnisse
Sensor 9654: Seite 3, 804 Ergebnisse
Sensor 9635: Seite 1, 1000 Ergebnisse
Sensor 9635: Seite 2, 1000 Ergebnisse
Sensor 9635: Seite 3, 674 Ergebnisse
Sensor 9674: Seite 1, 1000 Ergebnisse
Sensor 9674: Seite 2, 1000 Ergebnisse
Sensor 9674: Seite 3, 741 Ergebnisse
Sensor 9744: Seite 1, 1000 Ergebnisse
Sensor 9744: Seite 2, 1000 Ergebnisse
Sensor 9744: Seite 3, 827 Ergebnisse
Sensor 9714: Seite 1, 1000 Ergebnisse
Sensor 9714: Seite 2, 1000 Ergebnisse
Sensor 9714: Seite 3, 713 Ergebnisse
Sensor 9719: Seite 1, 1000 Ergebnisse
Sensor 9719: Seite 2, 1000 Ergebnisse
Sensor 9719: Seite 3, 743 Ergebnisse
Sensor 9684: Seite 1, 1000 Ergebnisse
Sensor 9684: Seite 2, 1000 Ergebnisse
Sensor 9684: Seite 3, 794 Ergebnisse
Sensor 9619: Seite 1, 1000 Ergebnisse
Sensor 9619: Seite 2, 1000 Ergebnisse
Sensor 9619: Seite 3, 716 Ergebnisse
Sensor 9676: Seite 1, 1000 Ergebnisse
Sensor 9676: Seite 2, 1000 Ergebnisse
Sensor 9676: Seite 3, 817 Ergebnisse
Sensor 10233: Seite 1, 1000 Ergebnisse
Sensor 10233: Seite 2, 1000 Ergebnisse
Sensor 10233: Seite 3, 512 Ergebnisse
Sensor 10267: Seite 1, 1000 Ergebnisse
Sensor 10267: Seite 2, 1000 Ergebnisse
Sensor 10267: Seite 3, 594 Ergebnisse
Sensor 10306: Seite 1, 1000 Ergebnisse
Sensor 10306: Seite 2, 1000 Ergebnisse
Sensor 10306: Seite 3, 468 Ergebnisse
Sensor 10324: Seite 1, 1000 Ergebnisse
Sensor 10324: Seite 2, 1000 Ergebnisse
Sensor 10324: Seite 3, 562 Ergebnisse
Sensor 10371: Seite 1, 1000 Ergebnisse
Sensor 10371: Seite 2, 1000 Ergebnisse
Sensor 10371: Seite 3, 542 Ergebnisse
Sensor 10383: Seite 1, 1000 Ergebnisse
Sensor 10383: Seite 2, 1000 Ergebnisse
Sensor 10383: Seite 3, 556 Ergebnisse
Sensor 10396: Seite 1, 1000 Ergebnisse
Sensor 10396: Seite 2, 1000 Ergebnisse
Sensor 10396: Seite 3, 460 Ergebnisse
Sensor 10425: Seite 1, 1000 Ergebnisse
Sensor 10425: Seite 2, 1000 Ergebnisse
Sensor 10425: Seite 3, 473 Ergebnisse
Sensor 22297: Seite 1, 720 Ergebnisse
Sensor 10445: Seite 1, 1000 Ergebnisse
Sensor 10445: Seite 2, 1000 Ergebnisse
Sensor 10445: Seite 3, 485 Ergebnisse
Sensor 10482: Seite 1, 1000 Ergebnisse
Sensor 10482: Seite 2, 1000 Ergebnisse
Sensor 10482: Seite 3, 554 Ergebnisse
Sensor 10491: Seite 1, 1000 Ergebnisse
Sensor 10491: Seite 2, 1000 Ergebnisse
Sensor 10491: Seite 3, 470 Ergebnisse
Sensor 10500: Seite 1, 1000 Ergebnisse
Sensor 10500: Seite 2, 1000 Ergebnisse
Sensor 10500: Seite 3, 276 Ergebnisse
Sensor 10511: Seite 1, 1000 Ergebnisse
Sensor 10511: Seite 2, 1000 Ergebnisse
Sensor 10511: Seite 3, 208 Ergebnisse
Sensor 10539: Seite 1, 1000 Ergebnisse
Sensor 10539: Seite 2, 1000 Ergebnisse
Sensor 10539: Seite 3, 262 Ergebnisse
Sensor 10544: Seite 1, 1000 Ergebnisse
Sensor 10544: Seite 2, 1000 Ergebnisse
Sensor 10544: Seite 3, 582 Ergebnisse
Sensor 10581: Seite 1, 922 Ergebnisse
Sensor 10646: Seite 1, 1000 Ergebnisse
Sensor 10646: Seite 2, 1000 Ergebnisse
Sensor 10646: Seite 3, 460 Ergebnisse
Sensor 6204: Seite 1, 1000 Ergebnisse
Sensor 6204: Seite 2, 1000 Ergebnisse
Sensor 6204: Seite 3, 808 Ergebnisse
Sensor 7025: Seite 1, 1000 Ergebnisse
Sensor 7025: Seite 2, 968 Ergebnisse
Sensor 7178: Seite 1, 1000 Ergebnisse
Sensor 7178: Seite 2, 1000 Ergebnisse
Sensor 7178: Seite 3, 314 Ergebnisse
Sensor 9640: Seite 1, 1000 Ergebnisse
Sensor 9640: Seite 2, 1000 Ergebnisse
Sensor 9640: Seite 3, 647 Ergebnisse
Sensor 7171: Seite 1, 1000 Ergebnisse
Sensor 7171: Seite 2, 897 Ergebnisse
Sensor 9750: Seite 1, 1000 Ergebnisse
Sensor 9750: Seite 2, 1000 Ergebnisse
Sensor 9750: Seite 3, 826 Ergebnisse
Sensor 9370: Seite 1, 1000 Ergebnisse
Sensor 9370: Seite 2, 1000 Ergebnisse
Sensor 9370: Seite 3, 544 Ergebnisse
Sensor 6211: Seite 1, 1000 Ergebnisse
Sensor 6211: Seite 2, 1000 Ergebnisse
Sensor 6211: Seite 3, 437 Ergebnisse
Sensor 9372: Seite 1, 1000 Ergebnisse
Sensor 9372: Seite 2, 1000 Ergebnisse
Sensor 9372: Seite 3, 486 Ergebnisse
Sensor 9375: Seite 1, 1000 Ergebnisse
Sensor 9375: Seite 2, 1000 Ergebnisse
Sensor 9375: Seite 3, 454 Ergebnisse
Sensor 9366: Seite 1, 1000 Ergebnisse
Sensor 9366: Seite 2, 1000 Ergebnisse
Sensor 9366: Seite 3, 503 Ergebnisse
Sensor 1316153: Seite 1, 159 Ergebnisse
Sensor 7214: Seite 1, 1000 Ergebnisse
Sensor 7214: Seite 2, 773 Ergebnisse
Sensor 7002: Seite 1, 1000 Ergebnisse
Sensor 7002: Seite 2, 1000 Ergebnisse
Sensor 7002: Seite 3, 239 Ergebnisse
Sensor 10263: Seite 1, 1000 Ergebnisse
Sensor 10263: Seite 2, 831 Ergebnisse
Sensor 10628: Seite 1, 1000 Ergebnisse
Sensor 10628: Seite 2, 895 Ergebnisse
Sensor 10238: Seite 1, 1000 Ergebnisse
Sensor 10238: Seite 2, 1000 Ergebnisse
Sensor 10238: Seite 3, 21 Ergebnisse
Sensor 10360: Seite 1, 1000 Ergebnisse
Sensor 10360: Seite 2, 997 Ergebnisse
Sensor 10607: Seite 1, 1000 Ergebnisse
Sensor 10607: Seite 2, 962 Ergebnisse
Sensor 10644: Seite 1, 1000 Ergebnisse
Sensor 10644: Seite 2, 938 Ergebnisse
Sensor 7217: Seite 1, 1000 Ergebnisse
Sensor 7217: Seite 2, 775 Ergebnisse
Sensor 7050: Seite 1, 1000 Ergebnisse
Sensor 7050: Seite 2, 617 Ergebnisse
Sensor 7197: Seite 1, 1000 Ergebnisse
Sensor 7197: Seite 2, 1000 Ergebnisse
Sensor 7197: Seite 3, 148 Ergebnisse
Sensor 8672: Seite 1, 1000 Ergebnisse
Sensor 8672: Seite 2, 531 Ergebnisse
Sensor 9111: Seite 1, 1000 Ergebnisse
Sensor 9111: Seite 2, 551 Ergebnisse
Sensor 9522: Seite 1, 1000 Ergebnisse
Sensor 9522: Seite 2, 1000 Ergebnisse
Sensor 9522: Seite 3, 114 Ergebnisse
Sensor 9602: Seite 1, 1000 Ergebnisse
Sensor 9602: Seite 2, 996 Ergebnisse
Sensor 9930: Seite 1, 1000 Ergebnisse
Sensor 9930: Seite 2, 903 Ergebnisse
Sensor 10466: Seite 1, 1000 Ergebnisse
Sensor 10466: Seite 2, 576 Ergebnisse
Sensor 10599: Seite 1, 1000 Ergebnisse
Sensor 10599: Seite 2, 1000 Ergebnisse
Sensor 10599: Seite 3, 94 Ergebnisse
Sensor 10293: Seite 1, 1000 Ergebnisse
Sensor 10293: Seite 2, 1000 Ergebnisse
Sensor 10293: Seite 3, 180 Ergebnisse
Sensor 10417: Seite 1, 1000 Ergebnisse
Sensor 10417: Seite 2, 581 Ergebnisse
Sensor 10496: Seite 1, 1000 Ergebnisse
Sensor 10496: Seite 2, 545 Ergebnisse
Sensor 10519: Seite 1, 1000 Ergebnisse
Sensor 10519: Seite 2, 1000 Ergebnisse
Sensor 10519: Seite 3, 188 Ergebnisse
Sensor 10632: Seite 1, 1000 Ergebnisse
Sensor 10632: Seite 2, 539 Ergebnisse
Sensor 6984: Seite 1, 1000 Ergebnisse
Sensor 6984: Seite 2, 1000 Ergebnisse
Sensor 6984: Seite 3, 191 Ergebnisse
Sensor 7097: Seite 1, 1000 Ergebnisse
Sensor 7097: Seite 2, 1000 Ergebnisse
Sensor 7097: Seite 3, 178 Ergebnisse
Sensor 9906: Seite 1, 1000 Ergebnisse
Sensor 9906: Seite 2, 1000 Ergebnisse
Sensor 9906: Seite 3, 140 Ergebnisse
Sensor 25102: Seite 1, 1000 Ergebnisse
Sensor 25102: Seite 2, 943 Ergebnisse
Sensor 7211: Seite 1, 1000 Ergebnisse
Sensor 7211: Seite 2, 1000 Ergebnisse
Sensor 7211: Seite 3, 164 Ergebnisse
Sensor 7255: Seite 1, 1000 Ergebnisse
Sensor 7255: Seite 2, 1000 Ergebnisse
Sensor 7255: Seite 3, 204 Ergebnisse
Sensor 29202: Seite 1, 1000 Ergebnisse
Sensor 29202: Seite 2, 925 Ergebnisse
Sensor 7284: Seite 1, 1000 Ergebnisse
Sensor 7284: Seite 2, 1000 Ergebnisse
Sensor 7284: Seite 3, 148 Ergebnisse
Sensor 6975: Seite 1, 1000 Ergebnisse
Sensor 6975: Seite 2, 301 Ergebnisse
Sensor 7100: Seite 1, 1000 Ergebnisse
Sensor 7100: Seite 2, 235 Ergebnisse
Sensor 7192: Seite 1, 1000 Ergebnisse
Sensor 7192: Seite 2, 92 Ergebnisse
Sensor 10369: Seite 1, 1000 Ergebnisse
Sensor 10369: Seite 2, 92 Ergebnisse
Sensor 10228: Seite 1, 1000 Ergebnisse
Sensor 10228: Seite 2, 96 Ergebnisse
Sensor 10283: Seite 1, 1000 Ergebnisse
Sensor 10283: Seite 2, 82 Ergebnisse
Sensor 10454: Seite 1, 1000 Ergebnisse
Sensor 10454: Seite 2, 94 Ergebnisse
Sensor 9620: Seite 1, 1000 Ergebnisse
Sensor 9620: Seite 2, 15 Ergebnisse
Sensor 7028: Seite 1, 711 Ergebnisse
Sensor 10555: Seite 1, 706 Ergebnisse
Sensor 7168: Seite 1, 578 Ergebnisse
Sensor 6997: Seite 1, 164 Ergebnisse
Sensor 7221: Seite 1, 1000 Ergebnisse
Sensor 7221: Seite 2, 1000 Ergebnisse
Sensor 7221: Seite 3, 345 Ergebnisse
Sensor 7186: Seite 1, 1000 Ergebnisse
Sensor 7186: Seite 2, 980 Ergebnisse
Sensor 6982: Seite 1, 1000 Ergebnisse
Sensor 6982: Seite 2, 1000 Ergebnisse
Sensor 6982: Seite 3, 315 Ergebnisse
Sensor 7181: Seite 1, 1000 Ergebnisse
Sensor 7181: Seite 2, 1000 Ergebnisse
Sensor 7181: Seite 3, 490 Ergebnisse
Sensor 10277: Seite 1, 1000 Ergebnisse
Sensor 10277: Seite 2, 1000 Ergebnisse
Sensor 10277: Seite 3, 468 Ergebnisse
Sensor 10299: Seite 1, 1000 Ergebnisse
Sensor 10299: Seite 2, 1000 Ergebnisse
Sensor 10299: Seite 3, 508 Ergebnisse
Sensor 10311: Seite 1, 1000 Ergebnisse
Sensor 10311: Seite 2, 1000 Ergebnisse
Sensor 10311: Seite 3, 514 Ergebnisse
Sensor 10339: Seite 1, 1000 Ergebnisse
Sensor 10339: Seite 2, 1000 Ergebnisse
Sensor 10339: Seite 3, 503 Ergebnisse
Sensor 10375: Seite 1, 1000 Ergebnisse
Sensor 10375: Seite 2, 1000 Ergebnisse
Sensor 10375: Seite 3, 482 Ergebnisse
Sensor 10380: Seite 1, 1000 Ergebnisse
Sensor 10380: Seite 2, 1000 Ergebnisse
Sensor 10380: Seite 3, 516 Ergebnisse
Sensor 10421: Seite 1, 1000 Ergebnisse
Sensor 10421: Seite 2, 1000 Ergebnisse
Sensor 10421: Seite 3, 504 Ergebnisse
Sensor 10430: Seite 1, 1000 Ergebnisse
Sensor 10430: Seite 2, 1000 Ergebnisse
Sensor 10430: Seite 3, 496 Ergebnisse
Sensor 10469: Seite 1, 1000 Ergebnisse
Sensor 10469: Seite 2, 1000 Ergebnisse
Sensor 10469: Seite 3, 517 Ergebnisse
Sensor 10508: Seite 1, 1000 Ergebnisse
Sensor 10508: Seite 2, 1000 Ergebnisse
Sensor 10508: Seite 3, 521 Ergebnisse
Sensor 10530: Seite 1, 1000 Ergebnisse
Sensor 10530: Seite 2, 1000 Ergebnisse
Sensor 10530: Seite 3, 513 Ergebnisse
Sensor 10535: Seite 1, 1000 Ergebnisse
Sensor 10535: Seite 2, 1000 Ergebnisse
Sensor 10547: Seite 1, 1000 Ergebnisse
Sensor 10547: Seite 2, 1000 Ergebnisse
Sensor 10547: Seite 3, 511 Ergebnisse
Sensor 10550: Seite 1, 1000 Ergebnisse
Sensor 10550: Seite 2, 1000 Ergebnisse
Sensor 10550: Seite 3, 423 Ergebnisse
Sensor 10559: Seite 1, 1000 Ergebnisse
Sensor 10559: Seite 2, 1000 Ergebnisse
Sensor 10559: Seite 3, 507 Ergebnisse
Sensor 10568: Seite 1, 1000 Ergebnisse
Sensor 10568: Seite 2, 1000 Ergebnisse
Sensor 10592: Seite 1, 1000 Ergebnisse
Sensor 10592: Seite 2, 1000 Ergebnisse
Sensor 10592: Seite 3, 464 Ergebnisse
Sensor 10602: Seite 1, 1000 Ergebnisse
Sensor 10602: Seite 2, 1000 Ergebnisse
Sensor 10602: Seite 3, 488 Ergebnisse
Sensor 10653: Seite 1, 1000 Ergebnisse
Sensor 10653: Seite 2, 1000 Ergebnisse
Sensor 10653: Seite 3, 514 Ergebnisse
Sensor 9573: Seite 1, 1000 Ergebnisse
Sensor 9573: Seite 2, 1000 Ergebnisse
Sensor 9573: Seite 3, 671 Ergebnisse
Sensor 10365: Seite 1, 1000 Ergebnisse
Sensor 10365: Seite 2, 1000 Ergebnisse
Sensor 10365: Seite 3, 358 Ergebnisse
Sensor 6213: Seite 1, 1000 Ergebnisse
Sensor 6213: Seite 2, 455 Ergebnisse
Sensor 7058: Seite 1, 1000 Ergebnisse
Sensor 7058: Seite 2, 754 Ergebnisse
Sensor 10674: Seite 1, 1000 Ergebnisse
Sensor 10674: Seite 2, 678 Ergebnisse
Sensor 10692: Seite 1, 1000 Ergebnisse
Sensor 10692: Seite 2, 674 Ergebnisse
Sensor 10697: Seite 1, 1000 Ergebnisse
Sensor 10697: Seite 2, 187 Ergebnisse
Sensor 10672: Seite 1, 1000 Ergebnisse
Sensor 10672: Seite 2, 684 Ergebnisse
Sensor 10683: Seite 1, 1000 Ergebnisse
Sensor 10683: Seite 2, 693 Ergebnisse
Sensor 10700: Seite 1, 1000 Ergebnisse
Sensor 10700: Seite 2, 673 Ergebnisse
Sensor 9546: Seite 1, 1000 Ergebnisse
Sensor 9546: Seite 2, 1000 Ergebnisse
Sensor 9546: Seite 3, 14 Ergebnisse
Sensor 9551: Seite 1, 1000 Ergebnisse
Sensor 9551: Seite 2, 1000 Ergebnisse
Sensor 9551: Seite 3, 12 Ergebnisse

[{'date': '2016-11-17', 'value': 50.0},
 {'date': '2016-11-18', 'value': 36.17391304347826},
 {'date': '2016-11-19', 'value': 20.545454545454547},
 {'date': '2016-11-20', 'value': 19.91304347826087},
 {'date': '2016-11-21', 'value': 31.523809523809526},
 {'date': '2016-11-22', 'value': 22.625},
 {'date': '2016-11-23', 'value': 13.434782608695652},
 {'date': '2016-11-24', 'value': 8.0},
 {'date': '2016-11-25', 'value': 31.5},
 {'date': '2016-11-26', 'value': 14.333333333333334},
 {'date': '2016-11-27', 'value': 9.818181818181818},
 {'date': '2016-11-28', 'value': 15.428571428571429},
 {'date': '2016-11-29', 'value': 18.0},
 {'date': '2016-11-30', 'value': 19.91304347826087},
 {'date': '2016-12-01', 'value': 32.8},
 {'date': '2016-12-02', 'value': 30.933333333333334},
 {'date': '2016-12-03', 'value': 19.5},
 {'date': '2016-12-05', 'value': 17.875},
 {'date': '2016-12-06', 'value': 19.0},
 {'date': '2016-12-07', 'value': 32.81818181818182},
 {'date': '2016-12-10', 'value': 32.833333333333336},
 {'date': '2016-12-11', 'value': 16.772727272727273},
 {'date': '2016-12-12', 'value': 27.61111111111111},
 {'date': '2016-12-13', 'value': 41.31578947368421},
 {'date': '2016-12-14', 'value': 34.904761904761905},
 {'date': '2016-12-15', 'value': 36.36363636363637},
 {'date': '2016-12-16', 'value': 19.8},
 {'date': '2016-12-17', 'value': 18.0},
 {'date': '2016-12-18', 'value': 14.75},
 {'date': '2016-12-19', 'value': 24.166666666666668},
 {'date': '2017-01-05', 'value': 44.333333333333336},
 {'date': '2017-01-06', 'value': 19.8},
 {'date': '2017-02-18', 'value': 24.0},
 {'date': '2017-02-19', 'value': 18.583333333333332},
 {'date': '2017-02-20', 'value': 25.666666666666668},
 {'date': '2017-02-21', 'value': 42.25},
 {'date': '2017-02-22', 'value': 27.0},
 {'date': '2017-02-23', 'value': 47.34782608695652},
 {'date': '2017-02-24', 'value': 44.25},
 {'date': '2017-02-25', 'value': 20.541666666666668},
 {'date': '2017-02-26', 'value': 19.0},
 {'date': '2017-02-27', 'value': 27.708333333333332},
 {'date': '2017-02-28', 'value': 10.541666666666666},
 {'date': '2017-03-01', 'value': 20.8125},
 {'date': '2017-03-02', 'value': 33.47826086956522},
 {'date': '2017-03-03', 'value': 18.208333333333332},
 {'date': '2017-03-04', 'value': 6.958333333333333},
 {'date': '2017-03-05', 'value': 9.791666666666666},
 {'date': '2017-03-06', 'value': 8.0},
 {'date': '2017-03-07', 'value': 8.347826086956522},
 {'date': '2017-03-08', 'value': 23.541666666666668},
 {'date': '2017-03-09', 'value': 48.875},
 {'date': '2017-03-10', 'value': 32.0},
 {'date': '2017-03-12', 'value': 15.666666666666666},
 {'date': '2017-03-13', 'value': 17.041666666666668},
 {'date': '2017-03-14', 'value': 23.291666666666668},
 {'date': '2017-03-15', 'value': 35.75},
 {'date': '2017-03-16', 'value': 45.333333333333336},
 {'date': '2017-03-17', 'value': 31.333333333333332},
 {'date': '2017-03-18', 'value': 25.291666666666668},
 {'date': '2017-03-19', 'value': 17.375},
 {'date': '2017-03-20', 'value': 29.666666666666668},
 {'date': '2017-03-21', 'value': 25.333333333333332},
 {'date': '2017-03-22', 'value': 17.833333333333332},
 {'date': '2017-03-23', 'value': 10.416666666666666},
 {'date': '2017-03-24', 'value': 16.0},
 {'date': '2017-03-27', 'value': 16.26086956521739},
 {'date': '2017-03-28', 'value': 19.416666666666668},
 {'date': '2017-03-29', 'value': 27.75},
 {'date': '2017-03-30', 'value': 24.75},
 {'date': '2017-03-31', 'value': 24.166666666666668},
 {'date': '2017-04-01', 'value': 5.791666666666667},
 {'date': '2017-04-02', 'value': 5.458333333333333},
 {'date': '2017-04-03', 'value': 17.333333333333332},
 {'date': '2017-04-04', 'value': 16.333333333333332},
 {'date': '2017-04-05', 'value': 11.833333333333334},
 {'date': '2017-04-06', 'value': 11.375},
 {'date': '2017-04-07', 'value': 19.041666666666668},
 {'date': '2017-04-08', 'value': 18.958333333333332},
 {'date': '2017-04-09', 'value': 13.166666666666666},
 {'date': '2017-04-10', 'value': 18.708333333333332},
 {'date': '2017-04-11', 'value': 25.916666666666668},
 {'date': '2017-04-12', 'value': 13.041666666666666},
 {'date': '2017-04-13', 'value': 26.666666666666668},
 {'date': '2017-04-14', 'value': 13.347826086956522},
 {'date': '2017-04-16', 'value': 25.0},
 {'date': '2017-04-17', 'value': 7.833333333333333},
 {'date': '2017-04-18', 'value': 12.1},
 {'date': '2017-04-19', 'value': 12.8125},
 {'date': '2017-04-20', 'value': 15.125},
 {'date': '2017-04-21', 'value': 18.583333333333332},
 {'date': '2017-04-22', 'value': 12.791666666666666},
 {'date': '2017-04-23', 'value': 12.0},
 {'date': '2017-04-24', 'value': 19.818181818181817},
 {'date': '2017-04-25', 'value': 17.166666666666668},
 {'date': '2017-04-26', 'value': 18.916666666666668},
 {'date': '2017-04-27', 'value': 19.958333333333332},
 {'date': '2017-04-28', 'value': 19.666666666666668},
 {'date': '2017-04-29', 'value': 14.083333333333334},
 {'date': '2017-05-02', 'value': 17.181818181818183},
 {'date': '2017-05-03', 'value': 18.555555555555557},
 {'date': '2017-05-04', 'value': 20.0},
 {'date': '2017-05-11', 'value': 16.375},
 {'date': '2017-05-12', 'value': 13.416666666666666},
 {'date': '2017-05-14', 'value': 12.842105263157896},
 {'date': '2017-05-15', 'value': 20.208333333333332},
 {'date': '2017-05-16', 'value': 24.0},
 {'date': '2017-05-17', 'value': 24.142857142857142},
 {'date': '2017-05-18', 'value': 15.055555555555555},
 {'date': '2017-05-24', 'value': 17.727272727272727},
 {'date': '2017-05-25', 'value': 23.043478260869566},
 {'date': '2017-05-26', 'value': 16.833333333333332},
 {'date': '2017-05-27', 'value': 6.5},
 {'date': '2017-05-28', 'value': 10.173913043478262},
 {'date': '2017-05-29', 'value': 13.708333333333334},
 {'date': '2017-05-30', 'value': 57.714285714285715},
 {'date': '2017-05-31', 'value': 15.521739130434783},
 {'date': '2017-06-01', 'value': 16.416666666666668},
 {'date': '2017-06-02', 'value': 14.791666666666666},
 {'date': '2017-06-03', 'value': 8.285714285714286},
 {'date': '2017-06-05', 'value': 13.125},
 {'date': '2017-06-06', 'value': 9.583333333333334},
 {'date': '2017-06-07', 'value': 8.5},
 {'date': '2017-06-08', 'value': 10.208333333333334},
 {'date': '2017-06-09', 'value': 12.473684210526315},
 {'date': '2017-06-14', 'value': 21.5},
 {'date': '2017-06-15', 'value': 21.95},
 {'date': '2017-06-16', 'value': 21.5},
 {'date': '2017-06-17', 'value': 13.208333333333334},
 {'date': '2017-06-18', 'value': 10.75},
 {'date': '2017-06-19', 'value': 10.458333333333334},
 {'date': '2017-06-20', 'value': 10.833333333333334},
 {'date': '2017-06-21', 'value': 15.583333333333334},
 {'date': '2017-06-22', 'value': 13.0},
 {'date': '2017-06-23', 'value': 17.23076923076923},
 {'date': '2017-06-24', 'value': 6.181818181818182},
 {'date': '2017-06-25', 'value': 6.7272727272727275},
 {'date': '2017-06-26', 'value': 12.875},
 {'date': '2017-06-27', 'value': 13.583333333333334},
 {'date': '2017-06-28', 'value': 8.941176470588236},
 {'date': '2017-06-29', 'value': 9.041666666666666},
 {'date': '2017-06-30', 'value': 7.25},
 {'date': '2017-07-01', 'value': 2.4347826086956523},
 {'date': '2017-07-02', 'value': 9.272727272727273},
 {'date': '2017-07-03', 'value': 14.791666666666666},
 {'date': '2017-07-04', 'value': 13.2},
 {'date': '2017-07-05', 'value': 5.0},
 {'date': '2017-07-06', 'value': 18.625},
 {'date': '2017-07-07', 'value': 16.227272727272727},
 {'date': '2017-07-08', 'value': 11.416666666666666},
 {'date': '2017-07-09', 'value': 12.458333333333334},
 {'date': '2017-07-10', 'value': 10.708333333333334},
 {'date': '2017-07-11', 'value': 9.733333333333333},
 {'date': '2017-07-12', 'value': 11.0},
 {'date': '2017-07-13', 'value': 10.45},
 {'date': '2017-07-14', 'value': 9.125},
 {'date': '2017-07-15', 'value': 9.1},
 {'date': '2017-07-16', 'value': 7.708333333333333},
 {'date': '2017-07-17', 'value': 11.208333333333334},
 {'date': '2017-07-18', 'value': 9.708333333333334},
 {'date': '2017-07-19', 'value': 12.65},
 {'date': '2017-07-20', 'value': 9.5},
 {'date': '2017-09-15', 'value': 16.695652173913043},
 {'date': '2017-09-16', 'value': 10.409090909090908},
 {'date': '2017-09-17', 'value': 9.136363636363637},
 {'date': '2017-09-18', 'value': 11.454545454545455},
 {'date': '2017-09-19', 'value': 13.368421052631579},
 {'date': '2017-09-20', 'value': 15.0},
 {'date': '2017-09-21', 'value': 20.0},
 {'date': '2017-09-22', 'value': 19.846153846153847},
 {'date': '2017-09-23', 'value': 14.15},
 {'date': '2017-09-24', 'value': 14.263157894736842},
 {'date': '2017-09-25', 'value': 16.764705882352942},
 {'date': '2017-09-26', 'value': 13.857142857142858},
 {'date': '2017-09-27', 'value': 18.928571428571427},
 {'date': '2017-09-28', 'value': 18.142857142857142},
 {'date': '2017-09-29', 'value': 22.63157894736842},
 {'date': '2017-09-30', 'value': 15.571428571428571},
 {'date': '2017-10-01', 'value': 11.090909090909092},
 {'date': '2017-10-02', 'value': 20.608695652173914},
 {'date': '2017-10-03', 'value': 18.59090909090909},
 {'date': '2017-10-04', 'value': 18.952380952380953},
 {'date': '2017-10-05', 'value': 17.952380952380953},
 {'date': '2017-10-06', 'value': 14.714285714285714},
 {'date': '2017-10-07', 'value': 12.61111111111111},
 {'date': '2017-10-08', 'value': 14.818181818181818},
 {'date': '2017-10-09', 'value': 24.17391304347826},
 {'date': '2017-10-10', 'value': 24.217391304347824},
 {'date': '2017-10-11', 'value': 20.318181818181817},
 {'date': '2017-10-12', 'value': 13.857142857142858},
 {'date': '2017-10-13', 'value': 18.217391304347824},
 {'date': '2017-10-14', 'value': 14.0},
 {'date': '2017-10-15', 'value': 10.615384615384615},
 {'date': '2017-10-16', 'value': 14.1875},
 {'date': '2017-10-17', 'value': 17.17391304347826},
 {'date': '2017-10-18', 'value': 14.571428571428571},
 {'date': '2017-10-19', 'value': 16.304347826086957},
 {'date': '2017-10-20', 'value': 11.5},
 {'date': '2017-10-21', 'value': 19.894736842105264},
 {'date': '2017-10-22', 'value': 5.909090909090909},
 {'date': '2017-10-26', 'value': 29.782608695652176},
 {'date': '2017-10-27', 'value': 22.238095238095237},
 {'date': '2017-10-28', 'value': 16.0},
 {'date': '2017-10-29', 'value': 19.863636363636363},
 {'date': '2017-10-30', 'value': 19.238095238095237},
 {'date': '2017-10-31', 'value': 26.26086956521739},
 {'date': '2017-11-01', 'value': 17.2},
 {'date': '2017-11-02', 'value': 23.625},
 {'date': '2017-11-03', 'value': 27.7},
 {'date': '2017-11-04', 'value': 13.476190476190476},
 {'date': '2017-11-05', 'value': 5.909090909090909},
 {'date': '2017-11-06', 'value': 6.052631578947368},
 {'date': '2017-11-07', 'value': 16.5625},
 {'date': '2017-11-08', 'value': 25.09090909090909},
 {'date': '2017-11-09', 'value': 17.523809523809526},
 {'date': '2017-11-10', 'value': 36.142857142857146},
 {'date': '2017-11-11', 'value': 14.421052631578947},
 {'date': '2017-11-12', 'value': 7.65},
 {'date': '2017-11-13', 'value': 6.15},
 {'date': '2017-11-14', 'value': 26.85},
 {'date': '2017-11-15', 'value': 37.388888888888886},
 {'date': '2017-11-16', 'value': 41.5625},
 {'date': '2017-11-17', 'value': 35.59090909090909},
 {'date': '2017-11-18', 'value': 25.941176470588236},
 {'date': '2017-11-19', 'value': 24.0},
 {'date': '2017-11-20', 'value': 36.68421052631579},
 {'date': '2017-11-21', 'value': 43.8421052631579},
 {'date': '2017-11-22', 'value': 35.8235294117647},
 {'date': '2017-11-23', 'value': 38.8235294117647},
 {'date': '2017-11-24', 'value': 42.1},
 {'date': '2017-11-25', 'value': 12.3125},
 {'date': '2017-11-26', 'value': 9.285714285714286},
 {'date': '2017-11-27', 'value': 17.4},
 {'date': '2017-11-30', 'value': 12.0},
 {'date': '2018-01-07', 'value': 12.291666666666666},
 {'date': '2018-01-08', 'value': 17.608695652173914},
 {'date': '2018-01-19', 'value': 34.476190476190474},
 {'date': '2018-03-10', 'value': 18.583333333333332},
 {'date': '2018-03-11', 'value': 12.25},
 {'date': '2018-03-12', 'value': 6.0},
 {'date': '2018-03-23', 'value': 16.7},
 {'date': '2018-04-26', 'value': 28.0},
 {'date': '2018-05-10', 'value': 15.0},
 {'date': '2018-06-07', 'value': 11.0},
 {'date': '2018-06-10', 'value': 10.0},
 {'date': '2018-06-22', 'value': 10.0},
 {'date': '2018-06-23', 'value': 15.772727272727273},
 {'date': '2018-06-24', 'value': 10.476190476190476},
 {'date': '2018-06-25', 'value': 7.0},
 {'date': '2018-07-01', 'value': 8.227272727272727},
 {'date': '2018-07-02', 'value': 11.909090909090908},
 {'date': '2018-07-13', 'value': 10.5},
 {'date': '2018-07-20', 'value': 8.5},
 {'date': '2018-07-23', 'value': 12.0},
 {'date': '2018-07-29', 'value': 7.0},
 {'date': '2018-07-30', 'value': 11.208333333333334},
 {'date': '2018-07-31', 'value': 20.23076923076923},
 {'date': '2018-08-12', 'value': 7.0},
 {'date': '2018-08-13', 'value': 16.0},
 {'date': '2018-08-25', 'value': 2.0},
 {'date': '2018-09-02', 'value': 3.5},
 {'date': '2018-09-05', 'value': 7.0},
 {'date': '2018-09-06', 'value': 4.0},
 {'date': '2018-09-16', 'value': 8.909090909090908},
 {'date': '2018-09-17', 'value': 9.555555555555555},
 {'date': '2018-09-22', 'value': 12.777777777777779},
 {'date': '2018-09-23', 'value': 10.666666666666666},
 {'date': '2018-09-24', 'value': 16.666666666666668},
 {'date': '2018-09-25', 'value': 12.142857142857142},
 {'date': '2018-09-26', 'value': 7.5},
 {'date': '2018-10-26', 'value': 14.0},
 {'date': '2018-11-11', 'value': 14.91304347826087},
 {'date': '2018-11-12', 'value': 16.363636363636363},
 {'date': '2018-12-01', 'value': 30.77777777777778},
 {'date': '2018-12-02', 'value': 18.125},
 {'date': '2018-12-03', 'value': 30.823529411764707},
 {'date': '2018-12-19', 'value': 15.0},
 {'date': '2019-01-01', 'value': 19.285714285714285},
 {'date': '2019-01-02', 'value': 21.75},
 {'date': '2019-01-03', 'value': 19.8},
 {'date': '2019-01-09', 'value': 9.545454545454545},
 {'date': '2019-01-10', 'value': 18.25},
 {'date': '2019-01-11', 'value': 29.923076923076923},
 {'date': '2019-01-25', 'value': 15.545454545454545},
 {'date': '2019-01-26', 'value': 17.545454545454547},
 {'date': '2019-01-27', 'value': 7.2727272727272725},
 {'date': '2019-01-28', 'value': 3.4545454545454546},
 {'date': '2019-01-29', 'value': 23.23076923076923},
 {'date': '2019-01-31', 'value': 23.0},
 {'date': '2019-02-01', 'value': 19.75},
 {'date': '2019-02-02', 'value': 3.076923076923077},
 {'date': '2019-02-03', 'value': 3.9473684210526314},
 {'date': '2019-02-04', 'value': 41.25},
 {'date': '2019-02-05', 'value': 36.5},
 {'date': '2019-02-11', 'value': 32.2},
 {'date': '2019-02-13', 'value': 28.764705882352942},
 {'date': '2019-02-14', 'value': 32.5},
 {'date': '2019-02-15', 'value': 42.6},
 {'date': '2019-02-16', 'value': 34.0},
 {'date': '2019-02-17', 'value': 20.77777777777778},
 {'date': '2019-02-18', 'value': 25.59090909090909},
 {'date': '2019-02-19', 'value': 29.75},
 {'date': '2019-02-20', 'value': 33.89473684210526},
 {'date': '2019-02-21', 'value': 30.58823529411765},
 {'date': '2019-02-22', 'value': 43.05555555555556},
 {'date': '2019-02-23', 'value': 21.333333333333332},
 {'date': '2019-02-24', 'value': 22.428571428571427},
 {'date': '2019-02-25', 'value': 31.5},
 {'date': '2019-02-26', 'value': 37.523809523809526},
 {'date': '2019-02-27', 'value': 41.42857142857143},
 {'date': '2019-02-28', 'value': 33.785714285714285},
 {'date': '2019-03-01', 'value': 28.0},
 {'date': '2019-03-02', 'value': 21.875},
 {'date': '2019-03-03', 'value': 27.333333333333332},
 {'date': '2019-03-04', 'value': 14.833333333333334},
 {'date': '2019-03-05', 'value': 23.8125},
 {'date': '2019-03-06', 'value': 24.6},
 {'date': '2019-03-07', 'value': 7.909090909090909},
 {'date': '2019-03-08', 'value': 29.0},
 {'date': '2019-03-09', 'value': 22.9375},
 {'date': '2019-03-10', 'value': 20.125},
 {'date': '2019-03-11', 'value': 13.8125},
 {'date': '2019-03-12', 'value': 17.91304347826087},
 {'date': '2019-03-13', 'value': 12.0},
 {'date': '2019-03-14', 'value': 3.0},
 {'date': '2019-03-15', 'value': 32.06666666666667},
 {'date': '2019-03-16', 'value': 25.35},
 {'date': '2019-03-17', 'value': 19.772727272727273},
 {'date': '2019-03-18', 'value': 12.545454545454545},
 {'date': '2019-03-19', 'value': 15.052631578947368},
 {'date': '2019-03-20', 'value': 15.6},
 {'date': '2019-03-21', 'value': 20.3},
 {'date': '2019-03-22', 'value': 21.263157894736842},
 {'date': '2019-03-23', 'value': 25.954545454545453},
 {'date': '2019-03-24', 'value': 21.761904761904763},
 {'date': '2019-03-25', 'value': 14.842105263157896},
 {'date': '2019-03-26', 'value': 15.695652173913043},
 {'date': '2019-03-27', 'value': 20.47826086956522},
 {'date': '2019-03-28', 'value': 26.055555555555557},
 {'date': '2019-03-29', 'value': 18.444444444444443},
 {'date': '2019-03-30', 'value': 14.4},
 {'date': '2019-03-31', 'value': 13.7},
 {'date': '2019-04-01', 'value': 21.545454545454547},
 {'date': '2019-04-02', 'value': 23.666666666666668},
 {'date': '2019-04-03', 'value': 13.65},
 {'date': '2019-04-04', 'value': 5.0},
 {'date': '2019-04-05', 'value': 13.571428571428571},
 {'date': '2019-04-06', 'value': 7.0},
 {'date': '2019-04-07', 'value': 9.954545454545455},
 {'date': '2019-04-08', 'value': 19.523809523809526},
 {'date': '2019-04-09', 'value': 15.090909090909092},
 {'date': '2019-04-10', 'value': 18.545454545454547},
 {'date': '2019-04-11', 'value': 12.636363636363637},
 {'date': '2019-04-12', 'value': 15.545454545454545},
 {'date': '2019-04-13', 'value': 12.0},
 {'date': '2019-04-14', 'value': 13.0},
 {'date': '2019-04-15', 'value': 13.181818181818182},
 {'date': '2019-04-16', 'value': 15.4},
 {'date': '2019-04-17', 'value': 12.181818181818182},
 {'date': '2019-04-18', 'value': 9.272727272727273},
 {'date': '2019-04-19', 'value': 4.428571428571429},
 {'date': '2019-04-20', 'value': 7.65},
 {'date': '2019-04-21', 'value': 12.681818181818182},
 {'date': '2019-04-22', 'value': 16.19047619047619},
 {'date': '2019-04-23', 'value': 14.555555555555555},
 {'date': '2019-04-24', 'value': 11.0},
 {'date': '2019-04-25', 'value': 14.857142857142858},
 {'date': '2019-04-26', 'value': 8.181818181818182},
 {'date': '2019-04-27', 'value': 14.052631578947368},
 {'date': '2019-04-28', 'value': 15.4},
 {'date': '2019-04-29', 'value': 14.076923076923077},
 {'date': '2019-04-30', 'value': 13.761904761904763},
 {'date': '2019-05-01', 'value': 9.714285714285714},
 {'date': '2019-05-02', 'value': 14.75},
 {'date': '2019-05-03', 'value': 18.454545454545453},
 {'date': '2019-05-04', 'value': 9.380952380952381},
 {'date': '2019-05-05', 'value': 4.478260869565218},
 {'date': '2019-05-06', 'value': 13.95},
 {'date': '2019-05-07', 'value': 21.055555555555557},
 {'date': '2019-05-08', 'value': 31.391304347826086},
 {'date': '2019-05-09', 'value': 11.130434782608695},
 {'date': '2019-05-10', 'value': 26.958333333333332},
 {'date': '2019-05-11', 'value': 11.65},
 {'date': '2019-05-12', 'value': 8.647058823529411},
 {'date': '2019-05-13', 'value': 8.5},
 {'date': '2019-05-14', 'value': 16.75},
 {'date': '2019-05-15', 'value': 11.714285714285714},
 {'date': '2019-05-18', 'value': 8.416666666666666},
 {'date': '2019-05-19', 'value': 6.416666666666667},
 {'date': '2019-05-20', 'value': 18.789473684210527},
 {'date': '2019-05-25', 'value': 8.0},
 {'date': '2019-05-27', 'value': 11.666666666666666},
 {'date': '2019-06-01', 'value': 20.0},
 {'date': '2019-06-04', 'value': 6.0},
 {'date': '2019-06-08', 'value': 13.5},
 {'date': '2019-06-15', 'value': 20.0},
 {'date': '2019-06-21', 'value': 12.0},
 {'date': '2019-06-22', 'value': 22.0},
 {'date': '2019-06-29', 'value': 52.0},
 {'date': '2019-07-03', 'value': -999.0},
 {'date': '2019-07-04', 'value': -582.75},
 {'date': '2019-07-05', 'value': 0.0},
 {'date': '2019-07-06', 'value': 0.0},
 {'date': '2019-07-07', 'value': 0.0},
 {'date': '2019-07-08', 'value': 0.0},
 {'date': '2019-07-09', 'value': 0.0},
 {'date': '2019-07-10', 'value': 0.0},
 {'date': '2019-07-11', 'value': 0.8333333333333334},
 {'date': '2019-07-12', 'value': 0.0},
 {'date': '2019-07-13', 'value': 5.0588235294117645},
 {'date': '2019-07-14', 'value': 6.375},

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

spain_daily = (
    df_results.groupby("date")
              .agg(spain_no2_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

spain_daily

           date  france_no2_mean
0    2016-11-17        40.921589
1    2016-11-18        33.937771
2    2016-11-19        23.059994
3    2016-11-20        18.638655
4    2016-11-21        20.418419
...         ...              ...
3150 2026-02-24        24.743590
3151 2026-02-25        25.210526
3152 2026-02-26        13.820513
3153 2026-02-27        17.013158
3154 2026-02-28         9.972973

[3155 rows x 2 columns]

In [ ]:
spain_daily[["date", "spain_no2_mean"]].to_csv(
    "daily_avg_spain_NO2.csv",
    index=False
)