# Get daily average values for air pollution in Austria from 2016-2026 using openAQ API

In [2]:
import requests
import pandas as pd 
import time

### List possible parameters (e.g. PM10, PM2.5, NO2)

In [2]:
api_url = "https://api.openaq.org/v3/parameters"

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, headers=headers)
response = response.json()

response

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 46},
 'results': [{'id': 1,
   'name': 'pm10',
   'units': 'µg/m³',
   'displayName': 'PM10',
   'description': 'Particulate matter less than 10 micrometers in diameter mass concentration'},
  {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': 'PM2.5',
   'description': 'Particulate matter less than 2.5 micrometers in diameter mass concentration'},
  {'id': 3,
   'name': 'o3',
   'units': 'µg/m³',
   'displayName': 'O₃ mass',
   'description': 'Ozone mass concentration'},
  {'id': 4,
   'name': 'co',
   'units': 'µg/m³',
   'displayName': 'CO mass',
   'description': 'Carbon Monoxide mass concentration'},
  {'id': 5,
   'name': 'no2',
   'units': 'µg/m³',
   'displayName': 'NO₂ mass',
   'description': 'Nitrogen Dioxide mass concentration'},
  {'id': 6,
   'name': 'so2',
   'units': 'µg/m³',
   'displayName': 'SO₂ mass',
   'description': 'Sulfur Dioxide mass concentration'},
  {'id': 7,
   'name': 'no2',
   'units': 'ppm',
   'displayName': 'NO₂',
   'description': 'Nitrogen Dioxide concentration'},
  {'id': 8,
   'name': 'co',
   'units': 'ppm',
   'displayName': 'CO',
   'description': 'Carbon Monoxide concentration'},
  {'id': 9,
   'name': 'so2',
   'units': 'ppm',
   'displayName': 'SO₂',
   'description': 'Sulfur Dioxide concentration'},
  {'id': 10,
   'name': 'o3',
   'units': 'ppm',
   'displayName': 'O₃',
   'description': 'Ozone concentration'},
  {'id': 11,
   'name': 'bc',
   'units': 'µg/m³',
   'displayName': 'BC',
   'description': 'Black Carbon mass concentration'},
  {'id': 15,
   'name': 'no2',
   'units': 'ppb',
   'displayName': 'NO₂',
   'description': None},
  {'id': 19,
   'name': 'pm1',
   'units': 'µg/m³',
   'displayName': 'PM1',
   'description': 'Particulate matter less than 1 micrometer in diameter mass concentration'},
  {'id': 21,
   'name': 'co2',
   'units': 'ppm',
   'displayName': 'CO₂',
   'description': 'Carbon Dioxide concentration'},
  {'id': 22,
   'name': 'wind_direction',
   'units': 'deg',
   'displayName': 'Wind direction',
   'description': 'Direction that the wind originates from'},
  {'id': 23,
   'name': 'nox',
   'units': 'ppb',
   'displayName': 'NOX',
   'description': None},
  {'id': 24,
   'name': 'no',
   'units': 'ppb',
   'displayName': 'NO',
   'description': None},
  {'id': 27,
   'name': 'nox',
   'units': 'µg/m³',
   'displayName': 'NOx mass',
   'description': 'Nitrogen Oxides mass concentration'},
  {'id': 28,
   'name': 'ch4',
   'units': 'ppm',
   'displayName': 'CH₄',
   'description': 'Methane concentration'},
  {'id': 32,
   'name': 'o3',
   'units': 'ppb',
   'displayName': 'O₃',
   'description': None},
  {'id': 33,
   'name': 'ufp',
   'units': 'particles/cm³',
   'displayName': 'UFP count',
   'description': 'Ultrafine Particles count concentration'},
  {'id': 34,
   'name': 'wind_speed',
   'units': 'm/s',
   'displayName': 'Wind speed',
   'description': 'Average wind speed in meters per second'},
  {'id': 35,
   'name': 'no',
   'units': 'ppm',
   'displayName': 'NO',
   'description': 'Nitrogen Monoxide concentration'},
  {'id': 95,
   'name': 'pressure',
   'units': 'hpa',
   'displayName': 'Atmospheric pressure',
   'description': 'Atmospheric or barometric pressure'},
  {'id': 97,
   'name': 'pm25-old',
   'units': 'ugm3',
   'displayName': None,
   'description': None},
  {'id': 98,
   'name': 'relativehumidity',
   'units': '%',
   'displayName': 'RH',
   'description': None},
  {'id': 100,
   'name': 'temperature',
   'units': 'c',
   'displayName': 'Temperature (C)',
   'description': None},
  {'id': 101,
   'name': 'so2',
   'units': 'ppb',
   'displayName': 'SO₂',
   'description': None},
  {'id': 102,
   'name': 'co',
   'units': 'ppb',
   'displayName': 'CO',
   'description': None},
  {'id': 125,
   'name': 'um003',
   'units': 'particles/cm³',
   'displayName': 'PM0.3 count',
   'description': None},
  {'id': 126,
   'name': 'um010',
   'units': 'particles/cm³',
   'displayName': 'PM1 count',
   'description': 'PM1 count'},
  {'id': 128,
   'name': 'temperature',
   'units': 'f',
   'displayName': 'Temperature (F)',
   'description': None},
  {'id': 130,
   'name': 'um025',
   'units': 'particles/cm³',
   'displayName': 'PM2.5 count',
   'description': 'PM2.5 count'},
  {'id': 132,
   'name': 'pressure',
   'units': 'mb',
   'displayName': 'Pressure',
   'description': None},
  {'id': 134,
   'name': 'humidity',
   'units': '%',
   'displayName': 'H',
   'description': None},
  {'id': 135,
   'name': 'um100',
   'units': 'particles/cm³',
   'displayName': 'PM10 count',
   'description': 'PM10 count'},
  {'id': 19840,
   'name': 'nox',
   'units': 'ppm',
   'displayName': 'NOx',
   'description': 'Nitrogen Oxides concentration'},
  {'id': 19843,
   'name': 'no',
   'units': 'µg/m³',
   'displayName': 'NO mass',
   'description': 'Nitrogen Monoxide mass concentration'},
  {'id': 19844,
   'name': 'pm4',
   'units': 'µg/m³',
   'displayName': 'PM4.0',
   'description': 'Particulate matter less than 4 micrometers in diameter mass concentration'},
  {'id': 19860,
   'name': 'pm25',
   'units': 'ppm',
   'displayName': None,
   'description': None},
  {'id': 19861,
   'name': 'bc_375',
   'units': 'ng/m³',
   'displayName': 'BC 375nm',
   'description': 'Black Carbon mass concentration 375nm '},
  {'id': 19862,
   'name': 'bc_470',
   'units': 'ng/m³',
   'displayName': 'BC 470nm',
   'description': 'Black Carbon mass concentration 470nm '},
  {'id': 19863,
   'name': 'bc_528',
   'units': 'ng/m³',
   'displayName': 'BC 528nm',
   'description': 'Black Carbon mass concentration 528nm '},
  {'id': 19864,
   'name': 'bc_625',
   'units': 'ng/m³',
   'displayName': 'BC 625nm',
   'description': 'Black Carbon mass concentration 625nm '},
  {'id': 19865,
   'name': 'bc_880',
   'units': 'ng/m³',
   'displayName': 'BC 880nm',
   'description': 'Black Carbon mass concentration 880nm '},
  {'id': 19866,
   'name': 'bc_370',
   'units': 'ng/m³',
   'displayName': 'BC 370nm',
   'description': 'Black Carbon mass concentration 375nm '}]}

# PM10

### Get all stations located in Poland that measure PM10
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "AT",   # only consider stations located in Austria
    "parameters_id": 1,   # PM10 
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm10 = df_sorted

df_top_pm10

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
8,2752,Wiener Neustadt,2700 Wiener Neustadt,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275363, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.814166999937704, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.254999999598795, 47.814166999937704, 16.25...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
15,2761,Mürzzuschlag Roseggerpark,8680 Mürzzuschlag,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275306, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.604721999960276, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.673056000049757, 47.604721999960276, 15.67...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
18,2764,Grünbach bei Freistadt,4264 Grünbach,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274395, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.53110999980738, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.574722000058197, 48.53110999980738, 14.574...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
20,2766,Liezen Pyhrnbach,8940 Liezen,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274806, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.56543899973233, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.244675999684107, 47.56543899973233, 14.244...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
24,2770,Bruck an der Mur Flurgasse,8600 Bruck an der Mur,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5787, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 47.40944299996983, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.253333000357205, 47.40944299996983, 15.253...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,4816305,Mödling Bachgasse,2340 Mödling,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13388776, 'name': 'co µg/m³', 'paramet...","{'latitude': 48.085556000069815, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.300972000220895, 48.085556000069815, 16.30...",None,2025-06-19 11:00:00+00:00,2026-03-05 17:00:00+00:00
265,4816306,Steyr Münichholz,4400 Steyr,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13388778, 'name': 'no2 µg/m³', 'parame...","{'latitude': 48.04925000005705, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.442361000245842, 48.04925000005705, 14.442...",None,2025-06-19 11:00:00+00:00,2026-03-05 17:00:00+00:00
266,6149652,"Stockerau, Rudolf Diesel-Straße",2000 Stockerau,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14776823, 'name': 'no2 µg/m³', 'parame...","{'latitude': 48.38499999970251, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.18211000035268, 48.38499999970251, 16.1821...",None,2025-11-29 09:00:00+00:00,2026-03-05 17:00:00+00:00
267,6150274,Salzburg Airport Kendlerstraße,5020 Salzburg,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14781509, 'name': 'no2 µg/m³', 'parame...","{'latitude': 47.78549099991712, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[13.011450999985355, 47.78549099991712, 13.011...",None,2025-11-29 23:00:00+00:00,2026-03-05 17:00:00+00:00
268,6170365,Klosterneuburg B14,3400 Klosterneuburg,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14931945, 'name': 'no2 µg/m³', 'parame...","{'latitude': 48.30832999974348, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.32803000038363, 48.30832999974348, 16.3280...",None,2025-12-16 23:00:00+00:00,2026-03-05 17:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [4]:
rows = []

for _, station in df_top_pm10.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM10 behalten
        if sensor["parameter"]["id"] == 1:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm10_sensors = pd.DataFrame(rows)

df_pm10_sensors

     station_id                     station_name  sensor_id sensor_name
0          2752                  Wiener Neustadt       5765  pm10 µg/m³
1          2761        Mürzzuschlag Roseggerpark       5752  pm10 µg/m³
2          2764           Grünbach bei Freistadt      11177  pm10 µg/m³
3          2766                 Liezen Pyhrnbach       6123  pm10 µg/m³
4          2770       Bruck an der Mur Flurgasse       5777  pm10 µg/m³
..          ...                              ...        ...         ...
264     4816305                Mödling Bachgasse   13388781  pm10 µg/m³
265     4816306                 Steyr Münichholz   13388779  pm10 µg/m³
266     6149652  Stockerau, Rudolf Diesel-Straße   14776824  pm10 µg/m³
267     6150274   Salzburg Airport Kendlerstraße   14781508  pm10 µg/m³
268     6170365               Klosterneuburg B14   14931944  pm10 µg/m³

[269 rows x 4 columns]

In [5]:
sensor_ids = df_pm10_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

269

[5765,
 5752,
 11177,
 6123,
 5777,
 5875,
 5881,
 5923,
 11473,
 5932,
 6064,
 5127007,
 6150,
 5940,
 5902,
 5999,
 11482,
 5953,
 5775,
 5870,
 6014,
 6175,
 5990,
 6034,
 6089,
 6149,
 6113,
 6154,
 6166,
 30320,
 39534,
 5943,
 6004,
 5790,
 6102,
 5680,
 5906,
 5857,
 5821,
 5744,
 5754,
 5751,
 5755,
 5757,
 6164,
 5762,
 5770,
 6153,
 5772,
 5778,
 5824,
 5784,
 5788,
 5792,
 5797,
 5800,
 5804,
 5808,
 5812,
 5815,
 6174,
 5826,
 5832,
 5837,
 5846,
 5869,
 5858,
 5862,
 5865,
 5867,
 6015,
 5912,
 5994,
 6104,
 5914,
 5918,
 5922,
 5936,
 6050,
 5958,
 6053,
 5973,
 5974,
 5992,
 5984,
 6046,
 6054,
 6018,
 6013,
 6016,
 6035,
 6026,
 6070,
 6080,
 6074,
 6124,
 6095,
 6130,
 6179,
 6116,
 6132,
 6145,
 6162,
 5748,
 5676,
 11579,
 11492,
 11306,
 11194,
 11479,
 11545,
 11431,
 11611,
 7380225,
 11227,
 11145,
 11472,
 11508,
 11585,
 11254,
 11154,
 11156,
 11192,
 11190,
 11202,
 11209,
 11212,
 11313,
 11343,
 11350,
 11352,
 11391,
 11397,
 11412,
 11443,
 11468,
 11484,
 11503,
 11515,
 11602,
 11581,
 11574,
 11620,
 11558,
 11273,
 11171,
 11248,
 11617,
 11640,
 11234,
 11251,
 11287,
 11302,
 11416,
 11451,
 11485,
 11512,
 11520,
 11526,
 11563,
 11618,
 11600,
 3219328,
 39535,
 11293,
 11590,
 11626,
 11316,
 11488,
 11331,
 11151,
 11323,
 11150,
 11283,
 11439,
 11530,
 11534,
 7903,
 5078757,
 5078789,
 5078304,
 5078390,
 5078476,
 5078791,
 5078977,
 5078807,
 5078850,
 5078856,
 5078950,
 5078377,
 5078756,
 5078562,
 5078483,
 5078370,
 5078673,
 5078951,
 5078666,
 5078362,
 5078675,
 7773945,
 7773511,
 7773559,
 7775512,
 7775126,
 7775318,
 7774314,
 7773379,
 7772982,
 7775029,
 7774394,
 7774536,
 7775129,
 7774143,
 7775727,
 7773022,
 7774456,
 7773570,
 7775746,
 7775180,
 7773856,
 7773418,
 7773853,
 7774161,
 7775160,
 7773263,
 7775263,
 7775395,
 7774807,
 7774926,
 7774397,
 7774598,
 7773084,
 7775442,
 7773035,
 7773455,
 7774073,
 7775364,
 7775098,
 7774088,
 7775644,
 7774554,
 13537108,
 7772829,
 7777006,
 7773187,
 7774151,
 7773358,
 7772953,
 7774904,
 7773643,
 7775493,
 7772909,
 7773950,
 7772769,
 7944808,
 7944809,
 7944819,
 9440306,
 9440302,
 12389003,
 11735553,
 12384597,
 12384598,
 12389004,
 13388781,
 13388779,
 14776824,
 14781508,
 14931944]

### Get daily, average values from each sensor/station for 2016-2026

In [6]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 5765: Seite 1, 1000 Ergebnisse
Sensor 5765: Seite 2, 1000 Ergebnisse
Sensor 5765: Seite 3, 168 Ergebnisse
Sensor 5752: Seite 1, 1000 Ergebnisse
Sensor 5752: Seite 2, 1000 Ergebnisse
Sensor 5752: Seite 3, 170 Ergebnisse
Sensor 11177: Seite 1, 1000 Ergebnisse
Sensor 11177: Seite 2, 1000 Ergebnisse
Sensor 11177: Seite 3, 143 Ergebnisse
Sensor 6123: Seite 1, 1000 Ergebnisse
Sensor 6123: Seite 2, 1000 Ergebnisse
Sensor 6123: Seite 3, 165 Ergebnisse
Sensor 5777: Seite 1, 1000 Ergebnisse
Sensor 5777: Seite 2, 1000 Ergebnisse
Sensor 5777: Seite 3, 163 Ergebnisse
Sensor 5875: Seite 1, 1000 Ergebnisse
Sensor 5875: Seite 2, 1000 Ergebnisse
Sensor 5875: Seite 3, 35 Ergebnisse
Sensor 5881: Seite 1, 1000 Ergebnisse
Sensor 5881: Seite 2, 1000 Ergebnisse
Sensor 5881: Seite 3, 171 Ergebnisse
Sensor 5923: Seite 1, 1000 Ergebnisse
Sensor 5923: Seite 2, 1000 Ergebnisse
Sensor 5923: Seite 3, 170 Ergebnisse
Sensor 11473: Seite 1, 1000 Ergebnisse
Sensor 11473: Seite 2, 1000 Ergebnisse
Sensor 11473: Seite 3, 142 Ergebnisse
Sensor 5932: Seite 1, 1000 Ergebnisse
Sensor 5932: Seite 2, 1000 Ergebnisse
Sensor 5932: Seite 3, 168 Ergebnisse
Sensor 6064: Seite 1, 1000 Ergebnisse
Sensor 6064: Seite 2, 1000 Ergebnisse
Sensor 6064: Seite 3, 163 Ergebnisse
Sensor 5127007: Seite 1, 947 Ergebnisse
Sensor 6150: Seite 1, 1000 Ergebnisse
Sensor 6150: Seite 2, 1000 Ergebnisse
Sensor 6150: Seite 3, 168 Ergebnisse
Sensor 5940: Seite 1, 1000 Ergebnisse
Sensor 5940: Seite 2, 1000 Ergebnisse
Sensor 5940: Seite 3, 89 Ergebnisse
Sensor 5902: Seite 1, 1000 Ergebnisse
Sensor 5902: Seite 2, 930 Ergebnisse
Sensor 5999: Seite 1, 1000 Ergebnisse
Sensor 5999: Seite 2, 476 Ergebnisse
Sensor 11482: Seite 1, 1000 Ergebnisse
Sensor 11482: Seite 2, 460 Ergebnisse
Sensor 5953: Seite 1, 1000 Ergebnisse
Sensor 5953: Seite 2, 479 Ergebnisse
Sensor 5775: Seite 1, 1000 Ergebnisse
Sensor 5775: Seite 2, 481 Ergebnisse
Sensor 5870: Seite 1, 1000 Ergebnisse
Sensor 5870: Seite 2, 469 Ergebnisse
Sensor 6014: Seite 1, 1000 Ergebnisse
Sensor 6014: Seite 2, 481 Ergebnisse
Sensor 6175: Seite 1, 1000 Ergebnisse
Sensor 6175: Seite 2, 479 Ergebnisse
Sensor 5990: Seite 1, 1000 Ergebnisse
Sensor 5990: Seite 2, 453 Ergebnisse
Sensor 6034: Seite 1, 1000 Ergebnisse
Sensor 6034: Seite 2, 484 Ergebnisse
Sensor 6089: Seite 1, 1000 Ergebnisse
Sensor 6089: Seite 2, 483 Ergebnisse
Sensor 6149: Seite 1, 1000 Ergebnisse
Sensor 6149: Seite 2, 463 Ergebnisse
Sensor 6113: Seite 1, 1000 Ergebnisse
Sensor 6113: Seite 2, 484 Ergebnisse
Sensor 6154: Seite 1, 1000 Ergebnisse
Sensor 6154: Seite 2, 484 Ergebnisse
Sensor 6166: Seite 1, 28 Ergebnisse
Sensor 30320: Seite 1, 1000 Ergebnisse
Sensor 30320: Seite 2, 269 Ergebnisse
Sensor 39534: Seite 1, 1000 Ergebnisse
Sensor 39534: Seite 2, 74 Ergebnisse
Sensor 5943: Seite 1, 1000 Ergebnisse
Sensor 5943: Seite 2, 309 Ergebnisse
Sensor 6004: Seite 1, 438 Ergebnisse
Sensor 5790: Seite 1, 156 Ergebnisse
Sensor 6102: Seite 1, 58 Ergebnisse
Sensor 5680: Seite 1, 19 Ergebnisse
Sensor 5906: Seite 1, 22 Ergebnisse
Sensor 5857: Seite 1, 22 Ergebnisse
Sensor 5821: Seite 1, 22 Ergebnisse
Sensor 5744: Seite 1, 22 Ergebnisse
Sensor 5754: Seite 1, 22 Ergebnisse
Sensor 5751: Seite 1, 22 Ergebnisse
Sensor 5755: Seite 1, 22 Ergebnisse
Sensor 5757: Seite 1, 22 Ergebnisse
Sensor 6164: Seite 1, 22 Ergebnisse
Sensor 5762: Seite 1, 22 Ergebnisse
Sensor 5770: Seite 1, 22 Ergebnisse
Sensor 6153: Seite 1, 22 Ergebnisse
Sensor 5772: Seite 1, 22 Ergebnisse
Sensor 5778: Seite 1, 22 Ergebnisse
Sensor 5824: Seite 1, 22 Ergebnisse
Sensor 5784: Seite 1, 22 Ergebnisse
Sensor 5788: Seite 1, 22 Ergebnisse
Sensor 5792: Seite 1, 22 Ergebnisse
Sensor 5797: Seite 1, 22 Ergebnisse
Sensor 5800: Seite 1, 22 Ergebnisse
Sensor 5804: Seite 1, 22 Ergebnisse
Sensor 5808: Seite 1, 22 Ergebnisse
Sensor 5812: Seite 1, 22 Ergebnisse
Sensor 5815: Seite 1, 22 Ergebnisse
Sensor 6174: Seite 1, 22 Ergebnisse
Sensor 5826: Seite 1, 22 Ergebnisse
Sensor 5832: Seite 1, 22 Ergebnisse
Sensor 5837: Seite 1, 22 Ergebnisse
Sensor 5846: Seite 1, 22 Ergebnisse
Sensor 5869: Seite 1, 22 Ergebnisse
Sensor 5858: Seite 1, 22 Ergebnisse
Sensor 6130: Seite 1, 22 Ergebnisse
Sensor 6179: Seite 1, 22 Ergebnisse
Sensor 6116: Seite 1, 22 Ergebnisse
Sensor 6132: Seite 1, 22 Ergebnisse
Sensor 6145: Seite 1, 22 Ergebnisse
Sensor 6162: Seite 1, 22 Ergebnisse
Sensor 5748: Seite 1, 22 Ergebnisse
Sensor 5676: Seite 1, 1000 Ergebnisse
Sensor 5676: Seite 2, 449 Ergebnisse
Sensor 11579: Seite 1, 1000 Ergebnisse
Sensor 11579: Seite 2, 1000 Ergebnisse
Sensor 11579: Seite 3, 147 Ergebnisse
Sensor 11492: Seite 1, 1000 Ergebnisse
Sensor 11492: Seite 2, 1000 Ergebnisse
Sensor 11492: Seite 3, 88 Ergebnisse
Sensor 11306: Seite 1, 1000 Ergebnisse
Sensor 11306: Seite 2, 1000 Ergebnisse
Sensor 11306: Seite 3, 98 Ergebnisse
Sensor 11194: Seite 1, 1000 Ergebnisse
Sensor 11194: Seite 2, 798 Ergebnisse
Sensor 11479: Seite 1, 1000 Ergebnisse
Sensor 11479: Seite 2, 1000 Ergebnisse
Sensor 11479: Seite 3, 146 Ergebnisse
Sensor 11545: Seite 1, 1000 Ergebnisse
Sensor 11545: Seite 2, 1000 Ergebnisse
Sensor 11545: Seite 3, 133 Ergebnisse
Sensor 11431: Seite 1, 1000 Ergebnisse
Sensor 11431: Seite 2, 1000 Ergebnisse
Sensor 11431: Seite 3, 137 Ergebnisse
Sensor 11611: Seite 1, 1000 Ergebnisse
Sensor 11611: Seite 2, 1000 Ergebnisse
Sensor 11611: Seite 3, 150 Ergebnisse
Sensor 7380225: Seite 1, 84 Ergebnisse
Sensor 11227: Seite 1, 1000 Ergebnisse
Sensor 11227: Seite 2, 448 Ergebnisse
Sensor 11145: Seite 1, 1000 Ergebnisse
Sensor 11145: Seite 2, 396 Ergebnisse
Sensor 11472: Seite 1, 1000 Ergebnisse
Sensor 11472: Seite 2, 429 Ergebnisse
Sensor 11508: Seite 1, 1000 Ergebnisse
Sensor 11508: Seite 2, 459 Ergebnisse
Sensor 11585: Seite 1, 1000 Ergebnisse
Sensor 11585: Seite 2, 460 Ergebnisse
Sensor 11254: Seite 1, 1000 Ergebnisse
Sensor 11254: Seite 2, 1000 Ergebnisse
Sensor 11254: Seite 3, 90 Ergebnisse
Sensor 11154: Seite 1, 1000 Ergebnisse
Sensor 11154: Seite 2, 1000 Ergebnisse
Sensor 11154: Seite 3, 146 Ergebnisse
Sensor 11156: Seite 1, 1000 Ergebnisse
Sensor 11156: Seite 2, 1000 Ergebnisse
Sensor 11156: Seite 3, 145 Ergebnisse
Sensor 11192: Seite 1, 1000 Ergebnisse
Sensor 11192: Seite 2, 1000 Ergebnisse
Sensor 11192: Seite 3, 96 Ergebnisse
Sensor 11190: Seite 1, 1000 Ergebnisse
Sensor 11190: Seite 2, 1000 Ergebnisse
Sensor 11190: Seite 3, 133 Ergebnisse
Sensor 11202: Seite 1, 1000 Ergebnisse
Sensor 11202: Seite 2, 1000 Ergebnisse
Sensor 11202: Seite 3, 145 Ergebnisse
Sensor 11209: Seite 1, 1000 Ergebnisse
Sensor 11209: Seite 2, 1000 Ergebnisse
Sensor 11209: Seite 3, 146 Ergebnisse
Sensor 11313: Seite 1, 1000 Ergebnisse
Sensor 11313: Seite 2, 1000 Ergebnisse
Sensor 11313: Seite 3, 146 Ergebnisse
Sensor 11343: Seite 1, 1000 Ergebnisse
Sensor 11343: Seite 2, 1000 Ergebnisse
Sensor 11343: Seite 3, 146 Ergebnisse
Sensor 11350: Seite 1, 1000 Ergebnisse
Sensor 11350: Seite 2, 1000 Ergebnisse
Sensor 11350: Seite 3, 146 Ergebnisse
Sensor 11352: Seite 1, 1000 Ergebnisse
Sensor 11352: Seite 2, 1000 Ergebnisse
Sensor 11352: Seite 3, 148 Ergebnisse
Sensor 11391: Seite 1, 1000 Ergebnisse
Sensor 11391: Seite 2, 1000 Ergebnisse
Sensor 11391: Seite 3, 147 Ergebnisse
Sensor 11397: Seite 1, 1000 Ergebnisse
Sensor 11397: Seite 2, 1000 Ergebnisse
Sensor 11397: Seite 3, 72 Ergebnisse
Sensor 11412: Seite 1, 1000 Ergebnisse
Sensor 11412: Seite 2, 1000 Ergebnisse
Sensor 11412: Seite 3, 146 Ergebnisse
Sensor 11443: Seite 1, 1000 Ergebnisse
Sensor 11443: Seite 2, 1000 Ergebnisse
Sensor 11443: Seite 3, 149 Ergebnisse
Sensor 11468: Seite 1, 1000 Ergebnisse
Sensor 11468: Seite 2, 1000 Ergebnisse
Sensor 11468: Seite 3, 147 Ergebnisse
Sensor 11484: Seite 1, 1000 Ergebnisse
Sensor 11484: Seite 2, 1000 Ergebnisse
Sensor 11484: Seite 3, 87 Ergebnisse
Sensor 11503: Seite 1, 1000 Ergebnisse
Sensor 11503: Seite 2, 1000 Ergebnisse
Sensor 11503: Seite 3, 148 Ergebnisse
Sensor 11515: Seite 1, 1000 Ergebnisse
Sensor 11515: Seite 2, 1000 Ergebnisse
Sensor 11515: Seite 3, 84 Ergebnisse
Sensor 11602: Seite 1, 1000 Ergebnisse
Sensor 11602: Seite 2, 1000 Ergebnisse
Sensor 11602: Seite 3, 147 Ergebnisse
Sensor 11581: Seite 1, 1000 Ergebnisse
Sensor 11581: Seite 2, 905 Ergebnisse
Sensor 11574: Seite 1, 1000 Ergebnisse
Sensor 11574: Seite 2, 1000 Ergebnisse
Sensor 11574: Seite 3, 148 Ergebnisse
Sensor 11558: Seite 1, 1000 Ergebnisse
Sensor 11558: Seite 2, 1000 Ergebnisse
Sensor 11558: Seite 3, 88 Ergebnisse
Sensor 11273: Seite 1, 1000 Ergebnisse
Sensor 11273: Seite 2, 904 Ergebnisse
Sensor 11171: Seite 1, 1000 Ergebnisse
Sensor 11171: Seite 2, 752 Ergebnisse
Sensor 11248: Seite 1, 1000 Ergebnisse
Sensor 11248: Seite 2, 576 Ergebnisse
Sensor 11617: Seite 1, 1000 Ergebnisse
Sensor 11617: Seite 2, 563 Ergebnisse
Sensor 11640: Seite 1, 1000 Ergebnisse
Sensor 11640: Seite 2, 461 Ergebnisse
Sensor 11234: Seite 1, 1000 Ergebnisse
Sensor 11234: Seite 2, 457 Ergebnisse
Sensor 11251: Seite 1, 140 Ergebnisse
Sensor 11287: Seite 1, 1000 Ergebnisse
Sensor 11287: Seite 2, 425 Ergebnisse
Sensor 11302: Seite 1, 1000 Ergebnisse
Sensor 11302: Seite 2, 455 Ergebnisse
Sensor 11416: Seite 1, 1000 Ergebnisse
Sensor 11416: Seite 2, 459 Ergebnisse
Sensor 11451: Seite 1, 1000 Ergebnisse
Sensor 11451: Seite 2, 403 Ergebnisse
Sensor 11485: Seite 1, 1000 Ergebnisse
Sensor 11485: Seite 2, 404 Ergebnisse
Sensor 11512: Seite 1, 1000 Ergebnisse
Sensor 11512: Seite 2, 455 Ergebnisse
Sensor 11520: Seite 1, 972 Ergebnisse
Sensor 11526: Seite 1, 1000 Ergebnisse
Sensor 11526: Seite 2, 458 Ergebnisse
Sensor 11563: Seite 1, 1000 Ergebnisse
Sensor 11563: Seite 2, 462 Ergebnisse
Sensor 11618: Seite 1, 1000 Ergebnisse
Sensor 11618: Seite 2, 451 Ergebnisse
Sensor 11600: Seite 1, 1000 Ergebnisse
Sensor 11600: Seite 2, 439 Ergebnisse
Sensor 3219328: Seite 1, 323 Ergebnisse
Sensor 39535: Seite 1, 1000 Ergebnisse
Sensor 39535: Seite 2, 64 Ergebnisse
Sensor 11293: Seite 1, 1000 Ergebnisse
Sensor 11293: Seite 2, 316 Ergebnisse
Sensor 11590: Seite 1, 1000 Ergebnisse
Sensor 11590: Seite 2, 386 Ergebnisse
Sensor 11626: Seite 1, 1000 Ergebnisse
Sensor 11626: Seite 2, 421 Ergebnisse
Sensor 11316: Seite 1, 1000 Ergebnisse
Sensor 11316: Seite 2, 412 Ergebnisse
Sensor 11488: Seite 1, 1000 Ergebnisse
Sensor 11488: Seite 2, 226 Ergebnisse
Sensor 11331: Seite 1, 749 Ergebnisse
Sensor 11151: Seite 1, 523 Ergebnisse
Sensor 11323: Seite 1, 376 Ergebnisse
Sensor 11150: Seite 1, 134 Ergebnisse
Sensor 11283: Seite 1, 134 Ergebnisse
Sensor 11439: Seite 1, 134 Ergebnisse
Sensor 11530: Seite 1, 134 Ergebnisse
Sensor 11534: Seite 1, 134 Ergebnisse
Sensor 7903: Seite 1, 71 Ergebnisse
Sensor 5078757: Seite 1, 961 Ergebnisse
Sensor 5078789: Seite 1, 954 Ergebnisse
Sensor 5078304: Seite 1, 956 Ergebnisse
Sensor 5078390: Seite 1, 962 Ergebnisse
Sensor 5078476: Seite 1, 952 Ergebnisse
Sensor 5078791: Seite 1, 903 Ergebnisse
Sensor 5078977: Seite 1, 962 Ergebnisse
Sensor 5078807: Seite 1, 961 Ergebnisse
Sensor 5078850: Seite 1, 960 Ergebnisse
Sensor 5078856: Seite 1, 962 Ergebnisse
Sensor 5078950: Seite 1, 961 Ergebnisse
Sensor 5078377: Seite 1, 962 Ergebnisse
Sensor 5078756: Seite 1, 961 Ergebnisse
Sensor 5078562: Seite 1, 902 Ergebnisse
Sensor 5078483: Seite 1, 873 Ergebnisse
Sensor 5078370: Seite 1, 396 Ergebnisse
Sensor 5078673: Seite 1, 270 Ergebnisse
Sensor 5078951: Seite 1, 272 Ergebnisse
Sensor 5078666: Seite 1, 273 Ergebnisse
Sensor 5078362: Seite 1, 269 Ergebnisse
Sensor 5078675: Seite 1, 267 Ergebnisse
Sensor 7773945: Seite 1, 697 Ergebnisse
Sensor 7773511: Seite 1, 692 Ergebnisse
Sensor 7773559: Seite 1, 694 Ergebnisse
Sensor 7775512: Seite 1, 697 Ergebnisse
Sensor 7775126: Seite 1, 693 Ergebnisse
Sensor 7775318: Seite 1, 694 Ergebnisse
Sensor 7774314: Seite 1, 693 Ergebnisse
Sensor 7773379: Seite 1, 635 Ergebnisse
Sensor 7772982: Seite 1, 697 Ergebnisse
Sensor 7775029: Seite 1, 694 Ergebnisse
Sensor 7774394: Seite 1, 694 Ergebnisse
Sensor 7774536: Seite 1, 694 Ergebnisse
Sensor 7775129: Seite 1, 693 Ergebnisse
Sensor 7774143: Seite 1, 694 Ergebnisse
Sensor 7775727: Seite 1, 694 Ergebnisse
Sensor 7773022: Seite 1, 635 Ergebnisse
Sensor 7774456: Seite 1, 694 Ergebnisse
Sensor 7773570: Seite 1, 693 Ergebnisse
Sensor 7775746: Seite 1, 694 Ergebnisse
Sensor 7775180: Seite 1, 635 Ergebnisse
Sensor 7773856: Seite 1, 693 Ergebnisse
Sensor 7773418: Seite 1, 694 Ergebnisse
Sensor 7773853: Seite 1, 695 Ergebnisse
Sensor 7774161: Seite 1, 694 Ergebnisse
Sensor 7775160: Seite 1, 694 Ergebnisse
Sensor 7773263: Seite 1, 693 Ergebnisse
Sensor 7775263: Seite 1, 694 Ergebnisse
Sensor 7775395: Seite 1, 694 Ergebnisse
Sensor 7774807: Seite 1, 694 Ergebnisse
Sensor 7774926: Seite 1, 693 Ergebnisse
Sensor 7774397: Seite 1, 693 Ergebnisse
Sensor 7774598: Seite 1, 697 Ergebnisse
Sensor 7773084: Seite 1, 693 Ergebnisse
Sensor 7775442: Seite 1, 694 Ergebnisse
Sensor 7773035: Seite 1, 697 Ergebnisse
Sensor 7773455: Seite 1, 626 Ergebnisse
Sensor 7774073: Seite 1, 635 Ergebnisse
Sensor 7775364: Seite 1, 635 Ergebnisse
Sensor 7775098: Seite 1, 626 Ergebnisse
Sensor 7774088: Seite 1, 694 Ergebnisse
Sensor 7775644: Seite 1, 690 Ergebnisse
Sensor 7774554: Seite 1, 693 Ergebnisse
Sensor 13537108: Seite 1, 169 Ergebnisse
Sensor 7772829: Seite 1, 697 Ergebnisse
Sensor 7777006: Seite 1, 691 Ergebnisse
Sensor 7773187: Seite 1, 697 Ergebnisse
Sensor 7774151: Seite 1, 697 Ergebnisse
Sensor 7773358: Seite 1, 694 Ergebnisse
Sensor 7772953: Seite 1, 694 Ergebnisse
Sensor 7774904: Seite 1, 693 Ergebnisse
Sensor 7773643: Seite 1, 693 Ergebnisse
Sensor 7775493: Seite 1, 694 Ergebnisse
Sensor 7772909: Seite 1, 747 Ergebnisse
Sensor 7773950: Seite 1, 689 Ergebnisse
Sensor 7772769: Seite 1, 277 Ergebnisse
Sensor 7944808: Seite 1, 6 Ergebnisse
Sensor 7944809: Seite 1, 6 Ergebnisse
Sensor 7944819: Seite 1, 6 Ergebnisse
Sensor 9440306: Seite 1, 638 Ergebnisse
Sensor 9440302: Seite 1, 586 Ergebnisse
Sensor 12389003: Seite 1, 250 Ergebnisse
Sensor 11735553: Seite 1, 76 Ergebnisse
Sensor 12384597: Seite 1, 252 Ergebnisse
Sensor 12384598: Seite 1, 346 Ergebnisse
Sensor 12389004: Seite 1, 251 Ergebnisse
Sensor 13388781: Seite 1, 243 Ergebnisse
Sensor 13388779: Seite 1, 243 Ergebnisse
Sensor 14776824: Seite 1, 91 Ergebnisse
Sensor 14781508: Seite 1, 91 Ergebnisse
Sensor 14931944: Seite 1, 75 Ergebnisse
221053

[{'date': '2016-11-18', 'value': 27.857142857142858},
 {'date': '2016-11-19', 'value': 21.071428571428573},
 {'date': '2016-11-20', 'value': 8.142857142857142},
 {'date': '2016-11-21', 'value': 13.0},
 {'date': '2016-11-22', 'value': 14.2},
 {'date': '2016-11-23', 'value': 51.642857142857146},
 {'date': '2016-11-25', 'value': 45.30769230769231},
 {'date': '2016-11-26', 'value': 61.785714285714285},
 {'date': '2016-11-27', 'value': 7.785714285714286},
 {'date': '2016-11-28', 'value': 11.142857142857142},
 {'date': '2016-11-29', 'value': 13.642857142857142},
 {'date': '2016-11-30', 'value': 17.142857142857142},
 {'date': '2016-12-01', 'value': 10.75},
 {'date': '2016-12-02', 'value': 9.6},
 {'date': '2016-12-03', 'value': 14.0},
 {'date': '2016-12-04', 'value': 28.642857142857142},
 {'date': '2016-12-05', 'value': 47.45454545454545},
 {'date': '2016-12-06', 'value': 34.4},
 {'date': '2016-12-07', 'value': 27.357142857142858},
 {'date': '2016-12-10', 'value': 16.375},
 {'date': '2016-12-11', 'value': 12.428571428571429},
 {'date': '2016-12-12', 'value': 7.6},
 {'date': '2017-02-18', 'value': 16.88235294117647},
 {'date': '2017-02-19', 'value': 9.666666666666666},
 {'date': '2017-02-20', 'value': 10.083333333333334},
 {'date': '2017-02-21', 'value': 7.375},
 {'date': '2017-02-22', 'value': 11.0},
 {'date': '2017-02-23', 'value': 7.978260869565218},
 {'date': '2017-02-24', 'value': 7.083333333333333},
 {'date': '2017-02-25', 'value': 7.458333333333333},
 {'date': '2017-02-26', 'value': 9.0},
 {'date': '2017-02-27', 'value': 22.770833333333332},
 {'date': '2017-02-28', 'value': 18.0},
 {'date': '2017-03-01', 'value': 7.395833333333333},
 {'date': '2017-03-02', 'value': 9.041666666666666},
 {'date': '2017-03-03', 'value': 9.833333333333334},
 {'date': '2017-03-04', 'value': 7.916666666666667},
 {'date': '2017-03-05', 'value': 2.8541666666666665},
 {'date': '2017-03-06', 'value': 7.0},
 {'date': '2017-03-07', 'value': 8.833333333333334},
 {'date': '2017-03-08', 'value': 15.895833333333334},
 {'date': '2017-03-09', 'value': 6.166666666666667},
 {'date': '2017-03-10', 'value': 3.966666666666667},
 {'date': '2017-03-12', 'value': 18.428571428571427},
 {'date': '2017-03-13', 'value': 19.416666666666668},
 {'date': '2017-03-14', 'value': 30.708333333333332},
 {'date': '2017-03-15', 'value': 33.708333333333336},
 {'date': '2017-03-16', 'value': 22.041666666666668},
 {'date': '2017-03-17', 'value': 17.375},
 {'date': '2017-03-18', 'value': 7.229166666666667},
 {'date': '2017-03-19', 'value': 3.5},
 {'date': '2017-03-20', 'value': 8.625},
 {'date': '2017-03-21', 'value': 12.791666666666666},
 {'date': '2017-03-22', 'value': 9.270833333333334},
 {'date': '2017-03-23', 'value': 15.979166666666666},
 {'date': '2017-03-24', 'value': 37.0},
 {'date': '2017-03-27', 'value': 16.833333333333332},
 {'date': '2017-03-28', 'value': 8.5},
 {'date': '2017-03-29', 'value': 9.354166666666666},
 {'date': '2017-03-30', 'value': 7.958333333333333},
 {'date': '2017-03-31', 'value': 9.4375},
 {'date': '2017-04-01', 'value': 8.416666666666666},
 {'date': '2017-04-02', 'value': 8.645833333333334},
 {'date': '2017-04-03', 'value': 11.166666666666666},
 {'date': '2017-04-04', 'value': 8.583333333333334},
 {'date': '2017-04-05', 'value': 6.166666666666667},
 {'date': '2017-04-06', 'value': 10.875},
 {'date': '2017-04-07', 'value': 8.729166666666666},
 {'date': '2017-04-08', 'value': 6.375},
 {'date': '2017-04-09', 'value': 9.625},
 {'date': '2017-04-10', 'value': 12.041666666666666},
 {'date': '2017-04-11', 'value': 13.375},
 {'date': '2017-04-12', 'value': 11.5},
 {'date': '2017-04-13', 'value': 13.166666666666666},
 {'date': '2017-04-14', 'value': 8.479166666666666},
 {'date': '2017-04-15', 'value': 9.604166666666666},
 {'date': '2017-04-16', 'value': 6.6875},
 {'date': '2017-04-17', 'value': 5.1875},
 {'date': '2017-04-18', 'value': 6.55},
 {'date': '2017-04-19', 'value': 10.5},
 {'date': '2017-04-20', 'value': 12.979166666666666},
 {'date': '2017-04-21', 'value': 9.145833333333334},
 {'date': '2017-04-22', 'value': 12.708333333333334},
 {'date': '2017-04-23', 'value': 8.75},
 {'date': '2017-04-24', 'value': 8.295454545454545},
 {'date': '2017-04-25', 'value': 10.041666666666666},
 {'date': '2017-04-26', 'value': 11.020833333333334},
 {'date': '2017-04-27', 'value': 7.416666666666667},
 {'date': '2017-04-28', 'value': 5.583333333333333},
 {'date': '2017-04-29', 'value': 4.738095238095238},
 {'date': '2017-05-02', 'value': 9.027777777777779},
 {'date': '2017-05-03', 'value': 15.333333333333334},
 {'date': '2017-05-11', 'value': 16.625},
 {'date': '2017-05-14', 'value': 10.5},
 {'date': '2017-05-15', 'value': 8.386363636363637},
 {'date': '2017-05-16', 'value': 8.583333333333334},
 {'date': '2017-05-17', 'value': 18.423076923076923},
 {'date': '2017-05-18', 'value': 14.75},
 {'date': '2017-05-24', 'value': 10.727272727272727},
 {'date': '2017-05-25', 'value': 12.333333333333334},
 {'date': '2017-05-26', 'value': 12.916666666666666},
 {'date': '2017-05-27', 'value': 9.875},
 {'date': '2017-05-28', 'value': 9.8125},
 {'date': '2017-05-29', 'value': 8.875},
 {'date': '2017-05-30', 'value': 13.125},
 {'date': '2017-05-31', 'value': 10.452380952380953},
 {'date': '2017-06-01', 'value': 10.76086956521739},
 {'date': '2017-06-02', 'value': 9.25},
 {'date': '2017-06-03', 'value': 7.25},
 {'date': '2017-06-04', 'value': 6.875},
 {'date': '2017-06-05', 'value': 4.520833333333333},
 {'date': '2017-06-06', 'value': 8.520833333333334},
 {'date': '2017-06-07', 'value': 4.3125},
 {'date': '2017-06-08', 'value': 7.041666666666667},
 {'date': '2017-06-09', 'value': 7.1875},
 {'date': '2017-06-10', 'value': 4.958333333333333},
 {'date': '2017-06-11', 'value': 4.75},
 {'date': '2017-06-12', 'value': 10.791666666666666},
 {'date': '2017-06-13', 'value': 9.125},
 {'date': '2017-06-14', 'value': 11.5},
 {'date': '2017-06-15', 'value': 8.208333333333334},
 {'date': '2017-06-16', 'value': 9.875},
 {'date': '2017-06-17', 'value': 7.854166666666667},
 {'date': '2017-06-18', 'value': 5.083333333333333},
 {'date': '2017-06-19', 'value': 7.75},
 {'date': '2017-06-20', 'value': 14.708333333333334},
 {'date': '2017-06-21', 'value': 15.083333333333334},
 {'date': '2017-06-22', 'value': 32.25},
 {'date': '2017-06-23', 'value': 14.409090909090908},
 {'date': '2017-06-24', 'value': 16.88095238095238},
 {'date': '2017-06-25', 'value': 19.4},
 {'date': '2017-06-26', 'value': 13.166666666666666},
 {'date': '2017-06-27', 'value': 17.4375},
 {'date': '2017-06-28', 'value': 17.886363636363637},
 {'date': '2017-06-29', 'value': 3.0416666666666665},
 {'date': '2017-06-30', 'value': 2.3541666666666665},
 {'date': '2017-07-01', 'value': 2.0952380952380953},
 {'date': '2017-07-02', 'value': 1.7272727272727273},
 {'date': '2017-07-03', 'value': 4.690476190476191},
 {'date': '2017-07-04', 'value': 6.21875},
 {'date': '2017-07-05', 'value': 10.65},
 {'date': '2017-07-06', 'value': 9.880952380952381},
 {'date': '2017-07-07', 'value': 21.68421052631579},
 {'date': '2017-07-08', 'value': 6.976190476190476},
 {'date': '2017-07-09', 'value': 11.0},
 {'date': '2017-07-10', 'value': 11.976190476190476},
 {'date': '2017-07-11', 'value': 2.5277777777777777},
 {'date': '2017-07-12', 'value': 7.444444444444445},
 {'date': '2017-07-13', 'value': 2.8333333333333335},
 {'date': '2017-07-14', 'value': 9.642857142857142},
 {'date': '2017-07-15', 'value': 2.625},
 {'date': '2017-07-16', 'value': 4.9375},
 {'date': '2017-07-17', 'value': 7.604166666666667},
 {'date': '2017-07-18', 'value': 11.80952380952381},
 {'date': '2017-07-19', 'value': 10.595238095238095},
 {'date': '2017-07-20', 'value': 8.7},
 {'date': '2020-03-16', 'value': 24.875},
 {'date': '2020-03-17', 'value': 26.26086956521739},
 {'date': '2020-03-18', 'value': 17.695652173913043},
 {'date': '2020-03-19', 'value': 23.23913043478261},
 {'date': '2020-03-20', 'value': 28.795454545454547},
 {'date': '2020-03-21', 'value': 16.90909090909091},
 {'date': '2020-03-22', 'value': 5.605263157894737},
 {'date': '2020-03-23', 'value': 20.0},
 {'date': '2020-03-24', 'value': 22.73913043478261},
 {'date': '2020-03-25', 'value': 21.652173913043477},
 {'date': '2020-03-26', 'value': 26.73913043478261},
 {'date': '2020-03-27', 'value': 56.90909090909091},
 {'date': '2020-03-28', 'value': 49.41304347826087},
 {'date': '2020-03-29', 'value': 36.27272727272727},
 {'date': '2020-03-30', 'value': 6.956521739130435},
 {'date': '2020-03-31', 'value': 10.318181818181818},
 {'date': '2020-04-01', 'value': 13.565217391304348},
 {'date': '2020-04-02', 'value': 16.565217391304348},
 {'date': '2020-04-03', 'value': 18.045454545454547},
 {'date': '2020-04-04', 'value': 19.108695652173914},
 {'date': '2020-04-05', 'value': 18.282608695652176},
 {'date': '2020-04-06', 'value': 25.431818181818183},
 {'date': '2020-04-07', 'value': 28.25},
 {'date': '2020-04-08', 'value': 16.476190476190474},
 {'date': '2020-04-09', 'value': 20.73913043478261},
 {'date': '2020-04-10', 'value': 17.304347826086957},
 {'date': '2020-04-11', 'value': 15.363636363636363},
 {'date': '2020-04-12', 'value': 15.347826086956522},
 {'date': '2020-04-13', 'value': 10.978260869565217},
 {'date': '2020-04-14', 'value': 8.869565217391305},
 {'date': '2020-04-15', 'value': 10.195652173913043},
 {'date': '2020-04-16', 'value': 16.0},
 {'date': '2020-04-17', 'value': 18.58695652173913},
 {'date': '2020-04-18', 'value': 22.934782608695652},
 {'date': '2020-04-19', 'value': 17.847826086956523},
 {'date': '2020-04-20', 'value': 16.717391304347824},
 {'date': '2020-04-21', 'value': 14.782608695652174},
 {'date': '2020-04-22', 'value': 15.113636363636363},
 {'date': '2020-04-23', 'value': 17.75},
 {'date': '2020-04-24', 'value': 18.636363636363637},
 {'date': '2020-04-25', 'value': 12.0},
 {'date': '2020-04-26', 'value': 10.095238095238095},
 {'date': '2020-04-27', 'value': 16.3},
 {'date': '2020-04-28', 'value': 14.833333333333334},
 {'date': '2020-04-29', 'value': 5.433333333333334},
 {'date': '2020-04-30', 'value': 4.659090909090909},
 {'date': '2020-05-01', 'value': 2.8181818181818183},
 {'date': '2020-05-02', 'value': 3.1666666666666665},
 {'date': '2020-05-03', 'value': 4.642857142857143},
 {'date': '2020-05-04', 'value': 7.131578947368421},
 {'date': '2020-05-05', 'value': 8.318181818181818},
 {'date': '2020-05-06', 'value': 6.565217391304348},
 {'date': '2020-05-07', 'value': 6.5},
 {'date': '2020-05-08', 'value': 15.264705882352942},
 {'date': '2020-05-09', 'value': 15.175},
 {'date': '2020-05-10', 'value': 16.97826086956522},
 {'date': '2020-05-11', 'value': 14.869565217391305},
 {'date': '2020-05-12', 'value': 3.090909090909091},
 {'date': '2020-05-13', 'value': 16.8},
 {'date': '2020-05-14', 'value': 11.416666666666666},
 {'date': '2020-05-15', 'value': 12.15},
 {'date': '2020-05-16', 'value': 11.842105263157896},
 {'date': '2020-05-17', 'value': 15.886363636363637},
 {'date': '2020-05-18', 'value': 17.043478260869566},
 {'date': '2020-05-19', 'value': 19.1},
 {'date': '2020-05-20', 'value': 14.973684210526315},
 {'date': '2020-05-21', 'value': 11.275},
 {'date': '2020-05-22', 'value': 14.931818181818182},
 {'date': '2020-05-23', 'value': 13.725},
 {'date': '2020-05-24', 'value': 5.738095238095238},
 {'date': '2020-05-25', 'value': 5.659090909090909},
 {'date': '2020-05-26', 'value': 5.386363636363637},
 {'date': '2020-05-27', 'value': 8.6},
 {'date': '2020-05-28', 'value': 4.285714285714286},
 {'date': '2020-05-29', 'value': 9.305555555555555},
 {'date': '2020-05-31', 'value': 1.5},
 {'date': '2020-06-01', 'value': 11.175},
 {'date': '2020-06-02', 'value': 11.40625},
 {'date': '2020-06-03', 'value': 7.823529411764706},
 {'date': '2020-06-04', 'value': 10.5},
 {'date': '2020-06-05', 'value': 4.894736842105263},
 {'date': '2020-06-07', 'value': 5.7},
 {'date': '2020-06-08', 'value': 5.368421052631579},
 {'date': '2020-06-09', 'value': 12.0},
 {'date': '2020-06-10', 'value': 12.30952380952381},
 {'date': '2020-06-11', 'value': 7.818181818181818},
 {'date': '2020-06-12', 'value': 12.392857142857142},
 {'date': '2020-06-13', 'value': 15.428571428571429},
 {'date': '2020-06-14', 'value': 10.078947368421053},
 {'date': '2020-06-15', 'value': 2.7},
 {'date': '2020-06-16', 'value': 11.333333333333334},
 {'date': '2020-06-17', 'value': 20.0},
 {'date': '2020-06-18', 'value': 6.794117647058823},
 {'date': '2020-06-19', 'value': 6.315789473684211},
 {'date': '2020-06-20', 'value': 5.136363636363637},
 {'date': '2020-06-21', 'value': 4.15625},
 {'date': '2020-06-22', 'value': 12.8},
 {'date': '2020-06-23', 'value': 13.31578947368421},
 {'date': '2020-06-24', 'value': 12.029411764705882},
 {'date': '2020-06-25', 'value': 8.428571428571429},
 {'date': '2020-06-26', 'value': 11.133333333333333},
 {'date': '2020-06-27', 'value': 14.192307692307692},
 {'date': '2020-06-28', 'value': 13.0},
 {'date': '2020-06-29', 'value': 9.476190476190476},
 {'date': '2020-06-30', 'value': 7.954545454545454},
 {'date': '2020-07-01', 'value': 11.416666666666666},
 {'date': '2020-07-02', 'value': 9.03125},
 {'date': '2020-07-04', 'value': 11.61111111111111},
 {'date': '2020-07-05', 'value': 11.68421052631579},
 {'date': '2020-07-06', 'value': 15.25},
 {'date': '2020-07-07', 'value': 10.7},
 {'date': '2020-07-08', 'value': 11.710526315789474},
 {'date': '2020-07-09', 'value': 14.91304347826087},
 {'date': '2020-07-10', 'value': 18.075},
 {'date': '2020-07-11', 'value': 4.714285714285714},
 {'date': '2020-07-12', 'value': 8.13888888888889},
 {'date': '2020-07-13', 'value': 14.833333333333334},
 {'date': '2020-07-14', 'value': 14.934782608695652},
 {'date': '2020-07-15', 'value': 14.272727272727273},
 {'date': '2020-07-16', 'value': 7.476190476190476},
 {'date': '2020-07-17', 'value': 6.956521739130435},
 {'date': '2020-07-18', 'value': 4.809523809523809},
 {'date': '2020-07-19', 'value': 7.6},
 {'date': '2020-07-20', 'value': 12.357142857142858},
 {'date': '2020-07-21', 'value': 18.5},
 {'date': '2020-07-22', 'value': 16.775},
 {'date': '2020-07-23', 'value': 18.42105263157895},
 {'date': '2020-07-24', 'value': 15.543478260869565},
 {'date': '2020-07-25', 'value': 13.318181818181818},
 {'date': '2020-07-26', 'value': 12.880952380952381},
 {'date': '2020-07-27', 'value': 8.956521739130435},
 {'date': '2020-07-28', 'value': 15.264705882352942},
 {'date': '2020-07-29', 'value': 13.277777777777779},
 {'date': '2020-07-30', 'value': 14.956521739130435},
 {'date': '2020-07-31', 'value': 19.425},
 {'date': '2020-08-01', 'value': 19.964285714285715},
 {'date': '2020-08-02', 'value': 17.282608695652176},
 {'date': '2020-08-03', 'value': 13.763157894736842},
 {'date': '2020-08-04', 'value': 7.826086956521739},
 {'date': '2020-08-05', 'value': 3.0},
 {'date': '2020-08-06', 'value': 14.023809523809524},
 {'date': '2020-08-07', 'value': 21.47222222222222},
 {'date': '2020-08-08', 'value': 24.613636363636363},
 {'date': '2020-08-09', 'value': 25.0},
 {'date': '2020-08-10', 'value': 23.15909090909091},
 {'date': '2020-08-11', 'value': 23.0},
 {'date': '2020-08-12', 'value': 14.75},
 {'date': '2020-08-13', 'value': 18.055555555555557},
 {'date': '2020-08-17', 'value': 19.555555555555557},
 {'date': '2020-08-18', 'value': 8.595238095238095},
 {'date': '2020-08-19', 'value': 6.456521739130435},
 {'date': '2020-08-20', 'value': 8.477272727272727},
 {'date': '2020-08-21', 'value': 12.727272727272727},
 {'date': '2020-08-22', 'value': 14.375},
 {'date': '2020-08-23', 'value': 5.921052631578948},
 {'date': '2020-08-24', 'value': 7.826086956521739},
 {'date': '2020-08-25', 'value': 10.0},
 {'date': '2020-08-26', 'value': 10.065217391304348},
 {'date': '2020-08-27', 'value': 14.894736842105264},
 {'date': '2020-08-28', 'value': 15.434782608695652},
 {'date': '2020-08-29', 'value': 9.428571428571429},
 {'date': '2020-08-30', 'value': 12.840909090909092},
 {'date': '2020-08-31', 'value': 4.386363636363637},
 {'date': '2020-09-01', 'value': 4.3478260869565215},
 {'date': '2020-09-02', 'value': 7.931818181818182},
 {'date': '2020-09-03', 'value': 6.7272727272727275},
 {'date': '2020-09-04', 'value': 6.5},
 {'date': '2020-09-05', 'value': 10.5},
 {'date': '2020-09-06', 'value': 8.166666666666666},
 {'date': '2020-09-07', 'value': 10.431818181818182},
 {'date': '2020-09-08', 'value': 9.717391304347826},
 {'date': '2020-09-09', 'value': 12.973684210526315},
 {'date': '2020-09-10', 'value': 17.55},
 {'date': '2020-09-11', 'value': 20.607142857142858},
 {'date': '2020-09-12', 'value': 23.36842105263158},
 {'date': '2020-09-13', 'value': 18.55},
 {'date': '2020-09-14', 'value': 16.571428571428573},
 {'date': '2020-09-17', 'value': 18.071428571428573},
 {'date': '2020-09-18', 'value': 8.088235294117647},
 {'date': '2020-09-19', 'value': 6.818181818181818},
 {'date': '2020-09-20', 'value': 9.785714285714286},
 {'date': '2020-09-21', 'value': 21.789473684210527},
 {'date': '2020-09-22', 'value': 28.47826086956522},
 {'date': '2020-09-23', 'value': 19.227272727272727},
 {'date': '2020-09-24', 'value': 9.76086956521739},
 {'date': '2020-09-25', 'value': 6.095238095238095},
 {'date': '2020-09-26', 'value': 2.2142857142857144},
 {'date': '2020-09-27', 'value': 3.3260869565217392},
 {'date': '2020-09-28', 'value': 5.55},
 {'date': '2020-09-29', 'value': 4.454545454545454},
 {'date': '2020-09-30', 'value': 8.23913043478261},
 {'date': '2020-10-01', 'value': 11.977272727272727},
 {'date': '2020-10-02', 'value': 13.386363636363637},
 {'date': '2020-10-03', 'value': 12.136363636363637},
 {'date': '2020-10-04', 'value': 5.25},
 {'date': '2020-10-05', 'value': 6.642857142857143},
 {'date': '2020-10-06', 'value': 8.782608695652174},
 {'date': '2020-10-07', 'value': 5.695652173913044},
 {'date': '2020-10-08', 'value': 6.136363636363637},
 {'date': '2020-10-09', 'value': 9.25},
 {'date': '2020-10-10', 'value': 10.204545454545455},
 {'date': '2020-10-11', 'value': 4.5},
 {'date': '2020-10-12', 'value': 8.23076923076923},
 {'date': '2020-10-13', 'value': 6.586956521739131},
 {'date': '2020-10-14', 'value': 4.852941176470588},
 {'date': '2020-10-15', 'value': 9.068181818181818},
 {'date': '2020-10-16', 'value': 10.866666666666667},
 {'date': '2020-10-18', 'value': 8.541666666666666},
 {'date': '2020-10-19', 'value': 14.08695652173913},
 {'date': '2020-10-20', 'value': 19.477272727272727},
 {'date': '2020-10-21', 'value': 30.152173913043477},
 {'date': '2020-10-22', 'value': 30.369565217391305},
 {'date': '2020-10-23', 'value': 30.956521739130434},
 {'date': '2020-10-24', 'value': 15.921052631578947},
 {'date': '2020-10-25', 'value': 15.891304347826088},
 {'date': '2020-10-26', 'value': 12.789473684210526},
 {'date': '2020-10-27', 'value': 9.526315789473685},
 {'date': '2020-10-28', 'value': 11.30952380952381},
 {'date': '2020-10-29', 'value': 6.823529411764706},
 {'date': '2020-10-30', 'value': 5.136363636363637},
 {'date': '2020-10-31', 'value': 7.944444444444445},
 {'date': '2020-11-01', 'value': 18.630434782608695},
 {'date': '2020-11-02', 'value': 21.195652173913043},
 {'date': '2020-11-03', 'value': 10.5},
 {'date': '2020-11-04', 'value': 9.795454545454545},
 {'date': '2020-11-05', 'value': 16.666666666666668},
 {'date': '2020-11-06', 'value': 19.214285714285715},
 {'date': '2020-11-07', 'value': 20.91176470588235},
 {'date': '2020-11-08', 'value': 25.805555555555557},
 {'date': '2020-11-09', 'value': 28.666666666666668},
 {'date': '2020-11-10', 'value': 18.08695652173913},
 {'date': '2020-11-11', 'value': 16.391304347826086},
 {'date': '2020-11-12', 'value': 15.347826086956522},
 {'date': '2020-11-13', 'value': 22.23913043478261},
 {'date': '2020-11-14', 'value': 22.058823529411764},
 {'date': '2020-11-15', 'value': 14.347826086956522},
 {'date': '2020-11-16', 'value': 17.63157894736842},
 {'date': '2020-11-17', 'value': 7.235294117647059},
 {'date': '2020-11-18', 'value': 13.947368421052632},
 {'date': '2020-11-19', 'value': 16.65},
 {'date': '2020-11-20', 'value': 8.25},
 {'date': '2020-11-21', 'value': 12.18421052631579},
 {'date': '2020-11-22', 'value': 16.678571428571427},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [7]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_pm10_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_pm10_mean
0    2016-11-18         24.076117
1    2016-11-19         17.638023
2    2016-11-20         10.274396
3    2016-11-21         19.452890
4    2016-11-22         23.753865
...         ...               ...
2223 2026-02-24          8.020619
2224 2026-02-25         13.725568
2225 2026-02-26         18.305548
2226 2026-02-27         19.779004
2227 2026-02-28         19.852625

[2228 rows x 2 columns]

### Convert dataframe to csv

In [8]:
france_daily[["date", "france_pm10_mean"]].to_csv(
    "daily_avg_austria_PM10.csv",
    index=False
)

# PM2.5

### Get 200 stations located in France that measure PM2.5
Stations are sorted descending by the duration of their measurements

In [7]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "AT",   # only consider stations located in France
    "parameters_id": 2,   # PM2.5
    #"monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm25 = df_sorted

df_top_pm25

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
5,2764,Grünbach bei Freistadt,4264 Grünbach,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274395, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.53110999980738, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.574722000058197, 48.53110999980738, 14.574...",None,2016-11-18 05:00:00+00:00,2026-03-06 09:00:00+00:00
6,2766,Liezen Pyhrnbach,8940 Liezen,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274806, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.56543899973233, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.244675999684107, 47.56543899973233, 14.244...",None,2016-11-18 05:00:00+00:00,2026-03-06 09:00:00+00:00
8,2812,A23 Südosttangente/Wehlistraße,1020 Wien,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5877, 'name': 'co µg/m³', 'parameter':...","{'latitude': 48.203060000058315, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.43454999985093, 48.203060000058315, 16.434...",None,2016-11-18 05:00:00+00:00,2026-03-06 09:00:00+00:00
12,2835,Weiz Bahnhofstraße,8160 Weiz,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275103, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.21570299990339, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.628392000380256, 47.21570299990339, 15.628...",None,2016-11-18 05:00:00+00:00,2026-03-06 09:00:00+00:00
14,2838,Leibnitz Lastenstraße,8430 Leibnitz,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5930, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 46.778333000184496, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.540556000320228, 46.778333000184496, 15.54...",None,2016-11-18 05:00:00+00:00,2026-03-06 09:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,276145,Leitendorf,NaN,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 1575646, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 47.369478343, 'longitude': 15.093...",None,"[15.093262866, 47.369478343, 15.093262866, 47....",None,NaT,NaT
77,276352,Laim lang,NaN,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 1576543, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 47.081206742, 'longitude': 15.435...",None,"[15.435399413, 47.081206742, 15.435399413, 47....",None,NaT,NaT
78,276621,Pachern Hauptstraße,NaN,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 1577827, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 47.057023455, 'longitude': 15.531...",None,"[15.531330965, 47.057023455, 15.531330965, 47....",None,NaT,NaT
79,276660,Kollmannsberg,NaN,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 1577966, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 47.858331533, 'longitude': 13.728...",None,"[13.728836216, 47.858331533, 13.728836216, 47....",None,NaT,NaT
80,440353,"09.30 Vormittag, Heizen",NaN,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 2465290, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 46.796130975, 'longitude': 15.900...",None,"[15.900985301, 46.796130975, 15.900985301, 46....",None,NaT,NaT

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [8]:
rows = []

for _, station in df_top_pm25.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM25 behalten
        if sensor["parameter"]["id"] == 2:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm25_sensors = pd.DataFrame(rows)

df_pm25_sensors

     station_id                    station_name  sensor_id sensor_name
0          2764          Grünbach bei Freistadt      30241  pm25 µg/m³
1          2766                Liezen Pyhrnbach   15043411  pm25 µg/m³
2          2812  A23 Südosttangente/Wehlistraße      30223  pm25 µg/m³
3          2835              Weiz Bahnhofstraße      30228  pm25 µg/m³
4          2838           Leibnitz Lastenstraße      30226  pm25 µg/m³
..          ...                             ...        ...         ...
164      276145                      Leitendorf    1575646  pm25 µg/m³
165      276352                       Laim lang    1576543  pm25 µg/m³
166      276621             Pachern Hauptstraße    1577827  pm25 µg/m³
167      276660                   Kollmannsberg    1577966  pm25 µg/m³
168      440353         09.30 Vormittag, Heizen    2465290  pm25 µg/m³

[169 rows x 4 columns]

In [9]:
sensor_ids = df_pm25_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

169

[30241,
 15043411,
 30223,
 30228,
 30226,
 30237,
 9445118,
 8613702,
 1562413,
 1965763,
 30235,
 30234,
 30231,
 24025,
 30238,
 30331,
 24071,
 6728726,
 1965764,
 30273,
 30313,
 7796983,
 15043409,
 30303,
 30217,
 2014768,
 30321,
 7796982,
 2088963,
 30309,
 8690007,
 30229,
 15043406,
 30219,
 30215,
 11223021,
 30214,
 2088966,
 1562197,
 15043413,
 7796984,
 30221,
 15043410,
 30212,
 30224,
 15043416,
 30232,
 30213,
 39527,
 30246,
 30239,
 30284,
 30222,
 39536,
 30233,
 24023,
 30281,
 30220,
 6460103,
 2762797,
 5078837,
 5078426,
 5078979,
 5078933,
 5078862,
 15043415,
 5078429,
 5078873,
 15043404,
 5078934,
 5078944,
 5078650,
 5078848,
 6732640,
 6894351,
 7155812,
 7663957,
 12389006,
 7775007,
 7773404,
 7773629,
 7775075,
 7774837,
 7776018,
 7772993,
 7775582,
 7774568,
 8613539,
 7773284,
 7773613,
 7773884,
 7773925,
 7774250,
 7773224,
 7775236,
 7773764,
 7773654,
 7772944,
 7775567,
 7774927,
 11223024,
 11223022,
 11626094,
 11857173,
 11626095,
 15043405,
 7775208,
 15043407,
 15043414,
 7775436,
 7773111,
 7774752,
 7773988,
 7773577,
 7773287,
 11223023,
 7944828,
 7944832,
 7944798,
 8872434,
 9060045,
 9299644,
 9440303,
 9721536,
 10148413,
 10317752,
 10396469,
 10409040,
 10989381,
 11202963,
 11221382,
 11258203,
 11473410,
 15043412,
 11735552,
 11983215,
 12178320,
 12178356,
 12384600,
 14781506,
 12464444,
 13388775,
 14086667,
 14152525,
 14153393,
 14243588,
 14359881,
 14493109,
 14671560,
 14729626,
 14753090,
 14781504,
 14931946,
 14942040,
 15093318,
 15384944,
 15416331,
 15435508,
 15561288,
 15595460,
 42881,
 42908,
 42937,
 1562469,
 1575646,
 1576543,
 1577827,
 1577966,
 2465290]

### Get daily, average values from each sensor/station for 2016-2026

In [10]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 30241: Seite 1, 1000 Ergebnisse
Sensor 30241: Seite 2, 1000 Ergebnisse
Sensor 30241: Seite 3, 8 Ergebnisse
Sensor 15043411: Seite 1, 59 Ergebnisse
Sensor 30223: Seite 1, 1000 Ergebnisse
Sensor 30223: Seite 2, 1000 Ergebnisse
Sensor 30223: Seite 3, 10 Ergebnisse
Sensor 30228: Seite 1, 1000 Ergebnisse
Sensor 30228: Seite 2, 1000 Ergebnisse
Sensor 30228: Seite 3, 11 Ergebnisse
Sensor 30226: Seite 1, 1000 Ergebnisse
Sensor 30226: Seite 2, 1000 Ergebnisse
Sensor 30226: Seite 3, 5 Ergebnisse
Sensor 30237: Seite 1, 1000 Ergebnisse
Sensor 30237: Seite 2, 1000 Ergebnisse
Sensor 30237: Seite 3, 11 Ergebnisse
Sensor 9445118: Seite 1, 586 Ergebnisse
Sensor 8613702: Seite 1, 582 Ergebnisse
Sensor 1562413: Seite 1, 1000 Ergebnisse
Sensor 1562413: Seite 2, 309 Ergebnisse
Sensor 1965763: Seite 1, 467 Ergebnisse
Sensor 30235: Seite 1, 1000 Ergebnisse
Sensor 30235: Seite 2, 320 Ergebnisse
Sensor 30234: Seite 1, 1000 Ergebnisse
Sensor 30234: Seite 2, 325 Ergebnisse
Sensor 30231: Seite 1, 1000 Ergebnisse
Sensor 30231: Seite 2, 322 Ergebnisse
Sensor 24025: Seite 1, 1000 Ergebnisse
Sensor 24025: Seite 2, 321 Ergebnisse
Sensor 30238: Seite 1, 1000 Ergebnisse
Sensor 30238: Seite 2, 322 Ergebnisse
Sensor 30331: Seite 1, 1000 Ergebnisse
Sensor 30331: Seite 2, 296 Ergebnisse
Sensor 24071: Seite 1, 1000 Ergebnisse
Sensor 24071: Seite 2, 323 Ergebnisse
Sensor 6728726: Seite 1, 172 Ergebnisse
Sensor 1965764: Seite 1, 469 Ergebnisse
Sensor 30273: Seite 1, 1000 Ergebnisse
Sensor 30273: Seite 2, 320 Ergebnisse
Sensor 30313: Seite 1, 1000 Ergebnisse
Sensor 30313: Seite 2, 295 Ergebnisse
Sensor 7796983: Seite 1, 692 Ergebnisse
Sensor 15043409: Seite 1, 60 Ergebnisse
Sensor 30303: Seite 1, 1000 Ergebnisse
Sensor 30303: Seite 2, 958 Ergebnisse
Sensor 30217: Seite 1, 1000 Ergebnisse
Sensor 30217: Seite 2, 945 Ergebnisse
Sensor 2014768: Seite 1, 1000 Ergebnisse
Sensor 2014768: Seite 2, 198 Ergebnisse
Sensor 30321: Seite 1, 1000 Ergebnisse
Sensor 30321: Seite 2, 1000 Ergebnisse
Sensor 30321: Seite 3, 3 Ergebnisse
Sensor 7796982: Seite 1, 692 Ergebnisse
Sensor 2088963: Seite 1, 208 Ergebnisse
Sensor 30309: Seite 1, 1000 Ergebnisse
Sensor 30309: Seite 2, 282 Ergebnisse
Sensor 8690007: Seite 1, 572 Ergebnisse
Sensor 30229: Seite 1, 1000 Ergebnisse
Sensor 30229: Seite 2, 943 Ergebnisse
Sensor 15043406: Seite 1, 59 Ergebnisse
Sensor 30219: Seite 1, 1000 Ergebnisse
Sensor 30219: Seite 2, 1000 Ergebnisse
Sensor 30219: Seite 3, 11 Ergebnisse
Sensor 30215: Seite 1, 1000 Ergebnisse
Sensor 30215: Seite 2, 1000 Ergebnisse
Sensor 30215: Seite 3, 11 Ergebnisse
Sensor 11223021: Seite 1, 465 Ergebnisse
Sensor 30214: Seite 1, 1000 Ergebnisse
Sensor 30214: Seite 2, 1000 Ergebnisse
Sensor 30214: Seite 3, 12 Ergebnisse
Sensor 2088966: Seite 1, 205 Ergebnisse
Sensor 1562197: Seite 1, 1000 Ergebnisse
Sensor 1562197: Seite 2, 299 Ergebnisse
Sensor 15043413: Seite 1, 60 Ergebnisse
Sensor 7796984: Seite 1, 692 Ergebnisse
Sensor 30221: Seite 1, 1000 Ergebnisse
Sensor 30221: Seite 2, 1000 Ergebnisse
Sensor 30221: Seite 3, 13 Ergebnisse
Sensor 15043410: Seite 1, 60 Ergebnisse
Sensor 30212: Seite 1, 1000 Ergebnisse
Sensor 30212: Seite 2, 1000 Ergebnisse
Sensor 30212: Seite 3, 13 Ergebnisse
Sensor 30224: Seite 1, 1000 Ergebnisse
Sensor 30224: Seite 2, 770 Ergebnisse
Sensor 15043416: Seite 1, 60 Ergebnisse
Sensor 30232: Seite 1, 1000 Ergebnisse
Sensor 30232: Seite 2, 769 Ergebnisse
Sensor 30213: Seite 1, 1000 Ergebnisse
Sensor 30213: Seite 2, 428 Ergebnisse
Sensor 39527: Seite 1, 1000 Ergebnisse
Sensor 39527: Seite 2, 73 Ergebnisse
Sensor 30246: Seite 1, 1000 Ergebnisse
Sensor 30246: Seite 2, 321 Ergebnisse
Sensor 30239: Seite 1, 1000 Ergebnisse
Sensor 30239: Seite 2, 319 Ergebnisse
Sensor 30284: Seite 1, 1000 Ergebnisse
Sensor 30284: Seite 2, 267 Ergebnisse
Sensor 30222: Seite 1, 1000 Ergebnisse
Sensor 30222: Seite 2, 322 Ergebnisse
Sensor 39536: Seite 1, 1000 Ergebnisse
Sensor 39536: Seite 2, 74 Ergebnisse
Sensor 30233: Seite 1, 1000 Ergebnisse
Sensor 30233: Seite 2, 303 Ergebnisse
Sensor 24023: Seite 1, 1000 Ergebnisse
Sensor 24023: Seite 2, 318 Ergebnisse
Sensor 30281: Seite 1, 1000 Ergebnisse
Sensor 30281: Seite 2, 310 Ergebnisse
Sensor 30220: Seite 1, 1000 Ergebnisse
Sensor 30220: Seite 2, 287 Ergebnisse
Sensor 6460103: Seite 1, 166 Ergebnisse
Sensor 2762797: Seite 1, 1 Ergebnisse
Sensor 5078837: Seite 1, 962 Ergebnisse
Sensor 5078426: Seite 1, 87 Ergebnisse
Sensor 5078979: Seite 1, 956 Ergebnisse
Sensor 5078933: Seite 1, 962 Ergebnisse
Sensor 5078862: Seite 1, 921 Ergebnisse
Sensor 15043415: Seite 1, 60 Ergebnisse
Sensor 5078429: Seite 1, 962 Ergebnisse
Sensor 5078873: Seite 1, 961 Ergebnisse
Sensor 15043404: Seite 1, 59 Ergebnisse
Sensor 5078934: Seite 1, 87 Ergebnisse
Sensor 5078944: Seite 1, 962 Ergebnisse
Sensor 5078650: Seite 1, 270 Ergebnisse
Sensor 5078848: Seite 1, 267 Ergebnisse
Sensor 6732640: Seite 1, 868 Ergebnisse
Sensor 6894351: Seite 1, 879 Ergebnisse
Sensor 7155812: Seite 1, 190 Ergebnisse
Sensor 7663957: Seite 1, 727 Ergebnisse
Sensor 12389006: Seite 1, 251 Ergebnisse
Sensor 7775007: Seite 1, 694 Ergebnisse
Sensor 7773404: Seite 1, 693 Ergebnisse
Sensor 7773629: Seite 1, 638 Ergebnisse
Sensor 7775075: Seite 1, 694 Ergebnisse
Sensor 7774837: Seite 1, 697 Ergebnisse
Sensor 7776018: Seite 1, 693 Ergebnisse
Sensor 7772993: Seite 1, 697 Ergebnisse
Sensor 7775582: Seite 1, 694 Ergebnisse
Sensor 7774568: Seite 1, 697 Ergebnisse
Sensor 8613539: Seite 1, 522 Ergebnisse
Sensor 7773284: Seite 1, 693 Ergebnisse
Sensor 7773613: Seite 1, 694 Ergebnisse
Sensor 7773884: Seite 1, 694 Ergebnisse
Sensor 7773925: Seite 1, 696 Ergebnisse
Sensor 7774250: Seite 1, 695 Ergebnisse
Sensor 7773224: Seite 1, 694 Ergebnisse
Sensor 7775236: Seite 1, 694 Ergebnisse
Sensor 7773764: Seite 1, 693 Ergebnisse
Sensor 7773654: Seite 1, 694 Ergebnisse
Sensor 7772944: Seite 1, 694 Ergebnisse
Sensor 7775567: Seite 1, 694 Ergebnisse
Sensor 7774927: Seite 1, 694 Ergebnisse
Sensor 11223024: Seite 1, 465 Ergebnisse
Sensor 11223022: Seite 1, 465 Ergebnisse
Sensor 11626094: Seite 1, 429 Ergebnisse
Sensor 11857173: Seite 1, 312 Ergebnisse
Sensor 11626095: Seite 1, 429 Ergebnisse
Sensor 15043405: Seite 1, 60 Ergebnisse
Sensor 7775208: Seite 1, 623 Ergebnisse
Sensor 15043407: Seite 1, 59 Ergebnisse
Sensor 15043414: Seite 1, 60 Ergebnisse
Sensor 7775436: Seite 1, 696 Ergebnisse
Sensor 7773111: Seite 1, 694 Ergebnisse
Sensor 7774752: Seite 1, 693 Ergebnisse
Sensor 7773988: Seite 1, 693 Ergebnisse
Sensor 7773577: Seite 1, 697 Ergebnisse
Sensor 7773287: Seite 1, 747 Ergebnisse
Sensor 11223023: Seite 1, 48 Ergebnisse
Sensor 7944828: Seite 1, 6 Ergebnisse
Sensor 7944832: Seite 1, 2 Ergebnisse
Sensor 7944798: Seite 1, 6 Ergebnisse
Sensor 8872434: Seite 1, 17 Ergebnisse
Sensor 9060045: Seite 1, 8 Ergebnisse
Sensor 9299644: Seite 1, 622 Ergebnisse
Sensor 9440303: Seite 1, 585 Ergebnisse
Sensor 9721536: Seite 1, 487 Ergebnisse
Sensor 10148413: Seite 1, 545 Ergebnisse
Sensor 10317752: Seite 1, 530 Ergebnisse
Sensor 10396469: Seite 1, 490 Ergebnisse
Sensor 10409040: Seite 1, 4 Ergebnisse
Sensor 10989381: Seite 1, 466 Ergebnisse
Sensor 11202963: Seite 1, 389 Ergebnisse
Sensor 11221382: Seite 1, 451 Ergebnisse
Sensor 11258203: Seite 1, 448 Ergebnisse
Sensor 11473410: Seite 1, 429 Ergebnisse
Sensor 15043412: Seite 1, 59 Ergebnisse
Sensor 11735552: Seite 1, 76 Ergebnisse
Sensor 11983215: Seite 1, 387 Ergebnisse
Sensor 12178320: Seite 1, 357 Ergebnisse
Sensor 12178356: Seite 1, 383 Ergebnisse
Sensor 12384600: Seite 1, 252 Ergebnisse
Sensor 14781506: Seite 1, 91 Ergebnisse
Sensor 12464444: Seite 1, 314 Ergebnisse
Sensor 13388775: Seite 1, 243 Ergebnisse
Sensor 14086667: Seite 1, 137 Ergebnisse
Sensor 14152525: Seite 1, 163 Ergebnisse
Sensor 14153393: Seite 1, 153 Ergebnisse
Sensor 14243588: Seite 1, 140 Ergebnisse
Sensor 14359881: Seite 1, 140 Ergebnisse
Sensor 14493109: Seite 1, 124 Ergebnisse
Sensor 14671560: Seite 1, 101 Ergebnisse
Sensor 14729626: Seite 1, 94 Ergebnisse
Sensor 14753090: Seite 1, 92 Ergebnisse
Sensor 14781504: Seite 1, 91 Ergebnisse
Sensor 14931946: Seite 1, 75 Ergebnisse
Sensor 14942040: Seite 1, 71 Ergebnisse
Sensor 15093318: Seite 1, 20 Ergebnisse
110471

[{'date': '2020-03-16', 'value': 8.3832499925},
 {'date': '2020-03-17', 'value': 8.59719570304348},
 {'date': '2020-03-18', 'value': 11.218833463809524},
 {'date': '2020-03-19', 'value': 10.81293487},
 {'date': '2020-03-20', 'value': 16.029260754782605},
 {'date': '2020-03-21', 'value': 8.7958409},
 {'date': '2020-03-22', 'value': 5.237973722631579},
 {'date': '2020-03-23', 'value': 7.149999749999999},
 {'date': '2020-03-24', 'value': 10.859239117391303},
 {'date': '2020-03-25', 'value': 12.743891254782607},
 {'date': '2020-03-26', 'value': 11.149521864347822},
 {'date': '2020-03-27', 'value': 21.024399703500002},
 {'date': '2020-03-28', 'value': 17.843021679130434},
 {'date': '2020-03-29', 'value': 20.754545142272725},
 {'date': '2020-03-30', 'value': 4.448119033333333},
 {'date': '2020-03-31', 'value': 5.747369657391305},
 {'date': '2020-04-01', 'value': 9.71302179173913},
 {'date': '2020-04-02', 'value': 9.291478110869566},
 {'date': '2020-04-03', 'value': 13.596704391363636},
 {'date': '2020-04-04', 'value': 10.603347856956523},
 {'date': '2020-04-05', 'value': 11.437825965652177},
 {'date': '2020-04-06', 'value': 11.944775005},
 {'date': '2020-04-07', 'value': 13.005000110000001},
 {'date': '2020-04-08', 'value': 4.476619028571427},
 {'date': '2020-04-09', 'value': 8.497413091304349},
 {'date': '2020-04-10', 'value': 8.13873906173913},
 {'date': '2020-04-11', 'value': 7.577818107272727},
 {'date': '2020-04-12', 'value': 7.3711086721739125},
 {'date': '2020-04-13', 'value': 8.002652039130435},
 {'date': '2020-04-14', 'value': 5.177347852173913},
 {'date': '2020-04-15', 'value': 5.7402391173913045},
 {'date': '2020-04-16', 'value': 3.6977825999999996},
 {'date': '2020-04-17', 'value': 8.545695673913041},
 {'date': '2020-04-18', 'value': 9.354304329565217},
 {'date': '2020-04-19', 'value': 7.758239159565218},
 {'date': '2020-04-20', 'value': 5.9590434152173914},
 {'date': '2020-04-21', 'value': 6.924282524782609},
 {'date': '2020-04-22', 'value': 7.089772630909089},
 {'date': '2020-04-23', 'value': 7.603599924499998},
 {'date': '2020-04-24', 'value': 7.046136418181817},
 {'date': '2020-04-25', 'value': 9.03483311},
 {'date': '2020-04-26', 'value': 4.853000011428571},
 {'date': '2020-04-27', 'value': 4.883342073157894},
 {'date': '2020-04-28', 'value': 5.435149999999999},
 {'date': '2020-04-29', 'value': 4.096366679333333},
 {'date': '2020-04-30', 'value': 3.632575036000001},
 {'date': '2020-05-01', 'value': 3.6574545340909097},
 {'date': '2020-05-02', 'value': 3.5720237723809523},
 {'date': '2020-05-03', 'value': 4.961571382142856},
 {'date': '2020-05-04', 'value': 6.012236815789475},
 {'date': '2020-05-05', 'value': 7.443409014999999},
 {'date': '2020-05-06', 'value': 2.9689249835},
 {'date': '2020-05-08', 'value': 4.835785639285715},
 {'date': '2020-05-09', 'value': 5.914541596666667},
 {'date': '2020-05-10', 'value': 8.902173950434781},
 {'date': '2020-05-11', 'value': 5.295522814999999},
 {'date': '2020-05-12', 'value': 4.328499975555556},
 {'date': '2020-05-13', 'value': 9.195300288},
 {'date': '2020-05-14', 'value': 7.685178480714286},
 {'date': '2020-05-15', 'value': 11.863590885454546},
 {'date': '2020-05-16', 'value': 12.219052560526315},
 {'date': '2020-05-17', 'value': 10.283789605263156},
 {'date': '2020-05-18', 'value': 6.284321439285715},
 {'date': '2020-05-19', 'value': 6.8164582991666665},
 {'date': '2020-05-20', 'value': 6.549421028421053},
 {'date': '2020-05-21', 'value': 6.860078956842105},
 {'date': '2020-05-22', 'value': 5.812380921904762},
 {'date': '2020-05-23', 'value': 10.6355499705},
 {'date': '2020-05-24', 'value': 3.8126500310000004},
 {'date': '2020-05-25', 'value': 3.0548863522727276},
 {'date': '2020-05-26', 'value': 6.080454507727271},
 {'date': '2020-05-27', 'value': 4.911766763333334},
 {'date': '2020-05-28', 'value': 2.528374905},
 {'date': '2020-05-29', 'value': 5.777699991},
 {'date': '2020-05-31', 'value': 16.30216725},
 {'date': '2020-06-01', 'value': 5.916649886},
 {'date': '2020-06-02', 'value': 3.47915623625},
 {'date': '2020-06-03', 'value': 2.665794143529412},
 {'date': '2020-06-04', 'value': 6.8237141999999995},
 {'date': '2020-06-05', 'value': 11.287368516842104},
 {'date': '2020-06-07', 'value': 2.2245000420000003},
 {'date': '2020-06-08', 'value': 8.11277795611111},
 {'date': '2020-06-09', 'value': 5.057111152777777},
 {'date': '2020-06-10', 'value': 2.8119047776190476},
 {'date': '2020-06-11', 'value': 2.636181836818182},
 {'date': '2020-06-12', 'value': 2.9027999980000003},
 {'date': '2020-06-13', 'value': 4.4222856876190475},
 {'date': '2020-06-14', 'value': 6.210824961},
 {'date': '2020-06-15', 'value': 15.265900098666668},
 {'date': '2020-06-16', 'value': 22.84329151583333},
 {'date': '2020-06-17', 'value': 12.541022902272731},
 {'date': '2020-06-18', 'value': 2.8832221644444442},
 {'date': '2020-06-19', 'value': 4.107722224444444},
 {'date': '2020-06-20', 'value': 4.584272639999999},
 {'date': '2020-06-21', 'value': 6.253781165625001},
 {'date': '2020-06-22', 'value': 7.15125012},
 {'date': '2020-06-23', 'value': 6.510533264},
 {'date': '2020-06-24', 'value': 3.3206875262500004},
 {'date': '2020-06-25', 'value': 4.49375021},
 {'date': '2020-06-26', 'value': 5.236083343333334},
 {'date': '2020-06-27', 'value': 7.462153906153846},
 {'date': '2020-06-28', 'value': 6.35540469},
 {'date': '2020-06-29', 'value': 4.483999976315789},
 {'date': '2020-06-30', 'value': 3.415599912},
 {'date': '2020-07-01', 'value': 4.308361128333333},
 {'date': '2020-07-02', 'value': 4.628433286000001},
 {'date': '2020-07-04', 'value': 4.421555462222222},
 {'date': '2020-07-05', 'value': 6.435687386875},
 {'date': '2020-07-07', 'value': 2.8773666733333334},
 {'date': '2020-07-08', 'value': 4.227710505789475},
 {'date': '2020-07-09', 'value': 5.444075007},
 {'date': '2020-07-10', 'value': 4.6239999475},
 {'date': '2020-07-11', 'value': 5.738714281428571},
 {'date': '2020-07-12', 'value': 6.230777736111111},
 {'date': '2020-07-13', 'value': 2.404249999166667},
 {'date': '2020-07-14', 'value': 4.0871086386956526},
 {'date': '2020-07-15', 'value': 8.828068077727272},
 {'date': '2020-07-16', 'value': 7.9794375693749995},
 {'date': '2020-07-17', 'value': 7.5467174621739135},
 {'date': '2020-07-18', 'value': 12.746357288571428},
 {'date': '2020-07-19', 'value': 14.897874922},
 {'date': '2020-07-20', 'value': 9.499571317142856},
 {'date': '2020-07-21', 'value': 11.947071570952382},
 {'date': '2020-07-22', 'value': 10.357349914500002},
 {'date': '2020-07-23', 'value': 9.379184165789477},
 {'date': '2020-07-24', 'value': 11.089847724782608},
 {'date': '2020-07-25', 'value': 8.553863736363637},
 {'date': '2020-07-26', 'value': 8.063738090952379},
 {'date': '2020-07-27', 'value': 3.750499989130435},
 {'date': '2020-07-28', 'value': 4.591200029333334},
 {'date': '2020-07-29', 'value': 5.676166634444445},
 {'date': '2020-07-30', 'value': 6.1576086495652165},
 {'date': '2020-07-31', 'value': 6.5815501165},
 {'date': '2020-08-01', 'value': 4.526678606428571},
 {'date': '2020-08-02', 'value': 10.809543334782608},
 {'date': '2020-08-03', 'value': 7.378789495263157},
 {'date': '2020-08-04', 'value': 5.096739051304347},
 {'date': '2020-08-05', 'value': 8.14850044},
 {'date': '2020-08-06', 'value': 6.6739211278947375},
 {'date': '2020-08-07', 'value': 11.949857129285714},
 {'date': '2020-08-08', 'value': 13.314363691363637},
 {'date': '2020-08-09', 'value': 14.731543411304347},
 {'date': '2020-08-10', 'value': 14.406658991363635},
 {'date': '2020-08-11', 'value': 13.898646967647057},
 {'date': '2020-08-12', 'value': 7.172999996},
 {'date': '2020-08-13', 'value': 15.37233334},
 {'date': '2020-08-14', 'value': 17.328454532272726},
 {'date': '2020-08-15', 'value': 13.856181941818182},
 {'date': '2020-08-16', 'value': 11.287333392857144},
 {'date': '2020-08-17', 'value': 10.786673976521739},
 {'date': '2020-08-18', 'value': 7.944119083809524},
 {'date': '2020-08-19', 'value': 6.41523916304348},
 {'date': '2020-08-20', 'value': 2.366863651818182},
 {'date': '2020-08-21', 'value': 3.9349317836363635},
 {'date': '2020-08-22', 'value': 8.651954646363636},
 {'date': '2020-08-24', 'value': 2.983299989},
 {'date': '2020-08-25', 'value': 3.951391225217392},
 {'date': '2020-08-26', 'value': 3.0910652265217387},
 {'date': '2020-08-27', 'value': 4.063289437894737},
 {'date': '2020-08-28', 'value': 4.288608701739131},
 {'date': '2020-08-29', 'value': 3.396999996190477},
 {'date': '2020-08-30', 'value': 5.69375000409091},
 {'date': '2020-08-31', 'value': 2.3299999786363643},
 {'date': '2020-09-01', 'value': 6.218347782608696},
 {'date': '2020-09-02', 'value': 6.605159104545455},
 {'date': '2020-09-03', 'value': 6.134068137272728},
 {'date': '2020-09-04', 'value': 5.84449982},
 {'date': '2020-09-05', 'value': 4.315818283636363},
 {'date': '2020-09-06', 'value': 14.877666466666668},
 {'date': '2020-09-07', 'value': 10.260227263636365},
 {'date': '2020-09-08', 'value': 5.239021731304349},
 {'date': '2020-09-09', 'value': 7.06069429111111},
 {'date': '2020-09-10', 'value': 8.93378261347826},
 {'date': '2020-09-11', 'value': 7.9447727595454545},
 {'date': '2020-09-12', 'value': 11.665950102},
 {'date': '2020-09-13', 'value': 7.4940952976190465},
 {'date': '2020-09-14', 'value': 8.618599950666667},
 {'date': '2020-09-15', 'value': 8.688190545714285},
 {'date': '2020-09-16', 'value': 14.871190339047624},
 {'date': '2020-09-17', 'value': 17.046690346190474},
 {'date': '2020-09-18', 'value': 3.2996470458823532},
 {'date': '2020-09-19', 'value': 4.660659091363636},
 {'date': '2020-09-20', 'value': 6.36916671},
 {'date': '2020-09-21', 'value': 10.792157871578945},
 {'date': '2020-09-22', 'value': 10.57299984521739},
 {'date': '2020-09-23', 'value': 11.90897379},
 {'date': '2020-09-24', 'value': 9.478966406000001},
 {'date': '2020-09-25', 'value': 7.829976137619049},
 {'date': '2020-09-26', 'value': 6.804999872000001},
 {'date': '2020-09-27', 'value': 2.3349129643478257},
 {'date': '2020-09-28', 'value': 3.9173234305882363},
 {'date': '2020-09-29', 'value': 10.877299972000001},
 {'date': '2020-09-30', 'value': 7.999521758695653},
 {'date': '2020-10-01', 'value': 11.607727284090908},
 {'date': '2020-10-02', 'value': 5.591954496818181},
 {'date': '2020-10-03', 'value': 5.981000043809523},
 {'date': '2020-10-04', 'value': 12.620499605},
 {'date': '2020-10-05', 'value': 2.130642835714286},
 {'date': '2020-10-06', 'value': 2.0714130191304347},
 {'date': '2020-10-07', 'value': 2.78823907},
 {'date': '2020-10-08', 'value': 4.922045421363635},
 {'date': '2020-10-09', 'value': 4.869409145},
 {'date': '2020-10-10', 'value': 12.202477114545456},
 {'date': '2020-10-11', 'value': 4.993099986666667},
 {'date': '2020-10-12', 'value': 5.362115377692307},
 {'date': '2020-10-13', 'value': 8.236804293913043},
 {'date': '2020-10-14', 'value': 11.931088397058824},
 {'date': '2020-10-15', 'value': 10.030545360454543},
 {'date': '2020-10-16', 'value': 7.370847925217391},
 {'date': '2020-10-17', 'value': 5.991562500416666},
 {'date': '2020-10-18', 'value': 6.404043483043479},
 {'date': '2020-10-19', 'value': 9.06769573652174},
 {'date': '2020-10-20', 'value': 4.693818162727273},
 {'date': '2020-10-21', 'value': 4.649804358695652},
 {'date': '2020-10-22', 'value': 12.998652039565217},
 {'date': '2020-10-23', 'value': 14.447391298260868},
 {'date': '2020-10-24', 'value': 21.71071042052631},
 {'date': '2020-10-25', 'value': 7.845130485217393},
 {'date': '2020-10-26', 'value': 12.181368648421053},
 {'date': '2020-10-27', 'value': 6.741920950000001},
 {'date': '2020-10-28', 'value': 2.695840885},
 {'date': '2020-10-29', 'value': 3.2351176752941173},
 {'date': '2020-10-30', 'value': 6.04586366818182},
 {'date': '2020-10-31', 'value': 7.250583392777778},
 {'date': '2020-11-01', 'value': 16.81410883347826},
 {'date': '2020-11-02', 'value': 12.13828271826087},
 {'date': '2020-11-03', 'value': 1.64400005},
 {'date': '2020-11-04', 'value': 4.848227355},
 {'date': '2020-11-05', 'value': 11.248809514285714},
 {'date': '2020-11-06', 'value': 0.935704530909091},
 {'date': '2020-11-07', 'value': 4.2887940464705885},
 {'date': '2020-11-08', 'value': 7.939972142222222},
 {'date': '2020-11-09', 'value': 26.818599983000002},
 {'date': '2020-11-10', 'value': 19.542062515625005},
 {'date': '2020-11-11', 'value': 18.274739074347828},
 {'date': '2020-11-12', 'value': 14.63752136521739},
 {'date': '2020-11-13', 'value': 12.610043416956518},
 {'date': '2020-11-14', 'value': 4.222735300588235},
 {'date': '2020-11-15', 'value': 4.018391263043478},
 {'date': '2020-11-16', 'value': 14.356106821428572},
 {'date': '2020-11-17', 'value': 7.624558752352942},
 {'date': '2020-11-18', 'value': 3.4491579173684213},
 {'date': '2020-11-19', 'value': 6.418450159000001},
 {'date': '2020-11-20', 'value': 4.727944436111111},
 {'date': '2020-11-21', 'value': 6.3044473194736845},
 {'date': '2020-11-22', 'value': 2.4798929128571428},
 {'date': '2020-11-23', 'value': 7.730305586666668},
 {'date': '2020-11-24', 'value': 3.401249953333334},
 {'date': '2020-11-25', 'value': 30.36900138},
 {'date': '2020-11-26', 'value': 4.586999954285714},
 {'date': '2020-11-27', 'value': 6.022450061000001},
 {'date': '2020-11-28', 'value': 7.659166595555557},
 {'date': '2020-11-29', 'value': 8.5547000125},
 {'date': '2020-11-30', 'value': 7.42636825631579},
 {'date': '2020-12-01', 'value': 12.9769502115},
 {'date': '2020-12-02', 'value': 15.321192222307692},
 {'date': '2020-12-04', 'value': 1.93876318},
 {'date': '2020-12-05', 'value': 2.1830384953846154},
 {'date': '2020-12-06', 'value': 7.732666408333334},
 {'date': '2020-12-07', 'value': 16.23905865},
 {'date': '2020-12-08', 'value': 1.5465750229999997},
 {'date': '2020-12-09', 'value': 11.950499982105264},
 {'date': '2020-12-10', 'value': 12.447052698947367},
 {'date': '2020-12-11', 'value': 8.5045771},
 {'date': '2020-12-13', 'value': 19.0805001225},
 {'date': '2020-12-14', 'value': 3.754949947000001},
 {'date': '2020-12-15', 'value': 8.296326049130435},
 {'date': '2020-12-16', 'value': 15.992886249090907},
 {'date': '2020-12-17', 'value': 14.328500016363638},
 {'date': '2020-12-18', 'value': 7.469176595882352},
 {'date': '2020-12-19', 'value': 18.149227225454545},
 {'date': '2020-12-20', 'value': 10.110568322272727},
 {'date': '2020-12-21', 'value': 11.014050098999999},
 {'date': '2020-12-22', 'value': 23.3153823917647},
 {'date': '2020-12-23', 'value': 3.294789434210526},
 {'date': '2020-12-24', 'value': 5.416152238695652},
 {'date': '2020-12-25', 'value': 4.256652179130436},
 {'date': '2020-12-26', 'value': 4.4401470864705885},
 {'date': '2020-12-29', 'value': 1.30475},
 {'date': '2020-12-30', 'value': 1.7799999752631581},
 {'date': '2020-12-31', 'value': 2.84321429},
 {'date': '2021-01-01', 'value': 2.274194452777778},
 {'date': '2021-01-03', 'value': 23.288891145217388},
 {'date': '2021-01-04', 'value': 10.933152007391305},
 {'date': '2021-01-05', 'value': 14.693249842777776},
 {'date': '2021-01-06', 'value': 7.466130396086956},
 {'date': '2021-01-07', 'value': 10.200608477391304},
 {'date': '2021-01-08', 'value': 15.507978352173916},
 {'date': '2021-01-09', 'value': 14.159146809411768},
 {'date': '2021-01-10', 'value': 7.1289443922222215},
 {'date': '2021-01-11', 'value': 9.311825032000002},
 {'date': '2021-01-12', 'value': 11.216363712272727},
 {'date': '2021-01-13', 'value': 3.720099945},
 {'date': '2021-01-14', 'value': 3.330218756875},
 {'date': '2021-01-15', 'value': 6.498613633636362},
 {'date': '2021-01-16', 'value': 6.366452371428571},
 {'date': '2021-01-17', 'value': 4.58386832263158},
 {'date': '2021-01-18', 'value': 6.331699891999999},
 {'date': '2021-01-19', 'value': 5.6337856452380946},
 {'date': '2021-01-20', 'value': 1.0443043365217393},
 {'date': '2021-01-21', 'value': 1.2770750155},
 {'date': '2021-01-22', 'value': 0.618649989},
 {'date': '2021-01-26', 'value': 2.160625005},
 {'date': '2021-01-27', 'value': 5.955545491363637},
 {'date': '2021-01-28', 'value': 10.371500069545455},
 {'date': '2021-01-29', 'value': 8.668282579565217},
 {'date': '2021-01-30', 'value': 9.172041740833334},
 {'date': '2021-01-31', 'value': 6.908717440869565},
 {'date': '2021-02-01', 'value': 6.30999994},
 {'date': '2021-02-02', 'value': 25.740052782631576},
 {'date': '2021-02-03', 'value': 15.004977003181823},
 {'date': '2021-02-04', 'value': 1.284724996},
 {'date': '2021-02-05', 'value': 4.556738139523809},
 {'date': '2021-02-06', 'value': 7.163521731304348},
 {'date': '2021-02-07', 'value': 6.629891327391303},
 {'date': '2021-02-08', 'value': 9.484826020869566},
 {'date': '2021-02-09', 'value': 9.49989144173913},
 {'date': '2021-02-10', 'value': 19.8184999026087},
 {'date': '2021-02-11', 'value': 9.537565329565217},
 {'date': '2021-02-12', 'value': 5.7442272313636344},
 {'date': '2021-02-13', 'value': 7.790456559565216},
 {'date': '2021-02-14', 'value': 4.307630430000001},
 {'date': '2021-02-15', 'value': 1.04299998},
 {'date': '2021-02-16', 'value': 12.390052602105262},
 {'date': '2021-02-17', 'value': 7.278456455217392},
 {'date': '2021-02-18', 'value': 2.254181803181818},
 {'date': '2021-02-19', 'value': 4.495408983636363},
 {'date': '2021-02-20', 'value': 5.74512499},
 {'date': '2021-02-21', 'value': 10.422931795454545},
 {'date': '2021-02-22', 'value': 9.723521704782609},
 {'date': '2021-02-23', 'value': 6.27952262},
 {'date': '2021-02-24', 'value': 13.74742857142857},
 {'date': '2021-02-25', 'value': 18.86877758833333},
 {'date': '2021-02-28', 'value': 6.441874855},
 {'date': '2021-03-01', 'value': 9.697590822727271},
 {'date': '2021-03-02', 'value': 5.979586937826086},
 {'date': '2021-03-03', 'value': 7.17249965},
 {'date': '2021-03-04', 'value': 17.878578733684208},
 {'date': '2021-03-05', 'value': 6.792760823478262},
 {'date': '2021-03-06', 'value': 5.815304367391304},
 {'date': '2021-03-07', 'value': 5.788065189565217},
 {'date': '2021-03-08', 'value': 12.399652040434786},
 {'date': '2021-03-09', 'value': 12.155187483125001},
 {'date': '2021-03-10', 'value': 14.7407500675},
 {'date': '2021-03-11', 'value': 7.512825016000001},
 {'date': '2021-03-12', 'value': 1.2008333304761907},
 {'date': '2021-03-13', 'value': 1.3608095100000004},
 {'date': '2021-03-14', 'value': 1.6850476166666666},
 {'date': '2021-03-15', 'value': 5.041657819473683},
 {'date': '2021-03-16', 'value': 2.7808750225},
 {'date': '2021-03-17', 'value': 6.230824918000001},
 {'date': '2021-03-18', 'value': 7.364095205238096},
 {'date': '2021-03-19', 'value': 6.818369612173913},
 {'date': '2021-03-20', 'value': 7.242369502173914},
 {'date': '2021-03-21', 'value': 9.16814276904762},
 {'date': '2021-03-22', 'value': 5.891869555652174},
 {'date': '2021-03-23', 'value': 8.702294261176469},
 {'date': '2021-03-24', 'value': 14.589900105999998},
 {'date': '2021-03-25', 'value': 13.376195632608697},
 {'date': '2021-03-26', 'value': 7.683523740952383},
 {'date': '2021-03-27', 'value': 4.567205788235293},
 {'date': '2021-03-28', 'value': 4.490857117142857},
 {'date': '2021-03-29', 'value': 6.149156207499999},
 {'date': '2021-03-30', 'value': 6.393714263809523},
 {'date': '2021-03-31', 'value': 6.471277841666666},
 {'date': '2021-04-01', 'value': 10.485100169999999},
 {'date': '2021-04-02', 'value': 10.343250265},
 {'date': '2021-04-03', 'value': 3.7305834250000003},
 {'date': '2021-04-04', 'value': 3.755769266923077},
 {'date': '2021-04-05', 'value': 4.919619049523811},
 {'date': '2021-04-06', 'value': 2.5199999825000003},
 {'date': '2021-04-07', 'value': 3.8142173960869568},
 {'date': '2021-04-08', 'value': 5.645824969},
 {'date': '2021-04-09', 'value': 7.979884601538463},
 {'date': '2021-04-10', 'value': 4.698261834285714},
 {'date': '2021-04-11', 'value': 5.324031296875001},
 {'date': '2021-04-12', 'value': 3.7392999609999995},
 {'date': '2021-04-13', 'value': 8.418735246470588},
 {'date': '2021-04-14', 'value': 5.78214284},
 {'date': '2021-04-15', 'value': 6.025925010500001},
 {'date': '2021-04-16', 'value': 8.180178434285713},
 {'date': '2021-04-17', 'value': 12.834431816818181},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [11]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_pm25_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_pm25_mean
0    2020-03-16         14.964924
1    2020-03-17         16.596052
2    2020-03-18         16.121165
3    2020-03-19         18.671564
4    2020-03-20         20.793286
...         ...               ...
2079 2026-02-24          4.310470
2080 2026-02-25          9.382287
2081 2026-02-26         14.726242
2082 2026-02-27         17.108548
2083 2026-02-28         19.306524

[2084 rows x 2 columns]

### Convert dataframe to csv

In [12]:
france_daily[["date", "france_pm25_mean"]].to_csv(
    "daily_avg_austria_PM25.csv",
    index=False
)

# NO2

In [17]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "AT",   # only consider stations located in France
    "parameters_id": 5,   # NO2
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_no2 = df_sorted

df_top_no2

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
11,2752,Wiener Neustadt,2700 Wiener Neustadt,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275363, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.814166999937704, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.254999999598795, 47.814166999937704, 16.25...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
20,2761,Mürzzuschlag Roseggerpark,8680 Mürzzuschlag,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4275306, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.604721999960276, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.673056000049757, 47.604721999960276, 15.67...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
22,2764,Grünbach bei Freistadt,4264 Grünbach,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274395, 'name': 'no µg/m³', 'paramete...","{'latitude': 48.53110999980738, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.574722000058197, 48.53110999980738, 14.574...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
24,2766,Liezen Pyhrnbach,8940 Liezen,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4274806, 'name': 'no µg/m³', 'paramete...","{'latitude': 47.56543899973233, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.244675999684107, 47.56543899973233, 14.244...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
28,2770,Bruck an der Mur Flurgasse,8600 Bruck an der Mur,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5787, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 47.40944299996983, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.253333000357205, 47.40944299996983, 15.253...",None,2016-11-18 05:00:00+00:00,2026-03-05 17:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,4816305,Mödling Bachgasse,2340 Mödling,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13388776, 'name': 'co µg/m³', 'paramet...","{'latitude': 48.085556000069815, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.300972000220895, 48.085556000069815, 16.30...",None,2025-06-19 11:00:00+00:00,2026-03-05 17:00:00+00:00
313,4816306,Steyr Münichholz,4400 Steyr,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13388778, 'name': 'no2 µg/m³', 'parame...","{'latitude': 48.04925000005705, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[14.442361000245842, 48.04925000005705, 14.442...",None,2025-06-19 11:00:00+00:00,2026-03-05 17:00:00+00:00
314,6149652,"Stockerau, Rudolf Diesel-Straße",2000 Stockerau,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14776823, 'name': 'no2 µg/m³', 'parame...","{'latitude': 48.38499999970251, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.18211000035268, 48.38499999970251, 16.1821...",None,2025-11-29 09:00:00+00:00,2026-03-05 17:00:00+00:00
315,6150274,Salzburg Airport Kendlerstraße,5020 Salzburg,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14781509, 'name': 'no2 µg/m³', 'parame...","{'latitude': 47.78549099991712, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[13.011450999985355, 47.78549099991712, 13.011...",None,2025-11-29 23:00:00+00:00,2026-03-05 17:00:00+00:00
316,6170365,Klosterneuburg B14,3400 Klosterneuburg,Europe/Vienna,"{'id': 89, 'code': 'AT', 'name': 'Austria'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14931945, 'name': 'no2 µg/m³', 'parame...","{'latitude': 48.30832999974348, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.32803000038363, 48.30832999974348, 16.3280...",None,2025-12-16 23:00:00+00:00,2026-03-05 17:00:00+00:00

In [18]:
rows = []

for _, station in df_top_no2.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur NO2 behalten
        if sensor["parameter"]["id"] == 5:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_no2_sensors = pd.DataFrame(rows)

df_no2_sensors

     station_id                     station_name  sensor_id sensor_name
0          2752                  Wiener Neustadt       5740   no2 µg/m³
1          2761        Mürzzuschlag Roseggerpark       5756   no2 µg/m³
2          2764           Grünbach bei Freistadt       5758   no2 µg/m³
3          2766                 Liezen Pyhrnbach       5761   no2 µg/m³
4          2770       Bruck an der Mur Flurgasse       5787   no2 µg/m³
..          ...                              ...        ...         ...
312     4816305                Mödling Bachgasse   13388774   no2 µg/m³
313     4816306                 Steyr Münichholz   13388778   no2 µg/m³
314     6149652  Stockerau, Rudolf Diesel-Straße   14776823   no2 µg/m³
315     6150274   Salzburg Airport Kendlerstraße   14781509   no2 µg/m³
316     6170365               Klosterneuburg B14   14931945   no2 µg/m³

[317 rows x 4 columns]

In [19]:
sensor_ids = df_no2_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

317

[5740,
 5756,
 5758,
 5761,
 5787,
 5876,
 6131,
 6167,
 5930,
 5934,
 6062,
 6085,
 6135,
 5946,
 5908,
 6000,
 5987,
 6027,
 5779,
 5896,
 5892,
 6079,
 6008,
 6106,
 6043,
 6076,
 5686,
 5884,
 6055,
 5937,
 5782,
 6005,
 6177,
 6044,
 5989,
 5950,
 5741,
 5760,
 5859,
 5838,
 5742,
 5743,
 6100,
 5746,
 5878,
 6084,
 5813,
 5759,
 5763,
 5983,
 6160,
 5945,
 5776,
 5780,
 5786,
 5864,
 5909,
 5798,
 5801,
 5802,
 5803,
 5807,
 5809,
 5944,
 6161,
 5827,
 5831,
 5836,
 5840,
 5843,
 6176,
 5893,
 5861,
 5863,
 5866,
 5868,
 5925,
 5897,
 5938,
 5899,
 5900,
 5979,
 6059,
 5920,
 5931,
 5929,
 5941,
 6032,
 5975,
 5954,
 5962,
 6051,
 5971,
 6036,
 5991,
 5988,
 5986,
 6003,
 6006,
 6099,
 6009,
 6022,
 6133,
 6017,
 6048,
 6037,
 6061,
 6065,
 6072,
 6077,
 6096,
 6105,
 6140,
 6122,
 6159,
 6139,
 6158,
 6168,
 5738,
 5677,
 11578,
 11489,
 11307,
 11624,
 11478,
 11542,
 11372,
 11428,
 11609,
 11569,
 11226,
 11148,
 11476,
 11507,
 11596,
 11586,
 11205,
 11610,
 11155,
 11158,
 11181,
 11191,
 11199,
 11204,
 11210,
 11214,
 11216,
 11223,
 11267,
 11295,
 11312,
 11351,
 11354,
 11379,
 11381,
 11406,
 11400,
 11414,
 11442,
 11467,
 11470,
 11501,
 11510,
 11527,
 11540,
 11541,
 11608,
 11572,
 11575,
 11595,
 11613,
 11619,
 11411,
 11557,
 11271,
 11172,
 11583,
 11249,
 11616,
 11048,
 11143,
 11228,
 11253,
 11281,
 11297,
 11325,
 11407,
 11449,
 11459,
 11487,
 11511,
 11513,
 11524,
 11561,
 11588,
 11601,
 11603,
 11238,
 11280,
 11303,
 11634,
 11314,
 11491,
 11332,
 11153,
 11308,
 11147,
 11285,
 11424,
 11532,
 11535,
 11329,
 5078693,
 5078847,
 5078672,
 5078404,
 5078853,
 5078455,
 5078451,
 5078441,
 5078634,
 5078865,
 5078879,
 5078381,
 5078496,
 5078963,
 5078929,
 5078715,
 5079013,
 5078486,
 5078387,
 5078303,
 5078827,
 5078556,
 7775386,
 7773561,
 7775997,
 7773992,
 7773678,
 7773413,
 7775747,
 7773272,
 7773539,
 7773592,
 7775259,
 7774907,
 7775380,
 7775038,
 7773015,
 7773755,
 7773942,
 7773545,
 7775503,
 7773720,
 7776000,
 7772988,
 7775101,
 7775532,
 7774824,
 7775227,
 7773275,
 7775932,
 7773530,
 7774435,
 7772928,
 7772977,
 7774127,
 7775115,
 7773170,
 7775910,
 7773204,
 7774517,
 7773360,
 7773770,
 7775935,
 7774065,
 7773569,
 7775922,
 7775513,
 7773457,
 7775913,
 7777043,
 7775470,
 7773705,
 7774794,
 7773587,
 8613421,
 7775646,
 7774492,
 7772904,
 7772987,
 7775698,
 7774987,
 7773894,
 7774999,
 7944831,
 7944804,
 7944823,
 7944801,
 7944814,
 7944820,
 7944817,
 7944812,
 9440299,
 9440301,
 9445107,
 11597870,
 11609498,
 11735551,
 12384602,
 12384601,
 12389002,
 13388774,
 13388778,
 14776823,
 14781509,
 14931945]

In [21]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 5740: Seite 1, 1000 Ergebnisse
Sensor 5740: Seite 2, 1000 Ergebnisse
Sensor 5740: Seite 3, 171 Ergebnisse
Sensor 5756: Seite 1, 1000 Ergebnisse
Sensor 5756: Seite 2, 1000 Ergebnisse
Sensor 5756: Seite 3, 154 Ergebnisse
Sensor 5758: Seite 1, 1000 Ergebnisse
Sensor 5758: Seite 2, 1000 Ergebnisse
Sensor 5758: Seite 3, 164 Ergebnisse
Sensor 5761: Seite 1, 1000 Ergebnisse
Sensor 5761: Seite 2, 1000 Ergebnisse
Sensor 5761: Seite 3, 139 Ergebnisse
Sensor 5787: Seite 1, 1000 Ergebnisse
Sensor 5787: Seite 2, 1000 Ergebnisse
Sensor 5787: Seite 3, 156 Ergebnisse
Sensor 5876: Seite 1, 1000 Ergebnisse
Sensor 5876: Seite 2, 1000 Ergebnisse
Sensor 5876: Seite 3, 166 Ergebnisse
Sensor 6131: Seite 1, 1000 Ergebnisse
Sensor 6131: Seite 2, 1000 Ergebnisse
Sensor 6131: Seite 3, 169 Ergebnisse
Sensor 5930: Seite 1, 1000 Ergebnisse
Sensor 5930: Seite 2, 1000 Ergebnisse
Sensor 5930: Seite 3, 143 Ergebnisse
Sensor 5934: Seite 1, 1000 Ergebnisse
Sensor 5934: Seite 2, 1000 Ergebnisse
Sensor 5934: Seite 3, 168 Ergebnisse
Sensor 6062: Seite 1, 1000 Ergebnisse
Sensor 6062: Seite 2, 1000 Ergebnisse
Sensor 6062: Seite 3, 147 Ergebnisse
Sensor 6085: Seite 1, 1000 Ergebnisse
Sensor 6085: Seite 2, 1000 Ergebnisse
Sensor 6085: Seite 3, 171 Ergebnisse
Sensor 6135: Seite 1, 1000 Ergebnisse
Sensor 6135: Seite 2, 1000 Ergebnisse
Sensor 6135: Seite 3, 166 Ergebnisse
Sensor 5946: Seite 1, 1000 Ergebnisse
Sensor 5946: Seite 2, 1000 Ergebnisse
Sensor 5946: Seite 3, 91 Ergebnisse
Sensor 5908: Seite 1, 1000 Ergebnisse
Sensor 5908: Seite 2, 927 Ergebnisse
Sensor 6000: Seite 1, 1000 Ergebnisse
Sensor 6000: Seite 2, 482 Ergebnisse
Sensor 5987: Seite 1, 1000 Ergebnisse
Sensor 5987: Seite 2, 480 Ergebnisse
Sensor 6027: Seite 1, 1000 Ergebnisse
Sensor 6027: Seite 2, 481 Ergebnisse
Sensor 5779: Seite 1, 1000 Ergebnisse
Sensor 5779: Seite 2, 478 Ergebnisse
Sensor 5896: Seite 1, 1000 Ergebnisse
Sensor 5896: Seite 2, 473 Ergebnisse
Sensor 5892: Seite 1, 1000 Ergebnisse
Sensor 5892: Seite 2, 480 Ergebnisse
Sensor 6079: Seite 1, 1000 Ergebnisse
Sensor 6079: Seite 2, 476 Ergebnisse
Sensor 6008: Seite 1, 1000 Ergebnisse
Sensor 6008: Seite 2, 438 Ergebnisse
Sensor 6106: Seite 1, 1000 Ergebnisse
Sensor 6106: Seite 2, 481 Ergebnisse
Sensor 6043: Seite 1, 1000 Ergebnisse
Sensor 6043: Seite 2, 482 Ergebnisse
Sensor 6076: Seite 1, 1000 Ergebnisse
Sensor 6076: Seite 2, 464 Ergebnisse
Sensor 5686: Seite 1, 1000 Ergebnisse
Sensor 5686: Seite 2, 318 Ergebnisse
Sensor 5884: Seite 1, 1000 Ergebnisse
Sensor 5884: Seite 2, 471 Ergebnisse
Sensor 6055: Seite 1, 1000 Ergebnisse
Sensor 6055: Seite 2, 477 Ergebnisse
Sensor 5937: Seite 1, 1000 Ergebnisse
Sensor 5937: Seite 2, 313 Ergebnisse
Sensor 5782: Seite 1, 770 Ergebnisse
Sensor 6005: Seite 1, 437 Ergebnisse
Sensor 6177: Seite 1, 155 Ergebnisse
Sensor 6044: Seite 1, 29 Ergebnisse
Sensor 5989: Seite 1, 22 Ergebnisse
Sensor 5950: Seite 1, 22 Ergebnisse
Sensor 5741: Seite 1, 22 Ergebnisse
Sensor 5760: Seite 1, 22 Ergebnisse
Sensor 5859: Seite 1, 22 Ergebnisse
Sensor 5838: Seite 1, 22 Ergebnisse
Sensor 5742: Seite 1, 22 Ergebnisse
Sensor 5743: Seite 1, 22 Ergebnisse
Sensor 6100: Seite 1, 22 Ergebnisse
Sensor 5746: Seite 1, 22 Ergebnisse
Sensor 5878: Seite 1, 22 Ergebnisse
Sensor 6084: Seite 1, 22 Ergebnisse
Sensor 5813: Seite 1, 22 Ergebnisse
Sensor 5759: Seite 1, 22 Ergebnisse
Sensor 5763: Seite 1, 22 Ergebnisse
Sensor 5983: Seite 1, 22 Ergebnisse
Sensor 6160: Seite 1, 22 Ergebnisse
Sensor 5945: Seite 1, 22 Ergebnisse
Sensor 5776: Seite 1, 22 Ergebnisse
Sensor 5780: Seite 1, 22 Ergebnisse
Sensor 5786: Seite 1, 22 Ergebnisse
Sensor 5864: Seite 1, 22 Ergebnisse
Sensor 5909: Seite 1, 22 Ergebnisse
Sensor 5798: Seite 1, 22 Ergebnisse
Sensor 5801: Seite 1, 22 Ergebnisse
Sensor 5802: Seite 1, 22 Ergebnisse
Sensor 5803: Seite 1, 22 Ergebnisse
Sensor 5807: Seite 1, 22 Ergebnisse
Sensor 5809: Seite 1, 22 Ergebnisse
Sensor 5944: Seite 1, 22 Ergebnisse
Sensor 6161: Seite 1, 22 Ergebnisse
Sensor 5827: Seite 1, 22 Ergebnisse
Sensor 5831: Seite 1, 22 Ergebnisse
Sensor 5836: Seite 1, 22 Ergebnisse
Sensor 5840: Seite 1, 17 Ergebnisse
Sensor 6077: Seite 1, 22 Ergebnisse
Sensor 6096: Seite 1, 22 Ergebnisse
Sensor 6105: Seite 1, 22 Ergebnisse
Sensor 6140: Seite 1, 22 Ergebnisse
Sensor 6122: Seite 1, 22 Ergebnisse
Sensor 6159: Seite 1, 22 Ergebnisse
Sensor 6139: Seite 1, 22 Ergebnisse
Sensor 6158: Seite 1, 22 Ergebnisse
Sensor 6168: Seite 1, 22 Ergebnisse
Sensor 5738: Seite 1, 22 Ergebnisse
Sensor 5677: Seite 1, 1000 Ergebnisse
Sensor 5677: Seite 2, 379 Ergebnisse
Sensor 11578: Seite 1, 1000 Ergebnisse
Sensor 11578: Seite 2, 1000 Ergebnisse
Sensor 11578: Seite 3, 144 Ergebnisse
Sensor 11489: Seite 1, 1000 Ergebnisse
Sensor 11489: Seite 2, 1000 Ergebnisse
Sensor 11489: Seite 3, 97 Ergebnisse
Sensor 11307: Seite 1, 1000 Ergebnisse
Sensor 11307: Seite 2, 1000 Ergebnisse
Sensor 11307: Seite 3, 97 Ergebnisse
Sensor 11624: Seite 1, 1000 Ergebnisse
Sensor 11624: Seite 2, 1000 Ergebnisse
Sensor 11624: Seite 3, 143 Ergebnisse
Sensor 11478: Seite 1, 1000 Ergebnisse
Sensor 11478: Seite 2, 1000 Ergebnisse
Sensor 11478: Seite 3, 127 Ergebnisse
Sensor 11542: Seite 1, 1000 Ergebnisse
Sensor 11542: Seite 2, 1000 Ergebnisse
Sensor 11542: Seite 3, 135 Ergebnisse
Sensor 11372: Seite 1, 1000 Ergebnisse
Sensor 11372: Seite 2, 1000 Ergebnisse
Sensor 11372: Seite 3, 146 Ergebnisse
Sensor 11428: Seite 1, 1000 Ergebnisse
Sensor 11428: Seite 2, 1000 Ergebnisse
Sensor 11428: Seite 3, 98 Ergebnisse
Sensor 11609: Seite 1, 1000 Ergebnisse
Sensor 11609: Seite 2, 1000 Ergebnisse
Sensor 11609: Seite 3, 146 Ergebnisse
Sensor 11569: Seite 1, 1000 Ergebnisse
Sensor 11569: Seite 2, 457 Ergebnisse
Sensor 11226: Seite 1, 1000 Ergebnisse
Sensor 11226: Seite 2, 449 Ergebnisse
Sensor 11148: Seite 1, 1000 Ergebnisse
Sensor 11148: Seite 2, 422 Ergebnisse
Sensor 11476: Seite 1, 1000 Ergebnisse
Sensor 11476: Seite 2, 447 Ergebnisse
Sensor 11507: Seite 1, 1000 Ergebnisse
Sensor 11507: Seite 2, 455 Ergebnisse
Sensor 11596: Seite 1, 1000 Ergebnisse
Sensor 11596: Seite 2, 459 Ergebnisse
Sensor 11586: Seite 1, 1000 Ergebnisse
Sensor 11586: Seite 2, 462 Ergebnisse
Sensor 11610: Seite 1, 1000 Ergebnisse
Sensor 11610: Seite 2, 1000 Ergebnisse
Sensor 11610: Seite 3, 86 Ergebnisse
Sensor 11155: Seite 1, 1000 Ergebnisse
Sensor 11155: Seite 2, 1000 Ergebnisse
Sensor 11155: Seite 3, 146 Ergebnisse
Sensor 11158: Seite 1, 1000 Ergebnisse
Sensor 11158: Seite 2, 1000 Ergebnisse
Sensor 11158: Seite 3, 126 Ergebnisse
Sensor 11181: Seite 1, 1000 Ergebnisse
Sensor 11181: Seite 2, 1000 Ergebnisse
Sensor 11181: Seite 3, 87 Ergebnisse
Sensor 11191: Seite 1, 1000 Ergebnisse
Sensor 11191: Seite 2, 1000 Ergebnisse
Sensor 11191: Seite 3, 116 Ergebnisse
Sensor 11199: Seite 1, 1000 Ergebnisse
Sensor 11199: Seite 2, 1000 Ergebnisse
Sensor 11199: Seite 3, 146 Ergebnisse
Sensor 11204: Seite 1, 1000 Ergebnisse
Sensor 11204: Seite 2, 1000 Ergebnisse
Sensor 11204: Seite 3, 146 Ergebnisse
Sensor 11210: Seite 1, 1000 Ergebnisse
Sensor 11210: Seite 2, 1000 Ergebnisse
Sensor 11210: Seite 3, 147 Ergebnisse
Sensor 11214: Seite 1, 1000 Ergebnisse
Sensor 11214: Seite 2, 1000 Ergebnisse
Sensor 11214: Seite 3, 141 Ergebnisse
Sensor 11216: Seite 1, 1000 Ergebnisse
Sensor 11216: Seite 2, 1000 Ergebnisse
Sensor 11216: Seite 3, 144 Ergebnisse
Sensor 11223: Seite 1, 503 Ergebnisse
Sensor 11267: Seite 1, 1000 Ergebnisse
Sensor 11267: Seite 2, 1000 Ergebnisse
Sensor 11267: Seite 3, 145 Ergebnisse
Sensor 11295: Seite 1, 1000 Ergebnisse
Sensor 11295: Seite 2, 1000 Ergebnisse
Sensor 11295: Seite 3, 136 Ergebnisse
Sensor 11312: Seite 1, 1000 Ergebnisse
Sensor 11312: Seite 2, 1000 Ergebnisse
Sensor 11312: Seite 3, 146 Ergebnisse
Sensor 11351: Seite 1, 1000 Ergebnisse
Sensor 11351: Seite 2, 1000 Ergebnisse
Sensor 11351: Seite 3, 145 Ergebnisse
Sensor 11354: Seite 1, 1000 Ergebnisse
Sensor 11354: Seite 2, 1000 Ergebnisse
Sensor 11354: Seite 3, 90 Ergebnisse
Sensor 11379: Seite 1, 448 Ergebnisse
Sensor 11381: Seite 1, 1000 Ergebnisse
Sensor 11381: Seite 2, 1000 Ergebnisse
Sensor 11381: Seite 3, 149 Ergebnisse
Sensor 11406: Seite 1, 1000 Ergebnisse
Sensor 11406: Seite 2, 1000 Ergebnisse
Sensor 11406: Seite 3, 148 Ergebnisse
Sensor 11400: Seite 1, 1000 Ergebnisse
Sensor 11400: Seite 2, 1000 Ergebnisse
Sensor 11400: Seite 3, 123 Ergebnisse
Sensor 11414: Seite 1, 1000 Ergebnisse
Sensor 11414: Seite 2, 1000 Ergebnisse
Sensor 11414: Seite 3, 148 Ergebnisse
Sensor 11442: Seite 1, 1000 Ergebnisse
Sensor 11442: Seite 2, 1000 Ergebnisse
Sensor 11442: Seite 3, 147 Ergebnisse
Sensor 11467: Seite 1, 1000 Ergebnisse
Sensor 11467: Seite 2, 1000 Ergebnisse
Sensor 11467: Seite 3, 148 Ergebnisse
Sensor 11470: Seite 1, 1000 Ergebnisse
Sensor 11470: Seite 2, 1000 Ergebnisse
Sensor 11470: Seite 3, 146 Ergebnisse
Sensor 11501: Seite 1, 1000 Ergebnisse
Sensor 11501: Seite 2, 1000 Ergebnisse
Sensor 11501: Seite 3, 145 Ergebnisse
Sensor 11510: Seite 1, 1000 Ergebnisse
Sensor 11510: Seite 2, 1000 Ergebnisse
Sensor 11510: Seite 3, 136 Ergebnisse
Sensor 11527: Seite 1, 1000 Ergebnisse
Sensor 11527: Seite 2, 1000 Ergebnisse
Sensor 11527: Seite 3, 145 Ergebnisse
Sensor 11540: Seite 1, 1000 Ergebnisse
Sensor 11540: Seite 2, 1000 Ergebnisse
Sensor 11540: Seite 3, 148 Ergebnisse
Sensor 11541: Seite 1, 1000 Ergebnisse
Sensor 11541: Seite 2, 1000 Ergebnisse
Sensor 11541: Seite 3, 144 Ergebnisse
Sensor 11608: Seite 1, 1000 Ergebnisse
Sensor 11608: Seite 2, 1000 Ergebnisse
Sensor 11608: Seite 3, 145 Ergebnisse
Sensor 11572: Seite 1, 1000 Ergebnisse
Sensor 11572: Seite 2, 1000 Ergebnisse
Sensor 11572: Seite 3, 144 Ergebnisse
Sensor 11575: Seite 1, 1000 Ergebnisse
Sensor 11575: Seite 2, 1000 Ergebnisse
Sensor 11575: Seite 3, 147 Ergebnisse
Sensor 11595: Seite 1, 1000 Ergebnisse
Sensor 11595: Seite 2, 1000 Ergebnisse
Sensor 11595: Seite 3, 144 Ergebnisse
Sensor 11613: Seite 1, 1000 Ergebnisse
Sensor 11613: Seite 2, 1000 Ergebnisse
Sensor 11613: Seite 3, 147 Ergebnisse
Sensor 11619: Seite 1, 1000 Ergebnisse
Sensor 11619: Seite 2, 1000 Ergebnisse
Sensor 11619: Seite 3, 138 Ergebnisse
Sensor 11411: Seite 1, 1000 Ergebnisse
Sensor 11411: Seite 2, 1000 Ergebnisse
Sensor 11411: Seite 3, 85 Ergebnisse
Sensor 11557: Seite 1, 1000 Ergebnisse
Sensor 11557: Seite 2, 1000 Ergebnisse
Sensor 11557: Seite 3, 81 Ergebnisse
Sensor 11271: Seite 1, 1000 Ergebnisse
Sensor 11271: Seite 2, 907 Ergebnisse
Sensor 11172: Seite 1, 1000 Ergebnisse
Sensor 11172: Seite 2, 753 Ergebnisse
Sensor 11583: Seite 1, 1000 Ergebnisse
Sensor 11583: Seite 2, 724 Ergebnisse
Sensor 11249: Seite 1, 1000 Ergebnisse
Sensor 11249: Seite 2, 573 Ergebnisse
Sensor 11616: Seite 1, 1000 Ergebnisse
Sensor 11616: Seite 2, 563 Ergebnisse
Sensor 11048: Seite 1, 1000 Ergebnisse
Sensor 11048: Seite 2, 458 Ergebnisse
Sensor 11143: Seite 1, 1000 Ergebnisse
Sensor 11143: Seite 2, 461 Ergebnisse
Sensor 11228: Seite 1, 1000 Ergebnisse
Sensor 11228: Seite 2, 455 Ergebnisse
Sensor 11253: Seite 1, 140 Ergebnisse
Sensor 11297: Seite 1, 1000 Ergebnisse
Sensor 11297: Seite 2, 460 Ergebnisse
Sensor 11325: Seite 1, 1000 Ergebnisse
Sensor 11325: Seite 2, 459 Ergebnisse
Sensor 11407: Seite 1, 1000 Ergebnisse
Sensor 11407: Seite 2, 441 Ergebnisse
Sensor 11449: Seite 1, 1000 Ergebnisse
Sensor 11449: Seite 2, 457 Ergebnisse
Sensor 11459: Seite 1, 1000 Ergebnisse
Sensor 11459: Seite 2, 392 Ergebnisse
Sensor 11487: Seite 1, 1000 Ergebnisse
Sensor 11487: Seite 2, 401 Ergebnisse
Sensor 11511: Seite 1, 1000 Ergebnisse
Sensor 11511: Seite 2, 451 Ergebnisse
Sensor 11513: Seite 1, 974 Ergebnisse
Sensor 11524: Seite 1, 1000 Ergebnisse
Sensor 11524: Seite 2, 455 Ergebnisse
Sensor 11561: Seite 1, 1000 Ergebnisse
Sensor 11561: Seite 2, 460 Ergebnisse
Sensor 11588: Seite 1, 1000 Ergebnisse
Sensor 11588: Seite 2, 439 Ergebnisse
Sensor 11601: Seite 1, 1000 Ergebnisse
Sensor 11601: Seite 2, 439 Ergebnisse
Sensor 11603: Seite 1, 1000 Ergebnisse
Sensor 11603: Seite 2, 453 Ergebnisse
Sensor 11238: Seite 1, 1000 Ergebnisse
Sensor 11238: Seite 2, 450 Ergebnisse
Sensor 11280: Seite 1, 1000 Ergebnisse
Sensor 11280: Seite 2, 455 Ergebnisse
Sensor 11303: Seite 1, 1000 Ergebnisse
Sensor 11303: Seite 2, 393 Ergebnisse
Sensor 11634: Seite 1, 1000 Ergebnisse
Sensor 11634: Seite 2, 454 Ergebnisse
Sensor 11314: Seite 1, 1000 Ergebnisse
Sensor 11314: Seite 2, 414 Ergebnisse
Sensor 11491: Seite 1, 1000 Ergebnisse
Sensor 11491: Seite 2, 230 Ergebnisse
Sensor 11332: Seite 1, 748 Ergebnisse
Sensor 11153: Seite 1, 520 Ergebnisse
Sensor 11308: Seite 1, 392 Ergebnisse
Sensor 11147: Seite 1, 134 Ergebnisse
Sensor 11285: Seite 1, 134 Ergebnisse
Sensor 11424: Seite 1, 134 Ergebnisse
Sensor 11532: Seite 1, 134 Ergebnisse
Sensor 11535: Seite 1, 134 Ergebnisse
Sensor 11329: Seite 1, 1000 Ergebnisse
Sensor 11329: Seite 2, 1000 Ergebnisse
Sensor 11329: Seite 3, 85 Ergebnisse
Sensor 5078693: Seite 1, 962 Ergebnisse
Sensor 5078847: Seite 1, 962 Ergebnisse
Sensor 5078672: Seite 1, 962 Ergebnisse
Sensor 5078404: Seite 1, 962 Ergebnisse
Sensor 5078853: Seite 1, 962 Ergebnisse
Sensor 5078455: Seite 1, 962 Ergebnisse
Sensor 5078451: Seite 1, 961 Ergebnisse
Sensor 5078441: Seite 1, 962 Ergebnisse
Sensor 5078634: Seite 1, 951 Ergebnisse
Sensor 5078865: Seite 1, 962 Ergebnisse
Sensor 5078879: Seite 1, 962 Ergebnisse
Sensor 5078381: Seite 1, 961 Ergebnisse
Sensor 5078496: Seite 1, 961 Ergebnisse
Sensor 5078963: Seite 1, 902 Ergebnisse
Sensor 5078929: Seite 1, 872 Ergebnisse
Sensor 5078715: Seite 1, 597 Ergebnisse
Sensor 5079013: Seite 1, 270 Ergebnisse
Sensor 5078486: Seite 1, 273 Ergebnisse
Sensor 5078387: Seite 1, 273 Ergebnisse
Sensor 5078303: Seite 1, 273 Ergebnisse
Sensor 5078827: Seite 1, 272 Ergebnisse
Sensor 5078556: Seite 1, 270 Ergebnisse
Sensor 7775386: Seite 1, 696 Ergebnisse
Sensor 7773561: Seite 1, 694 Ergebnisse
Sensor 7775997: Seite 1, 696 Ergebnisse
Sensor 7773992: Seite 1, 694 Ergebnisse
Sensor 7773678: Seite 1, 694 Ergebnisse
Sensor 7773413: Seite 1, 693 Ergebnisse
Sensor 7775747: Seite 1, 635 Ergebnisse
Sensor 7773272: Seite 1, 694 Ergebnisse
Sensor 7773539: Seite 1, 694 Ergebnisse
Sensor 7773592: Seite 1, 693 Ergebnisse
Sensor 7775259: Seite 1, 694 Ergebnisse
Sensor 7774907: Seite 1, 693 Ergebnisse
Sensor 7775380: Seite 1, 692 Ergebnisse
Sensor 7775038: Seite 1, 693 Ergebnisse
Sensor 7773015: Seite 1, 694 Ergebnisse
Sensor 7773755: Seite 1, 693 Ergebnisse
Sensor 7773942: Seite 1, 694 Ergebnisse
Sensor 7773545: Seite 1, 693 Ergebnisse
Sensor 7775503: Seite 1, 696 Ergebnisse
Sensor 7773720: Seite 1, 693 Ergebnisse
Sensor 7776000: Seite 1, 693 Ergebnisse
Sensor 7772988: Seite 1, 693 Ergebnisse
Sensor 7775101: Seite 1, 694 Ergebnisse
Sensor 7775532: Seite 1, 694 Ergebnisse
Sensor 7774824: Seite 1, 635 Ergebnisse
Sensor 7775227: Seite 1, 694 Ergebnisse
Sensor 7773275: Seite 1, 696 Ergebnisse
Sensor 7775932: Seite 1, 694 Ergebnisse
Sensor 7773530: Seite 1, 694 Ergebnisse
Sensor 7774435: Seite 1, 693 Ergebnisse
Sensor 7772928: Seite 1, 693 Ergebnisse
Sensor 7772977: Seite 1, 693 Ergebnisse
Sensor 7774127: Seite 1, 693 Ergebnisse
Sensor 7775115: Seite 1, 693 Ergebnisse
Sensor 7773170: Seite 1, 693 Ergebnisse
Sensor 7775910: Seite 1, 697 Ergebnisse
Sensor 7773204: Seite 1, 694 Ergebnisse
Sensor 7774517: Seite 1, 693 Ergebnisse
Sensor 7773360: Seite 1, 696 Ergebnisse
Sensor 7773770: Seite 1, 626 Ergebnisse
Sensor 7775935: Seite 1, 694 Ergebnisse
Sensor 7774065: Seite 1, 693 Ergebnisse
Sensor 7773569: Seite 1, 626 Ergebnisse
Sensor 7775922: Seite 1, 694 Ergebnisse
Sensor 7775513: Seite 1, 690 Ergebnisse
Sensor 7773457: Seite 1, 694 Ergebnisse
Sensor 7775913: Seite 1, 697 Ergebnisse
Sensor 7777043: Seite 1, 691 Ergebnisse
Sensor 7775470: Seite 1, 697 Ergebnisse
Sensor 7773705: Seite 1, 693 Ergebnisse
Sensor 7774794: Seite 1, 694 Ergebnisse
Sensor 7773587: Seite 1, 694 Ergebnisse
Sensor 8613421: Seite 1, 653 Ergebnisse
Sensor 7775646: Seite 1, 693 Ergebnisse
Sensor 7774492: Seite 1, 694 Ergebnisse
Sensor 7772904: Seite 1, 693 Ergebnisse
Sensor 7772987: Seite 1, 694 Ergebnisse
Sensor 7775698: Seite 1, 747 Ergebnisse
Sensor 7774987: Seite 1, 689 Ergebnisse
Sensor 7773894: Seite 1, 286 Ergebnisse
Sensor 7774999: Seite 1, 277 Ergebnisse
Sensor 7944831: Seite 1, 6 Ergebnisse
Sensor 7944804: Seite 1, 6 Ergebnisse
Sensor 7944823: Seite 1, 6 Ergebnisse
Sensor 7944801: Seite 1, 6 Ergebnisse
Sensor 7944814: Seite 1, 6 Ergebnisse
Sensor 7944820: Seite 1, 6 Ergebnisse
Sensor 7944817: Seite 1, 2 Ergebnisse
Sensor 7944812: Seite 1, 6 Ergebnisse
Sensor 9440299: Seite 1, 638 Ergebnisse
Sensor 9440301: Seite 1, 585 Ergebnisse
Sensor 9445107: Seite 1, 527 Ergebnisse
Sensor 11597870: Seite 1, 338 Ergebnisse
Sensor 11609498: Seite 1, 430 Ergebnisse
Sensor 11735551: Seite 1, 76 Ergebnisse
Sensor 12384602: Seite 1, 252 Ergebnisse
Sensor 12384601: Seite 1, 346 Ergebnisse
Sensor 12389002: Seite 1, 250 Ergebnisse
Sensor 13388774: Seite 1, 243 Ergebnisse
Sensor 13388778: Seite 1, 243 Ergebnisse
Sensor 14776823: Seite 1, 91 Ergebnisse
Sensor 14781509: Seite 1, 91 Ergebnisse
Sensor 14931945: Seite 1, 75 Ergebnisse
266522

[{'date': '2016-11-18', 'value': 18.846153846153847},
 {'date': '2016-11-19', 'value': 14.76923076923077},
 {'date': '2016-11-20', 'value': 6.076923076923077},
 {'date': '2016-11-21', 'value': 9.076923076923077},
 {'date': '2016-11-22', 'value': 9.2},
 {'date': '2016-11-23', 'value': 30.076923076923077},
 {'date': '2016-11-25', 'value': 27.785714285714285},
 {'date': '2016-11-26', 'value': 27.214285714285715},
 {'date': '2016-11-27', 'value': 11.357142857142858},
 {'date': '2016-11-28', 'value': 11.857142857142858},
 {'date': '2016-11-29', 'value': 21.785714285714285},
 {'date': '2016-11-30', 'value': 40.92857142857143},
 {'date': '2016-12-01', 'value': 12.75},
 {'date': '2016-12-02', 'value': 10.3},
 {'date': '2016-12-03', 'value': 28.23076923076923},
 {'date': '2016-12-04', 'value': 26.615384615384617},
 {'date': '2016-12-05', 'value': 43.5},
 {'date': '2016-12-06', 'value': 34.55555555555556},
 {'date': '2016-12-07', 'value': 39.84615384615385},
 {'date': '2016-12-10', 'value': 40.0},
 {'date': '2016-12-11', 'value': 19.076923076923077},
 {'date': '2016-12-12', 'value': 17.0},
 {'date': '2017-02-18', 'value': 19.66846510470588},
 {'date': '2017-02-19', 'value': 18.385871447499998},
 {'date': '2017-02-20', 'value': 22.21443525625},
 {'date': '2017-02-21', 'value': 11.047458585833333},
 {'date': '2017-02-22', 'value': 11.95181274},
 {'date': '2017-02-23', 'value': 12.147198590869564},
 {'date': '2017-02-24', 'value': 5.493849751666666},
 {'date': '2017-02-25', 'value': 11.609193620416669},
 {'date': '2017-02-26', 'value': 17.991461969166668},
 {'date': '2017-02-27', 'value': 16.728553450833335},
 {'date': '2017-02-28', 'value': 9.756662643750001},
 {'date': '2017-03-01', 'value': 7.143200195833333},
 {'date': '2017-03-02', 'value': 7.167103645416668},
 {'date': '2017-03-03', 'value': 8.17105577125},
 {'date': '2017-03-04', 'value': 2.3744267391666667},
 {'date': '2017-03-05', 'value': 8.206911224999999},
 {'date': '2017-03-06', 'value': 8.837511570714286},
 {'date': '2017-03-07', 'value': 10.738703395624999},
 {'date': '2017-03-08', 'value': 22.043126081666667},
 {'date': '2017-03-09', 'value': 13.433837152916666},
 {'date': '2017-03-10', 'value': 5.628506862666666},
 {'date': '2017-03-12', 'value': 16.91693693857143},
 {'date': '2017-03-13', 'value': 20.310113148750002},
 {'date': '2017-03-14', 'value': 21.56106936625},
 {'date': '2017-03-15', 'value': 20.40971183333333},
 {'date': '2017-03-16', 'value': 26.65652525},
 {'date': '2017-03-17', 'value': 17.481517471666667},
 {'date': '2017-03-18', 'value': 3.6612384891666667},
 {'date': '2017-03-19', 'value': 4.848451890833332},
 {'date': '2017-03-20', 'value': 11.7087919675},
 {'date': '2017-03-21', 'value': 13.764503833749998},
 {'date': '2017-03-22', 'value': 9.828373986249998},
 {'date': '2017-03-23', 'value': 13.728648461250001},
 {'date': '2017-03-24', 'value': 37.86334228},
 {'date': '2017-03-27', 'value': 26.321874897083333},
 {'date': '2017-03-28', 'value': 18.166754722916668},
 {'date': '2017-03-29', 'value': 14.150946021666664},
 {'date': '2017-03-30', 'value': 11.525531113749999},
 {'date': '2017-03-31', 'value': 11.087297936249998},
 {'date': '2017-04-01', 'value': 3.5775758625000003},
 {'date': '2017-04-02', 'value': 12.286462962916668},
 {'date': '2017-04-03', 'value': 15.64890631},
 {'date': '2017-04-04', 'value': 4.079551935},
 {'date': '2017-04-05', 'value': 3.924178331666667},
 {'date': '2017-04-06', 'value': 8.159103810833333},
 {'date': '2017-04-07', 'value': 7.489802241666667},
 {'date': '2017-04-08', 'value': 7.326460819166667},
 {'date': '2017-04-09', 'value': 12.656969150416664},
 {'date': '2017-04-10', 'value': 17.481517593333333},
 {'date': '2017-04-11', 'value': 8.31846143791667},
 {'date': '2017-04-12', 'value': 16.063235421666665},
 {'date': '2017-04-13', 'value': 17.294272341666666},
 {'date': '2017-04-14', 'value': 16.142914453750002},
 {'date': '2017-04-15', 'value': 11.75261561},
 {'date': '2017-04-16', 'value': 3.740917205833334},
 {'date': '2017-04-17', 'value': 4.083535889999999},
 {'date': '2017-04-18', 'value': 6.2531881579999995},
 {'date': '2017-04-19', 'value': 8.206911033333334},
 {'date': '2017-04-20', 'value': 6.9200993566666655},
 {'date': '2017-04-21', 'value': 7.657127777083335},
 {'date': '2017-04-22', 'value': 8.995730598333333},
 {'date': '2017-04-23', 'value': 8.031617879999999},
 {'date': '2017-04-24', 'value': 11.99961965681818},
 {'date': '2017-04-25', 'value': 10.151072581666666},
 {'date': '2017-04-26', 'value': 9.378188411666667},
 {'date': '2017-04-27', 'value': 9.8363417375},
 {'date': '2017-04-28', 'value': 5.66515896625},
 {'date': '2017-04-29', 'value': 4.676004387619047},
 {'date': '2017-05-02', 'value': 11.240015587222222},
 {'date': '2017-05-03', 'value': 35.05864842666667},
 {'date': '2017-05-11', 'value': 6.31055688888889},
 {'date': '2017-05-14', 'value': 8.318461415},
 {'date': '2017-05-15', 'value': 7.783889375454544},
 {'date': '2017-05-16', 'value': 8.378220535},
 {'date': '2017-05-17', 'value': 14.355834071428571},
 {'date': '2017-05-18', 'value': 4.028557469333333},
 {'date': '2017-05-24', 'value': 9.665756743181818},
 {'date': '2017-05-25', 'value': 3.6731903225},
 {'date': '2017-05-26', 'value': 8.437979615416666},
 {'date': '2017-05-27', 'value': 7.97584283},
 {'date': '2017-05-28', 'value': 4.840484001250001},
 {'date': '2017-05-29', 'value': 7.824453242083334},
 {'date': '2017-05-30', 'value': 9.963827596249999},
 {'date': '2017-05-31', 'value': 5.905333618571428},
 {'date': '2017-06-01', 'value': 7.262544773043477},
 {'date': '2017-06-02', 'value': 9.254686710833331},
 {'date': '2017-06-03', 'value': 6.238845961666667},
 {'date': '2017-06-04', 'value': 5.9679382612500005},
 {'date': '2017-06-05', 'value': 3.1074712150000003},
 {'date': '2017-06-06', 'value': 5.577512524166667},
 {'date': '2017-06-07', 'value': 2.6254147704166666},
 {'date': '2017-06-08', 'value': 4.5536404458333335},
 {'date': '2017-06-09', 'value': 7.657127814999999},
 {'date': '2017-06-10', 'value': 6.860340224583333},
 {'date': '2017-06-11', 'value': 5.788660921666666},
 {'date': '2017-06-12', 'value': 8.78059824},
 {'date': '2017-06-13', 'value': 4.374363380000001},
 {'date': '2017-06-14', 'value': 6.677079198333334},
 {'date': '2017-06-15', 'value': 8.94792349875},
 {'date': '2017-06-16', 'value': 5.864356},
 {'date': '2017-06-17', 'value': 2.908274319166667},
 {'date': '2017-06-18', 'value': 3.3664272299999998},
 {'date': '2017-06-19', 'value': 8.254718419583334},
 {'date': '2017-06-20', 'value': 8.430011627083331},
 {'date': '2017-06-21', 'value': 8.274638192916667},
 {'date': '2017-06-22', 'value': 29.78391647},
 {'date': '2017-06-23', 'value': 7.2623557159090915},
 {'date': '2017-06-24', 'value': 9.09248369952381},
 {'date': '2017-06-25', 'value': 6.568716116500001},
 {'date': '2017-06-26', 'value': 4.849020920000001},
 {'date': '2017-06-27', 'value': 7.971858915000001},
 {'date': '2017-06-28', 'value': 5.2240285604545456},
 {'date': '2017-06-29', 'value': 3.5855437487499997},
 {'date': '2017-06-30', 'value': 4.426154462083333},
 {'date': '2017-07-01', 'value': 5.69133923904762},
 {'date': '2017-07-02', 'value': 5.250105155454547},
 {'date': '2017-07-03', 'value': 4.325417866666666},
 {'date': '2017-07-04', 'value': 12.53674812470588},
 {'date': '2017-07-05', 'value': 10.957421727},
 {'date': '2017-07-06', 'value': 6.36519374952381},
 {'date': '2017-07-07', 'value': 11.926650694210524},
 {'date': '2017-07-08', 'value': 4.6623450647619045},
 {'date': '2017-07-09', 'value': 8.084737018333332},
 {'date': '2017-07-10', 'value': 6.788629357619047},
 {'date': '2017-07-11', 'value': 5.439402668888889},
 {'date': '2017-07-12', 'value': 8.371580622777778},
 {'date': '2017-07-13', 'value': 3.5878201899999995},
 {'date': '2017-07-14', 'value': 9.843740403333332},
 {'date': '2017-07-15', 'value': 4.011824990416667},
 {'date': '2017-07-16', 'value': 4.358427519166667},
 {'date': '2017-07-17', 'value': 9.680968048750001},
 {'date': '2017-07-18', 'value': 9.35656160952381},
 {'date': '2017-07-19', 'value': 10.909159120952381},
 {'date': '2017-07-20', 'value': 9.695310146},
 {'date': '2020-03-16', 'value': 31.202198023333334},
 {'date': '2020-03-17', 'value': 24.220890777727266},
 {'date': '2020-03-18', 'value': 15.277534188695652},
 {'date': '2020-03-19', 'value': 15.698162224999999},
 {'date': '2020-03-20', 'value': 15.963068026666665},
 {'date': '2020-03-21', 'value': 6.820500945714284},
 {'date': '2020-03-22', 'value': 2.454105471666667},
 {'date': '2020-03-23', 'value': 6.747651777142857},
 {'date': '2020-03-24', 'value': 8.509690518636365},
 {'date': '2020-03-25', 'value': 10.869630137272724},
 {'date': '2020-03-26', 'value': 14.13790754318182},
 {'date': '2020-03-27', 'value': 12.794130764285713},
 {'date': '2020-03-28', 'value': 10.413288143636365},
 {'date': '2020-03-29', 'value': 5.73231682904762},
 {'date': '2020-03-30', 'value': 4.8980699727272725},
 {'date': '2020-03-31', 'value': 9.922177331363635},
 {'date': '2020-04-01', 'value': 10.617555331363635},
 {'date': '2020-04-02', 'value': 12.764535627727271},
 {'date': '2020-04-03', 'value': 14.888543260952382},
 {'date': '2020-04-04', 'value': 10.491518036363637},
 {'date': '2020-04-05', 'value': 8.666150455454545},
 {'date': '2020-04-06', 'value': 11.287063922380952},
 {'date': '2020-04-07', 'value': 2.67720603},
 {'date': '2020-04-08', 'value': 9.9630307085},
 {'date': '2020-04-09', 'value': 15.646009158636366},
 {'date': '2020-04-10', 'value': 9.345278010000001},
 {'date': '2020-04-11', 'value': 7.662819061428571},
 {'date': '2020-04-12', 'value': 6.001982835454545},
 {'date': '2020-04-13', 'value': 4.202691788636363},
 {'date': '2020-04-14', 'value': 4.050577845909091},
 {'date': '2020-04-15', 'value': 11.212973112727276},
 {'date': '2020-04-16', 'value': 12.868842369090912},
 {'date': '2020-04-17', 'value': 11.260780438181817},
 {'date': '2020-04-18', 'value': 9.77440942},
 {'date': '2020-04-19', 'value': 7.636121550000001},
 {'date': '2020-04-20', 'value': 9.47887370181818},
 {'date': '2020-04-21', 'value': 10.873976165909092},
 {'date': '2020-04-22', 'value': 10.217092395238097},
 {'date': '2020-04-23', 'value': 10.512562478421051},
 {'date': '2020-04-24', 'value': 17.181925149},
 {'date': '2020-04-25', 'value': 4.525752856666666},
 {'date': '2020-04-26', 'value': 4.9241467065},
 {'date': '2020-04-27', 'value': 10.014360699473686},
 {'date': '2020-04-28', 'value': 10.914395113499998},
 {'date': '2020-04-29', 'value': 5.122205268571428},
 {'date': '2020-04-30', 'value': 3.3034809895},
 {'date': '2020-05-01', 'value': 1.775697822857143},
 {'date': '2020-05-02', 'value': 1.3768488105},
 {'date': '2020-05-03', 'value': 3.401144252857143},
 {'date': '2020-05-04', 'value': 11.245327427222222},
 {'date': '2020-05-05', 'value': 6.360640679047618},
 {'date': '2020-05-06', 'value': 4.650341581363635},
 {'date': '2020-05-07', 'value': 4.87633943},
 {'date': '2020-05-08', 'value': 13.236632209374998},
 {'date': '2020-05-09', 'value': 7.629030485789472},
 {'date': '2020-05-10', 'value': 8.070732967272725},
 {'date': '2020-05-11', 'value': 7.001588941818183},
 {'date': '2020-05-12', 'value': 2.781512792727273},
 {'date': '2020-05-13', 'value': 7.266701788000001},
 {'date': '2020-05-14', 'value': 5.710310362222223},
 {'date': '2020-05-15', 'value': 6.989923057894736},
 {'date': '2020-05-16', 'value': 5.019761319444445},
 {'date': '2020-05-17', 'value': 9.292818824761904},
 {'date': '2020-05-18', 'value': 6.74613406388889},
 {'date': '2020-05-19', 'value': 11.03592581105263},
 {'date': '2020-05-20', 'value': 5.513769435555556},
 {'date': '2020-05-21', 'value': 4.3026524042105265},
 {'date': '2020-05-22', 'value': 10.126030950000002},
 {'date': '2020-05-23', 'value': 6.342428367222222},
 {'date': '2020-05-24', 'value': 1.5202705655},
 {'date': '2020-05-25', 'value': 6.46080828857143},
 {'date': '2020-05-26', 'value': 3.5377364690909086},
 {'date': '2020-05-27', 'value': 3.524077292142857},
 {'date': '2020-05-28', 'value': 3.9338536571428575},
 {'date': '2020-05-29', 'value': 3.0034201788235295},
 {'date': '2020-05-31', 'value': 3.569608046666666},
 {'date': '2020-06-01', 'value': 1.8931671079999994},
 {'date': '2020-06-02', 'value': 6.322508910625001},
 {'date': '2020-06-03', 'value': 7.834764462352941},
 {'date': '2020-06-04', 'value': 2.4859770314285714},
 {'date': '2020-06-05', 'value': 4.679798504999999},
 {'date': '2020-06-07', 'value': 1.28123431},
 {'date': '2020-06-08', 'value': 2.7409489755555554},
 {'date': '2020-06-09', 'value': 4.423428654210526},
 {'date': '2020-06-10', 'value': 7.8738539880000005},
 {'date': '2020-06-11', 'value': 3.8245799547619055},
 {'date': '2020-06-12', 'value': 11.039797183076924},
 {'date': '2020-06-13', 'value': 5.182305761},
 {'date': '2020-06-14', 'value': 4.350459690000001},
 {'date': '2020-06-15', 'value': 3.405347189230769},
 {'date': '2020-06-16', 'value': 5.641255372727273},
 {'date': '2020-06-17', 'value': 5.910714421363635},
 {'date': '2020-06-18', 'value': 3.12715656},
 {'date': '2020-06-19', 'value': 4.752602988823528},
 {'date': '2020-06-20', 'value': 2.227817839},
 {'date': '2020-06-21', 'value': 0.7230846631249999},
 {'date': '2020-06-22', 'value': 3.136155648},
 {'date': '2020-06-23', 'value': 2.9428018622222223},
 {'date': '2020-06-24', 'value': 6.828000204117645},
 {'date': '2020-06-25', 'value': 2.103519007142857},
 {'date': '2020-06-26', 'value': 5.566129867142857},
 {'date': '2020-06-27', 'value': 5.317637034615384},
 {'date': '2020-06-28', 'value': 4.752040685},
 {'date': '2020-06-29', 'value': 8.3519264865},
 {'date': '2020-06-30', 'value': 5.131311417142858},
 {'date': '2020-07-01', 'value': 6.59177591},
 {'date': '2020-07-02', 'value': 4.971953974666666},
 {'date': '2020-07-04', 'value': 3.977563114},
 {'date': '2020-07-05', 'value': 5.2812949},
 {'date': '2020-07-06', 'value': 12.286463255},
 {'date': '2020-07-07', 'value': 5.109399820625},
 {'date': '2020-07-08', 'value': 7.681031361111113},
 {'date': '2020-07-09', 'value': 5.354411954999999},
 {'date': '2020-07-10', 'value': 6.716918534500001},
 {'date': '2020-07-11', 'value': 4.61681437},
 {'date': '2020-07-12', 'value': 1.1473740041176468},
 {'date': '2020-07-13', 'value': 5.206644040909091},
 {'date': '2020-07-14', 'value': 7.557891715909091},
 {'date': '2020-07-15', 'value': 6.060137998571428},
 {'date': '2020-07-16', 'value': 6.219495449047618},
 {'date': '2020-07-17', 'value': 4.285267973181818},
 {'date': '2020-07-18', 'value': 3.3321652864999995},
 {'date': '2020-07-19', 'value': 3.0596639421052636},
 {'date': '2020-07-20', 'value': 6.296897745714285},
 {'date': '2020-07-21', 'value': 7.123280195000001},
 {'date': '2020-07-22', 'value': 8.781436877368423},
 {'date': '2020-07-23', 'value': 8.291901715},
 {'date': '2020-07-24', 'value': 9.28764486909091},
 {'date': '2020-07-25', 'value': 5.5504216385},
 {'date': '2020-07-26', 'value': 6.525689533500001},
 {'date': '2020-07-27', 'value': 5.636909430454547},
 {'date': '2020-07-28', 'value': 8.611280578125001},
 {'date': '2020-07-29', 'value': 9.21086347888889},
 {'date': '2020-07-30', 'value': 9.435412601363637},
 {'date': '2020-07-31', 'value': 10.61320931736842},
 {'date': '2020-08-01', 'value': 3.8760646715384612},
 {'date': '2020-08-02', 'value': 6.827744358636363},
 {'date': '2020-08-03', 'value': 9.475900042631576},
 {'date': '2020-08-04', 'value': 4.2852679540909095},
 {'date': '2020-08-05', 'value': 0.430265255},
 {'date': '2020-08-06', 'value': 5.421342094000001},
 {'date': '2020-08-07', 'value': 9.53489036888889},
 {'date': '2020-08-08', 'value': 7.307679602857141},
 {'date': '2020-08-09', 'value': 5.949829503181818},
 {'date': '2020-08-10', 'value': 9.597874556666662},
 {'date': '2020-08-11', 'value': 10.95981205625},
 {'date': '2020-08-12', 'value': 3.9966860409999994},
 {'date': '2020-08-13', 'value': 7.885919662380952},
 {'date': '2020-08-14', 'value': 5.440920314761905},
 {'date': '2020-08-15', 'value': 3.4247374050000006},
 {'date': '2020-08-16', 'value': 2.4381697054999996},
 {'date': '2020-08-17', 'value': 11.008705654090907},
 {'date': '2020-08-18', 'value': 6.562174001052632},
 {'date': '2020-08-19', 'value': 5.549987054545454},
 {'date': '2020-08-20', 'value': 9.056058754285715},
 {'date': '2020-08-21', 'value': 7.539886267142857},
 {'date': '2020-08-22', 'value': 6.849017546842106},
 {'date': '2020-08-23', 'value': 3.2340198411764707},
 {'date': '2020-08-24', 'value': 6.271441901818182},
 {'date': '2020-08-25', 'value': 6.932051095454545},
 {'date': '2020-08-26', 'value': 9.39932082},
 {'date': '2020-08-27', 'value': 3.681158178888889},
 {'date': '2020-08-28', 'value': 6.940743424999997},
 {'date': '2020-08-29', 'value': 4.5082236415},
 {'date': '2020-08-30', 'value': 5.063015274285713},
 {'date': '2020-08-31', 'value': 1.9792201405},
 {'date': '2020-09-01', 'value': 0.20426733318181817},
 {'date': '2020-09-02', 'value': 5.0962527485},
 {'date': '2020-09-03', 'value': 6.005501067142857},
 {'date': '2020-09-04', 'value': 2.151326355},
 {'date': '2020-09-05', 'value': 0.41114236000000004},
 {'date': '2020-09-06', 'value': 0.0},
 {'date': '2020-09-07', 'value': 1.7028486876190476},
 {'date': '2020-09-08', 'value': 5.337027604999999},
 {'date': '2020-09-09', 'value': 9.168927514736843},
 {'date': '2020-09-10', 'value': 15.389588416363639},
 {'date': '2020-09-11', 'value': 16.909424014000003},
 {'date': '2020-09-12', 'value': 12.36949661631579},
 {'date': '2020-09-13', 'value': 11.162992913},
 {'date': '2020-09-14', 'value': 19.193017190666662},
 {'date': '2020-09-15', 'value': 12.44113329647059},
 {'date': '2020-09-16', 'value': 16.586599370000002},
 {'date': '2020-09-17', 'value': 15.049722189333332},
 {'date': '2020-09-18', 'value': 11.346253920555556},
 {'date': '2020-09-19', 'value': 9.078824469047618},
 {'date': '2020-09-20', 'value': 7.643848042222225},
 {'date': '2020-09-21', 'value': 12.098046241764704},
 {'date': '2020-09-22', 'value': 9.439758556363635},
 {'date': '2020-09-23', 'value': 12.703069228095238},
 {'date': '2020-09-24', 'value': 14.381289715000001},
 {'date': '2020-09-25', 'value': 9.06828029},
 {'date': '2020-09-26', 'value': 4.024915064761904},
 {'date': '2020-09-27', 'value': 5.949829464090908},
 {'date': '2020-09-28', 'value': 12.807310502105267},
 {'date': '2020-09-29', 'value': 7.405777491818181},
 {'date': '2020-09-30', 'value': 12.107185835},
 {'date': '2020-10-01', 'value': 14.225312361111113},
 {'date': '2020-10-02', 'value': 9.893824118571427},
 {'date': '2020-10-03', 'value': 1.7927718474999998},
 {'date': '2020-10-04', 'value': 1.673253765},
 {'date': '2020-10-05', 'value': 16.841811107142856},
 {'date': '2020-10-06', 'value': 14.920207667727276},
 {'date': '2020-10-07', 'value': 11.295549302272729},
 {'date': '2020-10-08', 'value': 11.111410977368422},
 {'date': '2020-10-09', 'value': 18.46725754142857},
 {'date': '2020-10-10', 'value': 12.739493978571428},
 {'date': '2020-10-11', 'value': 4.857216574000001},
 {'date': '2020-10-12', 'value': 6.573496694166667},
 {'date': '2020-10-13', 'value': 6.992896703181817},
 {'date': '2020-10-14', 'value': 11.0673783525},
 {'date': '2020-10-15', 'value': 19.089434476499996},
 {'date': '2020-10-16', 'value': 8.777411043333334},
 {'date': '2020-10-18', 'value': 11.421586595454546},
 {'date': '2020-10-19', 'value': 16.18492709},
 {'date': '2020-10-20', 'value': 9.511366181428572},
 {'date': '2020-10-21', 'value': 20.791807300909095},
 {'date': '2020-10-22', 'value': 20.174659290909094},
 {'date': '2020-10-23', 'value': 16.067581908181822},
 {'date': '2020-10-24', 'value': 17.70992996444444},
 {'date': '2020-10-25', 'value': 10.772566836190476},
 {'date': '2020-10-26', 'value': 8.105984656666665},
 {'date': '2020-10-27', 'value': 17.428398525000002},
 {'date': '2020-10-28', 'value': 17.100653119500002},
 {'date': '2020-10-29', 'value': 16.218609000625},
 {'date': '2020-10-30', 'value': 12.783658548999998},
 {'date': '2020-10-31', 'value': 7.92475436117647},
 {'date': '2020-11-01', 'value': 11.08258983818182},

In [22]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_no2_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_no2_mean
0    2016-11-18        28.427506
1    2016-11-19        23.950704
2    2016-11-20        17.617347
3    2016-11-21        23.357076
4    2016-11-22        32.685498
...         ...              ...
2222 2026-02-24        13.665903
2223 2026-02-25        16.713599
2224 2026-02-26        18.059154
2225 2026-02-27        18.553076
2226 2026-02-28        15.477623

[2227 rows x 2 columns]

In [23]:
france_daily[["date", "france_no2_mean"]].to_csv(
    "daily_avg_austria_NO2.csv",
    index=False
)

## Cleaning

In [4]:
df = pd.read_csv("../romania/2daily_avg_romania_PM10.csv")

df = df[
    (df['value'] >= 0) & (df['value'] <= 100) & 
    (
        (~df['date'].between('2019-07-05', '2019-12-23')) | 
        (df['value'] >= 2)
    )
]

df.to_csv('cleaned_daily_avg_romania_PM10.csv', index=False)

## Monthly Data

In [5]:
df = pd.read_csv('../romania/cleaned_daily_avg_romania_PM10.csv')

df['date'] = pd.to_datetime(df['date'])

df['date'] = df['date'].dt.to_period('M')

df = df.groupby('date').agg(value=("value", "mean")).reset_index()

df.to_csv("monthly_avg_romania_PM10.csv", index=False)