# Get daily average values for air pollution in Poland from 2016-2026 using openAQ API

In [1]:
import requests
import pandas as pd 
import time

### List possible parameters (e.g. PM10, PM2.5, NO2)

In [2]:
api_url = "https://api.openaq.org/v3/parameters"

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, headers=headers)
response = response.json()

response

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 46},
 'results': [{'id': 1,
   'name': 'pm10',
   'units': 'µg/m³',
   'displayName': 'PM10',
   'description': 'Particulate matter less than 10 micrometers in diameter mass concentration'},
  {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': 'PM2.5',
   'description': 'Particulate matter less than 2.5 micrometers in diameter mass concentration'},
  {'id': 3,
   'name': 'o3',
   'units': 'µg/m³',
   'displayName': 'O₃ mass',
   'description': 'Ozone mass concentration'},
  {'id': 4,
   'name': 'co',
   'units': 'µg/m³',
   'displayName': 'CO mass',
   'description': 'Carbon Monoxide mass concentration'},
  {'id': 5,
   'name': 'no2',
   'units': 'µg/m³',
   'displayName': 'NO₂ mass',
   'description': 'Nitrogen Dioxide mass concentration'},
  {'id': 6,
   'name': 'so2',
   'units': 'µg/m³',
   'displayName': 'SO₂ mass',
   'description': 'Sulfur Dioxide mass concentration'},
  {'id': 7,
   'name': 'no2',
   'units': 'ppm',
   'displayName': 'NO₂',
   'description': 'Nitrogen Dioxide concentration'},
  {'id': 8,
   'name': 'co',
   'units': 'ppm',
   'displayName': 'CO',
   'description': 'Carbon Monoxide concentration'},
  {'id': 9,
   'name': 'so2',
   'units': 'ppm',
   'displayName': 'SO₂',
   'description': 'Sulfur Dioxide concentration'},
  {'id': 10,
   'name': 'o3',
   'units': 'ppm',
   'displayName': 'O₃',
   'description': 'Ozone concentration'},
  {'id': 11,
   'name': 'bc',
   'units': 'µg/m³',
   'displayName': 'BC',
   'description': 'Black Carbon mass concentration'},
  {'id': 15,
   'name': 'no2',
   'units': 'ppb',
   'displayName': 'NO₂',
   'description': None},
  {'id': 19,
   'name': 'pm1',
   'units': 'µg/m³',
   'displayName': 'PM1',
   'description': 'Particulate matter less than 1 micrometer in diameter mass concentration'},
  {'id': 21,
   'name': 'co2',
   'units': 'ppm',
   'displayName': 'CO₂',
   'description': 'Carbon Dioxide concentration'},
  {'id': 22,
   'name': 'wind_direction',
   'units': 'deg',
   'displayName': 'Wind direction',
   'description': 'Direction that the wind originates from'},
  {'id': 23,
   'name': 'nox',
   'units': 'ppb',
   'displayName': 'NOX',
   'description': None},
  {'id': 24,
   'name': 'no',
   'units': 'ppb',
   'displayName': 'NO',
   'description': None},
  {'id': 27,
   'name': 'nox',
   'units': 'µg/m³',
   'displayName': 'NOx mass',
   'description': 'Nitrogen Oxides mass concentration'},
  {'id': 28,
   'name': 'ch4',
   'units': 'ppm',
   'displayName': 'CH₄',
   'description': 'Methane concentration'},
  {'id': 32,
   'name': 'o3',
   'units': 'ppb',
   'displayName': 'O₃',
   'description': None},
  {'id': 33,
   'name': 'ufp',
   'units': 'particles/cm³',
   'displayName': 'UFP count',
   'description': 'Ultrafine Particles count concentration'},
  {'id': 34,
   'name': 'wind_speed',
   'units': 'm/s',
   'displayName': 'Wind speed',
   'description': 'Average wind speed in meters per second'},
  {'id': 35,
   'name': 'no',
   'units': 'ppm',
   'displayName': 'NO',
   'description': 'Nitrogen Monoxide concentration'},
  {'id': 95,
   'name': 'pressure',
   'units': 'hpa',
   'displayName': 'Atmospheric pressure',
   'description': 'Atmospheric or barometric pressure'},
  {'id': 97,
   'name': 'pm25-old',
   'units': 'ugm3',
   'displayName': None,
   'description': None},
  {'id': 98,
   'name': 'relativehumidity',
   'units': '%',
   'displayName': 'RH',
   'description': None},
  {'id': 100,
   'name': 'temperature',
   'units': 'c',
   'displayName': 'Temperature (C)',
   'description': None},
  {'id': 101,
   'name': 'so2',
   'units': 'ppb',
   'displayName': 'SO₂',
   'description': None},
  {'id': 102,
   'name': 'co',
   'units': 'ppb',
   'displayName': 'CO',
   'description': None},
  {'id': 125,
   'name': 'um003',
   'units': 'particles/cm³',
   'displayName': 'PM0.3 count',
   'description': None},
  {'id': 126,
   'name': 'um010',
   'units': 'particles/cm³',
   'displayName': 'PM1 count',
   'description': 'PM1 count'},
  {'id': 128,
   'name': 'temperature',
   'units': 'f',
   'displayName': 'Temperature (F)',
   'description': None},
  {'id': 130,
   'name': 'um025',
   'units': 'particles/cm³',
   'displayName': 'PM2.5 count',
   'description': 'PM2.5 count'},
  {'id': 132,
   'name': 'pressure',
   'units': 'mb',
   'displayName': 'Pressure',
   'description': None},
  {'id': 134,
   'name': 'humidity',
   'units': '%',
   'displayName': 'H',
   'description': None},
  {'id': 135,
   'name': 'um100',
   'units': 'particles/cm³',
   'displayName': 'PM10 count',
   'description': 'PM10 count'},
  {'id': 19840,
   'name': 'nox',
   'units': 'ppm',
   'displayName': 'NOx',
   'description': 'Nitrogen Oxides concentration'},
  {'id': 19843,
   'name': 'no',
   'units': 'µg/m³',
   'displayName': 'NO mass',
   'description': 'Nitrogen Monoxide mass concentration'},
  {'id': 19844,
   'name': 'pm4',
   'units': 'µg/m³',
   'displayName': 'PM4.0',
   'description': 'Particulate matter less than 4 micrometers in diameter mass concentration'},
  {'id': 19860,
   'name': 'pm25',
   'units': 'ppm',
   'displayName': None,
   'description': None},
  {'id': 19861,
   'name': 'bc_375',
   'units': 'ng/m³',
   'displayName': 'BC 375nm',
   'description': 'Black Carbon mass concentration 375nm '},
  {'id': 19862,
   'name': 'bc_470',
   'units': 'ng/m³',
   'displayName': 'BC 470nm',
   'description': 'Black Carbon mass concentration 470nm '},
  {'id': 19863,
   'name': 'bc_528',
   'units': 'ng/m³',
   'displayName': 'BC 528nm',
   'description': 'Black Carbon mass concentration 528nm '},
  {'id': 19864,
   'name': 'bc_625',
   'units': 'ng/m³',
   'displayName': 'BC 625nm',
   'description': 'Black Carbon mass concentration 625nm '},
  {'id': 19865,
   'name': 'bc_880',
   'units': 'ng/m³',
   'displayName': 'BC 880nm',
   'description': 'Black Carbon mass concentration 880nm '},
  {'id': 19866,
   'name': 'bc_370',
   'units': 'ng/m³',
   'displayName': 'BC 370nm',
   'description': 'Black Carbon mass concentration 375nm '}]}

# PM10

### Get all stations located in Poland that measure PM10
Stations are sorted descending by the duration of their measurements

In [29]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "IT",   # only consider stations located in Poland
    "parameters_id": 1,   # PM10 
    #"monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm10 = df_sorted

df_top_pm10

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
10,7236,ISONZO,CORSO ISONZO-VIALE CAVOUR - Ferrara (FE),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 20851, 'name': 'co µg/m³', 'parameter'...","{'latitude': 44.84249999990541, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[11.613060000433586, 44.84249999990541, 11.613...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
64,7597,DELTA CERVIA,"VIA JELENIA GORA, 6 - Cervia (RA)",Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22135, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.283889000018235, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[12.332222000093372, 44.283889000018235, 12.33...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
66,7599,BESENZONE,VIA PAVESA BERSANO DI BESENZONE - Besenzone (PC),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22075, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.989444000052735, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[10.019166999885284, 44.989444000052735, 10.01...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
75,7609,CASTELLARANO,VIA REVERBERI - Castellarano (RE),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22091, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.516111000289975, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[10.73388899989651, 44.516111000289975, 10.733...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
67,7600,CORTE BRUGNATELLA,Loc. Carana - Corte Brugnatella (PC) - Corte B...,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22063, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.734729999698565, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[9.366930000033793, 44.734729999698565, 9.3669...",None,2017-11-01 23:00:00+00:00,2025-11-27 10:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,3292229,Casalmaggiore,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 11264, 'name': 'Leonardo'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 24, 'name': 'AirGradient Open Air Gene...","[{'id': 11475739, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 44.9855387, 'longitude': 10.4170163}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[10.4170163, 44.9855387, 10.4170163, 44.9855387]",None,2024-11-29 17:00:00+00:00,2026-03-06 12:00:00+00:00
350,3293387,Milano,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 11265, 'name': 'Matteo'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 24, 'name': 'AirGradient Open Air Gene...","[{'id': 11484309, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 45.4654219, 'longitude': 9.1859243}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[9.1859243, 45.4654219, 9.1859243, 45.4654219]",None,2024-11-30 12:00:00+00:00,2026-01-20 00:00:00+00:00
351,3301196,Cella,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 11509, 'name': 'Unknown Person'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 24, 'name': 'AirGradient Open Air Gene...","[{'id': 11542058, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 45.698907274171056, 'longitude': ...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[9.379909078234926, 45.698907274171056, 9.3799...",None,2024-12-05 14:00:00+00:00,2026-03-06 12:00:00+00:00
352,3350351,Cittadella (PD),NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 11509, 'name': 'Unknown Person'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 11901477, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 45.6628012, 'longitude': 11.7569295}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[11.7569295, 45.6628012, 11.7569295, 45.6628012]",None,2025-01-05 00:00:00+00:00,2026-03-06 12:00:00+00:00
0,5369,Tarquinia,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 151, 'name': 'ARPA Lazio'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13965, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 42.240389, 'longitude': 11.766344}",None,"[11.766344, 42.240389, 11.766344, 42.240389]",None,NaT,NaT

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [31]:
rows = []

for _, station in df_top_pm10.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM10 behalten
        if sensor["parameter"]["id"] == 1:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm10_sensors = pd.DataFrame(rows)

df_pm10_sensors

     station_id       station_name  sensor_id sensor_name
0          7236             ISONZO      22165  pm10 µg/m³
1          7597       DELTA CERVIA      22136  pm10 µg/m³
2          7599          BESENZONE      22070  pm10 µg/m³
3          7609       CASTELLARANO      22089  pm10 µg/m³
4          7600  CORTE BRUGNATELLA      22061  pm10 µg/m³
..          ...                ...        ...         ...
350     3292229      Casalmaggiore   11475725  pm10 µg/m³
351     3293387             Milano   11484313  pm10 µg/m³
352     3301196              Cella   11542072  pm10 µg/m³
353     3350351    Cittadella (PD)   11901444  pm10 µg/m³
354        5369          Tarquinia      13964  pm10 µg/m³

[355 rows x 4 columns]

In [32]:
sensor_ids = df_pm10_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

355

[22165,
 22136,
 22070,
 22089,
 22061,
 22104,
 22138,
 22197,
 22108,
 22071,
 22171,
 22133,
 22113,
 22199,
 22190,
 22066,
 22175,
 22069,
 22164,
 22079,
 22085,
 22096,
 22093,
 22099,
 22109,
 22177,
 22119,
 22117,
 22146,
 22124,
 22153,
 22130,
 22151,
 22148,
 22154,
 22163,
 22162,
 22186,
 22189,
 20602,
 20607,
 20606,
 20595,
 20598,
 22195,
 21803,
 21764,
 21766,
 21767,
 21774,
 21770,
 21772,
 21811,
 21804,
 21807,
 21808,
 21809,
 21810,
 21812,
 21814,
 21815,
 21816,
 21817,
 21818,
 21821,
 21820,
 21822,
 21825,
 21826,
 21828,
 21831,
 21832,
 21834,
 21835,
 21837,
 21838,
 21840,
 21845,
 21847,
 21848,
 21849,
 21853,
 21855,
 21856,
 21859,
 21860,
 21862,
 21762,
 21763,
 7775455,
 23468,
 23466,
 23484,
 22631,
 7775967,
 7774118,
 7775189,
 7772729,
 7773685,
 5078278,
 7775965,
 7773037,
 7772822,
 5078297,
 7773748,
 7775580,
 5078276,
 7774064,
 7774499,
 7775117,
 7774393,
 7775306,
 7774513,
 5078282,
 15538674,
 7773821,
 7776031,
 7774792,
 7774588,
 7773415,
 7773803,
 7773675,
 7774822,
 7775843,
 7774089,
 7773410,
 7772990,
 7773858,
 7773214,
 7774398,
 7773966,
 7774039,
 7772717,
 7774226,
 7775798,
 7775900,
 7774070,
 7773394,
 7775985,
 7773708,
 7775349,
 7772792,
 15538685,
 15545434,
 15538702,
 15545438,
 5078285,
 5078283,
 5078288,
 5078298,
 24421,
 5078280,
 5078273,
 5078299,
 5078272,
 5078296,
 5078263,
 5078266,
 5078268,
 5078265,
 5078289,
 14392780,
 15538669,
 15567072,
 7776020,
 24512,
 24705,
 24698,
 24701,
 7777171,
 22209,
 22604,
 22635,
 22637,
 22844,
 15538694,
 15545435,
 15545440,
 7774637,
 24440,
 24569,
 7773310,
 24322,
 23989,
 7775924,
 1764523,
 8613280,
 24313,
 24382,
 7531552,
 24416,
 24417,
 12907941,
 5078281,
 7775010,
 24532,
 24535,
 24543,
 8613070,
 24562,
 5078275,
 1702603,
 7950621,
 15538671,
 1764647,
 15538687,
 15538677,
 15545430,
 15545432,
 15586346,
 15556738,
 15545429,
 15545433,
 15538701,
 15596004,
 25020,
 15538688,
 15538666,
 15538700,
 15556739,
 15538690,
 15538672,
 15579566,
 15538689,
 7531550,
 22274,
 1555181,
 24490,
 24506,
 22260,
 22730,
 15545431,
 5078277,
 5079211,
 24410,
 5078290,
 5078295,
 5078269,
 24763,
 15538691,
 22263,
 7775366,
 5078300,
 22632,
 15538698,
 1287749,
 1288174,
 1288171,
 1288160,
 1288166,
 1288158,
 15538705,
 5079444,
 5079451,
 5079457,
 5079461,
 5079450,
 5078551,
 5078720,
 5078937,
 5079209,
 7777633,
 5104465,
 15538664,
 5079066,
 15545439,
 5078843,
 5078508,
 5078739,
 7970860,
 7979466,
 7970841,
 7978348,
 7531553,
 7773079,
 7774815,
 7775783,
 7775830,
 7774971,
 7775511,
 7774772,
 7775712,
 8622697,
 7775388,
 7774958,
 7775673,
 7775275,
 7772912,
 7772889,
 7774204,
 9324552,
 7775261,
 9324554,
 7775217,
 14392772,
 14392764,
 14392758,
 14392781,
 14392759,
 14392769,
 14392765,
 14392774,
 14392782,
 7775676,
 7775062,
 14392767,
 14392757,
 7772966,
 14392778,
 14392783,
 7773786,
 7773140,
 7774586,
 7772773,
 7774789,
 7780084,
 7854040,
 15538706,
 15538668,
 15538684,
 15567070,
 7775948,
 7775068,
 9323262,
 7852821,
 7773990,
 7775047,
 7852819,
 7852823,
 7774780,
 7774545,
 7775754,
 7773278,
 7775239,
 7775034,
 7775669,
 7774101,
 7774251,
 7775735,
 7775530,
 7775696,
 7773285,
 7775563,
 14392776,
 8433624,
 8618998,
 9434491,
 10646480,
 10874830,
 11287574,
 11475725,
 11484313,
 11542072,
 11901444,
 13964]

### Get daily, average values from each sensor/station for 2016-2026

In [33]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 22165: Seite 1, 781 Ergebnisse
Sensor 22136: Seite 1, 766 Ergebnisse
Sensor 22070: Seite 1, 683 Ergebnisse
Sensor 22089: Seite 1, 776 Ergebnisse
Sensor 22061: Seite 1, 757 Ergebnisse
Sensor 22104: Seite 1, 761 Ergebnisse
Sensor 22138: Seite 1, 771 Ergebnisse
Sensor 22197: Seite 1, 772 Ergebnisse
Sensor 22108: Seite 1, 766 Ergebnisse
Sensor 22071: Seite 1, 766 Ergebnisse
Sensor 22171: Seite 1, 769 Ergebnisse
Sensor 22133: Seite 1, 773 Ergebnisse
Sensor 22113: Seite 1, 765 Ergebnisse
Sensor 22199: Seite 1, 769 Ergebnisse
Sensor 22190: Seite 1, 772 Ergebnisse
Sensor 22066: Seite 1, 750 Ergebnisse
Sensor 22175: Seite 1, 764 Ergebnisse
Sensor 22069: Seite 1, 773 Ergebnisse
Sensor 22164: Seite 1, 768 Ergebnisse
Sensor 22079: Seite 1, 743 Ergebnisse
Sensor 22085: Seite 1, 739 Ergebnisse
Sensor 22096: Seite 1, 756 Ergebnisse
Sensor 22093: Seite 1, 782 Ergebnisse
Sensor 22099: Seite 1, 736 Ergebnisse
Sensor 22109: Seite 1, 775 Ergebnisse
Sensor 22177: Seite 1, 778 Ergebnisse
Sensor 22119: Seite 1, 756 Ergebnisse
Sensor 22117: Seite 1, 781 Ergebnisse
Sensor 22146: Seite 1, 776 Ergebnisse
Sensor 22124: Seite 1, 771 Ergebnisse
Sensor 22153: Seite 1, 747 Ergebnisse
Sensor 22130: Seite 1, 762 Ergebnisse
Sensor 22151: Seite 1, 780 Ergebnisse
Sensor 22148: Seite 1, 762 Ergebnisse
Sensor 22154: Seite 1, 773 Ergebnisse
Sensor 22163: Seite 1, 757 Ergebnisse
Sensor 22162: Seite 1, 764 Ergebnisse
Sensor 22186: Seite 1, 774 Ergebnisse
Sensor 22189: Seite 1, 779 Ergebnisse
Sensor 20602: Seite 1, 647 Ergebnisse
Sensor 20607: Seite 1, 630 Ergebnisse
Sensor 20606: Seite 1, 637 Ergebnisse
Sensor 20595: Seite 1, 642 Ergebnisse
Sensor 20598: Seite 1, 625 Ergebnisse
Sensor 22195: Seite 1, 778 Ergebnisse
Sensor 21803: Seite 1, 1000 Ergebnisse
Sensor 21803: Seite 2, 840 Ergebnisse
Sensor 21764: Seite 1, 1000 Ergebnisse
Sensor 21764: Seite 2, 880 Ergebnisse
Sensor 21766: Seite 1, 1000 Ergebnisse
Sensor 21766: Seite 2, 838 Ergebnisse
Sensor 21767: Seite 1, 1000 Ergebnisse
Sensor 21767: Seite 2, 907 Ergebnisse
Sensor 21774: Seite 1, 1000 Ergebnisse
Sensor 21774: Seite 2, 818 Ergebnisse
Sensor 21770: Seite 1, 1000 Ergebnisse
Sensor 21770: Seite 2, 741 Ergebnisse
Sensor 21772: Seite 1, 1000 Ergebnisse
Sensor 21772: Seite 2, 815 Ergebnisse
Sensor 21811: Seite 1, 1000 Ergebnisse
Sensor 21811: Seite 2, 862 Ergebnisse
Sensor 21804: Seite 1, 1000 Ergebnisse
Sensor 21804: Seite 2, 889 Ergebnisse
Sensor 21807: Seite 1, 1000 Ergebnisse
Sensor 21807: Seite 2, 893 Ergebnisse
Sensor 21808: Seite 1, 1000 Ergebnisse
Sensor 21808: Seite 2, 881 Ergebnisse
Sensor 21809: Seite 1, 1000 Ergebnisse
Sensor 21809: Seite 2, 904 Ergebnisse
Sensor 21810: Seite 1, 1000 Ergebnisse
Sensor 21810: Seite 2, 880 Ergebnisse
Sensor 21812: Seite 1, 1000 Ergebnisse
Sensor 21812: Seite 2, 855 Ergebnisse
Sensor 21814: Seite 1, 1000 Ergebnisse
Sensor 21814: Seite 2, 875 Ergebnisse
Sensor 21815: Seite 1, 1000 Ergebnisse
Sensor 21815: Seite 2, 876 Ergebnisse
Sensor 21816: Seite 1, 1000 Ergebnisse
Sensor 21816: Seite 2, 725 Ergebnisse
Sensor 21817: Seite 1, 1000 Ergebnisse
Sensor 21817: Seite 2, 859 Ergebnisse
Sensor 21818: Seite 1, 1000 Ergebnisse
Sensor 21818: Seite 2, 879 Ergebnisse
Sensor 21821: Seite 1, 1000 Ergebnisse
Sensor 21821: Seite 2, 861 Ergebnisse
Sensor 21820: Seite 1, 1000 Ergebnisse
Sensor 21820: Seite 2, 829 Ergebnisse
Sensor 21822: Seite 1, 1000 Ergebnisse
Sensor 21822: Seite 2, 875 Ergebnisse
Sensor 21825: Seite 1, 1000 Ergebnisse
Sensor 21825: Seite 2, 888 Ergebnisse
Sensor 21826: Seite 1, 1000 Ergebnisse
Sensor 21826: Seite 2, 898 Ergebnisse
Sensor 21828: Seite 1, 1000 Ergebnisse
Sensor 21828: Seite 2, 896 Ergebnisse
Sensor 21831: Seite 1, 1000 Ergebnisse
Sensor 21831: Seite 2, 863 Ergebnisse
Sensor 21832: Seite 1, 1000 Ergebnisse
Sensor 21832: Seite 2, 885 Ergebnisse
Sensor 21834: Seite 1, 1000 Ergebnisse
Sensor 21834: Seite 2, 877 Ergebnisse
Sensor 21835: Seite 1, 1000 Ergebnisse
Sensor 21835: Seite 2, 834 Ergebnisse
Sensor 21837: Seite 1, 1000 Ergebnisse
Sensor 21837: Seite 2, 863 Ergebnisse
Sensor 21838: Seite 1, 1000 Ergebnisse
Sensor 21838: Seite 2, 858 Ergebnisse
Sensor 21840: Seite 1, 1000 Ergebnisse
Sensor 21840: Seite 2, 818 Ergebnisse
Sensor 21845: Seite 1, 1000 Ergebnisse
Sensor 21845: Seite 2, 868 Ergebnisse
Sensor 21847: Seite 1, 1000 Ergebnisse
Sensor 21847: Seite 2, 848 Ergebnisse
Sensor 21848: Seite 1, 1000 Ergebnisse
Sensor 21848: Seite 2, 871 Ergebnisse
Sensor 21849: Seite 1, 1000 Ergebnisse
Sensor 21849: Seite 2, 881 Ergebnisse
Sensor 21853: Seite 1, 1000 Ergebnisse
Sensor 21853: Seite 2, 872 Ergebnisse
Sensor 21855: Seite 1, 1000 Ergebnisse
Sensor 21855: Seite 2, 866 Ergebnisse
Sensor 21856: Seite 1, 1000 Ergebnisse
Sensor 21856: Seite 2, 866 Ergebnisse
Sensor 21859: Seite 1, 1000 Ergebnisse
Sensor 21859: Seite 2, 827 Ergebnisse
Sensor 21860: Seite 1, 1000 Ergebnisse
Sensor 21860: Seite 2, 813 Ergebnisse
Sensor 21862: Seite 1, 1000 Ergebnisse
Sensor 21862: Seite 2, 874 Ergebnisse
Sensor 21762: Seite 1, 1000 Ergebnisse
Sensor 21762: Seite 2, 361 Ergebnisse
Sensor 21763: Seite 1, 727 Ergebnisse
Sensor 7775455: Seite 1, 655 Ergebnisse
Sensor 23468: Seite 1, 1000 Ergebnisse
Sensor 23468: Seite 2, 518 Ergebnisse
Sensor 23466: Seite 1, 1000 Ergebnisse
Sensor 23466: Seite 2, 492 Ergebnisse
Sensor 23484: Seite 1, 1000 Ergebnisse
Sensor 23484: Seite 2, 567 Ergebnisse
Sensor 22631: Seite 1, 738 Ergebnisse
Sensor 7775967: Seite 1, 713 Ergebnisse
Sensor 7774118: Seite 1, 713 Ergebnisse
Sensor 7775189: Seite 1, 705 Ergebnisse
Sensor 7772729: Seite 1, 650 Ergebnisse
Sensor 7773685: Seite 1, 666 Ergebnisse
Sensor 5078278: Seite 1, 817 Ergebnisse
Sensor 7775965: Seite 1, 688 Ergebnisse
Sensor 7773037: Seite 1, 666 Ergebnisse
Sensor 7772822: Seite 1, 717 Ergebnisse
Sensor 5078297: Seite 1, 825 Ergebnisse
Sensor 7773748: Seite 1, 718 Ergebnisse
Sensor 7775580: Seite 1, 715 Ergebnisse
Sensor 5078276: Seite 1, 796 Ergebnisse
Sensor 7774064: Seite 1, 449 Ergebnisse
Sensor 7774499: Seite 1, 673 Ergebnisse
Sensor 7775117: Seite 1, 627 Ergebnisse
Sensor 7774393: Seite 1, 698 Ergebnisse
Sensor 7775306: Seite 1, 688 Ergebnisse
Sensor 7774513: Seite 1, 611 Ergebnisse
Sensor 5078282: Seite 1, 814 Ergebnisse
Sensor 15538674: Seite 1, 4 Ergebnisse
Sensor 7773821: Seite 1, 667 Ergebnisse
Sensor 7776031: Seite 1, 713 Ergebnisse
Sensor 7774792: Seite 1, 660 Ergebnisse
Sensor 7774588: Seite 1, 655 Ergebnisse
Sensor 7773415: Seite 1, 718 Ergebnisse
Sensor 7773803: Seite 1, 510 Ergebnisse
Sensor 7773675: Seite 1, 518 Ergebnisse
Sensor 7774822: Seite 1, 696 Ergebnisse
Sensor 7775843: Seite 1, 671 Ergebnisse
Sensor 7774089: Seite 1, 645 Ergebnisse
Sensor 7773410: Seite 1, 665 Ergebnisse
Sensor 7772990: Seite 1, 677 Ergebnisse
Sensor 7773858: Seite 1, 661 Ergebnisse
Sensor 7773214: Seite 1, 719 Ergebnisse
Sensor 7774398: Seite 1, 666 Ergebnisse
Sensor 7773966: Seite 1, 642 Ergebnisse
Sensor 7774039: Seite 1, 644 Ergebnisse
Sensor 7772717: Seite 1, 674 Ergebnisse
Sensor 7774226: Seite 1, 696 Ergebnisse
Sensor 7775798: Seite 1, 647 Ergebnisse
Sensor 7775900: Seite 1, 673 Ergebnisse
Sensor 7774070: Seite 1, 689 Ergebnisse
Sensor 7773394: Seite 1, 696 Ergebnisse
Sensor 7775985: Seite 1, 671 Ergebnisse
Sensor 7773708: Seite 1, 633 Ergebnisse
Sensor 7775349: Seite 1, 669 Ergebnisse
Sensor 7772792: Seite 1, 668 Ergebnisse
Sensor 15538685: Seite 1, 5 Ergebnisse
Sensor 15545434: Seite 1, 4 Ergebnisse
Sensor 15538702: Seite 1, 5 Ergebnisse
Sensor 15545438: Seite 1, 4 Ergebnisse
Sensor 5078285: Seite 1, 801 Ergebnisse
Sensor 5078283: Seite 1, 814 Ergebnisse
Sensor 5078288: Seite 1, 817 Ergebnisse
Sensor 5078298: Seite 1, 810 Ergebnisse
Sensor 24421: Seite 1, 1000 Ergebnisse
Sensor 24421: Seite 2, 662 Ergebnisse
Sensor 5078280: Seite 1, 826 Ergebnisse
Sensor 5078273: Seite 1, 821 Ergebnisse
Sensor 5078299: Seite 1, 809 Ergebnisse
Sensor 5078272: Seite 1, 824 Ergebnisse
Sensor 5078296: Seite 1, 821 Ergebnisse
Sensor 5078263: Seite 1, 817 Ergebnisse
Sensor 5078266: Seite 1, 826 Ergebnisse
Sensor 5078268: Seite 1, 816 Ergebnisse
Sensor 5078265: Seite 1, 806 Ergebnisse
Sensor 5078289: Seite 1, 806 Ergebnisse
Sensor 14392780: Seite 1, 128 Ergebnisse
Sensor 15538669: Seite 1, 5 Ergebnisse
Sensor 15567072: Seite 1, 1 Ergebnisse
Sensor 7776020: Seite 1, 679 Ergebnisse
Sensor 24512: Seite 1, 1000 Ergebnisse
Sensor 24512: Seite 2, 49 Ergebnisse
Sensor 24705: Seite 1, 1000 Ergebnisse
Sensor 24705: Seite 2, 56 Ergebnisse
Sensor 24698: Seite 1, 1000 Ergebnisse
Sensor 24698: Seite 2, 54 Ergebnisse
Sensor 24701: Seite 1, 1000 Ergebnisse
Sensor 24701: Seite 2, 20 Ergebnisse
Sensor 7777171: Seite 1, 744 Ergebnisse
Sensor 22209: Seite 1, 1000 Ergebnisse
Sensor 22209: Seite 2, 440 Ergebnisse
Sensor 22604: Seite 1, 720 Ergebnisse
Sensor 22635: Seite 1, 737 Ergebnisse
Sensor 22637: Seite 1, 723 Ergebnisse
Sensor 22844: Seite 1, 1000 Ergebnisse
Sensor 22844: Seite 2, 19 Ergebnisse
Sensor 15538694: Seite 1, 5 Ergebnisse
Sensor 15545435: Seite 1, 4 Ergebnisse
Sensor 15545440: Seite 1, 4 Ergebnisse
Sensor 7774637: Seite 1, 680 Ergebnisse
Sensor 24440: Seite 1, 381 Ergebnisse
Sensor 24569: Seite 1, 1000 Ergebnisse
Sensor 24569: Seite 2, 838 Ergebnisse
Sensor 7773310: Seite 1, 391 Ergebnisse
Sensor 24322: Seite 1, 1000 Ergebnisse
Sensor 24322: Seite 2, 852 Ergebnisse
Sensor 23989: Seite 1, 1000 Ergebnisse
Sensor 23989: Seite 2, 743 Ergebnisse
Sensor 7775924: Seite 1, 722 Ergebnisse
Sensor 1764523: Seite 1, 1000 Ergebnisse
Sensor 1764523: Seite 2, 244 Ergebnisse
Sensor 8613280: Seite 1, 72 Ergebnisse
Sensor 24313: Seite 1, 777 Ergebnisse
Sensor 24382: Seite 1, 869 Ergebnisse
Sensor 7531552: Seite 1, 734 Ergebnisse
Sensor 24416: Seite 1, 1000 Ergebnisse
Sensor 24416: Seite 2, 734 Ergebnisse
Sensor 24417: Seite 1, 1000 Ergebnisse
Sensor 24417: Seite 2, 714 Ergebnisse
Sensor 12907941: Seite 1, 281 Ergebnisse
Sensor 5078281: Seite 1, 819 Ergebnisse
Sensor 7775010: Seite 1, 667 Ergebnisse
Sensor 24532: Seite 1, 1000 Ergebnisse
Sensor 24532: Seite 2, 933 Ergebnisse
Sensor 24535: Seite 1, 1000 Ergebnisse
Sensor 24535: Seite 2, 873 Ergebnisse
Sensor 24543: Seite 1, 1000 Ergebnisse
Sensor 24543: Seite 2, 929 Ergebnisse
Sensor 8613070: Seite 1, 72 Ergebnisse
Sensor 24562: Seite 1, 851 Ergebnisse
Sensor 5078275: Seite 1, 815 Ergebnisse
Sensor 1702603: Seite 1, 1000 Ergebnisse
Sensor 1702603: Seite 2, 279 Ergebnisse
Sensor 7950621: Seite 1, 523 Ergebnisse
Sensor 15538671: Seite 1, 5 Ergebnisse
Sensor 1764647: Seite 1, 1000 Ergebnisse
Sensor 1764647: Seite 2, 217 Ergebnisse
Sensor 15538687: Seite 1, 4 Ergebnisse
Sensor 15538677: Seite 1, 5 Ergebnisse
Sensor 15545430: Seite 1, 3 Ergebnisse
Sensor 15545432: Seite 1, 3 Ergebnisse
Sensor 15586346: Seite 1, 1 Ergebnisse
Sensor 15556738: Seite 1, 5 Ergebnisse
Sensor 15545429: Seite 1, 4 Ergebnisse
Sensor 15545433: Seite 1, 4 Ergebnisse
Sensor 15538701: Seite 1, 5 Ergebnisse
Sensor 25020: Seite 1, 1000 Ergebnisse
Sensor 25020: Seite 2, 803 Ergebnisse
Sensor 15538688: Seite 1, 5 Ergebnisse
Sensor 15538666: Seite 1, 5 Ergebnisse
Sensor 15538700: Seite 1, 5 Ergebnisse
Sensor 15556739: Seite 1, 4 Ergebnisse
Sensor 15538690: Seite 1, 5 Ergebnisse
Sensor 15538672: Seite 1, 5 Ergebnisse
Sensor 15579566: Seite 1, 2 Ergebnisse
Sensor 15538689: Seite 1, 5 Ergebnisse
Sensor 7531550: Seite 1, 712 Ergebnisse
Sensor 22274: Seite 1, 739 Ergebnisse
Sensor 1555181: Seite 1, 733 Ergebnisse
Sensor 24490: Seite 1, 1000 Ergebnisse
Sensor 24490: Seite 2, 220 Ergebnisse
Sensor 24506: Seite 1, 1000 Ergebnisse
Sensor 24506: Seite 2, 52 Ergebnisse
Sensor 22260: Seite 1, 708 Ergebnisse
Sensor 22730: Seite 1, 105 Ergebnisse
Sensor 15545431: Seite 1, 4 Ergebnisse
Sensor 5078277: Seite 1, 814 Ergebnisse
Sensor 5079211: Seite 1, 797 Ergebnisse
Sensor 24410: Seite 1, 1000 Ergebnisse
Sensor 24410: Seite 2, 729 Ergebnisse
Sensor 5078290: Seite 1, 831 Ergebnisse
Sensor 5078295: Seite 1, 805 Ergebnisse
Sensor 5078269: Seite 1, 793 Ergebnisse
Sensor 24763: Seite 1, 1000 Ergebnisse
Sensor 24763: Seite 2, 863 Ergebnisse
Sensor 15538691: Seite 1, 5 Ergebnisse
Sensor 22263: Seite 1, 1000 Ergebnisse
Sensor 22263: Seite 2, 455 Ergebnisse
Sensor 7775366: Seite 1, 43 Ergebnisse
Sensor 5078300: Seite 1, 869 Ergebnisse
Sensor 22632: Seite 1, 774 Ergebnisse
Sensor 15538698: Seite 1, 5 Ergebnisse
Sensor 1287749: Seite 1, 768 Ergebnisse
Sensor 1288174: Seite 1, 363 Ergebnisse
Sensor 1288171: Seite 1, 1000 Ergebnisse
Sensor 1288171: Seite 2, 319 Ergebnisse
Sensor 1288160: Seite 1, 763 Ergebnisse
Sensor 1288166: Seite 1, 754 Ergebnisse
Sensor 1288158: Seite 1, 736 Ergebnisse
Sensor 15538705: Seite 1, 5 Ergebnisse
Sensor 5079444: Seite 1, 958 Ergebnisse
Sensor 5079451: Seite 1, 948 Ergebnisse
Sensor 5079457: Seite 1, 997 Ergebnisse
Sensor 5079461: Seite 1, 991 Ergebnisse
Sensor 5079450: Seite 1, 3 Ergebnisse
Sensor 5078551: Seite 1, 816 Ergebnisse
Sensor 5078720: Seite 1, 822 Ergebnisse
Sensor 5078937: Seite 1, 814 Ergebnisse
Sensor 5079209: Seite 1, 612 Ergebnisse
Sensor 7777633: Seite 1, 702 Ergebnisse
Sensor 5104465: Seite 1, 672 Ergebnisse
Sensor 15538664: Seite 1, 4 Ergebnisse
Sensor 5079066: Seite 1, 946 Ergebnisse
Sensor 15545439: Seite 1, 4 Ergebnisse
Sensor 5078843: Seite 1, 247 Ergebnisse
Sensor 5078508: Seite 1, 820 Ergebnisse
Sensor 5078739: Seite 1, 812 Ergebnisse
Sensor 7970860: Seite 1, 126 Ergebnisse
Sensor 7979466: Seite 1, 2 Ergebnisse
Sensor 7970841: Seite 1, 312 Ergebnisse
Sensor 7978348: Seite 1, 3 Ergebnisse
Sensor 7531553: Seite 1, 326 Ergebnisse
Sensor 7773079: Seite 1, 648 Ergebnisse
Sensor 7774815: Seite 1, 721 Ergebnisse
Sensor 7775783: Seite 1, 648 Ergebnisse
Sensor 7775830: Seite 1, 714 Ergebnisse
Sensor 7774971: Seite 1, 695 Ergebnisse
Sensor 7775511: Seite 1, 721 Ergebnisse
Sensor 7774772: Seite 1, 393 Ergebnisse
Sensor 7775712: Seite 1, 645 Ergebnisse
Sensor 8622697: Seite 1, 638 Ergebnisse
Sensor 7775388: Seite 1, 666 Ergebnisse
Sensor 7774958: Seite 1, 652 Ergebnisse
Sensor 7775673: Seite 1, 713 Ergebnisse
Sensor 7775275: Seite 1, 707 Ergebnisse
Sensor 7772912: Seite 1, 713 Ergebnisse
Sensor 7772889: Seite 1, 713 Ergebnisse
Sensor 7774204: Seite 1, 715 Ergebnisse
Sensor 9324552: Seite 1, 580 Ergebnisse
Sensor 7775261: Seite 1, 510 Ergebnisse
Sensor 9324554: Seite 1, 572 Ergebnisse
Sensor 7775217: Seite 1, 607 Ergebnisse
Sensor 14392772: Seite 1, 130 Ergebnisse
Sensor 14392764: Seite 1, 132 Ergebnisse
Sensor 14392758: Seite 1, 132 Ergebnisse
Sensor 14392781: Seite 1, 132 Ergebnisse
Sensor 14392759: Seite 1, 134 Ergebnisse
Sensor 14392769: Seite 1, 132 Ergebnisse
Sensor 14392765: Seite 1, 131 Ergebnisse
Sensor 14392774: Seite 1, 134 Ergebnisse
Sensor 14392782: Seite 1, 132 Ergebnisse
Sensor 7775676: Seite 1, 693 Ergebnisse
Sensor 7775062: Seite 1, 684 Ergebnisse
Sensor 14392767: Seite 1, 132 Ergebnisse
Sensor 14392757: Seite 1, 134 Ergebnisse
Sensor 7772966: Seite 1, 655 Ergebnisse
Sensor 14392778: Seite 1, 127 Ergebnisse
Sensor 14392783: Seite 1, 134 Ergebnisse
Sensor 7773786: Seite 1, 694 Ergebnisse
Sensor 7773140: Seite 1, 716 Ergebnisse
Sensor 7774586: Seite 1, 731 Ergebnisse
Sensor 7772773: Seite 1, 648 Ergebnisse
Sensor 7774789: Seite 1, 647 Ergebnisse
Sensor 7780084: Seite 1, 637 Ergebnisse
Sensor 7854040: Seite 1, 651 Ergebnisse
Sensor 15538706: Seite 1, 5 Ergebnisse
Sensor 15538668: Seite 1, 5 Ergebnisse
Sensor 15538684: Seite 1, 5 Ergebnisse
Sensor 15567070: Seite 1, 3 Ergebnisse
Sensor 7775948: Seite 1, 691 Ergebnisse
Sensor 7775068: Seite 1, 682 Ergebnisse
Sensor 9323262: Seite 1, 580 Ergebnisse
Sensor 7852821: Seite 1, 652 Ergebnisse
Sensor 7773990: Seite 1, 664 Ergebnisse
Sensor 7775047: Seite 1, 662 Ergebnisse
Sensor 7852819: Seite 1, 652 Ergebnisse
Sensor 7852823: Seite 1, 651 Ergebnisse
Sensor 7774780: Seite 1, 729 Ergebnisse
Sensor 7774545: Seite 1, 727 Ergebnisse
Sensor 7775754: Seite 1, 729 Ergebnisse
Sensor 7773278: Seite 1, 725 Ergebnisse
Sensor 7775239: Seite 1, 721 Ergebnisse
Sensor 7775034: Seite 1, 555 Ergebnisse
Sensor 7775669: Seite 1, 728 Ergebnisse
Sensor 7774101: Seite 1, 730 Ergebnisse
Sensor 7774251: Seite 1, 570 Ergebnisse
Sensor 7775735: Seite 1, 561 Ergebnisse
Sensor 7775530: Seite 1, 114 Ergebnisse
Sensor 7775696: Seite 1, 713 Ergebnisse
Sensor 7773285: Seite 1, 618 Ergebnisse
Sensor 7775563: Seite 1, 146 Ergebnisse
Sensor 14392776: Seite 1, 129 Ergebnisse
Sensor 8433624: Seite 1, 189 Ergebnisse
Sensor 8618998: Seite 1, 6 Ergebnisse
Sensor 9434491: Seite 1, 95 Ergebnisse
Sensor 10646480: Seite 1, 5 Ergebnisse
Sensor 10874830: Seite 1, 99 Ergebnisse
Sensor 11287574: Seite 1, 62 Ergebnisse
Sensor 11475725: Seite 1, 46 Ergebnisse
Sensor 11484313: Seite 1, 45 Ergebnisse
Sensor 11542072: Seite 1, 40 Ergebnisse
Sensor 11901444: Seite 1, 9 Ergebnisse
272511

[{'date': '2017-11-01', 'value': 35.0},
 {'date': '2017-11-02', 'value': 50.0},
 {'date': '2017-11-05', 'value': 33.0},
 {'date': '2017-11-06', 'value': 7.0},
 {'date': '2017-11-07', 'value': 8.0},
 {'date': '2017-11-08', 'value': 22.0},
 {'date': '2017-11-09', 'value': 29.0},
 {'date': '2017-11-13', 'value': 6.0},
 {'date': '2017-11-14', 'value': 17.0},
 {'date': '2017-11-15', 'value': 22.0},
 {'date': '2017-11-16', 'value': 29.0},
 {'date': '2017-11-20', 'value': 60.0},
 {'date': '2017-11-21', 'value': 66.0},
 {'date': '2017-11-22', 'value': 76.0},
 {'date': '2017-11-23', 'value': 89.0},
 {'date': '2017-11-27', 'value': 24.0},
 {'date': '2017-11-28', 'value': 34.0},
 {'date': '2017-11-29', 'value': 39.0},
 {'date': '2017-11-30', 'value': 40.0},
 {'date': '2017-12-03', 'value': 33.0},
 {'date': '2017-12-04', 'value': 47.0},
 {'date': '2017-12-06', 'value': 65.0},
 {'date': '2017-12-10', 'value': 20.0},
 {'date': '2017-12-12', 'value': 33.0},
 {'date': '2017-12-13', 'value': 43.0},
 {'date': '2017-12-14', 'value': 42.0},
 {'date': '2017-12-17', 'value': 46.0},
 {'date': '2017-12-20', 'value': 66.0},
 {'date': '2017-12-21', 'value': 76.0},
 {'date': '2017-12-23', 'value': 70.0},
 {'date': '2017-12-26', 'value': 63.0},
 {'date': '2017-12-27', 'value': 21.0},
 {'date': '2017-12-28', 'value': 6.0},
 {'date': '2018-01-01', 'value': 44.0},
 {'date': '2018-01-02', 'value': 31.0},
 {'date': '2018-01-03', 'value': 33.0},
 {'date': '2018-01-04', 'value': 37.0},
 {'date': '2018-01-07', 'value': 47.0},
 {'date': '2018-01-08', 'value': 32.0},
 {'date': '2018-01-09', 'value': 35.0},
 {'date': '2018-01-10', 'value': 27.0},
 {'date': '2018-01-14', 'value': 33.0},
 {'date': '2018-01-15', 'value': 43.0},
 {'date': '2018-01-21', 'value': 44.0},
 {'date': '2018-01-22', 'value': 46.0},
 {'date': '2018-01-23', 'value': 48.0},
 {'date': '2018-01-24', 'value': 58.0},
 {'date': '2018-01-25', 'value': 69.0},
 {'date': '2018-01-28', 'value': 46.0},
 {'date': '2018-01-29', 'value': 42.0},
 {'date': '2018-01-30', 'value': 38.0},
 {'date': '2018-01-31', 'value': 38.0},
 {'date': '2018-02-01', 'value': 21.0},
 {'date': '2018-02-02', 'value': 7.0},
 {'date': '2018-02-03', 'value': 4.0},
 {'date': '2018-02-04', 'value': 24.0},
 {'date': '2018-02-05', 'value': 25.0},
 {'date': '2018-02-06', 'value': 22.0},
 {'date': '2018-02-07', 'value': 26.0},
 {'date': '2018-02-08', 'value': 31.0},
 {'date': '2018-02-09', 'value': 54.0},
 {'date': '2018-02-10', 'value': 32.0},
 {'date': '2018-02-11', 'value': 26.0},
 {'date': '2018-02-12', 'value': 26.0},
 {'date': '2018-02-14', 'value': 35.0},
 {'date': '2018-02-16', 'value': 59.0},
 {'date': '2018-02-18', 'value': 34.0},
 {'date': '2018-02-19', 'value': 17.0},
 {'date': '2018-02-22', 'value': 11.0},
 {'date': '2018-02-26', 'value': 25.0},
 {'date': '2018-03-01', 'value': 53.0},
 {'date': '2018-03-02', 'value': 80.0},
 {'date': '2018-03-03', 'value': 56.0},
 {'date': '2018-03-08', 'value': 40.0},
 {'date': '2018-03-09', 'value': 27.0},
 {'date': '2018-03-10', 'value': 37.0},
 {'date': '2018-03-11', 'value': 28.0},
 {'date': '2018-03-12', 'value': 19.0},
 {'date': '2018-03-13', 'value': 34.0},
 {'date': '2018-03-14', 'value': 31.0},
 {'date': '2018-03-15', 'value': 25.0},
 {'date': '2018-03-20', 'value': 25.0},
 {'date': '2018-03-21', 'value': 28.0},
 {'date': '2018-03-22', 'value': 25.0},
 {'date': '2018-03-27', 'value': 46.0},
 {'date': '2018-03-28', 'value': 29.0},
 {'date': '2018-03-29', 'value': 34.0},
 {'date': '2018-03-30', 'value': 37.0},
 {'date': '2018-03-31', 'value': 18.0},
 {'date': '2018-04-01', 'value': 5.0},
 {'date': '2018-04-02', 'value': 12.0},
 {'date': '2018-04-03', 'value': 14.0},
 {'date': '2018-04-04', 'value': 32.0},
 {'date': '2018-04-05', 'value': 29.0},
 {'date': '2018-04-07', 'value': 27.0},
 {'date': '2018-04-08', 'value': 18.0},
 {'date': '2018-04-09', 'value': 14.0},
 {'date': '2018-04-11', 'value': 21.0},
 {'date': '2018-04-12', 'value': 20.0},
 {'date': '2018-04-13', 'value': 33.0},
 {'date': '2018-04-14', 'value': 17.0},
 {'date': '2018-04-15', 'value': 23.0},
 {'date': '2018-04-16', 'value': 37.0},
 {'date': '2018-04-18', 'value': 33.0},
 {'date': '2018-04-20', 'value': 28.0},
 {'date': '2018-04-21', 'value': 26.0},
 {'date': '2018-04-22', 'value': 26.0},
 {'date': '2018-04-23', 'value': 20.0},
 {'date': '2018-04-24', 'value': 30.0},
 {'date': '2018-04-25', 'value': 27.0},
 {'date': '2018-04-26', 'value': 26.0},
 {'date': '2018-04-27', 'value': 29.0},
 {'date': '2018-04-29', 'value': 27.0},
 {'date': '2018-04-30', 'value': 33.0},
 {'date': '2018-05-01', 'value': 15.0},
 {'date': '2018-05-02', 'value': 15.0},
 {'date': '2018-05-03', 'value': 17.0},
 {'date': '2018-05-04', 'value': 25.0},
 {'date': '2018-05-05', 'value': 31.0},
 {'date': '2018-05-06', 'value': 28.0},
 {'date': '2018-05-07', 'value': 23.0},
 {'date': '2018-05-08', 'value': 22.0},
 {'date': '2018-05-09', 'value': 32.0},
 {'date': '2018-05-10', 'value': 14.0},
 {'date': '2018-05-11', 'value': 24.0},
 {'date': '2018-05-12', 'value': 28.0},
 {'date': '2018-05-13', 'value': 23.0},
 {'date': '2018-05-14', 'value': 16.0},
 {'date': '2018-05-15', 'value': 9.0},
 {'date': '2018-05-17', 'value': 16.0},
 {'date': '2018-05-18', 'value': 21.0},
 {'date': '2018-05-25', 'value': 21.0},
 {'date': '2018-05-26', 'value': 29.0},
 {'date': '2018-05-27', 'value': 18.0},
 {'date': '2018-05-28', 'value': 19.0},
 {'date': '2018-05-29', 'value': 19.0},
 {'date': '2018-05-30', 'value': 27.0},
 {'date': '2018-05-31', 'value': 26.0},
 {'date': '2018-06-02', 'value': 23.0},
 {'date': '2018-06-03', 'value': 19.0},
 {'date': '2018-06-04', 'value': 18.0},
 {'date': '2018-06-06', 'value': 20.0},
 {'date': '2018-06-07', 'value': 29.0},
 {'date': '2018-06-08', 'value': 24.0},
 {'date': '2018-06-09', 'value': 18.0},
 {'date': '2018-06-10', 'value': 15.0},
 {'date': '2018-06-11', 'value': 16.0},
 {'date': '2018-06-13', 'value': 24.0},
 {'date': '2018-06-14', 'value': 17.0},
 {'date': '2018-06-15', 'value': 11.0},
 {'date': '2018-06-16', 'value': 14.0},
 {'date': '2018-06-17', 'value': 19.0},
 {'date': '2018-06-19', 'value': 21.0},
 {'date': '2018-06-20', 'value': 19.0},
 {'date': '2018-06-21', 'value': 22.0},
 {'date': '2018-06-22', 'value': 21.0},
 {'date': '2018-06-23', 'value': 17.0},
 {'date': '2018-06-24', 'value': 12.0},
 {'date': '2018-06-25', 'value': 12.0},
 {'date': '2018-06-26', 'value': 11.0},
 {'date': '2018-06-27', 'value': 9.0},
 {'date': '2018-06-28', 'value': 14.0},
 {'date': '2018-06-29', 'value': 9.0},
 {'date': '2018-06-30', 'value': 11.0},
 {'date': '2018-07-01', 'value': 17.0},
 {'date': '2018-07-02', 'value': 16.0},
 {'date': '2018-07-03', 'value': 16.0},
 {'date': '2018-07-04', 'value': 22.0},
 {'date': '2018-07-05', 'value': 14.0},
 {'date': '2018-07-06', 'value': 18.0},
 {'date': '2018-07-07', 'value': 15.0},
 {'date': '2018-07-08', 'value': 13.0},
 {'date': '2018-07-09', 'value': 12.0},
 {'date': '2018-07-10', 'value': 14.0},
 {'date': '2018-07-11', 'value': 19.0},
 {'date': '2018-07-12', 'value': 15.0},
 {'date': '2018-07-13', 'value': 16.0},
 {'date': '2018-07-14', 'value': 18.0},
 {'date': '2018-07-15', 'value': 17.0},
 {'date': '2018-07-16', 'value': 18.0},
 {'date': '2018-07-17', 'value': 12.0},
 {'date': '2018-07-19', 'value': 19.0},
 {'date': '2018-07-20', 'value': 22.0},
 {'date': '2018-07-21', 'value': 23.0},
 {'date': '2018-07-22', 'value': 15.0},
 {'date': '2018-07-23', 'value': 12.0},
 {'date': '2018-07-24', 'value': 9.0},
 {'date': '2018-07-25', 'value': 19.0},
 {'date': '2018-07-26', 'value': 21.0},
 {'date': '2018-07-27', 'value': 20.0},
 {'date': '2018-07-28', 'value': 15.0},
 {'date': '2018-07-29', 'value': 19.0},
 {'date': '2018-07-30', 'value': 21.0},
 {'date': '2018-07-31', 'value': 23.0},
 {'date': '2018-08-01', 'value': 27.0},
 {'date': '2018-08-02', 'value': 23.0},
 {'date': '2018-08-03', 'value': 24.0},
 {'date': '2018-08-04', 'value': 21.0},
 {'date': '2018-08-05', 'value': 23.0},
 {'date': '2018-08-06', 'value': 22.0},
 {'date': '2018-08-07', 'value': 21.0},
 {'date': '2018-08-09', 'value': 28.0},
 {'date': '2018-08-10', 'value': 25.0},
 {'date': '2018-08-11', 'value': 19.0},
 {'date': '2018-08-12', 'value': 20.0},
 {'date': '2018-08-13', 'value': 16.0},
 {'date': '2018-08-14', 'value': 19.0},
 {'date': '2018-08-15', 'value': 16.0},
 {'date': '2018-08-16', 'value': 10.0},
 {'date': '2018-08-18', 'value': 17.0},
 {'date': '2018-08-19', 'value': 19.0},
 {'date': '2018-08-20', 'value': 23.0},
 {'date': '2018-08-21', 'value': 25.0},
 {'date': '2018-08-24', 'value': 26.0},
 {'date': '2018-08-25', 'value': 24.0},
 {'date': '2018-08-26', 'value': 16.0},
 {'date': '2018-08-27', 'value': 7.0},
 {'date': '2018-08-28', 'value': 14.0},
 {'date': '2018-08-29', 'value': 17.0},
 {'date': '2018-08-30', 'value': 20.0},
 {'date': '2018-08-31', 'value': 19.0},
 {'date': '2018-09-01', 'value': 15.0},
 {'date': '2018-09-02', 'value': 12.0},
 {'date': '2018-09-03', 'value': 10.0},
 {'date': '2018-09-04', 'value': 14.0},
 {'date': '2018-09-05', 'value': 16.0},
 {'date': '2018-09-06', 'value': 20.0},
 {'date': '2018-09-07', 'value': 18.0},
 {'date': '2018-09-12', 'value': 27.0},
 {'date': '2018-09-13', 'value': 28.0},
 {'date': '2018-09-14', 'value': 38.0},
 {'date': '2018-09-15', 'value': 46.0},
 {'date': '2018-09-17', 'value': 22.0},
 {'date': '2018-09-18', 'value': 28.0},
 {'date': '2018-09-19', 'value': 30.0},
 {'date': '2018-09-20', 'value': 24.0},
 {'date': '2018-09-22', 'value': 29.0},
 {'date': '2018-09-23', 'value': 27.0},
 {'date': '2018-09-24', 'value': 19.0},
 {'date': '2018-09-25', 'value': 26.0},
 {'date': '2018-09-26', 'value': 17.0},
 {'date': '2018-09-27', 'value': 18.0},
 {'date': '2018-09-28', 'value': 34.0},
 {'date': '2018-09-29', 'value': 40.0},
 {'date': '2018-09-30', 'value': 22.0},
 {'date': '2018-10-01', 'value': 13.0},
 {'date': '2018-10-03', 'value': 10.0},
 {'date': '2018-10-04', 'value': 22.0},
 {'date': '2018-10-05', 'value': 25.0},
 {'date': '2018-10-06', 'value': 22.0},
 {'date': '2018-10-07', 'value': 26.0},
 {'date': '2018-10-08', 'value': 47.0},
 {'date': '2018-10-09', 'value': 35.0},
 {'date': '2018-10-12', 'value': 47.0},
 {'date': '2018-10-13', 'value': 61.0},
 {'date': '2018-10-14', 'value': 52.0},
 {'date': '2018-10-15', 'value': 48.0},
 {'date': '2018-10-17', 'value': 39.0},
 {'date': '2018-10-18', 'value': 52.0},
 {'date': '2018-10-19', 'value': 52.0},
 {'date': '2018-10-20', 'value': 52.0},
 {'date': '2018-10-21', 'value': 59.0},
 {'date': '2018-10-22', 'value': 45.0},
 {'date': '2018-10-23', 'value': 15.0},
 {'date': '2018-10-24', 'value': 29.0},
 {'date': '2018-10-27', 'value': 37.0},
 {'date': '2018-10-28', 'value': 18.0},
 {'date': '2018-10-29', 'value': 27.0},
 {'date': '2018-10-30', 'value': 13.0},
 {'date': '2018-11-01', 'value': 29.0},
 {'date': '2018-11-02', 'value': 30.0},
 {'date': '2018-11-03', 'value': 27.0},
 {'date': '2018-11-04', 'value': 32.0},
 {'date': '2018-11-05', 'value': 30.0},
 {'date': '2018-11-06', 'value': 23.0},
 {'date': '2018-11-07', 'value': 28.0},
 {'date': '2018-11-08', 'value': 28.0},
 {'date': '2018-11-09', 'value': 40.0},
 {'date': '2018-11-10', 'value': 32.0},
 {'date': '2018-11-11', 'value': 47.0},
 {'date': '2018-11-12', 'value': 47.0},
 {'date': '2018-11-13', 'value': 52.0},
 {'date': '2018-11-15', 'value': 30.0},
 {'date': '2018-11-16', 'value': 27.0},
 {'date': '2018-11-17', 'value': 20.0},
 {'date': '2018-11-18', 'value': 20.0},
 {'date': '2018-11-19', 'value': 20.0},
 {'date': '2018-11-20', 'value': 16.0},
 {'date': '2018-11-21', 'value': 35.0},
 {'date': '2018-11-22', 'value': 44.0},
 {'date': '2018-11-23', 'value': 44.0},
 {'date': '2018-11-24', 'value': 27.0},
 {'date': '2018-11-25', 'value': 27.0},
 {'date': '2018-11-26', 'value': 37.0},
 {'date': '2018-11-27', 'value': 28.0},
 {'date': '2018-11-28', 'value': 30.0},
 {'date': '2018-11-29', 'value': 37.0},
 {'date': '2018-11-30', 'value': 50.0},
 {'date': '2018-12-01', 'value': 78.0},
 {'date': '2018-12-02', 'value': 81.0},
 {'date': '2018-12-03', 'value': 80.0},
 {'date': '2018-12-04', 'value': 96.0},
 {'date': '2018-12-05', 'value': 75.0},
 {'date': '2018-12-06', 'value': 41.0},
 {'date': '2018-12-07', 'value': 51.0},
 {'date': '2018-12-08', 'value': 55.0},
 {'date': '2018-12-09', 'value': 35.0},
 {'date': '2018-12-10', 'value': 14.0},
 {'date': '2018-12-11', 'value': 33.0},
 {'date': '2018-12-12', 'value': 45.0},
 {'date': '2018-12-16', 'value': 68.0},
 {'date': '2018-12-17', 'value': 64.0},
 {'date': '2018-12-18', 'value': 61.0},
 {'date': '2018-12-19', 'value': 52.0},
 {'date': '2018-12-20', 'value': 45.0},
 {'date': '2018-12-21', 'value': 50.0},
 {'date': '2018-12-22', 'value': 56.0},
 {'date': '2018-12-23', 'value': 62.0},
 {'date': '2018-12-24', 'value': 28.0},
 {'date': '2018-12-25', 'value': 27.0},
 {'date': '2018-12-26', 'value': 28.0},
 {'date': '2018-12-27', 'value': 43.0},
 {'date': '2018-12-28', 'value': 56.0},
 {'date': '2018-12-29', 'value': 58.0},
 {'date': '2018-12-30', 'value': 68.0},
 {'date': '2018-12-31', 'value': 62.0},
 {'date': '2019-01-01', 'value': 63.0},
 {'date': '2019-01-02', 'value': 55.0},
 {'date': '2019-01-03', 'value': 38.0},
 {'date': '2019-01-04', 'value': 45.0},
 {'date': '2019-01-05', 'value': 76.0},
 {'date': '2019-01-06', 'value': 84.0},
 {'date': '2019-01-07', 'value': 113.0},
 {'date': '2019-01-08', 'value': 68.0},
 {'date': '2019-01-09', 'value': 51.0},
 {'date': '2019-01-10', 'value': 37.0},
 {'date': '2019-01-11', 'value': 56.0},
 {'date': '2019-01-12', 'value': 52.0},
 {'date': '2019-01-14', 'value': 61.0},
 {'date': '2019-01-15', 'value': 29.0},
 {'date': '2019-01-16', 'value': 56.0},
 {'date': '2019-01-17', 'value': 70.0},
 {'date': '2019-01-18', 'value': 48.0},
 {'date': '2019-01-19', 'value': 18.0},
 {'date': '2019-01-20', 'value': 46.0},
 {'date': '2019-01-21', 'value': 57.0},
 {'date': '2019-01-22', 'value': 35.0},
 {'date': '2019-01-23', 'value': 24.0},
 {'date': '2019-01-24', 'value': 31.0},
 {'date': '2019-01-25', 'value': 47.0},
 {'date': '2019-01-26', 'value': 59.0},
 {'date': '2019-01-27', 'value': 73.0},
 {'date': '2019-01-28', 'value': 61.0},
 {'date': '2019-01-29', 'value': 44.0},
 {'date': '2019-01-30', 'value': 28.0},
 {'date': '2019-01-31', 'value': 34.0},
 {'date': '2019-02-01', 'value': 22.0},
 {'date': '2019-02-02', 'value': 30.0},
 {'date': '2019-02-03', 'value': 37.0},
 {'date': '2019-02-04', 'value': 32.0},
 {'date': '2019-02-05', 'value': 49.0},
 {'date': '2019-02-06', 'value': 73.0},
 {'date': '2019-02-07', 'value': 69.0},
 {'date': '2019-02-08', 'value': 83.0},
 {'date': '2019-02-09', 'value': 80.0},
 {'date': '2019-02-10', 'value': 89.0},
 {'date': '2019-02-11', 'value': 54.0},
 {'date': '2019-02-13', 'value': 32.0},
 {'date': '2019-02-14', 'value': 74.0},
 {'date': '2019-02-15', 'value': 88.0},
 {'date': '2019-02-17', 'value': 108.0},
 {'date': '2019-02-18', 'value': 83.0},
 {'date': '2019-02-20', 'value': 112.0},
 {'date': '2019-02-21', 'value': 91.0},
 {'date': '2019-02-23', 'value': 36.0},
 {'date': '2019-02-24', 'value': 25.0},
 {'date': '2019-02-25', 'value': 55.0},
 {'date': '2019-02-26', 'value': 60.0},
 {'date': '2019-02-27', 'value': 52.0},
 {'date': '2019-02-28', 'value': 60.0},
 {'date': '2019-03-01', 'value': 57.0},
 {'date': '2019-03-02', 'value': 84.0},
 {'date': '2019-03-03', 'value': 67.0},
 {'date': '2019-03-04', 'value': 59.0},
 {'date': '2019-03-05', 'value': 59.0},
 {'date': '2019-03-06', 'value': 40.0},
 {'date': '2019-03-07', 'value': 38.0},
 {'date': '2019-03-08', 'value': 26.0},
 {'date': '2019-03-09', 'value': 23.0},
 {'date': '2019-03-10', 'value': 25.0},
 {'date': '2019-03-11', 'value': 45.0},
 {'date': '2019-03-12', 'value': 11.0},
 {'date': '2019-03-13', 'value': 25.0},
 {'date': '2019-03-15', 'value': 39.0},
 {'date': '2019-03-16', 'value': 50.0},
 {'date': '2019-03-17', 'value': 28.0},
 {'date': '2019-03-18', 'value': 13.0},
 {'date': '2019-03-19', 'value': 16.0},
 {'date': '2019-03-20', 'value': 24.0},
 {'date': '2019-03-21', 'value': 33.0},
 {'date': '2019-03-22', 'value': 45.0},
 {'date': '2019-03-23', 'value': 42.0},
 {'date': '2019-03-24', 'value': 37.0},
 {'date': '2019-03-25', 'value': 40.0},
 {'date': '2019-03-26', 'value': 12.0},
 {'date': '2019-03-27', 'value': 24.0},
 {'date': '2019-03-28', 'value': 21.0},
 {'date': '2019-03-29', 'value': 24.0},
 {'date': '2019-03-30', 'value': 32.0},
 {'date': '2019-04-01', 'value': 42.0},
 {'date': '2019-04-03', 'value': 43.0},
 {'date': '2019-04-04', 'value': 23.0},
 {'date': '2019-04-05', 'value': 18.0},
 {'date': '2019-04-06', 'value': 18.0},
 {'date': '2019-04-07', 'value': 20.0},
 {'date': '2019-04-08', 'value': 20.0},
 {'date': '2019-04-09', 'value': 27.0},
 {'date': '2019-04-10', 'value': 39.0},
 {'date': '2019-04-11', 'value': 34.0},
 {'date': '2019-04-12', 'value': 18.0},
 {'date': '2019-04-13', 'value': 17.0},
 {'date': '2019-04-15', 'value': 27.0},
 {'date': '2019-04-16', 'value': 24.0},
 {'date': '2019-04-17', 'value': 36.0},
 {'date': '2019-04-18', 'value': 48.0},
 {'date': '2019-04-19', 'value': 37.0},
 {'date': '2019-04-20', 'value': 23.0},
 {'date': '2019-04-21', 'value': 24.0},
 {'date': '2019-04-22', 'value': 20.0},
 {'date': '2019-04-23', 'value': 26.0},
 {'date': '2019-04-24', 'value': 30.0},
 {'date': '2019-04-25', 'value': 33.0},
 {'date': '2019-04-26', 'value': 43.0},
 {'date': '2019-04-27', 'value': 42.0},
 {'date': '2019-04-28', 'value': 13.0},
 {'date': '2019-04-29', 'value': 11.0},
 {'date': '2019-04-30', 'value': 11.0},
 {'date': '2019-05-01', 'value': 20.0},
 {'date': '2019-05-02', 'value': 16.0},
 {'date': '2019-05-03', 'value': 15.0},
 {'date': '2019-05-04', 'value': 15.0},
 {'date': '2019-05-05', 'value': 13.0},
 {'date': '2019-05-06', 'value': 9.0},
 {'date': '2019-05-07', 'value': 11.0},
 {'date': '2019-05-08', 'value': 18.0},
 {'date': '2019-05-09', 'value': 23.0},
 {'date': '2019-05-10', 'value': 13.0},
 {'date': '2019-05-11', 'value': 15.0},
 {'date': '2019-05-12', 'value': 14.0},
 {'date': '2019-05-13', 'value': 8.0},
 {'date': '2019-05-15', 'value': 23.0},
 {'date': '2019-05-16', 'value': 14.0},
 {'date': '2019-05-17', 'value': 17.0},
 {'date': '2019-05-18', 'value': 10.0},
 {'date': '2019-05-19', 'value': 16.0},
 {'date': '2019-05-20', 'value': 11.0},
 {'date': '2019-05-21', 'value': 6.0},
 {'date': '2019-05-22', 'value': 15.0},
 {'date': '2019-05-23', 'value': 28.0},
 {'date': '2019-05-24', 'value': 20.0},
 {'date': '2019-05-25', 'value': 20.0},
 {'date': '2019-05-26', 'value': 24.0},
 {'date': '2019-05-27', 'value': 19.0},
 {'date': '2019-05-28', 'value': 11.0},
 {'date': '2019-05-29', 'value': 14.0},
 {'date': '2019-05-30', 'value': 8.0},
 {'date': '2019-05-31', 'value': 14.0},
 {'date': '2019-06-01', 'value': 16.0},
 {'date': '2019-06-02', 'value': 16.0},
 {'date': '2019-06-03', 'value': 12.0},
 {'date': '2019-06-04', 'value': 14.0},
 {'date': '2019-06-05', 'value': 19.0},
 {'date': '2019-06-06', 'value': 24.0},
 {'date': '2019-06-07', 'value': 25.0},
 {'date': '2019-06-08', 'value': 27.0},
 {'date': '2019-06-09', 'value': 36.0},
 {'date': '2019-06-10', 'value': 34.0},
 {'date': '2019-06-11', 'value': 35.0},
 {'date': '2019-06-12', 'value': 41.0},
 {'date': '2019-06-14', 'value': 18.0},
 {'date': '2019-06-15', 'value': 30.0},
 {'date': '2019-06-16', 'value': 35.0},
 {'date': '2019-06-17', 'value': 26.0},
 {'date': '2019-06-18', 'value': 22.0},
 {'date': '2019-06-19', 'value': 20.0},
 {'date': '2019-06-20', 'value': 23.0},
 {'date': '2019-06-21', 'value': 21.0},
 {'date': '2019-06-22', 'value': 26.0},
 {'date': '2019-06-23', 'value': 27.0},
 {'date': '2019-06-24', 'value': 23.0},
 {'date': '2019-06-25', 'value': 19.0},
 {'date': '2019-06-26', 'value': 25.0},
 {'date': '2019-06-27', 'value': 27.0},
 {'date': '2019-06-28', 'value': 32.0},
 {'date': '2019-06-29', 'value': 31.0},
 {'date': '2019-06-30', 'value': 25.0},
 {'date': '2019-07-01', 'value': 26.0},
 {'date': '2019-07-03', 'value': 28.0},
 {'date': '2019-07-04', 'value': 21.0},
 {'date': '2019-07-05', 'value': 16.0},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [34]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_pm10_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_pm10_mean
0    2017-11-01         28.139535
1    2017-11-02         39.000000
2    2017-11-05         38.875000
3    2017-11-06          7.804878
4    2017-11-07          9.095238
...         ...               ...
2882 2026-02-24         35.105126
2883 2026-02-25         33.872320
2884 2026-02-26         32.823928
2885 2026-02-27         36.292619
2886 2026-02-28         30.512268

[2887 rows x 2 columns]

### Convert dataframe to csv

In [35]:
france_daily[["date", "france_pm10_mean"]].to_csv(
    "daily_avg_italy_PM10.csv",
    index=False
)

# PM2.5

### Get 200 stations located in France that measure PM2.5
Stations are sorted descending by the duration of their measurements

In [36]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "IT",   # only consider stations located in France
    "parameters_id": 2,   # PM2.5
    #"monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm25 = df_sorted

df_top_pm25

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
31,7599,BESENZONE,VIA PAVESA BERSANO DI BESENZONE - Besenzone (PC),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22075, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.989444000052735, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[10.019166999885284, 44.989444000052735, 10.01...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
37,7609,CASTELLARANO,VIA REVERBERI - Castellarano (RE),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22091, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.516111000289975, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[10.73388899989651, 44.516111000289975, 10.733...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
0,7498,PARCO MONTECUCCO,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 150, 'name': 'Arpae Emilia-Romagna'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 21742, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 45.0385, 'longitude': 9.6693}",None,"[9.6693, 45.0385, 9.6693, 45.0385]",None,2017-11-01 23:00:00+00:00,2020-05-05 23:00:00+00:00
29,7586,SAN CLEMENTE,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 150, 'name': 'Arpae Emilia-Romagna'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22159, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 43.9318, 'longitude': 12.6273}",None,"[12.6273, 43.9318, 12.6273, 43.9318]",None,2017-11-01 23:00:00+00:00,2020-05-05 23:00:00+00:00
30,7587,SAN PIETRO CAPOFIUME,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 150, 'name': 'Arpae Emilia-Romagna'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22024, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.6542, 'longitude': 11.6248}",None,"[11.6248, 44.6542, 11.6248, 44.6542]",None,2017-11-01 23:00:00+00:00,2020-05-05 23:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,466439,bardo pineta 3,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 2617274, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 45.075347271, 'longitude': 6.7004...",None,"[6.700447127, 45.075347271, 6.700447127, 45.07...",None,NaT,NaT
178,471850,bardo neve,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 2647817, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 45.075517267, 'longitude': 6.7004...",None,"[6.700428016, 45.075517267, 6.700428016, 45.07...",None,NaT,NaT
179,476232,casa balcone vento,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 6, 'name': 'Unknown Community Organizat...","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 2671635, 'name': 'pm25 µg/m³', 'parame...","{'latitude': 45.072570434, 'longitude': 7.6764...",None,"[7.676466443, 45.072570434, 7.676466443, 45.07...",None,NaT,NaT
241,5200352,egdp-6,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 11, 'name': 'HabitatMap'}","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 13691481, 'name': 'pm25 µg/m³', 'param...","{'latitude': 40.33146167, 'longitude': 18.1731...",None,"[18.173145577, 40.33146167, 18.173145577, 40.3...",None,NaT,NaT
242,5338026,egdp-7,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 11, 'name': 'HabitatMap'}","{'id': 200, 'name': 'HabitatMap'}",False,False,"[{'id': 5, 'name': 'HabitatMap Sensor'}]","[{'id': 13793572, 'name': 'pm25 µg/m³', 'param...","{'latitude': 40.330947686, 'longitude': 18.174...",None,"[18.17460604, 40.330947686, 18.17460604, 40.33...",None,NaT,NaT

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [38]:
rows = []

for _, station in df_top_pm25.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM25 behalten
        if sensor["parameter"]["id"] == 2:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm25_sensors = pd.DataFrame(rows)

df_pm25_sensors

     station_id          station_name  sensor_id sensor_name
0          7599             BESENZONE      22060  pm25 µg/m³
1          7609          CASTELLARANO      22088  pm25 µg/m³
2          7498      PARCO MONTECUCCO      22134  pm25 µg/m³
3          7586          SAN CLEMENTE      22166  pm25 µg/m³
4          7587  SAN PIETRO CAPOFIUME      22173  pm25 µg/m³
..          ...                   ...        ...         ...
257      466439        bardo pineta 3    2617274  pm25 µg/m³
258      471850            bardo neve    2647817  pm25 µg/m³
259      476232    casa balcone vento    2671635  pm25 µg/m³
260     5200352                egdp-6   13691481  pm25 µg/m³
261     5338026                egdp-7   13793572  pm25 µg/m³

[262 rows x 4 columns]

In [39]:
sensor_ids = df_pm25_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

262

[22060,
 22088,
 22134,
 22166,
 22173,
 22105,
 22068,
 22076,
 22077,
 22084,
 22094,
 22101,
 22107,
 22112,
 22120,
 22118,
 22149,
 22125,
 22131,
 22152,
 22150,
 22168,
 22187,
 22192,
 21773,
 21768,
 1561965,
 21802,
 21806,
 21846,
 6625728,
 21813,
 21830,
 21819,
 21841,
 21823,
 21824,
 21827,
 21829,
 21833,
 21836,
 6629241,
 21839,
 21842,
 7490833,
 21850,
 21857,
 21861,
 21765,
 9324553,
 23472,
 23475,
 23480,
 22636,
 7772744,
 7774426,
 7775914,
 5078264,
 7773744,
 7772850,
 9324555,
 7775024,
 15538678,
 7772749,
 7775618,
 7774544,
 7774841,
 9323263,
 7774785,
 7775409,
 7774279,
 7775178,
 7773552,
 7775778,
 7775099,
 7773017,
 7773388,
 7773064,
 7773043,
 15538682,
 5078294,
 5078267,
 5078291,
 5078302,
 24420,
 5078270,
 5078293,
 24694,
 5078271,
 14392771,
 15538676,
 7774775,
 24511,
 24704,
 7777172,
 22605,
 22633,
 22634,
 15538681,
 24568,
 23986,
 23990,
 7774921,
 7774326,
 1764525,
 24306,
 24381,
 9323266,
 24415,
 12907940,
 7773584,
 24534,
 24542,
 24558,
 2142719,
 1702605,
 13931888,
 15538665,
 1702604,
 15538699,
 15556737,
 15545436,
 15538693,
 15538697,
 15556740,
 15538667,
 15538703,
 7531551,
 25056,
 22273,
 24489,
 24505,
 15538680,
 24409,
 5078279,
 5078286,
 5078287,
 15538675,
 22257,
 15545437,
 5078274,
 15538670,
 1287742,
 1288173,
 1288150,
 15538696,
 5079445,
 5079452,
 5079458,
 5079014,
 5078814,
 5079210,
 7777632,
 15538673,
 2671728,
 5078729,
 6530163,
 6606148,
 6661852,
 7336787,
 9323264,
 7774579,
 7775760,
 7774140,
 7775291,
 8622694,
 7774003,
 7775963,
 7774162,
 7777523,
 7775039,
 14392773,
 14392775,
 14392768,
 14392761,
 14392770,
 14392756,
 14392785,
 14392762,
 7774252,
 7774309,
 14392777,
 14392766,
 7774365,
 14392760,
 7774434,
 7773114,
 7774679,
 7773796,
 7774706,
 7780083,
 15538704,
 15538679,
 15567071,
 7773115,
 7773609,
 9323267,
 7852822,
 7852816,
 7852818,
 7774000,
 7773382,
 7852820,
 14392784,
 8433565,
 8618983,
 10646491,
 10874824,
 10904608,
 11287563,
 11475722,
 11484317,
 11542074,
 11901451,
 12187655,
 12453265,
 12612135,
 13388485,
 13480491,
 13850807,
 14046259,
 14152500,
 14153911,
 14454621,
 14485762,
 14515495,
 14522873,
 14559514,
 14640526,
 14675922,
 14764471,
 14930673,
 15039756,
 15106061,
 15152586,
 15153844,
 15204307,
 15244073,
 15300524,
 15402794,
 1572641,
 1573836,
 2183248,
 2186657,
 2193461,
 2194180,
 2207606,
 2209990,
 2215907,
 2227868,
 2359596,
 2426102,
 2526634,
 2544685,
 2561235,
 2578271,
 2595504,
 2617274,
 2647817,
 2671635,
 13691481,
 13793572]

### Get daily, average values from each sensor/station for 2016-2026

In [40]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 22060: Seite 1, 38 Ergebnisse
Sensor 22088: Seite 1, 38 Ergebnisse
Sensor 22134: Seite 1, 38 Ergebnisse
Sensor 22166: Seite 1, 38 Ergebnisse
Sensor 22173: Seite 1, 38 Ergebnisse
Sensor 22105: Seite 1, 32 Ergebnisse
Sensor 22068: Seite 1, 31 Ergebnisse
Sensor 22076: Seite 1, 38 Ergebnisse
Sensor 22077: Seite 1, 38 Ergebnisse
Sensor 22084: Seite 1, 37 Ergebnisse
Sensor 22094: Seite 1, 38 Ergebnisse
Sensor 22101: Seite 1, 38 Ergebnisse
Sensor 22107: Seite 1, 38 Ergebnisse
Sensor 22112: Seite 1, 37 Ergebnisse
Sensor 22120: Seite 1, 38 Ergebnisse
Sensor 22118: Seite 1, 38 Ergebnisse
Sensor 22149: Seite 1, 38 Ergebnisse
Sensor 22125: Seite 1, 33 Ergebnisse
Sensor 22131: Seite 1, 38 Ergebnisse
Sensor 22152: Seite 1, 37 Ergebnisse
Sensor 22150: Seite 1, 38 Ergebnisse
Sensor 22168: Seite 1, 38 Ergebnisse
Sensor 22187: Seite 1, 38 Ergebnisse
Sensor 22192: Seite 1, 38 Ergebnisse
Sensor 21773: Seite 1, 1000 Ergebnisse
Sensor 21773: Seite 2, 892 Ergebnisse
Sensor 21768: Seite 1, 1000 Ergebnisse
Sensor 21768: Seite 2, 814 Ergebnisse
Sensor 1561965: Seite 1, 1000 Ergebnisse
Sensor 1561965: Seite 2, 167 Ergebnisse
Sensor 21802: Seite 1, 1000 Ergebnisse
Sensor 21802: Seite 2, 724 Ergebnisse
Sensor 21806: Seite 1, 1000 Ergebnisse
Sensor 21806: Seite 2, 892 Ergebnisse
Sensor 21846: Seite 1, 1000 Ergebnisse
Sensor 21846: Seite 2, 884 Ergebnisse
Sensor 6625728: Seite 1, 913 Ergebnisse
Sensor 21813: Seite 1, 1000 Ergebnisse
Sensor 21813: Seite 2, 715 Ergebnisse
Sensor 21830: Seite 1, 1000 Ergebnisse
Sensor 21830: Seite 2, 879 Ergebnisse
Sensor 21819: Seite 1, 1000 Ergebnisse
Sensor 21819: Seite 2, 839 Ergebnisse
Sensor 21841: Seite 1, 1000 Ergebnisse
Sensor 21841: Seite 2, 787 Ergebnisse
Sensor 21823: Seite 1, 1000 Ergebnisse
Sensor 21823: Seite 2, 860 Ergebnisse
Sensor 21824: Seite 1, 1000 Ergebnisse
Sensor 21824: Seite 2, 888 Ergebnisse
Sensor 21827: Seite 1, 1000 Ergebnisse
Sensor 21827: Seite 2, 895 Ergebnisse
Sensor 21829: Seite 1, 1000 Ergebnisse
Sensor 21829: Seite 2, 895 Ergebnisse
Sensor 21833: Seite 1, 1000 Ergebnisse
Sensor 21833: Seite 2, 868 Ergebnisse
Sensor 21836: Seite 1, 1000 Ergebnisse
Sensor 21836: Seite 2, 846 Ergebnisse
Sensor 6629241: Seite 1, 909 Ergebnisse
Sensor 21839: Seite 1, 1000 Ergebnisse
Sensor 21839: Seite 2, 860 Ergebnisse
Sensor 21842: Seite 1, 1000 Ergebnisse
Sensor 21842: Seite 2, 815 Ergebnisse
Sensor 7490833: Seite 1, 747 Ergebnisse
Sensor 21850: Seite 1, 1000 Ergebnisse
Sensor 21850: Seite 2, 871 Ergebnisse
Sensor 21857: Seite 1, 1000 Ergebnisse
Sensor 21857: Seite 2, 863 Ergebnisse
Sensor 21861: Seite 1, 1000 Ergebnisse
Sensor 21861: Seite 2, 824 Ergebnisse
Sensor 21765: Seite 1, 1000 Ergebnisse
Sensor 21765: Seite 2, 359 Ergebnisse
Sensor 9324553: Seite 1, 593 Ergebnisse
Sensor 23472: Seite 1, 1000 Ergebnisse
Sensor 23472: Seite 2, 562 Ergebnisse
Sensor 23475: Seite 1, 1000 Ergebnisse
Sensor 23475: Seite 2, 572 Ergebnisse
Sensor 23480: Seite 1, 1000 Ergebnisse
Sensor 23480: Seite 2, 553 Ergebnisse
Sensor 22636: Seite 1, 738 Ergebnisse
Sensor 7772744: Seite 1, 530 Ergebnisse
Sensor 7774426: Seite 1, 701 Ergebnisse
Sensor 7775914: Seite 1, 644 Ergebnisse
Sensor 5078264: Seite 1, 813 Ergebnisse
Sensor 7773744: Seite 1, 690 Ergebnisse
Sensor 7772850: Seite 1, 709 Ergebnisse
Sensor 9324555: Seite 1, 566 Ergebnisse
Sensor 7775024: Seite 1, 613 Ergebnisse
Sensor 15538678: Seite 1, 4 Ergebnisse
Sensor 7772749: Seite 1, 667 Ergebnisse
Sensor 7775618: Seite 1, 711 Ergebnisse
Sensor 7774544: Seite 1, 655 Ergebnisse
Sensor 7774841: Seite 1, 659 Ergebnisse
Sensor 9323263: Seite 1, 342 Ergebnisse
Sensor 7774785: Seite 1, 696 Ergebnisse
Sensor 7775409: Seite 1, 671 Ergebnisse
Sensor 7774279: Seite 1, 663 Ergebnisse
Sensor 7775178: Seite 1, 489 Ergebnisse
Sensor 7773552: Seite 1, 636 Ergebnisse
Sensor 7775778: Seite 1, 636 Ergebnisse
Sensor 7775099: Seite 1, 646 Ergebnisse
Sensor 7773017: Seite 1, 694 Ergebnisse
Sensor 7773388: Seite 1, 674 Ergebnisse
Sensor 7773064: Seite 1, 633 Ergebnisse
Sensor 7773043: Seite 1, 683 Ergebnisse
Sensor 15538682: Seite 1, 5 Ergebnisse
Sensor 5078294: Seite 1, 809 Ergebnisse
Sensor 5078267: Seite 1, 812 Ergebnisse
Sensor 5078291: Seite 1, 816 Ergebnisse
Sensor 5078302: Seite 1, 805 Ergebnisse
Sensor 24420: Seite 1, 1000 Ergebnisse
Sensor 24420: Seite 2, 677 Ergebnisse
Sensor 5078270: Seite 1, 821 Ergebnisse
Sensor 5078293: Seite 1, 824 Ergebnisse
Sensor 24694: Seite 1, 1000 Ergebnisse
Sensor 24694: Seite 2, 759 Ergebnisse
Sensor 5078271: Seite 1, 805 Ergebnisse
Sensor 14392771: Seite 1, 128 Ergebnisse
Sensor 15538676: Seite 1, 5 Ergebnisse
Sensor 7774775: Seite 1, 562 Ergebnisse
Sensor 24511: Seite 1, 1000 Ergebnisse
Sensor 24511: Seite 2, 49 Ergebnisse
Sensor 24704: Seite 1, 1000 Ergebnisse
Sensor 24704: Seite 2, 56 Ergebnisse
Sensor 7777172: Seite 1, 739 Ergebnisse
Sensor 22605: Seite 1, 720 Ergebnisse
Sensor 22633: Seite 1, 738 Ergebnisse
Sensor 22634: Seite 1, 723 Ergebnisse
Sensor 15538681: Seite 1, 5 Ergebnisse
Sensor 24568: Seite 1, 1000 Ergebnisse
Sensor 24568: Seite 2, 833 Ergebnisse
Sensor 23986: Seite 1, 1000 Ergebnisse
Sensor 23986: Seite 2, 845 Ergebnisse
Sensor 23990: Seite 1, 1000 Ergebnisse
Sensor 23990: Seite 2, 797 Ergebnisse
Sensor 7774921: Seite 1, 570 Ergebnisse
Sensor 7774326: Seite 1, 718 Ergebnisse
Sensor 1764525: Seite 1, 1000 Ergebnisse
Sensor 1764525: Seite 2, 240 Ergebnisse
Sensor 24306: Seite 1, 1000 Ergebnisse
Sensor 24306: Seite 2, 497 Ergebnisse
Sensor 24381: Seite 1, 1000 Ergebnisse
Sensor 24381: Seite 2, 754 Ergebnisse
Sensor 9323266: Seite 1, 595 Ergebnisse
Sensor 24415: Seite 1, 1000 Ergebnisse
Sensor 24415: Seite 2, 733 Ergebnisse
Sensor 12907940: Seite 1, 281 Ergebnisse
Sensor 7773584: Seite 1, 658 Ergebnisse
Sensor 24534: Seite 1, 1000 Ergebnisse
Sensor 24534: Seite 2, 725 Ergebnisse
Sensor 24542: Seite 1, 1000 Ergebnisse
Sensor 24542: Seite 2, 930 Ergebnisse
Sensor 24558: Seite 1, 1000 Ergebnisse
Sensor 24558: Seite 2, 858 Ergebnisse
Sensor 2142719: Seite 1, 1000 Ergebnisse
Sensor 2142719: Seite 2, 64 Ergebnisse
Sensor 1702605: Seite 1, 1000 Ergebnisse
Sensor 1702605: Seite 2, 279 Ergebnisse
Sensor 13931888: Seite 1, 185 Ergebnisse
Sensor 15538665: Seite 1, 5 Ergebnisse
Sensor 1702604: Seite 1, 1000 Ergebnisse
Sensor 1702604: Seite 2, 250 Ergebnisse
Sensor 15538699: Seite 1, 4 Ergebnisse
Sensor 15556737: Seite 1, 5 Ergebnisse
Sensor 15545436: Seite 1, 4 Ergebnisse
Sensor 15538693: Seite 1, 5 Ergebnisse
Sensor 15538697: Seite 1, 5 Ergebnisse
Sensor 15556740: Seite 1, 4 Ergebnisse
Sensor 15538667: Seite 1, 5 Ergebnisse
Sensor 15538703: Seite 1, 5 Ergebnisse
Sensor 7531551: Seite 1, 712 Ergebnisse
Sensor 25056: Seite 1, 1000 Ergebnisse
Sensor 25056: Seite 2, 762 Ergebnisse
Sensor 22273: Seite 1, 749 Ergebnisse
Sensor 24489: Seite 1, 1000 Ergebnisse
Sensor 24489: Seite 2, 218 Ergebnisse
Sensor 24505: Seite 1, 1000 Ergebnisse
Sensor 24505: Seite 2, 47 Ergebnisse
Sensor 15538680: Seite 1, 5 Ergebnisse
Sensor 24409: Seite 1, 1000 Ergebnisse
Sensor 24409: Seite 2, 726 Ergebnisse
Sensor 5078279: Seite 1, 828 Ergebnisse
Sensor 5078286: Seite 1, 801 Ergebnisse
Sensor 5078287: Seite 1, 793 Ergebnisse
Sensor 15538675: Seite 1, 5 Ergebnisse
Sensor 22257: Seite 1, 1000 Ergebnisse
Sensor 22257: Seite 2, 455 Ergebnisse
Sensor 15545437: Seite 1, 4 Ergebnisse
Sensor 5078274: Seite 1, 869 Ergebnisse
Sensor 15538670: Seite 1, 5 Ergebnisse
Sensor 1287742: Seite 1, 767 Ergebnisse
Sensor 1288173: Seite 1, 763 Ergebnisse
Sensor 1288150: Seite 1, 751 Ergebnisse
Sensor 15538696: Seite 1, 5 Ergebnisse
Sensor 5079445: Seite 1, 937 Ergebnisse
Sensor 5079452: Seite 1, 947 Ergebnisse
Sensor 5079458: Seite 1, 992 Ergebnisse
Sensor 5079014: Seite 1, 815 Ergebnisse
Sensor 5078814: Seite 1, 808 Ergebnisse
Sensor 5079210: Seite 1, 609 Ergebnisse
Sensor 7777632: Seite 1, 672 Ergebnisse
Sensor 15538673: Seite 1, 4 Ergebnisse
Sensor 2671728: Seite 1, 1 Ergebnisse
Sensor 5078729: Seite 1, 840 Ergebnisse
Sensor 6530163: Seite 1, 332 Ergebnisse
Sensor 6606148: Seite 1, 1 Ergebnisse
Sensor 6661852: Seite 1, 417 Ergebnisse
Sensor 7336787: Seite 1, 822 Ergebnisse
Sensor 9323264: Seite 1, 169 Ergebnisse
Sensor 7774579: Seite 1, 647 Ergebnisse
Sensor 7775760: Seite 1, 640 Ergebnisse
Sensor 7774140: Seite 1, 712 Ergebnisse
Sensor 7775291: Seite 1, 646 Ergebnisse
Sensor 8622694: Seite 1, 630 Ergebnisse
Sensor 7774003: Seite 1, 664 Ergebnisse
Sensor 7775963: Seite 1, 710 Ergebnisse
Sensor 7774162: Seite 1, 713 Ergebnisse
Sensor 7777523: Seite 1, 674 Ergebnisse
Sensor 7775039: Seite 1, 610 Ergebnisse
Sensor 14392773: Seite 1, 132 Ergebnisse
Sensor 14392775: Seite 1, 132 Ergebnisse
Sensor 14392768: Seite 1, 132 Ergebnisse
Sensor 14392761: Seite 1, 134 Ergebnisse
Sensor 14392770: Seite 1, 132 Ergebnisse
Sensor 14392756: Seite 1, 131 Ergebnisse
Sensor 14392785: Seite 1, 134 Ergebnisse
Sensor 14392762: Seite 1, 130 Ergebnisse
Sensor 7774252: Seite 1, 693 Ergebnisse
Sensor 7774309: Seite 1, 686 Ergebnisse
Sensor 14392777: Seite 1, 132 Ergebnisse
Sensor 14392766: Seite 1, 134 Ergebnisse
Sensor 7774365: Seite 1, 656 Ergebnisse
Sensor 14392760: Seite 1, 127 Ergebnisse
Sensor 7774434: Seite 1, 693 Ergebnisse
Sensor 7773114: Seite 1, 716 Ergebnisse
Sensor 7774679: Seite 1, 731 Ergebnisse
Sensor 7773796: Seite 1, 643 Ergebnisse
Sensor 7774706: Seite 1, 646 Ergebnisse
Sensor 7780083: Seite 1, 630 Ergebnisse
Sensor 15538704: Seite 1, 5 Ergebnisse
Sensor 15538679: Seite 1, 5 Ergebnisse
Sensor 15567071: Seite 1, 3 Ergebnisse
Sensor 7773115: Seite 1, 689 Ergebnisse
Sensor 7773609: Seite 1, 681 Ergebnisse
Sensor 9323267: Seite 1, 579 Ergebnisse
Sensor 7852822: Seite 1, 652 Ergebnisse
Sensor 7852816: Seite 1, 652 Ergebnisse
Sensor 7852818: Seite 1, 651 Ergebnisse
Sensor 7774000: Seite 1, 711 Ergebnisse
Sensor 7773382: Seite 1, 146 Ergebnisse
Sensor 7852820: Seite 1, 652 Ergebnisse
Sensor 14392784: Seite 1, 129 Ergebnisse
Sensor 8433565: Seite 1, 189 Ergebnisse
Sensor 8618983: Seite 1, 6 Ergebnisse
Sensor 10646491: Seite 1, 5 Ergebnisse
Sensor 10874824: Seite 1, 431 Ergebnisse
Sensor 10904608: Seite 1, 507 Ergebnisse
Sensor 11287563: Seite 1, 428 Ergebnisse
Sensor 11475722: Seite 1, 429 Ergebnisse
Sensor 11484317: Seite 1, 384 Ergebnisse
Sensor 11542074: Seite 1, 423 Ergebnisse
Sensor 11901451: Seite 1, 392 Ergebnisse
Sensor 12187655: Seite 1, 368 Ergebnisse
Sensor 12453265: Seite 1, 353 Ergebnisse
Sensor 12612135: Seite 1, 332 Ergebnisse
Sensor 13388485: Seite 1, 108 Ergebnisse
Sensor 13480491: Seite 1, 220 Ergebnisse
Sensor 13850807: Seite 1, 199 Ergebnisse
Sensor 14046259: Seite 1, 170 Ergebnisse
Sensor 14152500: Seite 1, 163 Ergebnisse
Sensor 14153911: Seite 1, 128 Ergebnisse
Sensor 14454621: Seite 1, 126 Ergebnisse
Sensor 14485762: Seite 1, 118 Ergebnisse
Sensor 14515495: Seite 1, 119 Ergebnisse
Sensor 14522873: Seite 1, 2 Ergebnisse
Sensor 14559514: Seite 1, 113 Ergebnisse
Sensor 14640526: Seite 1, 106 Ergebnisse
Sensor 14675922: Seite 1, 102 Ergebnisse
Sensor 14764471: Seite 1, 91 Ergebnisse
Sensor 14930673: Seite 1, 72 Ergebnisse
Sensor 15039756: Seite 1, 60 Ergebnisse
Sensor 15106061: Seite 1, 50 Ergebnisse
Sensor 15152586: Seite 1, 47 Ergebnisse
Sensor 15153844: Seite 1, 47 Ergebnisse
Sensor 15204307: Seite 1, 37 Ergebnisse
Sensor 15244073: Seite 1, 22 Ergebnisse
Sensor 15300524: Seite 1, 22 Ergebnisse
Sensor 15402794: Seite 1, 1 Ergebnisse
151798

[{'date': '2020-03-28', 'value': 28.0},
 {'date': '2020-03-30', 'value': 17.0},
 {'date': '2020-03-31', 'value': 15.0},
 {'date': '2020-04-01', 'value': 12.0},
 {'date': '2020-04-02', 'value': 19.0},
 {'date': '2020-04-03', 'value': 21.0},
 {'date': '2020-04-04', 'value': 26.0},
 {'date': '2020-04-05', 'value': 27.0},
 {'date': '2020-04-06', 'value': 25.0},
 {'date': '2020-04-07', 'value': 31.0},
 {'date': '2020-04-09', 'value': 17.0},
 {'date': '2020-04-10', 'value': 12.0},
 {'date': '2020-04-11', 'value': 14.0},
 {'date': '2020-04-12', 'value': 10.0},
 {'date': '2020-04-13', 'value': 4.0},
 {'date': '2020-04-14', 'value': 7.0},
 {'date': '2020-04-15', 'value': 14.0},
 {'date': '2020-04-16', 'value': 13.0},
 {'date': '2020-04-17', 'value': 18.0},
 {'date': '2020-04-18', 'value': 18.0},
 {'date': '2020-04-19', 'value': 6.0},
 {'date': '2020-04-20', 'value': 0.0},
 {'date': '2020-04-21', 'value': 0.0},
 {'date': '2020-04-22', 'value': 4.0},
 {'date': '2020-04-23', 'value': 13.0},
 {'date': '2020-04-24', 'value': 25.0},
 {'date': '2020-04-25', 'value': 20.0},
 {'date': '2020-04-26', 'value': 6.0},
 {'date': '2020-04-27', 'value': 4.0},
 {'date': '2020-04-28', 'value': 5.0},
 {'date': '2020-04-29', 'value': 1.0},
 {'date': '2020-04-30', 'value': 4.0},
 {'date': '2020-05-01', 'value': 0.0},
 {'date': '2020-05-02', 'value': 2.0},
 {'date': '2020-05-03', 'value': 5.0},
 {'date': '2020-05-04', 'value': 11.0},
 {'date': '2020-05-05', 'value': 10.0},
 {'date': '2020-05-06', 'value': 14.0},
 {'date': '2020-03-28', 'value': 23.0},
 {'date': '2020-03-30', 'value': 12.0},
 {'date': '2020-03-31', 'value': 10.0},
 {'date': '2020-04-01', 'value': 7.0},
 {'date': '2020-04-02', 'value': 11.0},
 {'date': '2020-04-03', 'value': 15.0},
 {'date': '2020-04-04', 'value': 20.0},
 {'date': '2020-04-05', 'value': 19.0},
 {'date': '2020-04-06', 'value': 16.0},
 {'date': '2020-04-07', 'value': 20.0},
 {'date': '2020-04-09', 'value': 12.0},
 {'date': '2020-04-10', 'value': 12.0},
 {'date': '2020-04-11', 'value': 14.0},
 {'date': '2020-04-12', 'value': 17.0},
 {'date': '2020-04-13', 'value': 8.0},
 {'date': '2020-04-14', 'value': 10.0},
 {'date': '2020-04-15', 'value': 9.0},
 {'date': '2020-04-16', 'value': 12.0},
 {'date': '2020-04-17', 'value': 12.0},
 {'date': '2020-04-18', 'value': 13.0},
 {'date': '2020-04-19', 'value': 10.0},
 {'date': '2020-04-20', 'value': 13.0},
 {'date': '2020-04-21', 'value': 11.0},
 {'date': '2020-04-22', 'value': 11.0},
 {'date': '2020-04-23', 'value': 13.0},
 {'date': '2020-04-24', 'value': 15.0},
 {'date': '2020-04-25', 'value': 13.0},
 {'date': '2020-04-26', 'value': 6.0},
 {'date': '2020-04-27', 'value': 5.0},
 {'date': '2020-04-28', 'value': 7.0},
 {'date': '2020-04-29', 'value': 3.0},
 {'date': '2020-04-30', 'value': 4.0},
 {'date': '2020-05-01', 'value': 6.0},
 {'date': '2020-05-02', 'value': 2.0},
 {'date': '2020-05-03', 'value': 4.0},
 {'date': '2020-05-04', 'value': 8.0},
 {'date': '2020-05-05', 'value': 9.0},
 {'date': '2020-05-06', 'value': 12.0},
 {'date': '2020-03-28', 'value': 35.0},
 {'date': '2020-03-30', 'value': 25.0},
 {'date': '2020-03-31', 'value': 17.0},
 {'date': '2020-04-01', 'value': 7.0},
 {'date': '2020-04-02', 'value': 17.0},
 {'date': '2020-04-03', 'value': 20.0},
 {'date': '2020-04-04', 'value': 26.0},
 {'date': '2020-04-05', 'value': 25.0},
 {'date': '2020-04-06', 'value': 21.0},
 {'date': '2020-04-07', 'value': 23.0},
 {'date': '2020-04-09', 'value': 18.0},
 {'date': '2020-04-10', 'value': 14.0},
 {'date': '2020-04-11', 'value': 18.0},
 {'date': '2020-04-12', 'value': 15.0},
 {'date': '2020-04-13', 'value': 10.0},
 {'date': '2020-04-14', 'value': 16.0},
 {'date': '2020-04-15', 'value': 16.0},
 {'date': '2020-04-16', 'value': 12.0},
 {'date': '2020-04-17', 'value': 15.0},
 {'date': '2020-04-18', 'value': 15.0},
 {'date': '2020-04-19', 'value': 12.0},
 {'date': '2020-04-20', 'value': 14.0},
 {'date': '2020-04-21', 'value': 14.0},
 {'date': '2020-04-22', 'value': 14.0},
 {'date': '2020-04-23', 'value': 17.0},
 {'date': '2020-04-24', 'value': 19.0},
 {'date': '2020-04-25', 'value': 18.0},
 {'date': '2020-04-26', 'value': 13.0},
 {'date': '2020-04-27', 'value': 9.0},
 {'date': '2020-04-28', 'value': 10.0},
 {'date': '2020-04-29', 'value': 7.0},
 {'date': '2020-04-30', 'value': 9.0},
 {'date': '2020-05-01', 'value': 9.0},
 {'date': '2020-05-02', 'value': 8.0},
 {'date': '2020-05-03', 'value': 7.0},
 {'date': '2020-05-04', 'value': 9.0},
 {'date': '2020-05-05', 'value': 7.0},
 {'date': '2020-05-06', 'value': 9.0},
 {'date': '2020-03-28', 'value': 31.0},
 {'date': '2020-03-30', 'value': 24.0},
 {'date': '2020-03-31', 'value': 10.0},
 {'date': '2020-04-01', 'value': 7.0},
 {'date': '2020-04-02', 'value': 9.0},
 {'date': '2020-04-03', 'value': 12.0},
 {'date': '2020-04-04', 'value': 17.0},
 {'date': '2020-04-05', 'value': 15.0},
 {'date': '2020-04-06', 'value': 13.0},
 {'date': '2020-04-07', 'value': 22.0},
 {'date': '2020-04-09', 'value': 16.0},
 {'date': '2020-04-10', 'value': 13.0},
 {'date': '2020-04-11', 'value': 14.0},
 {'date': '2020-04-12', 'value': 17.0},
 {'date': '2020-04-13', 'value': 14.0},
 {'date': '2020-04-14', 'value': 12.0},
 {'date': '2020-04-15', 'value': 9.0},
 {'date': '2020-04-16', 'value': 6.0},
 {'date': '2020-04-17', 'value': 8.0},
 {'date': '2020-04-18', 'value': 9.0},
 {'date': '2020-04-19', 'value': 4.0},
 {'date': '2020-04-20', 'value': 2.0},
 {'date': '2020-04-21', 'value': 3.0},
 {'date': '2020-04-22', 'value': 4.0},
 {'date': '2020-04-23', 'value': 6.0},
 {'date': '2020-04-24', 'value': 16.0},
 {'date': '2020-04-25', 'value': 17.0},
 {'date': '2020-04-26', 'value': 9.0},
 {'date': '2020-04-27', 'value': 8.0},
 {'date': '2020-04-28', 'value': 5.0},
 {'date': '2020-04-29', 'value': 3.0},
 {'date': '2020-04-30', 'value': 2.0},
 {'date': '2020-05-01', 'value': 2.0},
 {'date': '2020-05-02', 'value': 1.0},
 {'date': '2020-05-03', 'value': 3.0},
 {'date': '2020-05-04', 'value': 4.0},
 {'date': '2020-05-05', 'value': 5.0},
 {'date': '2020-05-06', 'value': 6.0},
 {'date': '2020-03-28', 'value': 29.0},
 {'date': '2020-03-30', 'value': 25.0},
 {'date': '2020-03-31', 'value': 14.0},
 {'date': '2020-04-01', 'value': 8.0},
 {'date': '2020-04-02', 'value': 12.0},
 {'date': '2020-04-03', 'value': 20.0},
 {'date': '2020-04-04', 'value': 20.0},
 {'date': '2020-04-05', 'value': 24.0},
 {'date': '2020-04-06', 'value': 16.0},
 {'date': '2020-04-07', 'value': 22.0},
 {'date': '2020-04-09', 'value': 17.0},
 {'date': '2020-04-10', 'value': 15.0},
 {'date': '2020-04-11', 'value': 16.0},
 {'date': '2020-04-12', 'value': 21.0},
 {'date': '2020-04-13', 'value': 13.0},
 {'date': '2020-04-14', 'value': 10.0},
 {'date': '2020-04-15', 'value': 10.0},
 {'date': '2020-04-16', 'value': 7.0},
 {'date': '2020-04-17', 'value': 12.0},
 {'date': '2020-04-18', 'value': 18.0},
 {'date': '2020-04-19', 'value': 16.0},
 {'date': '2020-04-20', 'value': 14.0},
 {'date': '2020-04-21', 'value': 1.0},
 {'date': '2020-04-22', 'value': 6.0},
 {'date': '2020-04-23', 'value': 9.0},
 {'date': '2020-04-24', 'value': 19.0},
 {'date': '2020-04-25', 'value': 18.0},
 {'date': '2020-04-26', 'value': 10.0},
 {'date': '2020-04-27', 'value': 8.0},
 {'date': '2020-04-28', 'value': 8.0},
 {'date': '2020-04-29', 'value': 2.0},
 {'date': '2020-04-30', 'value': 4.0},
 {'date': '2020-05-01', 'value': 2.0},
 {'date': '2020-05-02', 'value': 2.0},
 {'date': '2020-05-03', 'value': 9.0},
 {'date': '2020-05-04', 'value': 7.0},
 {'date': '2020-05-05', 'value': 8.0},
 {'date': '2020-05-06', 'value': 9.0},
 {'date': '2020-03-28', 'value': 20.0},
 {'date': '2020-03-30', 'value': 14.0},
 {'date': '2020-03-31', 'value': 9.0},
 {'date': '2020-04-01', 'value': 4.0},
 {'date': '2020-04-02', 'value': 9.0},
 {'date': '2020-04-03', 'value': 14.0},
 {'date': '2020-04-04', 'value': 14.0},
 {'date': '2020-04-05', 'value': 16.0},
 {'date': '2020-04-06', 'value': 12.0},
 {'date': '2020-04-07', 'value': 19.0},
 {'date': '2020-04-09', 'value': 11.0},
 {'date': '2020-04-10', 'value': 9.0},
 {'date': '2020-04-16', 'value': 9.0},
 {'date': '2020-04-17', 'value': 9.0},
 {'date': '2020-04-18', 'value': 9.0},
 {'date': '2020-04-19', 'value': 9.0},
 {'date': '2020-04-20', 'value': 5.0},
 {'date': '2020-04-21', 'value': 3.0},
 {'date': '2020-04-22', 'value': 5.0},
 {'date': '2020-04-23', 'value': 10.0},
 {'date': '2020-04-25', 'value': 13.0},
 {'date': '2020-04-26', 'value': 8.0},
 {'date': '2020-04-27', 'value': 6.0},
 {'date': '2020-04-28', 'value': 7.0},
 {'date': '2020-04-29', 'value': 2.0},
 {'date': '2020-04-30', 'value': 5.0},
 {'date': '2020-05-01', 'value': 1.0},
 {'date': '2020-05-02', 'value': 1.0},
 {'date': '2020-05-03', 'value': 5.0},
 {'date': '2020-05-04', 'value': 5.0},
 {'date': '2020-05-05', 'value': 6.0},
 {'date': '2020-05-06', 'value': 4.0},
 {'date': '2020-03-28', 'value': 22.0},
 {'date': '2020-03-30', 'value': 12.0},
 {'date': '2020-03-31', 'value': 11.0},
 {'date': '2020-04-02', 'value': 13.0},
 {'date': '2020-04-03', 'value': 17.0},
 {'date': '2020-04-04', 'value': 23.0},
 {'date': '2020-04-05', 'value': 20.0},
 {'date': '2020-04-06', 'value': 16.0},
 {'date': '2020-04-07', 'value': 20.0},
 {'date': '2020-04-09', 'value': 11.0},
 {'date': '2020-04-14', 'value': 11.0},
 {'date': '2020-04-16', 'value': 17.0},
 {'date': '2020-04-17', 'value': 11.0},
 {'date': '2020-04-18', 'value': 12.0},
 {'date': '2020-04-19', 'value': 17.0},
 {'date': '2020-04-20', 'value': 7.0},
 {'date': '2020-04-21', 'value': 10.0},
 {'date': '2020-04-22', 'value': 6.0},
 {'date': '2020-04-23', 'value': 12.0},
 {'date': '2020-04-24', 'value': 19.0},
 {'date': '2020-04-25', 'value': 15.0},
 {'date': '2020-04-26', 'value': 10.0},
 {'date': '2020-04-27', 'value': 8.0},
 {'date': '2020-04-28', 'value': 4.0},
 {'date': '2020-04-29', 'value': 3.0},
 {'date': '2020-04-30', 'value': 3.0},
 {'date': '2020-05-01', 'value': 2.0},
 {'date': '2020-05-02', 'value': 1.0},
 {'date': '2020-05-03', 'value': 4.0},
 {'date': '2020-05-04', 'value': 7.0},
 {'date': '2020-05-06', 'value': 6.0},
 {'date': '2020-03-28', 'value': 33.0},
 {'date': '2020-03-30', 'value': 25.0},
 {'date': '2020-03-31', 'value': 12.0},
 {'date': '2020-04-01', 'value': 6.0},
 {'date': '2020-04-02', 'value': 12.0},
 {'date': '2020-04-03', 'value': 20.0},
 {'date': '2020-04-04', 'value': 23.0},
 {'date': '2020-04-05', 'value': 27.0},
 {'date': '2020-04-06', 'value': 17.0},
 {'date': '2020-04-07', 'value': 27.0},
 {'date': '2020-04-09', 'value': 14.0},
 {'date': '2020-04-10', 'value': 15.0},
 {'date': '2020-04-11', 'value': 18.0},
 {'date': '2020-04-12', 'value': 21.0},
 {'date': '2020-04-13', 'value': 17.0},
 {'date': '2020-04-14', 'value': 11.0},
 {'date': '2020-04-15', 'value': 8.0},
 {'date': '2020-04-16', 'value': 7.0},
 {'date': '2020-04-17', 'value': 11.0},
 {'date': '2020-04-18', 'value': 15.0},
 {'date': '2020-04-19', 'value': 12.0},
 {'date': '2020-04-20', 'value': 9.0},
 {'date': '2020-04-21', 'value': 2.0},
 {'date': '2020-04-22', 'value': 5.0},
 {'date': '2020-04-23', 'value': 12.0},
 {'date': '2020-04-24', 'value': 20.0},
 {'date': '2020-04-25', 'value': 20.0},
 {'date': '2020-04-26', 'value': 10.0},
 {'date': '2020-04-27', 'value': 8.0},
 {'date': '2020-04-28', 'value': 8.0},
 {'date': '2020-04-29', 'value': 2.0},
 {'date': '2020-04-30', 'value': 3.0},
 {'date': '2020-05-01', 'value': 2.0},
 {'date': '2020-05-02', 'value': 3.0},
 {'date': '2020-05-03', 'value': 8.0},
 {'date': '2020-05-04', 'value': 7.0},
 {'date': '2020-05-05', 'value': 5.0},
 {'date': '2020-05-06', 'value': 8.0},
 {'date': '2020-03-28', 'value': 34.0},
 {'date': '2020-03-30', 'value': 27.0},
 {'date': '2020-03-31', 'value': 15.0},
 {'date': '2020-04-01', 'value': 7.0},
 {'date': '2020-04-02', 'value': 12.0},
 {'date': '2020-04-03', 'value': 21.0},
 {'date': '2020-04-04', 'value': 18.0},
 {'date': '2020-04-05', 'value': 31.0},
 {'date': '2020-04-06', 'value': 16.0},
 {'date': '2020-04-07', 'value': 25.0},
 {'date': '2020-04-09', 'value': 16.0},
 {'date': '2020-04-10', 'value': 17.0},
 {'date': '2020-04-11', 'value': 21.0},
 {'date': '2020-04-12', 'value': 22.0},
 {'date': '2020-04-13', 'value': 18.0},
 {'date': '2020-04-14', 'value': 14.0},
 {'date': '2020-04-15', 'value': 11.0},
 {'date': '2020-04-16', 'value': 8.0},
 {'date': '2020-04-17', 'value': 14.0},
 {'date': '2020-04-18', 'value': 18.0},
 {'date': '2020-04-19', 'value': 18.0},
 {'date': '2020-04-20', 'value': 13.0},
 {'date': '2020-04-21', 'value': 8.0},
 {'date': '2020-04-22', 'value': 8.0},
 {'date': '2020-04-23', 'value': 11.0},
 {'date': '2020-04-24', 'value': 16.0},
 {'date': '2020-04-25', 'value': 19.0},
 {'date': '2020-04-26', 'value': 13.0},
 {'date': '2020-04-27', 'value': 13.0},
 {'date': '2020-04-28', 'value': 9.0},
 {'date': '2020-04-29', 'value': 6.0},
 {'date': '2020-04-30', 'value': 8.0},
 {'date': '2020-05-01', 'value': 4.0},
 {'date': '2020-05-02', 'value': 5.0},
 {'date': '2020-05-03', 'value': 11.0},
 {'date': '2020-05-04', 'value': 6.0},
 {'date': '2020-05-05', 'value': 7.0},
 {'date': '2020-05-06', 'value': 11.0},
 {'date': '2020-03-28', 'value': 22.0},
 {'date': '2020-03-30', 'value': 11.0},
 {'date': '2020-03-31', 'value': 7.0},
 {'date': '2020-04-01', 'value': 3.0},
 {'date': '2020-04-02', 'value': 6.0},
 {'date': '2020-04-03', 'value': 11.0},
 {'date': '2020-04-04', 'value': 14.0},
 {'date': '2020-04-05', 'value': 18.0},
 {'date': '2020-04-06', 'value': 14.0},
 {'date': '2020-04-07', 'value': 18.0},
 {'date': '2020-04-09', 'value': 11.0},
 {'date': '2020-04-10', 'value': 10.0},
 {'date': '2020-04-11', 'value': 11.0},
 {'date': '2020-04-12', 'value': 10.0},
 {'date': '2020-04-13', 'value': 7.0},
 {'date': '2020-04-14', 'value': 12.0},
 {'date': '2020-04-15', 'value': 7.0},
 {'date': '2020-04-16', 'value': 7.0},
 {'date': '2020-04-17', 'value': 6.0},
 {'date': '2020-04-18', 'value': 9.0},
 {'date': '2020-04-19', 'value': 7.0},
 {'date': '2020-04-20', 'value': 6.0},
 {'date': '2020-04-22', 'value': 1.0},
 {'date': '2020-04-23', 'value': 9.0},
 {'date': '2020-04-24', 'value': 15.0},
 {'date': '2020-04-25', 'value': 12.0},
 {'date': '2020-04-26', 'value': 8.0},
 {'date': '2020-04-27', 'value': 5.0},
 {'date': '2020-04-28', 'value': 5.0},
 {'date': '2020-04-29', 'value': 2.0},
 {'date': '2020-04-30', 'value': 2.0},
 {'date': '2020-05-01', 'value': 2.0},
 {'date': '2020-05-02', 'value': 2.0},
 {'date': '2020-05-03', 'value': 2.0},
 {'date': '2020-05-04', 'value': 4.0},
 {'date': '2020-05-05', 'value': 6.0},
 {'date': '2020-05-06', 'value': 4.0},
 {'date': '2020-03-28', 'value': 37.0},
 {'date': '2020-03-30', 'value': 24.0},
 {'date': '2020-03-31', 'value': 15.0},
 {'date': '2020-04-01', 'value': 7.0},
 {'date': '2020-04-02', 'value': 9.0},
 {'date': '2020-04-03', 'value': 18.0},
 {'date': '2020-04-04', 'value': 21.0},
 {'date': '2020-04-05', 'value': 22.0},
 {'date': '2020-04-06', 'value': 13.0},
 {'date': '2020-04-07', 'value': 23.0},
 {'date': '2020-04-09', 'value': 19.0},
 {'date': '2020-04-10', 'value': 15.0},
 {'date': '2020-04-11', 'value': 17.0},
 {'date': '2020-04-12', 'value': 22.0},
 {'date': '2020-04-13', 'value': 19.0},
 {'date': '2020-04-14', 'value': 16.0},
 {'date': '2020-04-15', 'value': 12.0},
 {'date': '2020-04-16', 'value': 9.0},
 {'date': '2020-04-17', 'value': 9.0},
 {'date': '2020-04-18', 'value': 15.0},
 {'date': '2020-04-19', 'value': 21.0},
 {'date': '2020-04-20', 'value': 17.0},
 {'date': '2020-04-21', 'value': 9.0},
 {'date': '2020-04-22', 'value': 10.0},
 {'date': '2020-04-23', 'value': 12.0},
 {'date': '2020-04-24', 'value': 17.0},
 {'date': '2020-04-25', 'value': 17.0},
 {'date': '2020-04-26', 'value': 11.0},
 {'date': '2020-04-27', 'value': 9.0},
 {'date': '2020-04-28', 'value': 11.0},
 {'date': '2020-04-29', 'value': 6.0},
 {'date': '2020-04-30', 'value': 6.0},
 {'date': '2020-05-01', 'value': 6.0},
 {'date': '2020-05-02', 'value': 6.0},
 {'date': '2020-05-03', 'value': 8.0},
 {'date': '2020-05-04', 'value': 5.0},
 {'date': '2020-05-05', 'value': 5.0},
 {'date': '2020-05-06', 'value': 7.0},
 {'date': '2020-03-28', 'value': 35.0},
 {'date': '2020-03-30', 'value': 26.0},
 {'date': '2020-03-31', 'value': 14.0},
 {'date': '2020-04-01', 'value': 8.0},
 {'date': '2020-04-02', 'value': 15.0},
 {'date': '2020-04-03', 'value': 25.0},
 {'date': '2020-04-04', 'value': 25.0},
 {'date': '2020-04-05', 'value': 27.0},
 {'date': '2020-04-06', 'value': 15.0},
 {'date': '2020-04-07', 'value': 24.0},
 {'date': '2020-04-09', 'value': 19.0},
 {'date': '2020-04-10', 'value': 18.0},
 {'date': '2020-04-11', 'value': 19.0},
 {'date': '2020-04-12', 'value': 23.0},
 {'date': '2020-04-13', 'value': 13.0},
 {'date': '2020-04-14', 'value': 13.0},
 {'date': '2020-04-15', 'value': 10.0},
 {'date': '2020-04-16', 'value': 12.0},
 {'date': '2020-04-17', 'value': 16.0},
 {'date': '2020-04-18', 'value': 22.0},
 {'date': '2020-04-19', 'value': 20.0},
 {'date': '2020-04-20', 'value': 16.0},
 {'date': '2020-04-21', 'value': 8.0},
 {'date': '2020-04-22', 'value': 11.0},
 {'date': '2020-04-23', 'value': 13.0},
 {'date': '2020-04-24', 'value': 21.0},
 {'date': '2020-04-25', 'value': 19.0},
 {'date': '2020-04-26', 'value': 9.0},
 {'date': '2020-04-27', 'value': 8.0},
 {'date': '2020-04-28', 'value': 7.0},
 {'date': '2020-04-29', 'value': 4.0},
 {'date': '2020-04-30', 'value': 5.0},
 {'date': '2020-05-01', 'value': 4.0},
 {'date': '2020-05-02', 'value': 3.0},
 {'date': '2020-05-03', 'value': 9.0},
 {'date': '2020-05-04', 'value': 7.0},
 {'date': '2020-05-05', 'value': 7.0},
 {'date': '2020-05-06', 'value': 9.0},
 {'date': '2020-03-28', 'value': 32.0},
 {'date': '2020-03-30', 'value': 27.0},
 {'date': '2020-03-31', 'value': 12.0},
 {'date': '2020-04-01', 'value': 9.0},
 {'date': '2020-04-02', 'value': 12.0},
 {'date': '2020-04-03', 'value': 22.0},
 {'date': '2020-04-04', 'value': 24.0},
 {'date': '2020-04-05', 'value': 21.0},
 {'date': '2020-04-06', 'value': 6.0},
 {'date': '2020-04-07', 'value': 23.0},
 {'date': '2020-04-09', 'value': 16.0},
 {'date': '2020-04-10', 'value': 14.0},
 {'date': '2020-04-11', 'value': 17.0},
 {'date': '2020-04-12', 'value': 21.0},
 {'date': '2020-04-13', 'value': 13.0},
 {'date': '2020-04-14', 'value': 10.0},
 {'date': '2020-04-15', 'value': 5.0},
 {'date': '2020-04-16', 'value': 7.0},
 {'date': '2020-04-17', 'value': 10.0},
 {'date': '2020-04-18', 'value': 17.0},
 {'date': '2020-04-19', 'value': 10.0},
 {'date': '2020-04-20', 'value': 7.0},
 {'date': '2020-04-21', 'value': 3.0},
 {'date': '2020-04-22', 'value': 4.0},
 {'date': '2020-04-23', 'value': 10.0},
 {'date': '2020-04-24', 'value': 19.0},
 {'date': '2020-04-25', 'value': 18.0},
 {'date': '2020-04-26', 'value': 8.0},
 {'date': '2020-04-27', 'value': 6.0},
 {'date': '2020-04-28', 'value': 6.0},
 {'date': '2020-04-29', 'value': 1.0},
 {'date': '2020-04-30', 'value': 1.0},
 {'date': '2020-05-01', 'value': 0.0},
 {'date': '2020-05-02', 'value': 0.0},
 {'date': '2020-05-03', 'value': 5.0},
 {'date': '2020-05-04', 'value': 4.0},
 {'date': '2020-05-05', 'value': 6.0},
 {'date': '2020-05-06', 'value': 6.0},
 {'date': '2020-03-28', 'value': 24.0},
 {'date': '2020-03-30', 'value': 13.0},
 {'date': '2020-03-31', 'value': 12.0},
 {'date': '2020-04-01', 'value': 5.0},
 {'date': '2020-04-02', 'value': 11.0},
 {'date': '2020-04-03', 'value': 17.0},
 {'date': '2020-04-04', 'value': 19.0},
 {'date': '2020-04-05', 'value': 19.0},
 {'date': '2020-04-06', 'value': 17.0},
 {'date': '2020-04-07', 'value': 23.0},
 {'date': '2020-04-09', 'value': 12.0},
 {'date': '2020-04-10', 'value': 13.0},
 {'date': '2020-04-11', 'value': 15.0},
 {'date': '2020-04-12', 'value': 13.0},
 {'date': '2020-04-13', 'value': 8.0},
 {'date': '2020-04-14', 'value': 14.0},
 {'date': '2020-04-15', 'value': 12.0},
 {'date': '2020-04-16', 'value': 8.0},
 {'date': '2020-04-17', 'value': 10.0},
 {'date': '2020-04-18', 'value': 12.0},
 {'date': '2020-04-19', 'value': 8.0},
 {'date': '2020-04-20', 'value': 8.0},
 {'date': '2020-04-21', 'value': 4.0},
 {'date': '2020-04-22', 'value': 5.0},
 {'date': '2020-04-23', 'value': 10.0},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [41]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_pm25_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_pm25_mean
0    2018-01-28         27.315789
1    2018-01-29         26.947368
2    2018-01-30         26.526316
3    2018-02-01        -42.210526
4    2018-02-03        -43.052632
...         ...               ...
2792 2026-02-24         26.024905
2793 2026-02-25         26.238816
2794 2026-02-26         26.178332
2795 2026-02-27         29.510096
2796 2026-02-28         26.152940

[2797 rows x 2 columns]

### Convert dataframe to csv

In [37]:
france_daily[["date", "france_pm25_mean"]].to_csv(
    "daily_avg_uk_PM25.csv",
    index=False
)

# NO2

In [51]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "IT",   # only consider stations located in France
    "parameters_id": 5,   # NO2
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_no2 = df_sorted

df_top_no2

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
9,7236,ISONZO,CORSO ISONZO-VIALE CAVOUR - Ferrara (FE),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 20851, 'name': 'co µg/m³', 'parameter'...","{'latitude': 44.84249999990541, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[11.613060000433586, 44.84249999990541, 11.613...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
66,7597,DELTA CERVIA,"VIA JELENIA GORA, 6 - Cervia (RA)",Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22135, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.283889000018235, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[12.332222000093372, 44.283889000018235, 12.33...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
68,7599,BESENZONE,VIA PAVESA BERSANO DI BESENZONE - Besenzone (PC),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22075, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.989444000052735, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[10.019166999885284, 44.989444000052735, 10.01...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
78,7609,CASTELLARANO,VIA REVERBERI - Castellarano (RE),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22091, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.516111000289975, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[10.73388899989651, 44.516111000289975, 10.733...",None,2017-11-01 23:00:00+00:00,2026-03-03 11:00:00+00:00
69,7600,CORTE BRUGNATELLA,Loc. Carana - Corte Brugnatella (PC) - Corte B...,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 22063, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.734729999698565, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[9.366930000033793, 44.734729999698565, 9.3669...",None,2017-11-01 23:00:00+00:00,2025-11-27 10:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,3257911,ANAGNI San Francesco,Via San Francesco- Anagni (FR),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11272039, 'name': 'no2 µg/m³', 'parame...","{'latitude': 41.73193499979726, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[13.140368999858808, 41.73193499979726, 13.140...",None,2024-11-10 07:00:00+00:00,2026-03-03 11:00:00+00:00
423,8516,Parco Urbano,Via M. Durant - Parco Urbano - Vibo Valentia (VV),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11710003, 'name': 'co µg/m³', 'paramet...","{'latitude': 38.66457999972391, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.080239999697902, 38.66457999972391, 16.080...",None,2024-12-15 18:00:00+00:00,2026-03-03 11:00:00+00:00
225,8264,Piazza Castello,PIAZZA CASTELLO - Reggio di Calabria (RC),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12130522, 'name': 'no2 µg/m³', 'parame...","{'latitude': 38.10591000000141, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.645239999653652, 38.10591000000141, 15.645...",None,2025-01-28 14:00:00+00:00,2026-03-03 11:00:00+00:00
272,8316,Via Argentaria,Via Argentaria - Vibo Valentia (VV),Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12130521, 'name': 'no2 µg/m³', 'parame...","{'latitude': 38.67579999999741, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[16.098250000334026, 38.67579999999741, 16.098...",None,2025-01-28 14:00:00+00:00,2026-03-03 11:00:00+00:00
0,5369,Tarquinia,NaN,Europe/Rome,"{'id': 91, 'code': 'IT', 'name': 'Italy'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 151, 'name': 'ARPA Lazio'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13965, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 42.240389, 'longitude': 11.766344}",None,"[11.766344, 42.240389, 11.766344, 42.240389]",None,NaT,NaT

In [47]:
rows = []

for _, station in df_top_no2.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur NO2 behalten
        if sensor["parameter"]["id"] == 5:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_no2_sensors = pd.DataFrame(rows)

df_no2_sensors

     station_id          station_name  sensor_id sensor_name
0          7236                ISONZO      22156   no2 µg/m³
1          7597          DELTA CERVIA      22135   no2 µg/m³
2          7599             BESENZONE      22075   no2 µg/m³
3          7609          CASTELLARANO      22091   no2 µg/m³
4          7600     CORTE BRUGNATELLA      22063   no2 µg/m³
..          ...                   ...        ...         ...
703     3257911  ANAGNI San Francesco   11272039   no2 µg/m³
704        8516          Parco Urbano   11710004   no2 µg/m³
705        8264       Piazza Castello   12130522   no2 µg/m³
706        8316        Via Argentaria   12130521   no2 µg/m³
707        5369             Tarquinia      13965   no2 µg/m³

[708 rows x 4 columns]

In [48]:
sensor_ids = df_no2_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

708

[22156,
 22135,
 22075,
 22091,
 22063,
 19774,
 22137,
 22194,
 22174,
 22170,
 22169,
 21742,
 22159,
 22024,
 22059,
 22183,
 22172,
 22067,
 22073,
 22080,
 22160,
 22082,
 22087,
 22098,
 22095,
 22103,
 22111,
 22191,
 22185,
 22114,
 22200,
 22121,
 22122,
 22128,
 22198,
 22167,
 22145,
 22155,
 22157,
 22184,
 20605,
 20603,
 20604,
 20597,
 22115,
 21873,
 21777,
 21781,
 21782,
 21789,
 21776,
 21780,
 21892,
 21915,
 21941,
 21874,
 21898,
 21883,
 21893,
 21864,
 21951,
 21953,
 21944,
 21948,
 21909,
 21950,
 21911,
 21906,
 21868,
 21920,
 21912,
 21872,
 21904,
 21890,
 21922,
 21932,
 21938,
 21949,
 21879,
 21875,
 21884,
 21894,
 21866,
 21903,
 21940,
 21885,
 21928,
 21785,
 21787,
 21902,
 21924,
 23762,
 23911,
 23921,
 23907,
 23909,
 23912,
 23914,
 23915,
 23922,
 23927,
 23933,
 23923,
 23935,
 24181,
 23256,
 23586,
 23570,
 23588,
 23535,
 23575,
 23594,
 23567,
 23627,
 23843,
 23419,
 23979,
 23982,
 23984,
 24163,
 23991,
 23748,
 23020,
 24116,
 23231,
 24294,
 23411,
 24106,
 23763,
 23766,
 23978,
 24014,
 24018,
 24021,
 24028,
 24031,
 24035,
 24039,
 24041,
 24045,
 24054,
 24057,
 24059,
 24062,
 24065,
 24066,
 24079,
 24083,
 24090,
 24093,
 24095,
 24105,
 24131,
 24133,
 24134,
 24142,
 24146,
 24150,
 24151,
 24154,
 24160,
 24170,
 24179,
 24188,
 24191,
 24194,
 24210,
 24215,
 24236,
 24229,
 24246,
 24245,
 24268,
 24277,
 24276,
 24284,
 24298,
 24312,
 24713,
 24302,
 24223,
 24067,
 24218,
 24692,
 23378,
 24208,
 24241,
 23767,
 23963,
 24020,
 24239,
 24016,
 24049,
 24072,
 24101,
 24108,
 24120,
 24123,
 24128,
 24137,
 24159,
 24161,
 24166,
 24173,
 24200,
 24217,
 24248,
 24249,
 24251,
 24256,
 24258,
 24260,
 24264,
 24266,
 24270,
 24273,
 24285,
 24295,
 24297,
 24353,
 24354,
 24367,
 24369,
 24374,
 24387,
 24389,
 24391,
 24425,
 24493,
 24502,
 24528,
 24665,
 24667,
 24668,
 24681,
 24684,
 24691,
 24696,
 24730,
 24732,
 24735,
 24746,
 24752,
 24754,
 24757,
 24769,
 24772,
 24793,
 24796,
 24971,
 24976,
 25021,
 24118,
 24184,
 24414,
 24359,
 24412,
 24418,
 24969,
 24707,
 24699,
 24702,
 24088,
 24843,
 22272,
 24431,
 24781,
 24447,
 25037,
 23250,
 23361,
 23743,
 24212,
 24439,
 24441,
 24571,
 24187,
 24325,
 23987,
 24280,
 24282,
 24304,
 24308,
 24315,
 24320,
 24384,
 24393,
 24395,
 24398,
 24402,
 24404,
 24406,
 24408,
 24982,
 24979,
 24451,
 24475,
 24477,
 24481,
 24483,
 24485,
 24487,
 24509,
 24537,
 24540,
 24544,
 24552,
 24555,
 24560,
 24565,
 24575,
 24685,
 24716,
 24721,
 24724,
 24726,
 24738,
 24739,
 24741,
 24780,
 24784,
 24791,
 24806,
 24808,
 24821,
 24832,
 24836,
 24838,
 24991,
 24992,
 24999,
 25003,
 25005,
 25007,
 25012,
 25014,
 25015,
 25017,
 25019,
 25024,
 25028,
 25030,
 25031,
 25040,
 25043,
 25044,
 25045,
 25049,
 25053,
 24717,
 25055,
 24338,
 24332,
 24336,
 24350,
 24463,
 24811,
 24498,
 24823,
 24831,
 23067,
 24798,
 24443,
 24817,
 24456,
 23629,
 23541,
 23609,
 23744,
 24358,
 24371,
 24373,
 24376,
 24446,
 24455,
 24539,
 24760,
 24762,
 24825,
 24826,
 24815,
 24075,
 24671,
 24679,
 24328,
 24994,
 22262,
 22264,
 22269,
 22270,
 24471,
 24453,
 24479,
 24492,
 24970,
 24973,
 24984,
 24520,
 24516,
 24514,
 24778,
 24202,
 24474,
 24496,
 24500,
 24513,
 24518,
 24804,
 24845,
 24839,
 24524,
 22259,
 23049,
 25036,
 23580,
 24675,
 24132,
 24749,
 24386,
 24392,
 24987,
 24470,
 24503,
 24526,
 24765,
 24788,
 25047,
 25027,
 24081,
 24469,
 23838,
 24043,
 25039,
 24318,
 22267,
 23906,
 24720,
 24786,
 1560115,
 1287743,
 1287753,
 1287756,
 1287727,
 1287758,
 1287757,
 1287741,
 1287735,
 1287752,
 1287751,
 1287768,
 1287779,
 1288159,
 1288157,
 1288163,
 1288521,
 1288185,
 1288148,
 1287770,
 1288178,
 1288154,
 1288506,
 1288149,
 1288162,
 1288145,
 1288165,
 1288182,
 1288144,
 1288172,
 1316788,
 1320594,
 5079446,
 5079454,
 5078320,
 5078670,
 5079051,
 5078942,
 5078750,
 5078383,
 5078435,
 5078516,
 5078885,
 5078702,
 5078561,
 5078863,
 7775133,
 5078531,
 5078821,
 5078494,
 5078796,
 5078597,
 5078738,
 5078525,
 5078600,
 5078655,
 5079026,
 5078665,
 5078901,
 5078728,
 3139410,
 5078314,
 5078725,
 5078834,
 5078284,
 5078912,
 5078501,
 5078816,
 5079064,
 5078776,
 7775300,
 7775557,
 7775804,
 7775897,
 7775089,
 7773615,
 7775198,
 7773169,
 7775061,
 7774617,
 7774184,
 7773345,
 7774704,
 8613247,
 7773774,
 7773943,
 7775683,
 7775854,
 7774988,
 7772875,
 7774452,
 7774281,
 7773913,
 7775860,
 7775873,
 7773866,
 7774509,
 7774177,
 7774004,
 7780085,
 7772986,
 7775124,
 7774232,
 7774922,
 7772756,
 7774701,
 7772895,
 7774201,
 7774324,
 7773558,
 7775839,
 7772814,
 7775362,
 7773330,
 7775770,
 7775677,
 7773456,
 7773436,
 7774263,
 7775383,
 7775065,
 7775551,
 7773791,
 7774400,
 7773548,
 7775629,
 7774139,
 7774002,
 7773525,
 7775373,
 7773664,
 7773096,
 7774020,
 7775220,
 7772947,
 7773983,
 7772847,
 7774920,
 7775714,
 7774607,
 7773245,
 7775404,
 7775826,
 7773357,
 7775341,
 7772823,
 7773933,
 7773712,
 7773924,
 7775724,
 7774932,
 7773009,
 7773929,
 7775796,
 7772745,
 7772915,
 7775412,
 7774486,
 7775363,
 7773877,
 7774578,
 7773058,
 7774800,
 7774702,
 7772795,
 7775193,
 7775684,
 7774703,
 7774406,
 7772878,
 7774103,
 7774721,
 7773806,
 7773109,
 7773852,
 7772767,
 7773400,
 7772765,
 7774942,
 7774078,
 7775020,
 7774599,
 7773639,
 7774340,
 7774823,
 7773179,
 7774422,
 7774067,
 7775634,
 7774944,
 7775941,
 7774071,
 7775148,
 7775675,
 7772721,
 7772808,
 7775866,
 7773257,
 7775816,
 7773395,
 7775912,
 7774604,
 7773690,
 7774330,
 7773919,
 7774713,
 7780776,
 7774364,
 7775762,
 7774808,
 7773680,
 7775311,
 7772727,
 7774157,
 7772927,
 7772849,
 7773487,
 7774482,
 7773014,
 7775033,
 7775431,
 7775469,
 7775959,
 7775265,
 7772879,
 7774535,
 7774990,
 7773994,
 7773870,
 7772852,
 7774457,
 7774998,
 7775785,
 7773020,
 7774462,
 7775751,
 7774461,
 7772710,
 7774424,
 7773841,
 7774715,
 7774777,
 8622644,
 7775960,
 7775730,
 7774611,
 7775145,
 7775390,
 7775538,
 7773855,
 7775162,
 7775237,
 7774850,
 7772848,
 7773356,
 7776032,
 7773934,
 7773302,
 7773346,
 7774383,
 7774613,
 7779950,
 7798110,
 8613050,
 8613211,
 11272039,
 11710004,
 12130522,
 12130521,
 13965]

In [52]:
headers = {
    "X-API-Key": "2e4741b1051f0a4545639472115170bf828e6a8569951f0969bbb98bbdb3863d"
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 22156: Seite 1, 1000 Ergebnisse
Sensor 22156: Seite 2, 1000 Ergebnisse
Sensor 22156: Seite 3, 754 Ergebnisse
Sensor 22135: Seite 1, 1000 Ergebnisse
Sensor 22135: Seite 2, 1000 Ergebnisse
Sensor 22135: Seite 3, 641 Ergebnisse
Sensor 22075: Seite 1, 1000 Ergebnisse
Sensor 22075: Seite 2, 1000 Ergebnisse
Sensor 22075: Seite 3, 746 Ergebnisse
Sensor 22091: Seite 1, 1000 Ergebnisse
Sensor 22091: Seite 2, 1000 Ergebnisse
Sensor 22091: Seite 3, 724 Ergebnisse
Sensor 19774: Seite 1, 450 Ergebnisse
Sensor 22137: Seite 1, 824 Ergebnisse
Sensor 22194: Seite 1, 819 Ergebnisse
Sensor 22174: Seite 1, 774 Ergebnisse
Sensor 22170: Seite 1, 820 Ergebnisse
Sensor 22169: Seite 1, 827 Ergebnisse
Sensor 21742: Seite 1, 779 Ergebnisse
Sensor 22159: Seite 1, 832 Ergebnisse
Sensor 22024: Seite 1, 800 Ergebnisse
Sensor 22059: Seite 1, 762 Ergebnisse
Sensor 22183: Seite 1, 830 Ergebnisse
Sensor 22172: Seite 1, 823 Ergebnisse
Sensor 22067: Seite 1, 752 Ergebnisse
Sensor 22073: Seite 1, 821 Ergebnisse
Sensor 22080: Seite 1, 822 Ergebnisse
Sensor 22160: Seite 1, 773 Ergebnisse
Sensor 22082: Seite 1, 827 Ergebnisse
Sensor 22087: Seite 1, 752 Ergebnisse
Sensor 22098: Seite 1, 825 Ergebnisse
Sensor 22095: Seite 1, 834 Ergebnisse
Sensor 22103: Seite 1, 819 Ergebnisse
Sensor 22111: Seite 1, 835 Ergebnisse
Sensor 22191: Seite 1, 815 Ergebnisse
Sensor 22185: Seite 1, 829 Ergebnisse
Sensor 22114: Seite 1, 835 Ergebnisse
Sensor 22200: Seite 1, 829 Ergebnisse
Sensor 22121: Seite 1, 831 Ergebnisse
Sensor 22122: Seite 1, 825 Ergebnisse
Sensor 22128: Seite 1, 810 Ergebnisse
Sensor 22198: Seite 1, 834 Ergebnisse
Sensor 22167: Seite 1, 832 Ergebnisse
Sensor 22145: Seite 1, 805 Ergebnisse
Sensor 22155: Seite 1, 818 Ergebnisse
Sensor 22157: Seite 1, 827 Ergebnisse
Sensor 22184: Seite 1, 825 Ergebnisse
Sensor 20605: Seite 1, 691 Ergebnisse
Sensor 20603: Seite 1, 687 Ergebnisse
Sensor 20604: Seite 1, 692 Ergebnisse
Sensor 20597: Seite 1, 683 Ergebnisse
Sensor 22115: Seite 1, 829 Ergebnisse
Sensor 21873: Seite 1, 1000 Ergebnisse
Sensor 21873: Seite 2, 1000 Ergebnisse
Sensor 21873: Seite 3, 733 Ergebnisse
Sensor 21777: Seite 1, 1000 Ergebnisse
Sensor 21777: Seite 2, 1000 Ergebnisse
Sensor 21777: Seite 3, 213 Ergebnisse
Sensor 21781: Seite 1, 1000 Ergebnisse
Sensor 21781: Seite 2, 1000 Ergebnisse
Sensor 21781: Seite 3, 177 Ergebnisse
Sensor 21782: Seite 1, 1000 Ergebnisse
Sensor 21782: Seite 2, 1000 Ergebnisse
Sensor 21782: Seite 3, 218 Ergebnisse
Sensor 21789: Seite 1, 1000 Ergebnisse
Sensor 21789: Seite 2, 1000 Ergebnisse
Sensor 21789: Seite 3, 226 Ergebnisse
Sensor 21776: Seite 1, 1000 Ergebnisse
Sensor 21776: Seite 2, 1000 Ergebnisse
Sensor 21776: Seite 3, 122 Ergebnisse
Sensor 21780: Seite 1, 1000 Ergebnisse
Sensor 21780: Seite 2, 1000 Ergebnisse
Sensor 21780: Seite 3, 216 Ergebnisse
Sensor 21892: Seite 1, 1000 Ergebnisse
Sensor 21892: Seite 2, 1000 Ergebnisse
Sensor 21892: Seite 3, 220 Ergebnisse
Sensor 21915: Seite 1, 1000 Ergebnisse
Sensor 21915: Seite 2, 1000 Ergebnisse
Sensor 21915: Seite 3, 738 Ergebnisse
Sensor 21941: Seite 1, 1000 Ergebnisse
Sensor 21941: Seite 2, 1000 Ergebnisse
Sensor 21941: Seite 3, 219 Ergebnisse
Sensor 21874: Seite 1, 1000 Ergebnisse
Sensor 21874: Seite 2, 1000 Ergebnisse
Sensor 21874: Seite 3, 221 Ergebnisse
Sensor 21898: Seite 1, 1000 Ergebnisse
Sensor 21898: Seite 2, 1000 Ergebnisse
Sensor 21898: Seite 3, 737 Ergebnisse
Sensor 21883: Seite 1, 1000 Ergebnisse
Sensor 21883: Seite 2, 1000 Ergebnisse
Sensor 21883: Seite 3, 746 Ergebnisse
Sensor 21893: Seite 1, 1000 Ergebnisse
Sensor 21893: Seite 2, 1000 Ergebnisse
Sensor 21893: Seite 3, 207 Ergebnisse
Sensor 21864: Seite 1, 1000 Ergebnisse
Sensor 21864: Seite 2, 1000 Ergebnisse
Sensor 21864: Seite 3, 720 Ergebnisse
Sensor 21951: Seite 1, 1000 Ergebnisse
Sensor 21951: Seite 2, 1000 Ergebnisse
Sensor 21951: Seite 3, 209 Ergebnisse
Sensor 21953: Seite 1, 1000 Ergebnisse
Sensor 21953: Seite 2, 1000 Ergebnisse
Sensor 21953: Seite 3, 191 Ergebnisse
Sensor 21944: Seite 1, 1000 Ergebnisse
Sensor 21944: Seite 2, 1000 Ergebnisse
Sensor 21944: Seite 3, 739 Ergebnisse
Sensor 21948: Seite 1, 1000 Ergebnisse
Sensor 21948: Seite 2, 1000 Ergebnisse
Sensor 21948: Seite 3, 218 Ergebnisse
Sensor 21909: Seite 1, 1000 Ergebnisse
Sensor 21909: Seite 2, 1000 Ergebnisse
Sensor 21909: Seite 3, 212 Ergebnisse
Sensor 21950: Seite 1, 1000 Ergebnisse
Sensor 21950: Seite 2, 1000 Ergebnisse
Sensor 21950: Seite 3, 715 Ergebnisse
Sensor 21911: Seite 1, 1000 Ergebnisse
Sensor 21911: Seite 2, 1000 Ergebnisse
Sensor 21911: Seite 3, 192 Ergebnisse
Sensor 21906: Seite 1, 1000 Ergebnisse
Sensor 21906: Seite 2, 1000 Ergebnisse
Sensor 21906: Seite 3, 198 Ergebnisse
Sensor 21868: Seite 1, 1000 Ergebnisse
Sensor 21868: Seite 2, 1000 Ergebnisse
Sensor 21868: Seite 3, 219 Ergebnisse
Sensor 21920: Seite 1, 1000 Ergebnisse
Sensor 21920: Seite 2, 1000 Ergebnisse
Sensor 21920: Seite 3, 223 Ergebnisse
Sensor 21912: Seite 1, 1000 Ergebnisse
Sensor 21912: Seite 2, 1000 Ergebnisse
Sensor 21912: Seite 3, 183 Ergebnisse
Sensor 21872: Seite 1, 1000 Ergebnisse
Sensor 21872: Seite 2, 1000 Ergebnisse
Sensor 21872: Seite 3, 214 Ergebnisse
Sensor 21904: Seite 1, 1000 Ergebnisse
Sensor 21904: Seite 2, 1000 Ergebnisse
Sensor 21904: Seite 3, 205 Ergebnisse
Sensor 21890: Seite 1, 1000 Ergebnisse
Sensor 21890: Seite 2, 1000 Ergebnisse
Sensor 21890: Seite 3, 727 Ergebnisse
Sensor 21922: Seite 1, 1000 Ergebnisse
Sensor 21922: Seite 2, 1000 Ergebnisse
Sensor 21922: Seite 3, 736 Ergebnisse
Sensor 21932: Seite 1, 1000 Ergebnisse
Sensor 21932: Seite 2, 1000 Ergebnisse
Sensor 21932: Seite 3, 205 Ergebnisse
Sensor 21938: Seite 1, 1000 Ergebnisse
Sensor 21938: Seite 2, 1000 Ergebnisse
Sensor 21938: Seite 3, 731 Ergebnisse
Sensor 21949: Seite 1, 1000 Ergebnisse
Sensor 21949: Seite 2, 1000 Ergebnisse
Sensor 21949: Seite 3, 735 Ergebnisse
Sensor 21879: Seite 1, 1000 Ergebnisse
Sensor 21879: Seite 2, 1000 Ergebnisse
Sensor 21879: Seite 3, 720 Ergebnisse
Sensor 21875: Seite 1, 1000 Ergebnisse
Sensor 21875: Seite 2, 1000 Ergebnisse
Sensor 21875: Seite 3, 211 Ergebnisse
Sensor 21884: Seite 1, 1000 Ergebnisse
Sensor 21884: Seite 2, 1000 Ergebnisse
Sensor 21884: Seite 3, 746 Ergebnisse
Sensor 21894: Seite 1, 1000 Ergebnisse
Sensor 21894: Seite 2, 1000 Ergebnisse
Sensor 21894: Seite 3, 213 Ergebnisse
Sensor 21866: Seite 1, 1000 Ergebnisse
Sensor 21866: Seite 2, 1000 Ergebnisse
Sensor 21866: Seite 3, 747 Ergebnisse
Sensor 21903: Seite 1, 1000 Ergebnisse
Sensor 21903: Seite 2, 1000 Ergebnisse
Sensor 21903: Seite 3, 213 Ergebnisse
Sensor 21940: Seite 1, 1000 Ergebnisse
Sensor 21940: Seite 2, 1000 Ergebnisse
Sensor 21940: Seite 3, 202 Ergebnisse
Sensor 21885: Seite 1, 1000 Ergebnisse
Sensor 21885: Seite 2, 1000 Ergebnisse
Sensor 21885: Seite 3, 219 Ergebnisse
Sensor 21928: Seite 1, 1000 Ergebnisse
Sensor 21928: Seite 2, 1000 Ergebnisse
Sensor 21928: Seite 3, 712 Ergebnisse
Sensor 21785: Seite 1, 1000 Ergebnisse
Sensor 21785: Seite 2, 656 Ergebnisse
Sensor 21787: Seite 1, 845 Ergebnisse
Sensor 21902: Seite 1, 1000 Ergebnisse
Sensor 21902: Seite 2, 1000 Ergebnisse
Sensor 21902: Seite 3, 217 Ergebnisse
Sensor 21924: Seite 1, 1000 Ergebnisse
Sensor 21924: Seite 2, 1000 Ergebnisse
Sensor 21924: Seite 3, 734 Ergebnisse
Sensor 23762: Seite 1, 1000 Ergebnisse
Sensor 23762: Seite 2, 293 Ergebnisse
Sensor 23911: Seite 1, 1000 Ergebnisse
Sensor 23911: Seite 2, 888 Ergebnisse
Sensor 23921: Seite 1, 1000 Ergebnisse
Sensor 23921: Seite 2, 894 Ergebnisse
Sensor 23907: Seite 1, 1000 Ergebnisse
Sensor 23907: Seite 2, 910 Ergebnisse
Sensor 23909: Seite 1, 1000 Ergebnisse
Sensor 23909: Seite 2, 910 Ergebnisse
Sensor 23912: Seite 1, 1000 Ergebnisse
Sensor 23912: Seite 2, 912 Ergebnisse
Sensor 23914: Seite 1, 1000 Ergebnisse
Sensor 23914: Seite 2, 900 Ergebnisse
Sensor 23915: Seite 1, 1000 Ergebnisse
Sensor 23915: Seite 2, 893 Ergebnisse
Sensor 23922: Seite 1, 1000 Ergebnisse
Sensor 23922: Seite 2, 822 Ergebnisse
Sensor 23927: Seite 1, 1000 Ergebnisse
Sensor 23927: Seite 2, 920 Ergebnisse
Sensor 23933: Seite 1, 1000 Ergebnisse
Sensor 23933: Seite 2, 880 Ergebnisse
Sensor 23923: Seite 1, 1000 Ergebnisse
Sensor 23923: Seite 2, 845 Ergebnisse
Sensor 23935: Seite 1, 1000 Ergebnisse
Sensor 23935: Seite 2, 215 Ergebnisse
Sensor 24181: Seite 1, 1000 Ergebnisse
Sensor 24181: Seite 2, 19 Ergebnisse
Sensor 23256: Seite 1, 1000 Ergebnisse
Sensor 23256: Seite 2, 642 Ergebnisse
Sensor 23586: Seite 1, 1000 Ergebnisse
Sensor 23586: Seite 2, 639 Ergebnisse
Sensor 23570: Seite 1, 1000 Ergebnisse
Sensor 23570: Seite 2, 620 Ergebnisse
Sensor 23588: Seite 1, 1000 Ergebnisse
Sensor 23588: Seite 2, 642 Ergebnisse
Sensor 23535: Seite 1, 1000 Ergebnisse
Sensor 23535: Seite 2, 629 Ergebnisse
Sensor 23575: Seite 1, 1000 Ergebnisse
Sensor 23575: Seite 2, 654 Ergebnisse
Sensor 23594: Seite 1, 1000 Ergebnisse
Sensor 23594: Seite 2, 644 Ergebnisse
Sensor 23567: Seite 1, 1000 Ergebnisse
Sensor 23567: Seite 2, 627 Ergebnisse
Sensor 23627: Seite 1, 1000 Ergebnisse
Sensor 23627: Seite 2, 637 Ergebnisse
Sensor 23843: Seite 1, 1000 Ergebnisse
Sensor 23843: Seite 2, 819 Ergebnisse
Sensor 23419: Seite 1, 1000 Ergebnisse
Sensor 23419: Seite 2, 37 Ergebnisse
Sensor 23979: Seite 1, 1000 Ergebnisse
Sensor 23979: Seite 2, 905 Ergebnisse
Sensor 23982: Seite 1, 1000 Ergebnisse
Sensor 23982: Seite 2, 909 Ergebnisse
Sensor 23984: Seite 1, 1000 Ergebnisse
Sensor 23984: Seite 2, 820 Ergebnisse
Sensor 24163: Seite 1, 1000 Ergebnisse
Sensor 24163: Seite 2, 940 Ergebnisse
Sensor 23991: Seite 1, 1000 Ergebnisse
Sensor 23991: Seite 2, 720 Ergebnisse
Sensor 23748: Seite 1, 727 Ergebnisse
Sensor 23020: Seite 1, 934 Ergebnisse
Sensor 24116: Seite 1, 1000 Ergebnisse
Sensor 24116: Seite 2, 894 Ergebnisse
Sensor 23231: Seite 1, 1000 Ergebnisse
Sensor 23231: Seite 2, 296 Ergebnisse
Sensor 24294: Seite 1, 1000 Ergebnisse
Sensor 24294: Seite 2, 81 Ergebnisse
Sensor 23411: Seite 1, 1000 Ergebnisse
Sensor 23411: Seite 2, 97 Ergebnisse
Sensor 24106: Seite 1, 1000 Ergebnisse
Sensor 24106: Seite 2, 320 Ergebnisse
Sensor 23763: Seite 1, 1000 Ergebnisse
Sensor 23763: Seite 2, 865 Ergebnisse
Sensor 23766: Seite 1, 1000 Ergebnisse
Sensor 23766: Seite 2, 306 Ergebnisse
Sensor 23978: Seite 1, 1000 Ergebnisse
Sensor 23978: Seite 2, 902 Ergebnisse
Sensor 24014: Seite 1, 1000 Ergebnisse
Sensor 24014: Seite 2, 914 Ergebnisse
Sensor 24018: Seite 1, 1000 Ergebnisse
Sensor 24018: Seite 2, 291 Ergebnisse
Sensor 24021: Seite 1, 1000 Ergebnisse
Sensor 24021: Seite 2, 283 Ergebnisse
Sensor 24028: Seite 1, 1000 Ergebnisse
Sensor 24028: Seite 2, 20 Ergebnisse
Sensor 24031: Seite 1, 1000 Ergebnisse
Sensor 24031: Seite 2, 661 Ergebnisse
Sensor 24035: Seite 1, 1000 Ergebnisse
Sensor 24035: Seite 2, 908 Ergebnisse
Sensor 24039: Seite 1, 1000 Ergebnisse
Sensor 24039: Seite 2, 898 Ergebnisse
Sensor 24041: Seite 1, 1000 Ergebnisse
Sensor 24041: Seite 2, 867 Ergebnisse
Sensor 24045: Seite 1, 1000 Ergebnisse
Sensor 24045: Seite 2, 696 Ergebnisse
Sensor 24054: Seite 1, 1000 Ergebnisse
Sensor 24054: Seite 2, 910 Ergebnisse
Sensor 24057: Seite 1, 1000 Ergebnisse
Sensor 24057: Seite 2, 847 Ergebnisse
Sensor 24059: Seite 1, 1000 Ergebnisse
Sensor 24059: Seite 2, 832 Ergebnisse
Sensor 24062: Seite 1, 1000 Ergebnisse
Sensor 24062: Seite 2, 910 Ergebnisse
Sensor 24065: Seite 1, 1000 Ergebnisse
Sensor 24065: Seite 2, 915 Ergebnisse
Sensor 24066: Seite 1, 1000 Ergebnisse
Sensor 24066: Seite 2, 928 Ergebnisse
Sensor 24079: Seite 1, 1000 Ergebnisse
Sensor 24079: Seite 2, 899 Ergebnisse
Sensor 24083: Seite 1, 1000 Ergebnisse
Sensor 24083: Seite 2, 277 Ergebnisse
Sensor 24090: Seite 1, 1000 Ergebnisse
Sensor 24090: Seite 2, 277 Ergebnisse
Sensor 24093: Seite 1, 1000 Ergebnisse
Sensor 24093: Seite 2, 307 Ergebnisse
Sensor 24095: Seite 1, 1000 Ergebnisse
Sensor 24095: Seite 2, 312 Ergebnisse
Sensor 24105: Seite 1, 1000 Ergebnisse
Sensor 24105: Seite 2, 321 Ergebnisse
Sensor 24131: Seite 1, 1000 Ergebnisse
Sensor 24131: Seite 2, 842 Ergebnisse
Sensor 24133: Seite 1, 1000 Ergebnisse
Sensor 24133: Seite 2, 914 Ergebnisse
Sensor 24134: Seite 1, 1000 Ergebnisse
Sensor 24134: Seite 2, 924 Ergebnisse
Sensor 24142: Seite 1, 1000 Ergebnisse
Sensor 24142: Seite 2, 882 Ergebnisse
Sensor 24146: Seite 1, 1000 Ergebnisse
Sensor 24146: Seite 2, 928 Ergebnisse
Sensor 24150: Seite 1, 1000 Ergebnisse
Sensor 24150: Seite 2, 910 Ergebnisse
Sensor 24151: Seite 1, 1000 Ergebnisse
Sensor 24151: Seite 2, 924 Ergebnisse
Sensor 24154: Seite 1, 1000 Ergebnisse
Sensor 24154: Seite 2, 887 Ergebnisse
Sensor 24160: Seite 1, 1000 Ergebnisse
Sensor 24160: Seite 2, 910 Ergebnisse
Sensor 24170: Seite 1, 1000 Ergebnisse
Sensor 24170: Seite 2, 921 Ergebnisse
Sensor 24179: Seite 1, 1000 Ergebnisse
Sensor 24179: Seite 2, 922 Ergebnisse
Sensor 24188: Seite 1, 1000 Ergebnisse
Sensor 24188: Seite 2, 917 Ergebnisse
Sensor 24191: Seite 1, 1000 Ergebnisse
Sensor 24191: Seite 2, 889 Ergebnisse
Sensor 24194: Seite 1, 1000 Ergebnisse
Sensor 24194: Seite 2, 924 Ergebnisse
Sensor 24210: Seite 1, 1000 Ergebnisse
Sensor 24210: Seite 2, 5 Ergebnisse
Sensor 24215: Seite 1, 1000 Ergebnisse
Sensor 24215: Seite 2, 829 Ergebnisse
Sensor 24236: Seite 1, 1000 Ergebnisse
Sensor 24236: Seite 2, 316 Ergebnisse
Sensor 24229: Seite 1, 1000 Ergebnisse
Sensor 24229: Seite 2, 914 Ergebnisse
Sensor 24246: Seite 1, 1000 Ergebnisse
Sensor 24246: Seite 2, 904 Ergebnisse
Sensor 24245: Seite 1, 1000 Ergebnisse
Sensor 24245: Seite 2, 318 Ergebnisse
Sensor 24268: Seite 1, 1000 Ergebnisse
Sensor 24268: Seite 2, 917 Ergebnisse
Sensor 24277: Seite 1, 1000 Ergebnisse
Sensor 24277: Seite 2, 826 Ergebnisse
Sensor 24276: Seite 1, 1000 Ergebnisse
Sensor 24276: Seite 2, 877 Ergebnisse
Sensor 24284: Seite 1, 1000 Ergebnisse
Sensor 24284: Seite 2, 301 Ergebnisse
Sensor 24298: Seite 1, 1000 Ergebnisse
Sensor 24298: Seite 2, 316 Ergebnisse
Sensor 24312: Seite 1, 1000 Ergebnisse
Sensor 24312: Seite 2, 293 Ergebnisse
Sensor 24713: Seite 1, 1000 Ergebnisse
Sensor 24713: Seite 2, 920 Ergebnisse
Sensor 24302: Seite 1, 1000 Ergebnisse
Sensor 24302: Seite 2, 298 Ergebnisse
Sensor 24223: Seite 1, 635 Ergebnisse
Sensor 24067: Seite 1, 1000 Ergebnisse
Sensor 24067: Seite 2, 312 Ergebnisse
Sensor 24218: Seite 1, 1000 Ergebnisse
Sensor 24218: Seite 2, 295 Ergebnisse
Sensor 24692: Seite 1, 1000 Ergebnisse
Sensor 24692: Seite 2, 921 Ergebnisse
Sensor 23378: Seite 1, 1000 Ergebnisse
Sensor 23378: Seite 2, 794 Ergebnisse
Sensor 24208: Seite 1, 1000 Ergebnisse
Sensor 24208: Seite 2, 322 Ergebnisse
Sensor 24241: Seite 1, 1000 Ergebnisse
Sensor 24241: Seite 2, 326 Ergebnisse
Sensor 23767: Seite 1, 1000 Ergebnisse
Sensor 23767: Seite 2, 300 Ergebnisse
Sensor 23963: Seite 1, 1000 Ergebnisse
Sensor 23963: Seite 2, 894 Ergebnisse
Sensor 24020: Seite 1, 1000 Ergebnisse
Sensor 24020: Seite 2, 327 Ergebnisse
Sensor 24239: Seite 1, 1000 Ergebnisse
Sensor 24239: Seite 2, 317 Ergebnisse
Sensor 24016: Seite 1, 1000 Ergebnisse
Sensor 24016: Seite 2, 308 Ergebnisse
Sensor 24049: Seite 1, 1000 Ergebnisse
Sensor 24049: Seite 2, 324 Ergebnisse
Sensor 24072: Seite 1, 1000 Ergebnisse
Sensor 24072: Seite 2, 308 Ergebnisse
Sensor 24101: Seite 1, 1000 Ergebnisse
Sensor 24101: Seite 2, 328 Ergebnisse
Sensor 24108: Seite 1, 1000 Ergebnisse
Sensor 24108: Seite 2, 315 Ergebnisse
Sensor 24120: Seite 1, 1000 Ergebnisse
Sensor 24120: Seite 2, 323 Ergebnisse
Sensor 24123: Seite 1, 1000 Ergebnisse
Sensor 24123: Seite 2, 317 Ergebnisse
Sensor 24128: Seite 1, 1000 Ergebnisse
Sensor 24128: Seite 2, 327 Ergebnisse
Sensor 24137: Seite 1, 1000 Ergebnisse
Sensor 24137: Seite 2, 329 Ergebnisse
Sensor 24159: Seite 1, 1000 Ergebnisse
Sensor 24159: Seite 2, 262 Ergebnisse
Sensor 24161: Seite 1, 1000 Ergebnisse
Sensor 24161: Seite 2, 302 Ergebnisse
Sensor 24166: Seite 1, 1000 Ergebnisse
Sensor 24166: Seite 2, 330 Ergebnisse
Sensor 24173: Seite 1, 1000 Ergebnisse
Sensor 24173: Seite 2, 239 Ergebnisse
Sensor 24200: Seite 1, 1000 Ergebnisse
Sensor 24200: Seite 2, 274 Ergebnisse
Sensor 24217: Seite 1, 1000 Ergebnisse
Sensor 24217: Seite 2, 298 Ergebnisse
Sensor 24248: Seite 1, 1000 Ergebnisse
Sensor 24248: Seite 2, 314 Ergebnisse
Sensor 24249: Seite 1, 1000 Ergebnisse
Sensor 24249: Seite 2, 321 Ergebnisse
Sensor 24251: Seite 1, 1000 Ergebnisse
Sensor 24251: Seite 2, 312 Ergebnisse
Sensor 24256: Seite 1, 1000 Ergebnisse
Sensor 24256: Seite 2, 331 Ergebnisse
Sensor 24258: Seite 1, 1000 Ergebnisse
Sensor 24258: Seite 2, 325 Ergebnisse
Sensor 24260: Seite 1, 1000 Ergebnisse
Sensor 24260: Seite 2, 317 Ergebnisse
Sensor 24264: Seite 1, 1000 Ergebnisse
Sensor 24264: Seite 2, 310 Ergebnisse
Sensor 24266: Seite 1, 1000 Ergebnisse
Sensor 24266: Seite 2, 283 Ergebnisse
Sensor 24270: Seite 1, 1000 Ergebnisse
Sensor 24270: Seite 2, 320 Ergebnisse
Sensor 24273: Seite 1, 1000 Ergebnisse
Sensor 24273: Seite 2, 313 Ergebnisse
Sensor 24285: Seite 1, 1000 Ergebnisse
Sensor 24285: Seite 2, 318 Ergebnisse
Sensor 24295: Seite 1, 1000 Ergebnisse
Sensor 24295: Seite 2, 323 Ergebnisse
Sensor 24297: Seite 1, 1000 Ergebnisse
Sensor 24297: Seite 2, 324 Ergebnisse
Sensor 24353: Seite 1, 1000 Ergebnisse
Sensor 24353: Seite 2, 801 Ergebnisse
Sensor 24354: Seite 1, 1000 Ergebnisse
Sensor 24354: Seite 2, 827 Ergebnisse
Sensor 24367: Seite 1, 1000 Ergebnisse
Sensor 24367: Seite 2, 840 Ergebnisse
Sensor 24369: Seite 1, 1000 Ergebnisse
Sensor 24369: Seite 2, 800 Ergebnisse
Sensor 24374: Seite 1, 1000 Ergebnisse
Sensor 24374: Seite 2, 888 Ergebnisse
Sensor 24387: Seite 1, 1000 Ergebnisse
Sensor 24387: Seite 2, 913 Ergebnisse
Sensor 24389: Seite 1, 1000 Ergebnisse
Sensor 24389: Seite 2, 917 Ergebnisse
Sensor 24391: Seite 1, 1000 Ergebnisse
Sensor 24391: Seite 2, 914 Ergebnisse
Sensor 24425: Seite 1, 1000 Ergebnisse
Sensor 24425: Seite 2, 754 Ergebnisse
Sensor 24493: Seite 1, 1000 Ergebnisse
Sensor 24493: Seite 2, 898 Ergebnisse
Sensor 24502: Seite 1, 1000 Ergebnisse
Sensor 24502: Seite 2, 835 Ergebnisse
Sensor 24528: Seite 1, 1000 Ergebnisse
Sensor 24528: Seite 2, 926 Ergebnisse
Sensor 24665: Seite 1, 1000 Ergebnisse
Sensor 24665: Seite 2, 909 Ergebnisse
Sensor 24667: Seite 1, 1000 Ergebnisse
Sensor 24667: Seite 2, 908 Ergebnisse
Sensor 24668: Seite 1, 1000 Ergebnisse
Sensor 24668: Seite 2, 923 Ergebnisse
Sensor 24681: Seite 1, 1000 Ergebnisse
Sensor 24681: Seite 2, 867 Ergebnisse
Sensor 24684: Seite 1, 1000 Ergebnisse
Sensor 24684: Seite 2, 917 Ergebnisse
Sensor 24691: Seite 1, 1000 Ergebnisse
Sensor 24691: Seite 2, 921 Ergebnisse
Sensor 24696: Seite 1, 1000 Ergebnisse
Sensor 24696: Seite 2, 808 Ergebnisse
Sensor 24730: Seite 1, 967 Ergebnisse
Sensor 24732: Seite 1, 1000 Ergebnisse
Sensor 24732: Seite 2, 74 Ergebnisse
Sensor 24735: Seite 1, 1000 Ergebnisse
Sensor 24735: Seite 2, 72 Ergebnisse
Sensor 24746: Seite 1, 1000 Ergebnisse
Sensor 24746: Seite 2, 67 Ergebnisse
Sensor 24752: Seite 1, 1000 Ergebnisse
Sensor 24752: Seite 2, 31 Ergebnisse
Sensor 24754: Seite 1, 1000 Ergebnisse
Sensor 24754: Seite 2, 43 Ergebnisse
Sensor 24757: Seite 1, 1000 Ergebnisse
Sensor 24757: Seite 2, 29 Ergebnisse
Sensor 24769: Seite 1, 1000 Ergebnisse
Sensor 24769: Seite 2, 895 Ergebnisse
Sensor 24772: Seite 1, 1000 Ergebnisse
Sensor 24772: Seite 2, 66 Ergebnisse
Sensor 24793: Seite 1, 1000 Ergebnisse
Sensor 24793: Seite 2, 823 Ergebnisse
Sensor 24796: Seite 1, 1000 Ergebnisse
Sensor 24796: Seite 2, 66 Ergebnisse
Sensor 24971: Seite 1, 1000 Ergebnisse
Sensor 24971: Seite 2, 745 Ergebnisse
Sensor 24976: Seite 1, 1000 Ergebnisse
Sensor 24976: Seite 2, 759 Ergebnisse
Sensor 25021: Seite 1, 1000 Ergebnisse
Sensor 25021: Seite 2, 828 Ergebnisse
Sensor 24118: Seite 1, 1000 Ergebnisse
Sensor 24118: Seite 2, 320 Ergebnisse
Sensor 24184: Seite 1, 1000 Ergebnisse
Sensor 24184: Seite 2, 276 Ergebnisse
Sensor 24414: Seite 1, 1000 Ergebnisse
Sensor 24414: Seite 2, 62 Ergebnisse
Sensor 24359: Seite 1, 1000 Ergebnisse
Sensor 24359: Seite 2, 125 Ergebnisse
Sensor 24412: Seite 1, 1000 Ergebnisse
Sensor 24412: Seite 2, 71 Ergebnisse
Sensor 24418: Seite 1, 1000 Ergebnisse
Sensor 24418: Seite 2, 67 Ergebnisse
Sensor 24969: Seite 1, 1000 Ergebnisse
Sensor 24969: Seite 2, 57 Ergebnisse

[{'date': '2017-11-01', 'value': 69.0},
 {'date': '2017-11-02', 'value': 59.0},
 {'date': '2017-11-05', 'value': 20.0},
 {'date': '2017-11-06', 'value': 10.0},
 {'date': '2017-11-07', 'value': 29.0},
 {'date': '2017-11-08', 'value': 61.0},
 {'date': '2017-11-09', 'value': 51.0},
 {'date': '2017-11-13', 'value': 36.0},
 {'date': '2017-11-14', 'value': 49.0},
 {'date': '2017-11-15', 'value': 42.0},
 {'date': '2017-11-16', 'value': 62.0},
 {'date': '2017-11-20', 'value': 46.0},
 {'date': '2017-11-21', 'value': 63.0},
 {'date': '2017-11-22', 'value': 62.0},
 {'date': '2017-11-23', 'value': 60.0},
 {'date': '2017-11-27', 'value': 67.0},
 {'date': '2017-11-28', 'value': 61.0},
 {'date': '2017-11-29', 'value': 47.0},
 {'date': '2017-11-30', 'value': 66.0},
 {'date': '2017-12-03', 'value': 75.0},
 {'date': '2017-12-04', 'value': 67.0},
 {'date': '2017-12-06', 'value': 71.0},
 {'date': '2017-12-10', 'value': 31.0},
 {'date': '2017-12-12', 'value': 43.0},
 {'date': '2017-12-13', 'value': 39.0},
 {'date': '2017-12-14', 'value': 49.0},
 {'date': '2017-12-17', 'value': 58.0},
 {'date': '2017-12-20', 'value': 64.0},
 {'date': '2017-12-21', 'value': 84.0},
 {'date': '2017-12-23', 'value': 90.0},
 {'date': '2017-12-26', 'value': 34.0},
 {'date': '2017-12-27', 'value': 32.0},
 {'date': '2017-12-28', 'value': 34.0},
 {'date': '2018-01-01', 'value': 36.65217391304348},
 {'date': '2018-01-02', 'value': 44.34782608695652},
 {'date': '2018-01-03', 'value': 56.869565217391305},
 {'date': '2018-01-04', 'value': 54.04347826086956},
 {'date': '2018-01-07', 'value': 33.56521739130435},
 {'date': '2018-01-08', 'value': 30.40909090909091},
 {'date': '2018-01-09', 'value': 40.47826086956522},
 {'date': '2018-01-10', 'value': 61.52173913043478},
 {'date': '2018-01-14', 'value': 40.78260869565217},
 {'date': '2018-01-15', 'value': 43.69565217391305},
 {'date': '2018-01-16', 'value': 48.95652173913044},
 {'date': '2018-01-17', 'value': 44.56521739130435},
 {'date': '2018-01-21', 'value': 59.0},
 {'date': '2018-01-22', 'value': 56.0},
 {'date': '2018-01-23', 'value': 44.0},
 {'date': '2018-01-24', 'value': 57.0},
 {'date': '2018-01-25', 'value': 55.0},
 {'date': '2018-01-28', 'value': 56.0},
 {'date': '2018-01-29', 'value': 44.130434782608695},
 {'date': '2018-01-30', 'value': 46.54545454545455},
 {'date': '2018-01-31', 'value': 42.69565217391305},
 {'date': '2018-02-01', 'value': 35.04347826086956},
 {'date': '2018-02-02', 'value': 44.73913043478261},
 {'date': '2018-02-03', 'value': 34.65217391304348},
 {'date': '2018-02-04', 'value': 46.47826086956522},
 {'date': '2018-02-05', 'value': 39.08695652173913},
 {'date': '2018-02-06', 'value': 38.130434782608695},
 {'date': '2018-02-07', 'value': 46.21739130434783},
 {'date': '2018-02-08', 'value': 57.65217391304348},
 {'date': '2018-02-09', 'value': 62.78260869565217},
 {'date': '2018-02-10', 'value': 49.26086956521739},
 {'date': '2018-02-11', 'value': 37.56521739130435},
 {'date': '2018-02-12', 'value': 43.52173913043478},
 {'date': '2018-02-14', 'value': 71.47826086956522},
 {'date': '2018-02-16', 'value': 70.73913043478261},
 {'date': '2018-02-17', 'value': 64.0},
 {'date': '2018-02-18', 'value': 30.454545454545453},
 {'date': '2018-02-19', 'value': 38.21739130434783},
 {'date': '2018-02-22', 'value': 28.391304347826086},
 {'date': '2018-02-23', 'value': 33.5},
 {'date': '2018-02-26', 'value': 23.347826086956523},
 {'date': '2018-03-01', 'value': 40.869565217391305},
 {'date': '2018-03-02', 'value': 62.08695652173913},
 {'date': '2018-03-03', 'value': 61.17391304347826},
 {'date': '2018-03-04', 'value': 44.4},
 {'date': '2018-03-06', 'value': 67.26086956521739},
 {'date': '2018-03-07', 'value': 52.76470588235294},
 {'date': '2018-03-08', 'value': 53.43478260869565},
 {'date': '2018-03-09', 'value': 52.17391304347826},
 {'date': '2018-03-10', 'value': 48.21739130434783},
 {'date': '2018-03-11', 'value': 29.347826086956523},
 {'date': '2018-03-12', 'value': 43.30434782608695},
 {'date': '2018-03-13', 'value': 48.56521739130435},
 {'date': '2018-03-14', 'value': 43.91304347826087},
 {'date': '2018-03-15', 'value': 37.17391304347826},
 {'date': '2018-03-19', 'value': 8.0},
 {'date': '2018-03-20', 'value': 39.36363636363637},
 {'date': '2018-03-21', 'value': 32.52173913043478},
 {'date': '2018-03-22', 'value': 48.43478260869565},
 {'date': '2018-03-26', 'value': 61.81818181818182},
 {'date': '2018-03-27', 'value': 41.52173913043478},
 {'date': '2018-03-28', 'value': 38.47826086956522},
 {'date': '2018-03-29', 'value': 35.08695652173913},
 {'date': '2018-03-30', 'value': 23.0},
 {'date': '2018-03-31', 'value': 28.695652173913043},
 {'date': '2018-04-01', 'value': 22.47826086956522},
 {'date': '2018-04-02', 'value': 26.17391304347826},
 {'date': '2018-04-03', 'value': 33.869565217391305},
 {'date': '2018-04-04', 'value': 31.52173913043478},
 {'date': '2018-04-05', 'value': 13.0},
 {'date': '2018-04-06', 'value': 44.81818181818182},
 {'date': '2018-04-07', 'value': 36.21739130434783},
 {'date': '2018-04-08', 'value': 23.347826086956523},
 {'date': '2018-04-09', 'value': 19.0},
 {'date': '2018-04-10', 'value': 36.59090909090909},
 {'date': '2018-04-11', 'value': 36.78260869565217},
 {'date': '2018-04-12', 'value': 33.95652173913044},
 {'date': '2018-04-13', 'value': 37.43478260869565},
 {'date': '2018-04-14', 'value': 41.91304347826087},
 {'date': '2018-04-15', 'value': 32.17391304347826},
 {'date': '2018-04-16', 'value': 24.0},
 {'date': '2018-04-17', 'value': 33.59090909090909},
 {'date': '2018-04-18', 'value': 59.0},
 {'date': '2018-04-19', 'value': 50.38095238095238},
 {'date': '2018-04-20', 'value': 41.0},
 {'date': '2018-04-21', 'value': 44.391304347826086},
 {'date': '2018-04-22', 'value': 21.91304347826087},
 {'date': '2018-04-23', 'value': 25.565217391304348},
 {'date': '2018-04-24', 'value': 28.608695652173914},
 {'date': '2018-04-25', 'value': 23.73913043478261},
 {'date': '2018-04-26', 'value': 32.85},
 {'date': '2018-04-27', 'value': 10.0},
 {'date': '2018-04-29', 'value': 15.608695652173912},
 {'date': '2018-04-30', 'value': 27.0},
 {'date': '2018-05-01', 'value': 19.652173913043477},
 {'date': '2018-05-02', 'value': 32.76190476190476},
 {'date': '2018-05-03', 'value': 39.391304347826086},
 {'date': '2018-05-04', 'value': 14.0},
 {'date': '2018-05-05', 'value': 39.56521739130435},
 {'date': '2018-05-06', 'value': 36.82608695652174},
 {'date': '2018-05-07', 'value': 38.38095238095238},
 {'date': '2018-05-08', 'value': 38.869565217391305},
 {'date': '2018-05-09', 'value': 36.391304347826086},
 {'date': '2018-05-10', 'value': 38.130434782608695},
 {'date': '2018-05-11', 'value': 41.130434782608695},
 {'date': '2018-05-12', 'value': 32.08695652173913},
 {'date': '2018-05-13', 'value': 21.73913043478261},
 {'date': '2018-05-14', 'value': 32.91304347826087},
 {'date': '2018-05-15', 'value': 17.0},
 {'date': '2018-05-16', 'value': 33.0},
 {'date': '2018-05-17', 'value': 38.608695652173914},
 {'date': '2018-05-18', 'value': 36.0},
 {'date': '2018-05-24', 'value': 41.27272727272727},
 {'date': '2018-05-25', 'value': 39.65217391304348},
 {'date': '2018-05-26', 'value': 26.217391304347824},
 {'date': '2018-05-27', 'value': 24.217391304347824},
 {'date': '2018-05-28', 'value': 31.869565217391305},
 {'date': '2018-05-29', 'value': 32.65217391304348},
 {'date': '2018-05-30', 'value': 31.26086956521739},
 {'date': '2018-05-31', 'value': 20.0},
 {'date': '2018-06-01', 'value': 41.81818181818182},
 {'date': '2018-06-02', 'value': 23.391304347826086},
 {'date': '2018-06-03', 'value': 21.08695652173913},
 {'date': '2018-06-04', 'value': 18.0},
 {'date': '2018-06-05', 'value': 29.90909090909091},
 {'date': '2018-06-06', 'value': 32.21739130434783},
 {'date': '2018-06-07', 'value': 30.782608695652176},
 {'date': '2018-06-08', 'value': 30.73913043478261},
 {'date': '2018-06-09', 'value': 28.91304347826087},
 {'date': '2018-06-10', 'value': 18.043478260869566},
 {'date': '2018-06-11', 'value': 19.0},
 {'date': '2018-06-12', 'value': 33.77272727272727},
 {'date': '2018-06-13', 'value': 35.21739130434783},
 {'date': '2018-06-14', 'value': 27.608695652173914},
 {'date': '2018-06-15', 'value': 27.26086956521739},
 {'date': '2018-06-16', 'value': 30.17391304347826},
 {'date': '2018-06-17', 'value': 37.0},
 {'date': '2018-06-18', 'value': 38.142857142857146},
 {'date': '2018-06-19', 'value': 35.65217391304348},
 {'date': '2018-06-20', 'value': 36.78260869565217},
 {'date': '2018-06-21', 'value': 34.43478260869565},
 {'date': '2018-06-22', 'value': 24.91304347826087},
 {'date': '2018-06-23', 'value': 17.26086956521739},
 {'date': '2018-06-24', 'value': 15.826086956521738},
 {'date': '2018-06-25', 'value': 22.652173913043477},
 {'date': '2018-06-26', 'value': 25.82608695652174},
 {'date': '2018-06-27', 'value': 37.56521739130435},
 {'date': '2018-06-28', 'value': 32.869565217391305},
 {'date': '2018-06-29', 'value': 45.0},
 {'date': '2018-06-30', 'value': 34.65217391304348},
 {'date': '2018-07-01', 'value': 13.608695652173912},
 {'date': '2018-07-02', 'value': 21.652173913043477},
 {'date': '2018-07-03', 'value': 23.869565217391305},
 {'date': '2018-07-04', 'value': 29.82608695652174},
 {'date': '2018-07-05', 'value': 34.82608695652174},
 {'date': '2018-07-06', 'value': 33.0},
 {'date': '2018-07-07', 'value': 23.217391304347824},
 {'date': '2018-07-08', 'value': 12.75},
 {'date': '2018-07-09', 'value': 25.217391304347824},
 {'date': '2018-07-10', 'value': 28.608695652173914},
 {'date': '2018-07-11', 'value': 24.73913043478261},
 {'date': '2018-07-12', 'value': 25.608695652173914},
 {'date': '2018-07-13', 'value': 29.82608695652174},
 {'date': '2018-07-14', 'value': 22.17391304347826},
 {'date': '2018-07-15', 'value': 17.652173913043477},
 {'date': '2018-07-16', 'value': 26.0},
 {'date': '2018-07-17', 'value': 16.5},
 {'date': '2018-07-18', 'value': 47.294117647058826},
 {'date': '2018-07-19', 'value': 42.583333333333336},
 {'date': '2018-07-20', 'value': 37.25},
 {'date': '2018-07-21', 'value': 23.541666666666668},
 {'date': '2018-07-22', 'value': 20.375},
 {'date': '2018-07-23', 'value': 29.833333333333332},
 {'date': '2018-07-24', 'value': 33.166666666666664},
 {'date': '2018-07-25', 'value': 39.5},
 {'date': '2018-07-26', 'value': 36.333333333333336},
 {'date': '2018-07-27', 'value': 33.608695652173914},
 {'date': '2018-07-28', 'value': 27.5},
 {'date': '2018-07-29', 'value': 20.666666666666668},
 {'date': '2018-07-30', 'value': 36.916666666666664},
 {'date': '2018-07-31', 'value': 40.791666666666664},
 {'date': '2018-08-01', 'value': 37.041666666666664},
 {'date': '2018-08-02', 'value': 30.583333333333332},
 {'date': '2018-08-03', 'value': 30.59090909090909},
 {'date': '2018-08-04', 'value': 30.666666666666668},
 {'date': '2018-08-05', 'value': 23.375},
 {'date': '2018-08-06', 'value': 27.666666666666668},
 {'date': '2018-08-07', 'value': 19.0},
 {'date': '2018-08-08', 'value': 29.91304347826087},
 {'date': '2018-08-09', 'value': 27.166666666666668},
 {'date': '2018-08-10', 'value': 29.541666666666668},
 {'date': '2018-08-11', 'value': 25.416666666666668},
 {'date': '2018-08-12', 'value': 13.958333333333334},
 {'date': '2018-08-13', 'value': 23.916666666666668},
 {'date': '2018-08-14', 'value': 24.333333333333332},
 {'date': '2018-08-15', 'value': 17.583333333333332},
 {'date': '2018-08-16', 'value': 25.0},
 {'date': '2018-08-17', 'value': 31.5},
 {'date': '2018-08-18', 'value': 27.0},
 {'date': '2018-08-19', 'value': 26.0},
 {'date': '2018-08-20', 'value': 37.0},
 {'date': '2018-08-21', 'value': 46.0},
 {'date': '2018-08-23', 'value': 35.69565217391305},
 {'date': '2018-08-24', 'value': 32.041666666666664},
 {'date': '2018-08-25', 'value': 19.125},
 {'date': '2018-08-26', 'value': 17.041666666666668},
 {'date': '2018-08-27', 'value': 34.916666666666664},
 {'date': '2018-08-28', 'value': 39.583333333333336},
 {'date': '2018-08-29', 'value': 37.416666666666664},
 {'date': '2018-08-30', 'value': 28.791666666666668},
 {'date': '2018-08-31', 'value': 24.416666666666668},
 {'date': '2018-09-01', 'value': 24.791666666666668},
 {'date': '2018-09-02', 'value': 18.25},
 {'date': '2018-09-03', 'value': 31.25},
 {'date': '2018-09-04', 'value': 36.875},
 {'date': '2018-09-05', 'value': 38.208333333333336},
 {'date': '2018-09-06', 'value': 30.916666666666668},
 {'date': '2018-09-07', 'value': 13.0},
 {'date': '2018-09-11', 'value': 35.17391304347826},
 {'date': '2018-09-12', 'value': 35.75},
 {'date': '2018-09-13', 'value': 33.208333333333336},
 {'date': '2018-09-14', 'value': 43.041666666666664},
 {'date': '2018-09-15', 'value': 21.0},
 {'date': '2018-09-16', 'value': 21.318181818181817},
 {'date': '2018-09-17', 'value': 33.291666666666664},
 {'date': '2018-09-18', 'value': 33.583333333333336},
 {'date': '2018-09-19', 'value': 35.583333333333336},
 {'date': '2018-09-20', 'value': 39.25},
 {'date': '2018-09-21', 'value': 37.958333333333336},
 {'date': '2018-09-22', 'value': 33.083333333333336},
 {'date': '2018-09-23', 'value': 19.166666666666668},
 {'date': '2018-09-24', 'value': 28.875},
 {'date': '2018-09-25', 'value': 26.208333333333332},
 {'date': '2018-09-26', 'value': 26.75},
 {'date': '2018-09-27', 'value': 62.25},
 {'date': '2018-09-28', 'value': 75.375},
 {'date': '2018-09-29', 'value': 41.75},
 {'date': '2018-09-30', 'value': 22.458333333333332},
 {'date': '2018-10-01', 'value': 17.0},
 {'date': '2018-10-02', 'value': 32.26086956521739},
 {'date': '2018-10-03', 'value': 49.041666666666664},
 {'date': '2018-10-04', 'value': 43.458333333333336},
 {'date': '2018-10-05', 'value': 43.041666666666664},
 {'date': '2018-10-06', 'value': 35.583333333333336},
 {'date': '2018-10-07', 'value': 36.833333333333336},
 {'date': '2018-10-08', 'value': 48.375},
 {'date': '2018-10-09', 'value': 57.0},
 {'date': '2018-10-11', 'value': 39.08695652173913},
 {'date': '2018-10-12', 'value': 43.75},
 {'date': '2018-10-13', 'value': 47.375},
 {'date': '2018-10-14', 'value': 38.625},
 {'date': '2018-10-15', 'value': 21.5},
 {'date': '2018-10-16', 'value': 40.36363636363637},
 {'date': '2018-10-17', 'value': 45.125},
 {'date': '2018-10-18', 'value': 46.583333333333336},
 {'date': '2018-10-19', 'value': 56.958333333333336},
 {'date': '2018-10-20', 'value': 44.25},
 {'date': '2018-10-21', 'value': 31.75},
 {'date': '2018-10-22', 'value': 33.208333333333336},
 {'date': '2018-10-23', 'value': 54.125},
 {'date': '2018-10-24', 'value': 49.416666666666664},
 {'date': '2018-10-25', 'value': 29.041666666666668},
 {'date': '2018-10-26', 'value': 40.5},
 {'date': '2018-10-27', 'value': 34.083333333333336},
 {'date': '2018-10-28', 'value': 17.75},
 {'date': '2018-10-29', 'value': 22.75},
 {'date': '2018-10-30', 'value': 32.391304347826086},
 {'date': '2018-11-01', 'value': 30.0},
 {'date': '2018-11-02', 'value': 32.125},
 {'date': '2018-11-03', 'value': 34.958333333333336},
 {'date': '2018-11-04', 'value': 24.375},
 {'date': '2018-11-05', 'value': 29.583333333333332},
 {'date': '2018-11-06', 'value': 30.75},
 {'date': '2018-11-07', 'value': 33.5},
 {'date': '2018-11-08', 'value': 46.125},
 {'date': '2018-11-09', 'value': 30.291666666666668},
 {'date': '2018-11-10', 'value': 27.458333333333332},
 {'date': '2018-11-11', 'value': 27.583333333333332},
 {'date': '2018-11-12', 'value': 37.458333333333336},
 {'date': '2018-11-13', 'value': 33.666666666666664},
 {'date': '2018-11-14', 'value': 21.0},
 {'date': '2018-11-15', 'value': 45.52173913043478},
 {'date': '2018-11-16', 'value': 41.041666666666664},
 {'date': '2018-11-17', 'value': 29.125},
 {'date': '2018-11-18', 'value': 28.166666666666668},
 {'date': '2018-11-19', 'value': 32.75},
 {'date': '2018-11-20', 'value': 35.125},
 {'date': '2018-11-21', 'value': 46.125},
 {'date': '2018-11-22', 'value': 47.666666666666664},
 {'date': '2018-11-23', 'value': 42.541666666666664},
 {'date': '2018-11-24', 'value': 36.130434782608695},
 {'date': '2018-11-25', 'value': 33.208333333333336},
 {'date': '2018-11-26', 'value': 43.17391304347826},
 {'date': '2018-11-27', 'value': 37.916666666666664},
 {'date': '2018-11-28', 'value': 47.375},
 {'date': '2018-11-29', 'value': 53.47826086956522},
 {'date': '2018-11-30', 'value': 56.82608695652174},
 {'date': '2018-12-01', 'value': 58.416666666666664},
 {'date': '2018-12-02', 'value': 43.75},
 {'date': '2018-12-03', 'value': 48.0},
 {'date': '2018-12-04', 'value': 51.25},
 {'date': '2018-12-05', 'value': 49.0},
 {'date': '2018-12-06', 'value': 44.25},
 {'date': '2018-12-07', 'value': 45.416666666666664},
 {'date': '2018-12-08', 'value': 44.958333333333336},
 {'date': '2018-12-09', 'value': 37.75},
 {'date': '2018-12-10', 'value': 42.875},
 {'date': '2018-12-11', 'value': 58.77272727272727},
 {'date': '2018-12-12', 'value': 68.5},
 {'date': '2018-12-16', 'value': 53.75},
 {'date': '2018-12-17', 'value': 47.458333333333336},
 {'date': '2018-12-18', 'value': 52.5},
 {'date': '2018-12-19', 'value': 52.375},
 {'date': '2018-12-20', 'value': 56.5},
 {'date': '2018-12-21', 'value': 51.708333333333336},
 {'date': '2018-12-22', 'value': 47.0},
 {'date': '2018-12-23', 'value': 39.833333333333336},
 {'date': '2018-12-24', 'value': 36.333333333333336},
 {'date': '2018-12-25', 'value': 28.875},
 {'date': '2018-12-26', 'value': 27.5},
 {'date': '2018-12-27', 'value': 38.75},
 {'date': '2018-12-28', 'value': 47.583333333333336},
 {'date': '2018-12-29', 'value': 49.458333333333336},
 {'date': '2018-12-30', 'value': 48.916666666666664},
 {'date': '2018-12-31', 'value': 47.583333333333336},
 {'date': '2019-01-01', 'value': 38.0},
 {'date': '2019-01-02', 'value': 34.791666666666664},
 {'date': '2019-01-03', 'value': 62.916666666666664},
 {'date': '2019-01-04', 'value': 63.291666666666664},
 {'date': '2019-01-05', 'value': 66.25},
 {'date': '2019-01-06', 'value': 64.08333333333333},
 {'date': '2019-01-07', 'value': 70.83333333333333},
 {'date': '2019-01-08', 'value': 50.791666666666664},
 {'date': '2019-01-09', 'value': 49.041666666666664},
 {'date': '2019-01-10', 'value': 56.875},
 {'date': '2019-01-11', 'value': 68.0},
 {'date': '2019-01-12', 'value': 54.75},
 {'date': '2019-01-13', 'value': 62.0},
 {'date': '2019-01-14', 'value': 57.30434782608695},
 {'date': '2019-01-15', 'value': 63.875},
 {'date': '2019-01-16', 'value': 80.125},
 {'date': '2019-01-17', 'value': 55.541666666666664},
 {'date': '2019-01-18', 'value': 40.916666666666664},
 {'date': '2019-01-19', 'value': 34.083333333333336},
 {'date': '2019-01-20', 'value': 49.583333333333336},
 {'date': '2019-01-21', 'value': 51.25},
 {'date': '2019-01-22', 'value': 48.5},
 {'date': '2019-01-23', 'value': 34.458333333333336},
 {'date': '2019-01-24', 'value': 39.75},
 {'date': '2019-01-25', 'value': 61.041666666666664},
 {'date': '2019-01-26', 'value': 59.125},
 {'date': '2019-01-27', 'value': 50.958333333333336},
 {'date': '2019-01-28', 'value': 51.458333333333336},
 {'date': '2019-01-29', 'value': 58.75},
 {'date': '2019-01-30', 'value': 48.25},
 {'date': '2019-01-31', 'value': 44.375},
 {'date': '2019-02-01', 'value': 40.608695652173914},
 {'date': '2019-02-02', 'value': 48.0},
 {'date': '2019-02-03', 'value': 38.958333333333336},
 {'date': '2019-02-04', 'value': 38.75},
 {'date': '2019-02-05', 'value': 52.833333333333336},
 {'date': '2019-02-06', 'value': 62.333333333333336},
 {'date': '2019-02-07', 'value': 68.625},
 {'date': '2019-02-08', 'value': 75.95238095238095},
 {'date': '2019-02-09', 'value': 63.5},
 {'date': '2019-02-10', 'value': 35.541666666666664},
 {'date': '2019-02-11', 'value': 40.458333333333336},
 {'date': '2019-02-12', 'value': 28.0},
 {'date': '2019-02-13', 'value': 45.608695652173914},
 {'date': '2019-02-14', 'value': 64.58333333333333},
 {'date': '2019-02-15', 'value': 66.0},
 {'date': '2019-02-17', 'value': 66.83333333333333},
 {'date': '2019-02-18', 'value': 68.58333333333333},
 {'date': '2019-02-20', 'value': 40.291666666666664},
 {'date': '2019-02-21', 'value': 58.333333333333336},
 {'date': '2019-02-23', 'value': 30.0},
 {'date': '2019-02-24', 'value': 35.708333333333336},

In [53]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

france_daily = (
    df_results.groupby("date")
              .agg(france_no2_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

france_daily

           date  france_no2_mean
0    2017-11-01        26.904762
1    2017-11-02        38.395349
2    2017-11-05        11.225000
3    2017-11-06        14.900000
4    2017-11-07        15.902439
...         ...              ...
2920 2026-02-24        20.166652
2921 2026-02-25        21.787114
2922 2026-02-26        20.068992
2923 2026-02-27        21.743708
2924 2026-02-28        14.739299

[2925 rows x 2 columns]

In [54]:
france_daily[["date", "france_no2_mean"]].to_csv(
    "daily_avg_italy_NO2.csv",
    index=False
)