# Get daily average values for air pollution in the UK from 2016-2026 using openAQ API

In [2]:
import requests
import pandas as pd 
import time

### List possible parameters (e.g. PM10, PM2.5, NO2)

In [ ]:
api_url = "https://api.openaq.org/v3/parameters"

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, headers=headers)
response = response.json()

response

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 46},
 'results': [{'id': 1,
   'name': 'pm10',
   'units': 'µg/m³',
   'displayName': 'PM10',
   'description': 'Particulate matter less than 10 micrometers in diameter mass concentration'},
  {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': 'PM2.5',
   'description': 'Particulate matter less than 2.5 micrometers in diameter mass concentration'},
  {'id': 3,
   'name': 'o3',
   'units': 'µg/m³',
   'displayName': 'O₃ mass',
   'description': 'Ozone mass concentration'},
  {'id': 4,
   'name': 'co',
   'units': 'µg/m³',
   'displayName': 'CO mass',
   'description': 'Carbon Monoxide mass concentration'},
  {'id': 5,
   'name': 'no2',
   'units': 'µg/m³',
   'displayName': 'NO₂ mass',
   'description': 'Nitrogen Dioxide mass concentration'},
  {'id': 6,
   'name': 'so2',
   'units': 'µg/m³',
   'displayName': 'SO₂ mass',
   'description': 'Sulfur Dioxide mass concentration'},
  {'id': 7,
   'name': 'no2',
   'units': 'ppm',
   'displayName': 'NO₂',
   'description': 'Nitrogen Dioxide concentration'},
  {'id': 8,
   'name': 'co',
   'units': 'ppm',
   'displayName': 'CO',
   'description': 'Carbon Monoxide concentration'},
  {'id': 9,
   'name': 'so2',
   'units': 'ppm',
   'displayName': 'SO₂',
   'description': 'Sulfur Dioxide concentration'},
  {'id': 10,
   'name': 'o3',
   'units': 'ppm',
   'displayName': 'O₃',
   'description': 'Ozone concentration'},
  {'id': 11,
   'name': 'bc',
   'units': 'µg/m³',
   'displayName': 'BC',
   'description': 'Black Carbon mass concentration'},
  {'id': 15,
   'name': 'no2',
   'units': 'ppb',
   'displayName': 'NO₂',
   'description': None},
  {'id': 19,
   'name': 'pm1',
   'units': 'µg/m³',
   'displayName': 'PM1',
   'description': 'Particulate matter less than 1 micrometer in diameter mass concentration'},
  {'id': 21,
   'name': 'co2',
   'units': 'ppm',
   'displayName': 'CO₂',
   'description': 'Carbon Dioxide concentration'},
  {'id': 22,
   'name': 'wind_direction',
   'units': 'deg',
   'displayName': 'Wind direction',
   'description': 'Direction that the wind originates from'},
  {'id': 23,
   'name': 'nox',
   'units': 'ppb',
   'displayName': 'NOX',
   'description': None},
  {'id': 24,
   'name': 'no',
   'units': 'ppb',
   'displayName': 'NO',
   'description': None},
  {'id': 27,
   'name': 'nox',
   'units': 'µg/m³',
   'displayName': 'NOx mass',
   'description': 'Nitrogen Oxides mass concentration'},
  {'id': 28,
   'name': 'ch4',
   'units': 'ppm',
   'displayName': 'CH₄',
   'description': 'Methane concentration'},
  {'id': 32,
   'name': 'o3',
   'units': 'ppb',
   'displayName': 'O₃',
   'description': None},
  {'id': 33,
   'name': 'ufp',
   'units': 'particles/cm³',
   'displayName': 'UFP count',
   'description': 'Ultrafine Particles count concentration'},
  {'id': 34,
   'name': 'wind_speed',
   'units': 'm/s',
   'displayName': 'Wind speed',
   'description': 'Average wind speed in meters per second'},
  {'id': 35,
   'name': 'no',
   'units': 'ppm',
   'displayName': 'NO',
   'description': 'Nitrogen Monoxide concentration'},
  {'id': 95,
   'name': 'pressure',
   'units': 'hpa',
   'displayName': 'Atmospheric pressure',
   'description': 'Atmospheric or barometric pressure'},
  {'id': 97,
   'name': 'pm25-old',
   'units': 'ugm3',
   'displayName': None,
   'description': None},
  {'id': 98,
   'name': 'relativehumidity',
   'units': '%',
   'displayName': 'RH',
   'description': None},
  {'id': 100,
   'name': 'temperature',
   'units': 'c',
   'displayName': 'Temperature (C)',
   'description': None},
  {'id': 101,
   'name': 'so2',
   'units': 'ppb',
   'displayName': 'SO₂',
   'description': None},
  {'id': 102,
   'name': 'co',
   'units': 'ppb',
   'displayName': 'CO',
   'description': None},
  {'id': 125,
   'name': 'um003',
   'units': 'particles/cm³',
   'displayName': 'PM0.3 count',
   'description': None},
  {'id': 126,
   'name': 'um010',
   'units': 'particles/cm³',
   'displayName': 'PM1 count',
   'description': 'PM1 count'},
  {'id': 128,
   'name': 'temperature',
   'units': 'f',
   'displayName': 'Temperature (F)',
   'description': None},
  {'id': 130,
   'name': 'um025',
   'units': 'particles/cm³',
   'displayName': 'PM2.5 count',
   'description': 'PM2.5 count'},
  {'id': 132,
   'name': 'pressure',
   'units': 'mb',
   'displayName': 'Pressure',
   'description': None},
  {'id': 134,
   'name': 'humidity',
   'units': '%',
   'displayName': 'H',
   'description': None},
  {'id': 135,
   'name': 'um100',
   'units': 'particles/cm³',
   'displayName': 'PM10 count',
   'description': 'PM10 count'},
  {'id': 19840,
   'name': 'nox',
   'units': 'ppm',
   'displayName': 'NOx',
   'description': 'Nitrogen Oxides concentration'},
  {'id': 19843,
   'name': 'no',
   'units': 'µg/m³',
   'displayName': 'NO mass',
   'description': 'Nitrogen Monoxide mass concentration'},
  {'id': 19844,
   'name': 'pm4',
   'units': 'µg/m³',
   'displayName': 'PM4.0',
   'description': 'Particulate matter less than 4 micrometers in diameter mass concentration'},
  {'id': 19860,
   'name': 'pm25',
   'units': 'ppm',
   'displayName': None,
   'description': None},
  {'id': 19861,
   'name': 'bc_375',
   'units': 'ng/m³',
   'displayName': 'BC 375nm',
   'description': 'Black Carbon mass concentration 375nm '},
  {'id': 19862,
   'name': 'bc_470',
   'units': 'ng/m³',
   'displayName': 'BC 470nm',
   'description': 'Black Carbon mass concentration 470nm '},
  {'id': 19863,
   'name': 'bc_528',
   'units': 'ng/m³',
   'displayName': 'BC 528nm',
   'description': 'Black Carbon mass concentration 528nm '},
  {'id': 19864,
   'name': 'bc_625',
   'units': 'ng/m³',
   'displayName': 'BC 625nm',
   'description': 'Black Carbon mass concentration 625nm '},
  {'id': 19865,
   'name': 'bc_880',
   'units': 'ng/m³',
   'displayName': 'BC 880nm',
   'description': 'Black Carbon mass concentration 880nm '},
  {'id': 19866,
   'name': 'bc_370',
   'units': 'ng/m³',
   'displayName': 'BC 370nm',
   'description': 'Black Carbon mass concentration 375nm '}]}

# PM10

### Get all stations located in Poland that measure PM10
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "GB",   # only consider stations located in UK
    #"monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm10 = df_sorted

df_top_pm10

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
4,148,London Bloomsbury,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 238, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.52229, 'longitude': -0.125889}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.125889, 51.52229, -0.125889, 51.52229]",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
5,149,Ealing Horn Lane,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 1304579, 'name': 'no2 µg/m³', 'paramet...","{'latitude': 51.51895, 'longitude': -0.265617}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.265617, 51.51895, -0.265617, 51.51895]",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
6,150,London Haringey Priory Park South - UKA00568,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 231, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.58412799971813, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-0.1252540000016108, 51.58412799971813, -0.12...",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
7,152,Camden Kerbside,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 256, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.54421, 'longitude': -0.175269}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.175269, 51.54421, -0.175269, 51.54421]",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
8,153,London Hillingdon - UKA00266,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 239, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.49632999971629, 'longitude': -...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[-0.4608609995824734, 51.49632999971629, -0.46...",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,4619882,Tower Hamlets - Millwall Park,Tower Hamlets,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13240506, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.4891342634, 'longitude': -0.01...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.0129769309432, 51.4891342634, -0.012976930...",None,2025-06-01 00:00:00+00:00,2026-03-06 09:00:00+00:00
287,4990521,Dartford - Town Centre,Dartford,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13537392, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.442557781389, 'longitude': 0.2...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[0.215950164318913, 51.442557781389, 0.2159501...",None,2025-07-04 00:00:00+00:00,2026-03-06 09:00:00+00:00
288,5738875,Kensington and Chelsea - Station Walk,Kensington and Chelsea,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14084832, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.5140517654184, 'longitude': -0...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.216518543773997, 51.5140517654184, -0.2165...",None,2025-09-07 00:00:00+00:00,2026-03-06 09:00:00+00:00
289,5738876,Kensington and Chelsea - Station Walk,Kensington and Chelsea,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14124220, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.5140519844289, 'longitude': -0...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.216532947379263, 51.5140519844289, -0.2165...",None,2025-09-15 00:00:00+00:00,2025-09-15 09:00:00+00:00
232,2730859,Woodville Road,NaN,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 11509, 'name': 'Unknown Person'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 8778449, 'name': 'pm1 µg/m³', 'paramet...","{'latitude': 51.656961, 'longitude': -0.184963}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[-0.184963, 51.656961, -0.184963, 51.656961]",None,NaT,NaT

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [10]:
rows = []

for _, station in df_top_pm10.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM10 behalten
        if sensor["parameter"]["id"] == 1:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm10_sensors = pd.DataFrame(rows)

df_pm10_sensors

,station_id,station_name,sensor_id,sensor_name
0,148,London Bloomsbury,244,pm10 µg/m³
1,149,Ealing Horn Lane,230,pm10 µg/m³
2,150,London Haringey Priory Park South - UKA00568,12626389,pm10 µg/m³
3,152,Camden Kerbside,236,pm10 µg/m³
4,153,London Hillingdon - UKA00266,1928199,pm10 µg/m³
...,...,...,...,...
294,4619882,Tower Hamlets - Millwall Park,13239927,pm10 µg/m³
295,4990521,Dartford - Town Centre,13537666,pm10 µg/m³
296,5738875,Kensington and Chelsea - Station Walk,14084833,pm10 µg/m³
297,5738876,Kensington and Chelsea - Station Walk,14124219,pm10 µg/m³
298,2730859,Woodville Road,8778446,pm10 µg/m³

In [12]:
sensor_ids = df_pm10_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

299

[244,
 230,
 12626389,
 236,
 1928199,
 245,
 248,
 28911,
 28891,
 217,
 227,
 1304758,
 1298329,
 13117098,
 724,
 1215,
 4935,
 5083,
 4947,
 5079,
 5272,
 1999690,
 5308,
 5143,
 5092,
 5247,
 4940,
 1732640,
 4223,
 7711610,
 28414,
 4663061,
 2609233,
 29745,
 9747494,
 28295,
 1876803,
 4294,
 10488785,
 4340,
 4350,
 1999689,
 4479,
 4538,
 1999694,
 4639,
 5097,
 4578,
 1999698,
 2012315,
 29843,
 4675,
 1927062,
 1999693,
 5325,
 4757,
 5307,
 4786,
 5322,
 4801,
 5168,
 28572,
 4868,
 30530,
 4879,
 29061,
 28470,
 4971,
 5015,
 4998,
 29969,
 28999,
 5029,
 1304649,
 5089,
 5148,
 5151,
 5159,
 5211,
 5260,
 5288,
 30065,
 1999471,
 4797,
 29757,
 1399,
 4894,
 4899,
 266,
 1389,
 5035,
 27979,
 4592,
 5104,
 4517,
 4791,
 10367546,
 7815,
 7825,
 30454,
 1304540,
 1304518,
 1304497,
 1304509,
 1304547,
 1304506,
 1304521,
 1304523,
 1304563,
 1304542,
 1304531,
 1304544,
 1304561,
 1304565,
 1304527,
 1304550,
 1304528,
 1304606,
 1306118,
 1316773,
 1304640,
 1304612,
 1304675,
 1304611,
 1304688,
 1304700,
 1304704,
 1304654,
 1304626,
 1304711,
 1304710,
 1304735,
 1304760,
 1304873,
 1304869,
 1304854,
 1304861,
 1304736,
 1304881,
 1304870,
 10144202,
 1304624,
 1304642,
 1304663,
 1304730,
 1304668,
 1304651,
 1304882,
 1304888,
 1304742,
 1304646,
 1304682,
 1304639,
 1304608,
 1304866,
 1304625,
 1304872,
 1304864,
 1304689,
 1304674,
 1304672,
 1304623,
 1304618,
 1304848,
 1304647,
 1304706,
 1304701,
 1304879,
 1308897,
 1304705,
 1304620,
 1304857,
 1304875,
 1304693,
 1304661,
 1304587,
 1304633,
 1304585,
 1304687,
 1304664,
 1304648,
 1304754,
 1304851,
 1307208,
 1334915,
 1561902,
 1636736,
 2009624,
 1759207,
 1759236,
 5079228,
 5079236,
 5079250,
 5079274,
 5079287,
 5079294,
 5079298,
 5079305,
 5079312,
 5079316,
 5079291,
 5114391,
 7978480,
 7971149,
 8423476,
 7971155,
 7978691,
 7971043,
 7979196,
 6905963,
 7978347,
 7971271,
 7971201,
 7979912,
 10092873,
 8833715,
 7971351,
 7979910,
 7977863,
 7971296,
 8939894,
 7971306,
 7978271,
 7970720,
 7980492,
 7980462,
 7980478,
 7970721,
 7980458,
 7972631,
 7972624,
 7972623,
 9211054,
 9210414,
 7970973,
 7979604,
 7981363,
 8622316,
 8622259,
 8622301,
 8656572,
 8811695,
 9131771,
 9224223,
 9224184,
 9310456,
 9339652,
 9483698,
 9502770,
 9502768,
 9526888,
 9796761,
 9877938,
 9915903,
 9915904,
 9915919,
 9965665,
 10050514,
 10060785,
 10081807,
 10090976,
 10256572,
 10432367,
 10433371,
 10543385,
 10660044,
 10747041,
 10849053,
 10911614,
 10932708,
 10984046,
 10986447,
 11029806,
 11200714,
 11222017,
 11245191,
 11280065,
 11324956,
 11370865,
 11383560,
 11406075,
 11509051,
 11657665,
 11698438,
 11741685,
 11763476,
 11796216,
 11798681,
 11818238,
 12151631,
 12514121,
 12640991,
 12926689,
 12973499,
 13239927,
 13537666,
 14084833,
 14124219,
 8778446]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 28911: Seite 1, 1000 Ergebnisse
Sensor 28911: Seite 2, 850 Ergebnisse
Sensor 28891: Seite 1, 1000 Ergebnisse
Sensor 28891: Seite 2, 761 Ergebnisse
Sensor 217: Seite 1, 1000 Ergebnisse
Sensor 217: Seite 2, 1000 Ergebnisse
Sensor 217: Seite 3, 1000 Ergebnisse
Sensor 217: Seite 4, 149 Ergebnisse
Sensor 1304758: Seite 1, 637 Ergebnisse
Sensor 1298329: Seite 1, 548 Ergebnisse
Sensor 1215: Seite 1, 1000 Ergebnisse
Sensor 1215: Seite 2, 1000 Ergebnisse
Sensor 28414: Seite 1, 1000 Ergebnisse
Sensor 29745: Seite 1, 1000 Ergebnisse
Sensor 29745: Seite 2, 1000 Ergebnisse
Sensor 29745: Seite 3, 305 Ergebnisse
Sensor 28295: Seite 1, 1000 Ergebnisse
Sensor 28295: Seite 2, 1000 Ergebnisse
Sensor 29843: Seite 1, 1000 Ergebnisse
Sensor 5325: Seite 1, 1000 Ergebnisse
Sensor 5325: Seite 2, 1000 Ergebnisse
Sensor 28572: Seite 1, 1000 Ergebnisse
Sensor 28572: Seite 2, 1000 Ergebnisse
Sensor 28572: Seite 3, 338 Ergebnisse
Sensor 30530: Seite 1, 1000 Ergebnisse
Sensor 29061: Seite 1, 1000 Ergebnisse
Sensor 29061: Seite 2, 1000 Ergebnisse
Sensor 29061: Seite 3, 114 Ergebnisse
Sensor 28470: Seite 1, 1000 Ergebnisse
Sensor 29969: Seite 1, 1000 Ergebnisse
Sensor 29969: Seite 2, 1000 Ergebnisse
Sensor 29969: Seite 3, 217 Ergebnisse
Sensor 28999: Seite 1, 1000 Ergebnisse
Sensor 30065: Seite 1, 1000 Ergebnisse
Sensor 29757: Seite 1, 803 Ergebnisse
Sensor 4899: Seite 1, 169 Ergebnisse
Sensor 266: Seite 1, 4 Ergebnisse
Sensor 27979: Seite 1, 1000 Ergebnisse
Sensor 7815: Seite 1, 1000 Ergebnisse
Sensor 7815: Seite 2, 1000 Ergebnisse
Sensor 7825: Seite 1, 1000 Ergebnisse
Sensor 7825: Seite 2, 1000 Ergebnisse
Sensor 7825: Seite 3, 648 Ergebnisse
Sensor 30454: Seite 1, 1000 Ergebnisse
Sensor 30454: Seite 2, 124 Ergebnisse
Sensor 1304540: Seite 1, 1000 Ergebnisse
Sensor 1304540: Seite 2, 397 Ergebnisse
Sensor 1304518: Seite 1, 982 Ergebnisse
Sensor 1304497: Seite 1, 1000 Ergebnisse
Sensor 1304497: Seite 2, 510 Ergebnisse
Sensor 1304509: Seite 1, 1000 Ergebnisse
Sensor 1304509: Seite 2, 553 Ergebnisse
Sensor 1304547: Seite 1, 1000 Ergebnisse
Sensor 1304547: Seite 2, 631 Ergebnisse
Sensor 1304506: Seite 1, 1000 Ergebnisse
Sensor 1304506: Seite 2, 561 Ergebnisse
Sensor 1304521: Seite 1, 1000 Ergebnisse
Sensor 1304521: Seite 2, 680 Ergebnisse
Sensor 1304523: Seite 1, 1000 Ergebnisse
Sensor 1304523: Seite 2, 580 Ergebnisse
Sensor 1304563: Seite 1, 1000 Ergebnisse
Sensor 1304563: Seite 2, 528 Ergebnisse
Sensor 1304542: Seite 1, 1000 Ergebnisse
Sensor 1304542: Seite 2, 577 Ergebnisse
Sensor 1304531: Seite 1, 1000 Ergebnisse
Sensor 1304531: Seite 2, 350 Ergebnisse
Sensor 1304544: Seite 1, 710 Ergebnisse
Sensor 1304561: Seite 1, 480 Ergebnisse
Sensor 1304565: Seite 1, 585 Ergebnisse
Sensor 1304527: Seite 1, 261 Ergebnisse
Sensor 1304550: Seite 1, 100 Ergebnisse
Sensor 1304528: Seite 1, 212 Ergebnisse
Sensor 1304606: Seite 1, 1000 Ergebnisse
Sensor 1304606: Seite 2, 381 Ergebnisse
Sensor 1306118: Seite 1, 1000 Ergebnisse
Sensor 1306118: Seite 2, 300 Ergebnisse
Sensor 1316773: Seite 1, 1000 Ergebnisse
Sensor 1316773: Seite 2, 327 Ergebnisse
Sensor 1304640: Seite 1, 1000 Ergebnisse
Sensor 1304640: Seite 2, 591 Ergebnisse
Sensor 1304612: Seite 1, 1000 Ergebnisse
Sensor 1304612: Seite 2, 437 Ergebnisse
Sensor 1304675: Seite 1, 1000 Ergebnisse
Sensor 1304675: Seite 2, 503 Ergebnisse
Sensor 1304611: Seite 1, 1000 Ergebnisse
Sensor 1304611: Seite 2, 640 Ergebnisse
Sensor 1304688: Seite 1, 1000 Ergebnisse
Sensor 1304688: Seite 2, 560 Ergebnisse
Sensor 1304700: Seite 1, 970 Ergebnisse
Sensor 1304704: Seite 1, 1000 Ergebnisse
Sensor 1304704: Seite 2, 546 Ergebnisse
Sensor 1304654: Seite 1, 1000 Ergebnisse
Sensor 1304654: Seite 2, 433 Ergebnisse
Sensor 1304626: Seite 1, 1000 Ergebnisse
Sensor 1304626: Seite 2, 590 Ergebnisse
Sensor 1304711: Seite 1, 1000 Ergebnisse
Sensor 1304711: Seite 2, 508 Ergebnisse
Sensor 1304710: Seite 1, 1000 Ergebnisse
Sensor 1304710: Seite 2, 625 Ergebnisse
Sensor 1304735: Seite 1, 1000 Ergebnisse
Sensor 1304735: Seite 2, 683 Ergebnisse
Sensor 1304760: Seite 1, 1000 Ergebnisse
Sensor 1304760: Seite 2, 635 Ergebnisse
Sensor 1304873: Seite 1, 1000 Ergebnisse
Sensor 1304873: Seite 2, 487 Ergebnisse
Sensor 1304869: Seite 1, 1000 Ergebnisse
Sensor 1304869: Seite 2, 582 Ergebnisse
Sensor 1304854: Seite 1, 1000 Ergebnisse
Sensor 1304854: Seite 2, 562 Ergebnisse
Sensor 1304861: Seite 1, 1000 Ergebnisse
Sensor 1304861: Seite 2, 527 Ergebnisse
Sensor 1304736: Seite 1, 1000 Ergebnisse
Sensor 1304736: Seite 2, 544 Ergebnisse
Sensor 1304881: Seite 1, 107 Ergebnisse
Sensor 1304870: Seite 1, 842 Ergebnisse
Sensor 10144202: Seite 1, 535 Ergebnisse
Sensor 1304624: Seite 1, 916 Ergebnisse
Sensor 1304642: Seite 1, 1000 Ergebnisse
Sensor 1304642: Seite 2, 513 Ergebnisse
Sensor 1304663: Seite 1, 1000 Ergebnisse
Sensor 1304663: Seite 2, 77 Ergebnisse
Sensor 1304730: Seite 1, 1000 Ergebnisse
Sensor 1304730: Seite 2, 512 Ergebnisse
Sensor 1304668: Seite 1, 1000 Ergebnisse
Sensor 1304668: Seite 2, 522 Ergebnisse
Sensor 1304651: Seite 1, 1000 Ergebnisse
Sensor 1304651: Seite 2, 304 Ergebnisse
Sensor 1304882: Seite 1, 997 Ergebnisse
Sensor 1304888: Seite 1, 926 Ergebnisse
Sensor 1304742: Seite 1, 1000 Ergebnisse
Sensor 1304742: Seite 2, 190 Ergebnisse
Sensor 1304646: Seite 1, 1000 Ergebnisse
Sensor 1304646: Seite 2, 284 Ergebnisse
Sensor 1304682: Seite 1, 1000 Ergebnisse
Sensor 1304682: Seite 2, 329 Ergebnisse
Sensor 1304639: Seite 1, 1000 Ergebnisse
Sensor 1304639: Seite 2, 245 Ergebnisse
Sensor 1304608: Seite 1, 313 Ergebnisse
Sensor 1304866: Seite 1, 1000 Ergebnisse
Sensor 1304866: Seite 2, 35 Ergebnisse
Sensor 1304625: Seite 1, 860 Ergebnisse
Sensor 1304872: Seite 1, 1000 Ergebnisse
Sensor 1304872: Seite 2, 12 Ergebnisse
Sensor 1304864: Seite 1, 1000 Ergebnisse
Sensor 1304864: Seite 2, 13 Ergebnisse
Sensor 1304689: Seite 1, 942 Ergebnisse
Sensor 1304674: Seite 1, 238 Ergebnisse
Sensor 1304672: Seite 1, 992 Ergebnisse
Sensor 1304623: Seite 1, 690 Ergebnisse
Sensor 1304618: Seite 1, 712 Ergebnisse
Sensor 1304848: Seite 1, 815 Ergebnisse
Sensor 1304647: Seite 1, 922 Ergebnisse
Sensor 1304706: Seite 1, 972 Ergebnisse
Sensor 1304701: Seite 1, 974 Ergebnisse
Sensor 1304879: Seite 1, 959 Ergebnisse
Sensor 1308897: Seite 1, 889 Ergebnisse
Sensor 1304705: Seite 1, 712 Ergebnisse
Sensor 1304620: Seite 1, 535 Ergebnisse
Sensor 1304857: Seite 1, 669 Ergebnisse
Sensor 1304875: Seite 1, 676 Ergebnisse
Sensor 1304693: Seite 1, 604 Ergebnisse
Sensor 1304661: Seite 1, 571 Ergebnisse
Sensor 1304587: Seite 1, 376 Ergebnisse
Sensor 1304633: Seite 1, 354 Ergebnisse
Sensor 1304585: Seite 1, 251 Ergebnisse
Sensor 1304687: Seite 1, 244 Ergebnisse
Sensor 1304664: Seite 1, 246 Ergebnisse
Sensor 1304648: Seite 1, 177 Ergebnisse
Sensor 1304754: Seite 1, 156 Ergebnisse
Sensor 1304851: Seite 1, 18 Ergebnisse
Sensor 1307208: Seite 1, 857 Ergebnisse
Sensor 1334915: Seite 1, 1000 Ergebnisse
Sensor 1334915: Seite 2, 185 Ergebnisse
Sensor 1561902: Seite 1, 1000 Ergebnisse
Sensor 1561902: Seite 2, 350 Ergebnisse
Sensor 1636736: Seite 1, 102 Ergebnisse
Sensor 2009624: Seite 1, 522 Ergebnisse
Sensor 1759207: Seite 1, 97 Ergebnisse
Sensor 1759236: Seite 1, 72 Ergebnisse
Sensor 5079236: Seite 1, 1000 Ergebnisse
Sensor 5079236: Seite 2, 1 Ergebnisse
Sensor 5079316: Seite 1, 997 Ergebnisse
Sensor 5114391: Seite 1, 725 Ergebnisse
Sensor 7978480: Seite 1, 3 Ergebnisse
Sensor 7971149: Seite 1, 312 Ergebnisse
Sensor 8423476: Seite 1, 1 Ergebnisse
Sensor 7971155: Seite 1, 87 Ergebnisse
Sensor 7978691: Seite 1, 3 Ergebnisse
Sensor 7971043: Seite 1, 280 Ergebnisse
Sensor 7979196: Seite 1, 3 Ergebnisse
Sensor 6905963: Seite 1, 781 Ergebnisse
Sensor 7978347: Seite 1, 3 Ergebnisse
Sensor 7971271: Seite 1, 134 Ergebnisse
Sensor 7971201: Seite 1, 313 Ergebnisse
Sensor 7979912: Seite 1, 3 Ergebnisse
Sensor 10092873: Seite 1, 22 Ergebnisse
Sensor 8833715: Seite 1, 76 Ergebnisse
Sensor 7971351: Seite 1, 311 Ergebnisse
Sensor 7979910: Seite 1, 3 Ergebnisse
Sensor 7977863: Seite 1, 3 Ergebnisse
Sensor 7971296: Seite 1, 299 Ergebnisse
Sensor 8939894: Seite 1, 15 Ergebnisse
Sensor 7971306: Seite 1, 311 Ergebnisse
Sensor 7978271: Seite 1, 3 Ergebnisse
Sensor 7980492: Seite 1, 194 Ergebnisse
Sensor 7980462: Seite 1, 194 Ergebnisse
Sensor 7980478: Seite 1, 182 Ergebnisse
Sensor 7980458: Seite 1, 194 Ergebnisse
Sensor 7970973: Seite 1, 313 Ergebnisse
Sensor 7979604: Seite 1, 3 Ergebnisse
Sensor 7981363: Seite 1, 310 Ergebnisse
Sensor 8622316: Seite 1, 207 Ergebnisse
Sensor 8622259: Seite 1, 677 Ergebnisse
Sensor 8622301: Seite 1, 443 Ergebnisse
Sensor 8656572: Seite 1, 291 Ergebnisse
Sensor 8811695: Seite 1, 278 Ergebnisse
Sensor 9131771: Seite 1, 14 Ergebnisse
Sensor 9224223: Seite 1, 244 Ergebnisse
Sensor 9224184: Seite 1, 241 Ergebnisse
Sensor 9310456: Seite 1, 194 Ergebnisse
Sensor 9339652: Seite 1, 71 Ergebnisse
Sensor 9483698: Seite 1, 222 Ergebnisse
Sensor 10432367: Seite 1, 136 Ergebnisse
Sensor 10433371: Seite 1, 126 Ergebnisse
Sensor 10543385: Seite 1, 83 Ergebnisse
Sensor 10660044: Seite 1, 118 Ergebnisse
Sensor 10747041: Seite 1, 108 Ergebnisse
Sensor 10849053: Seite 1, 101 Ergebnisse
Sensor 10911614: Seite 1, 25 Ergebnisse
Sensor 10932708: Seite 1, 93 Ergebnisse
Sensor 10984046: Seite 1, 89 Ergebnisse
Sensor 10986447: Seite 1, 86 Ergebnisse
Sensor 11029806: Seite 1, 85 Ergebnisse
Sensor 11200714: Seite 1, 8 Ergebnisse
Sensor 11222017: Seite 1, 68 Ergebnisse
Sensor 11245191: Seite 1, 60 Ergebnisse
Sensor 11280065: Seite 1, 63 Ergebnisse
Sensor 11324956: Seite 1, 7 Ergebnisse
Sensor 11370865: Seite 1, 55 Ergebnisse
Sensor 11383560: Seite 1, 12 Ergebnisse
Sensor 11406075: Seite 1, 52 Ergebnisse
Sensor 11509051: Seite 1, 10 Ergebnisse
Sensor 11657665: Seite 1, 30 Ergebnisse
Sensor 11698438: Seite 1, 2 Ergebnisse
Sensor 11741685: Seite 1, 24 Ergebnisse
Sensor 11763476: Seite 1, 22 Ergebnisse
Sensor 11796216: Seite 1, 19 Ergebnisse
Sensor 11798681: Seite 1, 1 Ergebnisse
Sensor 11818238: Seite 1, 17 Ergebnisse
Sensor 12151631: Seite 1, 375 Ergebnisse
Sensor 12514121: Seite 1, 4 Ergebnisse
Sensor 12640991: Seite 1, 329 Ergebnisse
138375

[{'date': '2020-10-13', 'value': 9.0},
 {'date': '2020-10-14', 'value': 10.0},
 {'date': '2020-10-15', 'value': 10.0},
 {'date': '2020-10-16', 'value': 11.19047619047619},
 {'date': '2020-10-17', 'value': 10.304347826086957},
 {'date': '2020-10-18', 'value': 12.958333333333334},
 {'date': '2020-10-19', 'value': 16.73913043478261},
 {'date': '2020-10-20', 'value': 14.958333333333334},
 {'date': '2020-10-21', 'value': 14.166666666666666},
 {'date': '2020-10-22', 'value': 8.208333333333334},
 {'date': '2020-10-23', 'value': 9.208333333333334},
 {'date': '2020-10-24', 'value': 7.956521739130435},
 {'date': '2020-10-25', 'value': 6.333333333333333},
 {'date': '2020-10-26', 'value': 6.95},
 {'date': '2020-10-27', 'value': 9.222222222222221},
 {'date': '2020-10-28', 'value': 10.782608695652174},
 {'date': '2020-10-29', 'value': 8.529411764705882},
 {'date': '2020-10-30', 'value': 7.076923076923077},
 {'date': '2020-10-31', 'value': 6.3076923076923075},
 {'date': '2020-11-01', 'value': 13.3},
 {'date': '2020-11-02', 'value': 7.041666666666667},
 {'date': '2020-11-04', 'value': 11.625},
 {'date': '2020-11-05', 'value': 33.34782608695652},
 {'date': '2020-11-06', 'value': 72.8695652173913},
 {'date': '2020-11-07', 'value': 32.07692307692308},
 {'date': '2020-11-08', 'value': 43.5},
 {'date': '2020-11-09', 'value': 20.0625},
 {'date': '2020-11-10', 'value': 14.25},
 {'date': '2020-11-11', 'value': 10.166666666666666},
 {'date': '2020-11-12', 'value': 8.208333333333334},
 {'date': '2020-11-13', 'value': 10.583333333333334},
 {'date': '2020-11-14', 'value': 11.722222222222221},
 {'date': '2020-11-15', 'value': 8.681818181818182},
 {'date': '2020-11-16', 'value': 7.181818181818182},
 {'date': '2020-11-17', 'value': 7.571428571428571},
 {'date': '2020-11-18', 'value': 9.375},
 {'date': '2020-11-19', 'value': 9.583333333333334},
 {'date': '2020-11-20', 'value': 9.166666666666666},
 {'date': '2020-11-21', 'value': 6.0},
 {'date': '2020-11-22', 'value': 6.923076923076923},
 {'date': '2020-11-23', 'value': 16.82608695652174},
 {'date': '2020-11-24', 'value': 9.75},
 {'date': '2020-11-25', 'value': 16.166666666666668},
 {'date': '2020-11-26', 'value': 19.307692307692307},
 {'date': '2020-11-27', 'value': 29.166666666666668},
 {'date': '2020-11-28', 'value': 37.21739130434783},
 {'date': '2020-11-29', 'value': 36.125},
 {'date': '2020-11-30', 'value': 26.791666666666668},
 {'date': '2020-12-01', 'value': 11.125},
 {'date': '2020-12-02', 'value': 14.65},
 {'date': '2020-12-04', 'value': 8.125},
 {'date': '2020-12-05', 'value': 7.583333333333333},
 {'date': '2020-12-06', 'value': 12.0},
 {'date': '2020-12-07', 'value': 16.347826086956523},
 {'date': '2020-12-08', 'value': 21.708333333333332},
 {'date': '2020-12-09', 'value': 16.130434782608695},
 {'date': '2020-12-10', 'value': 15.333333333333334},
 {'date': '2020-12-11', 'value': 11.833333333333334},
 {'date': '2020-12-13', 'value': 6.0},
 {'date': '2020-12-14', 'value': 8.041666666666666},
 {'date': '2020-12-15', 'value': 9.75},
 {'date': '2020-12-16', 'value': 10.521739130434783},
 {'date': '2020-12-17', 'value': 8.304347826086957},
 {'date': '2020-12-18', 'value': 8.136363636363637},
 {'date': '2020-12-19', 'value': 9.76923076923077},
 {'date': '2020-12-20', 'value': 8.391304347826088},
 {'date': '2020-12-21', 'value': 8.0},
 {'date': '2020-12-22', 'value': 3.933333333333333},
 {'date': '2020-12-23', 'value': 8.2},
 {'date': '2020-12-24', 'value': 5.0},
 {'date': '2020-12-25', 'value': 6.625},
 {'date': '2020-12-26', 'value': 7.260869565217392},
 {'date': '2020-12-27', 'value': 3.8333333333333335},
 {'date': '2020-12-28', 'value': 9.75},
 {'date': '2020-12-29', 'value': 14.708333333333334},
 {'date': '2020-12-30', 'value': 15.375},
 {'date': '2020-12-31', 'value': 21.58823529411765},
 {'date': '2021-01-01', 'value': 26.4},
 {'date': '2021-01-03', 'value': 9.416666666666666},
 {'date': '2021-01-04', 'value': 7.043478260869565},
 {'date': '2021-01-05', 'value': 5.578947368421052},
 {'date': '2021-01-06', 'value': 6.043478260869565},
 {'date': '2021-01-07', 'value': 13.727272727272727},
 {'date': '2021-01-08', 'value': 25.416666666666668},
 {'date': '2021-01-09', 'value': 19.956521739130434},
 {'date': '2021-01-10', 'value': 23.90909090909091},
 {'date': '2021-01-11', 'value': 13.5},
 {'date': '2021-01-12', 'value': 4.3478260869565215},
 {'date': '2021-01-13', 'value': 11.608695652173912},
 {'date': '2021-01-14', 'value': 6.85},
 {'date': '2021-01-15', 'value': 13.0},
 {'date': '2021-01-16', 'value': 17.47826086956522},
 {'date': '2021-01-17', 'value': 9.375},
 {'date': '2021-01-18', 'value': 10.571428571428571},
 {'date': '2021-01-19', 'value': 5.0},
 {'date': '2021-01-20', 'value': 5.809523809523809},
 {'date': '2021-01-21', 'value': 7.545454545454546},
 {'date': '2021-01-22', 'value': 9.0},
 {'date': '2021-01-23', 'value': 9.272727272727273},
 {'date': '2021-01-24', 'value': 11.08695652173913},
 {'date': '2021-01-25', 'value': 11.5},
 {'date': '2021-01-26', 'value': 11.0},
 {'date': '2021-01-27', 'value': 8.7},
 {'date': '2021-01-28', 'value': 8.875},
 {'date': '2021-01-29', 'value': 7.791666666666667},
 {'date': '2021-01-30', 'value': 9.545454545454545},
 {'date': '2021-01-31', 'value': 12.458333333333334},
 {'date': '2021-02-04', 'value': 11.5},
 {'date': '2021-02-05', 'value': 8.782608695652174},
 {'date': '2021-02-06', 'value': 11.5},
 {'date': '2021-02-07', 'value': 13.75},
 {'date': '2021-02-08', 'value': 7.75},
 {'date': '2021-02-09', 'value': 9.208333333333334},
 {'date': '2021-02-10', 'value': 9.041666666666666},
 {'date': '2021-02-11', 'value': 12.791666666666666},
 {'date': '2021-02-12', 'value': 19.583333333333332},
 {'date': '2021-02-13', 'value': 17.458333333333332},
 {'date': '2021-02-14', 'value': 16.5},
 {'date': '2021-02-16', 'value': 10.666666666666666},
 {'date': '2021-02-17', 'value': 12.333333333333334},
 {'date': '2021-02-18', 'value': 9.666666666666666},
 {'date': '2021-02-19', 'value': 9.909090909090908},
 {'date': '2021-02-21', 'value': 27.0},
 {'date': '2021-02-22', 'value': 27.304347826086957},
 {'date': '2021-02-23', 'value': 18.238095238095237},
 {'date': '2021-02-24', 'value': 11.0},
 {'date': '2021-02-25', 'value': 15.73913043478261},
 {'date': '2021-02-26', 'value': 17.444444444444443},
 {'date': '2021-02-27', 'value': 21.666666666666668},
 {'date': '2021-03-01', 'value': 24.681818181818183},
 {'date': '2021-03-02', 'value': 41.958333333333336},
 {'date': '2021-03-04', 'value': 33.958333333333336},
 {'date': '2021-03-05', 'value': 10.958333333333334},
 {'date': '2021-03-06', 'value': 10.166666666666666},
 {'date': '2021-03-07', 'value': 17.041666666666668},
 {'date': '2021-03-08', 'value': 35.375},
 {'date': '2021-03-09', 'value': 35.5},
 {'date': '2021-03-10', 'value': 19.7},
 {'date': '2021-03-11', 'value': 13.4},
 {'date': '2021-03-12', 'value': 10.7},
 {'date': '2021-03-13', 'value': 7.375},
 {'date': '2021-03-14', 'value': 6.125},
 {'date': '2021-03-15', 'value': 9.416666666666666},
 {'date': '2021-03-16', 'value': 14.166666666666666},
 {'date': '2021-03-17', 'value': 19.904761904761905},
 {'date': '2021-03-18', 'value': 18.347826086956523},
 {'date': '2021-03-19', 'value': 11.0},
 {'date': '2021-03-20', 'value': 12.0},
 {'date': '2021-03-21', 'value': 14.958333333333334},
 {'date': '2021-03-22', 'value': 22.208333333333332},
 {'date': '2021-03-23', 'value': 32.25},
 {'date': '2021-03-24', 'value': 26.058823529411764},
 {'date': '2021-03-25', 'value': 16.541666666666668},
 {'date': '2021-03-26', 'value': 9.083333333333334},
 {'date': '2021-03-27', 'value': 7.857142857142857},
 {'date': '2021-03-28', 'value': 12.071428571428571},
 {'date': '2021-03-29', 'value': 13.333333333333334},
 {'date': '2021-03-30', 'value': 20.714285714285715},
 {'date': '2021-03-31', 'value': 33.526315789473685},
 {'date': '2021-04-01', 'value': 36.25},
 {'date': '2021-04-02', 'value': 32.0},
 {'date': '2021-04-03', 'value': 15.333333333333334},
 {'date': '2021-04-04', 'value': 19.375},
 {'date': '2021-04-05', 'value': 19.130434782608695},
 {'date': '2021-04-06', 'value': 11.26086956521739},
 {'date': '2021-04-07', 'value': 12.391304347826088},
 {'date': '2021-04-08', 'value': 9.523809523809524},
 {'date': '2021-04-09', 'value': 9.166666666666666},
 {'date': '2021-04-10', 'value': 10.842105263157896},
 {'date': '2021-04-11', 'value': 10.071428571428571},
 {'date': '2021-04-12', 'value': 11.0},
 {'date': '2021-04-13', 'value': 17.0},
 {'date': '2021-04-14', 'value': 22.77777777777778},
 {'date': '2021-04-15', 'value': 12.26086956521739},
 {'date': '2021-04-16', 'value': 12.636363636363637},
 {'date': '2021-04-17', 'value': 12.6},
 {'date': '2021-04-18', 'value': 10.476190476190476},
 {'date': '2021-04-19', 'value': 19.458333333333332},
 {'date': '2021-04-20', 'value': 33.69565217391305},
 {'date': '2021-04-21', 'value': 41.666666666666664},
 {'date': '2021-04-22', 'value': 22.15},
 {'date': '2021-04-23', 'value': 18.363636363636363},
 {'date': '2021-04-24', 'value': 17.583333333333332},
 {'date': '2021-04-27', 'value': 21.444444444444443},
 {'date': '2021-04-28', 'value': 31.80952380952381},
 {'date': '2021-04-29', 'value': 16.60833333333333},
 {'date': '2021-04-30', 'value': 12.941176470588236},
 {'date': '2021-05-01', 'value': 17.253846153846155},
 {'date': '2021-05-02', 'value': 21.0},
 {'date': '2021-05-03', 'value': 14.581818181818182},
 {'date': '2021-05-04', 'value': 5.716666666666666},
 {'date': '2021-05-05', 'value': 4.8375},
 {'date': '2021-05-06', 'value': 5.9624999999999995},
 {'date': '2021-05-07', 'value': 8.35},
 {'date': '2021-05-08', 'value': 8.85},
 {'date': '2021-05-09', 'value': 8.45},
 {'date': '2021-05-10', 'value': 6.91764705882353},
 {'date': '2021-05-11', 'value': 10.215789473684211},
 {'date': '2021-05-12', 'value': 9.75263157894737},
 {'date': '2021-05-13', 'value': 10.928571428571429},
 {'date': '2021-05-14', 'value': 12.524999999999997},
 {'date': '2021-05-15', 'value': 12.629166666666668},
 {'date': '2021-05-16', 'value': 7.8478260869565215},
 {'date': '2021-05-17', 'value': 7.729166666666667},
 {'date': '2021-05-18', 'value': 7.352941176470588},
 {'date': '2021-05-19', 'value': 5.766666666666666},
 {'date': '2021-05-20', 'value': 8.082608695652175},
 {'date': '2021-05-21', 'value': 12.587499999999997},
 {'date': '2021-05-22', 'value': 8.36875},
 {'date': '2021-05-25', 'value': 7.0125},
 {'date': '2021-05-26', 'value': 7.45},
 {'date': '2021-05-27', 'value': 13.150000000000004},
 {'date': '2021-05-28', 'value': 19.936363636363634},
 {'date': '2021-05-29', 'value': 20.466666666666665},
 {'date': '2021-05-30', 'value': 19.0},
 {'date': '2021-05-31', 'value': 20.904545454545453},
 {'date': '2021-06-01', 'value': 23.0},
 {'date': '2021-06-02', 'value': 26.09090909090909},
 {'date': '2021-06-03', 'value': 28.075},
 {'date': '2021-06-04', 'value': 12.025},
 {'date': '2021-06-05', 'value': 11.85},
 {'date': '2021-06-06', 'value': 10.561904761904762},
 {'date': '2021-06-07', 'value': 8.404545454545454},
 {'date': '2021-06-08', 'value': 9.872222222222222},
 {'date': '2021-06-10', 'value': 8.516666666666667},
 {'date': '2021-06-11', 'value': 7.666666666666667},
 {'date': '2021-06-12', 'value': 9.020833333333334},
 {'date': '2021-06-13', 'value': 14.886956521739132},
 {'date': '2021-06-14', 'value': 13.190909090909093},
 {'date': '2021-06-15', 'value': 14.929166666666665},
 {'date': '2021-06-16', 'value': 15.0},
 {'date': '2021-06-17', 'value': 13.941666666666668},
 {'date': '2021-06-18', 'value': 6.7124999999999995},
 {'date': '2021-06-19', 'value': 5.391666666666666},
 {'date': '2021-06-20', 'value': 9.521739130434783},
 {'date': '2021-06-21', 'value': 8.758333333333335},
 {'date': '2021-06-22', 'value': 12.669565217391304},
 {'date': '2021-06-23', 'value': 11.649999999999999},
 {'date': '2021-06-24', 'value': 15.286956521739132},
 {'date': '2021-06-25', 'value': 7.195833333333333},
 {'date': '2021-06-26', 'value': 11.0625},
 {'date': '2021-06-27', 'value': 15.313636363636363},
 {'date': '2021-06-28', 'value': 21.358823529411765},
 {'date': '2021-07-08', 'value': 8.716666666666667},
 {'date': '2021-07-09', 'value': 12.291666666666666},
 {'date': '2021-07-10', 'value': 11.0},
 {'date': '2021-07-12', 'value': 8.641666666666667},
 {'date': '2021-07-13', 'value': 14.843478260869563},
 {'date': '2021-07-14', 'value': 14.458333333333334},
 {'date': '2021-07-15', 'value': 11.994444444444445},
 {'date': '2021-07-16', 'value': 17.641666666666666},
 {'date': '2021-07-17', 'value': 10.5},
 {'date': '2021-07-18', 'value': 11.195833333333335},
 {'date': '2021-07-19', 'value': 18.770833333333332},
 {'date': '2021-07-20', 'value': 23.236363636363635},
 {'date': '2021-07-21', 'value': 34.958333333333336},
 {'date': '2021-07-22', 'value': 35.791666666666664},
 {'date': '2021-07-23', 'value': 19.033333333333335},
 {'date': '2021-07-24', 'value': 21.45},
 {'date': '2021-07-25', 'value': 31.22222222222222},
 {'date': '2021-08-03', 'value': 10.779166666666663},
 {'date': '2021-08-04', 'value': 12.533333333333333},
 {'date': '2021-08-05', 'value': 9.814285714285713},
 {'date': '2021-08-06', 'value': 8.129166666666666},
 {'date': '2021-08-07', 'value': 8.541666666666666},
 {'date': '2021-08-08', 'value': 7.5},
 {'date': '2021-08-09', 'value': 7.086956521739131},
 {'date': '2021-08-10', 'value': 9.375},
 {'date': '2021-08-11', 'value': 8.583333333333334},
 {'date': '2021-08-12', 'value': 7.708333333333333},
 {'date': '2021-08-13', 'value': 10.3375},
 {'date': '2021-08-14', 'value': 13.0},
 {'date': '2021-08-15', 'value': 9.666666666666666},
 {'date': '2021-08-16', 'value': 11.625},
 {'date': '2021-08-17', 'value': 13.125},
 {'date': '2021-08-18', 'value': 7.208333333333333},
 {'date': '2021-08-19', 'value': 7.285714285714286},
 {'date': '2021-08-20', 'value': 4.895833333333333},
 {'date': '2021-08-21', 'value': 8.958333333333334},
 {'date': '2021-08-22', 'value': 9.291666666666666},
 {'date': '2021-08-23', 'value': 10.191666666666668},
 {'date': '2021-08-24', 'value': 10.975},
 {'date': '2021-08-25', 'value': 8.795652173913044},
 {'date': '2021-08-26', 'value': 10.370833333333334},
 {'date': '2021-08-27', 'value': 13.708333333333334},
 {'date': '2021-08-28', 'value': 17.791666666666668},
 {'date': '2021-08-29', 'value': 14.708333333333334},
 {'date': '2021-08-30', 'value': 11.0},
 {'date': '2021-08-31', 'value': 11.521739130434783},
 {'date': '2021-09-01', 'value': 14.833333333333334},
 {'date': '2021-09-02', 'value': 18.875},
 {'date': '2021-09-03', 'value': 18.583333333333332},
 {'date': '2021-09-04', 'value': 22.791666666666668},
 {'date': '2021-09-05', 'value': 23.25},
 {'date': '2021-09-06', 'value': 33.625},
 {'date': '2021-09-07', 'value': 44.708333333333336},
 {'date': '2021-09-08', 'value': 49.583333333333336},
 {'date': '2021-09-09', 'value': 35.375},
 {'date': '2021-09-10', 'value': 8.833333333333334},
 {'date': '2021-09-11', 'value': 8.85},
 {'date': '2021-09-12', 'value': 8.945833333333333},
 {'date': '2021-09-13', 'value': 9.625},
 {'date': '2021-09-14', 'value': 15.81304347826087},
 {'date': '2021-09-15', 'value': 18.75},
 {'date': '2021-09-16', 'value': 18.033333333333335},
 {'date': '2021-09-17', 'value': 13.666666666666666},
 {'date': '2021-09-18', 'value': 16.9875},
 {'date': '2021-09-19', 'value': 29.0},
 {'date': '2021-09-20', 'value': 16.670833333333334},
 {'date': '2021-09-21', 'value': 18.833333333333332},
 {'date': '2021-09-22', 'value': 14.458333333333334},
 {'date': '2021-09-23', 'value': 10.879166666666665},
 {'date': '2021-09-24', 'value': 8.166666666666666},
 {'date': '2021-09-25', 'value': 10.958333333333334},
 {'date': '2021-09-26', 'value': 16.5},
 {'date': '2021-09-27', 'value': 8.945833333333333},
 {'date': '2021-09-28', 'value': 7.458333333333333},
 {'date': '2021-09-29', 'value': 8.0},
 {'date': '2021-09-30', 'value': 7.913043478260869},
 {'date': '2021-10-01', 'value': 5.5},
 {'date': '2021-10-02', 'value': 8.016666666666667},
 {'date': '2021-10-03', 'value': 4.933333333333334},
 {'date': '2021-10-04', 'value': 8.133333333333333},
 {'date': '2021-10-05', 'value': 6.804166666666667},
 {'date': '2021-10-06', 'value': 5.7875000000000005},
 {'date': '2021-10-07', 'value': 10.120833333333334},
 {'date': '2021-10-08', 'value': 8.870833333333334},
 {'date': '2021-10-09', 'value': 25.2},
 {'date': '2021-10-10', 'value': 31.704166666666666},
 {'date': '2021-10-11', 'value': 13.200000000000001},
 {'date': '2021-10-12', 'value': 15.9125},
 {'date': '2021-10-13', 'value': 11.045833333333334},
 {'date': '2021-10-14', 'value': 11.475},
 {'date': '2021-10-15', 'value': 10.191666666666668},
 {'date': '2021-10-16', 'value': 15.879166666666668},
 {'date': '2021-10-17', 'value': 13.3125},
 {'date': '2021-10-18', 'value': 14.275},
 {'date': '2021-10-19', 'value': 11.25},
 {'date': '2021-10-20', 'value': 21.058333333333334},
 {'date': '2021-10-21', 'value': 8.225},
 {'date': '2021-10-22', 'value': 8.9125},
 {'date': '2021-10-23', 'value': 7.870833333333334},
 {'date': '2021-10-24', 'value': 7.920833333333333},
 {'date': '2021-10-25', 'value': 9.970833333333333},
 {'date': '2021-10-26', 'value': 8.129166666666666},
 {'date': '2021-10-27', 'value': 7.729166666666667},
 {'date': '2021-10-28', 'value': 9.683333333333334},
 {'date': '2021-10-29', 'value': 12.0},
 {'date': '2021-10-30', 'value': 9.91304347826087},
 {'date': '2021-10-31', 'value': 9.384},
 {'date': '2021-11-01', 'value': 10.450000000000001},
 {'date': '2021-11-02', 'value': 9.983333333333333},
 {'date': '2021-11-03', 'value': 19.195833333333333},
 {'date': '2021-11-04', 'value': 10.0875},
 {'date': '2021-11-05', 'value': 12.85},
 {'date': '2021-11-06', 'value': 20.375},
 {'date': '2021-11-07', 'value': 10.775},
 {'date': '2021-11-08', 'value': 19.004166666666666},
 {'date': '2021-11-09', 'value': 11.866666666666667},
 {'date': '2021-11-10', 'value': 7.291666666666667},
 {'date': '2021-11-11', 'value': 10.004166666666666},
 {'date': '2021-11-12', 'value': 13.137500000000001},
 {'date': '2021-11-13', 'value': 8.554166666666667},
 {'date': '2021-11-14', 'value': 8.595652173913043},
 {'date': '2021-11-15', 'value': 14.241666666666667},
 {'date': '2021-11-16', 'value': 18.520833333333332},
 {'date': '2021-11-17', 'value': 15.208333333333334},
 {'date': '2021-11-18', 'value': 15.812500000000002},
 {'date': '2021-11-19', 'value': 9.566666666666668},
 {'date': '2021-11-20', 'value': 15.616666666666667},
 {'date': '2021-11-21', 'value': 8.991666666666667},
 {'date': '2021-11-22', 'value': 10.991666666666667},
 {'date': '2021-11-23', 'value': 20.179166666666667},
 {'date': '2021-11-24', 'value': 29.474999999999998},
 {'date': '2021-11-25', 'value': 17.629166666666666},
 {'date': '2021-11-26', 'value': 11.5},
 {'date': '2021-11-27', 'value': 6.383333333333333},
 {'date': '2021-11-29', 'value': 13.770833333333334},
 {'date': '2021-11-30', 'value': 11.237499999999999},
 {'date': '2021-12-01', 'value': 4.520833333333333},
 {'date': '2021-12-02', 'value': 7.641666666666667},
 {'date': '2021-12-03', 'value': 10.458333333333334},
 {'date': '2021-12-04', 'value': 13.958333333333334},
 {'date': '2021-12-05', 'value': 5.720833333333334},
 {'date': '2021-12-06', 'value': 9.6},
 {'date': '2021-12-07', 'value': 8.728571428571428},
 {'date': '2021-12-08', 'value': 11.095833333333333},
 {'date': '2021-12-09', 'value': 12.866666666666667},
 {'date': '2021-12-10', 'value': 8.9},
 {'date': '2021-12-11', 'value': 10.012500000000001},
 {'date': '2021-12-12', 'value': 7.8875},
 {'date': '2021-12-13', 'value': 5.991666666666667},
 {'date': '2021-12-14', 'value': 9.241666666666667},
 {'date': '2021-12-15', 'value': 8.070833333333333},
 {'date': '2021-12-16', 'value': 12.591666666666669},
 {'date': '2021-12-17', 'value': 18.6375},
 {'date': '2021-12-18', 'value': 13.808333333333332},
 {'date': '2021-12-19', 'value': 7.95},
 {'date': '2021-12-20', 'value': 8.225},
 {'date': '2021-12-21', 'value': 22.349999999999998},
 {'date': '2021-12-22', 'value': 27.34166666666667},
 {'date': '2021-12-23', 'value': 28.96666666666667},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

uk_daily = (
    df_results.groupby("date")
              .agg(uk_pm10_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

uk_daily

           date  france_pm10_mean
0    2016-01-30          6.105263
1    2016-01-31          9.700000
2    2016-02-01         10.136364
3    2016-02-02         16.866667
4    2016-02-03         12.125000
...         ...               ...
3511 2026-02-24         17.103575
3512 2026-02-25         17.773800
3513 2026-02-26         14.262275
3514 2026-02-27         10.556579
3515 2026-02-28         10.406697

[3516 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
uk_daily[["date", "uk_pm10_mean"]].to_csv(
    "daily_avg_uk_PM10.csv",
    index=False
)

# PM2.5

### Get 200 stations located in France that measure PM2.5
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "GB",   # only consider stations located in UK
    "parameters_id": 2,   # PM2.5
    #"monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm25 = df_sorted

df_top_pm25

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
0,60,Haringey Roadside,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 88, 'name': 'no2 µg/m³', 'parameter': ...","{'latitude': 51.5993, 'longitude': -0.068218}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.068218, 51.5993, -0.068218, 51.5993]",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
2,141,London Harlington,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 237, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.48879, 'longitude': -0.441614}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.441614, 51.48879, -0.441614, 51.48879]",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
5,148,Camden - Bloomsbury,Camden,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 238, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.52228699999999, 'longitude': -...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.125848, 51.52228699999999, -0.125848, 51.5...",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
6,150,London Haringey Priory Park South,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 231, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.584128, 'longitude': -0.125254}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.125254, 51.584128, -0.125254, 51.584128]",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
8,152,Camden - Swiss Cottage,Camden,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 256, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.544219, 'longitude': -0.175284}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.175284, 51.544219, -0.175284, 51.544219]",None,2016-01-30 01:00:00+00:00,2026-03-06 10:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,6247129,SL-AG-001(Bardsey),NaN,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 12, 'name': 'AirGradient'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 15498414, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 53.88994, 'longitude': -1.4395}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[-1.4395, 53.88994, -1.4395, 53.88994]",None,2026-02-20 22:00:00+00:00,2026-03-06 11:00:00+00:00
512,6254734,Dean House,NaN,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 12, 'name': 'AirGradient'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 15555230, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 53.7843, 'longitude': -1.646}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[-1.646, 53.7843, -1.646, 53.7843]",None,2026-02-27 20:00:00+00:00,2026-03-02 11:00:00+00:00
513,6259992,"Girton College, Cambridge",NaN,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 12, 'name': 'AirGradient'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 15594341, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 52.2297, 'longitude': 0.08374}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[0.08374, 52.2297, 0.08374, 52.2297]",None,2026-03-04 12:00:00+00:00,2026-03-06 11:00:00+00:00
514,6261449,"Denton, Norfolk",NaN,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 12, 'name': 'AirGradient'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 15605512, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 52.44585, 'longitude': 1.35337}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[1.35337, 52.44585, 1.35337, 52.44585]",None,2026-03-05 19:00:00+00:00,2026-03-06 11:00:00+00:00
312,2730859,Woodville Road,NaN,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 11509, 'name': 'Unknown Person'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 8778449, 'name': 'pm1 µg/m³', 'paramet...","{'latitude': 51.656961, 'longitude': -0.184963}","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[-0.184963, 51.656961, -0.184963, 51.656961]",None,NaT,NaT

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [36]:
rows = []

for _, station in df_top_pm25.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM25 behalten
        if sensor["parameter"]["id"] == 2:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm25_sensors = pd.DataFrame(rows)

df_pm25_sensors

     station_id                       station_name  sensor_id sensor_name
0            60                  Haringey Roadside        206  pm25 µg/m³
1           141                  London Harlington        261  pm25 µg/m³
2           148                Camden - Bloomsbury        232  pm25 µg/m³
3           150  London Haringey Priory Park South   12626392  pm25 µg/m³
4           152             Camden - Swiss Cottage        235  pm25 µg/m³
..          ...                                ...        ...         ...
510     6247129                 SL-AG-001(Bardsey)   15498415  pm25 µg/m³
511     6254734                         Dean House   15555231  pm25 µg/m³
512     6259992          Girton College, Cambridge   15594342  pm25 µg/m³
513     6261449                    Denton, Norfolk   15605513  pm25 µg/m³
514     2730859                     Woodville Road    8778433  pm25 µg/m³

[515 rows x 4 columns]

In [37]:
sensor_ids = df_pm25_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

515

[206,
 261,
 232,
 12626392,
 235,
 1927060,
 246,
 249,
 254,
 257,
 1304692,
 211,
 28890,
 228,
 12915957,
 13117097,
 12626393,
 12626397,
 5318,
 1213,
 4850,
 1279,
 1314,
 12785243,
 1404,
 1999688,
 1467,
 5135,
 5088,
 5252,
 4938,
 1732639,
 7711609,
 29698,
 5269,
 4663062,
 2609234,
 4917,
 9747495,
 12626400,
 1876804,
 12626390,
 29675,
 28877,
 12626391,
 1999692,
 2572698,
 28321,
 1999697,
 12626399,
 5096,
 12626396,
 1999696,
 2012316,
 29844,
 1927061,
 1999691,
 5321,
 4767,
 5196,
 4787,
 5284,
 4798,
 4818,
 4825,
 4870,
 5066,
 5033,
 4915,
 4919,
 4960,
 4978,
 4989,
 5010,
 5025,
 5026,
 2032039,
 5090,
 5145,
 5150,
 5156,
 5217,
 5262,
 5286,
 5312,
 1999695,
 4788,
 4892,
 4728,
 4895,
 4900,
 265,
 12626395,
 1390,
 5034,
 4983,
 12626388,
 5106,
 4792,
 10367545,
 12626398,
 29695,
 28991,
 29838,
 7814,
 12626394,
 446268,
 446275,
 1296216,
 1296207,
 1296138,
 1296338,
 1296256,
 1296024,
 1295945,
 1295981,
 1296105,
 1296109,
 1296199,
 1296008,
 1295908,
 1296291,
 1295916,
 1295930,
 1296179,
 1296283,
 1296124,
 1296047,
 1295989,
 1296004,
 1296072,
 1295993,
 1296324,
 1295966,
 1295961,
 1296055,
 1296252,
 1296320,
 1296101,
 1296212,
 1296287,
 1296032,
 1296152,
 1296195,
 1296000,
 1296142,
 1295972,
 1296309,
 1296187,
 1296237,
 1295957,
 1295953,
 1296093,
 1296203,
 1296271,
 1295926,
 1296051,
 1296043,
 1296156,
 1296328,
 1295977,
 1296017,
 1296275,
 1296267,
 1296039,
 1296089,
 1295903,
 1296164,
 1296076,
 1296084,
 1295912,
 1296225,
 1296129,
 1296080,
 1296116,
 1296353,
 1296233,
 1296229,
 1296241,
 1296313,
 1296070,
 1296097,
 1296340,
 1296345,
 1296013,
 1296279,
 1296183,
 1296060,
 1296248,
 1296191,
 1296176,
 1295920,
 1296335,
 1296349,
 1295924,
 1295934,
 1296299,
 1296171,
 1296221,
 1295942,
 1296127,
 1296306,
 1296133,
 1296263,
 1296160,
 1296028,
 30453,
 12913463,
 6933605,
 6612671,
 6955371,
 1792043,
 1792083,
 1304516,
 1304504,
 1304507,
 1304559,
 1339998,
 1304721,
 1304607,
 1304680,
 1557241,
 1666368,
 13717234,
 12716244,
 12090599,
 12129805,
 1304722,
 1304713,
 1304737,
 1304734,
 7771087,
 10416144,
 12098616,
 10975087,
 10601409,
 11268004,
 1304849,
 7799668,
 10144201,
 1304613,
 1304632,
 1304686,
 1304862,
 1304619,
 1304757,
 1304669,
 1304614,
 1304683,
 1304886,
 1953963,
 1304653,
 1304660,
 1304679,
 2235091,
 1304584,
 1304670,
 1304588,
 1304814,
 1307207,
 1356319,
 1334916,
 1561901,
 2009625,
 5079229,
 5079237,
 5079251,
 5079275,
 5079282,
 5079295,
 5079299,
 5079306,
 5079313,
 5079317,
 12626401,
 5079292,
 6395783,
 5114392,
 6530154,
 6530346,
 6738569,
 6794730,
 6905962,
 6912437,
 6971135,
 6977044,
 6977036,
 7251982,
 7267676,
 7267678,
 7296919,
 7337003,
 7349462,
 7374349,
 7515649,
 7544409,
 7779243,
 7897356,
 7897357,
 7897363,
 7897367,
 7897374,
 7897359,
 7897362,
 7897361,
 7897368,
 7897335,
 7897344,
 7933691,
 7981356,
 8622289,
 8656561,
 8811685,
 9131767,
 9224230,
 9224190,
 9310452,
 9339665,
 9483707,
 9502772,
 9502776,
 9526870,
 9796763,
 9877951,
 9915924,
 9915912,
 9915909,
 9965662,
 10050517,
 10060780,
 10081803,
 10090974,
 10256569,
 10432372,
 10433364,
 10543394,
 10563649,
 10563650,
 10563647,
 10563648,
 10574317,
 10574315,
 10574314,
 10574316,
 10660054,
 10747047,
 10849042,
 10911603,
 10932702,
 10984025,
 10986430,
 11029807,
 11200694,
 11222033,
 11245170,
 11280080,
 11324944,
 11370869,
 11383552,
 11406056,
 11509044,
 11599599,
 11599584,
 11599591,
 11599580,
 11599596,
 11599579,
 11599598,
 11599597,
 11599593,
 11599578,
 11599585,
 11599589,
 11599575,
 11599594,
 11599587,
 11599582,
 11599590,
 11599577,
 11599574,
 11599586,
 11599588,
 11599576,
 11599573,
 11599595,
 11599583,
 11599592,
 11599581,
 11599949,
 11599951,
 11599950,
 11657641,
 11698456,
 11722221,
 11741710,
 11763465,
 11796193,
 11798699,
 11818241,
 12151587,
 12178096,
 12177952,
 12177944,
 12255842,
 12394602,
 12460933,
 12514122,
 12592751,
 12592754,
 12592753,
 12592752,
 12640990,
 12611189,
 12667317,
 12667931,
 12736690,
 12740085,
 12750913,
 12814530,
 12872712,
 12915156,
 12926970,
 12916492,
 12973500,
 12973502,
 13117416,
 13119187,
 13462324,
 13509665,
 13875548,
 13886562,
 13893646,
 13963538,
 14085098,
 14099778,
 14107197,
 14124221,
 14153846,
 14153856,
 14153861,
 14153936,
 14152335,
 14152355,
 14152380,
 14152650,
 14153005,
 14153070,
 14153308,
 14153313,
 14153328,
 14153438,
 14153623,
 14153638,
 14153668,
 14153688,
 14153816,
 14153213,
 14153851,
 14152555,
 14152770,
 14152390,
 14157104,
 14165632,
 14383281,
 14183636,
 14244676,
 14262772,
 14269383,
 14269378,
 14313795,
 14349086,
 14385076,
 14407778,
 14425510,
 14443357,
 14445094,
 14559242,
 14611560,
 14617329,
 14643021,
 14661310,
 14662675,
 14667506,
 14675917,
 14723916,
 14737543,
 14745619,
 14816074,
 14922919,
 14932672,
 14932677,
 14945826,
 14983967,
 14993323,
 15143648,
 15143653,
 15143658,
 15148560,
 15170480,
 15187833,
 15271997,
 15275214,
 15311445,
 15339990,
 15351101,
 15357775,
 15357780,
 15357785,
 15364912,
 15376876,
 15498415,
 15555231,
 15594342,
 15605513,
 8778433]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 206: Seite 1, 11 Ergebnisse
Sensor 1304692: Seite 1, 1000 Ergebnisse
Sensor 1304692: Seite 2, 285 Ergebnisse
Sensor 28890: Seite 1, 1000 Ergebnisse
Sensor 28890: Seite 2, 1000 Ergebnisse
Sensor 28890: Seite 3, 517 Ergebnisse
Sensor 12915957: Seite 1, 299 Ergebnisse
Sensor 1213: Seite 1, 1000 Ergebnisse
Sensor 1213: Seite 2, 1000 Ergebnisse
Sensor 29698: Seite 1, 1000 Ergebnisse
Sensor 29698: Seite 2, 1000 Ergebnisse
Sensor 29698: Seite 3, 704 Ergebnisse
Sensor 29675: Seite 1, 1000 Ergebnisse
Sensor 28877: Seite 1, 1000 Ergebnisse
Sensor 28877: Seite 2, 1000 Ergebnisse
Sensor 28877: Seite 3, 604 Ergebnisse
Sensor 28321: Seite 1, 1000 Ergebnisse
Sensor 28321: Seite 2, 1000 Ergebnisse
Sensor 28321: Seite 3, 651 Ergebnisse
Sensor 29844: Seite 1, 1000 Ergebnisse
Sensor 5321: Seite 1, 1000 Ergebnisse
Sensor 5321: Seite 2, 1000 Ergebnisse
Sensor 4900: Seite 1, 185 Ergebnisse
Sensor 265: Seite 1, 4 Ergebnisse
Sensor 4983: Seite 1, 1000 Ergebnisse
Sensor 4983: Seite 2, 1000 Ergebnisse
Sensor 29695: Seite 1, 1000 Ergebnisse
Sensor 29695: Seite 2, 1000 Ergebnisse
Sensor 29695: Seite 3, 694 Ergebnisse
Sensor 28991: Seite 1, 1000 Ergebnisse
Sensor 28991: Seite 2, 1000 Ergebnisse
Sensor 28991: Seite 3, 793 Ergebnisse
Sensor 29838: Seite 1, 1000 Ergebnisse
Sensor 29838: Seite 2, 1000 Ergebnisse
Sensor 29838: Seite 3, 676 Ergebnisse
Sensor 7814: Seite 1, 1000 Ergebnisse
Sensor 7814: Seite 2, 1000 Ergebnisse
Sensor 1296216: Seite 1, 654 Ergebnisse
Sensor 1296207: Seite 1, 352 Ergebnisse
Sensor 1296138: Seite 1, 782 Ergebnisse
Sensor 1296338: Seite 1, 498 Ergebnisse
Sensor 1296256: Seite 1, 763 Ergebnisse
Sensor 1296024: Seite 1, 601 Ergebnisse
Sensor 1295945: Seite 1, 778 Ergebnisse
Sensor 1295981: Seite 1, 778 Ergebnisse
Sensor 1296105: Seite 1, 743 Ergebnisse
Sensor 1296109: Seite 1, 741 Ergebnisse
Sensor 1296199: Seite 1, 765 Ergebnisse
Sensor 1296008: Seite 1, 733 Ergebnisse
Sensor 1295908: Seite 1, 539 Ergebnisse
Sensor 1296291: Seite 1, 543 Ergebnisse
Sensor 1295916: Seite 1, 771 Ergebnisse
Sensor 1295930: Seite 1, 594 Ergebnisse
Sensor 1296179: Seite 1, 621 Ergebnisse
Sensor 1296283: Seite 1, 315 Ergebnisse
Sensor 1296124: Seite 1, 674 Ergebnisse
Sensor 1296047: Seite 1, 740 Ergebnisse
Sensor 1295989: Seite 1, 756 Ergebnisse
Sensor 1296004: Seite 1, 729 Ergebnisse
Sensor 1296072: Seite 1, 727 Ergebnisse
Sensor 1295993: Seite 1, 766 Ergebnisse
Sensor 1296324: Seite 1, 384 Ergebnisse
Sensor 1295966: Seite 1, 267 Ergebnisse
Sensor 1295961: Seite 1, 744 Ergebnisse
Sensor 1296055: Seite 1, 299 Ergebnisse
Sensor 1296252: Seite 1, 765 Ergebnisse
Sensor 1296320: Seite 1, 754 Ergebnisse
Sensor 1296101: Seite 1, 764 Ergebnisse
Sensor 1296212: Seite 1, 643 Ergebnisse
Sensor 1296287: Seite 1, 641 Ergebnisse
Sensor 1296032: Seite 1, 594 Ergebnisse
Sensor 1296152: Seite 1, 506 Ergebnisse
Sensor 1296195: Seite 1, 616 Ergebnisse
Sensor 1296000: Seite 1, 70 Ergebnisse
Sensor 1296142: Seite 1, 591 Ergebnisse
Sensor 1295972: Seite 1, 751 Ergebnisse
Sensor 1296309: Seite 1, 740 Ergebnisse
Sensor 1296187: Seite 1, 465 Ergebnisse
Sensor 1296237: Seite 1, 546 Ergebnisse
Sensor 1295957: Seite 1, 653 Ergebnisse
Sensor 1295953: Seite 1, 460 Ergebnisse
Sensor 1296093: Seite 1, 523 Ergebnisse
Sensor 1296203: Seite 1, 650 Ergebnisse
Sensor 1296271: Seite 1, 594 Ergebnisse
Sensor 1295926: Seite 1, 530 Ergebnisse
Sensor 1296051: Seite 1, 562 Ergebnisse
Sensor 1296043: Seite 1, 534 Ergebnisse
Sensor 1296156: Seite 1, 656 Ergebnisse
Sensor 1296328: Seite 1, 749 Ergebnisse
Sensor 1295977: Seite 1, 635 Ergebnisse
Sensor 1296017: Seite 1, 678 Ergebnisse
Sensor 1296275: Seite 1, 629 Ergebnisse
Sensor 1296267: Seite 1, 628 Ergebnisse
Sensor 1296039: Seite 1, 579 Ergebnisse
Sensor 1296089: Seite 1, 328 Ergebnisse
Sensor 1295903: Seite 1, 549 Ergebnisse
Sensor 1296164: Seite 1, 601 Ergebnisse
Sensor 1296076: Seite 1, 538 Ergebnisse
Sensor 1296084: Seite 1, 136 Ergebnisse
Sensor 1295912: Seite 1, 151 Ergebnisse
Sensor 1296225: Seite 1, 565 Ergebnisse
Sensor 1296129: Seite 1, 534 Ergebnisse
Sensor 1296080: Seite 1, 304 Ergebnisse
Sensor 1296116: Seite 1, 649 Ergebnisse
Sensor 1296353: Seite 1, 644 Ergebnisse
Sensor 1296233: Seite 1, 605 Ergebnisse
Sensor 1296229: Seite 1, 436 Ergebnisse
Sensor 1296241: Seite 1, 554 Ergebnisse
Sensor 1296313: Seite 1, 630 Ergebnisse
Sensor 1296070: Seite 1, 588 Ergebnisse
Sensor 1296097: Seite 1, 611 Ergebnisse
Sensor 1296340: Seite 1, 485 Ergebnisse
Sensor 1296345: Seite 1, 409 Ergebnisse
Sensor 1296013: Seite 1, 571 Ergebnisse
Sensor 1296279: Seite 1, 551 Ergebnisse
Sensor 1296183: Seite 1, 609 Ergebnisse
Sensor 1296060: Seite 1, 424 Ergebnisse
Sensor 1296248: Seite 1, 405 Ergebnisse
Sensor 1296191: Seite 1, 588 Ergebnisse
Sensor 1296176: Seite 1, 201 Ergebnisse
Sensor 1295920: Seite 1, 568 Ergebnisse
Sensor 1296335: Seite 1, 472 Ergebnisse
Sensor 1296349: Seite 1, 553 Ergebnisse
Sensor 1295924: Seite 1, 505 Ergebnisse
Sensor 1295934: Seite 1, 307 Ergebnisse
Sensor 1296299: Seite 1, 15 Ergebnisse
Sensor 1296171: Seite 1, 435 Ergebnisse
Sensor 1296221: Seite 1, 277 Ergebnisse
Sensor 1295942: Seite 1, 310 Ergebnisse
Sensor 1296127: Seite 1, 326 Ergebnisse
Sensor 1296306: Seite 1, 326 Ergebnisse
Sensor 1296133: Seite 1, 320 Ergebnisse
Sensor 1296263: Seite 1, 198 Ergebnisse
Sensor 1296160: Seite 1, 278 Ergebnisse
Sensor 1296028: Seite 1, 40 Ergebnisse
Sensor 30453: Seite 1, 1000 Ergebnisse
Sensor 30453: Seite 2, 124 Ergebnisse
Sensor 12913463: Seite 1, 207 Ergebnisse
Sensor 6933605: Seite 1, 895 Ergebnisse
Sensor 6612671: Seite 1, 832 Ergebnisse
Sensor 6955371: Seite 1, 893 Ergebnisse
Sensor 1792043: Seite 1, 1000 Ergebnisse
Sensor 1792043: Seite 2, 185 Ergebnisse
Sensor 1792083: Seite 1, 1000 Ergebnisse
Sensor 1792083: Seite 2, 293 Ergebnisse
Sensor 1304516: Seite 1, 1000 Ergebnisse
Sensor 1304516: Seite 2, 688 Ergebnisse
Sensor 1304504: Seite 1, 537 Ergebnisse
Sensor 1304507: Seite 1, 1000 Ergebnisse
Sensor 1304507: Seite 2, 451 Ergebnisse
Sensor 1304559: Seite 1, 566 Ergebnisse
Sensor 1339998: Seite 1, 109 Ergebnisse
Sensor 1304721: Seite 1, 1000 Ergebnisse
Sensor 1304721: Seite 2, 442 Ergebnisse
Sensor 1304607: Seite 1, 1000 Ergebnisse
Sensor 1304607: Seite 2, 341 Ergebnisse
Sensor 1304680: Seite 1, 1000 Ergebnisse
Sensor 1304680: Seite 2, 246 Ergebnisse
Sensor 1557241: Seite 1, 486 Ergebnisse
Sensor 1666368: Seite 1, 1000 Ergebnisse
Sensor 1666368: Seite 2, 247 Ergebnisse
Sensor 13717234: Seite 1, 216 Ergebnisse
Sensor 12716244: Seite 1, 322 Ergebnisse
Sensor 12090599: Seite 1, 369 Ergebnisse
Sensor 12129805: Seite 1, 386 Ergebnisse
Sensor 1304722: Seite 1, 1000 Ergebnisse
Sensor 1304722: Seite 2, 347 Ergebnisse
Sensor 1304713: Seite 1, 1000 Ergebnisse
Sensor 1304713: Seite 2, 346 Ergebnisse
Sensor 1304737: Seite 1, 1000 Ergebnisse
Sensor 1304737: Seite 2, 624 Ergebnisse
Sensor 1304734: Seite 1, 1000 Ergebnisse
Sensor 1304734: Seite 2, 683 Ergebnisse
Sensor 7771087: Seite 1, 755 Ergebnisse
Sensor 10416144: Seite 1, 519 Ergebnisse
Sensor 12098616: Seite 1, 346 Ergebnisse
Sensor 10975087: Seite 1, 406 Ergebnisse
Sensor 10601409: Seite 1, 455 Ergebnisse
Sensor 11268004: Seite 1, 416 Ergebnisse
Sensor 1304849: Seite 1, 332 Ergebnisse
Sensor 7799668: Seite 1, 733 Ergebnisse
Sensor 10144201: Seite 1, 535 Ergebnisse
Sensor 1304613: Seite 1, 929 Ergebnisse
Sensor 1304632: Seite 1, 1000 Ergebnisse
Sensor 1304632: Seite 2, 58 Ergebnisse
Sensor 1304686: Seite 1, 1000 Ergebnisse
Sensor 1304686: Seite 2, 323 Ergebnisse
Sensor 1304862: Seite 1, 1000 Ergebnisse
Sensor 1304862: Seite 2, 234 Ergebnisse
Sensor 1304619: Seite 1, 779 Ergebnisse
Sensor 1304757: Seite 1, 1000 Ergebnisse
Sensor 1304757: Seite 2, 206 Ergebnisse
Sensor 1304669: Seite 1, 1000 Ergebnisse
Sensor 1304669: Seite 2, 279 Ergebnisse
Sensor 1304614: Seite 1, 1000 Ergebnisse
Sensor 1304614: Seite 2, 316 Ergebnisse
Sensor 1304683: Seite 1, 1000 Ergebnisse
Sensor 1304683: Seite 2, 245 Ergebnisse
Sensor 1304886: Seite 1, 1000 Ergebnisse
Sensor 1304886: Seite 2, 34 Ergebnisse
Sensor 1953963: Seite 1, 603 Ergebnisse
Sensor 1304653: Seite 1, 797 Ergebnisse
Sensor 1304660: Seite 1, 983 Ergebnisse
Sensor 1304679: Seite 1, 942 Ergebnisse
Sensor 2235091: Seite 1, 6 Ergebnisse
Sensor 1304584: Seite 1, 671 Ergebnisse
Sensor 1304670: Seite 1, 607 Ergebnisse
Sensor 1304588: Seite 1, 250 Ergebnisse
Sensor 1304814: Seite 1, 1000 Ergebnisse
Sensor 1304814: Seite 2, 158 Ergebnisse
Sensor 1307207: Seite 1, 860 Ergebnisse
Sensor 1356319: Seite 1, 1000 Ergebnisse
Sensor 1356319: Seite 2, 304 Ergebnisse
Sensor 1334916: Seite 1, 1000 Ergebnisse
Sensor 1334916: Seite 2, 173 Ergebnisse
Sensor 1561901: Seite 1, 1000 Ergebnisse
Sensor 1561901: Seite 2, 346 Ergebnisse
Sensor 2009625: Seite 1, 522 Ergebnisse
Sensor 5079237: Seite 1, 1000 Ergebnisse
Sensor 5079237: Seite 2, 1 Ergebnisse
Sensor 6395783: Seite 1, 223 Ergebnisse
Sensor 5114392: Seite 1, 719 Ergebnisse
Sensor 6530154: Seite 1, 852 Ergebnisse
Sensor 6530346: Seite 1, 101 Ergebnisse
Sensor 6738569: Seite 1, 667 Ergebnisse
Sensor 6794730: Seite 1, 793 Ergebnisse
Sensor 6905962: Seite 1, 781 Ergebnisse
Sensor 6912437: Seite 1, 310 Ergebnisse
Sensor 6971135: Seite 1, 2 Ergebnisse
Sensor 6977044: Seite 1, 32 Ergebnisse
Sensor 6977036: Seite 1, 13 Ergebnisse
Sensor 7251982: Seite 1, 833 Ergebnisse
Sensor 7267676: Seite 1, 57 Ergebnisse
Sensor 7267678: Seite 1, 34 Ergebnisse
Sensor 7296919: Seite 1, 342 Ergebnisse
Sensor 7337003: Seite 1, 820 Ergebnisse
Sensor 7349462: Seite 1, 807 Ergebnisse
Sensor 7374349: Seite 1, 27 Ergebnisse
Sensor 7515649: Seite 1, 1 Ergebnisse
Sensor 7544409: Seite 1, 718 Ergebnisse
Sensor 7779243: Seite 1, 8 Ergebnisse
Sensor 7897356: Seite 1, 709 Ergebnisse
Sensor 7897357: Seite 1, 511 Ergebnisse
Sensor 7897363: Seite 1, 511 Ergebnisse
Sensor 7897367: Seite 1, 499 Ergebnisse
Sensor 7897374: Seite 1, 709 Ergebnisse
Sensor 7897359: Seite 1, 511 Ergebnisse
Sensor 7897362: Seite 1, 593 Ergebnisse
Sensor 7897361: Seite 1, 591 Ergebnisse
Sensor 7897368: Seite 1, 591 Ergebnisse
Sensor 7897335: Seite 1, 276 Ergebnisse
Sensor 7897344: Seite 1, 198 Ergebnisse
Sensor 7933691: Seite 1, 667 Ergebnisse
Sensor 7981356: Seite 1, 693 Ergebnisse
Sensor 8622289: Seite 1, 675 Ergebnisse
Sensor 8656561: Seite 1, 672 Ergebnisse
Sensor 8811685: Seite 1, 639 Ergebnisse
Sensor 9131767: Seite 1, 14 Ergebnisse
Sensor 9224230: Seite 1, 627 Ergebnisse
Sensor 9224190: Seite 1, 312 Ergebnisse
Sensor 9310452: Seite 1, 525 Ergebnisse
Sensor 9339665: Seite 1, 71 Ergebnisse
Sensor 9483707: Seite 1, 605 Ergebnisse
Sensor 9502772: Seite 1, 263 Ergebnisse
Sensor 9502776: Seite 1, 263 Ergebnisse
Sensor 9526870: Seite 1, 522 Ergebnisse
Sensor 9796763: Seite 1, 561 Ergebnisse
Sensor 9877951: Seite 1, 572 Ergebnisse
Sensor 9915924: Seite 1, 130 Ergebnisse
Sensor 9915912: Seite 1, 130 Ergebnisse
Sensor 9915909: Seite 1, 130 Ergebnisse
Sensor 9965662: Seite 1, 565 Ergebnisse
Sensor 10050517: Seite 1, 1 Ergebnisse
Sensor 10060780: Seite 1, 557 Ergebnisse
Sensor 10081803: Seite 1, 520 Ergebnisse
Sensor 10090974: Seite 1, 553 Ergebnisse
Sensor 10256569: Seite 1, 525 Ergebnisse
Sensor 10432372: Seite 1, 519 Ergebnisse
Sensor 10433364: Seite 1, 441 Ergebnisse
Sensor 10543394: Seite 1, 83 Ergebnisse
Sensor 10563649: Seite 1, 1 Ergebnisse
Sensor 10563650: Seite 1, 1 Ergebnisse
Sensor 10563647: Seite 1, 1 Ergebnisse
Sensor 10563648: Seite 1, 1 Ergebnisse
Sensor 10660054: Seite 1, 501 Ergebnisse
Sensor 10747047: Seite 1, 485 Ergebnisse
Sensor 10849042: Seite 1, 484 Ergebnisse
Sensor 10911603: Seite 1, 25 Ergebnisse
Sensor 10932702: Seite 1, 473 Ergebnisse
Sensor 10984025: Seite 1, 449 Ergebnisse
Sensor 10986430: Seite 1, 464 Ergebnisse
Sensor 11029807: Seite 1, 468 Ergebnisse
Sensor 11200694: Seite 1, 8 Ergebnisse
Sensor 11222033: Seite 1, 68 Ergebnisse
Sensor 11245170: Seite 1, 443 Ergebnisse
Sensor 11280080: Seite 1, 63 Ergebnisse
Sensor 11324944: Seite 1, 45 Ergebnisse
Sensor 11370869: Seite 1, 438 Ergebnisse
Sensor 11383552: Seite 1, 75 Ergebnisse
Sensor 11406056: Seite 1, 434 Ergebnisse
Sensor 11509044: Seite 1, 339 Ergebnisse
Sensor 11599591: Seite 1, 446 Ergebnisse
Sensor 11599596: Seite 1, 129 Ergebnisse
Sensor 11599579: Seite 1, 446 Ergebnisse
Sensor 11599598: Seite 1, 446 Ergebnisse
Sensor 11599597: Seite 1, 446 Ergebnisse
Sensor 11599593: Seite 1, 446 Ergebnisse
Sensor 11599578: Seite 1, 446 Ergebnisse
Sensor 11599585: Seite 1, 446 Ergebnisse
Sensor 11599589: Seite 1, 446 Ergebnisse
Sensor 11599575: Seite 1, 446 Ergebnisse
Sensor 11599594: Seite 1, 446 Ergebnisse
Sensor 11599587: Seite 1, 446 Ergebnisse
Sensor 11599582: Seite 1, 446 Ergebnisse
Sensor 11599590: Seite 1, 446 Ergebnisse
Sensor 11599577: Seite 1, 446 Ergebnisse
Sensor 11599574: Seite 1, 418 Ergebnisse
Sensor 11599586: Seite 1, 446 Ergebnisse
Sensor 11599588: Seite 1, 418 Ergebnisse
Sensor 11599576: Seite 1, 446 Ergebnisse
Sensor 11599573: Seite 1, 446 Ergebnisse
Sensor 11599595: Seite 1, 446 Ergebnisse
Sensor 11599583: Seite 1, 437 Ergebnisse
Sensor 11599592: Seite 1, 446 Ergebnisse
Sensor 11599581: Seite 1, 446 Ergebnisse
Sensor 11599949: Seite 1, 446 Ergebnisse
Sensor 11599951: Seite 1, 446 Ergebnisse
Sensor 11599950: Seite 1, 444 Ergebnisse
Sensor 11657641: Seite 1, 413 Ergebnisse
Sensor 11698456: Seite 1, 2 Ergebnisse
Sensor 11722221: Seite 1, 437 Ergebnisse
Sensor 11741710: Seite 1, 403 Ergebnisse
Sensor 11763465: Seite 1, 400 Ergebnisse
Sensor 11796193: Seite 1, 402 Ergebnisse
Sensor 11798699: Seite 1, 381 Ergebnisse
Sensor 11818241: Seite 1, 400 Ergebnisse
Sensor 12151587: Seite 1, 375 Ergebnisse
Sensor 12178096: Seite 1, 383 Ergebnisse
Sensor 12177952: Seite 1, 353 Ergebnisse
Sensor 12177944: Seite 1, 198 Ergebnisse
Sensor 12255842: Seite 1, 14 Ergebnisse
Sensor 12394602: Seite 1, 337 Ergebnisse
Sensor 12460933: Seite 1, 353 Ergebnisse
Sensor 12514122: Seite 1, 4 Ergebnisse
Sensor 12592751: Seite 1, 340 Ergebnisse
Sensor 12592754: Seite 1, 340 Ergebnisse
Sensor 12592753: Seite 1, 340 Ergebnisse
Sensor 12592752: Seite 1, 340 Ergebnisse
Sensor 12640990: Seite 1, 326 Ergebnisse
Sensor 12611189: Seite 1, 299 Ergebnisse
Sensor 12667317: Seite 1, 2 Ergebnisse
Sensor 12667931: Seite 1, 50 Ergebnisse
Sensor 12736690: Seite 1, 309 Ergebnisse
Sensor 12740085: Seite 1, 53 Ergebnisse
Sensor 12750913: Seite 1, 293 Ergebnisse
Sensor 12814530: Seite 1, 317 Ergebnisse
Sensor 12872712: Seite 1, 254 Ergebnisse
Sensor 12915156: Seite 1, 283 Ergebnisse
Sensor 12926970: Seite 1, 9 Ergebnisse
Sensor 12916492: Seite 1, 296 Ergebnisse
Sensor 12973500: Seite 1, 293 Ergebnisse
Sensor 12973502: Seite 1, 298 Ergebnisse
Sensor 13117416: Seite 1, 283 Ergebnisse
Sensor 13119187: Seite 1, 283 Ergebnisse
Sensor 13462324: Seite 1, 234 Ergebnisse
Sensor 13509665: Seite 1, 209 Ergebnisse
Sensor 13875548: Seite 1, 197 Ergebnisse
Sensor 13886562: Seite 1, 182 Ergebnisse
Sensor 13893646: Seite 1, 184 Ergebnisse
Sensor 13963538: Seite 1, 146 Ergebnisse
Sensor 14085098: Seite 1, 157 Ergebnisse
Sensor 14099778: Seite 1, 156 Ergebnisse
Sensor 14107197: Seite 1, 169 Ergebnisse
Sensor 14124221: Seite 1, 1 Ergebnisse
Sensor 14153846: Seite 1, 154 Ergebnisse
Sensor 14153856: Seite 1, 146 Ergebnisse
Sensor 14153861: Seite 1, 163 Ergebnisse
Sensor 14153936: Seite 1, 158 Ergebnisse
Sensor 14152335: Seite 1, 163 Ergebnisse
Sensor 14152355: Seite 1, 163 Ergebnisse
Sensor 14383281: Seite 1, 8 Ergebnisse
Sensor 14183636: Seite 1, 136 Ergebnisse
Sensor 14244676: Seite 1, 6 Ergebnisse
Sensor 14262772: Seite 1, 151 Ergebnisse
Sensor 14269383: Seite 1, 150 Ergebnisse
Sensor 14269378: Seite 1, 111 Ergebnisse
Sensor 14313795: Seite 1, 86 Ergebnisse
Sensor 14349086: Seite 1, 141 Ergebnisse
Sensor 14385076: Seite 1, 137 Ergebnisse
Sensor 14407778: Seite 1, 134 Ergebnisse
Sensor 14425510: Seite 1, 132 Ergebnisse
Sensor 14443357: Seite 1, 130 Ergebnisse
Sensor 14445094: Seite 1, 130 Ergebnisse
Sensor 14559242: Seite 1, 28 Ergebnisse
Sensor 14611560: Seite 1, 2 Ergebnisse
Sensor 14617329: Seite 1, 109 Ergebnisse
Sensor 14643021: Seite 1, 1 Ergebnisse
Sensor 14661310: Seite 1, 40 Ergebnisse
Sensor 14662675: Seite 1, 104 Ergebnisse
Sensor 14667506: Seite 1, 48 Ergebnisse
Sensor 14675917: Seite 1, 35 Ergebnisse
Sensor 14723916: Seite 1, 69 Ergebnisse
Sensor 14737543: Seite 1, 94 Ergebnisse
Sensor 14745619: Seite 1, 87 Ergebnisse
Sensor 14816074: Seite 1, 85 Ergebnisse
Sensor 14922919: Seite 1, 70 Ergebnisse
Sensor 14932672: Seite 1, 25 Ergebnisse
Sensor 14932677: Seite 1, 30 Ergebnisse
Sensor 14945826: Seite 1, 71 Ergebnisse
Sensor 14983967: Seite 1, 39 Ergebnisse
192572

[{'date': '2016-01-30', 'value': 6.5},
 {'date': '2016-01-31', 'value': 8.521739130434783},
 {'date': '2016-02-01', 'value': 9.333333333333334},
 {'date': '2016-02-02', 'value': 10.85},
 {'date': '2016-02-03', 'value': 9.3},
 {'date': '2016-02-04', 'value': 10.045454545454545},
 {'date': '2016-02-05', 'value': 11.25},
 {'date': '2016-02-06', 'value': 9.583333333333334},
 {'date': '2016-02-07', 'value': 9.208333333333334},
 {'date': '2016-02-08', 'value': 8.91304347826087},
 {'date': '2016-02-09', 'value': 10.894736842105264},
 {'date': '2021-04-30', 'value': 9.576923076923077},
 {'date': '2021-05-01', 'value': 16.171428571428574},
 {'date': '2021-05-02', 'value': 15.4},
 {'date': '2021-05-03', 'value': 6.5},
 {'date': '2021-05-04', 'value': 3.049999999999999},
 {'date': '2021-05-05', 'value': 3.390909090909091},
 {'date': '2021-05-06', 'value': 5.1761904761904765},
 {'date': '2021-05-07', 'value': 5.105263157894736},
 {'date': '2021-05-08', 'value': 5.61},
 {'date': '2021-05-10', 'value': 4.283333333333333},
 {'date': '2021-05-12', 'value': 5.3055555555555545},
 {'date': '2021-05-13', 'value': 8.683333333333332},
 {'date': '2021-05-14', 'value': 11.090476190476192},
 {'date': '2021-05-15', 'value': 8.09},
 {'date': '2021-05-16', 'value': 5.057142857142857},
 {'date': '2021-05-17', 'value': 6.147619047619047},
 {'date': '2021-05-18', 'value': 6.22},
 {'date': '2021-05-19', 'value': 3.435},
 {'date': '2021-05-20', 'value': 4.414285714285715},
 {'date': '2021-05-22', 'value': 3.042857142857143},
 {'date': '2021-05-25', 'value': 3.5714285714285707},
 {'date': '2021-05-28', 'value': 12.736842105263158},
 {'date': '2021-05-29', 'value': 14.327272727272724},
 {'date': '2021-05-30', 'value': 14.8},
 {'date': '2021-05-31', 'value': 15.364999999999998},
 {'date': '2021-06-01', 'value': 19.0},
 {'date': '2021-06-02', 'value': 13.559999999999999},
 {'date': '2021-06-03', 'value': 12.542857142857141},
 {'date': '2021-06-04', 'value': 8.531818181818183},
 {'date': '2021-06-05', 'value': 10.692307692307695},
 {'date': '2021-06-06', 'value': 6.526666666666666},
 {'date': '2021-06-07', 'value': 5.29},
 {'date': '2021-06-08', 'value': 6.423529411764704},
 {'date': '2021-06-10', 'value': 4.890476190476191},
 {'date': '2021-06-11', 'value': 6.733333333333333},
 {'date': '2021-06-12', 'value': 6.810526315789472},
 {'date': '2021-06-13', 'value': 10.415789473684212},
 {'date': '2021-06-14', 'value': 7.863157894736844},
 {'date': '2021-06-15', 'value': 7.105555555555554},
 {'date': '2021-06-17', 'value': 12.888888888888891},
 {'date': '2021-06-18', 'value': 3.9142857142857137},
 {'date': '2021-06-19', 'value': 4.50952380952381},
 {'date': '2021-06-20', 'value': 5.352380952380952},
 {'date': '2021-06-21', 'value': 5.719047619047619},
 {'date': '2021-06-22', 'value': 6.8050000000000015},
 {'date': '2021-06-23', 'value': 7.6428571428571415},
 {'date': '2021-06-24', 'value': 12.584615384615384},
 {'date': '2021-06-25', 'value': 4.604761904761905},
 {'date': '2021-06-26', 'value': 9.379999999999999},
 {'date': '2021-06-27', 'value': 19.336842105263155},
 {'date': '2021-06-28', 'value': 10.085714285714285},
 {'date': '2021-06-29', 'value': 10.79047619047619},
 {'date': '2021-07-01', 'value': 11.0},
 {'date': '2021-07-02', 'value': 13.911764705882355},
 {'date': '2021-07-03', 'value': 8.02},
 {'date': '2021-07-04', 'value': 3.8142857142857145},
 {'date': '2021-07-05', 'value': 5.184210526315789},
 {'date': '2021-07-06', 'value': 3.4764705882352938},
 {'date': '2021-07-07', 'value': 6.35},
 {'date': '2021-07-08', 'value': 5.858823529411764},
 {'date': '2021-07-09', 'value': 7.910000000000001},
 {'date': '2021-07-13', 'value': 12.323809523809526},
 {'date': '2021-07-14', 'value': 7.561904761904763},
 {'date': '2021-07-15', 'value': 5.623076923076923},
 {'date': '2021-07-16', 'value': 8.315},
 {'date': '2021-07-17', 'value': 5.033333333333333},
 {'date': '2021-07-18', 'value': 8.471428571428572},
 {'date': '2021-07-19', 'value': 10.91578947368421},
 {'date': '2021-07-20', 'value': 12.735},
 {'date': '2021-07-22', 'value': 24.10952380952381},
 {'date': '2021-07-23', 'value': 9.504999999999999},
 {'date': '2021-07-24', 'value': 18.114285714285714},
 {'date': '2021-07-25', 'value': 30.0},
 {'date': '2021-08-03', 'value': 6.499999999999998},
 {'date': '2021-08-04', 'value': 10.666666666666666},
 {'date': '2021-08-05', 'value': 5.939999999999999},
 {'date': '2021-08-06', 'value': 3.9529411764705875},
 {'date': '2021-08-07', 'value': 3.068421052631579},
 {'date': '2021-08-08', 'value': 5.8},
 {'date': '2021-08-09', 'value': 4.228571428571429},
 {'date': '2021-08-10', 'value': 6.119047619047619},
 {'date': '2021-08-11', 'value': 5.030000000000001},
 {'date': '2021-08-12', 'value': 5.281818181818182},
 {'date': '2021-08-13', 'value': 7.461904761904761},
 {'date': '2021-08-14', 'value': 7.4863636363636346},
 {'date': '2021-08-15', 'value': 5.231818181818182},
 {'date': '2021-08-16', 'value': 11.635000000000002},
 {'date': '2021-08-17', 'value': 4.861904761904761},
 {'date': '2021-08-18', 'value': 3.8857142857142852},
 {'date': '2021-08-19', 'value': 4.35},
 {'date': '2021-08-20', 'value': 2.5999999999999996},
 {'date': '2021-08-21', 'value': 6.476470588235294},
 {'date': '2021-08-22', 'value': 5.749999999999999},
 {'date': '2021-08-23', 'value': 7.078571428571428},
 {'date': '2021-08-24', 'value': 6.321052631578948},
 {'date': '2021-08-25', 'value': 3.8190476190476192},
 {'date': '2021-08-26', 'value': 6.189473684210526},
 {'date': '2021-08-27', 'value': 7.338095238095238},
 {'date': '2021-08-28', 'value': 7.366666666666666},
 {'date': '2021-08-29', 'value': 6.612500000000001},
 {'date': '2021-08-30', 'value': 4.8},
 {'date': '2021-08-31', 'value': 6.545},
 {'date': '2021-09-01', 'value': 6.723529411764708},
 {'date': '2021-09-02', 'value': 10.147058823529411},
 {'date': '2021-09-03', 'value': 15.50952380952381},
 {'date': '2021-09-04', 'value': 16.48},
 {'date': '2021-09-05', 'value': 19.290909090909096},
 {'date': '2021-09-06', 'value': 25.417647058823526},
 {'date': '2021-09-07', 'value': 36.49999999999999},
 {'date': '2021-09-08', 'value': 35.50000000000001},
 {'date': '2021-09-09', 'value': 9.854545454545455},
 {'date': '2021-09-10', 'value': 5.314285714285714},
 {'date': '2021-09-11', 'value': 6.255555555555556},
 {'date': '2021-09-12', 'value': 6.1499999999999995},
 {'date': '2021-09-13', 'value': 5.976190476190476},
 {'date': '2021-09-14', 'value': 16.595},
 {'date': '2021-09-15', 'value': 7.753846153846155},
 {'date': '2021-09-16', 'value': 11.621052631578946},
 {'date': '2021-09-17', 'value': 7.246153846153847},
 {'date': '2021-09-18', 'value': 14.718181818181819},
 {'date': '2021-09-19', 'value': 29.85789473684211},
 {'date': '2021-09-20', 'value': 7.342857142857142},
 {'date': '2021-09-21', 'value': 12.305882352941174},
 {'date': '2021-09-22', 'value': 9.368421052631579},
 {'date': '2021-09-23', 'value': 4.86842105263158},
 {'date': '2021-09-24', 'value': 5.994736842105262},
 {'date': '2021-09-25', 'value': 8.518181818181818},
 {'date': '2021-09-26', 'value': 16.56},
 {'date': '2021-09-27', 'value': 2.3947368421052637},
 {'date': '2021-09-28', 'value': 4.2666666666666675},
 {'date': '2021-09-29', 'value': 1.1},
 {'date': '2021-09-30', 'value': 4.516666666666667},
 {'date': '2021-10-01', 'value': 2.8952380952380956},
 {'date': '2021-10-02', 'value': 4.633333333333334},
 {'date': '2021-10-03', 'value': 2.5421052631578953},
 {'date': '2021-10-04', 'value': 3.4647058823529413},
 {'date': '2021-10-05', 'value': 2.3380952380952382},
 {'date': '2021-10-06', 'value': 4.300000000000001},
 {'date': '2021-10-07', 'value': 7.111111111111111},
 {'date': '2021-10-08', 'value': 6.094736842105263},
 {'date': '2021-10-09', 'value': 30.52777777777778},
 {'date': '2021-10-10', 'value': 20.520000000000003},
 {'date': '2021-10-11', 'value': 6.61578947368421},
 {'date': '2021-10-12', 'value': 8.766666666666666},
 {'date': '2021-10-13', 'value': 6.4},
 {'date': '2021-10-14', 'value': 10.199999999999998},
 {'date': '2021-10-15', 'value': 7.252380952380953},
 {'date': '2021-10-16', 'value': 11.325},
 {'date': '2021-10-17', 'value': 9.99047619047619},
 {'date': '2021-10-18', 'value': 8.595454545454546},
 {'date': '2021-10-19', 'value': 11.713636363636367},
 {'date': '2021-10-20', 'value': 5.7444444444444445},
 {'date': '2021-10-21', 'value': 4.13},
 {'date': '2021-10-22', 'value': 3.8190476190476197},
 {'date': '2021-10-23', 'value': 4.568181818181818},
 {'date': '2021-10-24', 'value': 3.8764705882352946},
 {'date': '2021-10-25', 'value': 6.152380952380954},
 {'date': '2021-10-26', 'value': 4.6818181818181825},
 {'date': '2021-10-27', 'value': 3.5499999999999994},
 {'date': '2021-10-28', 'value': 5.931578947368419},
 {'date': '2021-10-29', 'value': 8.0},
 {'date': '2021-10-30', 'value': 4.141176470588235},
 {'date': '2021-10-31', 'value': 4.883333333333334},
 {'date': '2021-11-01', 'value': 5.054545454545454},
 {'date': '2021-11-02', 'value': 7.8100000000000005},
 {'date': '2021-11-03', 'value': 15.057894736842107},
 {'date': '2021-11-04', 'value': 4.585714285714286},
 {'date': '2021-11-05', 'value': 15.959090909090916},
 {'date': '2021-11-06', 'value': 7.327272727272727},
 {'date': '2021-11-07', 'value': 9.695454545454545},
 {'date': '2021-11-08', 'value': 11.372727272727273},
 {'date': '2021-11-09', 'value': 5.152380952380952},
 {'date': '2021-11-10', 'value': 5.829411764705882},
 {'date': '2021-11-11', 'value': 7.247368421052631},
 {'date': '2021-11-12', 'value': 8.353333333333333},
 {'date': '2021-11-13', 'value': 6.0590909090909095},
 {'date': '2021-11-14', 'value': 7.736842105263159},
 {'date': '2021-11-15', 'value': 15.76153846153846},
 {'date': '2021-11-16', 'value': 12.2},
 {'date': '2021-11-21', 'value': 4.3},
 {'date': '2021-11-22', 'value': 8.136363636363637},
 {'date': '2021-11-23', 'value': 19.93913043478261},
 {'date': '2021-11-24', 'value': 22.008695652173916},
 {'date': '2021-11-25', 'value': 9.578260869565216},
 {'date': '2021-11-26', 'value': 4.99090909090909},
 {'date': '2021-11-27', 'value': 5.440909090909091},
 {'date': '2021-11-29', 'value': 14.613043478260868},
 {'date': '2021-11-30', 'value': 4.582608695652174},
 {'date': '2021-12-01', 'value': 3.5181818181818176},
 {'date': '2021-12-02', 'value': 7.363636363636363},
 {'date': '2021-12-03', 'value': 9.350000000000001},
 {'date': '2021-12-04', 'value': 8.563636363636364},
 {'date': '2021-12-05', 'value': 3.786363636363636},
 {'date': '2021-12-06', 'value': 8.100000000000001},
 {'date': '2021-12-07', 'value': 5.177777777777778},
 {'date': '2021-12-08', 'value': 6.818181818181818},
 {'date': '2021-12-09', 'value': 6.88695652173913},
 {'date': '2021-12-10', 'value': 5.736363636363636},
 {'date': '2021-12-11', 'value': 7.895454545454545},
 {'date': '2021-12-12', 'value': 4.54090909090909},
 {'date': '2021-12-13', 'value': 3.9},
 {'date': '2021-12-14', 'value': 7.172727272727275},
 {'date': '2021-12-15', 'value': 5.0249999999999995},
 {'date': '2021-12-16', 'value': 8.950000000000001},
 {'date': '2021-12-17', 'value': 13.008695652173913},
 {'date': '2021-12-18', 'value': 13.26818181818182},
 {'date': '2021-12-19', 'value': 6.763636363636363},
 {'date': '2021-12-20', 'value': 7.368181818181819},
 {'date': '2021-12-21', 'value': 17.719047619047622},
 {'date': '2021-12-22', 'value': 20.535000000000004},
 {'date': '2021-12-23', 'value': 16.943478260869565},
 {'date': '2021-12-24', 'value': 10.182608695652174},
 {'date': '2021-12-25', 'value': 12.734782608695653},
 {'date': '2021-12-26', 'value': 19.271428571428572},
 {'date': '2021-12-27', 'value': 6.16875},
 {'date': '2021-12-29', 'value': 5.247826086956521},
 {'date': '2021-12-30', 'value': 4.360869565217392},
 {'date': '2021-12-31', 'value': 7.978260869565219},
 {'date': '2022-01-01', 'value': 10.227272727272728},
 {'date': '2022-01-02', 'value': 3.2882352941176474},
 {'date': '2022-01-03', 'value': 7.554545454545454},
 {'date': '2022-01-04', 'value': 6.040909090909091},
 {'date': '2022-01-05', 'value': 8.534782608695652},
 {'date': '2022-01-06', 'value': 8.713043478260868},
 {'date': '2022-01-07', 'value': 4.340909090909092},
 {'date': '2022-01-08', 'value': 5.4565217391304355},
 {'date': '2022-01-09', 'value': 10.517391304347827},
 {'date': '2022-01-10', 'value': 15.40434782608696},
 {'date': '2022-01-11', 'value': 9.899999999999999},
 {'date': '2022-01-12', 'value': 20.526315789473685},
 {'date': '2022-01-13', 'value': 19.645454545454545},
 {'date': '2022-01-14', 'value': 24.845454545454547},
 {'date': '2022-01-15', 'value': 25.1},
 {'date': '2022-01-16', 'value': 17.690000000000005},
 {'date': '2022-01-17', 'value': 14.805263157894737},
 {'date': '2022-01-18', 'value': 21.860000000000003},
 {'date': '2022-01-19', 'value': 12.9},
 {'date': '2022-01-20', 'value': 9.868181818181817},
 {'date': '2022-01-21', 'value': 13.392857142857142},
 {'date': '2022-01-22', 'value': 13.936363636363637},
 {'date': '2022-01-23', 'value': 18.254545454545454},
 {'date': '2022-01-24', 'value': 24.574999999999996},
 {'date': '2022-01-25', 'value': 24.9},
 {'date': '2022-01-26', 'value': 21.200000000000003},
 {'date': '2022-01-28', 'value': 9.392857142857142},
 {'date': '2022-01-29', 'value': 3.342105263157895},
 {'date': '2022-01-30', 'value': 9.561904761904762},
 {'date': '2022-01-31', 'value': 6.721739130434782},
 {'date': '2022-02-01', 'value': 5.211111111111111},
 {'date': '2022-02-02', 'value': 5.745454545454546},
 {'date': '2022-02-03', 'value': 4.257142857142857},
 {'date': '2022-02-04', 'value': 3.6799999999999997},
 {'date': '2022-02-05', 'value': 5.02},
 {'date': '2022-02-06', 'value': 3.152173913043478},
 {'date': '2022-02-07', 'value': 16.405882352941177},
 {'date': '2022-02-08', 'value': 3.222222222222222},
 {'date': '2022-02-09', 'value': 4.454545454545455},
 {'date': '2022-02-10', 'value': 5.222222222222223},
 {'date': '2022-02-11', 'value': 8.56086956521739},
 {'date': '2022-02-12', 'value': 7.466666666666666},
 {'date': '2022-02-13', 'value': 7.6},
 {'date': '2022-02-14', 'value': 2.542857142857143},
 {'date': '2022-02-15', 'value': 4.250000000000001},
 {'date': '2022-02-16', 'value': 4.633333333333334},
 {'date': '2022-02-25', 'value': 31.8},
 {'date': '2022-02-27', 'value': 8.608695652173914},
 {'date': '2022-02-28', 'value': 10.319999999999999},
 {'date': '2022-03-03', 'value': 16.0},
 {'date': '2022-03-04', 'value': 14.083333333333332},
 {'date': '2022-03-05', 'value': 5.588235294117648},
 {'date': '2022-03-06', 'value': 6.827272727272727},
 {'date': '2022-03-07', 'value': 9.286666666666665},
 {'date': '2022-03-08', 'value': 25.049999999999997},
 {'date': '2022-03-09', 'value': 15.337499999999999},
 {'date': '2022-03-10', 'value': 16.772727272727277},
 {'date': '2022-03-11', 'value': 10.586363636363636},
 {'date': '2022-03-12', 'value': 5.490909090909091},
 {'date': '2022-03-13', 'value': 5.454545454545455},
 {'date': '2022-03-14', 'value': 6.972222222222223},
 {'date': '2022-03-15', 'value': 12.8375},
 {'date': '2022-03-16', 'value': 16.82857142857143},
 {'date': '2022-03-17', 'value': 4.578947368421053},
 {'date': '2022-03-18', 'value': 11.681818181818182},
 {'date': '2022-03-19', 'value': 16.66956521739131},
 {'date': '2022-03-20', 'value': 14.216666666666669},
 {'date': '2022-03-21', 'value': 40.44117647058823},
 {'date': '2022-03-22', 'value': 44.57500000000001},
 {'date': '2022-03-24', 'value': 78.8},
 {'date': '2022-03-25', 'value': 58.370000000000005},
 {'date': '2022-03-26', 'value': 37.7},
 {'date': '2022-03-27', 'value': 10.10714285714286},
 {'date': '2022-03-28', 'value': 12.6},
 {'date': '2022-03-29', 'value': 23.62},
 {'date': '2022-03-30', 'value': 24.35},
 {'date': '2022-03-31', 'value': 4.05},
 {'date': '2022-04-01', 'value': 3.51764705882353},
 {'date': '2022-04-02', 'value': 5.165},
 {'date': '2022-04-03', 'value': 8.31},
 {'date': '2022-04-04', 'value': 4.447368421052632},
 {'date': '2022-04-05', 'value': 4.043749999999999},
 {'date': '2022-04-06', 'value': 2.6894736842105265},
 {'date': '2022-04-07', 'value': 3.15},
 {'date': '2022-04-08', 'value': 5.247368421052633},
 {'date': '2022-04-09', 'value': 5.14},
 {'date': '2022-04-10', 'value': 6.431818181818182},
 {'date': '2022-04-11', 'value': 11.27142857142857},
 {'date': '2022-04-12', 'value': 15.36},
 {'date': '2022-04-13', 'value': 8.21904761904762},
 {'date': '2022-04-14', 'value': 6.726315789473684},
 {'date': '2022-04-15', 'value': 10.218749999999998},
 {'date': '2022-04-16', 'value': 29.19047619047619},
 {'date': '2022-04-17', 'value': 31.433333333333334},
 {'date': '2022-04-18', 'value': 10.123809523809525},
 {'date': '2022-04-19', 'value': 9.75},
 {'date': '2022-04-20', 'value': 14.821052631578949},
 {'date': '2022-04-21', 'value': 15.729999999999999},
 {'date': '2022-04-22', 'value': 13.27727272727273},
 {'date': '2022-04-23', 'value': 21.906666666666663},
 {'date': '2022-04-24', 'value': 17.417647058823526},
 {'date': '2022-04-25', 'value': 10.335294117647056},
 {'date': '2022-04-26', 'value': 7.515789473684211},
 {'date': '2022-04-27', 'value': 8.7},
 {'date': '2022-04-28', 'value': 12.035294117647059},
 {'date': '2022-04-29', 'value': 9.640000000000002},
 {'date': '2022-04-30', 'value': 10.115384615384615},
 {'date': '2022-05-01', 'value': 11.172727272727274},
 {'date': '2022-05-02', 'value': 14.054545454545456},
 {'date': '2022-05-03', 'value': 19.695},
 {'date': '2022-05-04', 'value': 18.23809523809524},
 {'date': '2022-05-05', 'value': 7.715000000000001},
 {'date': '2022-05-06', 'value': 9.668750000000001},
 {'date': '2022-05-07', 'value': 5.536842105263159},
 {'date': '2022-05-08', 'value': 8.968181818181817},
 {'date': '2022-05-09', 'value': 10.295238095238096},
 {'date': '2022-05-10', 'value': 6.605555555555556},
 {'date': '2022-05-11', 'value': 5.894999999999998},
 {'date': '2022-05-12', 'value': 5.827777777777777},
 {'date': '2022-05-13', 'value': 5.449999999999999},
 {'date': '2022-05-14', 'value': 10.48},
 {'date': '2022-05-15', 'value': 19.61904761904762},
 {'date': '2022-05-16', 'value': 14.461904761904762},
 {'date': '2022-05-17', 'value': 6.436842105263159},
 {'date': '2022-05-18', 'value': 3.6736842105263166},
 {'date': '2022-05-19', 'value': 5.391666666666667},
 {'date': '2022-05-20', 'value': 3.9499999999999993},
 {'date': '2022-05-31', 'value': 4.111764705882353},
 {'date': '2022-06-01', 'value': 5.505263157894736},
 {'date': '2022-06-02', 'value': 10.1},
 {'date': '2022-06-03', 'value': 12.749999999999998},
 {'date': '2022-06-04', 'value': 8.63684210526316},
 {'date': '2022-06-05', 'value': 11.957142857142856},
 {'date': '2022-06-06', 'value': 4.169230769230769},
 {'date': '2022-06-07', 'value': 5.4},
 {'date': '2022-06-13', 'value': 4.949999999999999},
 {'date': '2022-06-24', 'value': 11.216666666666667},
 {'date': '2022-06-25', 'value': 6.176470588235294},
 {'date': '2022-06-26', 'value': 5.4},
 {'date': '2022-06-27', 'value': 3.735294117647059},
 {'date': '2022-06-28', 'value': 4.652631578947369},
 {'date': '2022-06-29', 'value': 4.300000000000001},
 {'date': '2022-06-30', 'value': 4.272222222222222},
 {'date': '2022-07-01', 'value': 3.7888888888888883},
 {'date': '2022-07-02', 'value': 3.440909090909092},
 {'date': '2022-07-03', 'value': 3.1149999999999998},
 {'date': '2022-07-04', 'value': 3.836842105263158},
 {'date': '2022-07-05', 'value': 3.8388888888888886},
 {'date': '2022-07-06', 'value': 3.875000000000001},
 {'date': '2022-07-07', 'value': 3.9764705882352938},
 {'date': '2022-07-08', 'value': 8.652380952380952},
 {'date': '2022-07-09', 'value': 4.368181818181818},
 {'date': '2022-07-10', 'value': 5.336363636363635},
 {'date': '2022-07-11', 'value': 4.921428571428571},
 {'date': '2022-07-12', 'value': 5.657142857142858},
 {'date': '2022-07-13', 'value': 6.336842105263158},
 {'date': '2022-07-14', 'value': 7.66875},
 {'date': '2022-07-15', 'value': 4.68421052631579},
 {'date': '2022-07-16', 'value': 5.071428571428571},
 {'date': '2022-07-17', 'value': 4.70625},
 {'date': '2022-07-18', 'value': 9.930000000000001},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

uk_daily = (
    df_results.groupby("date")
              .agg(uk_pm25_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

uk_daily

           date  france_pm25_mean
0    2016-01-30          6.500000
1    2016-01-31          8.521739
2    2016-02-01          9.333333
3    2016-02-02         10.850000
4    2016-02-03          9.300000
...         ...               ...
3503 2026-02-24          7.027929
3504 2026-02-25         13.274358
3505 2026-02-26          5.476900
3506 2026-02-27          4.579939
3507 2026-02-28          5.554695

[3508 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
uk_daily[["date", "france_pm25_mean"]].to_csv(
    "daily_avg_uk_PM25.csv",
    index=False
)

# NO2

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "GB",   # only consider stations located in UK
    "parameters_id": 5,   # NO2
    #"monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)
df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_no2 = df_sorted

df_top_no2

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
0,60,Haringey Roadside,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 88, 'name': 'no2 µg/m³', 'parameter': ...","{'latitude': 51.5993, 'longitude': -0.068218}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.068218, 51.5993, -0.068218, 51.5993]",None,2016-01-30 01:00:00+00:00,2026-03-06 11:00:00+00:00
2,141,London Harlington,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 237, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.48879, 'longitude': -0.441614}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.441614, 51.48879, -0.441614, 51.48879]",None,2016-01-30 01:00:00+00:00,2026-03-06 11:00:00+00:00
5,148,Camden - Bloomsbury,Camden,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 238, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.52228699999999, 'longitude': -...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.125848, 51.52228699999999, -0.125848, 51.5...",None,2016-01-30 01:00:00+00:00,2026-03-06 11:00:00+00:00
6,149,Ealing Horn Lane,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 1304579, 'name': 'no2 µg/m³', 'paramet...","{'latitude': 51.51895, 'longitude': -0.265617}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.265617, 51.51895, -0.265617, 51.51895]",None,2016-01-30 01:00:00+00:00,2026-03-06 11:00:00+00:00
7,150,London Haringey Priory Park South,London,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 169, 'name': 'DEFRA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 231, 'name': 'no2 µg/m³', 'parameter':...","{'latitude': 51.584128, 'longitude': -0.125254}","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.125254, 51.584128, -0.125254, 51.584128]",None,2016-01-30 01:00:00+00:00,2026-03-06 11:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,4619882,Tower Hamlets - Millwall Park,Tower Hamlets,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13240506, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.4891342634, 'longitude': -0.01...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.0129769309432, 51.4891342634, -0.012976930...",None,2025-06-01 00:00:00+00:00,2026-03-06 10:00:00+00:00
310,4990521,Dartford - Town Centre,Dartford,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13537392, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.442557781389, 'longitude': 0.2...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[0.215950164318913, 51.442557781389, 0.2159501...",None,2025-07-04 00:00:00+00:00,2026-03-06 10:00:00+00:00
309,4955906,Westminster - Queens Park Gardens,Westminster,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13535111, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.5286629697555, 'longitude': -0...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.20875365618309, 51.5286629697555, -0.20875...",None,2025-07-04 10:00:00+00:00,2026-03-06 10:00:00+00:00
311,5738875,Kensington and Chelsea - Station Walk,Kensington and Chelsea,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14084832, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.5140517654184, 'longitude': -0...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.216518543773997, 51.5140517654184, -0.2165...",None,2025-09-07 00:00:00+00:00,2026-03-06 10:00:00+00:00
312,5738876,Kensington and Chelsea - Station Walk,Kensington and Chelsea,Europe/London,"{'id': 79, 'code': 'GB', 'name': 'United Kingd...","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 205, 'name': 'London Air Quality Network'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14124220, 'name': 'no2 µg/m³', 'parame...","{'latitude': 51.5140519844289, 'longitude': -0...","[{'id': 34, 'name': 'UK OGL ""Open Government L...","[-0.216532947379263, 51.5140519844289, -0.2165...",None,2025-09-15 00:00:00+00:00,2025-09-15 09:00:00+00:00

In [43]:
rows = []

for _, station in df_top_no2.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur NO2 behalten
        if sensor["parameter"]["id"] == 5:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_no2_sensors = pd.DataFrame(rows)

df_no2_sensors

     station_id                           station_name  sensor_id sensor_name
0            60                      Haringey Roadside         88   no2 µg/m³
1           141                      London Harlington        237   no2 µg/m³
2           148                    Camden - Bloomsbury        238   no2 µg/m³
3           149                       Ealing Horn Lane    1304579   no2 µg/m³
4           150      London Haringey Priory Park South        231   no2 µg/m³
..          ...                                    ...        ...         ...
308     4619882          Tower Hamlets - Millwall Park   13240506   no2 µg/m³
309     4990521                 Dartford - Town Centre   13537392   no2 µg/m³
310     4955906      Westminster - Queens Park Gardens   13535111   no2 µg/m³
311     5738875  Kensington and Chelsea - Station Walk   14084832   no2 µg/m³
312     5738876  Kensington and Chelsea - Station Walk   14124220   no2 µg/m³

[313 rows x 4 columns]

In [44]:
sensor_ids = df_no2_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

313

[88,
 237,
 238,
 1304579,
 231,
 256,
 239,
 241,
 242,
 255,
 251,
 1304749,
 250,
 258,
 233,
 234,
 709,
 2218,
 4416,
 4694,
 2217,
 5320,
 1210,
 1244,
 5304,
 7823,
 4267,
 5046,
 4238,
 4248,
 1557,
 5099,
 1741,
 1796,
 2500,
 3171,
 4342,
 4669,
 4149,
 4268,
 4192,
 4195,
 4220,
 4362,
 4266,
 4269,
 4272,
 4274,
 4276,
 4292,
 4339,
 4351,
 4384,
 4444,
 4475,
 4476,
 4490,
 4527,
 4530,
 4558,
 4575,
 4576,
 4679,
 4628,
 4641,
 4627,
 4652,
 4678,
 4674,
 4677,
 4703,
 4702,
 4711,
 4746,
 4756,
 5264,
 4784,
 4815,
 4802,
 5153,
 4822,
 4866,
 5076,
 4932,
 5093,
 4979,
 5057,
 5031,
 5005,
 5022,
 5030,
 5054,
 5087,
 5152,
 5160,
 5176,
 5238,
 5289,
 5316,
 4326,
 4477,
 4688,
 4426,
 4160,
 3787,
 4889,
 4468,
 4494,
 2642,
 4596,
 579,
 452,
 4896,
 262,
 3053,
 1373,
 5038,
 4209,
 4144,
 4229,
 4665,
 5101,
 4659,
 4790,
 4164,
 7818,
 7819,
 7822,
 7810,
 7817,
 7824,
 7811,
 7820,
 1304546,
 1304543,
 1304530,
 1304511,
 1304529,
 1304545,
 1304514,
 1304522,
 1304508,
 1304534,
 1304557,
 1304566,
 1304548,
 1304562,
 1304558,
 1304525,
 1304538,
 1304526,
 1304501,
 2686349,
 1304564,
 1304535,
 1304505,
 1304519,
 1304503,
 1304499,
 1304498,
 1304512,
 1304582,
 1304589,
 1304609,
 1304697,
 1304703,
 1304645,
 1304681,
 1304691,
 12747705,
 1304650,
 1304621,
 1304714,
 1304708,
 1304750,
 1304885,
 1304745,
 1304744,
 1304752,
 1304880,
 1304877,
 1304871,
 1304876,
 1304698,
 1304884,
 1304858,
 1304634,
 1304617,
 1304733,
 1304747,
 1304637,
 1304657,
 1304655,
 1304731,
 1304583,
 1304666,
 1304656,
 1304867,
 1304852,
 1304665,
 1304743,
 1304659,
 1304628,
 1304685,
 1304581,
 1304889,
 1304667,
 1304887,
 1304874,
 1304636,
 1304699,
 1304629,
 1304695,
 1304644,
 1304856,
 1304859,
 1304900,
 1305046,
 1304707,
 1304696,
 1304643,
 1304616,
 1304746,
 1304756,
 1304868,
 1304863,
 1304732,
 1304676,
 1304630,
 1304635,
 1304658,
 1304865,
 1304860,
 1304622,
 1304684,
 1304855,
 1304590,
 1304627,
 1304580,
 1304755,
 1304694,
 1304678,
 1304662,
 1304702,
 1304741,
 1304740,
 1312357,
 1310775,
 1310773,
 1310774,
 1329038,
 1561900,
 1561903,
 1561966,
 1702425,
 1652534,
 1839382,
 1923486,
 5079259,
 5079231,
 5079238,
 5079253,
 5079276,
 5079283,
 5079288,
 5079297,
 5079300,
 5079307,
 5079315,
 5079319,
 5079341,
 5079293,
 5079290,
 2382003,
 5111975,
 6824670,
 8622320,
 8622638,
 8622236,
 8622232,
 8622277,
 8622323,
 8622263,
 8622221,
 8622264,
 8622322,
 8622618,
 8622317,
 8622255,
 8622274,
 8622310,
 8622268,
 8622635,
 8622303,
 8622258,
 8622299,
 8622214,
 8622287,
 8622312,
 8622290,
 9909573,
 9909574,
 12151632,
 12630851,
 12747984,
 12915155,
 12960855,
 13125837,
 13240506,
 13537392,
 13535111,
 14084832,
 14124220]

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 1304579: Seite 1, 1000 Ergebnisse
Sensor 1304579: Seite 2, 540 Ergebnisse
Sensor 1304749: Seite 1, 716 Ergebnisse
Sensor 250: Seite 1, 179 Ergebnisse
Sensor 234: Seite 1, 1000 Ergebnisse
Sensor 234: Seite 2, 1000 Ergebnisse
Sensor 234: Seite 3, 1000 Ergebnisse
Sensor 234: Seite 4, 311 Ergebnisse
Sensor 709: Seite 1, 1000 Ergebnisse
Sensor 709: Seite 2, 1000 Ergebnisse
Sensor 709: Seite 3, 1000 Ergebnisse
Sensor 709: Seite 4, 196 Ergebnisse
Sensor 1210: Seite 1, 1000 Ergebnisse
Sensor 1210: Seite 2, 1000 Ergebnisse
Sensor 1210: Seite 3, 1000 Ergebnisse
Sensor 1210: Seite 4, 199 Ergebnisse
Sensor 4267: Seite 1, 1000 Ergebnisse
Sensor 4267: Seite 2, 1000 Ergebnisse
Sensor 5046: Seite 1, 1000 Ergebnisse
Sensor 5046: Seite 2, 1000 Ergebnisse
Sensor 4248: Seite 1, 1000 Ergebnisse
Sensor 4248: Seite 2, 1000 Ergebnisse
Sensor 1557: Seite 1, 1000 Ergebnisse
Sensor 1557: Seite 2, 1000 Ergebnisse
Sensor 4195: Seite 1, 1000 Ergebnisse
Sensor 4195: Seite 2, 1000 Ergebnisse
Sensor 4195: Seite 3, 1000 Ergebnisse
Sensor 4195: Seite 4, 431 Ergebnisse
Sensor 4679: Seite 1, 1000 Ergebnisse
Sensor 4679: Seite 2, 1000 Ergebnisse
Sensor 4679: Seite 3, 1000 Ergebnisse
Sensor 4679: Seite 4, 445 Ergebnisse
Sensor 4628: Seite 1, 1000 Ergebnisse
Sensor 4628: Seite 2, 1000 Ergebnisse
Sensor 4628: Seite 3, 1000 Ergebnisse
Sensor 4628: Seite 4, 230 Ergebnisse
Sensor 4678: Seite 1, 1000 Ergebnisse
Sensor 4678: Seite 2, 1000 Ergebnisse
Sensor 4678: Seite 3, 1000 Ergebnisse
Sensor 4678: Seite 4, 298 Ergebnisse
Sensor 4746: Seite 1, 1000 Ergebnisse
Sensor 4746: Seite 2, 1000 Ergebnisse
Sensor 4688: Seite 1, 1000 Ergebnisse
Sensor 4688: Seite 2, 1000 Ergebnisse
Sensor 4426: Seite 1, 1000 Ergebnisse
Sensor 4426: Seite 2, 1000 Ergebnisse
Sensor 4426: Seite 3, 848 Ergebnisse
Sensor 4468: Seite 1, 1000 Ergebnisse
Sensor 4468: Seite 2, 881 Ergebnisse
Sensor 4494: Seite 1, 1000 Ergebnisse
Sensor 4494: Seite 2, 507 Ergebnisse
Sensor 579: Seite 1, 62 Ergebnisse
Sensor 4896: Seite 1, 192 Ergebnisse
Sensor 262: Seite 1, 4 Ergebnisse
Sensor 7818: Seite 1, 1000 Ergebnisse
Sensor 7818: Seite 2, 1000 Ergebnisse
Sensor 7818: Seite 3, 1000 Ergebnisse
Sensor 7818: Seite 4, 185 Ergebnisse
Sensor 7819: Seite 1, 1000 Ergebnisse
Sensor 7819: Seite 2, 1000 Ergebnisse
Sensor 7819: Seite 3, 1000 Ergebnisse
Sensor 7819: Seite 4, 57 Ergebnisse
Sensor 7822: Seite 1, 1000 Ergebnisse
Sensor 7822: Seite 2, 1000 Ergebnisse
Sensor 7822: Seite 3, 1000 Ergebnisse
Sensor 7822: Seite 4, 183 Ergebnisse
Sensor 7810: Seite 1, 1000 Ergebnisse
Sensor 7810: Seite 2, 1000 Ergebnisse
Sensor 7810: Seite 3, 1000 Ergebnisse
Sensor 7810: Seite 4, 162 Ergebnisse
Sensor 7817: Seite 1, 1000 Ergebnisse
Sensor 7817: Seite 2, 1000 Ergebnisse
Sensor 7817: Seite 3, 1000 Ergebnisse
Sensor 7817: Seite 4, 210 Ergebnisse
Sensor 7824: Seite 1, 1000 Ergebnisse
Sensor 7824: Seite 2, 1000 Ergebnisse
Sensor 7824: Seite 3, 1000 Ergebnisse
Sensor 7824: Seite 4, 33 Ergebnisse
Sensor 7811: Seite 1, 1000 Ergebnisse
Sensor 7811: Seite 2, 1000 Ergebnisse
Sensor 7811: Seite 3, 1000 Ergebnisse
Sensor 7811: Seite 4, 105 Ergebnisse
Sensor 7820: Seite 1, 1000 Ergebnisse
Sensor 7820: Seite 2, 27 Ergebnisse
Sensor 1304546: Seite 1, 1000 Ergebnisse
Sensor 1304546: Seite 2, 601 Ergebnisse
Sensor 1304543: Seite 1, 1000 Ergebnisse
Sensor 1304543: Seite 2, 614 Ergebnisse
Sensor 1304530: Seite 1, 1000 Ergebnisse
Sensor 1304530: Seite 2, 579 Ergebnisse
Sensor 1304511: Seite 1, 1000 Ergebnisse
Sensor 1304511: Seite 2, 680 Ergebnisse
Sensor 1304529: Seite 1, 1000 Ergebnisse
Sensor 1304529: Seite 2, 425 Ergebnisse
Sensor 1304545: Seite 1, 1000 Ergebnisse
Sensor 1304545: Seite 2, 621 Ergebnisse
Sensor 1304514: Seite 1, 1000 Ergebnisse
Sensor 1304514: Seite 2, 674 Ergebnisse
Sensor 1304522: Seite 1, 1000 Ergebnisse
Sensor 1304522: Seite 2, 547 Ergebnisse
Sensor 1304508: Seite 1, 1000 Ergebnisse
Sensor 1304508: Seite 2, 517 Ergebnisse
Sensor 1304534: Seite 1, 1000 Ergebnisse
Sensor 1304534: Seite 2, 656 Ergebnisse
Sensor 1304557: Seite 1, 1000 Ergebnisse
Sensor 1304557: Seite 2, 216 Ergebnisse
Sensor 1304566: Seite 1, 1000 Ergebnisse
Sensor 1304566: Seite 2, 549 Ergebnisse
Sensor 1304548: Seite 1, 956 Ergebnisse
Sensor 1304562: Seite 1, 1000 Ergebnisse
Sensor 1304562: Seite 2, 676 Ergebnisse
Sensor 1304558: Seite 1, 1000 Ergebnisse
Sensor 1304558: Seite 2, 513 Ergebnisse
Sensor 1304525: Seite 1, 1000 Ergebnisse
Sensor 1304525: Seite 2, 562 Ergebnisse
Sensor 1304538: Seite 1, 1000 Ergebnisse
Sensor 1304538: Seite 2, 218 Ergebnisse
Sensor 1304526: Seite 1, 1000 Ergebnisse
Sensor 1304526: Seite 2, 177 Ergebnisse
Sensor 1304501: Seite 1, 715 Ergebnisse
Sensor 2686349: Seite 1, 123 Ergebnisse
Sensor 1304564: Seite 1, 621 Ergebnisse
Sensor 1304535: Seite 1, 502 Ergebnisse
Sensor 1304505: Seite 1, 590 Ergebnisse
Sensor 1304519: Seite 1, 262 Ergebnisse
Sensor 1304503: Seite 1, 230 Ergebnisse
Sensor 1304499: Seite 1, 261 Ergebnisse
Sensor 1304498: Seite 1, 254 Ergebnisse
Sensor 1304512: Seite 1, 250 Ergebnisse
Sensor 1304582: Seite 1, 1000 Ergebnisse
Sensor 1304582: Seite 2, 591 Ergebnisse
Sensor 1304589: Seite 1, 1000 Ergebnisse
Sensor 1304589: Seite 2, 662 Ergebnisse
Sensor 1304609: Seite 1, 1000 Ergebnisse
Sensor 1304609: Seite 2, 636 Ergebnisse
Sensor 1304697: Seite 1, 1000 Ergebnisse
Sensor 1304697: Seite 2, 651 Ergebnisse
Sensor 1304703: Seite 1, 1000 Ergebnisse
Sensor 1304703: Seite 2, 449 Ergebnisse
Sensor 1304645: Seite 1, 1000 Ergebnisse
Sensor 1304645: Seite 2, 635 Ergebnisse
Sensor 1304681: Seite 1, 1000 Ergebnisse
Sensor 1304681: Seite 2, 606 Ergebnisse
Sensor 1304691: Seite 1, 1000 Ergebnisse
Sensor 1304691: Seite 2, 468 Ergebnisse
Sensor 12747705: Seite 1, 322 Ergebnisse
Sensor 1304650: Seite 1, 1000 Ergebnisse
Sensor 1304650: Seite 2, 577 Ergebnisse
Sensor 1304621: Seite 1, 1000 Ergebnisse
Sensor 1304621: Seite 2, 561 Ergebnisse
Sensor 1304714: Seite 1, 1000 Ergebnisse
Sensor 1304714: Seite 2, 468 Ergebnisse
Sensor 1304708: Seite 1, 1000 Ergebnisse
Sensor 1304708: Seite 2, 536 Ergebnisse
Sensor 1304750: Seite 1, 1000 Ergebnisse
Sensor 1304750: Seite 2, 643 Ergebnisse
Sensor 1304885: Seite 1, 1000 Ergebnisse
Sensor 1304885: Seite 2, 644 Ergebnisse
Sensor 1304745: Seite 1, 1000 Ergebnisse
Sensor 1304745: Seite 2, 399 Ergebnisse
Sensor 1304744: Seite 1, 1000 Ergebnisse
Sensor 1304744: Seite 2, 611 Ergebnisse
Sensor 1304752: Seite 1, 1000 Ergebnisse
Sensor 1304752: Seite 2, 504 Ergebnisse
Sensor 1304880: Seite 1, 1000 Ergebnisse
Sensor 1304880: Seite 2, 140 Ergebnisse
Sensor 1304877: Seite 1, 1000 Ergebnisse
Sensor 1304877: Seite 2, 431 Ergebnisse
Sensor 1304871: Seite 1, 1000 Ergebnisse
Sensor 1304871: Seite 2, 350 Ergebnisse
Sensor 1304876: Seite 1, 1000 Ergebnisse
Sensor 1304876: Seite 2, 381 Ergebnisse
Sensor 1304698: Seite 1, 1000 Ergebnisse
Sensor 1304698: Seite 2, 422 Ergebnisse
Sensor 1304884: Seite 1, 529 Ergebnisse
Sensor 1304858: Seite 1, 1000 Ergebnisse
Sensor 1304858: Seite 2, 549 Ergebnisse
Sensor 1304634: Seite 1, 1000 Ergebnisse
Sensor 1304634: Seite 2, 305 Ergebnisse
Sensor 1304617: Seite 1, 1000 Ergebnisse
Sensor 1304617: Seite 2, 346 Ergebnisse
Sensor 1304733: Seite 1, 917 Ergebnisse
Sensor 1304747: Seite 1, 855 Ergebnisse
Sensor 1304637: Seite 1, 1000 Ergebnisse
Sensor 1304637: Seite 2, 564 Ergebnisse
Sensor 1304657: Seite 1, 1000 Ergebnisse
Sensor 1304657: Seite 2, 559 Ergebnisse
Sensor 1304655: Seite 1, 1000 Ergebnisse
Sensor 1304655: Seite 2, 536 Ergebnisse
Sensor 1304731: Seite 1, 1000 Ergebnisse
Sensor 1304731: Seite 2, 524 Ergebnisse
Sensor 1304583: Seite 1, 1000 Ergebnisse
Sensor 1304583: Seite 2, 549 Ergebnisse
Sensor 1304666: Seite 1, 1000 Ergebnisse
Sensor 1304666: Seite 2, 236 Ergebnisse
Sensor 1304656: Seite 1, 1000 Ergebnisse
Sensor 1304656: Seite 2, 293 Ergebnisse
Sensor 1304867: Seite 1, 1000 Ergebnisse
Sensor 1304867: Seite 2, 197 Ergebnisse
Sensor 1304852: Seite 1, 1000 Ergebnisse
Sensor 1304852: Seite 2, 247 Ergebnisse
Sensor 1304665: Seite 1, 1000 Ergebnisse
Sensor 1304665: Seite 2, 37 Ergebnisse
Sensor 1304743: Seite 1, 1000 Ergebnisse
Sensor 1304743: Seite 2, 195 Ergebnisse
Sensor 1304659: Seite 1, 1000 Ergebnisse
Sensor 1304659: Seite 2, 227 Ergebnisse
Sensor 1304628: Seite 1, 1000 Ergebnisse
Sensor 1304628: Seite 2, 260 Ergebnisse
Sensor 1304685: Seite 1, 1000 Ergebnisse
Sensor 1304685: Seite 2, 116 Ergebnisse
Sensor 1304581: Seite 1, 384 Ergebnisse
Sensor 1304889: Seite 1, 988 Ergebnisse
Sensor 1304667: Seite 1, 928 Ergebnisse
Sensor 1304887: Seite 1, 1000 Ergebnisse
Sensor 1304887: Seite 2, 8 Ergebnisse
Sensor 1304874: Seite 1, 1000 Ergebnisse
Sensor 1304874: Seite 2, 55 Ergebnisse
Sensor 1304636: Seite 1, 942 Ergebnisse
Sensor 1304699: Seite 1, 1000 Ergebnisse
Sensor 1304699: Seite 2, 13 Ergebnisse
Sensor 1304629: Seite 1, 1000 Ergebnisse
Sensor 1304629: Seite 2, 27 Ergebnisse
Sensor 1304695: Seite 1, 982 Ergebnisse
Sensor 1304644: Seite 1, 681 Ergebnisse
Sensor 1304856: Seite 1, 869 Ergebnisse
Sensor 1304859: Seite 1, 913 Ergebnisse
Sensor 1304900: Seite 1, 774 Ergebnisse
Sensor 1305046: Seite 1, 889 Ergebnisse
Sensor 1304707: Seite 1, 859 Ergebnisse
Sensor 1304696: Seite 1, 968 Ergebnisse
Sensor 1304643: Seite 1, 972 Ergebnisse
Sensor 1304616: Seite 1, 877 Ergebnisse
Sensor 1304746: Seite 1, 812 Ergebnisse
Sensor 1304756: Seite 1, 740 Ergebnisse
Sensor 1304868: Seite 1, 895 Ergebnisse
Sensor 1304863: Seite 1, 684 Ergebnisse
Sensor 1304732: Seite 1, 295 Ergebnisse
Sensor 1304676: Seite 1, 737 Ergebnisse
Sensor 1304630: Seite 1, 702 Ergebnisse
Sensor 1304635: Seite 1, 709 Ergebnisse
Sensor 1304658: Seite 1, 565 Ergebnisse
Sensor 1304865: Seite 1, 675 Ergebnisse
Sensor 1304860: Seite 1, 674 Ergebnisse
Sensor 1304622: Seite 1, 607 Ergebnisse
Sensor 1304684: Seite 1, 605 Ergebnisse
Sensor 1304855: Seite 1, 580 Ergebnisse
Sensor 1304590: Seite 1, 555 Ergebnisse
Sensor 1304627: Seite 1, 270 Ergebnisse
Sensor 1304580: Seite 1, 251 Ergebnisse
Sensor 1304755: Seite 1, 252 Ergebnisse
Sensor 1304694: Seite 1, 248 Ergebnisse
Sensor 1304678: Seite 1, 251 Ergebnisse
Sensor 1304662: Seite 1, 176 Ergebnisse
Sensor 1304702: Seite 1, 246 Ergebnisse
Sensor 1304741: Seite 1, 191 Ergebnisse
Sensor 1304740: Seite 1, 167 Ergebnisse
Sensor 1312357: Seite 1, 910 Ergebnisse
Sensor 1310775: Seite 1, 1000 Ergebnisse
Sensor 1310775: Seite 2, 430 Ergebnisse
Sensor 1310773: Seite 1, 1000 Ergebnisse
Sensor 1310773: Seite 2, 165 Ergebnisse
Sensor 1310774: Seite 1, 1000 Ergebnisse
Sensor 1310774: Seite 2, 428 Ergebnisse
Sensor 1329038: Seite 1, 1000 Ergebnisse
Sensor 1329038: Seite 2, 170 Ergebnisse
Sensor 1561900: Seite 1, 1000 Ergebnisse
Sensor 1561900: Seite 2, 297 Ergebnisse
Sensor 1561903: Seite 1, 188 Ergebnisse
Sensor 1561966: Seite 1, 989 Ergebnisse
Sensor 1702425: Seite 1, 44 Ergebnisse
Sensor 1652534: Seite 1, 589 Ergebnisse
Sensor 1839382: Seite 1, 77 Ergebnisse
Sensor 1923486: Seite 1, 71 Ergebnisse
Sensor 5079259: Seite 1, 826 Ergebnisse
Sensor 5079231: Seite 1, 993 Ergebnisse
Sensor 5079238: Seite 1, 1000 Ergebnisse
Sensor 5079238: Seite 2, 6 Ergebnisse
Sensor 5079253: Seite 1, 1000 Ergebnisse
Sensor 5079253: Seite 2, 2 Ergebnisse
Sensor 5079283: Seite 1, 1000 Ergebnisse
Sensor 5079283: Seite 2, 8 Ergebnisse
Sensor 5079297: Seite 1, 994 Ergebnisse
Sensor 5079300: Seite 1, 862 Ergebnisse
Sensor 5079307: Seite 1, 987 Ergebnisse
Sensor 5079315: Seite 1, 1000 Ergebnisse
Sensor 5079315: Seite 2, 3 Ergebnisse
Sensor 5079341: Seite 1, 1000 Ergebnisse
Sensor 5079341: Seite 2, 6 Ergebnisse
Sensor 5079293: Seite 1, 598 Ergebnisse
Sensor 5079290: Seite 1, 122 Ergebnisse
Sensor 2382003: Seite 1, 400 Ergebnisse
Sensor 5111975: Seite 1, 564 Ergebnisse
Sensor 6824670: Seite 1, 791 Ergebnisse
Sensor 8622320: Seite 1, 690 Ergebnisse
Sensor 8622638: Seite 1, 670 Ergebnisse
Sensor 8622236: Seite 1, 660 Ergebnisse
Sensor 8622232: Seite 1, 692 Ergebnisse
Sensor 8622277: Seite 1, 677 Ergebnisse
Sensor 8622323: Seite 1, 697 Ergebnisse
Sensor 8622263: Seite 1, 692 Ergebnisse
Sensor 8622221: Seite 1, 696 Ergebnisse
Sensor 8622264: Seite 1, 692 Ergebnisse
Sensor 8622322: Seite 1, 654 Ergebnisse
Sensor 8622618: Seite 1, 697 Ergebnisse
Sensor 8622317: Seite 1, 641 Ergebnisse
Sensor 8622255: Seite 1, 691 Ergebnisse
Sensor 8622274: Seite 1, 695 Ergebnisse
Sensor 8622310: Seite 1, 686 Ergebnisse
Sensor 8622268: Seite 1, 694 Ergebnisse
Sensor 8622635: Seite 1, 662 Ergebnisse
Sensor 8622303: Seite 1, 689 Ergebnisse
Sensor 8622258: Seite 1, 680 Ergebnisse
Sensor 8622299: Seite 1, 102 Ergebnisse
Sensor 8622214: Seite 1, 107 Ergebnisse
Sensor 8622287: Seite 1, 1 Ergebnisse
Sensor 8622312: Seite 1, 1 Ergebnisse
Sensor 8622290: Seite 1, 1 Ergebnisse
Sensor 9909573: Seite 1, 586 Ergebnisse
Sensor 9909574: Seite 1, 594 Ergebnisse
Sensor 12151632: Seite 1, 352 Ergebnisse
Sensor 12630851: Seite 1, 2 Ergebnisse
Sensor 12747984: Seite 1, 310 Ergebnisse
Sensor 12915155: Seite 1, 305 Ergebnisse
Sensor 12960855: Seite 1, 1 Ergebnisse
Sensor 13125837: Seite 1, 263 Ergebnisse
Sensor 13240506: Seite 1, 266 Ergebnisse
Sensor 13537392: Seite 1, 223 Ergebnisse
Sensor 13535111: Seite 1, 212 Ergebnisse
Sensor 14084832: Seite 1, 173 Ergebnisse
Sensor 14124220: Seite 1, 1 Ergebnisse
222309

[{'date': '2021-04-30', 'value': 40.6},
 {'date': '2021-05-01', 'value': 32.08461538461539},
 {'date': '2021-05-02', 'value': 61.3},
 {'date': '2021-05-03', 'value': 15.504761904761903},
 {'date': '2021-05-04', 'value': 19.085714285714285},
 {'date': '2021-05-05', 'value': 29.686363636363637},
 {'date': '2021-05-06', 'value': 39.07272727272727},
 {'date': '2021-05-07', 'value': 28.523809523809526},
 {'date': '2021-05-08', 'value': 18.095238095238095},
 {'date': '2021-05-09', 'value': 6.933333333333333},
 {'date': '2021-05-10', 'value': 26.031250000000004},
 {'date': '2021-05-11', 'value': 33.87222222222223},
 {'date': '2021-05-12', 'value': 27.488235294117644},
 {'date': '2021-05-13', 'value': 43.78421052631578},
 {'date': '2021-05-14', 'value': 38.73636363636364},
 {'date': '2021-05-15', 'value': 24.777272727272734},
 {'date': '2021-05-16', 'value': 17.23181818181818},
 {'date': '2021-05-17', 'value': 31.16666666666668},
 {'date': '2021-05-18', 'value': 39.84117647058824},
 {'date': '2021-05-19', 'value': 27.46363636363636},
 {'date': '2021-05-20', 'value': 28.75238095238095},
 {'date': '2021-05-21', 'value': 10.866666666666667},
 {'date': '2021-05-22', 'value': 20.993333333333332},
 {'date': '2021-05-25', 'value': 28.966666666666665},
 {'date': '2021-05-26', 'value': 26.049999999999997},
 {'date': '2021-05-27', 'value': 42.142857142857146},
 {'date': '2021-05-28', 'value': 55.78181818181818},
 {'date': '2021-05-29', 'value': 40.66818181818182},
 {'date': '2021-05-30', 'value': 77.5},
 {'date': '2021-05-31', 'value': 26.22380952380952},
 {'date': '2021-06-01', 'value': 50.7},
 {'date': '2021-06-02', 'value': 48.778947368421065},
 {'date': '2021-06-03', 'value': 32.184999999999995},
 {'date': '2021-06-04', 'value': 30.736363636363638},
 {'date': '2021-06-05', 'value': 23.218181818181822},
 {'date': '2021-06-06', 'value': 16.442857142857143},
 {'date': '2021-06-07', 'value': 21.649999999999995},
 {'date': '2021-06-08', 'value': 31.18},
 {'date': '2021-06-10', 'value': 21.60952380952381},
 {'date': '2021-06-11', 'value': 20.845000000000002},
 {'date': '2021-06-12', 'value': 16.040909090909093},
 {'date': '2021-06-13', 'value': 19.87727272727273},
 {'date': '2021-06-14', 'value': 32.595000000000006},
 {'date': '2021-06-15', 'value': 24.161904761904765},
 {'date': '2021-06-16', 'value': 18.9},
 {'date': '2021-06-17', 'value': 29.031818181818185},
 {'date': '2021-06-18', 'value': 12.5},
 {'date': '2021-06-19', 'value': 20.90909090909091},
 {'date': '2021-06-20', 'value': 16.404545454545456},
 {'date': '2021-06-21', 'value': 29.60909090909091},
 {'date': '2021-06-22', 'value': 21.1},
 {'date': '2021-06-23', 'value': 29.7090909090909},
 {'date': '2021-06-24', 'value': 35.61818181818182},
 {'date': '2021-06-25', 'value': 26.38181818181818},
 {'date': '2021-06-26', 'value': 18.049999999999997},
 {'date': '2021-06-27', 'value': 16.02777777777778},
 {'date': '2021-06-28', 'value': 28.5},
 {'date': '2021-06-29', 'value': 23.386363636363637},
 {'date': '2021-07-01', 'value': 35.6},
 {'date': '2021-07-02', 'value': 27.047619047619047},
 {'date': '2021-07-03', 'value': 19.64285714285714},
 {'date': '2021-07-04', 'value': 7.795454545454546},
 {'date': '2021-07-05', 'value': 18.845454545454547},
 {'date': '2021-07-06', 'value': 18.28636363636364},
 {'date': '2021-07-08', 'value': 27.186363636363634},
 {'date': '2021-07-09', 'value': 31.93684210526316},
 {'date': '2021-07-10', 'value': 22.0},
 {'date': '2021-07-13', 'value': 28.014285714285712},
 {'date': '2021-07-14', 'value': 25.454545454545453},
 {'date': '2021-07-15', 'value': 26.935714285714283},
 {'date': '2021-07-16', 'value': 27.359999999999992},
 {'date': '2021-07-17', 'value': 27.427272727272726},
 {'date': '2021-07-18', 'value': 32.777272727272724},
 {'date': '2021-07-19', 'value': 43.3590909090909},
 {'date': '2021-07-20', 'value': 51.49090909090909},
 {'date': '2021-07-21', 'value': 49.45238095238094},
 {'date': '2021-07-22', 'value': 51.6},
 {'date': '2021-07-23', 'value': 30.504545454545447},
 {'date': '2021-07-24', 'value': 32.48181818181818},
 {'date': '2021-07-25', 'value': 20.125000000000004},
 {'date': '2021-08-03', 'value': 37.457142857142856},
 {'date': '2021-08-04', 'value': 46.15000000000001},
 {'date': '2021-08-05', 'value': 24.126315789473683},
 {'date': '2021-08-06', 'value': 19.527272727272727},
 {'date': '2021-08-07', 'value': 13.672727272727274},
 {'date': '2021-08-08', 'value': 5.65},
 {'date': '2021-08-09', 'value': 25.11904761904762},
 {'date': '2021-08-10', 'value': 27.763636363636362},
 {'date': '2021-08-11', 'value': 28.50454545454545},
 {'date': '2021-08-12', 'value': 22.609090909090913},
 {'date': '2021-08-13', 'value': 26.91818181818182},
 {'date': '2021-08-14', 'value': 18.922727272727272},
 {'date': '2021-08-15', 'value': 14.045454545454543},
 {'date': '2021-08-16', 'value': 24.972727272727276},
 {'date': '2021-08-17', 'value': 28.590909090909097},
 {'date': '2021-08-18', 'value': 21.700000000000003},
 {'date': '2021-08-19', 'value': 22.057142857142857},
 {'date': '2021-08-20', 'value': 26.745454545454546},
 {'date': '2021-08-21', 'value': 23.827272727272728},
 {'date': '2021-08-22', 'value': 13.881818181818181},
 {'date': '2021-08-23', 'value': 20.79090909090909},
 {'date': '2021-08-24', 'value': 21.75909090909091},
 {'date': '2021-08-25', 'value': 20.336363636363636},
 {'date': '2021-08-26', 'value': 17.854545454545452},
 {'date': '2021-08-27', 'value': 18.54090909090909},
 {'date': '2021-08-28', 'value': 18.586363636363632},
 {'date': '2021-08-29', 'value': 20.60909090909091},
 {'date': '2021-08-30', 'value': 5.5},
 {'date': '2021-08-31', 'value': 22.790476190476188},
 {'date': '2021-09-01', 'value': 25.086363636363636},
 {'date': '2021-09-02', 'value': 26.018181818181816},
 {'date': '2021-09-03', 'value': 36.59545454545455},
 {'date': '2021-09-04', 'value': 28.95454545454545},
 {'date': '2021-09-05', 'value': 36.20454545454546},
 {'date': '2021-09-06', 'value': 60.62272727272727},
 {'date': '2021-09-07', 'value': 70.72727272727272},
 {'date': '2021-09-08', 'value': 70.86363636363636},
 {'date': '2021-09-09', 'value': 32.74090909090909},
 {'date': '2021-09-10', 'value': 31.077272727272724},
 {'date': '2021-09-11', 'value': 24.231818181818177},
 {'date': '2021-09-12', 'value': 27.985714285714288},
 {'date': '2021-09-13', 'value': 34.6},
 {'date': '2021-09-14', 'value': 47.12272727272728},
 {'date': '2021-09-15', 'value': 41.17727272727273},
 {'date': '2021-09-16', 'value': 41.10909090909092},
 {'date': '2021-09-17', 'value': 33.10454545454545},
 {'date': '2021-09-18', 'value': 45.690909090909095},
 {'date': '2021-09-19', 'value': 41.61363636363637},
 {'date': '2021-09-20', 'value': 30.313636363636363},
 {'date': '2021-09-21', 'value': 45.89047619047619},
 {'date': '2021-09-22', 'value': 41.34090909090909},
 {'date': '2021-09-23', 'value': 38.75909090909091},
 {'date': '2021-09-24', 'value': 34.154545454545456},
 {'date': '2021-09-25', 'value': 27.672727272727276},
 {'date': '2021-09-26', 'value': 29.295454545454547},
 {'date': '2021-09-27', 'value': 22.354545454545452},
 {'date': '2021-09-28', 'value': 29.072727272727274},
 {'date': '2021-09-29', 'value': 13.5},
 {'date': '2021-09-30', 'value': 34.780952380952385},
 {'date': '2021-10-01', 'value': 30.8},
 {'date': '2021-10-02', 'value': 27.86666666666667},
 {'date': '2021-10-03', 'value': 17.990909090909092},
 {'date': '2021-10-04', 'value': 33.91363636363636},
 {'date': '2021-10-05', 'value': 23.395454545454548},
 {'date': '2021-10-06', 'value': 27.686363636363634},
 {'date': '2021-10-07', 'value': 38.48636363636364},
 {'date': '2021-10-08', 'value': 34.17272727272728},
 {'date': '2021-10-09', 'value': 56.28181818181818},
 {'date': '2021-10-10', 'value': 34.53636363636363},
 {'date': '2021-10-11', 'value': 38.76818181818182},
 {'date': '2021-10-12', 'value': 38.50909090909091},
 {'date': '2021-10-13', 'value': 39.54545454545455},
 {'date': '2021-10-14', 'value': 35.24545454545454},
 {'date': '2021-10-15', 'value': 38.76818181818182},
 {'date': '2021-10-16', 'value': 48.44090909090908},
 {'date': '2021-10-17', 'value': 31.818181818181824},
 {'date': '2021-10-18', 'value': 35.57272727272727},
 {'date': '2021-10-19', 'value': 17.177272727272722},
 {'date': '2021-10-20', 'value': 23.731818181818188},
 {'date': '2021-10-21', 'value': 27.018181818181816},
 {'date': '2021-10-22', 'value': 36.56363636363637},
 {'date': '2021-10-23', 'value': 30.159090909090903},
 {'date': '2021-10-24', 'value': 12.413636363636362},
 {'date': '2021-10-25', 'value': 35.11818181818182},
 {'date': '2021-10-26', 'value': 35.304545454545455},
 {'date': '2021-10-27', 'value': 25.177272727272733},
 {'date': '2021-10-28', 'value': 23.231818181818184},
 {'date': '2021-10-29', 'value': 8.9},
 {'date': '2021-10-30', 'value': 26.323809523809523},
 {'date': '2021-10-31', 'value': 13.720833333333333},
 {'date': '2021-11-01', 'value': 38.0695652173913},
 {'date': '2021-11-02', 'value': 57.952173913043474},
 {'date': '2021-11-03', 'value': 43.57391304347826},
 {'date': '2021-11-04', 'value': 30.321739130434775},
 {'date': '2021-11-05', 'value': 50.7695652173913},
 {'date': '2021-11-06', 'value': 20.147826086956517},
 {'date': '2021-11-07', 'value': 23.208695652173915},
 {'date': '2021-11-08', 'value': 46.478260869565226},
 {'date': '2021-11-09', 'value': 42.163636363636364},
 {'date': '2021-11-10', 'value': 45.856521739130436},
 {'date': '2021-11-11', 'value': 41.48181818181818},
 {'date': '2021-11-12', 'value': 29.247826086956525},
 {'date': '2021-11-13', 'value': 27.94347826086957},
 {'date': '2021-11-14', 'value': 24.791304347826088},
 {'date': '2021-11-15', 'value': 50.15652173913044},
 {'date': '2021-11-16', 'value': 53.468181818181826},
 {'date': '2021-11-17', 'value': 46.68695652173912},
 {'date': '2021-11-18', 'value': 44.49999999999999},
 {'date': '2021-11-19', 'value': 34.41304347826087},
 {'date': '2021-11-20', 'value': 27.09565217391304},
 {'date': '2021-11-21', 'value': 11.521739130434783},
 {'date': '2021-11-22', 'value': 32.082608695652176},
 {'date': '2021-11-23', 'value': 53.665217391304346},
 {'date': '2021-11-24', 'value': 49.48260869565218},
 {'date': '2021-11-25', 'value': 41.44285714285714},
 {'date': '2021-11-26', 'value': 33.08695652173913},
 {'date': '2021-11-27', 'value': 12.678260869565216},
 {'date': '2021-11-29', 'value': 42.46521739130434},
 {'date': '2021-11-30', 'value': 29.999999999999996},
 {'date': '2021-12-01', 'value': 21.09090909090909},
 {'date': '2021-12-02', 'value': 36.42173913043477},
 {'date': '2021-12-03', 'value': 47.94347826086957},
 {'date': '2021-12-04', 'value': 24.200000000000006},
 {'date': '2021-12-05', 'value': 13.5},
 {'date': '2021-12-06', 'value': 32.22608695652174},
 {'date': '2021-12-07', 'value': 37.76},
 {'date': '2021-12-08', 'value': 24.921739130434784},
 {'date': '2021-12-09', 'value': 42.66086956521739},
 {'date': '2021-12-10', 'value': 23.07826086956522},
 {'date': '2021-12-11', 'value': 38.89565217391304},
 {'date': '2021-12-12', 'value': 17.852173913043476},
 {'date': '2021-12-13', 'value': 29.243478260869566},
 {'date': '2021-12-14', 'value': 36.35217391304348},
 {'date': '2021-12-15', 'value': 40.516666666666666},
 {'date': '2021-12-16', 'value': 50.23913043478261},
 {'date': '2021-12-17', 'value': 35.55652173913043},
 {'date': '2021-12-18', 'value': 25.299999999999994},
 {'date': '2021-12-19', 'value': 26.69130434782609},
 {'date': '2021-12-20', 'value': 36.939130434782605},
 {'date': '2021-12-21', 'value': 46.68695652173913},
 {'date': '2021-12-22', 'value': 50.5318181818182},
 {'date': '2021-12-23', 'value': 31.104347826086954},
 {'date': '2021-12-24', 'value': 36.795652173913034},
 {'date': '2021-12-25', 'value': 17.76521739130435},
 {'date': '2021-12-26', 'value': 33.082608695652176},
 {'date': '2021-12-27', 'value': 20.63478260869565},
 {'date': '2021-12-29', 'value': 14.98695652173913},
 {'date': '2021-12-30', 'value': 7.556521739130434},
 {'date': '2021-12-31', 'value': 11.1},
 {'date': '2022-01-01', 'value': 9.947826086956521},
 {'date': '2022-01-02', 'value': 7.5476190476190474},
 {'date': '2022-01-03', 'value': 13.021739130434783},
 {'date': '2022-01-04', 'value': 28.92173913043478},
 {'date': '2022-01-05', 'value': 34.06956521739131},
 {'date': '2022-01-06', 'value': 39.891304347826086},
 {'date': '2022-01-07', 'value': 34.79565217391304},
 {'date': '2022-01-08', 'value': 22.63913043478261},
 {'date': '2022-01-09', 'value': 37.160869565217396},
 {'date': '2022-01-10', 'value': 57.07391304347825},
 {'date': '2022-01-11', 'value': 39.68181818181818},
 {'date': '2022-01-12', 'value': 62.14347826086957},
 {'date': '2022-01-13', 'value': 72.38260869565217},
 {'date': '2022-01-14', 'value': 85.54782608695652},
 {'date': '2022-01-15', 'value': 51.013043478260876},
 {'date': '2022-01-16', 'value': 36.83478260869566},
 {'date': '2022-01-17', 'value': 63.54782608695652},
 {'date': '2022-01-18', 'value': 70.0217391304348},
 {'date': '2022-01-19', 'value': 43.643478260869564},
 {'date': '2022-01-20', 'value': 33.42727272727272},
 {'date': '2022-01-21', 'value': 52.83478260869563},
 {'date': '2022-01-22', 'value': 36.04782608695652},
 {'date': '2022-01-23', 'value': 24.37391304347826},
 {'date': '2022-01-24', 'value': 34.28260869565218},
 {'date': '2022-01-25', 'value': 35.27826086956521},
 {'date': '2022-01-26', 'value': 37.652173913043484},
 {'date': '2022-01-28', 'value': 45.69130434782609},
 {'date': '2022-01-29', 'value': 18.499999999999996},
 {'date': '2022-01-30', 'value': 25.840909090909097},
 {'date': '2022-01-31', 'value': 18.86086956521739},
 {'date': '2022-02-01', 'value': 20.230434782608693},
 {'date': '2022-02-02', 'value': 33.939130434782605},
 {'date': '2022-02-03', 'value': 34.68260869565216},
 {'date': '2022-02-04', 'value': 24.847826086956516},
 {'date': '2022-02-05', 'value': 21.477272727272727},
 {'date': '2022-02-06', 'value': 6.817391304347825},
 {'date': '2022-02-07', 'value': 33.82272727272728},
 {'date': '2022-02-08', 'value': 29.61739130434782},
 {'date': '2022-02-09', 'value': 30.843478260869574},
 {'date': '2022-02-10', 'value': 22.682608695652174},
 {'date': '2022-02-11', 'value': 39.60869565217391},
 {'date': '2022-02-12', 'value': 14.773913043478263},
 {'date': '2022-02-13', 'value': 7.334782608695652},
 {'date': '2022-02-14', 'value': 23.721739130434784},
 {'date': '2022-02-15', 'value': 31.68260869565217},
 {'date': '2022-02-16', 'value': 17.24705882352941},
 {'date': '2022-02-17', 'value': 17.15652173913043},
 {'date': '2022-02-18', 'value': 9.095652173913043},
 {'date': '2022-02-19', 'value': 14.117391304347828},
 {'date': '2022-02-20', 'value': 5.2043478260869565},
 {'date': '2022-02-21', 'value': 14.891304347826084},
 {'date': '2022-02-22', 'value': 31.97826086956521},
 {'date': '2022-02-23', 'value': 34.20434782608696},
 {'date': '2022-02-24', 'value': 22.86521739130435},
 {'date': '2022-02-25', 'value': 39.84347826086957},
 {'date': '2022-02-27', 'value': 18.413043478260867},
 {'date': '2022-02-28', 'value': 27.595652173913045},
 {'date': '2022-03-01', 'value': 32.46521739130435},
 {'date': '2022-03-02', 'value': 47.43478260869566},
 {'date': '2022-03-03', 'value': 39.18695652173913},
 {'date': '2022-03-04', 'value': 34.16086956521739},
 {'date': '2022-03-05', 'value': 16.871428571428574},
 {'date': '2022-03-06', 'value': 14.369565217391301},
 {'date': '2022-03-07', 'value': 25.713043478260868},
 {'date': '2022-03-08', 'value': 30.265217391304358},
 {'date': '2022-03-09', 'value': 23.434782608695652},
 {'date': '2022-03-10', 'value': 24.547826086956523},
 {'date': '2022-03-11', 'value': 20.586956521739133},
 {'date': '2022-03-12', 'value': 13.11304347826087},
 {'date': '2022-03-13', 'value': 15.899999999999999},
 {'date': '2022-03-14', 'value': 47.526086956521745},
 {'date': '2022-03-15', 'value': 42.96086956521739},
 {'date': '2022-03-16', 'value': 35.24347826086957},
 {'date': '2022-03-17', 'value': 39.95217391304349},
 {'date': '2022-03-18', 'value': 41.26086956521739},
 {'date': '2022-03-19', 'value': 28.0304347826087},
 {'date': '2022-03-20', 'value': 31.02608695652174},
 {'date': '2022-03-21', 'value': 57.23043478260868},
 {'date': '2022-03-22', 'value': 45.25882352941177},
 {'date': '2022-03-24', 'value': 109.7},
 {'date': '2022-03-25', 'value': 52.86521739130435},
 {'date': '2022-03-26', 'value': 31.23913043478261},
 {'date': '2022-03-27', 'value': 27.347619047619045},
 {'date': '2022-03-28', 'value': 46.9},
 {'date': '2022-03-29', 'value': 32.171428571428564},
 {'date': '2022-03-30', 'value': 31.190909090909088},
 {'date': '2022-03-31', 'value': 19.177272727272726},
 {'date': '2022-04-01', 'value': 21.900000000000002},
 {'date': '2022-04-02', 'value': 28.49090909090909},
 {'date': '2022-04-03', 'value': 32.09545454545454},
 {'date': '2022-04-04', 'value': 25.63636363636364},
 {'date': '2022-04-05', 'value': 23.536363636363635},
 {'date': '2022-04-06', 'value': 22.586363636363636},
 {'date': '2022-04-07', 'value': 16.486363636363635},
 {'date': '2022-04-08', 'value': 40.22727272727272},
 {'date': '2022-04-09', 'value': 22.740909090909092},
 {'date': '2022-04-10', 'value': 26.49090909090909},
 {'date': '2022-04-11', 'value': 34.945454545454545},
 {'date': '2022-04-12', 'value': 41.25454545454544},
 {'date': '2022-04-13', 'value': 32.53181818181818},
 {'date': '2022-04-14', 'value': 37.72272727272727},
 {'date': '2022-04-15', 'value': 39.654545454545456},
 {'date': '2022-04-16', 'value': 40.404545454545456},
 {'date': '2022-04-17', 'value': 27.940909090909088},
 {'date': '2022-04-18', 'value': 20.05909090909091},
 {'date': '2022-04-19', 'value': 30.981818181818184},
 {'date': '2022-04-20', 'value': 24.768181818181816},
 {'date': '2022-04-21', 'value': 29.34090909090909},
 {'date': '2022-04-22', 'value': 23.681818181818187},
 {'date': '2022-04-23', 'value': 20.31363636363636},
 {'date': '2022-04-24', 'value': 18.813636363636366},
 {'date': '2022-04-25', 'value': 26.672727272727276},
 {'date': '2022-04-26', 'value': 30.37727272727273},
 {'date': '2022-04-27', 'value': 32.3},
 {'date': '2022-04-28', 'value': 32.390476190476186},
 {'date': '2022-04-29', 'value': 34.7909090909091},
 {'date': '2022-04-30', 'value': 30.99545454545455},
 {'date': '2022-05-01', 'value': 19.222727272727266},
 {'date': '2022-05-02', 'value': 24.822727272727274},
 {'date': '2022-05-03', 'value': 32.71818181818182},
 {'date': '2022-05-04', 'value': 35.34761904761904},
 {'date': '2022-05-05', 'value': 31.24090909090909},
 {'date': '2022-05-06', 'value': 37.050000000000004},
 {'date': '2022-05-07', 'value': 20.059090909090916},
 {'date': '2022-05-08', 'value': 17.854545454545455},
 {'date': '2022-05-09', 'value': 34.92272727272728},
 {'date': '2022-05-10', 'value': 28.490909090909096},
 {'date': '2022-05-11', 'value': 25.340909090909086},
 {'date': '2022-05-12', 'value': 31.800000000000008},
 {'date': '2022-05-13', 'value': 26.16818181818182},
 {'date': '2022-05-14', 'value': 23.763636363636362},
 {'date': '2022-05-15', 'value': 37.60909090909091},
 {'date': '2022-05-16', 'value': 33.913636363636364},
 {'date': '2022-05-17', 'value': 26.049999999999997},
 {'date': '2022-05-18', 'value': 26.74545454545455},
 {'date': '2022-05-19', 'value': 29.368181818181824},
 {'date': '2022-05-20', 'value': 31.74090909090909},
 {'date': '2022-05-21', 'value': 20.66363636363636},
 {'date': '2022-05-22', 'value': 17.109999999999996},
 {'date': '2022-05-23', 'value': 33.67894736842105},
 {'date': '2022-05-24', 'value': 28.072727272727274},
 {'date': '2022-05-25', 'value': 27.290476190476188},
 {'date': '2022-05-26', 'value': 20.131818181818183},
 {'date': '2022-05-27', 'value': 3.3},
 {'date': '2022-05-28', 'value': 13.452380952380949},
 {'date': '2022-05-29', 'value': 9.968181818181819},
 {'date': '2022-05-30', 'value': 27.486363636363638},
 {'date': '2022-05-31', 'value': 25.55454545454545},
 {'date': '2022-06-01', 'value': 26.41428571428571},
 {'date': '2022-06-02', 'value': 27.181818181818183},
 {'date': '2022-06-03', 'value': 16.89545454545454},

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

uk_daily = (
    df_results.groupby("date")
              .agg(uk_no2_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

uk_daily

           date  france_no2_mean
0    2016-01-30        14.708333
1    2016-01-31        12.826087
2    2016-02-01        17.250000
3    2016-02-02        20.818182
4    2016-02-03        27.700000
...         ...              ...
3525 2026-02-24        18.105761
3526 2026-02-25        22.540376
3527 2026-02-26        12.419169
3528 2026-02-27        18.540104
3529 2026-02-28        16.565297

[3530 rows x 2 columns]

In [ ]:
uk_daily[["date", "uk_no2_mean"]].to_csv(
    "daily_avg_uk_NO2.csv",
    index=False
)