In [1]:
#import sys
#!{sys.executable} -m pip install plotly      #falls man noch was installieren muss, geht das hiermit recht leicht

In [ ]:
#components################################################################################

In [134]:
import requests
import urllib.parse as up
import pandas as pd
from pandas import json_normalize
import json
base = "https://luftdaten.umweltbundesamt.de/api/air-data/v4/components/json?lang=de&index=code" 
#query = {
    #"angebotsart": "1",
    #"wo": "Schleswig-Holstein",
    #"umkreis": "200",
    #"arbeitszeit": "ho;mj",  # Semikolon bleibt bewusst erhalten
    #"page": "5",
    #"size": "250",
    #"pav": "false",
#}
# safe=';' sorgt dafür, dass das Semikolon nicht encodiert wird, falls die API es so erwartet
url = f"{base}?{up.urlencode}"

#url = f"{base}?{up.urlencode(query, safe=';')}"

#headers = {
    #"X-API-Key": "jobboerse-jobsuche",
    #"Accept": "application/json",
    #"User-Agent": "Mozilla/5.0",
#}

r = requests.get(url, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data1= r.json()

URL: https://luftdaten.umweltbundesamt.de/api/air-data/v4/components/json?lang=de&index=code?%3Cfunction%20urlencode%20at%200x00000202D3A32A20%3E
Status: 200 OK
CT: application/json

In [135]:
print(data.keys())

dict_keys(['count', 'indices', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'])

In [136]:
indices=data["indices"] #alle möglichen Eigenschaften inklusive der dort vorhanden Daten denke ich mal für Angebotsart 1
indices                 #aus manchen Eigenschaften werde ich aber noch nicht so richtig schlau, da keine Einheiten gegeben sind

['component id',
 'component code',
 'component symbol',
 'component unit',
 'component name']

In [137]:
data1

{'count': 12,
 'indices': ['component id',
  'component code',
  'component symbol',
  'component unit',
  'component name'],
 '1': ['1', 'PM10', 'PM₁₀', 'µg/m³', 'Feinstaub'],
 '2': ['2', 'CO', 'CO', 'mg/m³', 'Kohlenmonoxid'],
 '3': ['3', 'O3', 'O₃', 'µg/m³', 'Ozon'],
 '4': ['4', 'SO2', 'SO₂', 'µg/m³', 'Schwefeldioxid'],
 '5': ['5', 'NO2', 'NO₂', 'µg/m³', 'Stickstoffdioxid'],
 '6': ['6', 'PM10PB', 'Pb', 'µg/m³', 'Blei im Feinstaub'],
 '7': ['7', 'PM10BAP', 'BaP', 'ng/m³', 'Benzo(a)pyren im Feinstaub'],
 '8': ['8', 'CHB', 'C₆H₆', 'µg/m³', 'Benzol'],
 '9': ['9', 'PM2', 'PM₂,₅', 'µg/m³', 'Feinstaub'],
 '10': ['10', 'PM10AS', 'As', 'ng/m³', 'Arsen im Feinstaub'],
 '11': ['11', 'PM10CD', 'Cd', 'ng/m³', 'Cadmium im Feinstaub'],
 '12': ['12', 'PM10NI', 'Ni', 'ng/m³', 'Nickel im Feinstaub']}

In [138]:
columns1 = data1["indices"]
columns1

['component id',
 'component code',
 'component symbol',
 'component unit',
 'component name']

In [139]:
rows1 = [value for key, value in data1.items() if key.isdigit()]
rows1

[['1', 'PM10', 'PM₁₀', 'µg/m³', 'Feinstaub'],
 ['2', 'CO', 'CO', 'mg/m³', 'Kohlenmonoxid'],
 ['3', 'O3', 'O₃', 'µg/m³', 'Ozon'],
 ['4', 'SO2', 'SO₂', 'µg/m³', 'Schwefeldioxid'],
 ['5', 'NO2', 'NO₂', 'µg/m³', 'Stickstoffdioxid'],
 ['6', 'PM10PB', 'Pb', 'µg/m³', 'Blei im Feinstaub'],
 ['7', 'PM10BAP', 'BaP', 'ng/m³', 'Benzo(a)pyren im Feinstaub'],
 ['8', 'CHB', 'C₆H₆', 'µg/m³', 'Benzol'],
 ['9', 'PM2', 'PM₂,₅', 'µg/m³', 'Feinstaub'],
 ['10', 'PM10AS', 'As', 'ng/m³', 'Arsen im Feinstaub'],
 ['11', 'PM10CD', 'Cd', 'ng/m³', 'Cadmium im Feinstaub'],
 ['12', 'PM10NI', 'Ni', 'ng/m³', 'Nickel im Feinstaub']]

In [140]:
df = pd.DataFrame(rows1, columns=columns1)
df

,component id,component code,component symbol,component unit,component name
0,1,PM10,PM₁₀,µg/m³,Feinstaub
1,2,CO,CO,mg/m³,Kohlenmonoxid
2,3,O3,O₃,µg/m³,Ozon
3,4,SO2,SO₂,µg/m³,Schwefeldioxid
4,5,NO2,NO₂,µg/m³,Stickstoffdioxid
5,6,PM10PB,Pb,µg/m³,Blei im Feinstaub
6,7,PM10BAP,BaP,ng/m³,Benzo(a)pyren im Feinstaub
7,8,CHB,C₆H₆,µg/m³,Benzol
8,9,PM2,"PM₂,₅",µg/m³,Feinstaub
9,10,PM10AS,As,ng/m³,Arsen im Feinstaub
10,11,PM10CD,Cd,ng/m³,Cadmium im Feinstaub
11,12,PM10NI,Ni,ng/m³,Nickel im Feinstaub

In [141]:
#networks######################################################################################

In [142]:
url = "https://luftdaten.umweltbundesamt.de/api/air-data/v4/networks/json?lang=de"

r = requests.get(url, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data2= r.json()

URL: https://luftdaten.umweltbundesamt.de/api/air-data/v4/networks/json?lang=de
Status: 200 OK
CT: application/json

In [143]:
data2

{'indices': ['network id', 'network code', 'network name'],
 'data': {'1': ['1', 'BW', 'Baden-Württemberg'],
  '2': ['2', 'BY', 'Bayern'],
  '3': ['3', 'BE', 'Berlin'],
  '4': ['4', 'BB', 'Brandenburg'],
  '5': ['5', 'HB', 'Bremen'],
  '6': ['6', 'HH', 'Hamburg'],
  '7': ['7', 'HE', 'Hessen'],
  '8': ['8', 'MV', 'Mecklenburg-Vorpommern'],
  '9': ['9', 'NI', 'Niedersachsen'],
  '10': ['10', 'NW', 'Nordrhein-Westfalen'],
  '11': ['11', 'RP', 'Rheinland-Pfalz'],
  '12': ['12', 'SL', 'Saarland'],
  '13': ['13', 'SN', 'Sachsen'],
  '14': ['14', 'ST', 'Sachsen-Anhalt'],
  '15': ['15', 'SH', 'Schleswig-Holstein'],
  '16': ['16', 'TH', 'Thüringen'],
  '17': ['17', 'UB', 'UBA']},
 'count': 17}

In [144]:
columns2 = data2["indices"]
columns2

['network id', 'network code', 'network name']

In [145]:
rows2 = [value for key, value in data2["data"].items() if key.isdigit()]
rows2

[['1', 'BW', 'Baden-Württemberg'],
 ['2', 'BY', 'Bayern'],
 ['3', 'BE', 'Berlin'],
 ['4', 'BB', 'Brandenburg'],
 ['5', 'HB', 'Bremen'],
 ['6', 'HH', 'Hamburg'],
 ['7', 'HE', 'Hessen'],
 ['8', 'MV', 'Mecklenburg-Vorpommern'],
 ['9', 'NI', 'Niedersachsen'],
 ['10', 'NW', 'Nordrhein-Westfalen'],
 ['11', 'RP', 'Rheinland-Pfalz'],
 ['12', 'SL', 'Saarland'],
 ['13', 'SN', 'Sachsen'],
 ['14', 'ST', 'Sachsen-Anhalt'],
 ['15', 'SH', 'Schleswig-Holstein'],
 ['16', 'TH', 'Thüringen'],
 ['17', 'UB', 'UBA']]

In [146]:
df = pd.DataFrame(rows2, columns=columns2)
df

   network id network code            network name
0           1           BW       Baden-Württemberg
1           2           BY                  Bayern
2           3           BE                  Berlin
3           4           BB             Brandenburg
4           5           HB                  Bremen
5           6           HH                 Hamburg
6           7           HE                  Hessen
7           8           MV  Mecklenburg-Vorpommern
8           9           NI           Niedersachsen
9          10           NW     Nordrhein-Westfalen
10         11           RP         Rheinland-Pfalz
11         12           SL                Saarland
12         13           SN                 Sachsen
13         14           ST          Sachsen-Anhalt
14         15           SH      Schleswig-Holstein
15         16           TH               Thüringen
16         17           UB                     UBA

In [147]:
#Scopes######################################################################################

In [148]:
url = "https://luftdaten.umweltbundesamt.de/api/air-data/v4/scopes/json?lang=de" 

r = requests.get(url, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data3= r.json()

URL: https://luftdaten.umweltbundesamt.de/api/air-data/v4/scopes/json?lang=de
Status: 200 OK
CT: application/json

In [149]:
data3

{'count': 6,
 'indices': ['scope id',
  'scope code',
  'scope time base',
  'scope time scope',
  'scope time is max',
  'scope name'],
 '1': ['1', '1TMW', 'day', '86400', '0', 'Tagesmittel'],
 '2': ['2', '1SMW', 'hour', '3600', '0', 'Ein-Stunden-Mittelwert'],
 '3': ['3', '1SMW_MAX', 'hour', '3600', '1', 'Ein-Stunden-Tagesmaxima'],
 '4': ['4', '8SMW', 'hour', '28800', '0', 'Acht-Stunden-Mittelwert'],
 '5': ['5', '8SMW_MAX', 'hour', '28800', '1', 'Acht-Stunden-Tagesmaxima'],
 '6': ['6', '1TMWGL', 'hour', '3600', '0', 'Tagesmittel (stündlich gleitend)']}

In [150]:
columns3 = data3["indices"]
columns3

['scope id',
 'scope code',
 'scope time base',
 'scope time scope',
 'scope time is max',
 'scope name']

In [152]:
rows3 = [value for key, value in data3.items() if key.isdigit()]
rows3

[['1', '1TMW', 'day', '86400', '0', 'Tagesmittel'],
 ['2', '1SMW', 'hour', '3600', '0', 'Ein-Stunden-Mittelwert'],
 ['3', '1SMW_MAX', 'hour', '3600', '1', 'Ein-Stunden-Tagesmaxima'],
 ['4', '8SMW', 'hour', '28800', '0', 'Acht-Stunden-Mittelwert'],
 ['5', '8SMW_MAX', 'hour', '28800', '1', 'Acht-Stunden-Tagesmaxima'],
 ['6', '1TMWGL', 'hour', '3600', '0', 'Tagesmittel (stündlich gleitend)']]

In [153]:
df = pd.DataFrame(rows3, columns=columns3)
df

,scope id,scope code,scope time base,scope time scope,scope time is max,scope name
0,1,1TMW,day,86400,0,Tagesmittel
1,2,1SMW,hour,3600,0,Ein-Stunden-Mittelwert
2,3,1SMW_MAX,hour,3600,1,Ein-Stunden-Tagesmaxima
3,4,8SMW,hour,28800,0,Acht-Stunden-Mittelwert
4,5,8SMW_MAX,hour,28800,1,Acht-Stunden-Tagesmaxima
5,6,1TMWGL,hour,3600,0,Tagesmittel (stündlich gleitend)

In [ ]:
#threshholds#######################################################################################

In [168]:
url = "https://luftdaten.umweltbundesamt.de/api/air-data/v4/thresholds/json?use=airquality&component=1&scope=2"

r = requests.get(url, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data4= r.json()

URL: https://luftdaten.umweltbundesamt.de/api/air-data/v4/thresholds/json?use=airquality&component=1&scope=2
Status: 200 OK
CT: application/json

In [169]:
data4

{'count': 5,
 'indices': ['threshold id',
  'component id',
  'scope id',
  'threshold type',
  'threshold min',
  'threshold max',
  'threshold index'],
 '206': ['206', '1', '2', 'aq4', '0', '9', '0'],
 '207': ['207', '1', '2', 'aq4', '10', '27', '1'],
 '208': ['208', '1', '2', 'aq4', '28', '54', '2'],
 '209': ['209', '1', '2', 'aq4', '55', '90', '3'],
 '210': ['210', '1', '2', 'aq4', '91', '4000', '4']}

In [170]:
columns4 = data4["indices"]
columns4

['threshold id',
 'component id',
 'scope id',
 'threshold type',
 'threshold min',
 'threshold max',
 'threshold index']

In [171]:
rows4 = [value for key, value in data4.items() if key.isdigit()]
rows4

[['206', '1', '2', 'aq4', '0', '9', '0'],
 ['207', '1', '2', 'aq4', '10', '27', '1'],
 ['208', '1', '2', 'aq4', '28', '54', '2'],
 ['209', '1', '2', 'aq4', '55', '90', '3'],
 ['210', '1', '2', 'aq4', '91', '4000', '4']]

In [172]:
df = pd.DataFrame(rows4, columns=columns4)
df

,threshold id,component id,scope id,threshold type,threshold min,threshold max,threshold index
0,206,1,2,aq4,0,9,0
1,207,1,2,aq4,10,27,1
2,208,1,2,aq4,28,54,2
3,209,1,2,aq4,55,90,3
4,210,1,2,aq4,91,4000,4

In [ ]:
#get all stations##########################################################################

In [174]:
url = "https://luftdaten.umweltbundesamt.de/api/air-data/v4/stations/json?use=airquality&lang=de&date_from=2025-09-01&date_to=2025-09-01&time_from=9&time_to=9"

r = requests.get(url, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data5= r.json()

URL: https://luftdaten.umweltbundesamt.de/api/air-data/v4/stations/json?use=airquality&lang=de&date_from=2025-09-01&date_to=2025-09-01&time_from=9&time_to=9
Status: 200 OK
CT: application/json

In [175]:
data5

{'request': {'use': 'airquality',
  'date_from': '2025-09-01',
  'date_to': '2025-09-01',
  'time_from': '09:00:00',
  'time_to': '09:00:00',
  'lang': 'de',
  'recent': False,
  'index': 'id',
  'datetime_from': '2025-09-01 08:00:00',
  'datetime_to': '2025-09-01 08:00:00'},
 'indices': ['station id',
  'station code',
  'station name',
  'station city',
  'station synonym',
  'station active from',
  'station active to',
  'station longitude',
  'station latitude',
  'network id',
  'station setting id',
  'station type id',
  'network code',
  'network name',
  'station setting name',
  'station setting short name',
  'station type name',
  'station street',
  'station street nr',
  'station zip code'],
 'data': {'21': ['21',
   'DEBB021',
   'Potsdam-Zentrum',
   'Potsdam',
   'PDBA',
   '2009-04-15',
   None,
   '13.0602',
   '52.4014',
   '4',
   '1',
   '1',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Am Bassinplatz',
   '',
   '14467'],
  '28': ['28',
   'DEBB029',
   'Schwedt (Oder)',
   'Schwedt/Oder',
   'SWHE',
   '1993-04-06',
   None,
   '14.2851',
   '53.0643',
   '4',
   '2',
   '2',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Industrie',
   'Helbigstr.',
   '',
   '16303'],
  '31': ['31',
   'DEBB032',
   'Eisenhüttenstadt',
   'Eisenhüttenstadt',
   'EHST',
   '1993-04-20',
   None,
   '14.6382',
   '52.1463',
   '4',
   '2',
   '2',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Industrie',
   'Karl-Marx-Str.',
   '35',
   '15890'],
  '42': ['42',
   'DEBB044',
   'Cottbus, Bahnhofstr.',
   'Cottbus',
   'COBA',
   '2012-09-25',
   None,
   '14.3280',
   '51.7566',
   '4',
   '1',
   '3',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Bahnhofstr.',
   '55',
   '03046'],
  '43': ['43',
   'DEBB045',
   'Frankfurt (Oder), Leipziger Str.',
   'Frankfurt (Oder)',
   'FFLS',
   '1995-08-01',
   None,
   '14.5386',
   '52.3373',
   '4',
   '1',
   '3',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Leipziger Str.',
   '',
   '15232'],
  '46': ['46',
   'DEBB048',
   'Neuruppin',
   'Neuruppin',
   'NEHA',
   '1998-06-11',
   None,
   '12.8095',
   '52.9319',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Gerhart-Hauptmann-Str.',
   '18/1',
   '16816'],
  '47': ['47',
   'DEBB049',
   'Brandenburg, Neuendorfer Str.',
   'Brandenburg',
   'BRNE',
   '2013-10-15',
   None,
   '12.5486',
   '52.4094',
   '4',
   '1',
   '3',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Neuendorfer Str.',
   '',
   '14770'],
  '51': ['51',
   'DEBB053',
   'Hasenholz (Buckow)',
   'Buckow',
   'HAHO',
   '2000-11-21',
   None,
   '14.0152',
   '52.5639',
   '4',
   '5',
   '1',
   'BB',
   'Brandenburg',
   'ländlich regional',
   'ländlich',
   'Hintergrund',
   'Ortsteil Hasenholz',
   '',
   '15377'],
  '52': ['52',
   'DEBB054',
   'Potsdam, Zeppelinstr.',
   'Potsdam',
   '',
   '2001-03-07',
   None,
   '13.0375',
   '52.3939',
   '4',
   '1',
   '3',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Zeppelinstr.',
   '30',
   '14471'],
  '53': ['53',
   'DEBB055',
   'Brandenburg a.d. Havel',
   'Brandenburg',
   '',
   '2001-10-01',
   None,
   '12.5523',
   '52.4204',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Lilli-Friesicke-Str.',
   '',
   '14770'],
  '61': ['61',
   'DEBB063',
   'Wittenberge',
   'Wittenberge',
   '',
   '2002-12-03',
   None,
   '11.7385',
   '52.9988',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Dr.-Wilhelm-Külz-Str.',
   '',
   '19322'],
  '62': ['62',
   'DEBB064',
   'Cottbus',
   'Cottbus',
   'COGA',
   '2002-12-10',
   None,
   '14.3345',
   '51.7468',
   '4',
   '1',
   '1',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Gartenstr.',
   '',
   '03050'],
  '63': ['63',
   'DEBB065',
   'Lütte (Belzig)',
   'Amt Belzig, Gemeinde Lütte',
   '',
   '2003-02-14',
   None,
   '12.5614',
   '52.1942',
   '4',
   '5',
   '1',
   'BB',
   'Brandenburg',
   'ländlich regional',
   'ländlich',
   'Hintergrund',
   'Die hohe Heide/Feldstraße',
   '',
   '14806'],
  '64': ['64',
   'DEBB066',
   'Spreewald',
   'Neu Zauche',
   'SPNZ',
   '2003-04-17',
   None,
   '14.0569',
   '51.8975',
   '4',
   '5',
   '1',
   'BB',
   'Brandenburg',
   'ländlich regional',
   'ländlich',
   'Hintergrund',
   '(Am Nordumfluter)',
   '',
   '15913'],
  '65': ['65',
   'DEBB067',
   'Nauen',
   'Nauen',
   '',
   '2025-01-01',
   None,
   '12.8853',
   '52.6085',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Kreuztaler Str.',
   '3',
   '14641'],
  '66': ['66',
   'DEBB068',
   'Bernau, Lohmühlenstr.',
   'Bernau',
   '',
   '2003-01-09',
   None,
   '13.5823',
   '52.6777',
   '4',
   '1',
   '3',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Lohmühlenstr.',
   '42',
   '16321'],
  '71': ['71',
   'DEBB073',
   'Potsdam, Großbeerenstr.',
   'Potsdam-Babelsberg',
   '',
   '2006-06-08',
   None,
   '13.0943',
   '52.3890',
   '4',
   '1',
   '3',
   'BB',
   'Brandenburg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Großbeerenstr.',
   '33',
   '14482'],
  '73': ['73',
   'DEBB075',
   'Potsdam, Groß Glienicke',
   'Potsdam',
   '',
   '2007-04-27',
   None,
   '13.1237',
   '52.4842',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Seeburger Chaussee',
   '2',
   '14476'],
  '81': ['81',
   'DEBB083',
   'Spremberg',
   'Spremberg',
   '',
   '2009-05-06',
   None,
   '14.3764',
   '51.5645',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Lustgartenstr.',
   '4a',
   '03130'],
  '84': ['84',
   'DEBB086',
   'Blankenfelde-Mahlow',
   'Mahlow',
   '',
   '2010-05-25',
   None,
   '13.4243',
   '52.3497',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Schulstr.',
   '1',
   '15831'],
  '90': ['90',
   'DEBB092',
   'Frankfurt (Oder)',
   'Frankfurt (Oder)',
   'FFIS',
   '2013-10-01',
   None,
   '14.5260',
   '52.3347',
   '4',
   '2',
   '1',
   'BB',
   'Brandenburg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Im Sande',
   '',
   '15234'],
  '121': ['121',
   'DEBE010',
   'Berlin Wedding',
   'Berlin',
   '',
   '1984-11-01',
   None,
   '13.3493',
   '52.5430',
   '3',
   '1',
   '1',
   'BE',
   'Berlin',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Amrumer Str./Limburger Str.',
   '',
   '13353'],
  '143': ['143',
   'DEBE032',
   'Berlin Grunewald (3.5 m)',
   'Berlin',
   '',
   '1986-10-01',
   None,
   '13.2251',
   '52.4732',
   '3',
   '6',
   '1',
   'BE',
   'Berlin',
   'ländlich stadtnah',
   'ländlich',
   'Hintergrund',
   'Jagen 91 (Waldstation, H=3.5 m)',
   '',
   '14193'],
  '145': ['145',
   'DEBE034',
   'Berlin Neukölln',
   'Berlin',
   '',
   '1986-03-01',
   None,
   '13.4308',
   '52.4895',
   '3',
   '1',
   '1',
   'BE',
   'Berlin',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Nansenstr.',
   '10',
   '12047'],
  '158': ['158',
   'DEBE051',
   'Berlin Buch',
   'Berlin',
   'MC077',
   '2017-07-24',
   None,
   '13.4831',
   '52.6442',
   '3',
   '2',
   '1',
   'BE',
   'Berlin',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Hobrechtsfelder Chaussee',
   '110-113',
   '13125'],
  '163': ['163',
   'DEBE056',
   'Berlin Friedrichshagen',
   'Berlin',
   '',
   '1994-02-01',
   None,
   '13.6471',
   '52.4477',
   '3',
   '6',
   '1',
   'BE',
   'Berlin',
   'ländlich stadtnah',
   'ländlich',
   'Hintergrund',
   'Müggelseedamm (Wasserwerk)',
   '308',
   '12587'],
  '168': ['168',
   'DEBE061',
   'Berlin Schildhornstraße',
   'Berlin',
   '',
   '1994-11-01',
   None,
   '13.3183',
   '52.4636',
   '3',
   '1',
   '3',
   'BE',
   'Berlin',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Schildhornstr.',
   '76',
   '12163'],
  '172': ['172',
   'DEBE065',
   'Berlin Frankfurter Allee',
   'Berlin',
   '',
   '1993-09-01',
   None,
   '13.4699',
   '52.5141',
   '3',
   '1',
   '3',
   'BE',
   'Berlin',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Frankfurter Allee',
   '86b',
   '10247'],
  '175': ['175',
   'DEBE068',
   'Berlin Mitte',
   'Berlin',
   '',
   '2003-01-01',
   None,
   '13.4188',
   '52.5136',
   '3',
   '1',
   '1',
   'BE',
   'Berlin',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Brückenstr.',
   '6',
   '10179'],
  '176': ['176',
   'DEBE069',
   'Berlin Mariendorfer Damm',
   'Berlin',
   '',
   '2009-01-01',
   None,
   '13.3877',
   '52.4381',
   '3',
   '1',
   '3',
   'BE',
   'Berlin',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Mariendorfer Damm',
   '148',
   '12107'],
  '215': ['215',
   'DEBW004',
   'Eggenstein',
   'Eggenstein',
   '',
   '1976-09-01',
   None,
   '8.4067',
   '49.0766',
   '1',
   '6',
   '1',
   'BW',
   'Baden-Württemberg',
   'ländlich stadtnah',
   'ländlich',
   'Hintergrund',
   'Gewann Zigeunerschlag',
   '',
   '76344'],
  '216': ['216',
   'DEBW005',
   'Mannheim-Nord',
   'Mannheim',
   '',
   '1975-01-01',
   None,
   '8.4653',
   '49.5441',
   '1',
   '2',
   '2',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Industrie',
   'Gew Steinweg',
   '',
   '68307'],
  '220': ['220',
   'DEBW009',
   'Heidelberg',
   'Heidelberg',
   '',
   '1984-01-01',
   None,
   '8.6767',
   '49.4195',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Ecke Berliner-/Blumenthalstr.',
   '',
   '69120'],
  '221': ['221',
   'DEBW010',
   'Wiesloch',
   'Wiesloch',
   '',
   '1986-05-01',
   None,
   '8.7001',
   '49.3007',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'In der Hessel',
   '',
   '69168'],
  '224': ['224',
   'DEBW013',
   'Stuttgart-Bad Cannstatt',
   'Stuttgart',
   '',
   '1981-01-01',
   None,
   '9.2297',
   '48.8088',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Gnesenerstr./Seuberstr.',
   '',
   '70374'],
  '226': ['226',
   'DEBW015',
   'Heilbronn',
   'Heilbronn',
   '',
   '1979-11-01',
   None,
   '9.2248',
   '49.1655',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Hans-Rießer-Straße',
   '2109',
   '74076'],
  '228': ['228',
   'DEBW019',
   'Ulm',
   'Ulm',
   '',
   '1978-10-01',
   None,
   '9.9790',
   '48.3968',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Böblingerstraße',
   '',
   '89077'],
  '231': ['231',
   'DEBW022',
   'Kehl',
   'Kehl',
   '',
   '1982-02-01',
   None,
   '7.8023',
   '48.5782',
   '1',
   '2',
   '2',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Industrie',
   'Rheindamm/Yachthafen',
   '',
   '77694'],
  '232': ['232',
   'DEBW023',
   'Weil am Rhein',
   'Weil am Rhein',
   '',
   '1982-02-01',
   None,
   '7.6333',
   '47.5882',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Zwölfthauen',
   '3',
   '79576'],
  '233': ['233',
   'DEBW024',
   'Ludwigsburg',
   'Ludwigsburg',
   '',
   '1982-03-01',
   None,
   '9.1728',
   '48.8992',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Weimar-/Schweizerstr.',
   '',
   '71636'],
  '236': ['236',
   'DEBW027',
   'Reutlingen',
   'Reutlingen',
   '',
   '1982-02-01',
   None,
   '9.2073',
   '48.4889',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Ebertstraße/Gelände "Pomologie"',
   '',
   '72762'],
  '238': ['238',
   'DEBW029',
   'Aalen',
   'Aalen',
   '',
   '1982-03-01',
   None,
   '10.0963',
   '48.8479',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Bahnhofstraße',
   '115',
   '73430'],
  '240': ['240',
   'DEBW031',
   'Schwarzwald-Süd',
   'Münstertal',
   'Kälbelescheuer',
   '1984-01-01',
   None,
   '7.7645',
   '47.8099',
   '1',
   '5',
   '1',
   'BW',
   'Baden-Württemberg',
   'ländlich regional',
   'ländlich',
   'Hintergrund',
   'Nähe Kälbelescheuer/Kl. Kaibenkopf',
   '',
   '79244'],
  '242': ['242',
   'DEBW033',
   'Pforzheim',
   'Pforzheim',
   '',
   '1989-04-01',
   None,
   '8.6655',
   '48.8890',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Dietlinger-/Wildbaderstr.',
   '',
   '75179'],
  '247': ['247',
   'DEBW038',
   'Friedrichshafen',
   'Friedrichshafen',
   '',
   '1987-01-01',
   None,
   '9.4857',
   '47.6601',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Ehlerstr./Polizeirevier',
   '',
   '88046'],
  '248': ['248',
   'DEBW039',
   'Villingen-Schwenningen',
   'Villingen-Schwenningen',
   '',
   '1987-06-01',
   None,
   '8.4636',
   '48.0487',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Unterer Dammweg',
   '',
   '78050'],
  '251': ['251',
   'DEBW042',
   'Bernhausen',
   'Bernhausen',
   '',
   '2024-01-01',
   None,
   '9.2294',
   '48.6775',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Nürtinger Straße',
   '',
   '70794'],
  '254': ['254',
   'DEBW046',
   'Biberach',
   'Biberach',
   '',
   '1990-11-01',
   None,
   '9.8003',
   '48.0899',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Hans-Liebherr-Straße',
   '',
   '88400'],
  '260': ['260',
   'DEBW052',
   'Konstanz',
   'Konstanz',
   '',
   '1990-09-01',
   None,
   '9.1693',
   '47.6644',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Zasius-/Wallgutstr.',
   '',
   '78462'],
  '264': ['264',
   'DEBW056',
   'Schwäbisch Hall',
   'Schwäbisch Hall',
   '',
   '2024-06-20',
   None,
   '9.7332',
   '49.1079',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Bahngelände',
   '',
   '74523'],
  '267': ['267',
   'DEBW059',
   'Tauberbischofsheim',
   'Tauberbischofsheim',
   '',
   '1990-11-01',
   None,
   '9.6579',
   '49.6348',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Kläranlage',
   '',
   '97941'],
  '276': ['276',
   'DEBW073',
   'Neuenburg',
   'Neuenburg',
   '',
   '1992-11-01',
   None,
   '7.5680',
   '47.8190',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Freiburger Str.',
   '25 a',
   '79395'],
  '279': ['279',
   'DEBW076',
   'Baden-Baden',
   'Baden-Baden',
   '',
   '1993-04-22',
   None,
   '8.2202',
   '48.7731',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Aumattstraße',
   '',
   '76530'],
  '282': ['282',
   'DEBW080',
   'Karlsruhe Reinhold-Frank-Straße',
   'Karlsruhe',
   '',
   '1994-03-15',
   None,
   '8.3872',
   '49.0080',
   '1',
   '1',
   '3',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Reinhold-Frank-Straße',
   '27',
   '76133'],
  '283': ['283',
   'DEBW081',
   'Karlsruhe-Nordwest',
   'Karlsruhe',
   '',
   '1985-03-01',
   None,
   '8.3556',
   '49.0286',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Daimlerstraße',
   '17',
   '76185'],
  '286': ['286',
   'DEBW084',
   'Freiburg',
   'Freiburg',
   '',
   '1979-06-01',
   None,
   '7.8321',
   '48.0015',
   '1',
   '1',
   '1',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Hintergrund',
   'Fehrenbachallee',
   '11',
   '79106'],
  '289': ['289',
   'DEBW087',
   'Schwäbische Alb',
   'Erpfingen',
   'Erpfingen',
   '1994-04-27',
   None,
   '9.2076',
   '48.3458',
   '1',
   '5',
   '1',
   'BW',
   'Baden-Württemberg',
   'ländlich regional',
   'ländlich',
   'Hintergrund',
   'Sportplatz-Gelände',
   '',
   '72820'],
  '299': ['299',
   'DEBW098',
   'Mannheim Friedrichsring',
   'Mannheim',
   '',
   '1994-04-28',
   None,
   '8.4720',
   '49.4926',
   '1',
   '1',
   '3',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Friedrichsring',
   'U2',
   '68161'],
  '300': ['300',
   'DEBW099',
   'Stuttgart Arnulf-Klett-Platz',
   'Stuttgart',
   '',
   '1994-12-06',
   None,
   '9.1807',
   '48.7831',
   '1',
   '1',
   '3',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Arnulf-Klett-Platz',
   '',
   '70173'],
  '308': ['308',
   'DEBW107',
   'Tübingen',
   'Tübingen',
   '',
   '2002-01-22',
   '2025-12-31',
   '9.0512',
   '48.5077',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Derendinger Straße, FlSt.Nr. 1645',
   '',
   '72072'],
  '313': ['313',
   'DEBW112',
   'Gärtringen',
   'Gärtringen',
   '',
   '2005-12-21',
   None,
   '8.9044',
   '48.6456',
   '1',
   '2',
   '1',
   'BW',
   'Baden-Württemberg',
   'vorstädtisches Gebiet',
   'vorstädtisch',
   'Hintergrund',
   'Goethestraße',
   '',
   '71116'],
  '319': ['319',
   'DEBW118',
   'Stuttgart Am Neckartor',
   'Stuttgart',
   '',
   '2003-12-23',
   None,
   '9.1910',
   '48.7881',
   '1',
   '1',
   '3',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Am Neckartor',
   '',
   '70190'],
  '323': ['323',
   'DEBW122',
   'Freiburg Schwarzwaldstraße',
   'Freiburg',
   '',
   '2004-12-27',
   None,
   '7.8599',
   '47.9882',
   '1',
   '1',
   '3',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Schwarzwaldstraße',
   '',
   '79102'],
  '337': ['337',
   'DEBW136',
   'Tübingen Mühlstraße',
   'Tübingen',
   '',
   '2004-01-01',
   None,
   '9.0580',
   '48.5202',
   '1',
   '1',
   '3',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Mühlstraße',
   '',
   '72074'],
  '348': ['348',
   'DEBW147',
   'Reutlingen Lederstraße-Ost',
   'Reutlingen',
   '',
   '2007-03-21',
   None,
   '9.2108',
   '48.4893',
   '1',
   '1',
   '3',
   'BW',
   'Baden-Württemberg',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Lederstraße',
   '',
   '72764'],
  '435': ['435',
   'DEBY001',
   'Ansbach/Residenzstraße',
   'Ansbach',
   '',
   '1989-07-01',
   None,
   '10.5723',
   '49.3049',
   '2',
   '1',
   '3',
   'BY',
   'Bayern',
   'städtisches Gebiet',
   'städtisch',
   'Verkehr',
   'Residenzstraße/Brauhausstraße',
   '',
   '91522'],
  '441': ['441',
   'DEBY007',
   'Augsburg/Bourges-Platz',
   'Augsburg',
   '',
   '1986-08-01',
   None,
   '10.8884',
   '48.3766',
   '2',

In [176]:
columns5 = data5["indices"]
columns5

['station id',
 'station code',
 'station name',
 'station city',
 'station synonym',
 'station active from',
 'station active to',
 'station longitude',
 'station latitude',
 'network id',
 'station setting id',
 'station type id',
 'network code',
 'network name',
 'station setting name',
 'station setting short name',
 'station type name',
 'station street',
 'station street nr',
 'station zip code']

In [178]:
rows5 = [value for key, value in data5["data"].items() if key.isdigit()]
rows5

[['21',
  'DEBB021',
  'Potsdam-Zentrum',
  'Potsdam',
  'PDBA',
  '2009-04-15',
  None,
  '13.0602',
  '52.4014',
  '4',
  '1',
  '1',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Am Bassinplatz',
  '',
  '14467'],
 ['28',
  'DEBB029',
  'Schwedt (Oder)',
  'Schwedt/Oder',
  'SWHE',
  '1993-04-06',
  None,
  '14.2851',
  '53.0643',
  '4',
  '2',
  '2',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Industrie',
  'Helbigstr.',
  '',
  '16303'],
 ['31',
  'DEBB032',
  'Eisenhüttenstadt',
  'Eisenhüttenstadt',
  'EHST',
  '1993-04-20',
  None,
  '14.6382',
  '52.1463',
  '4',
  '2',
  '2',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Industrie',
  'Karl-Marx-Str.',
  '35',
  '15890'],
 ['42',
  'DEBB044',
  'Cottbus, Bahnhofstr.',
  'Cottbus',
  'COBA',
  '2012-09-25',
  None,
  '14.3280',
  '51.7566',
  '4',
  '1',
  '3',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Bahnhofstr.',
  '55',
  '03046'],
 ['43',
  'DEBB045',
  'Frankfurt (Oder), Leipziger Str.',
  'Frankfurt (Oder)',
  'FFLS',
  '1995-08-01',
  None,
  '14.5386',
  '52.3373',
  '4',
  '1',
  '3',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Leipziger Str.',
  '',
  '15232'],
 ['46',
  'DEBB048',
  'Neuruppin',
  'Neuruppin',
  'NEHA',
  '1998-06-11',
  None,
  '12.8095',
  '52.9319',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Gerhart-Hauptmann-Str.',
  '18/1',
  '16816'],
 ['47',
  'DEBB049',
  'Brandenburg, Neuendorfer Str.',
  'Brandenburg',
  'BRNE',
  '2013-10-15',
  None,
  '12.5486',
  '52.4094',
  '4',
  '1',
  '3',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Neuendorfer Str.',
  '',
  '14770'],
 ['51',
  'DEBB053',
  'Hasenholz (Buckow)',
  'Buckow',
  'HAHO',
  '2000-11-21',
  None,
  '14.0152',
  '52.5639',
  '4',
  '5',
  '1',
  'BB',
  'Brandenburg',
  'ländlich regional',
  'ländlich',
  'Hintergrund',
  'Ortsteil Hasenholz',
  '',
  '15377'],
 ['52',
  'DEBB054',
  'Potsdam, Zeppelinstr.',
  'Potsdam',
  '',
  '2001-03-07',
  None,
  '13.0375',
  '52.3939',
  '4',
  '1',
  '3',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Zeppelinstr.',
  '30',
  '14471'],
 ['53',
  'DEBB055',
  'Brandenburg a.d. Havel',
  'Brandenburg',
  '',
  '2001-10-01',
  None,
  '12.5523',
  '52.4204',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Lilli-Friesicke-Str.',
  '',
  '14770'],
 ['61',
  'DEBB063',
  'Wittenberge',
  'Wittenberge',
  '',
  '2002-12-03',
  None,
  '11.7385',
  '52.9988',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Dr.-Wilhelm-Külz-Str.',
  '',
  '19322'],
 ['62',
  'DEBB064',
  'Cottbus',
  'Cottbus',
  'COGA',
  '2002-12-10',
  None,
  '14.3345',
  '51.7468',
  '4',
  '1',
  '1',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Gartenstr.',
  '',
  '03050'],
 ['63',
  'DEBB065',
  'Lütte (Belzig)',
  'Amt Belzig, Gemeinde Lütte',
  '',
  '2003-02-14',
  None,
  '12.5614',
  '52.1942',
  '4',
  '5',
  '1',
  'BB',
  'Brandenburg',
  'ländlich regional',
  'ländlich',
  'Hintergrund',
  'Die hohe Heide/Feldstraße',
  '',
  '14806'],
 ['64',
  'DEBB066',
  'Spreewald',
  'Neu Zauche',
  'SPNZ',
  '2003-04-17',
  None,
  '14.0569',
  '51.8975',
  '4',
  '5',
  '1',
  'BB',
  'Brandenburg',
  'ländlich regional',
  'ländlich',
  'Hintergrund',
  '(Am Nordumfluter)',
  '',
  '15913'],
 ['65',
  'DEBB067',
  'Nauen',
  'Nauen',
  '',
  '2025-01-01',
  None,
  '12.8853',
  '52.6085',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Kreuztaler Str.',
  '3',
  '14641'],
 ['66',
  'DEBB068',
  'Bernau, Lohmühlenstr.',
  'Bernau',
  '',
  '2003-01-09',
  None,
  '13.5823',
  '52.6777',
  '4',
  '1',
  '3',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Lohmühlenstr.',
  '42',
  '16321'],
 ['71',
  'DEBB073',
  'Potsdam, Großbeerenstr.',
  'Potsdam-Babelsberg',
  '',
  '2006-06-08',
  None,
  '13.0943',
  '52.3890',
  '4',
  '1',
  '3',
  'BB',
  'Brandenburg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Großbeerenstr.',
  '33',
  '14482'],
 ['73',
  'DEBB075',
  'Potsdam, Groß Glienicke',
  'Potsdam',
  '',
  '2007-04-27',
  None,
  '13.1237',
  '52.4842',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Seeburger Chaussee',
  '2',
  '14476'],
 ['81',
  'DEBB083',
  'Spremberg',
  'Spremberg',
  '',
  '2009-05-06',
  None,
  '14.3764',
  '51.5645',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Lustgartenstr.',
  '4a',
  '03130'],
 ['84',
  'DEBB086',
  'Blankenfelde-Mahlow',
  'Mahlow',
  '',
  '2010-05-25',
  None,
  '13.4243',
  '52.3497',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Schulstr.',
  '1',
  '15831'],
 ['90',
  'DEBB092',
  'Frankfurt (Oder)',
  'Frankfurt (Oder)',
  'FFIS',
  '2013-10-01',
  None,
  '14.5260',
  '52.3347',
  '4',
  '2',
  '1',
  'BB',
  'Brandenburg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Im Sande',
  '',
  '15234'],
 ['121',
  'DEBE010',
  'Berlin Wedding',
  'Berlin',
  '',
  '1984-11-01',
  None,
  '13.3493',
  '52.5430',
  '3',
  '1',
  '1',
  'BE',
  'Berlin',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Amrumer Str./Limburger Str.',
  '',
  '13353'],
 ['143',
  'DEBE032',
  'Berlin Grunewald (3.5 m)',
  'Berlin',
  '',
  '1986-10-01',
  None,
  '13.2251',
  '52.4732',
  '3',
  '6',
  '1',
  'BE',
  'Berlin',
  'ländlich stadtnah',
  'ländlich',
  'Hintergrund',
  'Jagen 91 (Waldstation, H=3.5 m)',
  '',
  '14193'],
 ['145',
  'DEBE034',
  'Berlin Neukölln',
  'Berlin',
  '',
  '1986-03-01',
  None,
  '13.4308',
  '52.4895',
  '3',
  '1',
  '1',
  'BE',
  'Berlin',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Nansenstr.',
  '10',
  '12047'],
 ['158',
  'DEBE051',
  'Berlin Buch',
  'Berlin',
  'MC077',
  '2017-07-24',
  None,
  '13.4831',
  '52.6442',
  '3',
  '2',
  '1',
  'BE',
  'Berlin',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Hobrechtsfelder Chaussee',
  '110-113',
  '13125'],
 ['163',
  'DEBE056',
  'Berlin Friedrichshagen',
  'Berlin',
  '',
  '1994-02-01',
  None,
  '13.6471',
  '52.4477',
  '3',
  '6',
  '1',
  'BE',
  'Berlin',
  'ländlich stadtnah',
  'ländlich',
  'Hintergrund',
  'Müggelseedamm (Wasserwerk)',
  '308',
  '12587'],
 ['168',
  'DEBE061',
  'Berlin Schildhornstraße',
  'Berlin',
  '',
  '1994-11-01',
  None,
  '13.3183',
  '52.4636',
  '3',
  '1',
  '3',
  'BE',
  'Berlin',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Schildhornstr.',
  '76',
  '12163'],
 ['172',
  'DEBE065',
  'Berlin Frankfurter Allee',
  'Berlin',
  '',
  '1993-09-01',
  None,
  '13.4699',
  '52.5141',
  '3',
  '1',
  '3',
  'BE',
  'Berlin',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Frankfurter Allee',
  '86b',
  '10247'],
 ['175',
  'DEBE068',
  'Berlin Mitte',
  'Berlin',
  '',
  '2003-01-01',
  None,
  '13.4188',
  '52.5136',
  '3',
  '1',
  '1',
  'BE',
  'Berlin',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Brückenstr.',
  '6',
  '10179'],
 ['176',
  'DEBE069',
  'Berlin Mariendorfer Damm',
  'Berlin',
  '',
  '2009-01-01',
  None,
  '13.3877',
  '52.4381',
  '3',
  '1',
  '3',
  'BE',
  'Berlin',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Mariendorfer Damm',
  '148',
  '12107'],
 ['215',
  'DEBW004',
  'Eggenstein',
  'Eggenstein',
  '',
  '1976-09-01',
  None,
  '8.4067',
  '49.0766',
  '1',
  '6',
  '1',
  'BW',
  'Baden-Württemberg',
  'ländlich stadtnah',
  'ländlich',
  'Hintergrund',
  'Gewann Zigeunerschlag',
  '',
  '76344'],
 ['216',
  'DEBW005',
  'Mannheim-Nord',
  'Mannheim',
  '',
  '1975-01-01',
  None,
  '8.4653',
  '49.5441',
  '1',
  '2',
  '2',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Industrie',
  'Gew Steinweg',
  '',
  '68307'],
 ['220',
  'DEBW009',
  'Heidelberg',
  'Heidelberg',
  '',
  '1984-01-01',
  None,
  '8.6767',
  '49.4195',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Ecke Berliner-/Blumenthalstr.',
  '',
  '69120'],
 ['221',
  'DEBW010',
  'Wiesloch',
  'Wiesloch',
  '',
  '1986-05-01',
  None,
  '8.7001',
  '49.3007',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'In der Hessel',
  '',
  '69168'],
 ['224',
  'DEBW013',
  'Stuttgart-Bad Cannstatt',
  'Stuttgart',
  '',
  '1981-01-01',
  None,
  '9.2297',
  '48.8088',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Gnesenerstr./Seuberstr.',
  '',
  '70374'],
 ['226',
  'DEBW015',
  'Heilbronn',
  'Heilbronn',
  '',
  '1979-11-01',
  None,
  '9.2248',
  '49.1655',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Hans-Rießer-Straße',
  '2109',
  '74076'],
 ['228',
  'DEBW019',
  'Ulm',
  'Ulm',
  '',
  '1978-10-01',
  None,
  '9.9790',
  '48.3968',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Böblingerstraße',
  '',
  '89077'],
 ['231',
  'DEBW022',
  'Kehl',
  'Kehl',
  '',
  '1982-02-01',
  None,
  '7.8023',
  '48.5782',
  '1',
  '2',
  '2',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Industrie',
  'Rheindamm/Yachthafen',
  '',
  '77694'],
 ['232',
  'DEBW023',
  'Weil am Rhein',
  'Weil am Rhein',
  '',
  '1982-02-01',
  None,
  '7.6333',
  '47.5882',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Zwölfthauen',
  '3',
  '79576'],
 ['233',
  'DEBW024',
  'Ludwigsburg',
  'Ludwigsburg',
  '',
  '1982-03-01',
  None,
  '9.1728',
  '48.8992',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Weimar-/Schweizerstr.',
  '',
  '71636'],
 ['236',
  'DEBW027',
  'Reutlingen',
  'Reutlingen',
  '',
  '1982-02-01',
  None,
  '9.2073',
  '48.4889',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Ebertstraße/Gelände "Pomologie"',
  '',
  '72762'],
 ['238',
  'DEBW029',
  'Aalen',
  'Aalen',
  '',
  '1982-03-01',
  None,
  '10.0963',
  '48.8479',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Bahnhofstraße',
  '115',
  '73430'],
 ['240',
  'DEBW031',
  'Schwarzwald-Süd',
  'Münstertal',
  'Kälbelescheuer',
  '1984-01-01',
  None,
  '7.7645',
  '47.8099',
  '1',
  '5',
  '1',
  'BW',
  'Baden-Württemberg',
  'ländlich regional',
  'ländlich',
  'Hintergrund',
  'Nähe Kälbelescheuer/Kl. Kaibenkopf',
  '',
  '79244'],
 ['242',
  'DEBW033',
  'Pforzheim',
  'Pforzheim',
  '',
  '1989-04-01',
  None,
  '8.6655',
  '48.8890',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Dietlinger-/Wildbaderstr.',
  '',
  '75179'],
 ['247',
  'DEBW038',
  'Friedrichshafen',
  'Friedrichshafen',
  '',
  '1987-01-01',
  None,
  '9.4857',
  '47.6601',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Ehlerstr./Polizeirevier',
  '',
  '88046'],
 ['248',
  'DEBW039',
  'Villingen-Schwenningen',
  'Villingen-Schwenningen',
  '',
  '1987-06-01',
  None,
  '8.4636',
  '48.0487',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Unterer Dammweg',
  '',
  '78050'],
 ['251',
  'DEBW042',
  'Bernhausen',
  'Bernhausen',
  '',
  '2024-01-01',
  None,
  '9.2294',
  '48.6775',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Nürtinger Straße',
  '',
  '70794'],
 ['254',
  'DEBW046',
  'Biberach',
  'Biberach',
  '',
  '1990-11-01',
  None,
  '9.8003',
  '48.0899',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Hans-Liebherr-Straße',
  '',
  '88400'],
 ['260',
  'DEBW052',
  'Konstanz',
  'Konstanz',
  '',
  '1990-09-01',
  None,
  '9.1693',
  '47.6644',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Zasius-/Wallgutstr.',
  '',
  '78462'],
 ['264',
  'DEBW056',
  'Schwäbisch Hall',
  'Schwäbisch Hall',
  '',
  '2024-06-20',
  None,
  '9.7332',
  '49.1079',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Bahngelände',
  '',
  '74523'],
 ['267',
  'DEBW059',
  'Tauberbischofsheim',
  'Tauberbischofsheim',
  '',
  '1990-11-01',
  None,
  '9.6579',
  '49.6348',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Kläranlage',
  '',
  '97941'],
 ['276',
  'DEBW073',
  'Neuenburg',
  'Neuenburg',
  '',
  '1992-11-01',
  None,
  '7.5680',
  '47.8190',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Freiburger Str.',
  '25 a',
  '79395'],
 ['279',
  'DEBW076',
  'Baden-Baden',
  'Baden-Baden',
  '',
  '1993-04-22',
  None,
  '8.2202',
  '48.7731',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Aumattstraße',
  '',
  '76530'],
 ['282',
  'DEBW080',
  'Karlsruhe Reinhold-Frank-Straße',
  'Karlsruhe',
  '',
  '1994-03-15',
  None,
  '8.3872',
  '49.0080',
  '1',
  '1',
  '3',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Reinhold-Frank-Straße',
  '27',
  '76133'],
 ['283',
  'DEBW081',
  'Karlsruhe-Nordwest',
  'Karlsruhe',
  '',
  '1985-03-01',
  None,
  '8.3556',
  '49.0286',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Daimlerstraße',
  '17',
  '76185'],
 ['286',
  'DEBW084',
  'Freiburg',
  'Freiburg',
  '',
  '1979-06-01',
  None,
  '7.8321',
  '48.0015',
  '1',
  '1',
  '1',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Fehrenbachallee',
  '11',
  '79106'],
 ['289',
  'DEBW087',
  'Schwäbische Alb',
  'Erpfingen',
  'Erpfingen',
  '1994-04-27',
  None,
  '9.2076',
  '48.3458',
  '1',
  '5',
  '1',
  'BW',
  'Baden-Württemberg',
  'ländlich regional',
  'ländlich',
  'Hintergrund',
  'Sportplatz-Gelände',
  '',
  '72820'],
 ['299',
  'DEBW098',
  'Mannheim Friedrichsring',
  'Mannheim',
  '',
  '1994-04-28',
  None,
  '8.4720',
  '49.4926',
  '1',
  '1',
  '3',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Friedrichsring',
  'U2',
  '68161'],
 ['300',
  'DEBW099',
  'Stuttgart Arnulf-Klett-Platz',
  'Stuttgart',
  '',
  '1994-12-06',
  None,
  '9.1807',
  '48.7831',
  '1',
  '1',
  '3',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Arnulf-Klett-Platz',
  '',
  '70173'],
 ['308',
  'DEBW107',
  'Tübingen',
  'Tübingen',
  '',
  '2002-01-22',
  '2025-12-31',
  '9.0512',
  '48.5077',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Derendinger Straße, FlSt.Nr. 1645',
  '',
  '72072'],
 ['313',
  'DEBW112',
  'Gärtringen',
  'Gärtringen',
  '',
  '2005-12-21',
  None,
  '8.9044',
  '48.6456',
  '1',
  '2',
  '1',
  'BW',
  'Baden-Württemberg',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Goethestraße',
  '',
  '71116'],
 ['319',
  'DEBW118',
  'Stuttgart Am Neckartor',
  'Stuttgart',
  '',
  '2003-12-23',
  None,
  '9.1910',
  '48.7881',
  '1',
  '1',
  '3',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Am Neckartor',
  '',
  '70190'],
 ['323',
  'DEBW122',
  'Freiburg Schwarzwaldstraße',
  'Freiburg',
  '',
  '2004-12-27',
  None,
  '7.8599',
  '47.9882',
  '1',
  '1',
  '3',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Schwarzwaldstraße',
  '',
  '79102'],
 ['337',
  'DEBW136',
  'Tübingen Mühlstraße',
  'Tübingen',
  '',
  '2004-01-01',
  None,
  '9.0580',
  '48.5202',
  '1',
  '1',
  '3',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Mühlstraße',
  '',
  '72074'],
 ['348',
  'DEBW147',
  'Reutlingen Lederstraße-Ost',
  'Reutlingen',
  '',
  '2007-03-21',
  None,
  '9.2108',
  '48.4893',
  '1',
  '1',
  '3',
  'BW',
  'Baden-Württemberg',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Lederstraße',
  '',
  '72764'],
 ['435',
  'DEBY001',
  'Ansbach/Residenzstraße',
  'Ansbach',
  '',
  '1989-07-01',
  None,
  '10.5723',
  '49.3049',
  '2',
  '1',
  '3',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Residenzstraße/Brauhausstraße',
  '',
  '91522'],
 ['441',
  'DEBY007',
  'Augsburg/Bourges-Platz',
  'Augsburg',
  '',
  '1986-08-01',
  None,
  '10.8884',
  '48.3766',
  '2',
  '1',
  '1',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Bourges-Platz',
  '',
  '86153'],
 ['443',
  'DEBY009',
  'Bamberg/Löwenbrücke',
  'Bamberg',
  '',
  '1978-01-01',
  None,
  '10.8877',
  '49.8983',
  '2',
  '1',
  '1',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Löwenbrücke',
  '',
  '96047'],
 ['446',
  'DEBY012',
  'Burghausen/Marktler Straße',
  'Burghausen',
  '',
  '1976-01-01',
  None,
  '12.8293',
  '48.1772',
  '2',
  '2',
  '1',
  'BY',
  'Bayern',
  'vorstädtisches Gebiet',
  'vorstädtisch',
  'Hintergrund',
  'Klausenstraße',
  '',
  '84489'],
 ['466',
  'DEBY032',
  'Kulmbach/Konrad-Adenauer-Straße',
  'Kulmbach',
  '',
  '1988-10-01',
  None,
  '11.4426',
  '50.1031',
  '2',
  '1',
  '1',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Konrad-Adenauer-Straße',
  '',
  '95326'],
 ['467',
  'DEBY033',
  'Landshut/Podewilsstraße',
  'Landshut',
  '',
  '1985-12-01',
  None,
  '12.1571',
  '48.5398',
  '2',
  '1',
  '3',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Podewilsstraße',
  '',
  '84028'],
 ['469',
  'DEBY035',
  'Lindau (Bodensee)/Friedrichshafener Straße',
  'Lindau (Bodensee)',
  '',
  '2013-12-12',
  None,
  '9.6889',
  '47.5575',
  '2',
  '1',
  '3',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Friedrichshafener Straße',
  '',
  '88131'],
 ['471',
  'DEBY037',
  'München/Stachus',
  'München',
  '',
  '1978-01-01',
  None,
  '11.5649',
  '48.1373',
  '2',
  '1',
  '3',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Sonnenstraße',
  '',
  '80335'],
 ['473',
  'DEBY039',
  'München/Lothstraße',
  'München',
  '',
  '1978-01-01',
  None,
  '11.5547',
  '48.1545',
  '2',
  '1',
  '1',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Lothstraße',
  '62',
  '80335'],
 ['486',
  'DEBY052',
  'Neu-Ulm/Gabelsbergerstraße',
  'Neu-Ulm',
  '',
  '1978-01-01',
  None,
  '10.0083',
  '48.3971',
  '2',
  '1',
  '1',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Hintergrund',
  'Gabelsberger-/Bahnhofstraße',
  '',
  '89231'],
 ['490',
  'DEBY056',
  'Fürth/Theresienstraße',
  'Fürth',
  '',
  '1990-11-01',
  None,
  '10.9847',
  '49.4722',
  '2',
  '1',
  '3',
  'BY',
  'Bayern',
  'städtisches Gebiet',
  'städtisch',
  'Verkehr',
  'Theresienstraße',
  '',
  '90762'],
 ['497',
  'DEBY063',

In [180]:
df = pd.DataFrame(rows5, columns=columns5)
df

,station id,station code,station name,station city,station synonym,station active from,station active to,station longitude,station latitude,network id,station setting id,station type id,network code,network name,station setting name,station setting short name,station type name,station street,station street nr,station zip code
0,21,DEBB021,Potsdam-Zentrum,Potsdam,PDBA,2009-04-15,NaN,13.0602,52.4014,4,1,1,BB,Brandenburg,städtisches Gebiet,städtisch,Hintergrund,Am Bassinplatz,,14467
1,28,DEBB029,Schwedt (Oder),Schwedt/Oder,SWHE,1993-04-06,NaN,14.2851,53.0643,4,2,2,BB,Brandenburg,vorstädtisches Gebiet,vorstädtisch,Industrie,Helbigstr.,,16303
2,31,DEBB032,Eisenhüttenstadt,Eisenhüttenstadt,EHST,1993-04-20,NaN,14.6382,52.1463,4,2,2,BB,Brandenburg,vorstädtisches Gebiet,vorstädtisch,Industrie,Karl-Marx-Str.,35,15890
3,42,DEBB044,"Cottbus, Bahnhofstr.",Cottbus,COBA,2012-09-25,NaN,14.3280,51.7566,4,1,3,BB,Brandenburg,städtisches Gebiet,städtisch,Verkehr,Bahnhofstr.,55,03046
4,43,DEBB045,"Frankfurt (Oder), Leipziger Str.",Frankfurt (Oder),FFLS,1995-08-01,NaN,14.5386,52.3373,4,1,3,BB,Brandenburg,städtisches Gebiet,städtisch,Verkehr,Leipziger Str.,,15232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,1679,DESN091,Zwickau-Werdauer Str.,Zwickau,ZwickauW,2011-10-20,NaN,12.4866,50.7204,13,1,3,SN,Sachsen,städtisches Gebiet,städtisch,Verkehr,Werdauer Str./Crimmitschauer Str.,,08056
421,9523,DEBW241,Ludwigsburg Schlossstraße,Ludwigsburg,,2020-01-01,NaN,9.1937,48.8982,1,1,3,BW,Baden-Württemberg,städtisches Gebiet,städtisch,Verkehr,Schlossstraße,21,71634
422,10351,DESH062,Norderstedt Bekwisch,Norderstedt,,2024-01-01,NaN,9.9906,53.6760,15,1,1,SH,Schleswig-Holstein,städtisches Gebiet,städtisch,Hintergrund,Bekwisch,9,22848
423,10388,DEST144,Magdeburg City-Tunnel,Magdeburg,,2024-01-01,NaN,11.6306,52.1312,14,1,3,ST,Sachsen-Anhalt,städtisches Gebiet,städtisch,Verkehr,Ernst-Reuter-Allee,,39104
424,10470,DEBW249,Stuttgart Hauptstätter Straße,Stuttgart,,2024-01-01,NaN,9.1709,48.7662,1,1,3,BW,Baden-Württemberg,städtisches Gebiet,städtisch,Verkehr,Hauptstätter Straße,121,70187

In [182]:
df.to_csv("get_all_stations.csv", index=False)

In [159]:
url = "https://luftdaten.umweltbundesamt.de/api/air-data/v4/measures/json?date_from=2025-09-01&time_from=9&date_to=2025-09-02&time_to=9&station=28&component=1&scope=1" 

r = requests.get(url, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data5= r.json()

URL: https://luftdaten.umweltbundesamt.de/api/air-data/v4/measures/json?date_from=2025-09-01&time_from=9&date_to=2025-09-02&time_to=9&station=28&component=1&scope=1
Status: 200 OK
CT: application/json

In [160]:
data5

{'request': {'component': '1',
  'scope': '1',
  'station': '28',
  'date_from': '2025-09-01',
  'date_to': '2025-09-02',
  'time_from': '09:00:00',
  'time_to': '09:00:00',
  'recent': False,
  'index': 'id',
  'lang': 'en',
  'datetime_from': '2025-09-01 08:00:00',
  'datetime_to': '2025-09-02 08:00:00'},
 'indices': {'data': {'station id': {'date start': ['component id',
     'scope id',
     'value',
     'date end',
     'index']}}},
 'data': {'28': {'2025-09-01 11:00:00': [1,
    1,
    12,
    '2025-09-01 12:00:00',
    '2']}}}

In [161]:
df = json_normalize(data5)
df

,request.component,request.scope,request.station,request.date_from,request.date_to,request.time_from,request.time_to,request.recent,request.index,request.lang,request.datetime_from,request.datetime_to,indices.data.station id.date start,data.28.2025-09-01 11:00:00
0,1,1,28,2025-09-01,2025-09-02,09:00:00,09:00:00,False,id,en,2025-09-01 08:00:00,2025-09-02 08:00:00,"[component id, scope id, value, date end, index]","[1, 1, 12, 2025-09-01 12:00:00, 2]"

In [162]:
df_job_SH.to_csv("jobs_SH_500.csv", index=False)

NameError: name 'df_job_SH' is not defined