# Get daily average values for air pollution in Poland from 2016-2026 using openAQ API

In [1]:
import requests
import pandas as pd 
import time

### List possible parameters (e.g. PM10, PM2.5, NO2)

In [ ]:
api_url = "https://api.openaq.org/v3/parameters"

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, headers=headers)
response = response.json()

response

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 46},
 'results': [{'id': 1,
   'name': 'pm10',
   'units': 'µg/m³',
   'displayName': 'PM10',
   'description': 'Particulate matter less than 10 micrometers in diameter mass concentration'},
  {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': 'PM2.5',
   'description': 'Particulate matter less than 2.5 micrometers in diameter mass concentration'},
  {'id': 3,
   'name': 'o3',
   'units': 'µg/m³',
   'displayName': 'O₃ mass',
   'description': 'Ozone mass concentration'},
  {'id': 4,
   'name': 'co',
   'units': 'µg/m³',
   'displayName': 'CO mass',
   'description': 'Carbon Monoxide mass concentration'},
  {'id': 5,
   'name': 'no2',
   'units': 'µg/m³',
   'displayName': 'NO₂ mass',
   'description': 'Nitrogen Dioxide mass concentration'},
  {'id': 6,
   'name': 'so2',
   'units': 'µg/m³',
   'displayName': 'SO₂ mass',
   'description': 'Sulfur Dioxide mass concentration'},
  {'id': 7,
   'name': 'no2',
   'units': 'ppm',
   'displayName': 'NO₂',
   'description': 'Nitrogen Dioxide concentration'},
  {'id': 8,
   'name': 'co',
   'units': 'ppm',
   'displayName': 'CO',
   'description': 'Carbon Monoxide concentration'},
  {'id': 9,
   'name': 'so2',
   'units': 'ppm',
   'displayName': 'SO₂',
   'description': 'Sulfur Dioxide concentration'},
  {'id': 10,
   'name': 'o3',
   'units': 'ppm',
   'displayName': 'O₃',
   'description': 'Ozone concentration'},
  {'id': 11,
   'name': 'bc',
   'units': 'µg/m³',
   'displayName': 'BC',
   'description': 'Black Carbon mass concentration'},
  {'id': 15,
   'name': 'no2',
   'units': 'ppb',
   'displayName': 'NO₂',
   'description': None},
  {'id': 19,
   'name': 'pm1',
   'units': 'µg/m³',
   'displayName': 'PM1',
   'description': 'Particulate matter less than 1 micrometer in diameter mass concentration'},
  {'id': 21,
   'name': 'co2',
   'units': 'ppm',
   'displayName': 'CO₂',
   'description': 'Carbon Dioxide concentration'},
  {'id': 22,
   'name': 'wind_direction',
   'units': 'deg',
   'displayName': 'Wind direction',
   'description': 'Direction that the wind originates from'},
  {'id': 23,
   'name': 'nox',
   'units': 'ppb',
   'displayName': 'NOX',
   'description': None},
  {'id': 24,
   'name': 'no',
   'units': 'ppb',
   'displayName': 'NO',
   'description': None},
  {'id': 27,
   'name': 'nox',
   'units': 'µg/m³',
   'displayName': 'NOx mass',
   'description': 'Nitrogen Oxides mass concentration'},
  {'id': 28,
   'name': 'ch4',
   'units': 'ppm',
   'displayName': 'CH₄',
   'description': 'Methane concentration'},
  {'id': 32,
   'name': 'o3',
   'units': 'ppb',
   'displayName': 'O₃',
   'description': None},
  {'id': 33,
   'name': 'ufp',
   'units': 'particles/cm³',
   'displayName': 'UFP count',
   'description': 'Ultrafine Particles count concentration'},
  {'id': 34,
   'name': 'wind_speed',
   'units': 'm/s',
   'displayName': 'Wind speed',
   'description': 'Average wind speed in meters per second'},
  {'id': 35,
   'name': 'no',
   'units': 'ppm',
   'displayName': 'NO',
   'description': 'Nitrogen Monoxide concentration'},
  {'id': 95,
   'name': 'pressure',
   'units': 'hpa',
   'displayName': 'Atmospheric pressure',
   'description': 'Atmospheric or barometric pressure'},
  {'id': 97,
   'name': 'pm25-old',
   'units': 'ugm3',
   'displayName': None,
   'description': None},
  {'id': 98,
   'name': 'relativehumidity',
   'units': '%',
   'displayName': 'RH',
   'description': None},
  {'id': 100,
   'name': 'temperature',
   'units': 'c',
   'displayName': 'Temperature (C)',
   'description': None},
  {'id': 101,
   'name': 'so2',
   'units': 'ppb',
   'displayName': 'SO₂',
   'description': None},
  {'id': 102,
   'name': 'co',
   'units': 'ppb',
   'displayName': 'CO',
   'description': None},
  {'id': 125,
   'name': 'um003',
   'units': 'particles/cm³',
   'displayName': 'PM0.3 count',
   'description': None},
  {'id': 126,
   'name': 'um010',
   'units': 'particles/cm³',
   'displayName': 'PM1 count',
   'description': 'PM1 count'},
  {'id': 128,
   'name': 'temperature',
   'units': 'f',
   'displayName': 'Temperature (F)',
   'description': None},
  {'id': 130,
   'name': 'um025',
   'units': 'particles/cm³',
   'displayName': 'PM2.5 count',
   'description': 'PM2.5 count'},
  {'id': 132,
   'name': 'pressure',
   'units': 'mb',
   'displayName': 'Pressure',
   'description': None},
  {'id': 134,
   'name': 'humidity',
   'units': '%',
   'displayName': 'H',
   'description': None},
  {'id': 135,
   'name': 'um100',
   'units': 'particles/cm³',
   'displayName': 'PM10 count',
   'description': 'PM10 count'},
  {'id': 19840,
   'name': 'nox',
   'units': 'ppm',
   'displayName': 'NOx',
   'description': 'Nitrogen Oxides concentration'},
  {'id': 19843,
   'name': 'no',
   'units': 'µg/m³',
   'displayName': 'NO mass',
   'description': 'Nitrogen Monoxide mass concentration'},
  {'id': 19844,
   'name': 'pm4',
   'units': 'µg/m³',
   'displayName': 'PM4.0',
   'description': 'Particulate matter less than 4 micrometers in diameter mass concentration'},
  {'id': 19860,
   'name': 'pm25',
   'units': 'ppm',
   'displayName': None,
   'description': None},
  {'id': 19861,
   'name': 'bc_375',
   'units': 'ng/m³',
   'displayName': 'BC 375nm',
   'description': 'Black Carbon mass concentration 375nm '},
  {'id': 19862,
   'name': 'bc_470',
   'units': 'ng/m³',
   'displayName': 'BC 470nm',
   'description': 'Black Carbon mass concentration 470nm '},
  {'id': 19863,
   'name': 'bc_528',
   'units': 'ng/m³',
   'displayName': 'BC 528nm',
   'description': 'Black Carbon mass concentration 528nm '},
  {'id': 19864,
   'name': 'bc_625',
   'units': 'ng/m³',
   'displayName': 'BC 625nm',
   'description': 'Black Carbon mass concentration 625nm '},
  {'id': 19865,
   'name': 'bc_880',
   'units': 'ng/m³',
   'displayName': 'BC 880nm',
   'description': 'Black Carbon mass concentration 880nm '},
  {'id': 19866,
   'name': 'bc_370',
   'units': 'ng/m³',
   'displayName': 'BC 370nm',
   'description': 'Black Carbon mass concentration 375nm '}]}

# PM10

### Get all stations located in Poland that measure PM10
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "PL",   # only consider stations located in Poland
    "parameters_id": 1,   # PM10 
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm10 = df_sorted

df_top_pm10

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
3,2511,Reja,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4887, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.55094028, 'longitude': 19.7052...",None,"[19.70527778, 52.55094028, 19.70527778, 52.550...",None,2016-01-30 01:00:00+00:00,2017-01-08 08:00:00+00:00
0,28,Ursynów,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5009, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 52.16077306, 'longitude': 21.0391...",None,"[21.03916667, 52.16077306, 21.03916667, 52.160...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
1,43,Konarskiego,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4990, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.17203333, 'longitude': 22.2727...",None,"[22.27277778, 52.17203333, 22.27277778, 52.172...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
2,2467,Marszałkowska,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4744, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.22517222, 'longitude': 21.8931...",None,"[21.89311111, 52.22517222, 21.89311111, 52.225...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
4,2531,Komunikacyjna,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5028, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.21929306, 'longitude': 21.0058...",None,"[21.00583333, 52.21929306, 21.00583333, 52.219...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,3362953,"Tomaszów Lubelski, ul. Janusza Petera",Tomaszów Lubelski,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11981591, 'name': 'pm10 µg/m³', 'param...","{'latitude': 50.444128, 'longitude': 23.421553}","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[23.421553, 50.444128, 23.421553, 50.444128]",None,2025-01-10 10:00:00+00:00,2025-10-10 14:00:00+00:00
304,3377216,"Nysa, ul. Rodziewiczówny 1",Nysa,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12087775, 'name': 'pm10 µg/m³', 'param...","{'latitude': 50.460992, 'longitude': 17.331499}","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[17.331499, 50.460992, 17.331499, 50.460992]",None,2025-01-21 08:00:00+00:00,2025-10-10 15:00:00+00:00
305,3616712,"Katowice, ul. Dudy-Gracza",Katowice,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12405264, 'name': 'no2 µg/m³', 'parame...","{'latitude': 50.25848299999999, 'longitude': 1...","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[19.036217, 50.25848299999999, 19.036217, 50.2...",None,2025-03-07 13:00:00+00:00,2025-10-10 15:00:00+00:00
306,5554541,"Warszawa, al. Solidarności",Warszawa,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13952345, 'name': 'no2 µg/m³', 'parame...","{'latitude': 52.243573, 'longitude': 20.999214}","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[20.999214, 52.243573, 20.999214, 52.243573]",None,2025-08-25 08:00:00+00:00,2025-10-10 13:00:00+00:00
307,5554542,"Warszawa, ul. Grochowska",Warszawa,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13952348, 'name': 'no2 µg/m³', 'parame...","{'latitude': 52.24570400000001, 'longitude': 2...","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[21.080427, 52.24570400000001, 21.080427, 52.2...",None,2025-08-25 08:00:00+00:00,2025-10-10 13:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [8]:
rows = []

for _, station in df_top_pm10.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM10 behalten
        if sensor["parameter"]["id"] == 1:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm10_sensors = pd.DataFrame(rows)

df_pm10_sensors

     station_id                           station_name  sensor_id sensor_name
0          2511                                   Reja       4898  pm10 µg/m³
1            28                                Ursynów       5003  pm10 µg/m³
2            43                            Konarskiego       4985  pm10 µg/m³
3          2467                          Marszałkowska       5256  pm10 µg/m³
4          2531                          Komunikacyjna       5012  pm10 µg/m³
..          ...                                    ...        ...         ...
303     3362953  Tomaszów Lubelski, ul. Janusza Petera   11981591  pm10 µg/m³
304     3377216             Nysa, ul. Rodziewiczówny 1   12087775  pm10 µg/m³
305     3616712              Katowice, ul. Dudy-Gracza   12405262  pm10 µg/m³
306     5554541             Warszawa, al. Solidarności   13952343  pm10 µg/m³
307     5554542               Warszawa, ul. Grochowska   13952346  pm10 µg/m³

[308 rows x 4 columns]

In [9]:
sensor_ids = df_pm10_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

308

[4898,
 5003,
 4985,
 5256,
 5012,
 5128,
 5222,
 5084,
 7384,
 10762,
 11012,
 35485,
 32964,
 34868,
 17899,
 35054,
 35595,
 35131,
 35292,
 35933,
 30404,
 29179,
 34896,
 36264,
 35738,
 35410,
 35650,
 35674,
 36427,
 28233,
 35549,
 36175,
 35328,
 35985,
 36484,
 22586,
 36359,
 23069,
 24004,
 24340,
 26737,
 28313,
 28314,
 28399,
 28505,
 29062,
 29765,
 30072,
 30113,
 30194,
 30288,
 30378,
 30392,
 30528,
 30532,
 34597,
 35235,
 35655,
 35480,
 35057,
 35448,
 35000,
 35064,
 35067,
 35142,
 36138,
 35106,
 35099,
 35820,
 35966,
 35381,
 35172,
 35211,
 35232,
 35276,
 35408,
 35304,
 35339,
 35393,
 35942,
 36456,
 35619,
 35895,
 35829,
 35811,
 35731,
 36494,
 35835,
 35866,
 35852,
 35875,
 35879,
 35907,
 35946,
 36161,
 36074,
 36165,
 36261,
 36334,
 36342,
 26098,
 30367,
 28504,
 28908,
 28836,
 29304,
 29346,
 36404,
 35210,
 35886,
 35923,
 28912,
 32945,
 28503,
 35881,
 35953,
 36333,
 28296,
 22577,
 22642,
 21643,
 21642,
 20464,
 20853,
 20897,
 20763,
 17900,
 17889,
 17822,
 17759,
 17740,
 22714,
 30105,
 1289067,
 36230,
 36461,
 20896,
 35862,
 35990,
 28865,
 35088,
 35681,
 20883,
 20925,
 20864,
 34894,
 17947,
 29320,
 20594,
 20904,
 28261,
 18094,
 36150,
 35270,
 20877,
 20902,
 35518,
 35133,
 32965,
 35046,
 35704,
 35030,
 32944,
 29898,
 35939,
 35612,
 28232,
 28772,
 35107,
 21680,
 22457,
 35282,
 28906,
 389750,
 34891,
 22588,
 21555,
 35061,
 35257,
 35256,
 35460,
 35464,
 28782,
 35101,
 35979,
 35419,
 389744,
 39294,
 40538,
 225217,
 234636,
 234637,
 245889,
 245900,
 245892,
 245899,
 245898,
 246031,
 386085,
 386091,
 386074,
 386072,
 388484,
 391215,
 425732,
 426778,
 426779,
 446254,
 852445,
 1180225,
 1289064,
 1289735,
 1293777,
 1303272,
 1562177,
 1562218,
 1562263,
 1562265,
 1562267,
 1562275,
 1562277,
 1562366,
 1562407,
 1562397,
 1562419,
 1562416,
 10494499,
 1727810,
 2011981,
 2017512,
 2023926,
 5079411,
 5079422,
 5079426,
 5079492,
 5079498,
 5079510,
 5079525,
 5079531,
 5079547,
 5079553,
 5079473,
 5079542,
 5079625,
 5079642,
 5079648,
 5079698,
 5079707,
 5079711,
 5079732,
 5079769,
 2507678,
 2553428,
 2553433,
 2553432,
 2555012,
 2555013,
 2555015,
 2570318,
 2569040,
 2569041,
 2589399,
 2589986,
 2666312,
 2687225,
 2773199,
 2773185,
 3490324,
 5079558,
 5079575,
 7009050,
 7176017,
 7576280,
 7610119,
 7634246,
 7634247,
 7635036,
 7644999,
 7645371,
 7660689,
 7676021,
 7695572,
 7743390,
 7749545,
 7773645,
 8619576,
 11428790,
 11428786,
 11716274,
 11865190,
 11872353,
 11872346,
 11872350,
 11883226,
 11883224,
 11884879,
 11884881,
 11948359,
 11960206,
 11950463,
 11960210,
 11959846,
 11960799,
 11981591,
 12087775,
 12405262,
 13952343,
 13952346]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 4898: Seite 1, 299 Ergebnisse
Sensor 5003: Seite 1, 298 Ergebnisse
Sensor 4985: Seite 1, 299 Ergebnisse
Sensor 5256: Seite 1, 298 Ergebnisse
Sensor 5012: Seite 1, 298 Ergebnisse
Sensor 5128: Seite 1, 298 Ergebnisse
Sensor 5222: Seite 1, 295 Ergebnisse
Sensor 5084: Seite 1, 201 Ergebnisse
Sensor 7384: Seite 1, 21 Ergebnisse
Sensor 10762: Seite 1, 1000 Ergebnisse
Sensor 10762: Seite 2, 1000 Ergebnisse
Sensor 10762: Seite 3, 1000 Ergebnisse
Sensor 10762: Seite 4, 64 Ergebnisse
Sensor 11012: Seite 1, 1000 Ergebnisse
Sensor 11012: Seite 2, 1000 Ergebnisse
Sensor 11012: Seite 3, 1000 Ergebnisse
Sensor 11012: Seite 4, 52 Ergebnisse
Sensor 35485: Seite 1, 1000 Ergebnisse
Sensor 35485: Seite 2, 1000 Ergebnisse
Sensor 35485: Seite 3, 528 Ergebnisse
Sensor 32964: Seite 1, 1000 Ergebnisse
Sensor 32964: Seite 2, 1000 Ergebnisse
Sensor 32964: Seite 3, 523 Ergebnisse
Sensor 34868: Seite 1, 1000 Ergebnisse
Sensor 34868: Seite 2, 1000 Ergebnisse
Sensor 34868: Seite 3, 551 Ergebnisse
Sensor 17899: Seite 1, 40 Ergebnisse
Sensor 35054: Seite 1, 1000 Ergebnisse
Sensor 35054: Seite 2, 1000 Ergebnisse
Sensor 35054: Seite 3, 501 Ergebnisse
Sensor 35595: Seite 1, 1000 Ergebnisse
Sensor 35595: Seite 2, 1000 Ergebnisse
Sensor 35595: Seite 3, 468 Ergebnisse
Sensor 35131: Seite 1, 1000 Ergebnisse
Sensor 35131: Seite 2, 1000 Ergebnisse
Sensor 35131: Seite 3, 537 Ergebnisse
Sensor 35292: Seite 1, 1000 Ergebnisse
Sensor 35292: Seite 2, 1000 Ergebnisse
Sensor 35292: Seite 3, 553 Ergebnisse
Sensor 35933: Seite 1, 1000 Ergebnisse
Sensor 35933: Seite 2, 1000 Ergebnisse
Sensor 35933: Seite 3, 415 Ergebnisse
Sensor 30404: Seite 1, 1000 Ergebnisse
Sensor 30404: Seite 2, 1000 Ergebnisse
Sensor 30404: Seite 3, 264 Ergebnisse
Sensor 29179: Seite 1, 1000 Ergebnisse
Sensor 29179: Seite 2, 1000 Ergebnisse
Sensor 29179: Seite 3, 522 Ergebnisse
Sensor 34896: Seite 1, 1000 Ergebnisse
Sensor 34896: Seite 2, 1000 Ergebnisse
Sensor 34896: Seite 3, 514 Ergebnisse
Sensor 36264: Seite 1, 1000 Ergebnisse
Sensor 36264: Seite 2, 1000 Ergebnisse
Sensor 36264: Seite 3, 548 Ergebnisse
Sensor 35738: Seite 1, 1000 Ergebnisse
Sensor 35738: Seite 2, 1000 Ergebnisse
Sensor 35738: Seite 3, 437 Ergebnisse
Sensor 35410: Seite 1, 1000 Ergebnisse
Sensor 35410: Seite 2, 1000 Ergebnisse
Sensor 35410: Seite 3, 548 Ergebnisse
Sensor 35650: Seite 1, 1000 Ergebnisse
Sensor 35650: Seite 2, 1000 Ergebnisse
Sensor 35650: Seite 3, 344 Ergebnisse
Sensor 35674: Seite 1, 1000 Ergebnisse
Sensor 35674: Seite 2, 1000 Ergebnisse
Sensor 35674: Seite 3, 530 Ergebnisse
Sensor 36427: Seite 1, 1000 Ergebnisse
Sensor 36427: Seite 2, 1000 Ergebnisse
Sensor 36427: Seite 3, 463 Ergebnisse
Sensor 28233: Seite 1, 1000 Ergebnisse
Sensor 28233: Seite 2, 1000 Ergebnisse
Sensor 28233: Seite 3, 506 Ergebnisse
Sensor 35549: Seite 1, 1000 Ergebnisse
Sensor 35549: Seite 2, 1000 Ergebnisse
Sensor 35549: Seite 3, 535 Ergebnisse
Sensor 36175: Seite 1, 1000 Ergebnisse
Sensor 36175: Seite 2, 1000 Ergebnisse
Sensor 36175: Seite 3, 490 Ergebnisse
Sensor 35328: Seite 1, 1000 Ergebnisse
Sensor 35328: Seite 2, 1000 Ergebnisse
Sensor 35328: Seite 3, 550 Ergebnisse
Sensor 35985: Seite 1, 1000 Ergebnisse
Sensor 35985: Seite 2, 1000 Ergebnisse
Sensor 35985: Seite 3, 546 Ergebnisse
Sensor 36484: Seite 1, 1000 Ergebnisse
Sensor 36484: Seite 2, 1000 Ergebnisse
Sensor 36484: Seite 3, 531 Ergebnisse
Sensor 22586: Seite 1, 1000 Ergebnisse
Sensor 22586: Seite 2, 1000 Ergebnisse
Sensor 22586: Seite 3, 553 Ergebnisse
Sensor 36359: Seite 1, 1000 Ergebnisse
Sensor 36359: Seite 2, 1000 Ergebnisse
Sensor 36359: Seite 3, 370 Ergebnisse
Sensor 23069: Seite 1, 1000 Ergebnisse
Sensor 23069: Seite 2, 1000 Ergebnisse
Sensor 23069: Seite 3, 418 Ergebnisse
Sensor 24004: Seite 1, 1000 Ergebnisse
Sensor 24004: Seite 2, 1000 Ergebnisse
Sensor 24004: Seite 3, 498 Ergebnisse
Sensor 24340: Seite 1, 1000 Ergebnisse
Sensor 24340: Seite 2, 1000 Ergebnisse
Sensor 24340: Seite 3, 122 Ergebnisse
Sensor 26737: Seite 1, 1000 Ergebnisse
Sensor 26737: Seite 2, 1000 Ergebnisse
Sensor 26737: Seite 3, 505 Ergebnisse
Sensor 28313: Seite 1, 1000 Ergebnisse
Sensor 28313: Seite 2, 1000 Ergebnisse
Sensor 28313: Seite 3, 513 Ergebnisse
Sensor 28314: Seite 1, 1000 Ergebnisse
Sensor 28314: Seite 2, 1000 Ergebnisse
Sensor 28314: Seite 3, 506 Ergebnisse
Sensor 28399: Seite 1, 1000 Ergebnisse
Sensor 28399: Seite 2, 1000 Ergebnisse
Sensor 28399: Seite 3, 506 Ergebnisse
Sensor 28505: Seite 1, 1000 Ergebnisse
Sensor 28505: Seite 2, 1000 Ergebnisse
Sensor 28505: Seite 3, 387 Ergebnisse
Sensor 29062: Seite 1, 1000 Ergebnisse
Sensor 29062: Seite 2, 1000 Ergebnisse
Sensor 29062: Seite 3, 488 Ergebnisse
Sensor 29765: Seite 1, 1000 Ergebnisse
Sensor 29765: Seite 2, 1000 Ergebnisse
Sensor 29765: Seite 3, 527 Ergebnisse
Sensor 30072: Seite 1, 1000 Ergebnisse
Sensor 30072: Seite 2, 1000 Ergebnisse
Sensor 30072: Seite 3, 438 Ergebnisse
Sensor 30113: Seite 1, 1000 Ergebnisse
Sensor 30113: Seite 2, 1000 Ergebnisse
Sensor 30113: Seite 3, 521 Ergebnisse
Sensor 30194: Seite 1, 1000 Ergebnisse
Sensor 30194: Seite 2, 1000 Ergebnisse
Sensor 30194: Seite 3, 107 Ergebnisse
Sensor 30288: Seite 1, 1000 Ergebnisse
Sensor 30288: Seite 2, 1000 Ergebnisse
Sensor 30288: Seite 3, 514 Ergebnisse
Sensor 30392: Seite 1, 1000 Ergebnisse
Sensor 30392: Seite 2, 1000 Ergebnisse
Sensor 30392: Seite 3, 516 Ergebnisse
Sensor 30528: Seite 1, 1000 Ergebnisse
Sensor 30528: Seite 2, 1000 Ergebnisse
Sensor 30528: Seite 3, 523 Ergebnisse
Sensor 30532: Seite 1, 1000 Ergebnisse
Sensor 30532: Seite 2, 1000 Ergebnisse
Sensor 30532: Seite 3, 495 Ergebnisse
Sensor 34597: Seite 1, 1000 Ergebnisse
Sensor 34597: Seite 2, 1000 Ergebnisse
Sensor 34597: Seite 3, 531 Ergebnisse
Sensor 35235: Seite 1, 1000 Ergebnisse
Sensor 35235: Seite 2, 1000 Ergebnisse
Sensor 35235: Seite 3, 399 Ergebnisse
Sensor 35655: Seite 1, 1000 Ergebnisse
Sensor 35655: Seite 2, 1000 Ergebnisse
Sensor 35655: Seite 3, 313 Ergebnisse
Sensor 35480: Seite 1, 1000 Ergebnisse
Sensor 35480: Seite 2, 1000 Ergebnisse
Sensor 35480: Seite 3, 543 Ergebnisse
Sensor 35057: Seite 1, 1000 Ergebnisse
Sensor 35057: Seite 2, 1000 Ergebnisse
Sensor 35057: Seite 3, 489 Ergebnisse
Sensor 35448: Seite 1, 1000 Ergebnisse
Sensor 35448: Seite 2, 1000 Ergebnisse
Sensor 35448: Seite 3, 519 Ergebnisse
Sensor 35000: Seite 1, 1000 Ergebnisse
Sensor 35000: Seite 2, 1000 Ergebnisse
Sensor 35000: Seite 3, 434 Ergebnisse
Sensor 35064: Seite 1, 1000 Ergebnisse
Sensor 35064: Seite 2, 1000 Ergebnisse
Sensor 35064: Seite 3, 552 Ergebnisse
Sensor 35067: Seite 1, 1000 Ergebnisse
Sensor 35067: Seite 2, 1000 Ergebnisse
Sensor 35067: Seite 3, 544 Ergebnisse
Sensor 35142: Seite 1, 1000 Ergebnisse
Sensor 35142: Seite 2, 1000 Ergebnisse
Sensor 35142: Seite 3, 57 Ergebnisse
Sensor 36138: Seite 1, 1000 Ergebnisse
Sensor 36138: Seite 2, 1000 Ergebnisse
Sensor 36138: Seite 3, 527 Ergebnisse
Sensor 35106: Seite 1, 1000 Ergebnisse
Sensor 35106: Seite 2, 1000 Ergebnisse
Sensor 35106: Seite 3, 516 Ergebnisse
Sensor 35099: Seite 1, 1000 Ergebnisse
Sensor 35099: Seite 2, 1000 Ergebnisse
Sensor 35099: Seite 3, 525 Ergebnisse
Sensor 35820: Seite 1, 1000 Ergebnisse
Sensor 35820: Seite 2, 1000 Ergebnisse
Sensor 35820: Seite 3, 536 Ergebnisse
Sensor 35966: Seite 1, 1000 Ergebnisse
Sensor 35966: Seite 2, 1000 Ergebnisse
Sensor 35966: Seite 3, 511 Ergebnisse
Sensor 35381: Seite 1, 1000 Ergebnisse
Sensor 35381: Seite 2, 1000 Ergebnisse
Sensor 35381: Seite 3, 546 Ergebnisse
Sensor 35172: Seite 1, 1000 Ergebnisse
Sensor 35172: Seite 2, 1000 Ergebnisse
Sensor 35172: Seite 3, 534 Ergebnisse
Sensor 35211: Seite 1, 1000 Ergebnisse
Sensor 35211: Seite 2, 1000 Ergebnisse
Sensor 35211: Seite 3, 494 Ergebnisse
Sensor 35232: Seite 1, 1000 Ergebnisse
Sensor 35232: Seite 2, 1000 Ergebnisse
Sensor 35232: Seite 3, 527 Ergebnisse
Sensor 35276: Seite 1, 1000 Ergebnisse
Sensor 35276: Seite 2, 1000 Ergebnisse
Sensor 35276: Seite 3, 522 Ergebnisse
Sensor 35408: Seite 1, 1000 Ergebnisse
Sensor 35408: Seite 2, 1000 Ergebnisse
Sensor 35408: Seite 3, 537 Ergebnisse
Sensor 35304: Seite 1, 1000 Ergebnisse
Sensor 35304: Seite 2, 1000 Ergebnisse
Sensor 35304: Seite 3, 539 Ergebnisse
Sensor 35339: Seite 1, 1000 Ergebnisse
Sensor 35339: Seite 2, 1000 Ergebnisse
Sensor 35339: Seite 3, 449 Ergebnisse
Sensor 35393: Seite 1, 1000 Ergebnisse
Sensor 35393: Seite 2, 1000 Ergebnisse
Sensor 35393: Seite 3, 363 Ergebnisse
Sensor 35942: Seite 1, 1000 Ergebnisse
Sensor 35942: Seite 2, 1000 Ergebnisse
Sensor 35942: Seite 3, 530 Ergebnisse
Sensor 36456: Seite 1, 1000 Ergebnisse
Sensor 36456: Seite 2, 1000 Ergebnisse
Sensor 36456: Seite 3, 500 Ergebnisse
Sensor 35619: Seite 1, 1000 Ergebnisse
Sensor 35619: Seite 2, 1000 Ergebnisse
Sensor 35619: Seite 3, 542 Ergebnisse
Sensor 35895: Seite 1, 1000 Ergebnisse
Sensor 35895: Seite 2, 1000 Ergebnisse
Sensor 35895: Seite 3, 69 Ergebnisse
Sensor 35829: Seite 1, 1000 Ergebnisse
Sensor 35829: Seite 2, 1000 Ergebnisse
Sensor 35829: Seite 3, 544 Ergebnisse
Sensor 35811: Seite 1, 1000 Ergebnisse
Sensor 35811: Seite 2, 1000 Ergebnisse
Sensor 35811: Seite 3, 435 Ergebnisse
Sensor 35731: Seite 1, 1000 Ergebnisse
Sensor 35731: Seite 2, 1000 Ergebnisse
Sensor 35731: Seite 3, 517 Ergebnisse
Sensor 36494: Seite 1, 1000 Ergebnisse
Sensor 36494: Seite 2, 1000 Ergebnisse
Sensor 36494: Seite 3, 554 Ergebnisse
Sensor 35835: Seite 1, 1000 Ergebnisse
Sensor 35835: Seite 2, 1000 Ergebnisse
Sensor 35835: Seite 3, 539 Ergebnisse
Sensor 35866: Seite 1, 1000 Ergebnisse
Sensor 35866: Seite 2, 1000 Ergebnisse
Sensor 35866: Seite 3, 542 Ergebnisse
Sensor 35852: Seite 1, 1000 Ergebnisse
Sensor 35852: Seite 2, 1000 Ergebnisse
Sensor 35852: Seite 3, 515 Ergebnisse
Sensor 35875: Seite 1, 1000 Ergebnisse
Sensor 35875: Seite 2, 1000 Ergebnisse
Sensor 35875: Seite 3, 448 Ergebnisse
Sensor 35879: Seite 1, 1000 Ergebnisse
Sensor 35879: Seite 2, 939 Ergebnisse
Sensor 35907: Seite 1, 1000 Ergebnisse
Sensor 35907: Seite 2, 1000 Ergebnisse
Sensor 35907: Seite 3, 514 Ergebnisse
Sensor 35946: Seite 1, 1000 Ergebnisse
Sensor 35946: Seite 2, 1000 Ergebnisse
Sensor 35946: Seite 3, 494 Ergebnisse
Sensor 36161: Seite 1, 1000 Ergebnisse
Sensor 36161: Seite 2, 1000 Ergebnisse
Sensor 36161: Seite 3, 536 Ergebnisse
Sensor 36074: Seite 1, 1000 Ergebnisse
Sensor 36074: Seite 2, 1000 Ergebnisse
Sensor 36074: Seite 3, 536 Ergebnisse
Sensor 36165: Seite 1, 1000 Ergebnisse
Sensor 36165: Seite 2, 1000 Ergebnisse
Sensor 36165: Seite 3, 549 Ergebnisse
Sensor 36261: Seite 1, 1000 Ergebnisse
Sensor 36261: Seite 2, 1000 Ergebnisse
Sensor 36261: Seite 3, 466 Ergebnisse
Sensor 36334: Seite 1, 1000 Ergebnisse
Sensor 36334: Seite 2, 1000 Ergebnisse
Sensor 36334: Seite 3, 525 Ergebnisse
Sensor 36342: Seite 1, 1000 Ergebnisse
Sensor 36342: Seite 2, 1000 Ergebnisse
Sensor 36342: Seite 3, 412 Ergebnisse
Sensor 26098: Seite 1, 1000 Ergebnisse
Sensor 26098: Seite 2, 1000 Ergebnisse
Sensor 26098: Seite 3, 394 Ergebnisse
Sensor 30367: Seite 1, 1000 Ergebnisse
Sensor 30367: Seite 2, 1000 Ergebnisse
Sensor 30367: Seite 3, 264 Ergebnisse
Sensor 28504: Seite 1, 1000 Ergebnisse
Sensor 28504: Seite 2, 1000 Ergebnisse
Sensor 28504: Seite 3, 526 Ergebnisse
Sensor 28908: Seite 1, 1000 Ergebnisse
Sensor 28908: Seite 2, 1000 Ergebnisse
Sensor 28908: Seite 3, 490 Ergebnisse
Sensor 28836: Seite 1, 1000 Ergebnisse
Sensor 28836: Seite 2, 1000 Ergebnisse
Sensor 28836: Seite 3, 523 Ergebnisse
Sensor 29304: Seite 1, 1000 Ergebnisse
Sensor 29304: Seite 2, 1000 Ergebnisse
Sensor 29304: Seite 3, 527 Ergebnisse
Sensor 29346: Seite 1, 1000 Ergebnisse
Sensor 29346: Seite 2, 1000 Ergebnisse
Sensor 29346: Seite 3, 431 Ergebnisse
Sensor 36404: Seite 1, 1000 Ergebnisse
Sensor 36404: Seite 2, 1000 Ergebnisse
Sensor 36404: Seite 3, 120 Ergebnisse
Sensor 35210: Seite 1, 1000 Ergebnisse
Sensor 35210: Seite 2, 739 Ergebnisse
Sensor 35886: Seite 1, 1000 Ergebnisse
Sensor 35886: Seite 2, 1000 Ergebnisse
Sensor 35886: Seite 3, 78 Ergebnisse
Sensor 35923: Seite 1, 1000 Ergebnisse
Sensor 35923: Seite 2, 1000 Ergebnisse
Sensor 35923: Seite 3, 49 Ergebnisse
Sensor 28912: Seite 1, 1000 Ergebnisse
Sensor 28912: Seite 2, 749 Ergebnisse
Sensor 32945: Seite 1, 1000 Ergebnisse
Sensor 32945: Seite 2, 752 Ergebnisse
Sensor 28503: Seite 1, 1000 Ergebnisse
Sensor 28503: Seite 2, 450 Ergebnisse
Sensor 35881: Seite 1, 1000 Ergebnisse
Sensor 35881: Seite 2, 443 Ergebnisse
Sensor 35953: Seite 1, 1000 Ergebnisse
Sensor 35953: Seite 2, 292 Ergebnisse
Sensor 36333: Seite 1, 1000 Ergebnisse
Sensor 36333: Seite 2, 450 Ergebnisse
Sensor 28296: Seite 1, 1000 Ergebnisse
Sensor 28296: Seite 2, 80 Ergebnisse
Sensor 22577: Seite 1, 578 Ergebnisse
Sensor 22642: Seite 1, 626 Ergebnisse
Sensor 21643: Seite 1, 436 Ergebnisse
Sensor 21642: Seite 1, 440 Ergebnisse
Sensor 20464: Seite 1, 317 Ergebnisse
Sensor 20853: Seite 1, 404 Ergebnisse
Sensor 20897: Seite 1, 385 Ergebnisse
Sensor 20763: Seite 1, 276 Ergebnisse
Sensor 17900: Seite 1, 38 Ergebnisse
Sensor 17889: Seite 1, 21 Ergebnisse
Sensor 17822: Seite 1, 29 Ergebnisse
Sensor 17759: Seite 1, 23 Ergebnisse
Sensor 17740: Seite 1, 20 Ergebnisse
Sensor 22714: Seite 1, 1000 Ergebnisse
Sensor 22714: Seite 2, 409 Ergebnisse
Sensor 30105: Seite 1, 1000 Ergebnisse
Sensor 30105: Seite 2, 1000 Ergebnisse
Sensor 30105: Seite 3, 448 Ergebnisse
Sensor 1289067: Seite 1, 489 Ergebnisse
Sensor 36230: Seite 1, 1000 Ergebnisse
Sensor 36230: Seite 2, 1000 Ergebnisse
Sensor 36230: Seite 3, 390 Ergebnisse
Sensor 36461: Seite 1, 1000 Ergebnisse
Sensor 36461: Seite 2, 1000 Ergebnisse
Sensor 36461: Seite 3, 492 Ergebnisse
Sensor 20896: Seite 1, 773 Ergebnisse
Sensor 35862: Seite 1, 1000 Ergebnisse
Sensor 35862: Seite 2, 1000 Ergebnisse
Sensor 35862: Seite 3, 471 Ergebnisse
Sensor 35990: Seite 1, 1000 Ergebnisse
Sensor 35990: Seite 2, 1000 Ergebnisse
Sensor 35990: Seite 3, 491 Ergebnisse
Sensor 28865: Seite 1, 849 Ergebnisse
Sensor 35088: Seite 1, 645 Ergebnisse
Sensor 35681: Seite 1, 700 Ergebnisse
Sensor 20883: Seite 1, 337 Ergebnisse
Sensor 20925: Seite 1, 362 Ergebnisse
Sensor 20864: Seite 1, 330 Ergebnisse
Sensor 34894: Seite 1, 1000 Ergebnisse
Sensor 34894: Seite 2, 1000 Ergebnisse
Sensor 34894: Seite 3, 355 Ergebnisse
Sensor 17947: Seite 1, 1 Ergebnisse
Sensor 29320: Seite 1, 1000 Ergebnisse
Sensor 29320: Seite 2, 1000 Ergebnisse
Sensor 29320: Seite 3, 432 Ergebnisse
Sensor 20594: Seite 1, 316 Ergebnisse
Sensor 20904: Seite 1, 314 Ergebnisse
Sensor 28261: Seite 1, 1000 Ergebnisse
Sensor 28261: Seite 2, 1000 Ergebnisse
Sensor 28261: Seite 3, 450 Ergebnisse
Sensor 18094: Seite 1, 1 Ergebnisse
Sensor 36150: Seite 1, 720 Ergebnisse
Sensor 35270: Seite 1, 1000 Ergebnisse
Sensor 35270: Seite 2, 1000 Ergebnisse
Sensor 35270: Seite 3, 442 Ergebnisse
Sensor 20877: Seite 1, 171 Ergebnisse
Sensor 20902: Seite 1, 277 Ergebnisse
Sensor 35518: Seite 1, 1000 Ergebnisse
Sensor 35518: Seite 2, 1000 Ergebnisse
Sensor 35518: Seite 3, 381 Ergebnisse
Sensor 35133: Seite 1, 1000 Ergebnisse
Sensor 35133: Seite 2, 1000 Ergebnisse
Sensor 35133: Seite 3, 334 Ergebnisse
Sensor 32965: Seite 1, 1000 Ergebnisse
Sensor 32965: Seite 2, 1000 Ergebnisse
Sensor 32965: Seite 3, 241 Ergebnisse
Sensor 35046: Seite 1, 463 Ergebnisse
Sensor 35704: Seite 1, 1000 Ergebnisse
Sensor 35704: Seite 2, 1000 Ergebnisse
Sensor 35704: Seite 3, 185 Ergebnisse
Sensor 35030: Seite 1, 1000 Ergebnisse
Sensor 35030: Seite 2, 1000 Ergebnisse
Sensor 35030: Seite 3, 68 Ergebnisse
Sensor 32944: Seite 1, 1000 Ergebnisse
Sensor 32944: Seite 2, 1000 Ergebnisse
Sensor 32944: Seite 3, 197 Ergebnisse
Sensor 29898: Seite 1, 1000 Ergebnisse
Sensor 29898: Seite 2, 1000 Ergebnisse
Sensor 29898: Seite 3, 48 Ergebnisse
Sensor 35939: Seite 1, 339 Ergebnisse
Sensor 35612: Seite 1, 700 Ergebnisse
Sensor 28232: Seite 1, 1000 Ergebnisse
Sensor 28232: Seite 2, 1000 Ergebnisse
Sensor 28232: Seite 3, 114 Ergebnisse
Sensor 28772: Seite 1, 1000 Ergebnisse
Sensor 28772: Seite 2, 1000 Ergebnisse
Sensor 28772: Seite 3, 115 Ergebnisse
Sensor 35107: Seite 1, 354 Ergebnisse
Sensor 21680: Seite 1, 56 Ergebnisse
Sensor 22457: Seite 1, 1000 Ergebnisse
Sensor 22457: Seite 2, 1000 Ergebnisse
Sensor 22457: Seite 3, 141 Ergebnisse
Sensor 35282: Seite 1, 291 Ergebnisse
Sensor 28906: Seite 1, 1000 Ergebnisse
Sensor 28906: Seite 2, 1000 Ergebnisse
Sensor 28906: Seite 3, 112 Ergebnisse
Sensor 389750: Seite 1, 1000 Ergebnisse
Sensor 389750: Seite 2, 317 Ergebnisse
Sensor 34891: Seite 1, 346 Ergebnisse
Sensor 22588: Seite 1, 339 Ergebnisse
Sensor 21555: Seite 1, 7 Ergebnisse
Sensor 35061: Seite 1, 330 Ergebnisse
Sensor 35257: Seite 1, 1000 Ergebnisse
Sensor 35257: Seite 2, 3 Ergebnisse
Sensor 35256: Seite 1, 323 Ergebnisse
Sensor 35460: Seite 1, 669 Ergebnisse
Sensor 35464: Seite 1, 281 Ergebnisse
Sensor 28782: Seite 1, 1000 Ergebnisse
Sensor 28782: Seite 2, 1000 Ergebnisse
Sensor 28782: Seite 3, 82 Ergebnisse
Sensor 35101: Seite 1, 1000 Ergebnisse
Sensor 35101: Seite 2, 649 Ergebnisse
Sensor 35419: Seite 1, 1000 Ergebnisse
Sensor 35419: Seite 2, 1000 Ergebnisse
Sensor 35419: Seite 3, 5 Ergebnisse
Sensor 389744: Seite 1, 1000 Ergebnisse
Sensor 389744: Seite 2, 730 Ergebnisse
Sensor 39294: Seite 1, 1000 Ergebnisse
Sensor 39294: Seite 2, 846 Ergebnisse
Sensor 40538: Seite 1, 1000 Ergebnisse
Sensor 40538: Seite 2, 798 Ergebnisse
Sensor 225217: Seite 1, 1000 Ergebnisse
Sensor 225217: Seite 2, 777 Ergebnisse
Sensor 234636: Seite 1, 1000 Ergebnisse
Sensor 234636: Seite 2, 756 Ergebnisse
Sensor 234637: Seite 1, 1000 Ergebnisse
Sensor 234637: Seite 2, 753 Ergebnisse
Sensor 245889: Seite 1, 1000 Ergebnisse
Sensor 245889: Seite 2, 728 Ergebnisse
Sensor 245900: Seite 1, 1000 Ergebnisse
Sensor 245900: Seite 2, 789 Ergebnisse
Sensor 245892: Seite 1, 1000 Ergebnisse
Sensor 245892: Seite 2, 634 Ergebnisse
Sensor 245899: Seite 1, 340 Ergebnisse
Sensor 245898: Seite 1, 332 Ergebnisse
Sensor 246031: Seite 1, 307 Ergebnisse
Sensor 386085: Seite 1, 339 Ergebnisse
Sensor 386091: Seite 1, 692 Ergebnisse
Sensor 386074: Seite 1, 1000 Ergebnisse
Sensor 386074: Seite 2, 774 Ergebnisse
Sensor 386072: Seite 1, 1000 Ergebnisse
Sensor 386072: Seite 2, 677 Ergebnisse
Sensor 388484: Seite 1, 319 Ergebnisse
Sensor 391215: Seite 1, 292 Ergebnisse
Sensor 425732: Seite 1, 322 Ergebnisse
Sensor 426778: Seite 1, 1000 Ergebnisse
Sensor 426778: Seite 2, 712 Ergebnisse
Sensor 426779: Seite 1, 1000 Ergebnisse
Sensor 426779: Seite 2, 688 Ergebnisse
Sensor 446254: Seite 1, 1000 Ergebnisse
Sensor 446254: Seite 2, 666 Ergebnisse
Sensor 852445: Seite 1, 675 Ergebnisse
Sensor 1180225: Seite 1, 309 Ergebnisse
Sensor 1289064: Seite 1, 536 Ergebnisse
Sensor 1289735: Seite 1, 672 Ergebnisse
Sensor 1293777: Seite 1, 1000 Ergebnisse
Sensor 1293777: Seite 2, 686 Ergebnisse
Sensor 1303272: Seite 1, 1000 Ergebnisse
Sensor 1303272: Seite 2, 663 Ergebnisse
Sensor 1562177: Seite 1, 1000 Ergebnisse
Sensor 1562177: Seite 2, 451 Ergebnisse
Sensor 1562218: Seite 1, 355 Ergebnisse
Sensor 1562263: Seite 1, 364 Ergebnisse
Sensor 1562265: Seite 1, 637 Ergebnisse
Sensor 1562267: Seite 1, 353 Ergebnisse
Sensor 1562275: Seite 1, 361 Ergebnisse
Sensor 1562277: Seite 1, 361 Ergebnisse
Sensor 1562366: Seite 1, 359 Ergebnisse
Sensor 1562407: Seite 1, 208 Ergebnisse
Sensor 1562397: Seite 1, 860 Ergebnisse
Sensor 1562419: Seite 1, 635 Ergebnisse
Sensor 1562416: Seite 1, 348 Ergebnisse
Sensor 1727810: Seite 1, 1000 Ergebnisse
Sensor 1727810: Seite 2, 324 Ergebnisse
Sensor 2011981: Seite 1, 1000 Ergebnisse
Sensor 2011981: Seite 2, 122 Ergebnisse
Sensor 2017512: Seite 1, 1000 Ergebnisse
Sensor 2017512: Seite 2, 238 Ergebnisse
Sensor 2023926: Seite 1, 1000 Ergebnisse
Sensor 2023926: Seite 2, 210 Ergebnisse
Sensor 2507678: Seite 1, 288 Ergebnisse
Sensor 2553428: Seite 1, 1000 Ergebnisse
Sensor 2553428: Seite 2, 84 Ergebnisse
Sensor 2553433: Seite 1, 600 Ergebnisse
Sensor 2553432: Seite 1, 272 Ergebnisse
Sensor 2555012: Seite 1, 1000 Ergebnisse
Sensor 2555012: Seite 2, 27 Ergebnisse
Sensor 2555013: Seite 1, 293 Ergebnisse
Sensor 2555015: Seite 1, 281 Ergebnisse
Sensor 2570318: Seite 1, 291 Ergebnisse
Sensor 2569040: Seite 1, 1000 Ergebnisse
Sensor 2569040: Seite 2, 2 Ergebnisse

[{'date': '2016-01-30', 'value': 14.090909090909092},
 {'date': '2016-01-31', 'value': 7.391304347826087},
 {'date': '2016-02-01', 'value': 13.608695652173912},
 {'date': '2016-02-02', 'value': 7.608695652173913},
 {'date': '2016-02-03', 'value': 8.217391304347826},
 {'date': '2016-02-04', 'value': 9.91304347826087},
 {'date': '2016-02-05', 'value': 16.08695652173913},
 {'date': '2016-02-06', 'value': 37.91304347826087},
 {'date': '2016-02-07', 'value': 32.78260869565217},
 {'date': '2016-02-08', 'value': 19.08695652173913},
 {'date': '2016-02-09', 'value': 11.565217391304348},
 {'date': '2016-02-10', 'value': 12.363636363636363},
 {'date': '2016-02-11', 'value': 18.08695652173913},
 {'date': '2016-02-12', 'value': 29.0},
 {'date': '2016-02-13', 'value': 28.652173913043477},
 {'date': '2016-02-14', 'value': 37.34782608695652},
 {'date': '2016-02-15', 'value': 51.86363636363637},
 {'date': '2016-02-16', 'value': 18.045454545454547},
 {'date': '2016-02-17', 'value': 17.695652173913043},
 {'date': '2016-02-18', 'value': 34.130434782608695},
 {'date': '2016-02-19', 'value': 20.652173913043477},
 {'date': '2016-02-20', 'value': 34.65217391304348},
 {'date': '2016-02-21', 'value': 10.73913043478261},
 {'date': '2016-02-22', 'value': 4.869565217391305},
 {'date': '2016-02-23', 'value': 12.956521739130435},
 {'date': '2016-02-24', 'value': 14.043478260869565},
 {'date': '2016-02-25', 'value': 22.130434782608695},
 {'date': '2016-02-26', 'value': 33.130434782608695},
 {'date': '2016-02-27', 'value': 49.82608695652174},
 {'date': '2016-02-28', 'value': 36.0},
 {'date': '2016-02-29', 'value': 31.181818181818183},
 {'date': '2016-03-01', 'value': 20.26086956521739},
 {'date': '2016-03-02', 'value': 39.18181818181818},
 {'date': '2016-03-03', 'value': 40.608695652173914},
 {'date': '2016-03-04', 'value': 27.91304347826087},
 {'date': '2016-03-05', 'value': 31.608695652173914},
 {'date': '2016-03-06', 'value': 31.043478260869566},
 {'date': '2016-03-07', 'value': 40.36363636363637},
 {'date': '2016-03-08', 'value': 43.34782608695652},
 {'date': '2016-03-09', 'value': 29.652173913043477},
 {'date': '2016-03-10', 'value': 17.869565217391305},
 {'date': '2016-03-11', 'value': 18.26086956521739},
 {'date': '2016-03-12', 'value': 22.608695652173914},
 {'date': '2016-03-13', 'value': 18.47826086956522},
 {'date': '2016-03-14', 'value': 33.69565217391305},
 {'date': '2016-03-15', 'value': 13.08695652173913},
 {'date': '2016-03-16', 'value': 20.652173913043477},
 {'date': '2016-03-17', 'value': 30.217391304347824},
 {'date': '2016-03-18', 'value': 21.434782608695652},
 {'date': '2016-03-19', 'value': 10.565217391304348},
 {'date': '2016-03-20', 'value': 20.82608695652174},
 {'date': '2016-03-21', 'value': 18.26086956521739},
 {'date': '2016-03-22', 'value': 13.304347826086957},
 {'date': '2016-03-23', 'value': 22.565217391304348},
 {'date': '2016-03-24', 'value': 37.0},
 {'date': '2016-03-25', 'value': 43.34782608695652},
 {'date': '2016-03-26', 'value': 28.347826086956523},
 {'date': '2016-03-27', 'value': 35.76190476190476},
 {'date': '2016-03-28', 'value': 37.8},
 {'date': '2016-03-29', 'value': 37.0},
 {'date': '2016-03-30', 'value': 16.19047619047619},
 {'date': '2016-03-31', 'value': 17.956521739130434},
 {'date': '2016-04-01', 'value': 12.73913043478261},
 {'date': '2016-04-02', 'value': 13.043478260869565},
 {'date': '2016-04-03', 'value': 18.681818181818183},
 {'date': '2016-04-04', 'value': 29.82608695652174},
 {'date': '2016-04-05', 'value': 42.130434782608695},
 {'date': '2016-04-06', 'value': 32.26086956521739},
 {'date': '2016-04-07', 'value': 30.304347826086957},
 {'date': '2016-04-08', 'value': 22.043478260869566},
 {'date': '2016-04-09', 'value': 20.130434782608695},
 {'date': '2016-04-10', 'value': 12.954545454545455},
 {'date': '2016-04-11', 'value': 20.956521739130434},
 {'date': '2016-04-12', 'value': 30.0},
 {'date': '2016-04-13', 'value': 41.21739130434783},
 {'date': '2016-04-14', 'value': 18.434782608695652},
 {'date': '2016-04-15', 'value': 19.17391304347826},
 {'date': '2016-04-16', 'value': 17.217391304347824},
 {'date': '2016-04-17', 'value': 17.782608695652176},
 {'date': '2016-04-18', 'value': 8.91304347826087},
 {'date': '2016-04-19', 'value': 15.521739130434783},
 {'date': '2016-04-20', 'value': 12.695652173913043},
 {'date': '2016-04-21', 'value': 12.782608695652174},
 {'date': '2016-04-22', 'value': 14.347826086956522},
 {'date': '2016-04-23', 'value': 19.434782608695652},
 {'date': '2016-04-24', 'value': 7.0},
 {'date': '2016-04-25', 'value': 12.956521739130435},
 {'date': '2016-04-26', 'value': 22.652173913043477},
 {'date': '2016-04-27', 'value': 13.26086956521739},
 {'date': '2016-04-28', 'value': 20.5},
 {'date': '2016-04-29', 'value': 19.761904761904763},
 {'date': '2016-04-30', 'value': 21.304347826086957},
 {'date': '2016-05-01', 'value': 21.652173913043477},
 {'date': '2016-05-02', 'value': 18.0},
 {'date': '2016-05-03', 'value': 18.043478260869566},
 {'date': '2016-05-04', 'value': 13.347826086956522},
 {'date': '2016-05-05', 'value': 19.956521739130434},
 {'date': '2016-05-06', 'value': 21.652173913043477},
 {'date': '2016-05-07', 'value': 18.73913043478261},
 {'date': '2016-05-08', 'value': 17.695652173913043},
 {'date': '2016-05-09', 'value': 16.869565217391305},
 {'date': '2016-05-10', 'value': 19.82608695652174},
 {'date': '2016-05-11', 'value': 24.17391304347826},
 {'date': '2016-05-12', 'value': 18.304347826086957},
 {'date': '2016-05-13', 'value': 15.227272727272727},
 {'date': '2016-05-14', 'value': 14.08695652173913},
 {'date': '2016-05-15', 'value': 10.217391304347826},
 {'date': '2016-05-16', 'value': 5.869565217391305},
 {'date': '2016-05-17', 'value': 8.956521739130435},
 {'date': '2016-05-18', 'value': 14.863636363636363},
 {'date': '2016-05-19', 'value': 20.130434782608695},
 {'date': '2016-05-20', 'value': 25.391304347826086},
 {'date': '2016-05-21', 'value': 18.217391304347824},
 {'date': '2016-05-22', 'value': 17.956521739130434},
 {'date': '2016-05-23', 'value': 20.347826086956523},
 {'date': '2016-05-24', 'value': 19.782608695652176},
 {'date': '2016-05-25', 'value': 23.652173913043477},
 {'date': '2016-05-26', 'value': 18.608695652173914},
 {'date': '2016-05-27', 'value': 23.0},
 {'date': '2016-05-28', 'value': 22.0},
 {'date': '2016-05-29', 'value': 17.428571428571427},
 {'date': '2016-05-30', 'value': 20.533333333333335},
 {'date': '2016-05-31', 'value': 20.347826086956523},
 {'date': '2016-06-01', 'value': 16.608695652173914},
 {'date': '2016-06-02', 'value': 15.608695652173912},
 {'date': '2016-06-03', 'value': 18.82608695652174},
 {'date': '2016-06-04', 'value': 22.73913043478261},
 {'date': '2016-06-05', 'value': 9.043478260869565},
 {'date': '2016-06-06', 'value': 8.73913043478261},
 {'date': '2016-06-07', 'value': 14.0},
 {'date': '2016-06-08', 'value': 16.08695652173913},
 {'date': '2016-06-09', 'value': 11.26086956521739},
 {'date': '2016-06-10', 'value': 12.304347826086957},
 {'date': '2016-06-11', 'value': 5.3478260869565215},
 {'date': '2016-06-12', 'value': 5.869565217391305},
 {'date': '2016-06-13', 'value': 11.652173913043478},
 {'date': '2016-06-14', 'value': 16.391304347826086},
 {'date': '2016-06-15', 'value': 14.26086956521739},
 {'date': '2016-06-16', 'value': 9.130434782608695},
 {'date': '2016-06-17', 'value': 13.0},
 {'date': '2016-06-18', 'value': 10.869565217391305},
 {'date': '2016-06-19', 'value': 10.782608695652174},
 {'date': '2016-06-20', 'value': 12.173913043478262},
 {'date': '2016-06-21', 'value': 15.521739130434783},
 {'date': '2016-06-22', 'value': 14.304347826086957},
 {'date': '2016-06-23', 'value': 17.130434782608695},
 {'date': '2016-06-24', 'value': 20.391304347826086},
 {'date': '2016-06-25', 'value': 26.434782608695652},
 {'date': '2016-06-26', 'value': 18.272727272727273},
 {'date': '2016-06-27', 'value': 4.5},
 {'date': '2016-06-28', 'value': 15.333333333333334},
 {'date': '2016-06-29', 'value': 15.26086956521739},
 {'date': '2016-06-30', 'value': 14.217391304347826},
 {'date': '2016-07-01', 'value': 10.782608695652174},
 {'date': '2016-07-02', 'value': 16.434782608695652},
 {'date': '2016-07-03', 'value': 8.956521739130435},
 {'date': '2016-07-04', 'value': 6.260869565217392},
 {'date': '2016-07-05', 'value': 8.217391304347826},
 {'date': '2016-07-06', 'value': 7.521739130434782},
 {'date': '2016-07-07', 'value': 6.608695652173913},
 {'date': '2016-07-08', 'value': 8.782608695652174},
 {'date': '2016-07-09', 'value': 7.739130434782608},
 {'date': '2016-07-10', 'value': 6.913043478260869},
 {'date': '2016-07-11', 'value': 11.782608695652174},
 {'date': '2016-07-12', 'value': 16.82608695652174},
 {'date': '2016-07-13', 'value': 17.304347826086957},
 {'date': '2016-07-14', 'value': 11.130434782608695},
 {'date': '2016-07-15', 'value': 4.469565217391304},
 {'date': '2016-07-16', 'value': 8.782608695652174},
 {'date': '2016-07-17', 'value': 10.304347826086957},
 {'date': '2016-07-18', 'value': 7.260869565217392},
 {'date': '2016-07-19', 'value': 5.3478260869565215},
 {'date': '2016-07-20', 'value': 8.08695652173913},
 {'date': '2016-07-21', 'value': 10.608695652173912},
 {'date': '2016-07-22', 'value': 11.347826086956522},
 {'date': '2016-07-23', 'value': 12.869565217391305},
 {'date': '2016-07-24', 'value': 22.043478260869566},
 {'date': '2016-07-25', 'value': 17.043478260869566},
 {'date': '2016-07-26', 'value': 21.652173913043477},
 {'date': '2016-07-27', 'value': 19.0},
 {'date': '2016-07-28', 'value': 18.571428571428573},
 {'date': '2016-07-29', 'value': 20.869565217391305},
 {'date': '2016-07-30', 'value': 15.173913043478262},
 {'date': '2016-07-31', 'value': 13.409090909090908},
 {'date': '2016-08-01', 'value': 10.545454545454545},
 {'date': '2016-08-02', 'value': 9.090909090909092},
 {'date': '2016-08-03', 'value': 12.681818181818182},
 {'date': '2016-08-04', 'value': 8.409090909090908},
 {'date': '2016-08-05', 'value': 12.545454545454545},
 {'date': '2016-08-06', 'value': 10.954545454545455},
 {'date': '2016-08-07', 'value': 5.545454545454546},
 {'date': '2016-08-08', 'value': 13.363636363636363},
 {'date': '2016-08-09', 'value': 12.545454545454545},
 {'date': '2016-08-10', 'value': 12.818181818181818},
 {'date': '2016-08-11', 'value': 7.454545454545454},
 {'date': '2016-08-12', 'value': 11.227272727272727},
 {'date': '2016-08-13', 'value': 14.818181818181818},
 {'date': '2016-08-14', 'value': 10.318181818181818},
 {'date': '2016-08-15', 'value': 5.7727272727272725},
 {'date': '2016-08-16', 'value': 12.173913043478262},
 {'date': '2016-08-17', 'value': 11.347826086956522},
 {'date': '2016-08-18', 'value': 12.521739130434783},
 {'date': '2016-08-19', 'value': 20.52173913043478},
 {'date': '2016-08-20', 'value': 20.73913043478261},
 {'date': '2016-08-21', 'value': 16.17391304347826},
 {'date': '2016-08-22', 'value': 17.08695652173913},
 {'date': '2016-08-23', 'value': 14.043478260869565},
 {'date': '2016-08-24', 'value': 10.347826086956522},
 {'date': '2016-08-25', 'value': 10.91304347826087},
 {'date': '2016-08-26', 'value': 14.0},
 {'date': '2016-08-27', 'value': 15.666666666666666},
 {'date': '2016-08-28', 'value': 21.869565217391305},
 {'date': '2016-08-29', 'value': 16.91304347826087},
 {'date': '2016-08-30', 'value': 7.782608695652174},
 {'date': '2016-08-31', 'value': 10.826086956521738},
 {'date': '2016-09-01', 'value': 15.478260869565217},
 {'date': '2016-09-02', 'value': 21.695652173913043},
 {'date': '2016-09-03', 'value': 21.08695652173913},
 {'date': '2016-09-04', 'value': 17.08695652173913},
 {'date': '2016-09-05', 'value': 7.521739130434782},
 {'date': '2016-09-06', 'value': 11.91304347826087},
 {'date': '2016-09-07', 'value': 17.17391304347826},
 {'date': '2016-09-08', 'value': 25.217391304347824},
 {'date': '2016-09-09', 'value': 28.304347826086957},
 {'date': '2016-09-10', 'value': 33.30434782608695},
 {'date': '2016-09-11', 'value': 30.565217391304348},
 {'date': '2016-09-12', 'value': 32.391304347826086},
 {'date': '2016-09-13', 'value': 35.47826086956522},
 {'date': '2016-09-14', 'value': 23.565217391304348},
 {'date': '2016-09-15', 'value': 26.130434782608695},
 {'date': '2016-09-16', 'value': 34.91304347826087},
 {'date': '2016-09-17', 'value': 28.217391304347824},
 {'date': '2016-09-18', 'value': 18.652173913043477},
 {'date': '2016-09-19', 'value': 22.91304347826087},
 {'date': '2016-09-20', 'value': 27.73913043478261},
 {'date': '2016-09-21', 'value': 13.652173913043478},
 {'date': '2016-09-22', 'value': 12.88888888888889},
 {'date': '2016-11-04', 'value': 16.5},
 {'date': '2016-11-09', 'value': 41.476190476190474},
 {'date': '2016-11-10', 'value': 34.68181818181818},
 {'date': '2016-11-11', 'value': 21.681818181818183},
 {'date': '2016-11-12', 'value': 29.454545454545453},
 {'date': '2016-11-13', 'value': 24.0},
 {'date': '2016-11-14', 'value': 30.272727272727273},
 {'date': '2016-11-15', 'value': 30.227272727272727},
 {'date': '2016-11-16', 'value': 19.869565217391305},
 {'date': '2016-11-17', 'value': 18.304347826086957},
 {'date': '2016-11-18', 'value': 26.08695652173913},
 {'date': '2016-11-19', 'value': 34.34782608695652},
 {'date': '2016-11-20', 'value': 18.130434782608695},
 {'date': '2016-11-21', 'value': 22.47826086956522},
 {'date': '2016-11-22', 'value': 21.045454545454547},
 {'date': '2016-11-23', 'value': 38.391304347826086},
 {'date': '2016-11-24', 'value': 51.0},
 {'date': '2016-11-25', 'value': 43.22727272727273},
 {'date': '2016-11-26', 'value': 28.608695652173914},
 {'date': '2016-11-27', 'value': 11.08695652173913},
 {'date': '2016-11-28', 'value': 9.869565217391305},
 {'date': '2016-11-29', 'value': 15.0},
 {'date': '2016-11-30', 'value': 21.727272727272727},
 {'date': '2016-12-01', 'value': 21.47826086956522},
 {'date': '2016-12-02', 'value': 9.818181818181818},
 {'date': '2016-12-03', 'value': 9.826086956521738},
 {'date': '2016-12-04', 'value': 23.217391304347824},
 {'date': '2016-12-05', 'value': 28.73913043478261},
 {'date': '2016-12-06', 'value': 24.26086956521739},
 {'date': '2016-12-07', 'value': 37.52173913043478},
 {'date': '2016-12-08', 'value': 18.130434782608695},
 {'date': '2016-12-09', 'value': 20.043478260869566},
 {'date': '2016-12-10', 'value': 18.181818181818183},
 {'date': '2016-12-11', 'value': 17.695652173913043},
 {'date': '2016-12-12', 'value': 10.391304347826088},
 {'date': '2016-12-13', 'value': 38.47826086956522},
 {'date': '2016-12-14', 'value': 27.17391304347826},
 {'date': '2016-12-15', 'value': 12.91304347826087},
 {'date': '2016-12-16', 'value': 50.04347826086956},
 {'date': '2016-12-17', 'value': 58.17391304347826},
 {'date': '2016-12-18', 'value': 41.52173913043478},
 {'date': '2016-12-19', 'value': 31.043478260869566},
 {'date': '2016-12-20', 'value': 36.0},
 {'date': '2016-12-21', 'value': 44.56521739130435},
 {'date': '2016-12-22', 'value': 52.34782608695652},
 {'date': '2016-12-23', 'value': 32.47826086956522},
 {'date': '2016-12-24', 'value': 25.0},
 {'date': '2016-12-25', 'value': 12.909090909090908},
 {'date': '2016-12-26', 'value': 6.6521739130434785},
 {'date': '2016-12-27', 'value': 6.739130434782608},
 {'date': '2016-12-28', 'value': 9.136363636363637},
 {'date': '2016-12-29', 'value': 29.869565217391305},
 {'date': '2016-12-30', 'value': 37.95652173913044},
 {'date': '2016-12-31', 'value': 37.30434782608695},
 {'date': '2017-01-01', 'value': 30.434782608695652},
 {'date': '2017-01-02', 'value': 24.347826086956523},
 {'date': '2017-01-03', 'value': 18.73913043478261},
 {'date': '2017-01-04', 'value': 7.0},
 {'date': '2017-01-05', 'value': 6.608695652173913},
 {'date': '2017-01-06', 'value': 11.347826086956522},
 {'date': '2017-01-07', 'value': 48.04347826086956},
 {'date': '2017-01-08', 'value': 103.11111111111111},
 {'date': '2016-01-30', 'value': 23.14090909090909},
 {'date': '2016-01-31', 'value': 14.45217391304348},
 {'date': '2016-02-01', 'value': 18.86521739130435},
 {'date': '2016-02-02', 'value': 11.868181818181823},
 {'date': '2016-02-03', 'value': 14.386956521739132},
 {'date': '2016-02-04', 'value': 19.204347826086956},
 {'date': '2016-02-05', 'value': 25.499999999999996},
 {'date': '2016-02-06', 'value': 42.6},
 {'date': '2016-02-07', 'value': 30.347826086956516},
 {'date': '2016-02-08', 'value': 27.44347826086957},
 {'date': '2016-02-09', 'value': 15.856521739130438},
 {'date': '2016-02-10', 'value': 16.513043478260876},
 {'date': '2016-02-11', 'value': 24.082608695652173},
 {'date': '2016-02-12', 'value': 25.06521739130435},
 {'date': '2016-02-13', 'value': 30.278260869565223},
 {'date': '2016-02-14', 'value': 40.00434782608695},
 {'date': '2016-02-15', 'value': 47.247826086956515},
 {'date': '2016-02-16', 'value': 24.400000000000006},
 {'date': '2016-02-17', 'value': 19.26086956521739},
 {'date': '2016-02-18', 'value': 39.15217391304348},
 {'date': '2016-02-19', 'value': 28.42173913043478},
 {'date': '2016-02-20', 'value': 35.97391304347826},
 {'date': '2016-02-21', 'value': 18.078260869565216},
 {'date': '2016-02-22', 'value': 9.32608695652174},
 {'date': '2016-02-23', 'value': 20.7695652173913},
 {'date': '2016-02-24', 'value': 22.247826086956522},
 {'date': '2016-02-25', 'value': 28.41304347826087},
 {'date': '2016-02-26', 'value': 50.27391304347826},
 {'date': '2016-02-27', 'value': 58.23636363636363},
 {'date': '2016-02-28', 'value': 45.2},
 {'date': '2016-02-29', 'value': 43.445454545454545},
 {'date': '2016-03-01', 'value': 21.539130434782606},
 {'date': '2016-03-02', 'value': 33.09130434782608},
 {'date': '2016-03-03', 'value': 36.743478260869566},
 {'date': '2016-03-04', 'value': 30.121739130434786},
 {'date': '2016-03-05', 'value': 42.417391304347824},
 {'date': '2016-03-06', 'value': 34.021739130434774},
 {'date': '2016-03-07', 'value': 35.28260869565217},
 {'date': '2016-03-08', 'value': 32.50434782608696},
 {'date': '2016-03-09', 'value': 40.278260869565216},
 {'date': '2016-03-10', 'value': 22.12608695652174},
 {'date': '2016-03-11', 'value': 21.826086956521742},
 {'date': '2016-03-12', 'value': 30.956521739130434},
 {'date': '2016-03-13', 'value': 19.739130434782613},
 {'date': '2016-03-14', 'value': 47.2},
 {'date': '2016-03-15', 'value': 19.06818181818182},
 {'date': '2016-03-16', 'value': 25.79565217391304},
 {'date': '2016-03-17', 'value': 47.79565217391304},
 {'date': '2016-03-18', 'value': 32.891304347826086},
 {'date': '2016-03-19', 'value': 14.700000000000003},
 {'date': '2016-03-20', 'value': 34.481818181818184},
 {'date': '2016-03-21', 'value': 30.265217391304343},
 {'date': '2016-03-22', 'value': 24.15652173913043},
 {'date': '2016-03-23', 'value': 21.82608695652174},
 {'date': '2016-03-24', 'value': 34.77391304347827},
 {'date': '2016-03-25', 'value': 57.01739130434783},
 {'date': '2016-03-26', 'value': 52.1},
 {'date': '2016-03-27', 'value': 51.271428571428565},
 {'date': '2016-03-28', 'value': 44.69},
 {'date': '2016-03-29', 'value': 34.6},
 {'date': '2016-03-30', 'value': 19.476190476190474},
 {'date': '2016-03-31', 'value': 31.721739130434774},
 {'date': '2016-04-01', 'value': 19.27391304347826},
 {'date': '2016-04-02', 'value': 20.65217391304348},
 {'date': '2016-04-03', 'value': 24.677272727272726},
 {'date': '2016-04-04', 'value': 42.50869565217391},
 {'date': '2016-04-05', 'value': 49.93043478260869},
 {'date': '2016-04-06', 'value': 56.63478260869565},
 {'date': '2016-04-07', 'value': 32.07391304347826},
 {'date': '2016-04-08', 'value': 31.56956521739131},
 {'date': '2016-04-09', 'value': 22.00454545454545},
 {'date': '2016-04-10', 'value': 21.30869565217391},
 {'date': '2016-04-11', 'value': 23.395652173913046},
 {'date': '2016-04-12', 'value': 40.69565217391305},
 {'date': '2016-04-13', 'value': 66.53636363636363},
 {'date': '2016-04-14', 'value': 37.47272727272728},
 {'date': '2016-04-15', 'value': 29.077272727272724},
 {'date': '2016-04-16', 'value': 23.99545454545455},
 {'date': '2016-04-17', 'value': 28.790909090909096},
 {'date': '2016-04-18', 'value': 20.199999999999996},
 {'date': '2016-04-19', 'value': 29.977272727272734},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

poland_daily = (
    df_results.groupby("date")
              .agg(poland_pm10_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

poland_daily

           date  france_pm10_mean
0    2016-01-30         23.433673
1    2016-01-31         14.652372
2    2016-02-01         22.070695
3    2016-02-02         12.797120
4    2016-02-03         15.112168
...         ...               ...
3409 2026-02-24         10.415971
3410 2026-02-25         17.840001
3411 2026-02-26         29.210439
3412 2026-02-27         35.605193
3413 2026-02-28         34.867596

[3414 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
poland_daily[["date", "poland_pm10_mean"]].to_csv(
    "daily_avg_poland_PM10.csv",
    index=False
)

# PM2.5

### Get 200 stations located in France that measure PM2.5
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "PL",   # only consider stations located in poland
    "parameters_id": 2,   # PM2.5
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm25 = df_sorted

df_top_pm25

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
3,2511,Reja,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4887, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.55094028, 'longitude': 19.7052...",None,"[19.70527778, 52.55094028, 19.70527778, 52.550...",None,2016-01-30 01:00:00+00:00,2017-01-08 08:00:00+00:00
0,28,Ursynów,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5009, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 52.16077306, 'longitude': 21.0391...",None,"[21.03916667, 52.16077306, 21.03916667, 52.160...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
1,43,Konarskiego,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4990, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.17203333, 'longitude': 22.2727...",None,"[22.27277778, 52.17203333, 22.27277778, 52.172...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
2,2467,Marszałkowska,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4744, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.22517222, 'longitude': 21.8931...",None,"[21.89311111, 52.22517222, 21.89311111, 52.225...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
4,2531,Komunikacyjna,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5028, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.21929306, 'longitude': 21.0058...",None,"[21.00583333, 52.21929306, 21.00583333, 52.219...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,3360076,"Lubań, ul. Ludowa",Lubań,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11960799, 'name': 'pm10 µg/m³', 'param...","{'latitude': 51.120091, 'longitude': 15.298189}","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[15.298189, 51.120091, 15.298189, 51.120091]",None,2025-01-08 11:00:00+00:00,2025-10-10 15:00:00+00:00
197,3362953,"Tomaszów Lubelski, ul. Janusza Petera",Tomaszów Lubelski,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11981591, 'name': 'pm10 µg/m³', 'param...","{'latitude': 50.444128, 'longitude': 23.421553}","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[23.421553, 50.444128, 23.421553, 50.444128]",None,2025-01-10 10:00:00+00:00,2025-10-10 14:00:00+00:00
198,3616712,"Katowice, ul. Dudy-Gracza",Katowice,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12405264, 'name': 'no2 µg/m³', 'parame...","{'latitude': 50.25848299999999, 'longitude': 1...","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[19.036217, 50.25848299999999, 19.036217, 50.2...",None,2025-03-07 13:00:00+00:00,2025-10-10 15:00:00+00:00
199,5554541,"Warszawa, al. Solidarności",Warszawa,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13952345, 'name': 'no2 µg/m³', 'parame...","{'latitude': 52.243573, 'longitude': 20.999214}","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[20.999214, 52.243573, 20.999214, 52.243573]",None,2025-08-25 08:00:00+00:00,2025-10-10 13:00:00+00:00
200,5554542,"Warszawa, ul. Grochowska",Warszawa,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13952348, 'name': 'no2 µg/m³', 'parame...","{'latitude': 52.24570400000001, 'longitude': 2...","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[21.080427, 52.24570400000001, 21.080427, 52.2...",None,2025-08-25 08:00:00+00:00,2025-10-10 13:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [15]:
rows = []

for _, station in df_top_pm25.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM25 behalten
        if sensor["parameter"]["id"] == 2:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm25_sensors = pd.DataFrame(rows)

df_pm25_sensors

     station_id                           station_name  sensor_id sensor_name
0          2511                                   Reja       4901  pm25 µg/m³
1            28                                Ursynów         47  pm25 µg/m³
2            43                            Konarskiego         63  pm25 µg/m³
3          2467                          Marszałkowska       4999  pm25 µg/m³
4          2531                          Komunikacyjna       5011  pm25 µg/m³
..          ...                                    ...        ...         ...
196     3360076                      Lubań, ul. Ludowa   11960800  pm25 µg/m³
197     3362953  Tomaszów Lubelski, ul. Janusza Petera   11981590  pm25 µg/m³
198     3616712              Katowice, ul. Dudy-Gracza   12405263  pm25 µg/m³
199     5554541             Warszawa, al. Solidarności   13952344  pm25 µg/m³
200     5554542               Warszawa, ul. Grochowska   13952347  pm25 µg/m³

[201 rows x 4 columns]

In [16]:
sensor_ids = df_pm25_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

201

[4901,
 47,
 63,
 4999,
 5011,
 5125,
 5165,
 5221,
 7391,
 10763,
 11014,
 35239,
 35055,
 35596,
 20740,
 35932,
 1308872,
 20854,
 34897,
 35412,
 1307549,
 20898,
 34913,
 34915,
 36483,
 22616,
 23068,
 24003,
 24339,
 26857,
 28114,
 28398,
 28502,
 29764,
 30071,
 30538,
 34598,
 34852,
 35874,
 34918,
 35035,
 35445,
 35068,
 35081,
 35108,
 35097,
 35121,
 35540,
 35217,
 35212,
 35221,
 35275,
 35303,
 36005,
 35620,
 35812,
 35732,
 36516,
 35836,
 1307955,
 7743958,
 35870,
 10741659,
 245894,
 36162,
 36260,
 26099,
 36405,
 35208,
 35885,
 1284247,
 36337,
 1562415,
 245897,
 1731994,
 36281,
 22647,
 17821,
 22713,
 18409,
 1289066,
 34850,
 35322,
 20858,
 35863,
 35993,
 35680,
 20855,
 20936,
 20881,
 20593,
 20901,
 18093,
 35454,
 20886,
 20919,
 35478,
 35144,
 35022,
 234714,
 35940,
 35613,
 35105,
 21679,
 35281,
 2589397,
 34890,
 22591,
 21554,
 35060,
 35258,
 35255,
 35461,
 35554,
 35085,
 35418,
 39293,
 245891,
 245890,
 386069,
 386092,
 1331070,
 388483,
 391202,
 425730,
 426780,
 852447,
 1289063,
 1289736,
 1303274,
 1562264,
 1562269,
 1562274,
 1562280,
 1562365,
 1562406,
 1562393,
 1562418,
 1562417,
 1727807,
 1727806,
 2017511,
 2023927,
 5079423,
 5079427,
 5079548,
 5079554,
 5079543,
 5079626,
 5079699,
 5079712,
 5079768,
 5079770,
 2507680,
 2553430,
 2553429,
 2553431,
 2555014,
 2555016,
 2554298,
 2555355,
 2569039,
 2589398,
 2666313,
 2704494,
 2773207,
 2773173,
 3490325,
 5079559,
 7176018,
 7576281,
 7610121,
 7634248,
 7634249,
 7635037,
 7644996,
 7660690,
 7676022,
 7695571,
 7749546,
 7754909,
 7775528,
 11142469,
 11428784,
 11428783,
 11716275,
 11865191,
 11872352,
 11872347,
 11872349,
 11883225,
 11884882,
 11948360,
 12078712,
 11950464,
 11959843,
 11960800,
 11981590,
 12405263,
 13952344,
 13952347]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 4901: Seite 1, 299 Ergebnisse
Sensor 47: Seite 1, 298 Ergebnisse
Sensor 63: Seite 1, 299 Ergebnisse
Sensor 4999: Seite 1, 297 Ergebnisse
Sensor 5011: Seite 1, 298 Ergebnisse
Sensor 5125: Seite 1, 298 Ergebnisse
Sensor 5165: Seite 1, 296 Ergebnisse
Sensor 5221: Seite 1, 295 Ergebnisse
Sensor 7391: Seite 1, 21 Ergebnisse
Sensor 10763: Seite 1, 1000 Ergebnisse
Sensor 10763: Seite 2, 1000 Ergebnisse
Sensor 10763: Seite 3, 1000 Ergebnisse
Sensor 10763: Seite 4, 80 Ergebnisse
Sensor 11014: Seite 1, 1000 Ergebnisse
Sensor 11014: Seite 2, 1000 Ergebnisse
Sensor 11014: Seite 3, 1000 Ergebnisse
Sensor 11014: Seite 4, 55 Ergebnisse
Sensor 35239: Seite 1, 1000 Ergebnisse
Sensor 35239: Seite 2, 1000 Ergebnisse
Sensor 35239: Seite 3, 551 Ergebnisse
Sensor 35055: Seite 1, 1000 Ergebnisse
Sensor 35055: Seite 2, 1000 Ergebnisse
Sensor 35055: Seite 3, 501 Ergebnisse
Sensor 35596: Seite 1, 1000 Ergebnisse
Sensor 35596: Seite 2, 1000 Ergebnisse
Sensor 35596: Seite 3, 506 Ergebnisse
Sensor 20740: Seite 1, 384 Ergebnisse
Sensor 35932: Seite 1, 1000 Ergebnisse
Sensor 35932: Seite 2, 1000 Ergebnisse
Sensor 35932: Seite 3, 123 Ergebnisse
Sensor 1308872: Seite 1, 1000 Ergebnisse
Sensor 1308872: Seite 2, 479 Ergebnisse
Sensor 20854: Seite 1, 405 Ergebnisse
Sensor 34897: Seite 1, 1000 Ergebnisse
Sensor 34897: Seite 2, 1000 Ergebnisse
Sensor 34897: Seite 3, 514 Ergebnisse
Sensor 35412: Seite 1, 1000 Ergebnisse
Sensor 35412: Seite 2, 1000 Ergebnisse
Sensor 35412: Seite 3, 548 Ergebnisse
Sensor 1307549: Seite 1, 1000 Ergebnisse
Sensor 1307549: Seite 2, 649 Ergebnisse
Sensor 20898: Seite 1, 382 Ergebnisse
Sensor 34913: Seite 1, 1000 Ergebnisse
Sensor 34913: Seite 2, 1000 Ergebnisse
Sensor 34913: Seite 3, 141 Ergebnisse
Sensor 34915: Seite 1, 1000 Ergebnisse
Sensor 34915: Seite 2, 1000 Ergebnisse
Sensor 34915: Seite 3, 145 Ergebnisse
Sensor 36483: Seite 1, 1000 Ergebnisse
Sensor 36483: Seite 2, 1000 Ergebnisse
Sensor 36483: Seite 3, 131 Ergebnisse
Sensor 22616: Seite 1, 1000 Ergebnisse
Sensor 22616: Seite 2, 391 Ergebnisse
Sensor 23068: Seite 1, 1000 Ergebnisse
Sensor 23068: Seite 2, 1000 Ergebnisse
Sensor 23068: Seite 3, 357 Ergebnisse
Sensor 24003: Seite 1, 1000 Ergebnisse
Sensor 24003: Seite 2, 1000 Ergebnisse
Sensor 24003: Seite 3, 498 Ergebnisse
Sensor 24339: Seite 1, 1000 Ergebnisse
Sensor 24339: Seite 2, 1000 Ergebnisse
Sensor 24339: Seite 3, 95 Ergebnisse
Sensor 26857: Seite 1, 1000 Ergebnisse
Sensor 26857: Seite 2, 1000 Ergebnisse
Sensor 26857: Seite 3, 498 Ergebnisse
Sensor 28114: Seite 1, 1000 Ergebnisse
Sensor 28114: Seite 2, 1000 Ergebnisse
Sensor 28114: Seite 3, 134 Ergebnisse
Sensor 28398: Seite 1, 1000 Ergebnisse
Sensor 28398: Seite 2, 1000 Ergebnisse
Sensor 28398: Seite 3, 498 Ergebnisse
Sensor 28502: Seite 1, 1000 Ergebnisse
Sensor 28502: Seite 2, 1000 Ergebnisse
Sensor 28502: Seite 3, 530 Ergebnisse
Sensor 29764: Seite 1, 1000 Ergebnisse
Sensor 29764: Seite 2, 1000 Ergebnisse
Sensor 29764: Seite 3, 520 Ergebnisse
Sensor 30071: Seite 1, 1000 Ergebnisse
Sensor 30071: Seite 2, 1000 Ergebnisse
Sensor 30071: Seite 3, 45 Ergebnisse
Sensor 30538: Seite 1, 1000 Ergebnisse
Sensor 30538: Seite 2, 1000 Ergebnisse
Sensor 30538: Seite 3, 426 Ergebnisse
Sensor 34598: Seite 1, 1000 Ergebnisse
Sensor 34598: Seite 2, 1000 Ergebnisse
Sensor 34598: Seite 3, 529 Ergebnisse
Sensor 34852: Seite 1, 1000 Ergebnisse
Sensor 34852: Seite 2, 1000 Ergebnisse
Sensor 34852: Seite 3, 413 Ergebnisse
Sensor 35874: Seite 1, 1000 Ergebnisse
Sensor 35874: Seite 2, 1000 Ergebnisse
Sensor 35874: Seite 3, 312 Ergebnisse
Sensor 34918: Seite 1, 1000 Ergebnisse
Sensor 34918: Seite 2, 1000 Ergebnisse
Sensor 34918: Seite 3, 543 Ergebnisse
Sensor 35035: Seite 1, 1000 Ergebnisse
Sensor 35035: Seite 2, 1000 Ergebnisse
Sensor 35035: Seite 3, 486 Ergebnisse
Sensor 35445: Seite 1, 1000 Ergebnisse
Sensor 35445: Seite 2, 1000 Ergebnisse
Sensor 35445: Seite 3, 519 Ergebnisse
Sensor 35068: Seite 1, 1000 Ergebnisse
Sensor 35068: Seite 2, 1000 Ergebnisse
Sensor 35068: Seite 3, 543 Ergebnisse
Sensor 35081: Seite 1, 1000 Ergebnisse
Sensor 35081: Seite 2, 202 Ergebnisse
Sensor 35108: Seite 1, 1000 Ergebnisse
Sensor 35108: Seite 2, 1000 Ergebnisse
Sensor 35108: Seite 3, 514 Ergebnisse
Sensor 35097: Seite 1, 1000 Ergebnisse
Sensor 35097: Seite 2, 1000 Ergebnisse
Sensor 35097: Seite 3, 526 Ergebnisse
Sensor 35121: Seite 1, 1000 Ergebnisse
Sensor 35121: Seite 2, 1000 Ergebnisse
Sensor 35121: Seite 3, 161 Ergebnisse
Sensor 35540: Seite 1, 1000 Ergebnisse
Sensor 35540: Seite 2, 1000 Ergebnisse
Sensor 35540: Seite 3, 511 Ergebnisse
Sensor 35217: Seite 1, 1000 Ergebnisse
Sensor 35217: Seite 2, 840 Ergebnisse
Sensor 35212: Seite 1, 1000 Ergebnisse
Sensor 35212: Seite 2, 1000 Ergebnisse
Sensor 35212: Seite 3, 507 Ergebnisse
Sensor 35221: Seite 1, 1000 Ergebnisse
Sensor 35221: Seite 2, 1000 Ergebnisse
Sensor 35221: Seite 3, 527 Ergebnisse
Sensor 35275: Seite 1, 1000 Ergebnisse
Sensor 35275: Seite 2, 1000 Ergebnisse
Sensor 35275: Seite 3, 478 Ergebnisse
Sensor 35303: Seite 1, 1000 Ergebnisse
Sensor 35303: Seite 2, 1000 Ergebnisse
Sensor 35303: Seite 3, 539 Ergebnisse
Sensor 36005: Seite 1, 1000 Ergebnisse
Sensor 36005: Seite 2, 1000 Ergebnisse
Sensor 36005: Seite 3, 138 Ergebnisse
Sensor 35620: Seite 1, 1000 Ergebnisse
Sensor 35620: Seite 2, 1000 Ergebnisse
Sensor 35620: Seite 3, 419 Ergebnisse
Sensor 35812: Seite 1, 1000 Ergebnisse
Sensor 35812: Seite 2, 1000 Ergebnisse
Sensor 35812: Seite 3, 435 Ergebnisse
Sensor 35732: Seite 1, 1000 Ergebnisse
Sensor 35732: Seite 2, 1000 Ergebnisse
Sensor 35732: Seite 3, 518 Ergebnisse
Sensor 36516: Seite 1, 1000 Ergebnisse
Sensor 36516: Seite 2, 1000 Ergebnisse
Sensor 36516: Seite 3, 554 Ergebnisse
Sensor 35836: Seite 1, 1000 Ergebnisse
Sensor 35836: Seite 2, 1000 Ergebnisse
Sensor 35836: Seite 3, 539 Ergebnisse
Sensor 1307955: Seite 1, 570 Ergebnisse
Sensor 35870: Seite 1, 1000 Ergebnisse
Sensor 35870: Seite 2, 1000 Ergebnisse
Sensor 35870: Seite 3, 448 Ergebnisse
Sensor 245894: Seite 1, 1000 Ergebnisse
Sensor 245894: Seite 2, 776 Ergebnisse
Sensor 36162: Seite 1, 1000 Ergebnisse
Sensor 36162: Seite 2, 1000 Ergebnisse
Sensor 36162: Seite 3, 536 Ergebnisse
Sensor 36260: Seite 1, 1000 Ergebnisse
Sensor 36260: Seite 2, 1000 Ergebnisse
Sensor 36260: Seite 3, 466 Ergebnisse
Sensor 26099: Seite 1, 1000 Ergebnisse
Sensor 26099: Seite 2, 1000 Ergebnisse
Sensor 26099: Seite 3, 394 Ergebnisse
Sensor 36405: Seite 1, 1000 Ergebnisse
Sensor 36405: Seite 2, 1000 Ergebnisse
Sensor 36405: Seite 3, 121 Ergebnisse
Sensor 35208: Seite 1, 1000 Ergebnisse
Sensor 35208: Seite 2, 739 Ergebnisse
Sensor 35885: Seite 1, 1000 Ergebnisse
Sensor 35885: Seite 2, 1000 Ergebnisse
Sensor 35885: Seite 3, 56 Ergebnisse
Sensor 1284247: Seite 1, 1000 Ergebnisse
Sensor 1284247: Seite 2, 286 Ergebnisse
Sensor 36337: Seite 1, 1000 Ergebnisse
Sensor 36337: Seite 2, 619 Ergebnisse
Sensor 1562415: Seite 1, 326 Ergebnisse
Sensor 245897: Seite 1, 696 Ergebnisse
Sensor 1731994: Seite 1, 278 Ergebnisse
Sensor 36281: Seite 1, 1000 Ergebnisse
Sensor 36281: Seite 2, 450 Ergebnisse
Sensor 22647: Seite 1, 599 Ergebnisse
Sensor 17821: Seite 1, 29 Ergebnisse
Sensor 22713: Seite 1, 1000 Ergebnisse
Sensor 22713: Seite 2, 409 Ergebnisse
Sensor 18409: Seite 1, 1000 Ergebnisse
Sensor 18409: Seite 2, 1000 Ergebnisse
Sensor 18409: Seite 3, 536 Ergebnisse
Sensor 1289066: Seite 1, 489 Ergebnisse
Sensor 34850: Seite 1, 1000 Ergebnisse
Sensor 34850: Seite 2, 1000 Ergebnisse
Sensor 34850: Seite 3, 390 Ergebnisse
Sensor 35322: Seite 1, 1000 Ergebnisse
Sensor 35322: Seite 2, 1000 Ergebnisse
Sensor 35322: Seite 3, 491 Ergebnisse
Sensor 20858: Seite 1, 773 Ergebnisse
Sensor 35863: Seite 1, 1000 Ergebnisse
Sensor 35863: Seite 2, 1000 Ergebnisse
Sensor 35863: Seite 3, 471 Ergebnisse
Sensor 35993: Seite 1, 1000 Ergebnisse
Sensor 35993: Seite 2, 1000 Ergebnisse
Sensor 35993: Seite 3, 491 Ergebnisse
Sensor 35680: Seite 1, 700 Ergebnisse
Sensor 20855: Seite 1, 337 Ergebnisse
Sensor 20936: Seite 1, 362 Ergebnisse
Sensor 20881: Seite 1, 330 Ergebnisse
Sensor 20593: Seite 1, 316 Ergebnisse
Sensor 20901: Seite 1, 314 Ergebnisse
Sensor 18093: Seite 1, 1 Ergebnisse
Sensor 35454: Seite 1, 720 Ergebnisse
Sensor 20886: Seite 1, 171 Ergebnisse
Sensor 20919: Seite 1, 277 Ergebnisse
Sensor 35478: Seite 1, 1000 Ergebnisse
Sensor 35478: Seite 2, 1000 Ergebnisse
Sensor 35478: Seite 3, 381 Ergebnisse
Sensor 35144: Seite 1, 1000 Ergebnisse
Sensor 35144: Seite 2, 1000 Ergebnisse
Sensor 35144: Seite 3, 334 Ergebnisse
Sensor 35022: Seite 1, 1000 Ergebnisse
Sensor 35022: Seite 2, 1000 Ergebnisse
Sensor 35022: Seite 3, 68 Ergebnisse
Sensor 234714: Seite 1, 1000 Ergebnisse
Sensor 234714: Seite 2, 754 Ergebnisse
Sensor 35940: Seite 1, 339 Ergebnisse
Sensor 35613: Seite 1, 695 Ergebnisse
Sensor 35105: Seite 1, 356 Ergebnisse
Sensor 21679: Seite 1, 56 Ergebnisse
Sensor 35281: Seite 1, 293 Ergebnisse
Sensor 2589397: Seite 1, 630 Ergebnisse
Sensor 34890: Seite 1, 346 Ergebnisse
Sensor 22591: Seite 1, 339 Ergebnisse
Sensor 21554: Seite 1, 7 Ergebnisse
Sensor 35060: Seite 1, 330 Ergebnisse
Sensor 35258: Seite 1, 675 Ergebnisse
Sensor 35255: Seite 1, 323 Ergebnisse
Sensor 35461: Seite 1, 669 Ergebnisse
Sensor 35554: Seite 1, 281 Ergebnisse
Sensor 35085: Seite 1, 1000 Ergebnisse
Sensor 35085: Seite 2, 649 Ergebnisse
Sensor 35418: Seite 1, 1000 Ergebnisse
Sensor 35418: Seite 2, 1000 Ergebnisse
Sensor 35418: Seite 3, 5 Ergebnisse
Sensor 39293: Seite 1, 1000 Ergebnisse
Sensor 39293: Seite 2, 846 Ergebnisse
Sensor 245891: Seite 1, 340 Ergebnisse
Sensor 245890: Seite 1, 332 Ergebnisse
Sensor 386069: Seite 1, 339 Ergebnisse
Sensor 386092: Seite 1, 691 Ergebnisse
Sensor 1331070: Seite 1, 1000 Ergebnisse
Sensor 1331070: Seite 2, 741 Ergebnisse
Sensor 388483: Seite 1, 319 Ergebnisse
Sensor 391202: Seite 1, 292 Ergebnisse
Sensor 425730: Seite 1, 322 Ergebnisse
Sensor 426780: Seite 1, 741 Ergebnisse
Sensor 852447: Seite 1, 675 Ergebnisse
Sensor 1289063: Seite 1, 523 Ergebnisse
Sensor 1289736: Seite 1, 672 Ergebnisse
Sensor 1303274: Seite 1, 1000 Ergebnisse
Sensor 1303274: Seite 2, 663 Ergebnisse
Sensor 1562264: Seite 1, 364 Ergebnisse
Sensor 1562269: Seite 1, 353 Ergebnisse
Sensor 1562274: Seite 1, 361 Ergebnisse
Sensor 1562280: Seite 1, 361 Ergebnisse
Sensor 1562365: Seite 1, 359 Ergebnisse
Sensor 1562406: Seite 1, 208 Ergebnisse
Sensor 1562393: Seite 1, 649 Ergebnisse
Sensor 1562418: Seite 1, 635 Ergebnisse
Sensor 1562417: Seite 1, 348 Ergebnisse
Sensor 1727807: Seite 1, 1000 Ergebnisse
Sensor 1727807: Seite 2, 360 Ergebnisse
Sensor 1727806: Seite 1, 1000 Ergebnisse
Sensor 1727806: Seite 2, 324 Ergebnisse
Sensor 2017511: Seite 1, 1000 Ergebnisse
Sensor 2017511: Seite 2, 238 Ergebnisse
Sensor 2023927: Seite 1, 1000 Ergebnisse
Sensor 2023927: Seite 2, 210 Ergebnisse
Sensor 2507680: Seite 1, 288 Ergebnisse
Sensor 2553430: Seite 1, 1000 Ergebnisse
Sensor 2553430: Seite 2, 84 Ergebnisse
Sensor 2553429: Seite 1, 600 Ergebnisse
Sensor 2553431: Seite 1, 272 Ergebnisse
Sensor 2555014: Seite 1, 1000 Ergebnisse
Sensor 2555014: Seite 2, 27 Ergebnisse
Sensor 2555016: Seite 1, 293 Ergebnisse
Sensor 2554298: Seite 1, 281 Ergebnisse
Sensor 2555355: Seite 1, 292 Ergebnisse
Sensor 2569039: Seite 1, 1000 Ergebnisse
Sensor 2569039: Seite 2, 2 Ergebnisse
Sensor 2589398: Seite 1, 1000 Ergebnisse
Sensor 2589398: Seite 2, 79 Ergebnisse
Sensor 2666313: Seite 1, 648 Ergebnisse
Sensor 2704494: Seite 1, 577 Ergebnisse
Sensor 2773207: Seite 1, 273 Ergebnisse
Sensor 2773173: Seite 1, 281 Ergebnisse
Sensor 3490325: Seite 1, 613 Ergebnisse
Sensor 7775528: Seite 1, 711 Ergebnisse
202824

[{'date': '2016-01-30', 'value': 12.086363636363636},
 {'date': '2016-01-31', 'value': 6.5782608695652165},
 {'date': '2016-02-01', 'value': 12.717391304347826},
 {'date': '2016-02-02', 'value': 6.626086956521738},
 {'date': '2016-02-03', 'value': 6.88695652173913},
 {'date': '2016-02-04', 'value': 8.947826086956523},
 {'date': '2016-02-05', 'value': 14.45217391304348},
 {'date': '2016-02-06', 'value': 36.06086956521739},
 {'date': '2016-02-07', 'value': 31.226086956521737},
 {'date': '2016-02-08', 'value': 17.1304347826087},
 {'date': '2016-02-09', 'value': 9.408695652173913},
 {'date': '2016-02-10', 'value': 11.622727272727271},
 {'date': '2016-02-11', 'value': 17.13913043478261},
 {'date': '2016-02-12', 'value': 27.173913043478265},
 {'date': '2016-02-13', 'value': 26.926086956521733},
 {'date': '2016-02-14', 'value': 35.15652173913043},
 {'date': '2016-02-15', 'value': 48.61818181818182},
 {'date': '2016-02-16', 'value': 16.75909090909091},
 {'date': '2016-02-17', 'value': 14.900000000000002},
 {'date': '2016-02-18', 'value': 31.7695652173913},
 {'date': '2016-02-19', 'value': 19.717391304347824},
 {'date': '2016-02-20', 'value': 33.373913043478254},
 {'date': '2016-02-21', 'value': 10.334782608695651},
 {'date': '2016-02-22', 'value': 4.578260869565217},
 {'date': '2016-02-23', 'value': 11.639130434782608},
 {'date': '2016-02-24', 'value': 12.530434782608692},
 {'date': '2016-02-25', 'value': 19.743478260869562},
 {'date': '2016-02-26', 'value': 31.539130434782606},
 {'date': '2016-02-27', 'value': 41.37826086956522},
 {'date': '2016-02-28', 'value': 35.2},
 {'date': '2016-02-29', 'value': 26.040909090909096},
 {'date': '2016-03-01', 'value': 19.7},
 {'date': '2016-03-02', 'value': 36.604545454545466},
 {'date': '2016-03-03', 'value': 37.56521739130435},
 {'date': '2016-03-04', 'value': 25.313043478260866},
 {'date': '2016-03-05', 'value': 28.982608695652175},
 {'date': '2016-03-06', 'value': 29.900000000000002},
 {'date': '2016-03-07', 'value': 36.022727272727266},
 {'date': '2016-03-08', 'value': 38.556521739130446},
 {'date': '2016-03-09', 'value': 26.50869565217392},
 {'date': '2016-03-10', 'value': 13.52608695652174},
 {'date': '2016-03-11', 'value': 17.543478260869566},
 {'date': '2016-03-12', 'value': 21.66521739130435},
 {'date': '2016-03-13', 'value': 16.86086956521739},
 {'date': '2016-03-14', 'value': 30.917391304347824},
 {'date': '2016-03-15', 'value': 12.195652173913043},
 {'date': '2016-03-16', 'value': 17.556521739130435},
 {'date': '2016-03-17', 'value': 27.439130434782605},
 {'date': '2016-03-18', 'value': 18.37391304347826},
 {'date': '2016-03-19', 'value': 8.365217391304347},
 {'date': '2016-03-20', 'value': 19.64782608695652},
 {'date': '2016-03-21', 'value': 16.565217391304348},
 {'date': '2016-03-22', 'value': 12.613043478260868},
 {'date': '2016-03-23', 'value': 19.17391304347826},
 {'date': '2016-03-24', 'value': 28.795652173913048},
 {'date': '2016-03-25', 'value': 36.704347826086966},
 {'date': '2016-03-26', 'value': 26.713043478260865},
 {'date': '2016-03-27', 'value': 33.12857142857143},
 {'date': '2016-03-28', 'value': 35.93},
 {'date': '2016-03-29', 'value': 35.7},
 {'date': '2016-03-30', 'value': 14.352380952380951},
 {'date': '2016-03-31', 'value': 16.008695652173913},
 {'date': '2016-04-01', 'value': 10.4},
 {'date': '2016-04-02', 'value': 10.839130434782609},
 {'date': '2016-04-03', 'value': 16.004545454545454},
 {'date': '2016-04-04', 'value': 18.543478260869566},
 {'date': '2016-04-05', 'value': 27.02173913043478},
 {'date': '2016-04-06', 'value': 26.495652173913044},
 {'date': '2016-04-07', 'value': 24.773913043478263},
 {'date': '2016-04-08', 'value': 14.47391304347826},
 {'date': '2016-04-09', 'value': 14.778260869565216},
 {'date': '2016-04-10', 'value': 10.418181818181818},
 {'date': '2016-04-11', 'value': 12.969565217391304},
 {'date': '2016-04-12', 'value': 22.869565217391308},
 {'date': '2016-04-13', 'value': 34.6},
 {'date': '2016-04-14', 'value': 15.313043478260866},
 {'date': '2016-04-15', 'value': 14.530434782608692},
 {'date': '2016-04-16', 'value': 15.104347826086956},
 {'date': '2016-04-17', 'value': 16.78260869565217},
 {'date': '2016-04-18', 'value': 6.360869565217392},
 {'date': '2016-04-19', 'value': 9.160869565217391},
 {'date': '2016-04-20', 'value': 6.369565217391305},
 {'date': '2016-04-21', 'value': 8.608695652173914},
 {'date': '2016-04-22', 'value': 8.160869565217391},
 {'date': '2016-04-23', 'value': 14.286956521739132},
 {'date': '2016-04-24', 'value': 6.291304347826087},
 {'date': '2016-04-25', 'value': 11.41304347826087},
 {'date': '2016-04-26', 'value': 17.952173913043477},
 {'date': '2016-04-27', 'value': 11.482608695652175},
 {'date': '2016-04-28', 'value': 19.75},
 {'date': '2016-04-29', 'value': 15.414285714285715},
 {'date': '2016-04-30', 'value': 17.413043478260867},
 {'date': '2016-05-01', 'value': 18.873913043478264},
 {'date': '2016-05-02', 'value': 13.517391304347825},
 {'date': '2016-05-03', 'value': 14.417391304347827},
 {'date': '2016-05-04', 'value': 9.891304347826088},
 {'date': '2016-05-05', 'value': 14.269565217391301},
 {'date': '2016-05-06', 'value': 10.139130434782606},
 {'date': '2016-05-07', 'value': 8.626086956521739},
 {'date': '2016-05-08', 'value': 9.98695652173913},
 {'date': '2016-05-09', 'value': 10.891304347826086},
 {'date': '2016-05-10', 'value': 11.326086956521738},
 {'date': '2016-05-11', 'value': 14.000000000000002},
 {'date': '2016-05-12', 'value': 11.991304347826086},
 {'date': '2016-05-13', 'value': 9.777272727272726},
 {'date': '2016-05-14', 'value': 11.917391304347827},
 {'date': '2016-05-15', 'value': 5.321739130434783},
 {'date': '2016-05-16', 'value': 4.365217391304348},
 {'date': '2016-05-17', 'value': 7.056521739130437},
 {'date': '2016-05-18', 'value': 12.659090909090912},
 {'date': '2016-05-19', 'value': 15.291304347826086},
 {'date': '2016-05-20', 'value': 18.2304347826087},
 {'date': '2016-05-21', 'value': 13.686956521739125},
 {'date': '2016-05-22', 'value': 13.269565217391307},
 {'date': '2016-05-23', 'value': 11.569565217391307},
 {'date': '2016-05-24', 'value': 7.647826086956522},
 {'date': '2016-05-25', 'value': 9.930434782608696},
 {'date': '2016-05-26', 'value': 13.395652173913048},
 {'date': '2016-05-27', 'value': 16.547826086956526},
 {'date': '2016-05-28', 'value': 17.65},
 {'date': '2016-05-29', 'value': 11.233333333333333},
 {'date': '2016-05-30', 'value': 12.366666666666667},
 {'date': '2016-05-31', 'value': 13.869565217391301},
 {'date': '2016-06-01', 'value': 12.386956521739132},
 {'date': '2016-06-02', 'value': 9.43913043478261},
 {'date': '2016-06-03', 'value': 9.14782608695652},
 {'date': '2016-06-04', 'value': 15.243478260869562},
 {'date': '2016-06-05', 'value': 4.908695652173913},
 {'date': '2016-06-06', 'value': 3.552173913043479},
 {'date': '2016-06-07', 'value': 5.322727272727272},
 {'date': '2016-06-08', 'value': 8.043478260869565},
 {'date': '2016-06-09', 'value': 6.839130434782608},
 {'date': '2016-06-10', 'value': 6.6000000000000005},
 {'date': '2016-06-11', 'value': 3.382608695652174},
 {'date': '2016-06-12', 'value': 3.3782608695652177},
 {'date': '2016-06-13', 'value': 4.521739130434782},
 {'date': '2016-06-14', 'value': 6.504347826086957},
 {'date': '2016-06-15', 'value': 8.51304347826087},
 {'date': '2016-06-16', 'value': 6.4217391304347835},
 {'date': '2016-06-17', 'value': 6.017391304347825},
 {'date': '2016-06-18', 'value': 8.51304347826087},
 {'date': '2016-06-19', 'value': 8.143478260869564},
 {'date': '2016-06-20', 'value': 10.169565217391305},
 {'date': '2016-06-21', 'value': 12.31304347826087},
 {'date': '2016-06-22', 'value': 9.086956521739129},
 {'date': '2016-06-23', 'value': 9.382608695652172},
 {'date': '2016-06-24', 'value': 12.317391304347826},
 {'date': '2016-06-25', 'value': 15.556521739130435},
 {'date': '2016-06-26', 'value': 12.086363636363636},
 {'date': '2016-06-27', 'value': 3.45},
 {'date': '2016-06-28', 'value': 11.633333333333331},
 {'date': '2016-06-29', 'value': 9.326086956521738},
 {'date': '2016-06-30', 'value': 8.586956521739129},
 {'date': '2016-07-01', 'value': 6.760869565217392},
 {'date': '2016-07-02', 'value': 10.282608695652172},
 {'date': '2016-07-03', 'value': 6.534782608695653},
 {'date': '2016-07-04', 'value': 3.5434782608695645},
 {'date': '2016-07-05', 'value': 4.669565217391304},
 {'date': '2016-07-06', 'value': 4.1},
 {'date': '2016-07-07', 'value': 4.095652173913043},
 {'date': '2016-07-08', 'value': 5.260869565217391},
 {'date': '2016-07-09', 'value': 5.834782608695652},
 {'date': '2016-07-10', 'value': 4.9565217391304355},
 {'date': '2016-07-11', 'value': 7.313043478260869},
 {'date': '2016-07-12', 'value': 13.043478260869568},
 {'date': '2016-07-13', 'value': 14.26521739130435},
 {'date': '2016-07-14', 'value': 8.708695652173912},
 {'date': '2016-07-15', 'value': 3.369565217391304},
 {'date': '2016-07-16', 'value': 5.865217391304347},
 {'date': '2016-07-17', 'value': 6.543478260869566},
 {'date': '2016-07-18', 'value': 4.539130434782609},
 {'date': '2016-07-19', 'value': 3.130434782608695},
 {'date': '2016-07-20', 'value': 3.760869565217392},
 {'date': '2016-07-21', 'value': 4.42608695652174},
 {'date': '2016-07-22', 'value': 5.621739130434782},
 {'date': '2016-07-23', 'value': 9.608695652173912},
 {'date': '2016-07-24', 'value': 13.047826086956524},
 {'date': '2016-07-25', 'value': 11.143478260869566},
 {'date': '2016-07-26', 'value': 12.939130434782612},
 {'date': '2016-07-27', 'value': 13.3},
 {'date': '2016-07-28', 'value': 13.476190476190476},
 {'date': '2016-07-29', 'value': 15.282608695652176},
 {'date': '2016-07-30', 'value': 11.52608695652174},
 {'date': '2016-07-31', 'value': 9.813636363636363},
 {'date': '2016-08-01', 'value': 8.322727272727272},
 {'date': '2016-08-02', 'value': 5.904545454545455},
 {'date': '2016-08-03', 'value': 9.854545454545455},
 {'date': '2016-08-04', 'value': 5.868181818181818},
 {'date': '2016-08-05', 'value': 8.045454545454545},
 {'date': '2016-08-06', 'value': 8.481818181818182},
 {'date': '2016-08-07', 'value': 3.681818181818181},
 {'date': '2016-08-08', 'value': 6.109090909090909},
 {'date': '2016-08-09', 'value': 8.65},
 {'date': '2016-08-10', 'value': 10.68181818181818},
 {'date': '2016-08-11', 'value': 4.281818181818181},
 {'date': '2016-08-12', 'value': 6.081818181818182},
 {'date': '2016-08-13', 'value': 11.036363636363635},
 {'date': '2016-08-14', 'value': 7.586363636363638},
 {'date': '2016-08-15', 'value': 3.8},
 {'date': '2016-08-16', 'value': 5.843478260869567},
 {'date': '2016-08-17', 'value': 6.069565217391304},
 {'date': '2016-08-18', 'value': 6.5826086956521745},
 {'date': '2016-08-19', 'value': 10.126086956521737},
 {'date': '2016-08-20', 'value': 14.252173913043478},
 {'date': '2016-08-21', 'value': 12.791304347826088},
 {'date': '2016-08-22', 'value': 13.11304347826087},
 {'date': '2016-08-23', 'value': 11.678260869565218},
 {'date': '2016-08-24', 'value': 6.48695652173913},
 {'date': '2016-08-25', 'value': 6.81304347826087},
 {'date': '2016-08-26', 'value': 10.2},
 {'date': '2016-08-27', 'value': 9.114285714285716},
 {'date': '2016-08-28', 'value': 14.747826086956517},
 {'date': '2016-08-29', 'value': 10.752173913043478},
 {'date': '2016-08-30', 'value': 3.7565217391304344},
 {'date': '2016-08-31', 'value': 5.930434782608696},
 {'date': '2016-09-01', 'value': 8.834782608695653},
 {'date': '2016-09-02', 'value': 11.669565217391304},
 {'date': '2016-09-03', 'value': 12.552173913043477},
 {'date': '2016-09-04', 'value': 11.02608695652174},
 {'date': '2016-09-05', 'value': 6.004347826086955},
 {'date': '2016-09-06', 'value': 4.791304347826087},
 {'date': '2016-09-07', 'value': 9.143478260869564},
 {'date': '2016-09-08', 'value': 17.434782608695652},
 {'date': '2016-09-09', 'value': 20.665217391304346},
 {'date': '2016-09-10', 'value': 21.326086956521742},
 {'date': '2016-09-11', 'value': 21.33913043478261},
 {'date': '2016-09-12', 'value': 16.882608695652173},
 {'date': '2016-09-13', 'value': 18.291304347826085},
 {'date': '2016-09-14', 'value': 7.769565217391305},
 {'date': '2016-09-15', 'value': 8.747826086956522},
 {'date': '2016-09-16', 'value': 13.31739130434783},
 {'date': '2016-09-17', 'value': 10.069565217391304},
 {'date': '2016-09-18', 'value': 5.3},
 {'date': '2016-09-19', 'value': 7.534782608695653},
 {'date': '2016-09-20', 'value': 13.308695652173917},
 {'date': '2016-09-21', 'value': 8.52608695652174},
 {'date': '2016-09-22', 'value': 10.544444444444444},
 {'date': '2016-11-04', 'value': 15.41},
 {'date': '2016-11-09', 'value': 39.133333333333326},
 {'date': '2016-11-10', 'value': 32.090909090909086},
 {'date': '2016-11-11', 'value': 20.968181818181822},
 {'date': '2016-11-12', 'value': 28.172727272727276},
 {'date': '2016-11-13', 'value': 23.204545454545453},
 {'date': '2016-11-14', 'value': 28.822727272727267},
 {'date': '2016-11-15', 'value': 28.813636363636366},
 {'date': '2016-11-16', 'value': 19.004347826086956},
 {'date': '2016-11-17', 'value': 17.191304347826087},
 {'date': '2016-11-18', 'value': 23.84347826086957},
 {'date': '2016-11-19', 'value': 32.77826086956522},
 {'date': '2016-11-20', 'value': 17.17391304347826},
 {'date': '2016-11-21', 'value': 20.082608695652176},
 {'date': '2016-11-22', 'value': 19.263636363636365},
 {'date': '2016-11-23', 'value': 34.447826086956525},
 {'date': '2016-11-24', 'value': 48.6},
 {'date': '2016-11-25', 'value': 34.85909090909091},
 {'date': '2016-11-26', 'value': 27.48695652173913},
 {'date': '2016-11-27', 'value': 10.573913043478262},
 {'date': '2016-11-28', 'value': 8.939130434782609},
 {'date': '2016-11-29', 'value': 13.854545454545455},
 {'date': '2016-11-30', 'value': 20.254545454545454},
 {'date': '2016-12-01', 'value': 20.51304347826087},
 {'date': '2016-12-02', 'value': 9.395454545454546},
 {'date': '2016-12-03', 'value': 9.134782608695652},
 {'date': '2016-12-04', 'value': 21.999999999999996},
 {'date': '2016-12-05', 'value': 27.33913043478261},
 {'date': '2016-12-06', 'value': 23.104347826086954},
 {'date': '2016-12-07', 'value': 32.31739130434782},
 {'date': '2016-12-08', 'value': 17.27826086956522},
 {'date': '2016-12-09', 'value': 19.14782608695652},
 {'date': '2016-12-10', 'value': 17.463636363636365},
 {'date': '2016-12-11', 'value': 16.747826086956515},
 {'date': '2016-12-12', 'value': 8.504347826086956},
 {'date': '2016-12-13', 'value': 34.45652173913043},
 {'date': '2016-12-14', 'value': 26.134782608695648},
 {'date': '2016-12-15', 'value': 12.04782608695652},
 {'date': '2016-12-16', 'value': 46.4},
 {'date': '2016-12-17', 'value': 47.49565217391305},
 {'date': '2016-12-18', 'value': 35.68260869565217},
 {'date': '2016-12-19', 'value': 27.173913043478255},
 {'date': '2016-12-20', 'value': 34.12173913043478},
 {'date': '2016-12-21', 'value': 41.8695652173913},
 {'date': '2016-12-22', 'value': 49.734782608695646},
 {'date': '2016-12-23', 'value': 31.286956521739132},
 {'date': '2016-12-24', 'value': 24.2},
 {'date': '2016-12-25', 'value': 12.35},
 {'date': '2016-12-26', 'value': 6.260869565217392},
 {'date': '2016-12-27', 'value': 5.665217391304348},
 {'date': '2016-12-28', 'value': 7.418181818181819},
 {'date': '2016-12-29', 'value': 27.952173913043477},
 {'date': '2016-12-30', 'value': 36.61739130434783},
 {'date': '2016-12-31', 'value': 36.03913043478261},
 {'date': '2017-01-01', 'value': 28.426086956521743},
 {'date': '2017-01-02', 'value': 23.386956521739133},
 {'date': '2017-01-03', 'value': 17.94782608695652},
 {'date': '2017-01-04', 'value': 6.6173913043478265},
 {'date': '2017-01-05', 'value': 5.839130434782609},
 {'date': '2017-01-06', 'value': 9.560869565217393},
 {'date': '2017-01-07', 'value': 45.05217391304348},
 {'date': '2017-01-08', 'value': 99.6888888888889},
 {'date': '2016-01-30', 'value': 14.631818181818183},
 {'date': '2016-01-31', 'value': 9.991304347826086},
 {'date': '2016-02-01', 'value': 15.917391304347829},
 {'date': '2016-02-02', 'value': 7.763636363636365},
 {'date': '2016-02-03', 'value': 8.786956521739128},
 {'date': '2016-02-04', 'value': 13.482608695652175},
 {'date': '2016-02-05', 'value': 19.104347826086958},
 {'date': '2016-02-06', 'value': 35.83478260869565},
 {'date': '2016-02-07', 'value': 24.400000000000002},
 {'date': '2016-02-08', 'value': 21.330434782608698},
 {'date': '2016-02-09', 'value': 9.265217391304347},
 {'date': '2016-02-10', 'value': 12.03913043478261},
 {'date': '2016-02-11', 'value': 18.87391304347826},
 {'date': '2016-02-12', 'value': 19.656521739130437},
 {'date': '2016-02-13', 'value': 24.7695652173913},
 {'date': '2016-02-14', 'value': 33.49565217391305},
 {'date': '2016-02-15', 'value': 37.69565217391304},
 {'date': '2016-02-16', 'value': 17.856521739130436},
 {'date': '2016-02-17', 'value': 13.700000000000001},
 {'date': '2016-02-18', 'value': 30.47826086956522},
 {'date': '2016-02-19', 'value': 22.88695652173913},
 {'date': '2016-02-20', 'value': 30.517391304347825},
 {'date': '2016-02-21', 'value': 14.008695652173913},
 {'date': '2016-02-22', 'value': 5.808695652173912},
 {'date': '2016-02-23', 'value': 15.347826086956522},
 {'date': '2016-02-24', 'value': 16.400000000000002},
 {'date': '2016-02-25', 'value': 21.17391304347826},
 {'date': '2016-02-26', 'value': 41.934782608695656},
 {'date': '2016-02-27', 'value': 47.75454545454545},
 {'date': '2016-02-28', 'value': 39.1},
 {'date': '2016-02-29', 'value': 37.0090909090909},
 {'date': '2016-03-01', 'value': 17.269565217391303},
 {'date': '2016-03-02', 'value': 27.721739130434777},
 {'date': '2016-03-03', 'value': 29.5},
 {'date': '2016-03-04', 'value': 24.008695652173916},
 {'date': '2016-03-05', 'value': 35.40869565217392},
 {'date': '2016-03-06', 'value': 28.121739130434776},
 {'date': '2016-03-07', 'value': 28.16521739130435},
 {'date': '2016-03-08', 'value': 24.952173913043477},
 {'date': '2016-03-09', 'value': 32.17391304347826},
 {'date': '2016-03-10', 'value': 16.54347826086956},
 {'date': '2016-03-11', 'value': 17.12608695652174},
 {'date': '2016-03-12', 'value': 23.256521739130438},
 {'date': '2016-03-13', 'value': 14.58695652173913},
 {'date': '2016-03-14', 'value': 35.61304347826087},
 {'date': '2016-03-15', 'value': 14.190909090909088},
 {'date': '2016-03-16', 'value': 15.895652173913044},
 {'date': '2016-03-17', 'value': 36.891304347826086},
 {'date': '2016-03-18', 'value': 23.59130434782608},
 {'date': '2016-03-19', 'value': 8.065217391304348},
 {'date': '2016-03-20', 'value': 28.08181818181818},
 {'date': '2016-03-21', 'value': 21.934782608695656},
 {'date': '2016-03-22', 'value': 18.573913043478264},
 {'date': '2016-03-23', 'value': 15.508695652173913},
 {'date': '2016-03-24', 'value': 22.40869565217392},
 {'date': '2016-03-25', 'value': 43.62608695652175},
 {'date': '2016-03-26', 'value': 44.02272727272728},
 {'date': '2016-03-27', 'value': 41.34761904761905},
 {'date': '2016-03-28', 'value': 36.72},
 {'date': '2016-03-29', 'value': 28.75},
 {'date': '2016-03-30', 'value': 13.028571428571427},
 {'date': '2016-03-31', 'value': 23.047826086956523},
 {'date': '2016-04-01', 'value': 12.573913043478262},
 {'date': '2016-04-02', 'value': 12.656521739130437},
 {'date': '2016-04-03', 'value': 16.986363636363635},
 {'date': '2016-04-04', 'value': 23.895652173913046},
 {'date': '2016-04-05', 'value': 27.221739130434788},
 {'date': '2016-04-06', 'value': 38.469565217391306},
 {'date': '2016-04-07', 'value': 22.147826086956524},
 {'date': '2016-04-08', 'value': 19.07391304347826},
 {'date': '2016-04-09', 'value': 12.563636363636364},
 {'date': '2016-04-10', 'value': 14.882608695652175},
 {'date': '2016-04-11', 'value': 13.395652173913048},
 {'date': '2016-04-12', 'value': 28.608695652173914},
 {'date': '2016-04-13', 'value': 47.84545454545455},
 {'date': '2016-04-14', 'value': 25.063636363636366},
 {'date': '2016-04-15', 'value': 15.709090909090905},
 {'date': '2016-04-16', 'value': 17.86818181818182},
 {'date': '2016-04-17', 'value': 22.181818181818183},
 {'date': '2016-04-18', 'value': 10.022727272727273},
 {'date': '2016-04-19', 'value': 15.227272727272727},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

poland_daily = (
    df_results.groupby("date")
              .agg(poland_pm25_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

poland_daily

           date  france_pm25_mean
0    2016-01-30         16.974973
1    2016-01-31         10.945331
2    2016-02-01         17.464155
3    2016-02-02          9.558004
4    2016-02-03          9.825543
...         ...               ...
3436 2026-02-24          8.730637
3437 2026-02-25         12.908593
3438 2026-02-26         21.601657
3439 2026-02-27         24.994349
3440 2026-02-28         26.887992

[3441 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
poland_daily[["date", "poland_pm25_mean"]].to_csv(
    "daily_avg_poland_PM25.csv",
    index=False
)

# NO2

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "PL",   # only consider stations located in poland
    "parameters_id": 5,   # NO2
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(df["datetimeFirst"].apply(lambda x: x["utc"]))
df["datetimeLast"] = pd.to_datetime(df["datetimeLast"].apply(lambda x: x["utc"]))

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_no2 = df_sorted

df_top_no2

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
4,2511,Reja,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4887, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.55094028, 'longitude': 19.7052...",None,"[19.70527778, 52.55094028, 19.70527778, 52.550...",None,2016-01-30 01:00:00+00:00,2017-01-08 08:00:00+00:00
5,2529,KPN,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4993, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 52.28585778, 'longitude': 20.4555...",None,"[20.45555556, 52.28585778, 20.45555556, 52.285...",None,2016-01-30 01:00:00+00:00,2017-01-08 08:00:00+00:00
0,28,Ursynów,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 5009, 'name': 'no2 µg/m³', 'parameter'...","{'latitude': 52.16077306, 'longitude': 21.0391...",None,"[21.03916667, 52.16077306, 21.03916667, 52.160...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
1,43,Konarskiego,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 4990, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.17203333, 'longitude': 22.2727...",None,"[22.27277778, 52.17203333, 22.27277778, 52.172...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
2,1207,Gimnazjum,NaN,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 214, 'name': 'Poland'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 2165, 'name': 'co µg/m³', 'parameter':...","{'latitude': 52.56083333, 'longitude': 19.6886...",None,"[19.68861111, 52.56083333, 19.68861111, 52.560...",None,2016-01-30 01:00:00+00:00,2017-01-08 07:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,3358648,"Sulechów, ul. Licealna",Sulechów,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11950466, 'name': 'bc µg/m³', 'paramet...","{'latitude': 52.08483300004918, 'longitude': 1...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[15.633249999605246, 52.08483300004918, 15.633...",None,2025-01-07 12:00:00+00:00,2026-01-02 07:00:00+00:00
233,3359900,"Gdańsk, ul. Powstańców Warszawskich",Gdańsk,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11959844, 'name': 'co µg/m³', 'paramet...","{'latitude': 54.353196000000004, 'longitude': ...","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[18.635267, 54.353196000000004, 18.635267, 54....",None,2025-01-08 08:00:00+00:00,2025-10-10 14:00:00+00:00
235,3616712,"Katowice, ul. Dudy-Gracza",Katowice,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12405264, 'name': 'no2 µg/m³', 'parame...","{'latitude': 50.25848299999999, 'longitude': 1...","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[19.036217, 50.25848299999999, 19.036217, 50.2...",None,2025-03-07 13:00:00+00:00,2025-10-10 15:00:00+00:00
236,5554541,"Warszawa, al. Solidarności",Warszawa,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13952345, 'name': 'no2 µg/m³', 'parame...","{'latitude': 52.243573, 'longitude': 20.999214}","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[20.999214, 52.243573, 20.999214, 52.243573]",None,2025-08-25 08:00:00+00:00,2025-10-10 13:00:00+00:00
237,5554542,"Warszawa, ul. Grochowska",Warszawa,Europe/Warsaw,"{'id': 77, 'code': 'PL', 'name': 'Poland'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 199, 'name': 'GIOS'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 13952348, 'name': 'no2 µg/m³', 'parame...","{'latitude': 52.24570400000001, 'longitude': 2...","[{'id': 35, 'name': 'Poland GIOS TOS', 'attrib...","[21.080427, 52.24570400000001, 21.080427, 52.2...",None,2025-08-25 08:00:00+00:00,2025-10-10 13:00:00+00:00

In [22]:
rows = []

for _, station in df_top_no2.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur NO2 behalten
        if sensor["parameter"]["id"] == 5:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_no2_sensors = pd.DataFrame(rows)

df_no2_sensors

     station_id                         station_name  sensor_id sensor_name
0          2511                                 Reja       4890   no2 µg/m³
1          2529                                  KPN       4993   no2 µg/m³
2            28                              Ursynów       5009   no2 µg/m³
3            43                          Konarskiego       4987   no2 µg/m³
4          1207                            Gimnazjum       2164   no2 µg/m³
..          ...                                  ...        ...         ...
233     3358648               Sulechów, ul. Licealna   11950465   no2 µg/m³
234     3359900  Gdańsk, ul. Powstańców Warszawskich   11959845   no2 µg/m³
235     3616712            Katowice, ul. Dudy-Gracza   12405264   no2 µg/m³
236     5554541           Warszawa, al. Solidarności   13952345   no2 µg/m³
237     5554542             Warszawa, ul. Grochowska   13952348   no2 µg/m³

[238 rows x 4 columns]

In [23]:
sensor_ids = df_no2_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

238

[4890,
 4993,
 5009,
 4987,
 2164,
 4970,
 5013,
 5130,
 5162,
 5225,
 5081,
 7383,
 7386,
 10761,
 11011,
 35509,
 35532,
 34866,
 36300,
 35593,
 35132,
 35250,
 35992,
 35935,
 20755,
 35726,
 34895,
 36266,
 35736,
 20875,
 35648,
 35672,
 35948,
 35090,
 20910,
 36220,
 35330,
 35154,
 36392,
 22584,
 36355,
 22895,
 23104,
 23930,
 24341,
 35557,
 35402,
 34848,
 35814,
 35967,
 35213,
 35958,
 36311,
 2776461,
 35321,
 35877,
 34884,
 35679,
 35980,
 36001,
 36228,
 36246,
 35989,
 34844,
 35176,
 34877,
 35544,
 36143,
 34964,
 35001,
 35019,
 36457,
 35062,
 36490,
 35079,
 36221,
 35093,
 35102,
 35114,
 35119,
 35598,
 35159,
 35428,
 35949,
 35238,
 35273,
 35278,
 35407,
 35306,
 35774,
 35395,
 35827,
 35573,
 35589,
 35617,
 35642,
 35677,
 35719,
 36491,
 35833,
 35839,
 35851,
 35906,
 36076,
 35915,
 35945,
 36160,
 36071,
 36263,
 36344,
 36459,
 17894,
 25519,
 20916,
 20908,
 35216,
 35888,
 35924,
 34798,
 35523,
 20917,
 36338,
 20882,
 35883,
 35954,
 20900,
 34863,
 35892,
 22645,
 22469,
 20870,
 21644,
 20942,
 20931,
 20890,
 20911,
 20699,
 17896,
 17727,
 17749,
 36153,
 36163,
 35399,
 35873,
 34987,
 20939,
 35986,
 35894,
 20810,
 20869,
 20918,
 20443,
 20859,
 20907,
 18092,
 36107,
 34898,
 20872,
 20575,
 20887,
 35521,
 35115,
 35031,
 22428,
 35611,
 21678,
 22455,
 34892,
 22585,
 21556,
 35069,
 35253,
 35463,
 35452,
 36132,
 36089,
 35421,
 36374,
 39295,
 225214,
 1182942,
 386029,
 386081,
 386088,
 425729,
 426782,
 1289734,
 1303276,
 1562262,
 1562364,
 1562390,
 1562394,
 1727809,
 1727811,
 2017509,
 2023407,
 5079413,
 5079425,
 5079429,
 5079432,
 5079495,
 5079501,
 5079511,
 5079528,
 5079534,
 5079550,
 5079569,
 5079523,
 5079629,
 5079644,
 5079702,
 5079710,
 5079713,
 5079753,
 5079771,
 2507679,
 2806832,
 2555356,
 2569037,
 2603465,
 2708078,
 5079562,
 7576282,
 7645000,
 7660691,
 11969951,
 7711091,
 7738351,
 8619575,
 11428780,
 11428788,
 11872351,
 11960205,
 11950465,
 11959845,
 12405264,
 13952345,
 13952348]

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 4890: Seite 1, 299 Ergebnisse
Sensor 4993: Seite 1, 313 Ergebnisse
Sensor 5009: Seite 1, 297 Ergebnisse
Sensor 4987: Seite 1, 294 Ergebnisse
Sensor 2164: Seite 1, 298 Ergebnisse
Sensor 4970: Seite 1, 296 Ergebnisse
Sensor 5013: Seite 1, 298 Ergebnisse
Sensor 5130: Seite 1, 298 Ergebnisse
Sensor 5162: Seite 1, 298 Ergebnisse
Sensor 5225: Seite 1, 298 Ergebnisse
Sensor 5081: Seite 1, 217 Ergebnisse
Sensor 7383: Seite 1, 61 Ergebnisse
Sensor 7386: Seite 1, 61 Ergebnisse
Sensor 10761: Seite 1, 1000 Ergebnisse
Sensor 10761: Seite 2, 1000 Ergebnisse
Sensor 10761: Seite 3, 1000 Ergebnisse
Sensor 10761: Seite 4, 56 Ergebnisse
Sensor 11011: Seite 1, 1000 Ergebnisse
Sensor 11011: Seite 2, 1000 Ergebnisse
Sensor 11011: Seite 3, 1000 Ergebnisse
Sensor 11011: Seite 4, 51 Ergebnisse
Sensor 35509: Seite 1, 1000 Ergebnisse
Sensor 35509: Seite 2, 1000 Ergebnisse
Sensor 35509: Seite 3, 113 Ergebnisse
Sensor 35532: Seite 1, 1000 Ergebnisse
Sensor 35532: Seite 2, 1000 Ergebnisse
Sensor 35532: Seite 3, 551 Ergebnisse
Sensor 34866: Seite 1, 1000 Ergebnisse
Sensor 34866: Seite 2, 1000 Ergebnisse
Sensor 34866: Seite 3, 551 Ergebnisse
Sensor 36300: Seite 1, 1000 Ergebnisse
Sensor 36300: Seite 2, 1000 Ergebnisse
Sensor 36300: Seite 3, 345 Ergebnisse
Sensor 35593: Seite 1, 1000 Ergebnisse
Sensor 35593: Seite 2, 1000 Ergebnisse
Sensor 35593: Seite 3, 524 Ergebnisse
Sensor 35132: Seite 1, 1000 Ergebnisse
Sensor 35132: Seite 2, 1000 Ergebnisse
Sensor 35132: Seite 3, 550 Ergebnisse
Sensor 35250: Seite 1, 1000 Ergebnisse
Sensor 35250: Seite 2, 1000 Ergebnisse
Sensor 35250: Seite 3, 551 Ergebnisse
Sensor 35992: Seite 1, 1000 Ergebnisse
Sensor 35992: Seite 2, 1000 Ergebnisse
Sensor 35992: Seite 3, 342 Ergebnisse
Sensor 35935: Seite 1, 1000 Ergebnisse
Sensor 35935: Seite 2, 417 Ergebnisse
Sensor 20755: Seite 1, 1000 Ergebnisse
Sensor 20755: Seite 2, 428 Ergebnisse
Sensor 35726: Seite 1, 1000 Ergebnisse
Sensor 35726: Seite 2, 1000 Ergebnisse
Sensor 35726: Seite 3, 550 Ergebnisse
Sensor 34895: Seite 1, 1000 Ergebnisse
Sensor 34895: Seite 2, 1000 Ergebnisse
Sensor 34895: Seite 3, 530 Ergebnisse
Sensor 36266: Seite 1, 1000 Ergebnisse
Sensor 36266: Seite 2, 1000 Ergebnisse
Sensor 36266: Seite 3, 544 Ergebnisse
Sensor 35736: Seite 1, 1000 Ergebnisse
Sensor 35736: Seite 2, 1000 Ergebnisse
Sensor 35736: Seite 3, 549 Ergebnisse
Sensor 20875: Seite 1, 1000 Ergebnisse
Sensor 20875: Seite 2, 479 Ergebnisse
Sensor 35648: Seite 1, 1000 Ergebnisse
Sensor 35648: Seite 2, 1000 Ergebnisse
Sensor 35648: Seite 3, 342 Ergebnisse
Sensor 35672: Seite 1, 1000 Ergebnisse
Sensor 35672: Seite 2, 1000 Ergebnisse
Sensor 35672: Seite 3, 538 Ergebnisse
Sensor 35948: Seite 1, 1000 Ergebnisse
Sensor 35948: Seite 2, 1000 Ergebnisse
Sensor 35948: Seite 3, 215 Ergebnisse
Sensor 35090: Seite 1, 1000 Ergebnisse
Sensor 35090: Seite 2, 1000 Ergebnisse
Sensor 35090: Seite 3, 518 Ergebnisse
Sensor 20910: Seite 1, 391 Ergebnisse
Sensor 36220: Seite 1, 1000 Ergebnisse
Sensor 36220: Seite 2, 1000 Ergebnisse
Sensor 36220: Seite 3, 507 Ergebnisse
Sensor 35330: Seite 1, 1000 Ergebnisse
Sensor 35330: Seite 2, 1000 Ergebnisse
Sensor 35330: Seite 3, 540 Ergebnisse
Sensor 35154: Seite 1, 1000 Ergebnisse
Sensor 35154: Seite 2, 1000 Ergebnisse
Sensor 35154: Seite 3, 533 Ergebnisse
Sensor 36392: Seite 1, 1000 Ergebnisse
Sensor 36392: Seite 2, 1000 Ergebnisse
Sensor 36392: Seite 3, 548 Ergebnisse
Sensor 22584: Seite 1, 1000 Ergebnisse
Sensor 22584: Seite 2, 1000 Ergebnisse
Sensor 22584: Seite 3, 552 Ergebnisse
Sensor 36355: Seite 1, 1000 Ergebnisse
Sensor 36355: Seite 2, 945 Ergebnisse
Sensor 22895: Seite 1, 1000 Ergebnisse
Sensor 22895: Seite 2, 1000 Ergebnisse
Sensor 22895: Seite 3, 417 Ergebnisse
Sensor 23104: Seite 1, 1000 Ergebnisse
Sensor 23104: Seite 2, 1000 Ergebnisse
Sensor 23104: Seite 3, 505 Ergebnisse
Sensor 23930: Seite 1, 1000 Ergebnisse
Sensor 23930: Seite 2, 1000 Ergebnisse
Sensor 23930: Seite 3, 513 Ergebnisse
Sensor 24341: Seite 1, 1000 Ergebnisse
Sensor 24341: Seite 2, 1000 Ergebnisse
Sensor 24341: Seite 3, 251 Ergebnisse
Sensor 35557: Seite 1, 1000 Ergebnisse
Sensor 35557: Seite 2, 1000 Ergebnisse
Sensor 35557: Seite 3, 530 Ergebnisse
Sensor 35402: Seite 1, 1000 Ergebnisse
Sensor 35402: Seite 2, 1000 Ergebnisse
Sensor 35402: Seite 3, 488 Ergebnisse
Sensor 34848: Seite 1, 1000 Ergebnisse
Sensor 34848: Seite 2, 460 Ergebnisse
Sensor 35814: Seite 1, 1000 Ergebnisse
Sensor 35814: Seite 2, 1000 Ergebnisse
Sensor 35814: Seite 3, 534 Ergebnisse
Sensor 35967: Seite 1, 1000 Ergebnisse
Sensor 35967: Seite 2, 1000 Ergebnisse
Sensor 35967: Seite 3, 556 Ergebnisse
Sensor 35213: Seite 1, 1000 Ergebnisse
Sensor 35213: Seite 2, 1000 Ergebnisse
Sensor 35213: Seite 3, 417 Ergebnisse
Sensor 35958: Seite 1, 1000 Ergebnisse
Sensor 35958: Seite 2, 1000 Ergebnisse
Sensor 35958: Seite 3, 524 Ergebnisse
Sensor 36311: Seite 1, 1000 Ergebnisse
Sensor 36311: Seite 2, 1000 Ergebnisse
Sensor 36311: Seite 3, 548 Ergebnisse
Sensor 2776461: Seite 1, 1000 Ergebnisse
Sensor 2776461: Seite 2, 72 Ergebnisse
Sensor 35321: Seite 1, 1000 Ergebnisse
Sensor 35321: Seite 2, 1000 Ergebnisse
Sensor 35321: Seite 3, 472 Ergebnisse
Sensor 35877: Seite 1, 1000 Ergebnisse
Sensor 35877: Seite 2, 1000 Ergebnisse
Sensor 35877: Seite 3, 550 Ergebnisse
Sensor 34884: Seite 1, 1000 Ergebnisse
Sensor 34884: Seite 2, 1000 Ergebnisse
Sensor 34884: Seite 3, 542 Ergebnisse
Sensor 35679: Seite 1, 1000 Ergebnisse
Sensor 35679: Seite 2, 1000 Ergebnisse
Sensor 35679: Seite 3, 542 Ergebnisse
Sensor 35980: Seite 1, 1000 Ergebnisse
Sensor 35980: Seite 2, 1000 Ergebnisse
Sensor 35980: Seite 3, 516 Ergebnisse
Sensor 36001: Seite 1, 1000 Ergebnisse
Sensor 36001: Seite 2, 760 Ergebnisse
Sensor 36228: Seite 1, 1000 Ergebnisse
Sensor 36228: Seite 2, 1000 Ergebnisse
Sensor 36228: Seite 3, 544 Ergebnisse
Sensor 36246: Seite 1, 1000 Ergebnisse
Sensor 36246: Seite 2, 1000 Ergebnisse
Sensor 36246: Seite 3, 499 Ergebnisse
Sensor 35989: Seite 1, 1000 Ergebnisse
Sensor 35989: Seite 2, 1000 Ergebnisse
Sensor 35989: Seite 3, 522 Ergebnisse
Sensor 34844: Seite 1, 1000 Ergebnisse
Sensor 34844: Seite 2, 1000 Ergebnisse
Sensor 34844: Seite 3, 441 Ergebnisse
Sensor 35176: Seite 1, 1000 Ergebnisse
Sensor 35176: Seite 2, 1000 Ergebnisse
Sensor 35176: Seite 3, 547 Ergebnisse
Sensor 34877: Seite 1, 1000 Ergebnisse
Sensor 34877: Seite 2, 1000 Ergebnisse
Sensor 34877: Seite 3, 512 Ergebnisse
Sensor 35544: Seite 1, 1000 Ergebnisse
Sensor 35544: Seite 2, 1000 Ergebnisse
Sensor 35544: Seite 3, 543 Ergebnisse
Sensor 36143: Seite 1, 1000 Ergebnisse
Sensor 36143: Seite 2, 1000 Ergebnisse
Sensor 36143: Seite 3, 511 Ergebnisse
Sensor 34964: Seite 1, 1000 Ergebnisse
Sensor 34964: Seite 2, 1000 Ergebnisse
Sensor 34964: Seite 3, 536 Ergebnisse
Sensor 35001: Seite 1, 1000 Ergebnisse
Sensor 35001: Seite 2, 1000 Ergebnisse
Sensor 35001: Seite 3, 434 Ergebnisse
Sensor 35019: Seite 1, 1000 Ergebnisse
Sensor 35019: Seite 2, 1000 Ergebnisse
Sensor 35019: Seite 3, 519 Ergebnisse
Sensor 36457: Seite 1, 1000 Ergebnisse
Sensor 36457: Seite 2, 1000 Ergebnisse
Sensor 36457: Seite 3, 488 Ergebnisse
Sensor 35062: Seite 1, 1000 Ergebnisse
Sensor 35062: Seite 2, 1000 Ergebnisse
Sensor 35062: Seite 3, 131 Ergebnisse
Sensor 36490: Seite 1, 1000 Ergebnisse
Sensor 36490: Seite 2, 1000 Ergebnisse
Sensor 36490: Seite 3, 550 Ergebnisse
Sensor 35079: Seite 1, 1000 Ergebnisse
Sensor 35079: Seite 2, 1000 Ergebnisse
Sensor 35079: Seite 3, 504 Ergebnisse
Sensor 36221: Seite 1, 1000 Ergebnisse
Sensor 36221: Seite 2, 1000 Ergebnisse
Sensor 36221: Seite 3, 537 Ergebnisse
Sensor 35093: Seite 1, 1000 Ergebnisse
Sensor 35093: Seite 2, 1000 Ergebnisse
Sensor 35093: Seite 3, 532 Ergebnisse
Sensor 35102: Seite 1, 1000 Ergebnisse
Sensor 35102: Seite 2, 1000 Ergebnisse
Sensor 35102: Seite 3, 543 Ergebnisse
Sensor 35114: Seite 1, 1000 Ergebnisse
Sensor 35114: Seite 2, 1000 Ergebnisse
Sensor 35114: Seite 3, 551 Ergebnisse
Sensor 35119: Seite 1, 1000 Ergebnisse
Sensor 35119: Seite 2, 1000 Ergebnisse
Sensor 35119: Seite 3, 85 Ergebnisse
Sensor 35598: Seite 1, 1000 Ergebnisse
Sensor 35598: Seite 2, 1000 Ergebnisse
Sensor 35598: Seite 3, 481 Ergebnisse
Sensor 35159: Seite 1, 1000 Ergebnisse
Sensor 35159: Seite 2, 1000 Ergebnisse
Sensor 35159: Seite 3, 427 Ergebnisse
Sensor 35428: Seite 1, 1000 Ergebnisse
Sensor 35428: Seite 2, 1000 Ergebnisse
Sensor 35428: Seite 3, 547 Ergebnisse
Sensor 35949: Seite 1, 1000 Ergebnisse
Sensor 35949: Seite 2, 1000 Ergebnisse
Sensor 35949: Seite 3, 556 Ergebnisse
Sensor 35238: Seite 1, 1000 Ergebnisse
Sensor 35238: Seite 2, 1000 Ergebnisse
Sensor 35238: Seite 3, 538 Ergebnisse
Sensor 35273: Seite 1, 1000 Ergebnisse
Sensor 35273: Seite 2, 1000 Ergebnisse
Sensor 35273: Seite 3, 449 Ergebnisse
Sensor 35278: Seite 1, 1000 Ergebnisse
Sensor 35278: Seite 2, 1000 Ergebnisse
Sensor 35278: Seite 3, 503 Ergebnisse
Sensor 35407: Seite 1, 1000 Ergebnisse
Sensor 35407: Seite 2, 1000 Ergebnisse
Sensor 35407: Seite 3, 548 Ergebnisse
Sensor 35306: Seite 1, 1000 Ergebnisse
Sensor 35306: Seite 2, 1000 Ergebnisse
Sensor 35306: Seite 3, 556 Ergebnisse
Sensor 35774: Seite 1, 1000 Ergebnisse
Sensor 35774: Seite 2, 1000 Ergebnisse
Sensor 35774: Seite 3, 543 Ergebnisse
Sensor 35395: Seite 1, 1000 Ergebnisse
Sensor 35395: Seite 2, 624 Ergebnisse
Sensor 35827: Seite 1, 1000 Ergebnisse
Sensor 35827: Seite 2, 1000 Ergebnisse
Sensor 35827: Seite 3, 359 Ergebnisse
Sensor 35573: Seite 1, 1000 Ergebnisse
Sensor 35573: Seite 2, 1000 Ergebnisse
Sensor 35573: Seite 3, 500 Ergebnisse
Sensor 35589: Seite 1, 1000 Ergebnisse
Sensor 35589: Seite 2, 1000 Ergebnisse
Sensor 35589: Seite 3, 544 Ergebnisse
Sensor 35617: Seite 1, 1000 Ergebnisse
Sensor 35617: Seite 2, 1000 Ergebnisse
Sensor 35617: Seite 3, 542 Ergebnisse
Sensor 35642: Seite 1, 1000 Ergebnisse
Sensor 35642: Seite 2, 1000 Ergebnisse
Sensor 35642: Seite 3, 369 Ergebnisse
Sensor 35677: Seite 1, 1000 Ergebnisse
Sensor 35677: Seite 2, 471 Ergebnisse
Sensor 35719: Seite 1, 1000 Ergebnisse
Sensor 35719: Seite 2, 1000 Ergebnisse
Sensor 35719: Seite 3, 82 Ergebnisse
Sensor 36491: Seite 1, 1000 Ergebnisse
Sensor 36491: Seite 2, 1000 Ergebnisse
Sensor 36491: Seite 3, 549 Ergebnisse
Sensor 35833: Seite 1, 1000 Ergebnisse
Sensor 35833: Seite 2, 1000 Ergebnisse
Sensor 35833: Seite 3, 499 Ergebnisse
Sensor 35839: Seite 1, 1000 Ergebnisse
Sensor 35839: Seite 2, 1000 Ergebnisse
Sensor 35839: Seite 3, 552 Ergebnisse
Sensor 35851: Seite 1, 1000 Ergebnisse
Sensor 35851: Seite 2, 1000 Ergebnisse
Sensor 35851: Seite 3, 542 Ergebnisse
Sensor 35906: Seite 1, 1000 Ergebnisse
Sensor 35906: Seite 2, 1000 Ergebnisse
Sensor 35906: Seite 3, 449 Ergebnisse
Sensor 36076: Seite 1, 1000 Ergebnisse
Sensor 36076: Seite 2, 946 Ergebnisse
Sensor 35915: Seite 1, 1000 Ergebnisse
Sensor 35915: Seite 2, 1000 Ergebnisse
Sensor 35915: Seite 3, 464 Ergebnisse
Sensor 35945: Seite 1, 1000 Ergebnisse
Sensor 35945: Seite 2, 537 Ergebnisse
Sensor 36160: Seite 1, 1000 Ergebnisse
Sensor 36160: Seite 2, 1000 Ergebnisse
Sensor 36160: Seite 3, 534 Ergebnisse
Sensor 36071: Seite 1, 1000 Ergebnisse
Sensor 36071: Seite 2, 1000 Ergebnisse
Sensor 36071: Seite 3, 485 Ergebnisse
Sensor 36263: Seite 1, 1000 Ergebnisse
Sensor 36263: Seite 2, 1000 Ergebnisse
Sensor 36263: Seite 3, 497 Ergebnisse
Sensor 36344: Seite 1, 1000 Ergebnisse
Sensor 36344: Seite 2, 1000 Ergebnisse
Sensor 36344: Seite 3, 467 Ergebnisse
Sensor 36459: Seite 1, 1000 Ergebnisse
Sensor 36459: Seite 2, 1000 Ergebnisse
Sensor 36459: Seite 3, 549 Ergebnisse
Sensor 17894: Seite 1, 25 Ergebnisse
Sensor 25519: Seite 1, 1000 Ergebnisse
Sensor 25519: Seite 2, 219 Ergebnisse
Sensor 20916: Seite 1, 322 Ergebnisse
Sensor 20908: Seite 1, 405 Ergebnisse
Sensor 35216: Seite 1, 1000 Ergebnisse
Sensor 35216: Seite 2, 1000 Ergebnisse
Sensor 35216: Seite 3, 148 Ergebnisse
Sensor 35888: Seite 1, 1000 Ergebnisse
Sensor 35888: Seite 2, 1000 Ergebnisse
Sensor 35888: Seite 3, 77 Ergebnisse
Sensor 35924: Seite 1, 1000 Ergebnisse
Sensor 35924: Seite 2, 1000 Ergebnisse
Sensor 35924: Seite 3, 54 Ergebnisse
Sensor 34798: Seite 1, 1000 Ergebnisse
Sensor 34798: Seite 2, 783 Ergebnisse
Sensor 35523: Seite 1, 1000 Ergebnisse
Sensor 35523: Seite 2, 774 Ergebnisse
Sensor 20917: Seite 1, 405 Ergebnisse
Sensor 36338: Seite 1, 1000 Ergebnisse
Sensor 36338: Seite 2, 699 Ergebnisse
Sensor 20882: Seite 1, 401 Ergebnisse
Sensor 35883: Seite 1, 1000 Ergebnisse
Sensor 35883: Seite 2, 418 Ergebnisse
Sensor 35954: Seite 1, 1000 Ergebnisse
Sensor 35954: Seite 2, 443 Ergebnisse
Sensor 20900: Seite 1, 401 Ergebnisse
Sensor 34863: Seite 1, 1000 Ergebnisse
Sensor 34863: Seite 2, 85 Ergebnisse
Sensor 35892: Seite 1, 761 Ergebnisse
Sensor 22645: Seite 1, 624 Ergebnisse
Sensor 22469: Seite 1, 568 Ergebnisse
Sensor 20870: Seite 1, 389 Ergebnisse
Sensor 21644: Seite 1, 440 Ergebnisse
Sensor 20942: Seite 1, 383 Ergebnisse
Sensor 20931: Seite 1, 403 Ergebnisse
Sensor 20890: Seite 1, 384 Ergebnisse
Sensor 20911: Seite 1, 377 Ergebnisse
Sensor 20699: Seite 1, 367 Ergebnisse
Sensor 17896: Seite 1, 38 Ergebnisse
Sensor 17727: Seite 1, 16 Ergebnisse
Sensor 17749: Seite 1, 21 Ergebnisse
Sensor 36153: Seite 1, 1000 Ergebnisse
Sensor 36153: Seite 2, 1000 Ergebnisse
Sensor 36153: Seite 3, 548 Ergebnisse
Sensor 36163: Seite 1, 1000 Ergebnisse
Sensor 36163: Seite 2, 1000 Ergebnisse
Sensor 36163: Seite 3, 530 Ergebnisse
Sensor 35399: Seite 1, 1000 Ergebnisse
Sensor 35399: Seite 2, 1000 Ergebnisse
Sensor 35399: Seite 3, 478 Ergebnisse
Sensor 35873: Seite 1, 1000 Ergebnisse
Sensor 35873: Seite 2, 182 Ergebnisse
Sensor 34987: Seite 1, 1000 Ergebnisse
Sensor 34987: Seite 2, 1000 Ergebnisse
Sensor 34987: Seite 3, 481 Ergebnisse
Sensor 20939: Seite 1, 361 Ergebnisse
Sensor 35986: Seite 1, 1000 Ergebnisse
Sensor 35986: Seite 2, 1000 Ergebnisse
Sensor 35986: Seite 3, 486 Ergebnisse
Sensor 35894: Seite 1, 863 Ergebnisse
Sensor 20810: Seite 1, 361 Ergebnisse
Sensor 20869: Seite 1, 337 Ergebnisse
Sensor 20918: Seite 1, 360 Ergebnisse
Sensor 20443: Seite 1, 270 Ergebnisse
Sensor 20859: Seite 1, 346 Ergebnisse
Sensor 20907: Seite 1, 314 Ergebnisse
Sensor 18092: Seite 1, 1 Ergebnisse
Sensor 36107: Seite 1, 722 Ergebnisse
Sensor 34898: Seite 1, 1000 Ergebnisse
Sensor 34898: Seite 2, 1000 Ergebnisse
Sensor 34898: Seite 3, 452 Ergebnisse
Sensor 20872: Seite 1, 171 Ergebnisse
Sensor 20575: Seite 1, 260 Ergebnisse
Sensor 20887: Seite 1, 280 Ergebnisse
Sensor 35521: Seite 1, 1000 Ergebnisse
Sensor 35521: Seite 2, 1000 Ergebnisse
Sensor 35521: Seite 3, 380 Ergebnisse
Sensor 35115: Seite 1, 1000 Ergebnisse
Sensor 35115: Seite 2, 261 Ergebnisse
Sensor 35031: Seite 1, 1000 Ergebnisse
Sensor 35031: Seite 2, 457 Ergebnisse
Sensor 22428: Seite 1, 1000 Ergebnisse
Sensor 22428: Seite 2, 1000 Ergebnisse
Sensor 22428: Seite 3, 170 Ergebnisse
Sensor 35611: Seite 1, 700 Ergebnisse
Sensor 21678: Seite 1, 25 Ergebnisse
Sensor 22455: Seite 1, 1000 Ergebnisse
Sensor 22455: Seite 2, 1000 Ergebnisse
Sensor 22455: Seite 3, 116 Ergebnisse
Sensor 34892: Seite 1, 346 Ergebnisse
Sensor 22585: Seite 1, 339 Ergebnisse
Sensor 21556: Seite 1, 7 Ergebnisse
Sensor 35069: Seite 1, 330 Ergebnisse
Sensor 35253: Seite 1, 332 Ergebnisse
Sensor 35463: Seite 1, 327 Ergebnisse
Sensor 35452: Seite 1, 1000 Ergebnisse
Sensor 35452: Seite 2, 1000 Ergebnisse
Sensor 35452: Seite 3, 107 Ergebnisse
Sensor 36132: Seite 1, 1000 Ergebnisse
Sensor 36132: Seite 2, 632 Ergebnisse
Sensor 36089: Seite 1, 899 Ergebnisse
Sensor 35421: Seite 1, 1000 Ergebnisse
Sensor 35421: Seite 2, 1000 Ergebnisse
Sensor 35421: Seite 3, 16 Ergebnisse
Sensor 39295: Seite 1, 762 Ergebnisse
Sensor 225214: Seite 1, 1000 Ergebnisse
Sensor 225214: Seite 2, 802 Ergebnisse
Sensor 1182942: Seite 1, 1000 Ergebnisse
Sensor 1182942: Seite 2, 691 Ergebnisse
Sensor 386029: Seite 1, 340 Ergebnisse
Sensor 386081: Seite 1, 694 Ergebnisse
Sensor 386088: Seite 1, 1000 Ergebnisse
Sensor 386088: Seite 2, 764 Ergebnisse
Sensor 425729: Seite 1, 322 Ergebnisse
Sensor 426782: Seite 1, 325 Ergebnisse
Sensor 1289734: Seite 1, 672 Ergebnisse
Sensor 1303276: Seite 1, 1000 Ergebnisse
Sensor 1303276: Seite 2, 656 Ergebnisse
Sensor 1562262: Seite 1, 364 Ergebnisse
Sensor 1562364: Seite 1, 359 Ergebnisse
Sensor 1562390: Seite 1, 356 Ergebnisse
Sensor 1562394: Seite 1, 613 Ergebnisse
Sensor 1727809: Seite 1, 1000 Ergebnisse
Sensor 1727809: Seite 2, 362 Ergebnisse
Sensor 1727811: Seite 1, 1000 Ergebnisse
Sensor 1727811: Seite 2, 363 Ergebnisse
Sensor 2017509: Seite 1, 1000 Ergebnisse
Sensor 2017509: Seite 2, 238 Ergebnisse
Sensor 2023407: Seite 1, 1000 Ergebnisse
Sensor 2023407: Seite 2, 211 Ergebnisse
Sensor 2507679: Seite 1, 288 Ergebnisse
Sensor 2806832: Seite 1, 202 Ergebnisse
Sensor 2555356: Seite 1, 292 Ergebnisse
Sensor 2569037: Seite 1, 999 Ergebnisse
Sensor 2603465: Seite 1, 618 Ergebnisse
Sensor 2708078: Seite 1, 287 Ergebnisse
317780

[{'date': '2016-01-30', 'value': 11.554545454545455},
 {'date': '2016-01-31', 'value': 4.726086956521739},
 {'date': '2016-02-01', 'value': 12.595652173913043},
 {'date': '2016-02-02', 'value': 8.326086956521738},
 {'date': '2016-02-03', 'value': 7.595652173913045},
 {'date': '2016-02-04', 'value': 9.739130434782606},
 {'date': '2016-02-05', 'value': 11.491304347826086},
 {'date': '2016-02-06', 'value': 19.169565217391305},
 {'date': '2016-02-07', 'value': 14.291304347826086},
 {'date': '2016-02-08', 'value': 14.195652173913041},
 {'date': '2016-02-09', 'value': 7.618181818181818},
 {'date': '2016-02-10', 'value': 15.963636363636363},
 {'date': '2016-02-11', 'value': 14.108695652173912},
 {'date': '2016-02-12', 'value': 19.54782608695652},
 {'date': '2016-02-13', 'value': 16.043478260869566},
 {'date': '2016-02-14', 'value': 16.969565217391303},
 {'date': '2016-02-15', 'value': 27.859090909090913},
 {'date': '2016-02-16', 'value': 15.009090909090911},
 {'date': '2016-02-17', 'value': 13.29565217391304},
 {'date': '2016-02-18', 'value': 19.882608695652173},
 {'date': '2016-02-19', 'value': 14.352173913043481},
 {'date': '2016-02-20', 'value': 14.613043478260865},
 {'date': '2016-02-21', 'value': 9.160869565217391},
 {'date': '2016-02-22', 'value': 8.556521739130435},
 {'date': '2016-02-23', 'value': 12.247826086956524},
 {'date': '2016-02-24', 'value': 10.769565217391303},
 {'date': '2016-02-25', 'value': 17.247826086956525},
 {'date': '2016-02-26', 'value': 20.173913043478255},
 {'date': '2016-02-27', 'value': 20.460869565217394},
 {'date': '2016-02-28', 'value': 11.9},
 {'date': '2016-02-29', 'value': 14.668181818181818},
 {'date': '2016-03-01', 'value': 17.40434782608696},
 {'date': '2016-03-02', 'value': 19.754545454545454},
 {'date': '2016-03-03', 'value': 28.78260869565217},
 {'date': '2016-03-04', 'value': 17.356521739130436},
 {'date': '2016-03-05', 'value': 15.747826086956518},
 {'date': '2016-03-06', 'value': 13.847826086956522},
 {'date': '2016-03-07', 'value': 31.113636363636363},
 {'date': '2016-03-08', 'value': 28.877272727272725},
 {'date': '2016-03-09', 'value': 18.326086956521742},
 {'date': '2016-03-10', 'value': 12.834782608695651},
 {'date': '2016-03-11', 'value': 10.504545454545454},
 {'date': '2016-03-12', 'value': 8.839130434782609},
 {'date': '2016-03-13', 'value': 10.008695652173913},
 {'date': '2016-03-14', 'value': 20.51739130434782},
 {'date': '2016-03-15', 'value': 14.295652173913044},
 {'date': '2016-03-16', 'value': 20.369565217391305},
 {'date': '2016-03-17', 'value': 15.27826086956522},
 {'date': '2016-03-18', 'value': 12.056521739130435},
 {'date': '2016-03-19', 'value': 9.76086956521739},
 {'date': '2016-03-20', 'value': 8.082608695652173},
 {'date': '2016-03-21', 'value': 10.97391304347826},
 {'date': '2016-03-22', 'value': 15.213043478260868},
 {'date': '2016-03-23', 'value': 21.48695652173913},
 {'date': '2016-03-24', 'value': 24.504347826086956},
 {'date': '2016-03-25', 'value': 25.26521739130435},
 {'date': '2016-03-26', 'value': 14.265217391304349},
 {'date': '2016-03-27', 'value': 10.366666666666665},
 {'date': '2016-03-28', 'value': 10.13},
 {'date': '2016-03-29', 'value': 12.5},
 {'date': '2016-03-30', 'value': 17.3952380952381},
 {'date': '2016-03-31', 'value': 14.778260869565221},
 {'date': '2016-04-01', 'value': 13.760869565217389},
 {'date': '2016-04-02', 'value': 15.130434782608694},
 {'date': '2016-04-03', 'value': 11.10909090909091},
 {'date': '2016-04-04', 'value': 24.882608695652166},
 {'date': '2016-04-05', 'value': 29.356521739130432},
 {'date': '2016-04-06', 'value': 19.34347826086957},
 {'date': '2016-04-07', 'value': 21.730434782608697},
 {'date': '2016-04-08', 'value': 24.752173913043475},
 {'date': '2016-04-09', 'value': 12.673913043478263},
 {'date': '2016-04-10', 'value': 7.872727272727274},
 {'date': '2016-04-11', 'value': 14.47391304347826},
 {'date': '2016-04-12', 'value': 25.54347826086956},
 {'date': '2016-04-13', 'value': 19.50869565217391},
 {'date': '2016-04-14', 'value': 14.334782608695651},
 {'date': '2016-04-15', 'value': 19.934782608695652},
 {'date': '2016-04-16', 'value': 13.68695652173913},
 {'date': '2016-04-17', 'value': 11.860869565217392},
 {'date': '2016-04-18', 'value': 10.530434782608696},
 {'date': '2016-04-19', 'value': 12.743478260869564},
 {'date': '2016-04-20', 'value': 11.143478260869566},
 {'date': '2016-04-21', 'value': 10.617391304347825},
 {'date': '2016-04-22', 'value': 14.030434782608696},
 {'date': '2016-04-23', 'value': 15.07826086956522},
 {'date': '2016-04-24', 'value': 6.230434782608696},
 {'date': '2016-04-25', 'value': 15.056521739130435},
 {'date': '2016-04-26', 'value': 20.213043478260875},
 {'date': '2016-04-27', 'value': 13.647826086956524},
 {'date': '2016-04-28', 'value': 7.85},
 {'date': '2016-04-29', 'value': 22.3},
 {'date': '2016-04-30', 'value': 13.952173913043483},
 {'date': '2016-05-01', 'value': 11.286956521739128},
 {'date': '2016-05-02', 'value': 15.465217391304344},
 {'date': '2016-05-03', 'value': 10.447826086956523},
 {'date': '2016-05-04', 'value': 14.604347826086956},
 {'date': '2016-05-05', 'value': 15.926086956521734},
 {'date': '2016-05-06', 'value': 18.68260869565217},
 {'date': '2016-05-07', 'value': 13.217391304347824},
 {'date': '2016-05-08', 'value': 12.3},
 {'date': '2016-05-09', 'value': 21.000000000000004},
 {'date': '2016-05-10', 'value': 27.65909090909091},
 {'date': '2016-05-11', 'value': 27.49130434782609},
 {'date': '2016-05-12', 'value': 19.452173913043477},
 {'date': '2016-05-13', 'value': 14.313636363636363},
 {'date': '2016-05-14', 'value': 13.01304347826087},
 {'date': '2016-05-15', 'value': 5.539130434782607},
 {'date': '2016-05-16', 'value': 8.98695652173913},
 {'date': '2016-05-17', 'value': 13.269565217391309},
 {'date': '2016-05-18', 'value': 18.34090909090909},
 {'date': '2016-05-19', 'value': 24.654545454545453},
 {'date': '2016-05-20', 'value': 33.06956521739131},
 {'date': '2016-05-21', 'value': 12.573913043478262},
 {'date': '2016-05-22', 'value': 11.86521739130435},
 {'date': '2016-05-23', 'value': 14.8},
 {'date': '2016-05-24', 'value': 17.721739130434784},
 {'date': '2016-05-25', 'value': 23.918181818181814},
 {'date': '2016-05-26', 'value': 9.469565217391303},
 {'date': '2016-05-27', 'value': 12.456521739130432},
 {'date': '2016-05-28', 'value': 20.950000000000003},
 {'date': '2016-05-29', 'value': 10.738095238095237},
 {'date': '2016-05-30', 'value': 13.129411764705884},
 {'date': '2016-05-31', 'value': 16.13181818181818},
 {'date': '2016-06-01', 'value': 15.200000000000003},
 {'date': '2016-06-02', 'value': 13.178260869565216},
 {'date': '2016-06-03', 'value': 24.208695652173915},
 {'date': '2016-06-04', 'value': 26.986956521739128},
 {'date': '2016-06-05', 'value': 9.065217391304348},
 {'date': '2016-06-06', 'value': 10.752173913043478},
 {'date': '2016-06-07', 'value': 17.6},
 {'date': '2016-06-08', 'value': 19.05652173913043},
 {'date': '2016-06-09', 'value': 11.917391304347827},
 {'date': '2016-06-10', 'value': 12.069565217391306},
 {'date': '2016-06-11', 'value': 8.634782608695653},
 {'date': '2016-06-12', 'value': 6.97391304347826},
 {'date': '2016-06-13', 'value': 12.756521739130436},
 {'date': '2016-06-14', 'value': 14.88695652173913},
 {'date': '2016-06-15', 'value': 15.908695652173913},
 {'date': '2016-06-16', 'value': 10.004347826086958},
 {'date': '2016-06-17', 'value': 9.865217391304348},
 {'date': '2016-06-18', 'value': 10.773913043478263},
 {'date': '2016-06-19', 'value': 16.43913043478261},
 {'date': '2016-06-20', 'value': 15.66956521739131},
 {'date': '2016-06-21', 'value': 12.22173913043478},
 {'date': '2016-06-22', 'value': 19.53478260869565},
 {'date': '2016-06-23', 'value': 22.76086956521739},
 {'date': '2016-06-24', 'value': 17.843478260869567},
 {'date': '2016-06-25', 'value': 12.030434782608697},
 {'date': '2016-06-26', 'value': 6.99},
 {'date': '2016-06-27', 'value': 8.05},
 {'date': '2016-06-28', 'value': 14.3952380952381},
 {'date': '2016-06-29', 'value': 18.11304347826087},
 {'date': '2016-06-30', 'value': 17.27826086956522},
 {'date': '2016-07-01', 'value': 13.769565217391303},
 {'date': '2016-07-02', 'value': 10.395652173913044},
 {'date': '2016-07-03', 'value': 6.039130434782609},
 {'date': '2016-07-04', 'value': 9.45217391304348},
 {'date': '2016-07-05', 'value': 14.295652173913046},
 {'date': '2016-07-06', 'value': 6.656521739130433},
 {'date': '2016-07-07', 'value': 6.721739130434782},
 {'date': '2016-07-08', 'value': 12.856521739130438},
 {'date': '2016-07-09', 'value': 6.1000000000000005},
 {'date': '2016-07-10', 'value': 7.07391304347826},
 {'date': '2016-07-11', 'value': 14.973913043478262},
 {'date': '2016-07-12', 'value': 17.84782608695652},
 {'date': '2016-07-13', 'value': 17.704347826086956},
 {'date': '2016-07-14', 'value': 11.469565217391304},
 {'date': '2016-07-15', 'value': 5.28695652173913},
 {'date': '2016-07-16', 'value': 8.58695652173913},
 {'date': '2016-07-17', 'value': 11.482608695652173},
 {'date': '2016-07-18', 'value': 6.782608695652174},
 {'date': '2016-07-19', 'value': 9.117391304347827},
 {'date': '2016-07-20', 'value': 10.834782608695651},
 {'date': '2016-07-21', 'value': 14.630434782608695},
 {'date': '2016-07-22', 'value': 17.417391304347827},
 {'date': '2016-07-23', 'value': 7.943478260869565},
 {'date': '2016-07-24', 'value': 7.64782608695652},
 {'date': '2016-07-25', 'value': 17.05652173913043},
 {'date': '2016-07-26', 'value': 21.365217391304352},
 {'date': '2016-07-27', 'value': 10.8},
 {'date': '2016-07-28', 'value': 13.461904761904764},
 {'date': '2016-07-29', 'value': 22.73478260869565},
 {'date': '2016-07-30', 'value': 15.017391304347827},
 {'date': '2016-07-31', 'value': 16.090909090909097},
 {'date': '2016-08-01', 'value': 8.909090909090908},
 {'date': '2016-08-02', 'value': 6.763636363636365},
 {'date': '2016-08-03', 'value': 11.399999999999999},
 {'date': '2016-08-04', 'value': 8.363636363636363},
 {'date': '2016-08-05', 'value': 12.313636363636363},
 {'date': '2016-08-06', 'value': 21.61363636363636},
 {'date': '2016-08-07', 'value': 8.763636363636364},
 {'date': '2016-08-08', 'value': 2.559090909090909},
 {'date': '2016-08-09', 'value': 6.472727272727273},
 {'date': '2016-08-10', 'value': 10.690909090909091},
 {'date': '2016-08-11', 'value': 6.818181818181818},
 {'date': '2016-08-12', 'value': 12.622727272727275},
 {'date': '2016-08-13', 'value': 10.577272727272728},
 {'date': '2016-08-14', 'value': 5.154545454545455},
 {'date': '2016-08-15', 'value': 4.831818181818182},
 {'date': '2016-08-16', 'value': 9.31304347826087},
 {'date': '2016-08-17', 'value': 9.382608695652172},
 {'date': '2016-08-18', 'value': 13.18695652173913},
 {'date': '2016-08-19', 'value': 14.43913043478261},
 {'date': '2016-08-20', 'value': 9.730434782608695},
 {'date': '2016-08-21', 'value': 6.4217391304347835},
 {'date': '2016-08-22', 'value': 8.121739130434781},
 {'date': '2016-08-23', 'value': 8.669565217391302},
 {'date': '2016-08-24', 'value': 9.43913043478261},
 {'date': '2016-08-25', 'value': 10.391304347826086},
 {'date': '2016-08-26', 'value': 8.0},
 {'date': '2016-08-27', 'value': 11.842857142857142},
 {'date': '2016-08-28', 'value': 10.173913043478262},
 {'date': '2016-08-29', 'value': 6.995652173913044},
 {'date': '2016-08-30', 'value': 4.086956521739131},
 {'date': '2016-08-31', 'value': 10.269565217391303},
 {'date': '2016-09-01', 'value': 9.247826086956522},
 {'date': '2016-09-02', 'value': 14.082608695652173},
 {'date': '2016-09-03', 'value': 12.691304347826087},
 {'date': '2016-09-04', 'value': 5.4565217391304355},
 {'date': '2016-09-05', 'value': 5.852173913043478},
 {'date': '2016-09-06', 'value': 5.756521739130435},
 {'date': '2016-09-07', 'value': 15.339130434782607},
 {'date': '2016-09-08', 'value': 16.456521739130434},
 {'date': '2016-09-09', 'value': 15.043478260869565},
 {'date': '2016-09-10', 'value': 12.039130434782608},
 {'date': '2016-09-11', 'value': 12.57391304347826},
 {'date': '2016-09-12', 'value': 13.708695652173912},
 {'date': '2016-09-13', 'value': 12.547826086956523},
 {'date': '2016-09-14', 'value': 9.134782608695652},
 {'date': '2016-09-15', 'value': 12.047826086956523},
 {'date': '2016-09-16', 'value': 17.895652173913046},
 {'date': '2016-09-17', 'value': 5.478260869565218},
 {'date': '2016-09-18', 'value': 2.508695652173913},
 {'date': '2016-09-19', 'value': 8.221739130434784},
 {'date': '2016-09-20', 'value': 13.06086956521739},
 {'date': '2016-09-21', 'value': 7.878260869565218},
 {'date': '2016-09-22', 'value': 12.777777777777779},
 {'date': '2016-11-04', 'value': 15.529999999999998},
 {'date': '2016-11-09', 'value': 31.66666666666666},
 {'date': '2016-11-10', 'value': 27.336363636363647},
 {'date': '2016-11-11', 'value': 11.763636363636364},
 {'date': '2016-11-12', 'value': 21.600000000000005},
 {'date': '2016-11-13', 'value': 19.80454545454546},
 {'date': '2016-11-14', 'value': 29.195454545454538},
 {'date': '2016-11-15', 'value': 21.85454545454546},
 {'date': '2016-11-16', 'value': 26.06086956521739},
 {'date': '2016-11-17', 'value': 23.165217391304346},
 {'date': '2016-11-18', 'value': 23.165217391304346},
 {'date': '2016-11-19', 'value': 27.38636363636364},
 {'date': '2016-11-20', 'value': 15.717391304347826},
 {'date': '2016-11-21', 'value': 21.439130434782612},
 {'date': '2016-11-22', 'value': 21.018181818181816},
 {'date': '2016-11-23', 'value': 28.12173913043478},
 {'date': '2016-11-24', 'value': 32.6},
 {'date': '2016-11-25', 'value': 28.763636363636362},
 {'date': '2016-11-26', 'value': 16.900000000000006},
 {'date': '2016-11-27', 'value': 8.295652173913044},
 {'date': '2016-11-28', 'value': 16.96521739130435},
 {'date': '2016-11-29', 'value': 15.069565217391306},
 {'date': '2016-11-30', 'value': 19.678260869565214},
 {'date': '2016-12-01', 'value': 26.74782608695652},
 {'date': '2016-12-02', 'value': 12.466666666666665},
 {'date': '2016-12-03', 'value': 10.134782608695653},
 {'date': '2016-12-04', 'value': 10.339130434782607},
 {'date': '2016-12-05', 'value': 19.039130434782606},
 {'date': '2016-12-06', 'value': 22.87826086956522},
 {'date': '2016-12-07', 'value': 22.082608695652173},
 {'date': '2016-12-08', 'value': 17.03913043478261},
 {'date': '2016-12-09', 'value': 19.97391304347826},
 {'date': '2016-12-10', 'value': 12.98181818181818},
 {'date': '2016-12-11', 'value': 12.01304347826087},
 {'date': '2016-12-12', 'value': 16.9},
 {'date': '2016-12-13', 'value': 23.582608695652176},
 {'date': '2016-12-14', 'value': 17.67391304347826},
 {'date': '2016-12-15', 'value': 21.04782608695652},
 {'date': '2016-12-16', 'value': 32.7304347826087},
 {'date': '2016-12-17', 'value': 23.952173913043474},
 {'date': '2016-12-18', 'value': 18.7},
 {'date': '2016-12-19', 'value': 22.330434782608698},
 {'date': '2016-12-20', 'value': 19.79565217391304},
 {'date': '2016-12-21', 'value': 25.85217391304348},
 {'date': '2016-12-22', 'value': 28.09130434782609},
 {'date': '2016-12-23', 'value': 23.656521739130437},
 {'date': '2016-12-24', 'value': 13.8},
 {'date': '2016-12-25', 'value': 7.627272727272729},
 {'date': '2016-12-26', 'value': 5.026086956521739},
 {'date': '2016-12-27', 'value': 5.582608695652173},
 {'date': '2016-12-28', 'value': 11.95217391304348},
 {'date': '2016-12-29', 'value': 19.48260869565217},
 {'date': '2016-12-30', 'value': 15.44347826086957},
 {'date': '2016-12-31', 'value': 18.152173913043477},
 {'date': '2017-01-01', 'value': 11.717391304347824},
 {'date': '2017-01-02', 'value': 14.308695652173911},
 {'date': '2017-01-03', 'value': 11.082608695652175},
 {'date': '2017-01-04', 'value': 7.447826086956522},
 {'date': '2017-01-05', 'value': 8.682608695652174},
 {'date': '2017-01-06', 'value': 3.8043478260869565},
 {'date': '2017-01-07', 'value': 16.01304347826087},
 {'date': '2017-01-08', 'value': 25.555555555555557},
 {'date': '2016-01-30', 'value': 13.186363636363636},
 {'date': '2016-01-31', 'value': 7.430434782608693},
 {'date': '2016-02-01', 'value': 9.765217391304349},
 {'date': '2016-02-02', 'value': 8.478260869565217},
 {'date': '2016-02-03', 'value': 8.23913043478261},
 {'date': '2016-02-04', 'value': 8.817391304347826},
 {'date': '2016-02-05', 'value': 8.965217391304346},
 {'date': '2016-02-06', 'value': 18.421739130434784},
 {'date': '2016-02-07', 'value': 12.717391304347826},
 {'date': '2016-02-08', 'value': 15.282608695652174},
 {'date': '2016-02-09', 'value': 11.469565217391303},
 {'date': '2016-02-10', 'value': 9.526086956521738},
 {'date': '2016-02-11', 'value': 10.13478260869565},
 {'date': '2016-02-12', 'value': 14.056521739130433},
 {'date': '2016-02-13', 'value': 15.021739130434785},
 {'date': '2016-02-14', 'value': 13.126086956521737},
 {'date': '2016-02-15', 'value': 19.356521739130436},
 {'date': '2016-02-16', 'value': 7.760869565217392},
 {'date': '2016-02-17', 'value': 11.556521739130433},
 {'date': '2016-02-18', 'value': 16.504347826086956},
 {'date': '2016-02-19', 'value': 11.86521739130435},
 {'date': '2016-02-20', 'value': 14.373913043478264},
 {'date': '2016-02-21', 'value': 9.169565217391305},
 {'date': '2016-02-22', 'value': 6.81304347826087},
 {'date': '2016-02-23', 'value': 10.217391304347828},
 {'date': '2016-02-24', 'value': 9.50869565217391},
 {'date': '2016-02-25', 'value': 12.808695652173913},
 {'date': '2016-02-26', 'value': 18.247826086956525},
 {'date': '2016-02-27', 'value': 22.539130434782606},
 {'date': '2016-02-28', 'value': 21.1},
 {'date': '2016-02-29', 'value': 11.031818181818183},
 {'date': '2016-03-01', 'value': 9.982608695652175},
 {'date': '2016-03-02', 'value': 16.76086956521739},
 {'date': '2016-03-03', 'value': 21.282608695652172},
 {'date': '2016-03-04', 'value': 18.12608695652174},
 {'date': '2016-03-05', 'value': 16.352173913043476},
 {'date': '2016-03-06', 'value': 12.247826086956524},
 {'date': '2016-03-07', 'value': 19.73913043478261},
 {'date': '2016-03-08', 'value': 12.239130434782611},
 {'date': '2016-03-09', 'value': 21.952173913043485},
 {'date': '2016-03-10', 'value': 9.191304347826089},
 {'date': '2016-03-11', 'value': 8.72608695652174},
 {'date': '2016-03-12', 'value': 7.760869565217392},
 {'date': '2016-03-13', 'value': 6.269565217391305},
 {'date': '2016-03-14', 'value': 10.214285714285714},
 {'date': '2016-03-15', 'value': 10.5125},
 {'date': '2016-03-16', 'value': 9.282608695652176},
 {'date': '2016-03-17', 'value': 12.334782608695651},
 {'date': '2016-03-18', 'value': 11.213043478260872},
 {'date': '2016-03-19', 'value': 6.926086956521738},
 {'date': '2016-03-20', 'value': 9.686956521739132},
 {'date': '2016-03-21', 'value': 10.56521739130435},
 {'date': '2016-03-22', 'value': 8.62608695652174},
 {'date': '2016-03-23', 'value': 12.256521739130436},
 {'date': '2016-03-24', 'value': 13.334782608695656},
 {'date': '2016-03-25', 'value': 22.495652173913037},
 {'date': '2016-03-26', 'value': 15.97826086956522},
 {'date': '2016-03-27', 'value': 13.204761904761906},
 {'date': '2016-03-28', 'value': 12.544444444444444},
 {'date': '2016-03-29', 'value': 15.65},
 {'date': '2016-03-30', 'value': 11.533333333333333},
 {'date': '2016-03-31', 'value': 13.0},
 {'date': '2016-04-01', 'value': 8.478260869565217},
 {'date': '2016-04-02', 'value': 9.034782608695652},
 {'date': '2016-04-03', 'value': 12.404545454545454},
 {'date': '2016-04-04', 'value': 19.360869565217396},
 {'date': '2016-04-05', 'value': 21.02608695652174},
 {'date': '2016-04-06', 'value': 20.92173913043478},
 {'date': '2016-04-07', 'value': 17.513043478260872},
 {'date': '2016-04-08', 'value': 11.191304347826089},
 {'date': '2016-04-09', 'value': 9.65217391304348},
 {'date': '2016-04-10', 'value': 8.791304347826088},
 {'date': '2016-04-11', 'value': 9.691304347826087},
 {'date': '2016-04-12', 'value': 12.604347826086956},
 {'date': '2016-04-13', 'value': 12.843478260869563},
 {'date': '2016-04-14', 'value': 10.730434782608697},
 {'date': '2016-04-15', 'value': 10.230434782608697},
 {'date': '2016-04-16', 'value': 12.830434782608695},
 {'date': '2016-04-17', 'value': 11.90434782608696},

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

poland_daily = (
    df_results.groupby("date")
              .agg(poland_no2_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

poland_daily

           date  france_no2_mean
0    2016-01-30        19.241126
1    2016-01-31        10.958281
2    2016-02-01        21.642411
3    2016-02-02        14.843302
4    2016-02-03        14.615613
...         ...              ...
3426 2026-02-24        12.267595
3427 2026-02-25        16.437960
3428 2026-02-26        19.552323
3429 2026-02-27        23.607157
3430 2026-02-28        21.105020

[3431 rows x 2 columns]

In [ ]:
poland_daily[["date", "poland_no2_mean"]].to_csv(
    "daily_avg_poland_NO2.csv",
    index=False
)